### ISSUE TITLE
AzureFileCopy throws if public ip address resource has null IpConfiguration

### ISSUE THREAD

**Issue by Iapmes** [Microsoft/vsts-tasks#1604]
There's an off chance (probably) that a public IP address can have a null IpConfiguration. (Returned by Get-AzureRMPublicIpAddress).

In that case the function Get-MachinesFqdnsForPublicIP will throw:

```
You cannot call a method on a null-valued expression.
At C:\Temp\vsts-tasks\...\Tasks\AzureFileCopy\Utility.ps1:501 char:17
+ ...             $fqdnMap[$publicIp.IpConfiguration.Id.ToLower()] =  $publ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : InvokeMethodOnNull

```

In my case this was not the public IP address for the destination VM for the copy task. The public IP that had a null IpConfiguration was "hanging" and orphaned and not connected to any network interface or any virtual machine (but belonged to the same resource group).

The VSTS release log file for the task would only contain sparse information with little value:

```
...
2016-04-28T19:06:56.0161981Z ##[debug][Azure Call]Got load balancers in resource group ######
2016-04-28T19:06:56.0341917Z ##[debug]Trying to get FQDN for the azureRM VM resources under public IP from resource Group ######
2016-04-28T19:06:56.0904971Z ##[debug]System.Management.Automation.RuntimeException: You cannot call a method on a null-valued expression.
2016-04-28T19:06:56.0904971Z    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
2016-04-28T19:06:56.0914910Z    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
2016-04-28T19:06:56.0914910Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2016-04-28T19:06:56.0924904Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2016-04-28T19:06:56.1268807Z ##[debug][Azure Call]Deleting container: 00ca24f4-42a9-4d1a-81c4-a2fac58a4bb2 in storage account: ###########
...
2016-04-28T19:06:56.2144383Z ##[error]System.Management.Automation.ParentContainsErrorRecordException: You cannot call a method on a null-valued expression.
```

The Public IP with a null IP configuration can probably be ignored when building the hashtable or at least a more informative exception should be thrown.

**Comment by KrishnaAdityaB** [comment]
@Iapmes 
#1760 was pushed towards fixing this. This will be available in next deployment which is around 4 weeks from now.

You can test this following these steps if you have a private agent
1. download the task from master branch
2. place it in appropriate folder under agents/tasks/AzureFileCopy/<version>

**Comment by pstricker** [comment]
Thanks for taking care of this! Surprised it even existed as it affects all Azure VMs behind a load balancer.

@KrishnaAdityaB Do you know when the release of this fix is scheduled exactly?
