### ISSUE TITLE
PowerShellOnTargetMachines fails when installing MSI

### ISSUE THREAD

**Issue by henning-krause** [Microsoft/vsts-tasks#1793]
I'm trying to install an MSI using the Release Management v.Next. Version is 2015, Update 2.1. Agent version is 1.95.1.

In my remote Powershell, I call Start-Process to execute msiexec.exe to install an MSI package. After that, I use select-string in a loop to wait until the MSI log states that the installation has finished. This script works fine when executed manually.

However, when I run this script using the ReleaseManagement Task PowerShellOnTargetMachines, the execution starts, the package is installed correctly, but the task fails. 

On the EventLog of the remote machine I see the VisualStudioRemoteDeployer crashing due to a NullReferenceException.

How can I troubleshoot this issue?

The logs are below:

Log from build.vNext:
``
2016-05-25T12:33:32.7913508Z ##[debug]Deployment logs for Deployment operation on mg-config226:5985 
2016-05-25T12:33:32.8023580Z ##[debug]Deployment aborted unexpectedly. This might be due to an unplanned restart of target machine. Consult the logs if any on the target machine to fix the issues and retry the operation.
2016-05-25T12:33:32.8063253Z ##[debug]Service logs for Deployment operation on mg-config226:5985 
2016-05-25T12:33:32.8083474Z ##[debug]RemoteDeployerSource Warning: 1221743 : [RemoteDeployer][25:Mai:16:14:33:30:7263; 2872, 4](MG-CONFIG226)Deployment machine went for an unplanned reboot
2016-05-25T12:33:32.8083474Z ource Verbose: 2 : [RemoteDeployer][25:Mai:16:14:32:35:7977; 2800, 4](MG-CONFIG226)Created public key for communication
2016-05-25T12:33:32.8093548Z RemoteDeployerSource Information: 12 : [RemoteDeployer][25:Mai:16:14:32:35:8132; 2800, 4](MG-CONFIG226)Deployment service - VisualStudioRemoteDeployerd56440e0-7908-4832-92de-50cbc725df91 is running...
2016-05-25T12:33:32.8103284Z RemoteDeployerSource Verbose: 4 : [RemoteDeployer][25:Mai:16:14:32:36:8483; 2800, 6](MG-CONFIG226)Input file found
2016-05-25T12:33:32.8103284Z RemoteDeployerSource Verbose: 5 : [RemoteDeployer][25:Mai:16:14:32:36:8483; 2800, 6](MG-CONFIG226)Reading input parameters
2016-05-25T12:33:32.8113247Z RemoteDeployerSource Verbose: 6 : [RemoteDeployer][25:Mai:16:14:32:36:8483; 2800, 6](MG-CONFIG226)Finished reading input parameters
2016-05-25T12:33:32.8173249Z Deployment status for machine 'mg-config226:5985' : 'Failed'
2016-05-25T12:33:32.8583806Z ##[error]You cannot call a method on a null-valued expression.
2016-05-25T12:33:32.8713499Z Finishing task: PowerShellOnTargetMachines
``

Log from remote powershell (C:\Windows\DtlDownloads\VisualStudioRemoteDeployerd56440e0-7908-4832-92de-50cbc725df91\deployment.log):
``
2016-05-25 14:32:40Z Waiting for the installation to start
2016-05-25 14:32:45Z Waiting for the installation to finish
2016-05-25 14:32:50Z Waiting for the installation to finish
2016-05-25 14:32:56Z Waiting for the installation to finish
2016-05-25 14:33:01Z Waiting for the installation to finish
2016-05-25 14:33:06Z Waiting for the installation to finish
2016-05-25 14:33:11Z Waiting for the installation to finish
2016-05-25 14:33:16Z Waiting for the installation to finish
2016-05-25 14:33:21Z Waiting for the installation to finish
2016-05-25 14:33:26Z Waiting for the installation to finish
2016-05-25 14:33:31Z Waiting for the installation to finish
2016-05-25 14:33:36Z Waiting for the installation to finish
2016-05-25 14:33:41Z Installation finished
2016-05-25 14:33:41Z Installation was successful
``

Eventlog entry (Time 14:33:41):

``
Application: VisualStudioRemoteDeployer.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.RemoteDeployerService.WriteResponseXMLFile(Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Interfaces.DeploymentResponse, Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Interfaces.IXmlSerializer)
   at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.RemoteDeployerService.Execute()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
``

**Comment by henning-krause** [comment]
After poking around a little bit with ADPlus and windbg, I saw this:

``
Logs and memory dumps will be placed in c:\temp\20160525_151032_Crash_Mode
Starting to monitor the following processes:
   VISUALSTUDIOREMOTEDEPLOYER.EXE
Press Enter to stop Monitoring...
Attaching to 3944 - VisualStudioRemoteDeployer in Crash mode 05/25/2016 15:11:08

Attaching to 2200 - VisualStudioRemoteDeployer in Crash mode 05/25/2016 15:12:31

Exited 2200 VisualStudioRemoteDeployer 05/25/2016 15:12:37
Exited 3944 VisualStudioRemoteDeployer 05/25/2016 15:13:01
`` 

The message about the unplanned restart probably comes from the fact that the first process crashes and the second one is created, finds some leftovers from the first process and thinks the machine has restarted. So that message is a little bit misleading...

**Comment by henning-krause** [comment]
Using windbg, I managed to find the cause for the NullReferenceException:

The class 
The class Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.RemoteDeployerService has a field deployerLogReader of type StreamReader. 
The method Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.RemoteDeployerService.WriteResponseXMLFile tries to perform a seek operation on said streamreader, by accessing the BaseStream property of the reader. But according to WindDBG, the stream field is null.

**Comment by codito** [comment]
@henning-krause thanks for the report. Can you please share the powershell script, debug log for the task and `C:\Windows\DtlDownloads\` directory on remote machine? (please email rm_customer_queries at microsoft domain)

**Comment by henning-krause** [comment]
@codito : Done

**Comment by henning-krause** [comment]
I found the root cause for this issue... We are running a PowerShell Cmdlet from a CustomAction in the Setup (PS-RegisterSessionConfiguration). This cmdlet restarts the WinRM service during execution which breaks the the connection between the build server and the deployment target.

Removing the custom action from the setup made the issue go away.

It would be great if the RM tools could fail with a better error message in this case though.
