### ISSUE TITLE
VSTest : cannot start UWP unit test

### ISSUE THREAD

**Issue by Guruumeditation** [Microsoft/vsts-tasks#1839]
Hi,

When I am launching unit testing of a UWP library, I always got an exception. (See stack trace below)
I created a Powershell script that launch vstest.console.exe, it crashes with the same exception also.

If I launch vastest.console.exe (or my powershell) manually, it works. But when it is launch by VSTS I got an exception.

I use VSTS, and a build machine (a VS2015 Azure VM).

Is it an issue, or am I missing something??

Cheers

Olivier

Application: vstest.console.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentNullException
   at Microsoft.VisualStudio.TestPlatform.ObjectModel.ValidateArg.NotNull[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.__Canon, System.String)
   at Microsoft.VisualStudio.TestPlatform.Client.LocalCrashDumpUtilities.TryGetLocalCrashDumpPath(System.String, System.String ByRef)
   at Microsoft.VisualStudio.TestPlatform.Client.TestExecutorServiceClient.TryGetLocalCrashDumpPath(System.String, System.String ByRef)
   at Microsoft.VisualStudio.TestPlatform.Client.TestExecutorServiceClient.GetTestRunAbortedMessage(System.String, Int32, Boolean, Boolean)
   at Microsoft.VisualStudio.TestPlatform.Client.TestExecutorServiceClient.TestExecutorServiceChannel_Reset(System.Object, System.EventArgs)
   at System.ServiceModel.Channels.CommunicationObject.OnClosed()

Exception Info: System.Runtime.CallbackException
   at System.ServiceModel.Channels.CommunicationObject.OnClosed()
   at System.ServiceModel.ServiceHostBase.OnClosed()
   at System.ServiceModel.ServiceHost.OnClosed()
   at System.ServiceModel.Channels.CommunicationObject.Close(System.TimeSpan)
   at Microsoft.VisualStudio.TestPlatform.Client.UniversalTestExecutorProxy.Close()
   at Microsoft.VisualStudio.TestPlatform.Client.TestExecutorServiceClient.StarPlatformSpecificTestExecution(Microsoft.VisualStudio.TestPlatform.Client.IPlatformTestExecutorClient, Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.ITestExecutorLauncher, Microsoft.VisualStudio.TestPlatform.ObjectModel.Architecture, Microsoft.VisualStudio.TestPlatform.ObjectModel.FrameworkVersion)
   at Microsoft.VisualStudio.TestPlatform.Client.TestExecutorServiceClient.Initialize_NoLock(Microsoft.VisualStudio.TestPlatform.ObjectModel.Architecture, Microsoft.VisualStudio.TestPlatform.ObjectModel.FrameworkVersion)
   at Microsoft.VisualStudio.TestPlatform.Client.TestExecutorServiceClient.EnsureInitialized(System.Collections.Generic.IDictionary`2<System.String,System.String>, Microsoft.VisualStudio.TestPlatform.Core.TestExecutionContext)
   at Microsoft.VisualStudio.TestPlatform.Client.TestExecutorServiceClient+<>c__DisplayClass18_0.<StartTestRun>b__0()
   at Microsoft.VisualStudio.TestPlatform.Client.TestExecutorServiceClient.InvokeTestExecutorServiceAction(System.Action)
   at Microsoft.VisualStudio.TestPlatform.Client.TestExecutorServiceClient.StartTestRun(System.Collections.Generic.IEnumerable`1<System.String>, Microsoft.VisualStudio.TestPlatform.Core.TestExecutionContext, System.String, System.Collections.Generic.IDictionary`2<System.String,System.String>, System.String, Microsoft.VisualStudio.TestPlatform.Core.ITestCaseLog, Microsoft.VisualStudio.TestPlatform.Core.ITestRunLog, Microsoft.VisualStudio.TestPlatform.Core.IFrameworkHandleInternal)
   at Microsoft.VisualStudio.TestPlatform.Client.Rocksteady.RocksteadyExecutionManager.StartTestRun(Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.TestRunCriteria, Boolean, Microsoft.VisualStudio.TestPlatform.Client.DataCollectionParameters, Microsoft.VisualStudio.TestPlatform.Client.ITestRunEventsHandler)
   at Microsoft.VisualStudio.TestPlatform.Client.TestRunRequest.ExecuteAsync()
   at Microsoft.VisualStudio.TestPlatform.CommandLine.Processors.RunTestsArgumentProcessor.RunTests(System.Collections.Generic.IEnumerable`1<System.String>, System.String, System.String, Boolean, Boolean)
   at Microsoft.VisualStudio.TestPlatform.CommandLine.Processors.RunTestsArgumentProcessor.ExecuteAppContainerSources(System.Collections.Generic.List`1<System.String>, System.String, Boolean)
   at Microsoft.VisualStudio.TestPlatform.CommandLine.Processors.RunTestsArgumentProcessor.Execute()
   at Microsoft.VisualStudio.TestPlatform.CommandLine.Executor.Execute(System.String[])
   at RockSteady.Program.Main(System.String[])

**Comment by atinb** [comment]
Are you running the Build agent as a service or as an interactive process? The latter is required for UWP tests to run. Thanks!

**Comment by Guruumeditation** [comment]
Hi,

I run as interactive. I am logged on my VM and I launched the “runagent.cmd”

De : Atin Bansal [mailto:notifications@github.com]
Envoyé : lundi 6 juin 2016 13:27
À : Microsoft/vsts-tasks <vsts-tasks@noreply.github.com>
Cc : Olivier Matis <olivier.matis@arcanastudio.net>; Author <author@noreply.github.com>
Objet : Re: [Microsoft/vsts-tasks] VSTest : cannot start UWP unit test (#1839)


Are you running the Build agent as a service or as an interactive process? The latter is required for UWP tests to run. Thanks!

**Comment by mtaron** [comment]
I am hitting the same thing.

**Comment by kaadhina** [comment]
Can you please try running the build agent using non-admin credentials?
UWP tests cannot be run as admin.

**Comment by mtaron** [comment]
Running the agent as non-admin worked! Thanks very much. :)
