### ISSUE TITLE
IllegalStateException in Sonar task

### ISSUE THREAD

**Issue by pascalberger** [Microsoft/vsts-tasks#1842]
I recently switched to building a solution with VS2015 which not throws this exception in the post step:

```
2016-06-07T09:47:36.1321589Z ##[error]ERROR: Error during Sonar runner execution
2016-06-07T09:47:36.1321589Z ##[error]org.sonar.runner.impl.RunnerException: Unable to execute Sonar
2016-06-07T09:47:36.1321589Z ##[error]at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:91)
2016-06-07T09:47:36.1321589Z ##[error]at org.sonar.runner.impl.BatchLauncher$1.run(BatchLauncher.java:75)
2016-06-07T09:47:36.1321589Z ##[error]at java.security.AccessController.doPrivileged(Native Method)
2016-06-07T09:47:36.1321589Z ##[error]at org.sonar.runner.impl.BatchLauncher.doExecute(BatchLauncher.java:69)
2016-06-07T09:47:36.1321589Z ##[error]at org.sonar.runner.impl.BatchLauncher.execute(BatchLauncher.java:50)
2016-06-07T09:47:36.1321589Z ##[error]at org.sonar.runner.api.EmbeddedRunner.doExecute(EmbeddedRunner.java:102)
2016-06-07T09:47:36.1321589Z ##[error]at org.sonar.runner.api.Runner.execute(Runner.java:100)
2016-06-07T09:47:36.1321589Z ##[error]at org.sonar.runner.Main.executeTask(Main.java:70)
2016-06-07T09:47:36.1321589Z ##[error]at org.sonar.runner.Main.execute(Main.java:59)
2016-06-07T09:47:36.1321589Z ##[error]at org.sonar.runner.Main.main(Main.java:53)
2016-06-07T09:47:36.1321589Z ##[error]Caused by: java.lang.IllegalStateException: Can't create measure for line 31 for file 'D:/BuildAgentTest/_work/1/s/MyFile.cs' with 30 lines
2016-06-07T09:47:36.1321589Z ##[error]at org.sonar.batch.sensor.coverage.CoverageExclusions.validateMaxLine(CoverageExclusions.java:158)
2016-06-07T09:47:36.1477859Z ##[error]at org.sonar.batch.sensor.coverage.CoverageExclusions.validate(CoverageExclusions.java:129)
2016-06-07T09:47:36.1477859Z ##[error]at org.sonar.batch.deprecated.DeprecatedSensorContext.saveMeasure(DeprecatedSensorContext.java:205)
2016-06-07T09:47:36.1477859Z ##[error]at org.sonar.plugins.dotnet.tests.CoverageReportImportSensor.analyze(CoverageReportImportSensor.java:103)
2016-06-07T09:47:36.1477859Z ##[error]at org.sonar.plugins.dotnet.tests.CoverageReportImportSensor.analyse(CoverageReportImportSensor.java:74)
2016-06-07T09:47:36.1477859Z ##[error]at org.sonar.batch.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:58)
2016-06-07T09:47:36.1477859Z ##[error]at org.sonar.batch.phases.SensorsExecutor.execute(SensorsExecutor.java:50)
2016-06-07T09:47:36.1477859Z ##[error]at org.sonar.batch.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:83)
2016-06-07T09:47:36.1477859Z ##[error]at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:192)
2016-06-07T09:47:36.1477859Z ##[error]at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
2016-06-07T09:47:36.1477859Z ##[error]at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
2016-06-07T09:47:36.1477859Z ##[error]at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:241)
2016-06-07T09:47:36.1477859Z ##[error]at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:236)
2016-06-07T09:47:36.1477859Z ##[error]at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:234)
2016-06-07T09:47:36.1477859Z ##[error]at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:226)
2016-06-07T09:47:36.1477859Z ##[error]at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
2016-06-07T09:47:36.1477859Z ##[error]at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
2016-06-07T09:47:36.1477859Z ##[error]at org.sonar.batch.task.ScanTask.execute(ScanTask.java:47)
2016-06-07T09:47:36.1477859Z ##[error]at org.sonar.batch.task.TaskContainer.doAfterStart(TaskContainer.java:86)
2016-06-07T09:47:36.1634096Z ##[error]at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
2016-06-07T09:47:36.1634096Z ##[error]at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
2016-06-07T09:47:36.1634096Z ##[error]at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:106)
2016-06-07T09:47:36.1634096Z ##[error]at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:119)
2016-06-07T09:47:36.1634096Z ##[error]at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:79)
2016-06-07T09:47:36.1634096Z ##[error]at org.sonar.runner.batch.IsolatedLauncher.execute(IsolatedLauncher.java:48)
2016-06-07T09:47:36.1634096Z ##[error]at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2016-06-07T09:47:36.1634096Z ##[error]at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2016-06-07T09:47:36.1634096Z ##[error]at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2016-06-07T09:47:36.1634096Z ##[error]at java.lang.reflect.Method.invoke(Unknown Source)
2016-06-07T09:47:36.1634096Z ##[error]at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:87)
2016-06-07T09:47:36.1634096Z ##[error]... 9 more
2016-06-07T09:47:36.1634096Z ##[error]ERROR:
2016-06-07T09:47:36.1634096Z ##[error]ERROR: Re-run SonarQube Runner using the -X switch to enable full debug logging.
2016-06-07T09:47:36.1634096Z ##[error]The SonarQube Scanner did not complete successfully
```

There was no code change involved, just building on a different agent which has VS2015 instead of VS2013 installed. There are certainly issues in the mentioned file. Any idea what might be the cause of it finding a issue on a non-existant line?

**Comment by bgavrilMS** [comment]
Hi Pascal, 

Looks like this is a bug in the SonarQube Scanner for MsBuild or in the plugin that handles the code coverage processing. You could try to disable code coverage generation until it's fixed. 

I found that other people report it as well: http://stackoverflow.com/questions/35652047/sonarqube-cant-create-measure-for-line-x-for-file-with-file-with-x-lines - sadly this thread is 3 months old. I'll ping my contacts in SonarSource to see if I can speed things up. 

In the mean time, could you clarify what version of SQ and what version of the C# plugin you are using?

**Comment by pascalberger** [comment]
Thanks @bgavrilMS. 

Versions are latest (Sonar 5.6 and C# Plugin 5.2).

**Comment by pascalberger** [comment]
@bgavrilMS Do you know what exactly I need to disable to workaround this issue? I tried to exclude **/* for code coverage in the analysis scope, but error still occurs.

**Comment by bgavrilMS** [comment]
I haven't actually reproed this yet. Could you try to disable Code Coverage altogether? If no code coverage file is produced, that code path will not be activated. 

Btw - what do you use to produce code coverage? Is it the Visual Studio Test task ?

**Comment by pascalberger** [comment]
Ah, I understood that I should disable coverage in Sonar :) 

Yes, a Visual Studio Test task is in this build definition. If I disable code coverage there it works.

**Comment by bgavrilMS** [comment]
Hi Pascal, 

We investigated and found that this problem is related to the code coverage tool shipped with VS 2015. We contacted the VS test team and they should have a fix in VS 2015 Update 3.
