### ISSUE TITLE
Nuget installer fails

### ISSUE THREAD

**Issue by sergeyzwezdin** [Microsoft/vsts-tasks#1903]
Some days ago nuget task started to fail during build with following error:

```
Set workingFolder to default: C:\Agent\tasks\NuGetInstaller\0.1.30
Executing the powershell script: C:\Agent\tasks\NuGetInstaller\0.1.30\NuGetInstaller.ps1
C:\Agent\agent\worker\tools\NuGet.exe restore "c:\a\3\s\src\test\test.sln"  -NonInteractive
MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'.
TODO: unknown keyword platform
System.Exception: Unexpected exit code 1 returned from tool NuGet.exe
at Microsoft.TeamFoundation.DistributedTask.Task.Internal.PowerShell.InvokeToolCmdlet.ProcessRecord()
at System.Management.Automation.CommandProcessor.ProcessRecord()
```

.sln file didn't changed. Any ideas what happened with this task?

**Comment by sergeyzwezdin** [comment]
Something broken at nuget.exe
https://github.com/NuGet/Home/issues/3001

**Comment by zeus82** [comment]
I just started getting this error today:

2016-10-26T00:07:24.4681508Z ##[error]Error: C:\a\_tasks\NuGetInstaller_333b11bd-d341-40d9-afcf-b32d5ce6f23b\0.2.22\node_modules\nuget-task-common\NuGet\3.3.0\NuGet.exe failed with return code: 1
2016-10-26T00:07:24.4681508Z ##[error]Packages failed to install

I think its related.
