### ISSUE TITLE
Sometimes exception loading assembly when running VSO online build in Run Functional Tests step

### ISSUE THREAD

**Issue by Jerry06** [Microsoft/vsts-tasks#1951]
Hi,
I have a sometime issue when running build on VSO online in the Run Functional Tests step.
Run 10 times this issue happened about 3-4 times
I found the exception in DTAExecutionHost.exe log file when loading DLL.
The full log in attached file.
Thank you for any help.
 
`E, 10504, 18, 2016/06/24, 13:28:24.285, 291767473089, DTAExecutionHost.exe, TAEF Engine Execution: System.IO.FileNotFoundException: Could not load file or assembly 'LogiGear.TestArchitect.TAIntegrationLoader, Version=3.0.50.0, Culture=neutral, PublicKeyToken=12834fd652593218' or one of its dependencies. The system cannot find the file specified.
File name: 'LogiGear.TestArchitect.TAIntegrationLoader, Version=3.0.50.0, Culture=neutral, PublicKeyToken=12834fd652593218'
   at System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
   at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
   at System.Reflection.CustomAttribute.IsCustomAttributeDefined(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Int32 attributeCtorToken, Boolean mustBeInheritable)
   at System.Reflection.CustomAttribute.IsDefined(RuntimeMethodInfo method, RuntimeType caType, Boolean inherit)
   at System.Reflection.RuntimeMethodInfo.IsDefined(Type attributeType, Boolean inherit)
   at Microsoft.VisualStudio.TestPlatform.MSTestFramework.ReflectHelper.IsAttributeDefined(MemberInfo memberInfo, Type attributeType, Boolean inherit)
   at Microsoft.VisualStudio.TestPlatform.MSTestFramework.TypeCache.UpdateInfoIfAssemblyInitializeMethod(TestAssemblyInfo assemblyInfo, MethodInfo methodInfo, Type assemblyInitializeType)
   at Microsoft.VisualStudio.TestPlatform.MSTestFramework.TypeCache.GetAssemblyInfo(Type type)
   at Microsoft.VisualStudio.TestPlatform.MSTestFramework.TypeCache.CreateClassInfo(Type classType, TestMethod testMethod)
   at Microsoft.VisualStudio.TestPlatform.MSTestFramework.TypeCache.GetClassInfo(TestMethod testMethod)
   at Microsoft.VisualStudio.TestPlatform.MSTestFramework.TypeCache.GetTestMethodInfo(TestMethod testMethod, Boolean isDataSource, TestContextImplementation testContext)
   at Microsoft.VisualStudio.TestPlatform.MSTestFramework.UnitTestRunner.RunInternal(TestMethod testMethod, Boolean isDataDriven, Dictionary`2 runParameters)
   at Microsoft.VisualStudio.TestPlatform.MSTestFramework.UnitTestRunner.RunSingleTest(String name, String fullClassName, Boolean isAsync, Dictionary`2 runParameters)
   at Microsoft.VisualStudio.TestPlatform.MSTestFramework.UnitTestRunner.RunSingleTest(String name, String fullClassName, Boolean isAsync, Dictionary`2 runParameters)
   at Microsoft.VisualStudio.TestPlatform.Extensions.VSTestIntegration.MixedModeExecutor.ExecuteTests(IEnumerable`1 tests, IRunContext runContext, ITestExecutionRecorder testExecutionRecorder, UnitTestRunner testRunner, TmiTestRun tmiTestRun)
   at Microsoft.VisualStudio.TestPlatform.Extensions.VSTestIntegration.MixedModeExecutor.ExecuteDurontoTestsInternal(IEnumerable`1 tests, IRunContext runContext, ITestExecutionRecorder testExecutionRecorder, String source, TestRunDirectories runDirectories, TmiTestRun tmiTestRun)
   at Microsoft.VisualStudio.TestPlatform.Extensions.VSTestIntegration.MixedModeExecutor.ExecuteDurontoTests(IEnumerable`1 tests, IRunContext runContext, IFrameworkHandle frameworkHandle, String source, TestRunDirectories runDirectories, TmiTestRun tmiTestRun)
   at Microsoft.VisualStudio.TestPlatform.Extensions.VSTestIntegration.MixedModeExecutor.ExecuteTests(IEnumerable`1 tests, IRunContext runContext, IFrameworkHandle frameworkHandle, TestRunDirectories runDirectories, Boolean isDeploymentDone, String source)
   at Microsoft.VisualStudio.TestPlatform.Extensions.VSTestIntegration.MixedModeExecutor.ExecuteTests(IEnumerable`1 tests, IRunContext runContext, IFrameworkHandle frameworkHandle, TestRunDirectories runDirectories, Boolean isDeploymentDone)
   at Microsoft.VisualStudio.TestPlatform.Extensions.VSTestIntegration.MixedModeExecutor.RunTests(IEnumerable`1 tests, IRunContext runContext, IFrameworkHandle frameworkHandle, TestRunCancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestPlatform.Extensions.VSTestIntegration.MSTestExecutor.RunTests(IEnumerable`1 tests, IRunContext runContext, IFrameworkHandle frameworkHandle)
   at WEX.TestExecution.ExecutionPlugin.ExecuteTests(IntPtr context, IntPtr logSessionPtr, IDictionary`2 rockSteadySettings)
   at WEX.TestExecution.InteropMethods.ExecuteTests(String[] rockSteadySettings, Int32 rockSteadySettingsSize, IntPtr context, IntPtr logSessionPtr)

![build error](https://cloud.githubusercontent.com/assets/15416971/16335213/a70ca2e4-3a2f-11e6-8b8a-b0fb12774b2c.jpg)

[DTAExecutionHost.exe - Log.txt](https://github.com/Microsoft/vsts-tasks/files/331576/DTAExecutionHost.exe.-.Log.txt)

**Comment by atinb** [comment]
@Jerry06 
Is 'LogiGear.TestArchitect.TAIntegrationLoader' your dll? It seems like it is missing on the machines. Are the deployment/copy steps running properly?
Thanks!

**Comment by Jerry06** [comment]
Yes it is my dll, you can see my attached picture, i have 4 steps :
1. Build solution
2. Copy file
3. Deploy test agent
4. Run function test 
Step 1,2,3 success but failed in step 4
This is sometimes not always.

**Comment by atinb** [comment]
Looks like you have set up your own agent. When you see the error, can you check to see if the file is present and accessible? Maybe call into vstest.console.exe with the file name and see what happens. Thanks!

**Comment by Jerry06** [comment]
Thanks for your reply
After running failed, i have run with vstest.console.exe and it passed as attached image 
![run_vstest console](https://cloud.githubusercontent.com/assets/15416971/16368693/4c41512e-3c5b-11e6-8443-299d83dffce2.jpg)
So i am thinking issue happened from DTAExecutionHost.exe?

**Comment by Jerry06** [comment]
Hi @atinb , @nigurr , do you have any update for this issue or any work around solution ?

**Comment by nigurr** [comment]
Can you please attach the DTAExecution Host log? Please remove previous logs from it.

**Comment by Jerry06** [comment]
hi @nigurr , this is my new log 
[DTAExecutionHost.exe - Copy.log.txt](https://github.com/Microsoft/vsts-tasks/files/346055/DTAExecutionHost.exe.-.Copy.log.txt)

**Comment by nigurr** [comment]
From the logs, 

`2016/07/04, 16:59:21.868, 918160146020, DTAExecutionHost.exe, TAEF Engine Execution: System.IO.FileNotFoundException: Could not load file or assembly 'LogiGear.TestArchitect.TAIntegrationLoader, Version=3.0.50.0, Culture=neutral, PublicKeyToken=12834fd652593218' or one of its dependencies. The system cannot find the file specified.`

One of the dependent DLLs or Test related DLLs are missing. Please copy all required DLLs to test machines

**Comment by Jerry06** [comment]
I checked, the TAIntegrationLoader is existed, and TAIntegrationLoader is not depend related DLL, 
btw running with vstest.console.exe the test is passed, you can see image in previous post.
Any more details i need to provide ?
Thanks,

**Comment by nigurr** [comment]
Can you share your Build config?

**Comment by Jerry06** [comment]
As below:
![deploy test agent](https://cloud.githubusercontent.com/assets/15416971/16560321/d642551e-421c-11e6-8aa8-956de79d5370.jpg)
![run test](https://cloud.githubusercontent.com/assets/15416971/16560323/d7cfe914-421c-11e6-8651-a727bca8c456.jpg)

**Comment by nigurr** [comment]
Hi,

From the logs, we can observe one thing, the Test filter you have applied is loading `C:\test\Viet1\obj\Release\Viet1.dll` too. This is where the loading of dependent DLL is failing.
You are running VsTest against `bin` folder, where dependent DLL might be existing.

Can you change your `Run Functional Task` definition to run `tests under bin folder only`

**Comment by Jerry06** [comment]
I will change to bin folder and try again. But the filter "-\obj\**" is not exclude obj folder?
i used  -\obj\** filter in https://www.visualstudio.com/en-us/docs/build/steps/test/run-functional-tests

**Comment by Jerry06** [comment]
Thank for your reply,
After i changed to _bin_ folder, this issue did not happen.
But if i am using drop location _C:\test_, how to filter exclude all _obj_ folders ?
Both  _-\obj\*_*  and  _-**\obj\**_ did not work

**Comment by nigurr** [comment]
Hi,

It's documentation defect, we will be fixing that. Currently we don't support exclude functionality in run functional tests.
You can use "Copy File" task to copy the required DLLs from bin folder to test folder which supports exclude/include functionality.

**Comment by thuongngo85** [comment]
Hi,
 After followed up your guide, this issue above was resolved. But we're facing another issue is that: all build steps in the build definition was completed but the vNext build shows the error message "The job running on agent has exceeded the maximum execution time". You can refer to the picture below for more detail:
![cleanup_task_hang](https://cloud.githubusercontent.com/assets/2087533/18121296/144e74b6-6f8e-11e6-9266-314bd3bd1ebd.PNG)

In additional information, our test suite is small and this issue happens when we queued build in more than 10 times.
 Could you please take a look on this issue?
