### ISSUE TITLE
PublishBuildArtifacts doesn't work with URN publish locations

### ISSUE THREAD

**Issue by dsoprea** [Microsoft/vsts-tasks#1964]
I have provided a URN/fileshare location to push artifacts to (using backslashes). The publish breaks down:

```
******************************************************************************
Starting task: Publish Artifacts
******************************************************************************
Set workingFolder to default: D:\Agents\A2\tasks\PublishBuildArtifacts\1.0.27
shell.js: internal error
RangeError: Maximum call stack size exceeded
    at RegExp.exec (native)
    at win32SplitPath (path.js:95:29)
    at Object.win32.dirname (path.js:331:16)
    at mkdirSyncRecursive (D:\Agents\A2\tasks\PublishBuildArtifacts\1.0.27\node_modules\shelljs\src\mkdir.js:7:22)
    at mkdirSyncRecursive (D:\Agents\A2\tasks\PublishBuildArtifacts\1.0.27\node_modules\shelljs\src\mkdir.js:18:3)
    at mkdirSyncRecursive (D:\Agents\A2\tasks\PublishBuildArtifacts\1.0.27\node_modules\shelljs\src\mkdir.js:18:3)
    at mkdirSyncRecursive (D:\Agents\A2\tasks\PublishBuildArtifacts\1.0.27\node_modules\shelljs\src\mkdir.js:18:3)
    at mkdirSyncRecursive (D:\Agents\A2\tasks\PublishBuildArtifacts\1.0.27\node_modules\shelljs\src\mkdir.js:18:3)
    at mkdirSyncRecursive (D:\Agents\A2\tasks\PublishBuildArtifacts\1.0.27\node_modules\shelljs\src\mkdir.js:18:3)
    at mkdirSyncRecursive (D:\Agents\A2\tasks\PublishBuildArtifacts\1.0.27\node_modules\shelljs\src\mkdir.js:18:3)
******************************************************************************
Finishing task: PublishBuildArtifacts
******************************************************************************
```

I placed some debug statements in mkdir.js (as well as stripping the trailing slash in case that was a problem:

```js
function mkdirSyncRecursive(dir) {
  // Dustin: We appear to have problems with a trailing slash in this version.

  l = dir.length;
  if(dir[l - 1] == "\\") {
	  dir = dir.substring(0, l - 1)
  }
	
  console.log("mkdirSyncRecursive 1: " + dir)
  var baseDir = path.dirname(dir);
  console.log("mkdirSyncRecursive 2: " + baseDir)

  // Base dir exists, no recursion necessary
  if (fs.existsSync(baseDir)) {
    fs.mkdirSync(dir, parseInt('0777', 8));
    return;
  }

  console.log("mkdirSyncRecursive 3: " + dir)

  // Base dir does not exist, go recursive
  mkdirSyncRecursive(baseDir);

  console.log("mkdirSyncRecursive 4: " + dir)
  
  // Base dir created, can create dir
  fs.mkdirSync(dir, parseInt('0777', 8));
}
```

The output indicates that we're looping endlessly:

```
2016-06-27T17:55:51.4563969Z ##[debug]TargetPath=\\file_share\BuildArchive\Product_Name.F1.Dev
2016-06-27T17:55:51.4563969Z ##[debug]creating path: \\file_share\BuildArchive\Product_Name.F1.Dev\20160627.15
2016-06-27T17:55:51.4563969Z mkdirSyncRecursive 1: \\file_share\BuildArchive\Product_Name.F1.Dev\20160627.15
2016-06-27T17:55:51.4563969Z mkdirSyncRecursive 2: \\file_share\BuildArchive\Product_Name.F1.Dev
2016-06-27T17:55:51.4720119Z mkdirSyncRecursive 3: \\file_share\BuildArchive\Product_Name.F1.Dev\20160627.15
2016-06-27T17:55:51.4720119Z mkdirSyncRecursive 1: \\file_share\BuildArchive\Product_Name.F1.Dev
2016-06-27T17:55:51.4720119Z mkdirSyncRecursive 2: \\file_share\BuildArchive\
2016-06-27T17:55:51.4720119Z mkdirSyncRecursive 3: \\file_share\BuildArchive\Product_Name.F1.Dev
2016-06-27T17:55:51.4720119Z mkdirSyncRecursive 1: \\file_share\BuildArchive
2016-06-27T17:55:51.4720119Z mkdirSyncRecursive 2: \\file_share\BuildArchive
2016-06-27T17:55:51.4720119Z mkdirSyncRecursive 3: \\file_share\BuildArchive
2016-06-27T17:55:51.4720119Z mkdirSyncRecursive 1: \\file_share\BuildArchive
2016-06-27T17:55:51.4720119Z mkdirSyncRecursive 2: \\file_share\BuildArchive
2016-06-27T17:55:51.4876441Z mkdirSyncRecursive 3: \\file_share\BuildArchive
2016-06-27T17:55:51.4876441Z mkdirSyncRecursive 1: \\file_share\BuildArchive
2016-06-27T17:55:51.4876441Z mkdirSyncRecursive 2: \\file_share\BuildArchive
2016-06-27T17:55:51.4876441Z mkdirSyncRecursive 3: \\file_share\BuildArchive
2016-06-27T17:55:51.4876441Z mkdirSyncRecursive 1: \\file_share\BuildArchive
2016-06-27T17:55:51.4876441Z mkdirSyncRecursive 2: \\file_share\BuildArchive
2016-06-27T17:55:51.4876441Z mkdirSyncRecursive 3: \\file_share\BuildArchive
2016-06-27T17:55:51.4876441Z mkdirSyncRecursive 1: \\file_share\BuildArchive
2016-06-27T17:55:51.5032607Z mkdirSyncRecursive 2: \\file_share\BuildArchive
2016-06-27T17:55:51.5032607Z mkdirSyncRecursive 3: \\file_share\BuildArchive
2016-06-27T17:55:51.5032607Z mkdirSyncRecursive 1: \\file_share\BuildArchive
2016-06-27T17:55:51.5032607Z mkdirSyncRecursive 2: \\file_share\BuildArchive
2016-06-27T17:55:51.5032607Z mkdirSyncRecursive 3: \\file_share\BuildArchive
2016-06-27T17:55:51.5032607Z mkdirSyncRecursive 1: \\file_share\BuildArchive
```

So, I tested in a Node.js console:

```js
var path = require('path');
console.log(path.dirname("//a/b/"))
console.log(path.basename("//a/b/"))
console.log(path.dirname("\\\\a\\b\\"))
console.log(path.basename("\\\\a\\b\\"))
```

Output:

```
//a
b/
.
\\a\b\
```

Notice that, if a URN is passed to `path.dirname()`, it essentially returns exactly what it was given. This makes `mkdirSyncRecursive()` loop forever. The poor-man's fix would be to map the URN to a local drive. The slightly longer-term fix would be to convert the backward-slashes to forward-slashes before the call and convert back afterwards, and the proper fix would be to handle URNs on Node.js' end. Even then, it'd have to propagate into whatever version of Node.js that TFS uses. I posted an issue there, as well: https://github.com/nodejs/node/issues/7447

It seems like this would sabotage most Windows-based publish operations. I can't be the first one noticing this. Hopefully someone can share the fix/reason for this and it's just something that I'm overlooking.

**Comment by dsoprea** [comment]
For further reference, using the 0.12.7 version with TFS:

```
> var path = require('path');
undefined
> console.log(path.dirname("//a/b/"))
//a/b/
undefined
> console.log(path.basename("//a/b/"))

undefined
> console.log(path.dirname("\\\\a\\b\\"))
\\a\b\
undefined
> console.log(path.basename("\\\\a\\b\\"))

undefined
> console.log(path.basename("\\\\a\\b"))

undefined
> console.log(path.basename("//a/b"))

undefined
> process.version
'v0.12.7'
```

Using the 4.4.3 version on my Windows desktop:

```
> var path = require('path');
undefined
> console.log(path.dirname("//a/b/"))
//a/b/
undefined
> console.log(path.basename("//a/b/"))

undefined
> console.log(path.dirname("\\\\a\\b\\"))
\\a\b\
undefined
> console.log(path.basename("\\\\a\\b\\"))

undefined
```

Using the Win32-compatibility layer doesn't make a difference:

```
> console.log(path.win32.dirname("//a/b/"))
//a/b/
undefined
> console.log(path.win32.basename("//a/b/"))

undefined
> console.log(path.win32.dirname("\\\\a\\b\\"))
\\a\b\
undefined
> console.log(path.win32.basename("\\\\a\\b\\"))

undefined
> process.version
'v4.4.3'
```

**Comment by dsoprea** [comment]
Closing. This is a shelljs/node thing that's, in any case, irrelevant here.
