### ISSUE TITLE
Azure File Copy: System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'storageKey' because it is an empty string.

### ISSUE THREAD

**Issue by AHoran** [Microsoft/vsts-tasks#1966]
TFS 2013 U 3

Was working in Update 2.

I'm trying to copy files up to a VM during my deployment I've not changed or modified the task since it worked in Update 2.

Detail from Logs below. I have tested the storage account name and the keys from the log and they work fine.
```
2016-06-28T02:57:34.9320997Z ##[debug]============================ HTTP RESPONSE ============================
2016-06-28T02:57:34.9320997Z Status Code:
2016-06-28T02:57:34.9320997Z OK
2016-06-28T02:57:34.9320997Z Headers:
2016-06-28T02:57:34.9320997Z Pragma                        : no-cache
2016-06-28T02:57:34.9320997Z x-ms-request-id               : cda6a734-5bad-49a6-9119-a12357fcc2ee
2016-06-28T02:57:34.9320997Z Cache-Control                 : no-cache
2016-06-28T02:57:34.9320997Z Server                        : Microsoft-Azure-Storage-Resource-Provider/1.0,Microsoft-HTTPAPI/2.0
2016-06-28T02:57:34.9320997Z x-ms-ratelimit-remaining-subscription-writes: 1197
2016-06-28T02:57:34.9320997Z x-ms-correlation-request-id   : cda6a734-5bad-49a6-9119-a12357fcc2ee
2016-06-28T02:57:34.9320997Z x-ms-routing-request-id       : AUSTRALIAEAST:20160628T025734Z:cda6a734-5bad-49a6-9119-a12357fcc2ee
2016-06-28T02:57:34.9320997Z Strict-Transport-Security     : max-age=31536000; includeSubDomains
2016-06-28T02:57:34.9320997Z Date                          : Tue, 28 Jun 2016 02:57:33 GMT
2016-06-28T02:57:34.9320997Z Connection                    : close
2016-06-28T02:57:34.9477003Z Body:
2016-06-28T02:57:34.9477003Z {
2016-06-28T02:57:34.9477003Z   "keys": [
2016-06-28T02:57:34.9477003Z     {
2016-06-28T02:57:34.9477003Z       "keyName": "key1",
2016-06-28T02:57:34.9477003Z       "permissions": "Full",
2016-06-28T02:57:34.9477003Z       "value": "ThisWasAValidKey1=="
2016-06-28T02:57:34.9477003Z     },
2016-06-28T02:57:34.9477003Z     {
2016-06-28T02:57:34.9477003Z       "keyName": "key2",
2016-06-28T02:57:34.9477003Z       "permissions": "Full",
2016-06-28T02:57:34.9477003Z       "value": "ThisWasAValidKey2=="
2016-06-28T02:57:34.9477003Z     }
2016-06-28T02:57:34.9477003Z   ]
2016-06-28T02:57:34.9477003Z }
2016-06-28T02:57:34.9477003Z ##[debug]AzureQoSEvent: CommandName - Get-AzureRmStorageAccountKey; IsSuccess - True; Duration - 00:00:00.6117927; Exception - ;
2016-06-28T02:57:35.7589315Z ##[debug]Finish sending metric.
2016-06-28T02:57:35.7589315Z ##[debug]12:57:35 PM - GetAzureStorageAccountKeyCommand end processing.
2016-06-28T02:57:35.7589315Z ##[debug]12:57:35 PM - GetAzureStorageAccountKeyCommand end processing.
2016-06-28T02:57:35.7745321Z ##[debug][Azure Call]Retrieved storage key successfully for the storage account: projectnamedevzxqun5wz in resource group: projectnameDev
2016-06-28T02:57:35.8369345Z ##[error]System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'storageKey' because it is an empty string.
2016-06-28T02:57:35.8369345Z ##[error]   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
2016-06-28T02:57:35.8369345Z ##[error]   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
2016-06-28T02:57:35.8369345Z ##[error]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2016-06-28T02:57:35.8369345Z ##[error]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2016-06-28T02:57:35.8369345Z ##[error]   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
2016-06-28T02:57:35.8369345Z ##[error]   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
2016-06-28T02:57:35.8369345Z ##[error]   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
2016-06-28T02:57:35.8369345Z ##[error]   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
2016-06-28T02:57:35.8369345Z ##[error]   at System.Management.Automation.CommandProcessorBase.Complete()
```

**Comment by AHoran** [comment]
I think this is issue #1660, i've worked around by editing the .ps1 file in the task on the build agent.

**Comment by nelsonmorais** [comment]
This fix also worked for me but my ps1 file was located in tasks\AzureFileCopy\1.0.62 (more recent version I presume)

Can someone tell me how tasks present on the agent folder are updated and when? I don't see them in the .zip agent that is downloaded from VSTS.
