### ISSUE TITLE
Sonar PRCA: RuntimeException: No changes found

### ISSUE THREAD

**Issue by pascalberger** [Microsoft/vsts-tasks#1968]
In a recent project I receive the following error during Sonar analysis from a PR:

```
2016-06-28T07:43:03.1350031Z Creating a discussion comment for the message at line 86 from /2016/IOZ.WebParts.GlobalNavigation/LAYOUTS/IOZ.WebParts.GlobalNavigation/CookieSettingsPage.aspx.cs
2016-06-28T07:43:03.3537474Z Creating a discussion comment for the message at line 121 from /2016/IOZ.WebParts.GlobalNavigation/LAYOUTS/IOZ.WebParts.GlobalNavigation/NavigationSettingsPage.aspx.cs
2016-06-28T07:43:03.3849957Z Creating a discussion comment for the message at line 35 from /2016/IOZ.WebParts.GlobalNavigation/LAYOUTS/IOZ.WebParts.GlobalNavigation/NavigationSettingsPage.aspx.cs
2016-06-28T07:43:03.4006212Z Creating a discussion comment for the message at line 100 from /2016/IOZ.WebParts.GlobalNavigation/ADMIN/IOZ.WebParts.GlobalNavigation/GlobalNavigationsettings.aspx.cs
2016-06-28T07:43:03.4631220Z ##[error]System.Management.Automation.RuntimeException: No changes found for /2016/IOZ.WebParts.GlobalNavigation/ADMIN/IOZ.WebParts.GlobalNavigation/GlobalNavigationsettings.aspx.cs ---> System.Management.Automation.RuntimeException: No changes found for /2016/IOZ.WebParts.GlobalNavigation/ADMIN/IOZ.WebParts.GlobalNavigation/GlobalNavigationsettings.aspx.cs
2016-06-28T07:43:03.4631220Z ##[error]   --- End of inner exception stack trace ---
2016-06-28T07:43:03.4631220Z ##[error]   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
2016-06-28T07:43:03.4787435Z ##[error]   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
2016-06-28T07:43:03.4787435Z ##[error]   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
2016-06-28T07:43:03.4787435Z ##[error]   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2016-06-28T07:43:03.4787435Z ##[error]   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2016-06-28T07:43:03.4787435Z ##[error]   at Microsoft.TeamFoundation.DistributedTask.Handlers.PowerShellHandler.Execute(ITaskContext context, CancellationToken cancellationToken, Int32 timeoutInMinutes)
2016-06-28T07:43:03.4787435Z ##[error]   at Microsoft.TeamFoundation.DistributedTask.Worker.JobRunner.RunTask(ITaskContext context, TaskWrapper task, CancellationTokenSource tokenSource)
```

Corresponding code is

    catch (Exception ex)

which I assume throws a CA1031 error.

Any idea what might be causing this?

**Comment by pascalberger** [comment]
Btw the file where the error occurs was added in the PR

**Comment by pascalberger** [comment]
Full log from the VSTS run available [here](https://gist.github.com/pascalberger/96bfa6f5dafc5ffc2df93baca60277fc).

**Comment by bgavrilMS** [comment]
Thanks @pascalberger, will investigate. Is this an ASP core project or an older flavour of ASP?

**Comment by pascalberger** [comment]
Worse, a SharePoint full trust solution :)

**Comment by bgavrilMS** [comment]
Hi @pascalberger - apologies for the long delay. We're actually looking into simplifying the implementation of PRCA as it uses some APIs that are too low level. Long story short - I have no idea why that assertion is thrown. All the files in the CR should have changes... . We'll try to repro the problem to find out more. 

In the interim, consider commenting the assertion out:

https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/SonarQubePostTest/PRCA/PostComments-Server.ps1#L317

**Comment by bgavrilMS** [comment]
Short term fix - ignore the messages if the underlying file changes are not found. In the longer term, we're looking at using a higher level API that should shield us from this.
