### ISSUE TITLE
Grunt and Gulp task L0 tests fail when run on a Mac

### ISSUE THREAD

**Issue by madhurig** [Microsoft/vsts-tasks#2047]
3 Gulp and 3 Grunt L0 tests fail when run on a Mac. L0 tests should be written so they run on any os/platform.

1) Grunt Suite runs a gruntFile when code coverage is enabled:

      AssertionError: should not have written to stderr
      + expected - actual

      -false
      +true
      
      at _build/Tests/L0/Grunt/_suite.js:98:13
      at _fulfilled (node_modules/q/q.js:834:54)
      at self.promiseDispatch.done (node_modules/q/q.js:863:30)
      at Promise.promise.promiseDispatch (node_modules/q/q.js:796:13)
      at node_modules/q/q.js:604:44
      at runSingle (node_modules/q/q.js:137:13)
      at flush (node_modules/q/q.js:125:13)

  2) Grunt Suite fails if istanbul fails:

      AssertionError: Istanbul should have failed
      + expected - actual

      -false
      +true
      
      at _build/Tests/L0/Grunt/_suite.js:264:13
      at _fulfilled (node_modules/q/q.js:834:54)
      at self.promiseDispatch.done (node_modules/q/q.js:863:30)
      at Promise.promise.promiseDispatch (node_modules/q/q.js:796:13)
      at node_modules/q/q.js:604:44
      at runSingle (node_modules/q/q.js:137:13)
      at flush (node_modules/q/q.js:125:13)

  3) Grunt Suite fails when test source files input does not match any file:

      AssertionError: false == true
      + expected - actual

      -false
      +true
      
      at _build/Tests/L0/Grunt/_suite.js:433:13
      at _fulfilled (node_modules/q/q.js:834:54)
      at self.promiseDispatch.done (node_modules/q/q.js:863:30)
      at Promise.promise.promiseDispatch (node_modules/q/q.js:796:13)
      at node_modules/q/q.js:604:44
      at runSingle (node_modules/q/q.js:137:13)
      at flush (node_modules/q/q.js:125:13)

1) Gulp Suite runs gulp when code coverage is enabled:

      AssertionError: should not have written to stderr
      + expected - actual

      -false
      +true
      
      at _build/Tests/L0/Gulp/_suite.js:99:13
      at _fulfilled (node_modules/q/q.js:834:54)
      at self.promiseDispatch.done (node_modules/q/q.js:863:30)
      at Promise.promise.promiseDispatch (node_modules/q/q.js:796:13)
      at node_modules/q/q.js:604:44
      at runSingle (node_modules/q/q.js:137:13)
      at flush (node_modules/q/q.js:125:13)

  2) Gulp Suite fails if istanbul fails:

      AssertionError: Istanbul should fail
      + expected - actual

      -false
      +true
      
      at _build/Tests/L0/Gulp/_suite.js:330:13
      at _fulfilled (node_modules/q/q.js:834:54)
      at self.promiseDispatch.done (node_modules/q/q.js:863:30)
      at Promise.promise.promiseDispatch (node_modules/q/q.js:796:13)
      at node_modules/q/q.js:604:44
      at runSingle (node_modules/q/q.js:137:13)
      at flush (node_modules/q/q.js:125:13)

  3) Gulp Suite fails when test source files input does not match any file:

      AssertionError: false == true
      + expected - actual

      -false
      +true
      
      at _build/Tests/L0/Gulp/_suite.js:440:13
      at _fulfilled (node_modules/q/q.js:834:54)
      at self.promiseDispatch.done (node_modules/q/q.js:863:30)
      at Promise.promise.promiseDispatch (node_modules/q/q.js:796:13)
      at node_modules/q/q.js:604:44
      at runSingle (node_modules/q/q.js:137:13)
      at flush (node_modules/q/q.js:125:13)

**Comment by nigurr** [comment]
Addressed here: https://github.com/Microsoft/vsts-tasks/pull/2072
