### ISSUE TITLE
VSTS Fails to complete SonarQube Analysis on PR

### ISSUE THREAD

**Issue by cwoolumtechnossus** [Microsoft/vsts-tasks#2052]
Since a few days ago, all of my pull request builds have started failing with the following error when completing SonarQube analysis.

```
5:22.7763674Z ##[error]System.Management.Automation.RuntimeException: Unable to find type [Microsoft.VisualStudio.Services.Client.VssConnection]. Make sure that the assembly that contains this type is loaded.
2016-07-10T06:45:22.7763674Z ##[error]   at System.Management.Automation.TypeOps.ResolveTypeName(ITypeName typeName)
2016-07-10T06:45:22.7763674Z ##[error]   at System.Management.Automation.Language.Compiler.GetAttribute(TypeConstraintAst typeConstraintAst)
2016-07-10T06:45:22.7763674Z ##[error]   at System.Management.Automation.Language.Compiler.GetRuntimeDefinedParameter(ParameterAst parameterAst, Boolean& customParameterSet, Boolean& usesCmdletBinding)
2016-07-10T06:45:22.7763674Z ##[error]   at System.Management.Automation.Language.Compiler.GetParameterMetaData(ReadOnlyCollection`1 parameters, Boolean automaticPositions, Boolean& usesCmdletBinding)
2016-07-10T06:45:22.7763674Z ##[error]   at System.Management.Automation.CompiledScriptBlockData.InitializeMetadata()
2016-07-10T06:45:22.7763674Z ##[error]   at System.Management.Automation.CompiledScriptBlockData.Compile(Boolean optimized)
2016-07-10T06:45:22.7763674Z ##[error]   at System.Management.Automation.DlrScriptCommandProcessor.Init()
2016-07-10T06:45:22.7919385Z ##[error]   at System.Management.Automation.CommandDiscovery.CreateCommandProcessorForScript(FunctionInfo functionInfo, ExecutionContext context, Boolean useNewScope, SessionStateInternal sessionState)
2016-07-10T06:45:22.7919385Z ##[error]   at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(CommandInfo commandInfo, CommandOrigin commandOrigin, Nullable`1 useLocalScope, SessionStateInternal sessionState)
2016-07-10T06:45:22.7919385Z ##[error]   at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(String commandName, CommandOrigin commandOrigin, Nullable`1 useLocalScope)
2016-07-10T06:45:22.7919385Z ##[error]   at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
2016-07-10T06:45:22.7919385Z ##[error]   at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, CommandRedirection[] redirections, ExecutionContext context)
2016-07-10T06:45:22.7919385Z ##[error]   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
2016-07-10T06:45:22.7919385Z ##[error]   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
2016-07-10T06:45:22.7919385Z ##[error]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2016-07-10T06:45:22.8232558Z Processing 0 new messages
2016-07-10T06:45:22.8388648Z ##[error]System.Management.Automation.RuntimeException: Unable to find type [PsWorkarounds.Helper]. Make sure that the assembly that contains this type is loaded.
2016-07-10T06:45:22.8544481Z ##[error]   at System.Management.Automation.TypeOps.ResolveTypeName(ITypeName typeName)
2016-07-10T06:45:22.8544481Z ##[error]   at System.Management.Automation.Interpreter.FuncCallInstruction`2.Run(InterpretedFrame frame)
2016-07-10T06:45:22.8544481Z ##[error]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2016-07-10T06:45:22.8544481Z ##[error]System.Management.Automation.PSArgumentException: Cannot find type [System.Collections.Generic.List[Microsoft.VisualStudio.Services.CodeReview.Discussion.WebApi.DiscussionThread]]: verify that the assembly containing this type is loaded.
2016-07-10T06:45:22.8544481Z ##[error]   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
2016-07-10T06:45:22.8701811Z ##[error]System.Management.Automation.RuntimeException: Unable to find type [System.Collections.Generic.List]. Make sure that the assembly that contains this type is loaded.
2016-07-10T06:45:22.8701811Z ##[error]   at System.Management.Automation.TypeOps.ResolveTypeName(ITypeName typeName)
2016-07-10T06:45:22.8701811Z ##[error]   at System.Management.Automation.TypeOps.ResolveTypeName(ITypeName typeName)
2016-07-10T06:45:22.8701811Z ##[error]   at System.Management.Automation.Language.Compiler.GetAttribute(TypeConstraintAst typeConstraintAst)
2016-07-10T06:45:22.8701811Z ##[error]   at System.Management.Automation.Language.Compiler.GetRuntimeDefinedParameter(ParameterAst parameterAst, Boolean& customParameterSet, Boolean& usesCmdletBinding)
2016-07-10T06:45:22.8701811Z ##[error]   at System.Management.Automation.Language.Compiler.GetParameterMetaData(ReadOnlyCollection`1 parameters, Boolean automaticPositions, Boolean& usesCmdletBinding)
2016-07-10T06:45:22.8701811Z ##[error]   at System.Management.Automation.CompiledScriptBlockData.InitializeMetadata()
2016-07-10T06:45:22.8701811Z ##[error]   at System.Management.Automation.CompiledScriptBlockData.Compile(Boolean optimized)
2016-07-10T06:45:22.8701811Z ##[error]   at System.Management.Automation.DlrScriptCommandProcessor.Init()
2016-07-10T06:45:22.8701811Z ##[error]   at System.Management.Automation.CommandDiscovery.CreateCommandProcessorForScript(FunctionInfo functionInfo, ExecutionContext context, Boolean useNewScope, SessionStateInternal sessionState)
2016-07-10T06:45:22.8701811Z ##[error]   at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(CommandInfo commandInfo, CommandOrigin commandOrigin, Nullable`1 useLocalScope, SessionStateInternal sessionState)
2016-07-10T06:45:22.8701811Z ##[error]   at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(String commandName, CommandOrigin commandOrigin, Nullable`1 useLocalScope)
2016-07-10T06:45:22.8701811Z ##[error]   at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
2016-07-10T06:45:22.8701811Z ##[error]   at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, CommandRedirection[] redirections, ExecutionContext context)
2016-07-10T06:45:22.8857294Z ##[error]   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
2016-07-10T06:45:22.8857294Z ##[error]   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
2016-07-10T06:45:22.8857294Z ##[error]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2016-07-10T06:45:22.8857294Z ##[error]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2016-07-10T06:45:22.9013602Z ##[error]System.Management.Automation.RuntimeException: Unable to find type [System.Collections.Generic.List]. Make sure that the assembly that contains this type is loaded.
2016-07-10T06:45:22.9013602Z ##[error]   at System.Management.Automation.TypeOps.ResolveTypeName(ITypeName typeName)
2016-07-10T06:45:22.9013602Z ##[error]   at System.Management.Automation.TypeOps.ResolveTypeName(ITypeName typeName)
2016-07-10T06:45:22.9013602Z ##[error]   at System.Management.Automation.Language.Compiler.GetAttribute(TypeConstraintAst typeConstraintAst)
2016-07-10T06:45:22.9013602Z ##[error]   at System.Management.Automation.Language.Compiler.GetRuntimeDefinedParameter(ParameterAst parameterAst, Boolean& customParameterSet, Boolean& usesCmdletBinding)
2016-07-10T06:45:22.9013602Z ##[error]   at System.Management.Automation.Language.Compiler.GetParameterMetaData(ReadOnlyCollection`1 parameters, Boolean automaticPositions, Boolean& usesCmdletBinding)
2016-07-10T06:45:22.9013602Z ##[error]   at System.Management.Automation.CompiledScriptBlockData.InitializeMetadata()
2016-07-10T06:45:22.9013602Z ##[error]   at System.Management.Automation.CompiledScriptBlockData.Compile(Boolean optimized)
2016-07-10T06:45:22.9013602Z ##[error]   at System.Management.Automation.DlrScriptCommandProcessor.Init()
2016-07-10T06:45:22.9013602Z ##[error]   at System.Management.Automation.CommandDiscovery.CreateCommandProcessorForScript(FunctionInfo functionInfo, ExecutionContext context, Boolean useNewScope, SessionStateInternal sessionState)
2016-07-10T06:45:22.9013602Z ##[error]   at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(CommandInfo commandInfo, CommandOrigin commandOrigin, Nullable`1 useLocalScope, SessionStateInternal sessionState)
2016-07-10T06:45:22.9013602Z ##[error]   at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(String commandName, CommandOrigin commandOrigin, Nullable`1 useLocalScope)
2016-07-10T06:45:22.9013602Z ##[error]   at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
2016-07-10T06:45:22.9013602Z ##[error]   at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, CommandRedirection[] redirections, ExecutionContext context)
2016-07-10T06:45:22.9170479Z ##[error]   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
2016-07-10T06:45:22.9170479Z ##[error]   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
2016-07-10T06:45:22.9170479Z ##[error]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2016-07-10T06:45:22.9170479Z ##[error]System.Management.Automation.RuntimeException: Unable to find type [System.Collections.Generic.List]. Make sure that the assembly that contains this type is loaded.
2016-07-10T06:45:22.9170479Z ##[error]   at System.Management.Automation.TypeOps.ResolveTypeName(ITypeName typeName)
2016-07-10T06:45:22.9170479Z ##[error]   at System.Management.Automation.TypeOps.ResolveTypeName(ITypeName typeName)
2016-07-10T06:45:22.9170479Z ##[error]   at System.Management.Automation.Language.Compiler.GetAttribute(TypeConstraintAst typeConstraintAst)
2016-07-10T06:45:22.9170479Z ##[error]   at System.Management.Automation.Language.Compiler.GetRuntimeDefinedParameter(ParameterAst parameterAst, Boolean& customParameterSet, Boolean& usesCmdletBinding)
2016-07-10T06:45:22.9326361Z ##[error]   at System.Management.Automation.Language.Compiler.GetParameterMetaData(ReadOnlyCollection`1 parameters, Boolean automaticPositions, Boolean& usesCmdletBinding)
2016-07-10T06:45:22.9326361Z ##[error]   at System.Management.Automation.CompiledScriptBlockData.InitializeMetadata()
2016-07-10T06:45:22.9326361Z ##[error]   at System.Management.Automation.CompiledScriptBlockData.Compile(Boolean optimized)
2016-07-10T06:45:22.9326361Z ##[error]   at System.Management.Automation.DlrScriptCommandProcessor.Init()
2016-07-10T06:45:22.9326361Z ##[error]   at System.Management.Automation.CommandDiscovery.CreateCommandProcessorForScript(FunctionInfo functionInfo, ExecutionContext context, Boolean useNewScope, SessionStateInternal sessionState)
2016-07-10T06:45:22.9326361Z ##[error]   at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(CommandInfo commandInfo, CommandOrigin commandOrigin, Nullable`1 useLocalScope, SessionStateInternal sessionState)
2016-07-10T06:45:22.9326361Z ##[error]   at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(String commandName, CommandOrigin commandOrigin, Nullable`1 useLocalScope)
2016-07-10T06:45:22.9326361Z ##[error]   at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
2016-07-10T06:45:22.9326361Z ##[error]   at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, CommandRedirection[] redirections, ExecutionContext context)
2016-07-10T06:45:22.9326361Z ##[error]   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
2016-07-10T06:45:22.9326361Z ##[error]   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
2016-07-10T06:45:22.9326361Z ##[error]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)

```

**Comment by cwoolumtechnossus** [comment]
duplicate of #2044
