### ISSUE TITLE
PublishTestResults - Failed to publish test results: Invalid value specified; Parameter name: TestOutcome

### ISSUE THREAD

**Issue by bgever** [Microsoft/vsts-tasks#2234]
Our tests include TRX (VSTest) outcomes of value `Pending`, which is a valid outcome according to the XSD in `%VSINSTALLDIR%\xml\Schemas\vstst.xsd`.

However, the PublishTestResults tasks fails with the following log:

```
2016-08-05T10:46:03.4238800Z ##[section]Starting: Publish Web App E2E Test Results
2016-08-05T10:46:03.4238800Z Preparing task execution handler.
2016-08-05T10:46:03.7242531Z Executing the powershell script: C:\VSTS-Agent-2.104.0\_work\_tasks\PublishTestResults_0b0f01ed-7dde-43ff-9cbb-e48954daf9b1\1.0.31\PublishTestResults.ps1
2016-08-05T10:46:03.9404188Z 
2016-08-05T10:46:03.9404188Z 
2016-08-05T10:46:03.9716586Z Publishing Test Results...
2016-08-05T10:46:05.8090061Z Test results remaining: 81
2016-08-05T10:46:06.5560818Z ##[warning]Failed to publish test results: Invalid value specified
2016-08-05T10:46:06.5560818Z Parameter name: TestOutcome
2016-08-05T10:46:06.5717084Z ##[section]Finishing: Publish Web App E2E Test Results
```

In the [PowerShell script](https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/PublishTestResults/PublishTestResults.ps1), it imports the following modules, which then are used to publish the results.

```ps1
# Import the Task.Common, Task.Internal and Task.TestResults dll that has all the cmdlets we need
import-module "Microsoft.TeamFoundation.DistributedTask.Task.Internal"
import-module "Microsoft.TeamFoundation.DistributedTask.Task.Common"
import-module "Microsoft.TeamFoundation.DistributedTask.Task.TestResults"
```

So it appears this dependency doesn't support the Pending outcome? Can this be fixed?

**Comment by tanvi-soni** [comment]
Are you using Windows (legacy) agent

**Comment by tanvi-soni** [comment]
Are you using Legacy Windows agent. We will be fixing this for new agent.

**Comment by bgever** [comment]
We're using agent version 2.104.0. Don't know whether that's a legacy version?

**Comment by SatishThareja** [comment]
@bgever Are you using core clr agent or windows agent(old) ?

**Comment by tanvi-soni** [comment]
@bgever Did you the try running with the latest build agent.

**Comment by bgever** [comment]
Hi @tanvi-soni & @SatishThareja, I've tried again getting the following failed result:
```
2016-09-15T06:46:10.7846760Z ##[section]Starting: Build
2016-09-15T06:46:10.8003106Z Current agent version: '2.105.2'
```
```
2016-09-15T06:58:34.3015020Z ##[section]Starting: Publish Web App E2E Test Results
2016-09-15T06:58:34.3015020Z Preparing task execution handler.
2016-09-15T06:58:34.6608818Z Executing the powershell script: C:\VSTS-Agent-2.104.0\_work\_tasks\PublishTestResults_0b0f01ed-7dde-43ff-9cbb-e48954daf9b1\1.0.32\PublishTestResults.ps1
2016-09-15T06:58:36.1296631Z Publishing Test Results...
2016-09-15T06:58:37.9320521Z Test results remaining: 80
2016-09-15T06:58:38.9202966Z ##[warning]'##vso[task.logissue type=error;TaskName=VSTest;code=Publish failed: Invalid value specified' contains logging command keyword '##vso', but it's not a legal command. Please reference documentaion to fix any potentially syntax error (http://go.microsoft.com/fwlink/?LinkId=817296)
2016-09-15T06:58:38.9202966Z ##vso[task.logissue type=error;TaskName=VSTest;code=Publish failed: Invalid value specified
2016-09-15T06:58:38.9202966Z Parameter name: TestOutcome]
2016-09-15T06:58:38.9202966Z ##[warning]Failed to publish test results: Invalid value specified
2016-09-15T06:58:38.9202966Z Parameter name: TestOutcome
2016-09-15T06:58:38.9827972Z ##[section]Finishing: Publish Web App E2E Test Results
```

**Comment by tanvi-soni** [comment]
@bgever The support for "Pending" outcome in trx was provided after agent 105.2. You can download the latest agent from https://github.com/Microsoft/vsts-agent/releases/tag/v2.106.0 
Let me know if the error still persists.

**Comment by tanvi-soni** [comment]
@bgever Closing the issue. 
Let me know if the error still persists.

**Comment by bgever** [comment]
@tanvi-soni I can only test this once it is available on VSTS via automatic update. I have forced the update via the Build Queues and now the latest version installed is 2.105.6. When is 2.106.0 expected to land in VSTS?

**Comment by tanvi-soni** [comment]
@bgever 2.105.6 should also work.
 If you run the build against 2.105.6 agent, your issue should get resolved.

**Comment by indrani-insight** [comment]
Hi Tanvi,

  I am also having same above issue using VSTest Task in the pipeline, could you please help me . For your reference below are the details.
  I have created a pipeline in Azure DevOps contain couple of tasks. I used VSTest Task for testing UnitTests for my .Net Project. Pipelines are running on self hosted build agent. VSTest task is failing after passing all the tests and it's saying "Failed to publish test results".  (FYI: I used VSTest task in another pipeline and it's working fine).

Pipeline description:

- task: VSTest@2
      displayName: 'Run Unit Tests'
      inputs:
        testSelector: 'testAssemblies'
        testAssemblyVer2: |
          **\ServicesUnitTest.dll
          !**\*TestAdapter.dll
          !**\obj\**
        searchFolder: '$(Build.SourcesDirectory)\UnitTest\ServicesUnitTest\bin\Debug'
        runOnlyImpactedTests: false
        testRunTitle: 'KioskTests'
        publishRunAttachments: false

error is:

2021-09-13T15:34:12.8455574Z Results File: C:\agent\w\_temp\TestResults\Kiosk-agent_rg-gp-kiosk-bui_2021-09-13_15_32_25.trx
2021-09-13T15:34:12.8603675Z Test Run Successful.
2021-09-13T15:34:12.8604022Z Total tests: 1367
2021-09-13T15:34:12.8604376Z      Passed: 1367
2021-09-13T15:34:12.8612412Z  Total time: 1.8063 Minutes
2021-09-13T15:34:12.8921503Z Vstest.console.exe exited with code 0.
2021-09-13T15:34:12.8921984Z **************** Completed test execution *********************
2021-09-13T15:34:12.9012745Z Test results files: C:\agent\w\_temp\TestResults\Kiosk-agent_rg-gp-kiosk-bui_2021-09-13_15_32_25.trx
2021-09-13T15:34:13.2853891Z Created test run: 1098308
2021-09-13T15:34:13.2855705Z Publishing test results: 989
2021-09-13T15:34:13.3830626Z Publishing test results to test run '1098308'.
2021-09-13T15:34:13.3864635Z TestResults To Publish 989, Test run id:1098308
2021-09-13T15:34:13.3969497Z Test results publishing 989, remaining: 0. Test run id: 1098308
2021-09-13T15:34:13.5937216Z Failed to publish test results.
2021-09-13T15:34:13.5991760Z Publishing Attachments: 1
2021-09-13T15:34:14.3834885Z ##[error]Error occurred while publishing test results : System.AggregateException: One or more errors occurred. ---> Microsoft.TeamFoundation.TestManagement.WebApi.InvalidPropertyException: Invalid Priority specified
2021-09-13T15:34:14.3836265Z    at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<HandleResponseAsync>d__53.MoveNext()
2021-09-13T15:34:14.3836733Z --- End of stack trace from previous location where exception was thrown ---
2021-09-13T15:34:14.3837160Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-09-13T15:34:14.3837705Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-09-13T15:34:14.3838211Z    at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__51.MoveNext()
2021-09-13T15:34:14.3838655Z --- End of stack trace from previous location where exception was thrown ---
2021-09-13T15:34:14.3839077Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-09-13T15:34:14.3839494Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-09-13T15:34:14.3839963Z    at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__47`1.MoveNext()
2021-09-13T15:34:14.3840407Z --- End of stack trace from previous location where exception was thrown ---
2021-09-13T15:34:14.3840827Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-09-13T15:34:14.3841273Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-09-13T15:34:14.3841761Z    at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__28`1.MoveNext()
2021-09-13T15:34:14.3842231Z --- End of stack trace from previous location where exception was thrown ---
2021-09-13T15:34:14.3842643Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-09-13T15:34:14.3843110Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-09-13T15:34:14.3843639Z    at Microsoft.TeamFoundation.TestClient.PublishTestResults.TestResultsPublisher.<PublishSingleBatch>d__10.MoveNext()
2021-09-13T15:34:14.3844140Z --- End of stack trace from previous location where exception was thrown ---
2021-09-13T15:34:14.3844546Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-09-13T15:34:14.3845014Z    at Microsoft.TeamFoundation.TestClient.PublishTestResults.TestResultsPublisher.<PublishResults>d__6.MoveNext()
2021-09-13T15:34:14.3845510Z --- End of stack trace from previous location where exception was thrown ---
2021-09-13T15:34:14.3846235Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-09-13T15:34:14.3846706Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-09-13T15:34:14.3847231Z    at Microsoft.TeamFoundation.TestClient.PublishTestResults.TestResultsPublisher.<AddTestResultsAsync>d__2.MoveNext()
2021-09-13T15:34:14.3847727Z --- End of stack trace from previous location where exception was thrown ---
2021-09-13T15:34:14.3848134Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-09-13T15:34:14.3848548Z    at Polly.Retry.AsyncRetryEngine.<ImplementationAsync>d__0`1.MoveNext()
2021-09-13T15:34:14.3848953Z --- End of stack trace from previous location where exception was thrown ---
2021-09-13T15:34:14.3849363Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-09-13T15:34:14.3849830Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-09-13T15:34:14.3850258Z    at Polly.AsyncPolicy.<ExecuteAsync>d__21`1.MoveNext()
2021-09-13T15:34:14.3850726Z    --- End of inner exception stack trace ---
2021-09-13T15:34:14.3851124Z    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
2021-09-13T15:34:14.3851618Z    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
2021-09-13T15:34:14.3852120Z    at Microsoft.VisualStudio.TestService.RestApiHelpers.HttpRetryWrapper.Execute[TResult](Func`1 func)
2021-09-13T15:34:14.3852675Z    at Microsoft.VisualStudio.TestService.TcmTestResultPublisher.TrxTestResultPublisher.PublishTestRunResults(TestRunModel testRunModel)
2021-09-13T15:34:14.3853259Z    at MS.VS.TestService.VstestConsoleAdapter.PublishTestResult.CreateOrUpdateTestRun(TestRunModel testRunModel)
2021-09-13T15:34:14.3853791Z    at MS.VS.TestService.VstestConsoleAdapter.PublishTestResult.Publish(VstestConsoleRunContext testRunContext)
2021-09-13T15:34:14.3854406Z ---> (Inner Exception #0) Microsoft.TeamFoundation.TestManagement.WebApi.InvalidPropertyException: Invalid Priority specified
2021-09-13T15:34:14.3854982Z    at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<HandleResponseAsync>d__53.MoveNext()
2021-09-13T15:34:14.3855456Z --- End of stack trace from previous location where exception was thrown ---
2021-09-13T15:34:14.3855864Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-09-13T15:34:14.3856331Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-09-13T15:34:14.3856809Z    at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__51.MoveNext()
2021-09-13T15:34:14.3857251Z --- End of stack trace from previous location where exception was thrown ---
2021-09-13T15:34:14.3857671Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-09-13T15:34:14.3858120Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-09-13T15:34:14.3858623Z    at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__47`1.MoveNext()
2021-09-13T15:34:14.3859065Z --- End of stack trace from previous location where exception was thrown ---
2021-09-13T15:34:14.3859486Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-09-13T15:34:14.3859934Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-09-13T15:34:14.3860431Z    at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__28`1.MoveNext()
2021-09-13T15:34:14.3860880Z --- End of stack trace from previous location where exception was thrown ---
2021-09-13T15:34:14.3861292Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-09-13T15:34:14.3861750Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-09-13T15:34:14.3862335Z    at Microsoft.TeamFoundation.TestClient.PublishTestResults.TestResultsPublisher.<PublishSingleBatch>d__10.MoveNext()
2021-09-13T15:34:14.3862842Z --- End of stack trace from previous location where exception was thrown ---
2021-09-13T15:34:14.3863251Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-09-13T15:34:14.3863731Z    at Microsoft.TeamFoundation.TestClient.PublishTestResults.TestResultsPublisher.<PublishResults>d__6.MoveNext()
2021-09-13T15:34:14.3864207Z --- End of stack trace from previous location where exception was thrown ---
2021-09-13T15:34:14.3864620Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-09-13T15:34:14.3865080Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-09-13T15:34:14.3865602Z    at Microsoft.TeamFoundation.TestClient.PublishTestResults.TestResultsPublisher.<AddTestResultsAsync>d__2.MoveNext()
2021-09-13T15:34:14.3866100Z --- End of stack trace from previous location where exception was thrown ---
2021-09-13T15:34:14.3866514Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-09-13T15:34:14.3866990Z    at Polly.Retry.AsyncRetryEngine.<ImplementationAsync>d__0`1.MoveNext()
2021-09-13T15:34:14.3867405Z --- End of stack trace from previous location where exception was thrown ---
2021-09-13T15:34:14.3867828Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-09-13T15:34:14.3868274Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-09-13T15:34:14.3868706Z    at Polly.AsyncPolicy.<ExecuteAsync>d__21`1.MoveNext()<---
2021-09-13T15:34:14.3868909Z 
2021-09-13T15:34:14.3877669Z ##[error]Skipping marking test run as complete as test run id 0 is invalid.
2021-09-13T15:34:14.4522445Z Completed TestExecution Model...
2021-09-13T15:34:14.4890344Z ##[warning]Vstest failed with error. Check logs for failures. There might be failed tests.
2021-09-13T15:34:14.4891978Z ##[error]Error: The process 'C:\agent\w\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.170.1\Modules\DTAExecutionHost.exe' failed with exit code 1
2021-09-13T15:34:14.4894196Z ##[error]Vstest failed with error. Check logs for failures. There might be failed tests.
2021-09-13T15:34:14.5009001Z ##[section]Finishing: Run Unit Tests

I appreciate your help!. 

Thanks,
Rani
