### ISSUE TITLE
Error using the Azure Deployment task

### ISSUE THREAD

**Issue by fleed** [Microsoft/vsts-tasks#2269]
I'm trying to deploy a package to a classic Cloud service in a VSTS build.

I'm getting the following error:

```csharp
Microsoft.WindowsAzure.Commands.Common.ComputeCloudException: BadRequest: The certificate with thumbprint 3351774e7348c1ee8daa554fd2d6bad8217e6677 was not found.
OperationID : '7d17019f41d7060a8669a8fd99bd52a5' ---> Hyak.Common.CloudException: BadRequest: The certificate with thumbprint 3351774e7348c1ee8daa554fd2d6bad8217e6677 was not found.
at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)
at Microsoft.WindowsAzure.Management.Compute.DeploymentOperationsExtensions.Create(IDeploymentOperations operations, String serviceName, DeploymentSlot deploymentSlot, DeploymentCreateParameters parameters)
at Microsoft.WindowsAzure.Commands.Utilities.Common.ServiceManagementBaseCmdlet.ExecuteClientActionNewSM[TResult](Object input, String operationDescription, Func`1 action, Func`3 contextFactory)
```

I've selected the right subscription and in configuration / services added the management certificate for the subscription as downloaded from the publishsettings.
Anyway from the error it seems that it's not doing the request with the right certificate.
What can be the problem?

Thanks

**Comment by vincentdass** [comment]
Hi fleed,
Can u please share the full log ?

**Comment by fleed** [comment]
[Azure deployment task log](https://gist.github.com/fleed/bc7afa8765d6b46361d0f7c89b4330bf)

**Comment by fleed** [comment]
Hi

Sorry, I've fixed the issue which was a wrong value for a Certificate Thumbprint.
I just think that the exception should give an idea of the issue, which can be easily solved if correctly detected.

Thanks for support.
