### ISSUE TITLE
Exception on Publish Artifacts task

### ISSUE THREAD

**Issue by ASeale74** [Microsoft/vsts-tasks#2285]
As the task is copying files from the staging location to the server, using a hosted build agent, it gets the following exception at random intervals:

`Unhandled Exception: System.ServiceModel.ProtocolException: This channel can no longer be used to send messages as the output session was auto-closed due to a server-initiated shutdown. Either disable auto-close by setting the DispatchRuntime.AutomaticInputSessionShutdown to false, or consider modifying the shutdown protocol with the remote server.
Server stack trace:
at System.ServiceModel.Channels.ServiceChannel.PrepareCall(ProxyOperationRuntime operation, Boolean oneway, ProxyRpc& rpc)
at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)
Exception rethrown at [0]:
at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
at Microsoft.TeamFoundation.DistributedTask.Agent.Logger.INetPipeWriter.Disconnect(Guid jobId)
at Microsoft.TeamFoundation.DistributedTask.Agent.Logger.ForwardingWriter.Dispose()
at Microsoft.TeamFoundation.DistributedTask.Agent.Worker.Common.BaseLogger.DisposeWriter(String name, ILogWriter writer)
at Microsoft.TeamFoundation.DistributedTask.Agent.Worker.Common.BaseLogger.Dispose()
at VsoWorker.Program.Main(String[] args)`

I've not been able to have it completely publish all of the files (123 files in total to process). The whole process from beginning of build to failure takes ~19 minutes.

**Comment by bryanmacfarlane** [comment]
The new vsts-agent has a bunch of robustness fixes around publishing artifacts.

https://github.com/Microsoft/vsts-agent/releases 

2.105.1 

Are you on hosted build or your own agent?

**Comment by ASeale74** [comment]
It's a hosted build.

**Comment by bryanmacfarlane** [comment]
This is fixed in the 2.x agent.  You can use a private agent if you need the fix.  For hosted, we are moving scale unit by scale unit so you should get it soon.
