### ISSUE TITLE
ConfigureTestAgent task: 'Cannot bind argument to parameter 'String' because it is an empty string.'

### ISSUE THREAD

**Issue by ozyx** [Microsoft/vsts-tasks#2311]
ConfigureTestAgent task continually errors out with this error message: `'Cannot bind argument to parameter 'String' because it is an empty string.'.`

Here's the full stack trace:
```
2016-08-22T21:10:46.8243972Z Executing the powershell script: D:\path\to\DeployTestAgent.ps1
2016-08-22T21:10:46.9181512Z ##[debug]resourceFilteringMethod = machineNames
2016-08-22T21:10:47.0275301Z DistributedTests: Starting to deploy and configure test agent on test machines.
2016-08-22T21:10:47.0431729Z DistributedTests: Inputs provided are:
2016-08-22T21:10:47.0431729Z DistributedTests: Machines: [machine name]
2016-08-22T21:10:47.0431729Z DistributedTests: Username: [username]
2016-08-22T21:10:47.0431729Z DistributedTests: Machine Group name: Integration Test Runners
2016-08-22T21:10:47.0431729Z DistributedTests: Run as process: False
2016-08-22T21:10:47.0431729Z DistributedTests: Login Automatically: False
2016-08-22T21:10:47.0431729Z DistributedTests: Disable Screen saver: False
2016-08-22T21:10:47.0431729Z DistributedTests: Agent location: \\path\to\agent\vstf_testagent.exe
2016-08-22T21:10:47.0431729Z DistributedTests: Update test agent: True
2016-08-22T21:10:47.0431729Z DistributedTests: Run test agent as DataCollection only : False
2016-08-22T21:10:47.0431729Z DistributedTests: Path to script that installs test agent on remote machine: D:\agent\tasks\DeployVisualStudioTestAgent\1.0.16\TestAgentInstall.ps1
2016-08-22T21:10:47.0431729Z DistributedTests: Path to script that configures test agent on remote machine: D:\agent\tasks\DeployVisualStudioTestAgent\1.0.16\TestAgentConfiguration.ps1
2016-08-22T21:10:47.0431729Z DistributedTests: Path to script that downloads test agent on azure remote machines : D:\agent\tasks\DeployVisualStudioTestAgent\1.0.16\DownloadTestAgent.ps1
2016-08-22T21:10:47.0431729Z DistributedTests: Path to script that checks if test agent is installed on remote machine: D:\agent\tasks\DeployVisualStudioTestAgent\1.0.16\CheckTestAgentInstallation.ps1
2016-08-22T21:10:47.2306769Z DistributedTests: Test Agent is being copied to: C:\path\to\vstf_testagent.exe
2016-08-22T21:11:18.1848384Z DistributedTests: Task 'CopyFilesToTestAgent' on machine 'MACHINE:5985' is being run
2016-08-22T21:11:58.2487008Z DistributedTests: Task 'CopyFilesToTestAgent' on machine 'MACHINE:5985' completed.
2016-08-22T21:11:58.2643330Z DistributedTests: Task 'DeployTestAgent' on machine 'MACHINE:5985' is being run
2016-08-22T21:12:05.6083326Z DistributedTests: Task 'DeployTestAgent' on machine 'MACHINE:5985' completed.
2016-08-22T21:12:05.6083326Z DistributedTests: Task 'ConfigureTestAgent' on machine 'MACHINE:5985' is being run
2016-08-22T21:12:09.8897216Z DistributedTests: Task 'ConfigureTestAgent' on machine 'MACHINE:5985' completed.
2016-08-22T21:12:09.8897216Z ##[warning]DistributedTests: Task 'ConfigureTestAgent' for machine 'MACHINE:5985's **Error : System.Exception: Cannot bind argument to parameter 'String' because it is an empty string.**
2016-08-22T21:12:09.8897216Z ##[warning]DistributedTests: Task 'ConfigureTestAgent' for machine MACHINE:5985's Log : 
2016-08-22T21:12:09.9053476Z ##[warning]	 Deployment started on target machine...
2016-08-22T21:12:09.9053476Z ##[warning]System.AggregateException: Failed to execute the powershell script. Consult the logs below for details of the error.
2016-08-22T21:12:09.9053476Z ##[warning]Cannot bind argument to parameter 'String' because it is an empty string. ---> System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'String' because it is an empty string.
2016-08-22T21:12:09.9053476Z ##[warning]   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
2016-08-22T21:12:09.9053476Z ##[warning]   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
2016-08-22T21:12:09.9053476Z ##[warning]   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
2016-08-22T21:12:09.9053476Z ##[warning]   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2016-08-22T21:12:09.9053476Z ##[warning]   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2016-08-22T21:12:09.9053476Z ##[warning]   at System.Management.Automation.PowerShell.CoreInvoke[TOutput](IEnumerable input, PSDataCollection`1 output, PSInvocationSettings settings)
2016-08-22T21:12:09.9053476Z ##[warning]   at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Deployment.PowershellExecutor.<>c__DisplayClass28_0.<Invoke>b__0()
2016-08-22T21:12:09.9053476Z ##[warning]   at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Utilities.RetryExecutor.<>c__DisplayClass19_0`1.<Execute>b__0()
2016-08-22T21:12:09.9053476Z ##[warning]   at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Utilities.RetryExecutor.Execute(Action action)
2016-08-22T21:12:09.9053476Z ##[warning]   at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Utilities.RetryExecutor.Execute[T](Func`1 action)
2016-08-22T21:12:09.9053476Z ##[warning]   at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Deployment.PowershellExecutor.Invoke(String errorContextMessage, Boolean writeResultToLog, Boolean isCancellable, ActionPreference errorActionPreference)
2016-08-22T21:12:09.9053476Z ##[warning]   --- End of inner exception stack trace ---
2016-08-22T21:12:09.9053476Z ##[warning]   at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Deployment.PowershellExecutor.Invoke(String errorContextMessage, Boolean writeResultToLog, Boolean isCancellable, ActionPreference errorActionPreference)
2016-08-22T21:12:09.9053476Z ##[warning]   at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Deployment.ScriptExecutor.ExecuteScript(IPowerShell powerShell, String script, String arguments, Boolean isScriptDotSourced, Boolean useHttp)
2016-08-22T21:12:09.9053476Z ##[warning]   at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Deployment.DeploymentService.RunPowerShellScripts(DeploymentMachineSpecification deploymentMachine, ScriptSpecification scriptSpecification, ScriptSpecification initializationScriptSpecification, String applicationPath, IPowerShell powerShellSession)
2016-08-22T21:12:09.9053476Z ##[warning]---> (Inner Exception #0) System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'String' because it is an empty string.
2016-08-22T21:12:09.9053476Z ##[warning]   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
2016-08-22T21:12:09.9053476Z ##[warning]   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
2016-08-22T21:12:09.9053476Z ##[warning]   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
2016-08-22T21:12:09.9053476Z ##[warning]   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2016-08-22T21:12:09.9053476Z ##[warning]   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2016-08-22T21:12:09.9053476Z ##[warning]   at System.Management.Automation.PowerShell.CoreInvoke[TOutput](IEnumerable input, PSDataCollection`1 output, PSInvocationSettings settings)
2016-08-22T21:12:09.9053476Z ##[warning]   at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Deployment.PowershellExecutor.<>c__DisplayClass28_0.<Invoke>b__0()
2016-08-22T21:12:09.9209715Z ##[warning]   at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Utilities.RetryExecutor.<>c__DisplayClass19_0`1.<Execute>b__0()
2016-08-22T21:12:09.9209715Z ##[warning]   at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Utilities.RetryExecutor.Execute(Action action)
2016-08-22T21:12:09.9209715Z ##[warning]   at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Utilities.RetryExecutor.Execute[T](Func`1 action)
2016-08-22T21:12:09.9209715Z ##[warning]   at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Deployment.PowershellExecutor.Invoke(String errorContextMessage, Boolean writeResultToLog, Boolean isCancellable, ActionPreference errorActionPreference)<---
2016-08-22T21:12:09.9209715Z ##[error]Error occured on 'MACHINE:5985'. Details : 'Cannot bind argument to parameter 'String' because it is an empty string.'. For troubleshooting, refer http://aka.ms/remotevstest.
```

Here's the build definition I'm using...
![buildorder](https://cloud.githubusercontent.com/assets/9259993/17873704/f02efa6a-687b-11e6-93c2-11242d607f45.png)

We are using vsts-tasks version `Release\m89`

Has anybody encountered this error before? The parameter is unnamed so I'm not even sure what the script is looking for in this case. Any help is appreciated.

**Comment by ozyx** [comment]
As it turns out, `ConfigureTestAgent.ps1` was reading the password that I had defined as a secret variable as an empty string `""`. Any reason as to why this happens? Passwords to target machines should be defined as secret variables... right?

**Comment by SatishThareja** [comment]
@ozyx  Can you share build logs with system.debug set to 'true' and send it to devops_tools@microsoft.com.

**Comment by SatishThareja** [comment]
@ozyx This issue has been fixed in latest TFS 2015 update. You can update to TFS 2015 update 3 to get a fix for this issue.
