### ISSUE TITLE
A parameter cannot be found that matches parameter name 'vstestLocationMethod'

### ISSUE THREAD

**Issue by halkor** [Microsoft/vsts-tasks#2499]
I'm suddenly getting this exeception when trying to run tests.

2016-09-13T08:11:22.1094992Z Executing the powershell script: C:\BuildAgent\tasks\VSTest\1.0.50\VSTest.ps1
2016-09-13T08:11:22.1876285Z ##[error]System.Management.Automation.ParameterBindingException: A parameter cannot be found that matches parameter name 'vstestLocationMethod'.
2016-09-13T08:11:22.1876285Z ##[error]   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
2016-09-13T08:11:22.1876285Z ##[error]   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
2016-09-13T08:11:22.1876285Z ##[error]   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
2016-09-13T08:11:22.2032386Z ##[error]   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2016-09-13T08:11:22.2032386Z ##[error]   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2016-09-13T08:11:22.2032386Z ##[error]   at Microsoft.TeamFoundation.DistributedTask.Handlers.PowerShellHandler.Execute(ITaskContext context, CancellationToken cancellationToken, Int32 timeoutInMinutes)
2016-09-13T08:11:22.2032386Z ##[error]   at Microsoft.TeamFoundation.DistributedTask.Worker.JobRunner.RunTask(ITaskContext context, TaskWrapper task, CancellationTokenSource tokenSource)

**Comment by allendm-msft** [comment]
Are you on a onprem tfs isntance or vsts? If former do share the version
What is your agent version and the task version? 
Did you download the agent from your tfs instance or compiled it from this repo?

**Comment by halkor** [comment]
I'm using VSTS, but have my own buildserver. The agent version is "1.105.6" and the task version is "1.0.50".

I was able to work around this issue by manually replacing files in the task folder with the latest version from github.

**Comment by halkor** [comment]
I upgraded to the version 2 agent and it works now. I had to upgrade manually. Isn't the agent supposed to upgrade itself?

**Comment by allendm-msft** [comment]
The agent does not auto upgrade from 1.x to 2.x. That said you should never have to replace the files on the agent yourself. If you can provide any more data let me know.

**Comment by halkor** [comment]
I guess the problem is that the 1.x agent gets test task version 1.0.50. On the 2.x agent I get version 1.0.59. The 1.0.50 version does not match input parameters in the VSTS gui.

I have upgraded all my agents to 2.x now and it works fine.

**Comment by nigurr** [comment]
@halkor, it works on 1.x agent too. Instead of re-queuing the build, you need to queue it again, that will internally push the latest task to agent.
