### ISSUE TITLE
VSTest task fails with Exception calling "GetVersionInfo" with "1" argument(s)

### ISSUE THREAD

**Issue by qmfrederik** [Microsoft/vsts-tasks#2524]
## **Agent version and platform**
Version: 2.105.5
Platform: Windows

## **VSTS type and version**
Hosted VSTS: quamotion.visualstudio.com

## **What's not working?** 

The Visual Studio Test task fails to run after the last update (see log below). 

On our build server, we only have MSBuild and the VSTest tools installed; Visual Studio itself is not.
[98cb01d41f51600735588ccbbd3d035d96d21a43](https://github.com/Microsoft/vsts-tasks/commit/98cb01d41f51600735588ccbbd3d035d96d21a43) added a check for Update 3 which uses `devenv.exe` to get the version number, but `devenv.exe` is not available.

An alternative would be to use `vstest.console.exe`, I'll prepare a PR for that.

## **Agent and Worker's diag log**

```
2016-09-15T08:40:09.5286733Z ##[section]Starting: Test Assemblies **\$(BuildConfiguration)\Quamotion.Test*.dll;-:**\obj\**;-:**\*VS2013*.dll
2016-09-15T08:40:09.5591208Z Preparing task execution handler.
2016-09-15T08:40:10.0143975Z Executing the powershell script: F:\vsts\_work\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\1.0.59\VSTest.ps1
2016-09-15T08:40:11.4966166Z 
2016-09-15T08:40:11.4966166Z 
2016-09-15T08:40:11.5122249Z ##[error]System.Management.Automation.CmdletInvocationException: Exception calling "GetVersionInfo" with "1" argument(s): "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\..\IDE\devenv.exe" ---> System.Management.Automation.MethodInvocationException: Exception calling "GetVersionInfo" with "1" argument(s): "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\..\IDE\devenv.exe" ---> System.IO.FileNotFoundException: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\..\IDE\devenv.exe
2016-09-15T08:40:11.5122249Z    at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
2016-09-15T08:40:11.5122249Z    at CallSite.Target(Closure , CallSite , Type , Object )
2016-09-15T08:40:11.5122249Z    --- End of inner exception stack trace ---
2016-09-15T08:40:11.5122249Z    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
2016-09-15T08:40:11.5122249Z    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
2016-09-15T08:40:11.5122249Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2016-09-15T08:40:11.5122249Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2016-09-15T08:40:11.5122249Z    at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
2016-09-15T08:40:11.5122249Z    at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
2016-09-15T08:40:11.5122249Z    at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
2016-09-15T08:40:11.5122249Z    at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
2016-09-15T08:40:11.5122249Z    at System.Management.Automation.CommandProcessorBase.Complete()
2016-09-15T08:40:11.5122249Z    --- End of inner exception stack trace ---
2016-09-15T08:40:11.5122249Z    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
2016-09-15T08:40:11.5122249Z    at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
2016-09-15T08:40:11.5122249Z    at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
2016-09-15T08:40:11.5122249Z    at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2016-09-15T08:40:11.5122249Z    at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2016-09-15T08:40:11.5122249Z    at Microsoft.TeamFoundation.DistributedTask.Handlers.LegacyVSTSPowerShellHost.VSTSPowerShellHost.Main(String[] args)
2016-09-15T08:40:11.5279001Z ##[error]LegacyVSTSPowerShellHost.exe completed with return code: -1.
2016-09-15T08:40:11.5279001Z ##[section]Finishing: Test Assemblies **\$(BuildConfiguration)\Quamotion.Test*.dll;-:**\obj\**;-:**\*VS2013*.dll
```

**Comment by allendm-msft** [comment]
@qmfrederik how did you get the msbuild/vstest packages without VS?

**Comment by qmfrederik** [comment]
@allendm-msft You can install MSBuild as part of the _Microsoft Build Tools 2015_ package, and vstest as part of the _Agents for Visual Studio 2015_ package.

You can find both packages on https://www.visualstudio.com/downloads/, first select _View All Downloads_, then expand _Tools for Visual Studio 2015_, and you'll find both downloads at the end of the list.

#2525 contains a proposed fix.

**Comment by allendm-msft** [comment]
@qmfrederik I guessed as much :) 
We do not recommend using Agents for VS as a replacement of VS because it is not at parity in the complete unit testing feature set with VS. We also base our testing off the VS install being present.
That's the reason the check for devenv is a conscious one for the vstest task. 

I have assigned this issue to our PO who will take a call on whether we want to add this fix in. 

P.S. Regardless of the above decision I really appreciate the pro-activeness in getting a fix available along with reporting the issue. Really awesome!!

**Comment by atinb** [comment]
@qmfrederik 
Like Allen said, the VSTest task has a strong dependency on VS being installed. Since the Test Agents do not provide full functionality, we will like to keep it this way.

**Comment by qmfrederik** [comment]
@atinb 

That's strange, the VSTest task worked for years without VS installed, and a recent change which was automatically pushed to my build server broke this.

I also believe one of the reasons the Agents for Visual Studio package was created, was to enable scenarios where you can run vstest without Visual Studio installed.

Do I understand correctly that for this scenario, you're recommending we change to another CI system (Jenkins or thie like) since the VS build agent won't support this scenario anymore?
