### ISSUE TITLE
"Test: Xamarin Test Cloud" Build Step Fails, Adds Unnecessary Quotes

### ISSUE THREAD

**Issue by brminnick** [Microsoft/vsts-tasks#2595]
The "Test: Xamarin Test Cloud" Build Step is adding double-quotes to the `--series`, `--locale`, `--assembly-dir`, and `--nunit-xml` parameters, which is causing a failure.

The "Test: Xamarin Test Cloud" Build Step was updated on 16 August 2016 indicating a regression in the latest version.

I am using a Hosted Agent. My college Brad Umbaugh is using a local build agent and he does is not experiencing this problem, so there may be a difference between the VSTS Hosted Agent and a Local Mac Agent.

**Current Version**
```
2016-09-21T17:15:41.3993380Z Executing the powershell script: C:\LR\MMS\Services\Mms\TaskAgentProvisioner\Tools\agents\1.105.6\tasks\XamarinTestCloud\1.0.27\XamarinTestCloud.ps1
2016-09-21T17:15:41.6633265Z Submit C:\a\1\b\bin\Debug\MobileLifeCycleSampleApp.MobileLifeCycleSampleApp.apk to Xamarin Test Cloud.
2016-09-21T17:15:41.6673258Z C:\a\1\s\packages\Xamarin.UITest.1.3.15\tools\test-cloud.exe submit "C:\a\1\b\bin\Debug\MobileLifeCycleSampleApp.MobileLifeCycleSampleApp.apk" ********  --user brandon.minnick@xamarin.com --devices b0509cbf --series "master" --locale "en_US" --assembly-dir "C:\a\1\s\MobileLifeCycleSampleApp\MobileLifeCycleSampleApp.UITest\bin\Debug\" --nunit-xml "C:\a\1\s\MobileLifeCycleSampleApp\MobileLifeCycleSampleApp.UITest\bin\Debug\xamarintest_98.0.xml"
2016-09-21T17:15:41.8783163Z ##[error]Illegal characters in path.
2016-09-21T17:15:41.8953161Z ##[error]System.Exception: Unexpected exit code 1 returned from tool test-cloud.exe
2016-09-21T17:15:41.8953161Z ##[error]   at Microsoft.TeamFoundation.DistributedTask.Task.Internal.PowerShell.InvokeToolCmdlet.ProcessRecord()
2016-09-21T17:15:41.8963166Z ##[error]   at System.Management.Automation.CommandProcessor.ProcessRecord()
```

**Previous Version**
This was how VSTS submitted to XTC before the "Test: Xamarin Test Cloud" build step was updated on 16 August
```
2016-08-13T18:55:42.4943773Z [command]C:/a/1/s/packages/Xamarin.UITest.1.3.14/tools/test-cloud.exe submit C:/a/1/b/bin/Release/MobileLifeCycleSampleApp.MobileLifeCycleSampleApp.apk e5220b51e1302ba7abf2725a3111b634 --user brandon.minnick@xamarin.com --devices b0509cbf --series master --locale en_US --assembly-dir C:\a\1\s\MobileLifeCycleSampleApp\MobileLifeCycleSampleApp.UITest\bin\Release\ --nunit-xml C:\a\1\s\MobileLifeCycleSampleApp\MobileLifeCycleSampleApp.UITest\bin\Release\xamarintest_79.0.xml
```

**Comment by madhurig** [comment]
@brminnick: Can you remove the trailing "\" in your build definition's "Test Assembly Dir" and see if it fixes your issue?

The difference you are seeing in the logged command is expected. XamarinTestCloud task was using .ts implementation prior to Aug 16 but we had to switch back to .ps implementation for publishing of nunit test results to Team Services to work from hosted build. The .ps implementation is not handling the trailing "\".

Thanks,
Madhuri

**Comment by brminnick** [comment]
Thanks @madhurig! 

I removed the trailing "\" and that fixed the problem!

I apologize for the red herring in regards to the double-quotes 😃

**Comment by madhurig** [comment]
Cool thanks!

**Comment by Athosone** [comment]
Same Issue here :(,
Any idea on how to remove these quotes from tfs ?
