### ISSUE TITLE
DeployAzureResourceGroup validation not handling blank override parameters

### ISSUE THREAD

**Issue by gustafsons** [Microsoft/vsts-tasks#2769]
When trying to validate the azure resource group deployment I've written using the Azure Resource manager deploy task in VSTS I keep getting an error:
```
2016-10-05T07:41:59.2415327Z [Azure Resource Manager]Validating Azure Resource Group Deployment Template
2016-10-05T07:41:59.6725412Z ##[error]A positional parameter cannot be found that accepts argument ''.
```

After some investigation, I figured out that it was because I wasn't specifying any Override Parameters in the task. If I run: 
```
Test-AzureRmResourceGroupDeployment -ResourceGroupName $resourceGroupName -TemplateFile $csmFile -TemplateParameterFile $csmParametersFile -Verbose -ErrorAction silentlyContinue
```

then it returns `VERBOSE: 09:30:06 - Template is valid.`

but if I give `$overrideParameters=""` then run the task with override parameters specified as it is in the task:
```
Test-AzureRmResourceGroupDeployment -ResourceGroupName $resourceGroupName -TemplateFile $csmFile -TemplateParameterFile $csmParametersFile $overrideParameters -Verbose -ErrorAction silentlyContinue
```

I get 
```
Test-AzureRmResourceGroupDeployment : A positional parameter cannot be found that accepts argument ''.
```

Is there something i'm missing here or does this need to be adjusted to handle when no override parameters are specified/is null?

**Comment by hiyadav** [comment]
@gustafsons thanks for identifying the bug correctly.
We will fix this issue soon.

**Comment by turowicz** [comment]
@hiyadav I've got a similar problem but the other way around. I specify all parameters, but it fails on the one that is a Base64-encoded string of length around 800 chars.

All overrides match template parameters by name. Checked it a dozen times.

The output is:

```
2016-10-18T09:18:33.3469326Z ##[debug]Processing: ##vso[task.logissue type=error;code=UNKNOWNDEP_Error;TaskId=94A74903-F93F-4075-884F-DC11F34058B4;]
2016-10-18T09:18:33.3539328Z ##[debug]Caught exception from task script.
2016-10-18T09:18:33.3569329Z ##[debug]Error record:
2016-10-18T09:18:33.4079315Z ##[debug]Invoke-Expression : A positional parameter cannot be found that accepts argument '<Base64 here>'.
2016-10-18T09:18:33.4089326Z ##[debug]At C:\Agent\_work\_tasks\AzureResourceGroupDeployment_94a74903-f93f-4075-884f-dc11f34058b4\1.0.91\AzureUtilityGTE1.0.ps1:75 char:5
2016-10-18T09:18:33.4099328Z ##[debug]+     Invoke-Expression -Command $finalCommand
2016-10-18T09:18:33.4109327Z ##[debug]+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2016-10-18T09:18:33.4119326Z ##[debug]    + CategoryInfo          : InvalidArgument: (:) [Invoke-Expression], ParameterBindingException
2016-10-18T09:18:33.4129328Z ##[debug]    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.InvokeExpressionCommand
2016-10-18T09:18:33.4149321Z ##[debug] 
2016-10-18T09:18:33.4169328Z ##[debug]Script stack trace:
2016-10-18T09:18:33.4209335Z ##[debug]at <ScriptBlock>, <No file>: line 1
2016-10-18T09:18:33.4219328Z ##[debug]at Deploy-AzureResourceGroup, C:\Agent\_work\_tasks\AzureResourceGroupDeployment_94a74903-f93f-4075-884f-dc11f34058b4\1.0.91\AzureUtilityGTE1.0.ps1: line 75
2016-10-18T09:18:33.4229328Z ##[debug]at Create-AzureResourceGroup, C:\Agent\_work\_tasks\AzureResourceGroupDeployment_94a74903-f93f-4075-884f-dc11f34058b4\1.0.91\Utility.ps1: line 182
2016-10-18T09:18:33.4239326Z ##[debug]at Handle-ResourceGroupLifeCycleOperations, C:\Agent\_work\_tasks\AzureResourceGroupDeployment_94a74903-f93f-4075-884f-dc11f34058b4\1.0.91\DeployAzureResourceGroup.ps1: line 75
2016-10-18T09:18:33.4249329Z ##[debug]at <ScriptBlock>, C:\Agent\_work\_tasks\AzureResourceGroupDeployment_94a74903-f93f-4075-884f-dc11f34058b4\1.0.91\DeployAzureResourceGroup.ps1: line 110
2016-10-18T09:18:33.4269319Z ##[debug]at <ScriptBlock>, <No file>: line 1
2016-10-18T09:18:33.4279326Z ##[debug]at <ScriptBlock>, <No file>: line 22
2016-10-18T09:18:33.4499322Z ##[debug]at <ScriptBlock>, <No file>: line 18
2016-10-18T09:18:33.4509431Z ##[debug]at <ScriptBlock>, <No file>: line 1
2016-10-18T09:18:33.4529333Z ##[debug]Exception:
2016-10-18T09:18:33.4589326Z ##[debug]System.Management.Automation.ParameterBindingException: A positional parameter cannot be found that accepts argument '<Base64 here>'.
2016-10-18T09:18:33.4599318Z ##[debug]   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
2016-10-18T09:18:33.4609322Z ##[debug]   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
2016-10-18T09:18:33.4619326Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2016-10-18T09:18:33.4629333Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2016-10-18T09:18:33.4639336Z ##[debug]   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
2016-10-18T09:18:33.4649336Z ##[debug]   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
2016-10-18T09:18:33.4659331Z ##[debug]   at System.Management.Automation.ScriptBlock.InvokeWithPipeImpl(ScriptBlockClauseToInvoke clauseToInvoke, Boolean createLocalScope, Dictionary`2 functionsToDefine, List`1 variablesToDefine, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Object[] args)
2016-10-18T09:18:33.4669332Z ##[debug]   at System.Management.Automation.ScriptBlock.<>c__DisplayClassa.<InvokeWithPipe>b__8()
2016-10-18T09:18:33.4679336Z ##[debug]   at System.Management.Automation.Runspaces.RunspaceBase.RunActionIfNoRunningPipelinesWithThreadCheck(Action action)
2016-10-18T09:18:33.4689334Z ##[debug]   at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, Dictionary`2 functionsToDefine, List`1 variablesToDefine, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Object[] args)
2016-10-18T09:18:33.4709322Z ##[debug]   at System.Management.Automation.ScriptBlock.InvokeUsingCmdlet(Cmdlet contextCmdlet, Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Object[] args)
2016-10-18T09:18:33.4719319Z ##[debug]   at Microsoft.PowerShell.Commands.InvokeExpressionCommand.ProcessRecord()
2016-10-18T09:18:33.4729332Z ##[debug]   at System.Management.Automation.CommandProcessor.ProcessRecord()
2016-10-18T09:18:33.4889337Z ##[debug]Processing: ##vso[task.logissue type=error]A positional parameter cannot be found that accepts argument '<Base64 here>'.
2016-10-18T09:18:33.4889337Z ##[error]A positional parameter cannot be found that accepts argument '<Base64 here>'.
```
