### ISSUE TITLE
Publish Artifact fails intermittently

### ISSUE THREAD

**Issue by smattt** [Microsoft/vsts-tasks#2978]
We have a handful of tasks in our Build + Deploy pipeline that fail about 10% of the time. They are causing our overall pipeline to become very unreliable. The Publish Artifact task is fairly solid but we encounter this error a few times each day:

Publish artifact drop
2016-10-28T22:27:39.5644012Z Upload 'C:\booyamiBuild_work\1\a' to file container: '#/140220/drop'
2016-10-28T22:27:39.9378031Z ##[section]Async Command End: Upload Artifact
**2016-10-28T22:27:39.9534018Z ##[error]Error while copying content to a stream.**
2016-10-28T22:27:39.9690249Z ##[section]Finishing: Publish Artifact: drop

We host a build agent on an Azure VM that is dedicated to our build and release work. We used to have two build agents running but I've throttled it down to one until we resolve these reliability issues. The machine is an F2 and has about 45GB of free disk space. If I hit a failure in this task, then queue a new build - the new build will hardly ever fail on that step.

Same machine, same code, same build agent - different results for Publish Artifact :(

Do you have any idea how we could resolve this? We want this step to be reliable.

**Comment by ericsciple** [comment]
what agent version?

**Comment by smattt** [comment]
We had been running 2.07 but I'm upgrading us now to 2.08.

**Comment by ericsciple** [comment]
@TingluoHuang thoughts?

fyi you can update from the pool admin UI.

**Comment by smattt** [comment]
Thanks, I did try that but it felt like it no-op'ed. After requesting the upgrade, I got no visual feedback. I waited maybe 30 minutes and my build agents were still on 2.07 so then I went ahead and manually upgraded them.

Unfortunately, I see the same issue on 2.08 :(

******************************************************************************
Starting: Publish Artifact: drop
******************************************************************************
==============================================================================
Task         : Publish Build Artifacts
Description  : Publish Build artifacts to the server or a file share
Version      : 1.0.38
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=708390)
==============================================================================
******************************************************************************
Async Command Start: Upload Artifact
******************************************************************************
******************************************************************************
Async Command End: Upload Artifact
******************************************************************************
An error occurred while sending the request.
******************************************************************************
Finishing: Publish Artifact: drop
**********************************************************************************

**Comment by ericsciple** [comment]
Can you email me (ersciple) the build log (download zip from build summary page) and also grab the worker log from the _diag folder of the agent (email is at microsoft com)?

@TingluoHuang has done a ton of investigation and many improvements for artifact upload resiliency. He's very familiar with the details of that code. I'll chat with him on Monday.

**Comment by bryanmacfarlane** [comment]
Might be a bug for this repo since upload file is a command in the agent the task calls:  https://github.com/Microsoft/vsts-agent

**Comment by smattt** [comment]
Thank you, Eric. I've sent the build log and the worker log to your MSFT alias email.

Hi Bryan. I'd be happy to create a bug on the agent, if you think that's a better spot for it. I can't really tell, from the logs, where the issue lies:

`
[2016-10-29 01:08:26Z INFO JobServerQueue] Try to append 2 batches web console lines, success rate: 2/2.
[2016-10-29 01:08:27Z INFO JobServerQueue] Try to append 1 batches web console lines, success rate: 1/1.
[2016-10-29 01:08:27Z INFO ProcessInvoker] Finished process with exit code 0, and elapsed time 00:00:00.5564540.
[2016-10-29 01:08:27Z INFO AsyncCommandContext] Start flush buffered output.
[2016-10-29 01:08:27Z INFO AsyncCommandContext] Finsh flush buffered output.
[2016-10-29 01:08:27Z INFO AsyncCommandContext] Wait till async command task to finish.
[2016-10-29 01:08:27Z INFO JobServerQueue] Try to upload 4 log files or attachments, success rate: 4/4.
[2016-10-29 01:08:27Z ERR  StepsRunner] Caught exception from async command Upload Artifact: System.Net.Http.HttpRequestException: Error while copying content to a stream. ---> System.IO.IOException: The read operation failed, see inner exception. ---> System.Net.Http.WinHttpException: A security error occurred
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.StreamToStreamCopy.<CopyAsyncAnyStreamToAnyStreamCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpContent.<LoadIntoBufferAsyncCore>d__48.MoveNext()
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpContent.<LoadIntoBufferAsyncCore>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__42`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.<GetConnectionDataAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.<ConnectAsync>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.<EnsureConnectedAsync>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.<FindServiceDefinitionsAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.<GetResourceLocationsAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssConnection.<GetClientInstanceAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssConnection.<GetClientServiceImplAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssConnection.<GetClientAsync>d__11`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.TaskExtensions.SyncResult[T](Task`1 task)
   at Microsoft.VisualStudio.Services.WebApi.VssConnection.GetClient[T]()
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.FileContainerServer..ctor(VssConnection connection, Guid projectId, Int64 containerId, String containerPath)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.ArtifactCommandExtension.<UploadArtifactAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.AsyncCommandContext.<WaitAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.<RunAsync>d__0.MoveNext()
[2016-10-29 01:08:27Z INFO StepsRunner] Step result: Failed
[2016-10-29 01:08:27Z INFO StepsRunner] Current state: job state = 'Failed', step failed = True, critical step failed = False
[2016-10-29 01:08:27Z INFO StepsRunner] Processing step: DisplayName='Post Job Cleanup', AlwaysRun=False, ContinueOnError=False, Critical=False, Enabled=True, Finally=True
[2016-10-29 01:08:27Z INFO StepsRunner] Starting the step.`

**Comment by smattt** [comment]
I saw a new variant pop up today, with a 'security error occurred' WinHttpException.

`******************************************************************************
Async Command End: Upload Artifact
******************************************************************************
Error while copying content to a stream.
System.Net.Http.HttpRequestException: Error while copying content to a stream. ---> System.IO.IOException: The read operation failed, see inner exception. ---> System.Net.Http.WinHttpException: A security error occurred
******************************************************************************
Finishing: Publish Artifact: drop
******************************************************************************`

**Comment by ericsciple** [comment]
(continuing on agent repo)
