### ISSUE TITLE
Windows machine file copy task missing powershell dependencies

### ISSUE THREAD

**Issue by jrexdepew** [Microsoft/vsts-tasks#2999]
When following the guide located [here](https://www.visualstudio.com/en-us/docs/release/examples/other-servers/net-to-workgroup-vm) we are encountering an error when the windows machine file copy task is run.

visual studio account: https://nucor.visualstudio.com 

```
2016-11-01T18:50:29.3441889Z Finished artifacts download
 
2016-11-01T18:50:29.3441889Z ##[section]Finishing: Download Artifacts
 
2016-11-01T18:50:29.3598083Z ##[section]Starting: Copy files from $(System.DefaultWorkingDirectory)/NSARWebSite WinRM Deploy UAT/deploy
 
2016-11-01T18:50:29.4223143Z ==============================================================================
 
2016-11-01T18:50:29.4223143Z Task         : Windows Machine File Copy
 
2016-11-01T18:50:29.4223143Z Description  : Copy files to remote machine(s)
 
2016-11-01T18:50:29.4223143Z Version      : 1.0.36
 
2016-11-01T18:50:29.4223143Z Author       : Microsoft Corporation
 
2016-11-01T18:50:29.4223143Z Help         : [More Information](https://go.microsoft.com/fwlink/?linkid=627415)
 
2016-11-01T18:50:29.4223143Z ==============================================================================
 
2016-11-01T18:50:29.4691811Z Preparing task execution handler.
 
2016-11-01T18:50:30.5786574Z Executing the powershell script: C:\vstsagent\_work\_tasks\WindowsMachineFileCopy_731004d4-1d66-4f70-8c05-638018b22210\1.0.36\WindowsMachineFileCopy.ps1
 
2016-11-01T18:50:30.5941973Z ##[error]System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.TeamFoundation.DistributedTask.Agent.Interfaces, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
 
2016-11-01T18:50:30.5941973Z File name: 'Microsoft.TeamFoundation.DistributedTask.Agent.Interfaces, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
 
2016-11-01T18:50:30.5941973Z    at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
 
2016-11-01T18:50:30.5941973Z    at System.Reflection.RuntimeAssembly.GetExportedTypes()
 
2016-11-01T18:50:30.5941973Z    at System.Management.Automation.Runspaces.PSSnapInHelpers.GetAssemblyTypes(Assembly assembly, String name)
 
2016-11-01T18:50:30.5941973Z    at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzePSSnapInAssembly(Assembly assembly, String name, PSSnapInInfo psSnapInInfo, PSModuleInfo moduleInfo, Boolean isModuleLoad, Dictionary`2& cmdlets, Dictionary`2& providers, String& helpFile)
 
2016-11-01T18:50:30.5941973Z    at System.Management.Automation.Runspaces.InitialSessionState.ImportCmdletsFromAssembly(Assembly assembly, PSModuleInfo module)
 
2016-11-01T18:50:30.5941973Z    at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadBinaryModule(PSModuleInfo parentModule, Boolean trySnapInName, String moduleName, String fileName, Assembly assemblyToLoad, String moduleBase, SessionState ss, ImportModuleOptions options, ManifestProcessingFlags manifestProcessingFlags, String prefix, Boolean loadTypes, Boolean loadFormats, Boolean& found, String shortModuleName, Boolean disableFormatUpdates)
 
2016-11-01T18:50:30.5941973Z    at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadBinaryModule(Boolean trySnapInName, String moduleName, String fileName, Assembly assemblyToLoad, String moduleBase, SessionState ss, ImportModuleOptions options, ManifestProcessingFlags manifestProcessingFlags, String prefix, Boolean loadTypes, Boolean loadFormats, Boolean& found)
 
2016-11-01T18:50:30.5941973Z    at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModule(PSModuleInfo parentModule, String fileName, String moduleBase, String prefix, SessionState ss, Object privateData, ImportModuleOptions& options, ManifestProcessingFlags manifestProcessingFlags, Boolean& found, Boolean& moduleFileFound)
 
2016-11-01T18:50:30.5941973Z    at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadUsingExtensions(PSModuleInfo parentModule, String moduleName, String fileBaseName, String extension, String moduleBase, String prefix, SessionState ss, ImportModuleOptions options, ManifestProcessingFlags manifestProcessingFlags, Boolean& found, Boolean& moduleFileFound)
 
2016-11-01T18:50:30.5941973Z    at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadUsingModulePath(PSModuleInfo parentModule, Boolean found, IEnumerable`1 modulePath, String name, SessionState ss, ImportModuleOptions options, ManifestProcessingFlags manifestProcessingFlags, PSModuleInfo& module)
 
2016-11-01T18:50:30.5941973Z    at Microsoft.PowerShell.Commands.ImportModuleCommand.ImportModule_LocallyViaName(ImportModuleOptions importModuleOptions, String name)
 
2016-11-01T18:50:30.5941973Z    at Microsoft.PowerShell.Commands.ImportModuleCommand.ProcessRecord()
 
2016-11-01T18:50:30.5941973Z    at System.Management.Automation.CommandProcessor.ProcessRecord()
 
2016-11-01T18:50:30.5941973Z 
 
2016-11-01T18:50:30.5941973Z WRN: Assembly binding logging is turned OFF.
 
2016-11-01T18:50:30.6098257Z To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
 
2016-11-01T18:50:30.6098257Z Note: There is some performance penalty associated with assembly bind failure logging.
 
2016-11-01T18:50:30.6098257Z To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
 
2016-11-01T18:50:30.6098257Z 
 
2016-11-01T18:50:30.6254479Z ##[error]System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.TeamFoundation.DistributedTask.Agent.Interfaces, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
 
2016-11-01T18:50:30.6254479Z File name: 'Microsoft.TeamFoundation.DistributedTask.Agent.Interfaces, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
 
2016-11-01T18:50:30.6254479Z    at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
 
2016-11-01T18:50:30.6254479Z    at System.Reflection.RuntimeAssembly.GetExportedTypes()
 
2016-11-01T18:50:30.6254479Z    at System.Management.Automation.Runspaces.PSSnapInHelpers.GetAssemblyTypes(Assembly assembly, String name)
 
2016-11-01T18:50:30.6254479Z    at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzePSSnapInAssembly(Assembly assembly, String name, PSSnapInInfo psSnapInInfo, PSModuleInfo moduleInfo, Boolean isModuleLoad, Dictionary`2& cmdlets, Dictionary`2& providers, String& helpFile)
 
2016-11-01T18:50:30.6254479Z    at System.Management.Automation.Runspaces.InitialSessionState.ImportCmdletsFromAssembly(Assembly assembly, PSModuleInfo module)
 
2016-11-01T18:50:30.6410706Z    at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadBinaryModule(PSModuleInfo parentModule, Boolean trySnapInName, String moduleName, String fileName, Assembly assemblyToLoad, String moduleBase, SessionState ss, ImportModuleOptions options, ManifestProcessingFlags manifestProcessingFlags, String prefix, Boolean loadTypes, Boolean loadFormats, Boolean& found, String shortModuleName, Boolean disableFormatUpdates)
 
2016-11-01T18:50:30.6410706Z    at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadBinaryModule(Boolean trySnapInName, String moduleName, String fileName, Assembly assemblyToLoad, String moduleBase, SessionState ss, ImportModuleOptions options, ManifestProcessingFlags manifestProcessingFlags, String prefix, Boolean loadTypes, Boolean loadFormats, Boolean& found)
 
2016-11-01T18:50:30.6410706Z    at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModule(PSModuleInfo parentModule, String fileName, String moduleBase, String prefix, SessionState ss, Object privateData, ImportModuleOptions& options, ManifestProcessingFlags manifestProcessingFlags, Boolean& found, Boolean& moduleFileFound)
 
2016-11-01T18:50:30.6410706Z    at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadUsingExtensions(PSModuleInfo parentModule, String moduleName, String fileBaseName, String extension, String moduleBase, String prefix, SessionState ss, ImportModuleOptions options, ManifestProcessingFlags manifestProcessingFlags, Boolean& found, Boolean& moduleFileFound)
 
2016-11-01T18:50:30.6410706Z    at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadUsingModulePath(PSModuleInfo parentModule, Boolean found, IEnumerable`1 modulePath, String name, SessionState ss, ImportModuleOptions options, ManifestProcessingFlags manifestProcessingFlags, PSModuleInfo& module)
 
2016-11-01T18:50:30.6410706Z    at Microsoft.PowerShell.Commands.ImportModuleCommand.ImportModule_LocallyViaName(ImportModuleOptions importModuleOptions, String name)
 
2016-11-01T18:50:30.6410706Z    at Microsoft.PowerShell.Commands.ImportModuleCommand.ProcessRecord()
 
2016-11-01T18:50:30.6410706Z    at System.Management.Automation.CommandProcessor.ProcessRecord()
 
2016-11-01T18:50:30.6410706Z 
 
2016-11-01T18:50:30.6410706Z WRN: Assembly binding logging is turned OFF.
 
2016-11-01T18:50:30.6410706Z To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
 
2016-11-01T18:50:30.6410706Z Note: There is some performance penalty associated with assembly bind failure logging.
 
2016-11-01T18:50:30.6410706Z To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
 
2016-11-01T18:50:30.6410706Z
```

**Comment by KrishnaAdityaB** [comment]
@jrexdepew 
I am not able to reproduce this issue with agent versioned 2.108.0
What is your agent version? If it is older - can you upgrade it?

How to get Agent Version:
You can see it in the release logs.
```
2016-11-02T09:01:16.5816450Z ##[section]Starting: Release
 
2016-11-02T09:01:16.6128980Z Current agent version: '2.108.0'
 
2016-11-02T09:01:19.4649900Z ##[section]Starting: Download Artifacts
 
2016-11-02T09:01:19.4806186Z ReleaseId=1, TeamProjectId=5e917099-bcb7-4e5e-9126-c33b49a65b4a, ReleaseDefinitionName=WFC-PS
 
2016-11-02T09:01:19.5274985Z Release folder: C:\agents\wfcps\_work\r1\a
 
2016-11-02T09:01:19.5431447Z Environment variables available are below.  Note that these environment variables can be referred to in the task (in the ReleaseDefinition) by replacing "_" with "." e.g. AGENT_NAME environment variable can be referenced using Agent.Name in the ReleaseDefinition: 
 
				[AGENT_ID] --> [6]
 
				[SYSTEM_JOBPOSITIONINPHASE] --> [1]
 
				[SYSTEM_PLANID] --> [84602a04-6365-4d75-944f-14de5c710c30]
```

**Comment by jrexdepew** [comment]
vsts agent x64 2.108.0 - Windows Server 2012 R2 Standard.

When following the guide that I posted, I downloaded the agent from VSTS on the agent settings screen.

The windows machine file copy task is version 1.0.36.  Is there any other information that might be useful?

**Comment by KrishnaAdityaB** [comment]
@jrexdepew 
Can you send me the debug logs?
Set a Release variable with name "System.Debug" and value "true". Queue the release. Please share me the logs of the task and corresponding logs from agent's _diag folder too.

You can mail the logs to me at RM_Customer_Queries at microsoft.com.

**Comment by KrishnaAdityaB** [comment]
@jrexdepew 
I am not able to reproduce this with VSTS account and vsts-agent-win7-x64-2.108.0.

My agent folder didn't have any *.Interfaces.dll. I ran the _tree /a /f_ command in the agent folder and shared the result here. [agent-tree.txt](https://github.com/Microsoft/vsts-tasks/files/592046/agent-tree.txt)

I enabled fusion logs while the build is running. The logs has no reference to that *Interfaces*. I shared those logs too.
[FusionLogs.zip](https://github.com/Microsoft/vsts-tasks/files/592048/FusionLogs.zip)

If this issue is resolved for you, already - please share the resolution.
Else please share the debug logs, output of _tree /a /f_ command and fusion logs.

**Comment by MrDoctorJ** [comment]
@KrishnaAdityaB 

I am developer helping @jrexdepew with this issue. I have emailed our agent output and logs to the above mentioned email address. Please let us know if there is anything else you need.

**Comment by MrDoctorJ** [comment]
The issue has been resolved. We have some modules installed in the wrong place (C:\Windows\System32\WindowsPowerShell\v1.0\Modules). As suggested by Krishna, removing the modules that were throwing errors from this directory solved our problem. Thanks so much for your help @KrishnaAdityaB .
