### ISSUE TITLE
Deploy AzureRM Web App task fails because of missing file

### ISSUE THREAD

**Issue by saschagottfried** [Microsoft/vsts-tasks#3074]
`Deploy AzureRM Web App` task fails with version 2.1.3. Some hours ago this task used version 2.1.2 and everything went fine.

```
2016-11-11T13:25:14.8013148Z ##[section]Starting: Deploy AzureRM Web App: 
2016-11-11T13:25:14.8522053Z ==============================================================================
2016-11-11T13:25:14.8522053Z Task         : Azure App Service Deploy
2016-11-11T13:25:14.8522053Z Description  : Update Azure App Service using Web Deploy / Kudu REST APIs 
2016-11-11T13:25:14.8522053Z Version      : 2.1.3
2016-11-11T13:25:14.8522053Z Author       : Microsoft Corporation
2016-11-11T13:25:14.8522053Z Help         : [More Information](https://aka.ms/azurermwebdeployreadme)
2016-11-11T13:25:14.8522053Z ==============================================================================
2016-11-11T13:25:15.2162733Z ##[error]File not found: 'C:\a\_tasks\AzureRmWebAppDeploy_497d490f-eea7-4f2b-ab94-48d9c1acdcb1\2.1.3\azurermwebappdeployment.js'
```

**Comment by drageam** [comment]
I got same problem. 
A few hours ago, with 2.1.2, it works. Now 2.1.3 same problem.

**Comment by Larswa** [comment]
Got same problem with 2.1.3. My last successfull deploy used 2.0.7 and was run Wednesday 9th November

**Comment by dhoare12** [comment]
Same issue - looks like the task updated to 2.1.3 at midday today and deployments have all been failing since then.
Logging onto the box we see that the "task.zip" file is still present in `/_work/_tasks/AzureRmWebAppDeploy_49.../2.1.3/` and that not all the assets have been extracted from this file. As a workaround **unzipping this zip file in the 2.1.3 folder seems to fix the issue**.

**Comment by aL3891** [comment]
Same problem here :/

**Comment by LadislavMargai** [comment]
Same problem here. My last successful deploy was _2016-11-11T10:44:27_ with **2.1.2**

**Comment by dagus** [comment]
Same problem here to

**Comment by treierts** [comment]
We have the same issue as well, this is the error we get:

`2016-11-11T13:02:04.7551688Z ##[error]File not found: 'C:\agent\_work\_tasks\AzureRmWebAppDeploy_497d490f-eea7-4f2b-ab94-48d9c1acdcb1\2.1.3\azurermwebappdeployment.js'`

This is the timestamp of the first occurence of this today on our build hosts.

**Comment by PeterOrneholm** [comment]
Same issue for us :/

**Comment by shadjamal** [comment]
Same here :-(

**Comment by lasrol** [comment]
Anyway to force it to use 2.1.2?

**Comment by aadje** [comment]
We are getting a similar error since 2.1.3 :
```
2016-11-11T14:18:29.6808379Z ##[warning]File name doesn't indicate a full path to a executable file.
2016-11-11T14:18:29.6808379Z Set workingFolder to default: D:\VsTsAgent\_work\SourceRootMapping\1d381850-f16b-4ab1-807f-11d95d0eb850\Job-035d6c31-5f2b-4967-8a59-b9d175a13011
2016-11-11T14:18:29.6848419Z ##[error]System.ComponentModel.Win32Exception (0x80004005): The directory name is invalid
2016-11-11T14:18:29.6858429Z ##[error]   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
```

**Comment by jakobehn** [comment]
If you have access to the build server, a temporary workaround is to unzip the task.zip inside the 2.1.3 folder of the AzureRMWebApp task

**Comment by adonnelly** [comment]
same here, really bad timing too. Started happening around 2 hours ago. A release at 11:30 GMT succeded. Redeploying the same release 2hrs ago failed. I can see task.zip. Unzipping this zip file in the 2.1.3 folder did not fix the issue as the folder got cleaned next release.

**Comment by b4rj** [comment]
Same here

**Comment by asadsahi** [comment]
Same here :(

**Comment by CKGrafico** [comment]
the same!!!

**Comment by mravko** [comment]
Same here...

**Comment by dsschnau** [comment]
same

**Comment by carlwoodhouse** [comment]
same issues as @aadje

**Comment by larsJoakimNilsson** [comment]
@jakobehn (long time no see ;)

Tnx Jacob... that work!

**Comment by ASeale** [comment]
The work around worked for me. Not sure why it erased for @adonnelly.

**Comment by alfredodev** [comment]
I copied the contents of 2.1.2 inside 2.1.3 and our build worked...

**Comment by CKGrafico** [comment]
@alfredodev solution fixed everything

**Comment by asadsahi** [comment]
Sorry what is the fix.

Is this on VSTS side or something end user have to do?

**Comment by RDalziel** [comment]
Getting this too

**Comment by mravko** [comment]
@asadsahi On the build agent you should go to the _work\_tasks\AzureRmWebAppDeploy(something)\2.1.3 directory and extract the task.zip in the 2.1.3 directory, as @jakobehn suggested. It worked for me.

**Comment by b4rj** [comment]
@mravko, what if you are using "Hosted" agente queue?

**Comment by mravko** [comment]
Can't help you there. Sorry. Maybe some else can.

**Comment by asadsahi** [comment]
Appologies for lack of my knowledge.

I am on Hosted agent too, Can we create a Default agent? 

Reading [this ](http://stackoverflow.com/questions/34483414/difference-between-default-and-hosted-agent-queue) SO answer Default agent seems to be on premises only or it can be in cloud too?

**Comment by adonnelly** [comment]
Tried the work around. Initially it seemed to be cleaning the directory after each release, but not anymore (maybe I imagined it). Anyway getting a slightly different error now.
[section]Starting: Deploy AzureRM App Service: XXXXXXXXXXXXXXX
module.js:341
throw err;
^
Error: Cannot find module 'vsts-task-lib/task'
at Function.Module._resolveFilename (module.js:339:15)
at Function.Module._load (module.js:290:25)
at Module.require (module.js:367:17)
at require (internal/module.js:16:19)
at Object.<anonymous> (C:\agent\_work\_tasks\AzureRmWebAppDeploy_497d490f-eea7-4f2b-ab94-48d9c1acdcb1\2.1.3\azurermwebappdeployment.js:10:12)
 at Module._compile (module.js:413:34)
 at Object.Module._extensions..js (module.js:422:10)
 at Module.load (module.js:357:32)
 at Function.Module._load (module.js:314:12)
 at Function.Module.runMain (module.js:447:10)
 ##[error]Exit code 1 returned from process: file name 'C:\agent\externals\node\bin\node.exe', arguments '"C:\agent\_work\_tasks\AzureRmWebAppDeploy_497d490f-eea7-4f2b-ab94-48d9c1acdcb1\2.1.3\azurermwebappdeployment.js"'.
 ##[section]Finishing: Deploy AzureRM App Service: xxxxxx

**Comment by mvvsubbu** [comment]
Sorry for the inconvenience we fixed the issue, you should be able to use the task.

**Comment by asadsahi** [comment]
indeed it does. Thanks @mvvsubbu

**Comment by RDalziel** [comment]
Confirmed here!

**Comment by b4rj** [comment]
Confirmed

**Comment by wbunle** [comment]
Confirmed here.
