### ISSUE TITLE
VSTS MacinCloud agent build stucked at xcode build

### ISSUE THREAD

**Issue by alexszilagyi** [Microsoft/vsts-tasks#3156]
I'm using [MacInCloud integration (MAC solution provider)](https://www.macincloud.com/). and managed to make a build definition for iOS but it gets stuck at the xCode build, below I'll attach my logs.

I've contacted [MacInCloud](https://www.macincloud.com/) and they've said:

> For all build difficulties you should contact Microsoft as the build agent is working properly, you may simply need a later version of agent to build if your local environment is on a later agent version.

Has anyone faced this issue before? How have been sorted out / solved?

**VSTS logs:**
```diff
2016-11-25T22:52:47.5900870Z ##[section]Starting: Xcode build clean
2016-11-25T22:52:47.6781800Z ==============================================================================
2016-11-25T22:52:47.6805030Z Task         : Xcode Build
2016-11-25T22:52:47.6826780Z Description  : Build an Xcode workspace on Mac OS
2016-11-25T22:52:47.6849450Z Version      : 2.3.5
2016-11-25T22:52:47.6870810Z Author       : Microsoft Corporation
2016-11-25T22:52:47.6893750Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613730)
2016-11-25T22:52:47.6914400Z ==============================================================================
2016-11-25T22:52:48.2900280Z ##[debug]agent.workFolder=/Users/vso112885/vsts-agent/_work
2016-11-25T22:52:48.2941910Z ##[debug]loading inputs and endpoints
2016-11-25T22:52:48.2967810Z ##[debug]loading INPUT_ACTIONS
2016-11-25T22:52:48.2993340Z ##[debug]loading INPUT_CONFIGURATION
2016-11-25T22:52:48.3017960Z ##[debug]loading INPUT_SDK
2016-11-25T22:52:48.3043930Z ##[debug]loading INPUT_XCWORKSPACEPATH
2016-11-25T22:52:48.3074250Z ##[debug]loading INPUT_SCHEME
2016-11-25T22:52:48.3097850Z ##[debug]loading INPUT_PACKAGEAPP
2016-11-25T22:52:48.3122670Z ##[debug]loading INPUT_ARCHIVEPATH
2016-11-25T22:52:48.3172990Z ##[debug]loading INPUT_EXPORTPATH
2016-11-25T22:52:48.3199800Z ##[debug]loading INPUT_EXPORTOPTIONS
2016-11-25T22:52:48.3225210Z ##[debug]loading INPUT_EXPORTMETHOD
2016-11-25T22:52:48.3269510Z ##[debug]loading INPUT_EXPORTTEAMID
2016-11-25T22:52:48.3297630Z ##[debug]loading INPUT_EXPORTOPTIONSPLIST
2016-11-25T22:52:48.3320900Z ##[debug]loading INPUT_XCODE8AUTOMATICSIGNING
2016-11-25T22:52:48.3344730Z ##[debug]loading INPUT_SIGNMETHOD
2016-11-25T22:52:48.3369540Z ##[debug]loading INPUT_IOSSIGNINGIDENTITY
2016-11-25T22:52:48.3397130Z ##[debug]loading INPUT_UNLOCKDEFAULTKEYCHAIN
2016-11-25T22:52:48.3423740Z ##[debug]loading INPUT_P12
2016-11-25T22:52:48.3448870Z ##[debug]loading INPUT_PROVPROFILE
2016-11-25T22:52:48.3473100Z ##[debug]loading INPUT_REMOVEPROFILE
2016-11-25T22:52:48.3496640Z ##[debug]loading INPUT_ARGS
2016-11-25T22:52:48.3519230Z ##[debug]loading INPUT_CWD
2016-11-25T22:52:48.3543460Z ##[debug]loading INPUT_OUTPUTPATTERN
2016-11-25T22:52:48.3565950Z ##[debug]loading INPUT_USEXCPRETTY
2016-11-25T22:52:48.3588180Z ##[debug]loading INPUT_PUBLISHJUNITRESULTS
2016-11-25T22:52:48.3612070Z ##[debug]loading INPUT_USEXCTOOL
2016-11-25T22:52:48.3634240Z ##[debug]loading ENDPOINT_AUTH_$/
2016-11-25T22:52:48.3656630Z ##[debug]loading ENDPOINT_AUTH_SCHEME_$/
2016-11-25T22:52:48.3679100Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_$/_ACCESSTOKEN
2016-11-25T22:52:48.3701520Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
2016-11-25T22:52:48.3724100Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
2016-11-25T22:52:48.3746410Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
2016-11-25T22:52:48.3769830Z ##[debug]loading SECRET_P12_PWD
2016-11-25T22:52:48.3792710Z ##[debug]loaded 32
2016-11-25T22:52:48.3815400Z ##[debug]HOME=/Users/vso112885
2016-11-25T22:52:48.3838600Z ##[debug]Absolute path for pathSegments: /Users/vso112885,Library,MobileDevice,Provisioning Profiles = /Users/vso112885/Library/MobileDevice/Provisioning Profiles
2016-11-25T22:52:48.3864940Z ##[debug]check path : /Users/vso112885/vsts-agent/_work/_tasks/Xcode_1e78dc1b-9132-4b18-9c75-0e7ecc634b74/2.3.5/task.json
2016-11-25T22:52:48.3891220Z ##[debug]set resource file to: /Users/vso112885/vsts-agent/_work/_tasks/Xcode_1e78dc1b-9132-4b18-9c75-0e7ecc634b74/2.3.5/task.json
2016-11-25T22:52:48.3916770Z ##[debug]system.culture=en-US
2016-11-25T22:52:48.3940050Z ##[debug]xcodeDeveloperDir=null
2016-11-25T22:52:48.3962770Z ##[debug]useXctool=false
2016-11-25T22:52:48.3989360Z ##[debug]check path : /usr/bin/xcodebuild
2016-11-25T22:52:48.4013460Z ##[debug]xcodebuild=/usr/bin/xcodebuild
2016-11-25T22:52:48.4035990Z ##[debug]Tool selected: /usr/bin/xcodebuild
2016-11-25T22:52:48.4068900Z ##[debug]cwd=/Users/vso112885/vsts-agent/_work/1/s/ProjectApp/platforms/ios/
2016-11-25T22:52:48.4096210Z ##[debug]outputPattern=output/iphoneos/Debug
2016-11-25T22:52:48.4125690Z ##[debug]Absolute path for pathSegments: /Users/vso112885/vsts-agent/_work/1/s/ProjectApp/platforms/ios/,output/iphoneos/Debug = /Users/vso112885/vsts-agent/_work/1/s/ProjectApp/platforms/ios/output/iphoneos/Debug
2016-11-25T22:52:48.4154040Z ##[debug]testing directory '/Users/vso112885/vsts-agent/_work/1/s/ProjectApp/platforms/ios/output/iphoneos/Debug'
2016-11-25T22:52:48.4184710Z ##[debug]testing directory '/Users/vso112885/vsts-agent/_work/1/s/ProjectApp/platforms/ios/output/iphoneos'
2016-11-25T22:52:48.4213110Z ##[debug]testing directory '/Users/vso112885/vsts-agent/_work/1/s/ProjectApp/platforms/ios/output'
2016-11-25T22:52:48.4240710Z ##[debug]testing directory '/Users/vso112885/vsts-agent/_work/1/s/ProjectApp/platforms/ios'
2016-11-25T22:52:48.4269220Z ##[debug]mkdir '/Users/vso112885/vsts-agent/_work/1/s/ProjectApp/platforms/ios/output'
2016-11-25T22:52:48.4307020Z ##[debug]mkdir '/Users/vso112885/vsts-agent/_work/1/s/ProjectApp/platforms/ios/output/iphoneos'
2016-11-25T22:52:48.4339190Z ##[debug]mkdir '/Users/vso112885/vsts-agent/_work/1/s/ProjectApp/platforms/ios/output/iphoneos/Debug'
2016-11-25T22:52:48.4370530Z ##[debug]xcWorkspacePath=/Users/vso112885/vsts-agent/_work/1/s
2016-11-25T22:52:48.4400980Z ##[debug]xcWorkspacePath=/Users/vso112885/vsts-agent/_work/1/s
2016-11-25T22:52:48.4431560Z ##[debug]Absolute path for pathSegments: /Users/vso112885/vsts-agent/_work/1/s = /Users/vso112885/vsts-agent/_work/1/s
2016-11-25T22:52:48.4461020Z ##[debug]build.sourcesDirectory=/Users/vso112885/vsts-agent/_work/1/s
2016-11-25T22:52:48.4490220Z ##[debug]Absolute path for pathSegments: /Users/vso112885/vsts-agent/_work/1/s = /Users/vso112885/vsts-agent/_work/1/s
2016-11-25T22:52:48.4516850Z ##[debug]xcWorkspacePathpath supplied :false
2016-11-25T22:52:48.4539180Z ##[debug]sdk=iphoneos
2016-11-25T22:52:48.4560090Z ##[debug]configuration=Debug
2016-11-25T22:52:48.4586780Z ##[debug]scheme=Project
2016-11-25T22:52:48.4611620Z ##[debug]useXcpretty=false
2016-11-25T22:52:48.4634640Z ##[debug]xctoolReporter=null
2016-11-25T22:52:48.4659830Z ##[debug]actions=build clean
2016-11-25T22:52:48.4684990Z ##[debug]packageApp=true
2016-11-25T22:52:48.4712450Z ##[debug]args=-project /Users/vso112885/vsts-agent/_work/1/s/ProjectApp/platforms/ios/Project.xcodeproj
2016-11-25T22:52:48.4746060Z ##[debug]/usr/bin/xcodebuild arg: -version
2016-11-25T22:52:48.4775160Z ##[debug]exec tool: /usr/bin/xcodebuild
2016-11-25T22:52:48.4800850Z ##[debug]Arguments:
2016-11-25T22:52:48.4827670Z ##[debug]   -version
2016-11-25T22:52:48.4855270Z [command]/usr/bin/xcodebuild -version
2016-11-25T22:52:48.4881240Z ##[debug]match = Xcode 7.3.1
2016-11-25T22:52:48.4905320Z ##[debug]version = 7
2016-11-25T22:52:48.4928860Z Xcode 7.3.1
2016-11-25T22:52:48.4952010Z ##[debug]match = null
2016-11-25T22:52:48.4977530Z Build version 7D1014
2016-11-25T22:52:48.5001350Z ##[debug]rc:0
2016-11-25T22:52:48.5026090Z ##[debug]success:true
2016-11-25T22:52:48.5050970Z ##[debug]xcodeVersion = 7
2016-11-25T22:52:48.5077600Z ##[debug]/usr/bin/xcodebuild arg: ["-sdk","iphoneos"]
2016-11-25T22:52:48.5102440Z ##[debug]/usr/bin/xcodebuild arg: ["-configuration","Debug"]
2016-11-25T22:52:48.5128220Z ##[debug]xcWorkspacePath=/Users/vso112885/vsts-agent/_work/1/s
2016-11-25T22:52:48.5196820Z ##[debug]Absolute path for pathSegments: /Users/vso112885/vsts-agent/_work/1/s = /Users/vso112885/vsts-agent/_work/1/s
2016-11-25T22:52:48.5272540Z ##[debug]build.sourcesDirectory=/Users/vso112885/vsts-agent/_work/1/s
2016-11-25T22:52:48.5296060Z ##[debug]Absolute path for pathSegments: /Users/vso112885/vsts-agent/_work/1/s = /Users/vso112885/vsts-agent/_work/1/s
2016-11-25T22:52:48.5321850Z ##[debug]xcWorkspacePathpath supplied :false
2016-11-25T22:52:48.5354040Z ##[debug]/usr/bin/xcodebuild arg: ["-scheme","Project"]
2016-11-25T22:52:48.5382100Z ##[debug]/usr/bin/xcodebuild arg: ["build","clean"]
2016-11-25T22:52:48.5427940Z ##[debug]Absolute path for pathSegments: /Users/vso112885/vsts-agent/_work/1/s/ProjectApp/platforms/ios/output/iphoneos/Debug,build.dst = /Users/vso112885/vsts-agent/_work/1/s/ProjectApp/platforms/ios/output/iphoneos/Debug/build.dst
2016-11-25T22:52:48.5467650Z ##[debug]/usr/bin/xcodebuild arg: DSTROOT=/Users/vso112885/vsts-agent/_work/1/s/ProjectApp/platforms/ios/output/iphoneos/Debug/build.dst
2016-11-25T22:52:48.5508320Z ##[debug]Absolute path for pathSegments: /Users/vso112885/vsts-agent/_work/1/s/ProjectApp/platforms/ios/output/iphoneos/Debug,build.obj = /Users/vso112885/vsts-agent/_work/1/s/ProjectApp/platforms/ios/output/iphoneos/Debug/build.obj
2016-11-25T22:52:48.5562050Z ##[debug]/usr/bin/xcodebuild arg: OBJROOT=/Users/vso112885/vsts-agent/_work/1/s/ProjectApp/platforms/ios/output/iphoneos/Debug/build.obj
2016-11-25T22:52:48.5620720Z ##[debug]Absolute path for pathSegments: /Users/vso112885/vsts-agent/_work/1/s/ProjectApp/platforms/ios/output/iphoneos/Debug,build.sym = /Users/vso112885/vsts-agent/_work/1/s/ProjectApp/platforms/ios/output/iphoneos/Debug/build.sym
2016-11-25T22:52:48.5655690Z ##[debug]/usr/bin/xcodebuild arg: SYMROOT=/Users/vso112885/vsts-agent/_work/1/s/ProjectApp/platforms/ios/output/iphoneos/Debug/build.sym
2016-11-25T22:52:48.5687910Z ##[debug]Absolute path for pathSegments: /Users/vso112885/vsts-agent/_work/1/s/ProjectApp/platforms/ios/output/iphoneos/Debug,build.pch = /Users/vso112885/vsts-agent/_work/1/s/ProjectApp/platforms/ios/output/iphoneos/Debug/build.pch
2016-11-25T22:52:48.5721010Z ##[debug]/usr/bin/xcodebuild arg: SHARED_PRECOMPS_DIR=/Users/vso112885/vsts-agent/_work/1/s/ProjectApp/platforms/ios/output/iphoneos/Debug/build.pch
2016-11-25T22:52:48.5756780Z ##[debug]/usr/bin/xcodebuild arg: -project /Users/vso112885/vsts-agent/_work/1/s/ProjectApp/platforms/ios/Project.xcodeproj
2016-11-25T22:52:48.5783570Z ##[debug]signMethod=file
2016-11-25T22:52:48.5808410Z ##[debug]xcode8AutomaticSigning=false
2016-11-25T22:52:48.5839610Z ##[debug]p12=/Users/vso112885/vsts-agent/_work/1/s
2016-11-25T22:52:48.5871620Z ##[debug]p12pwd=null
2016-11-25T22:52:48.5897860Z ##[debug]provProfile=/Users/vso112885/vsts-agent/_work/1/s
2016-11-25T22:52:48.5931860Z ##[debug]removeProfile=false
2016-11-25T22:52:48.5948130Z ##[debug]p12=/Users/vso112885/vsts-agent/_work/1/s
2016-11-25T22:52:48.5965980Z ##[debug]Absolute path for pathSegments: /Users/vso112885/vsts-agent/_work/1/s = /Users/vso112885/vsts-agent/_work/1/s
2016-11-25T22:52:48.5995350Z ##[debug]build.sourcesDirectory=/Users/vso112885/vsts-agent/_work/1/s
2016-11-25T22:52:48.6028360Z ##[debug]Absolute path for pathSegments: /Users/vso112885/vsts-agent/_work/1/s = /Users/vso112885/vsts-agent/_work/1/s
2016-11-25T22:52:48.6064940Z ##[debug]p12path supplied :false
2016-11-25T22:52:48.6100600Z ##[debug]provProfile=/Users/vso112885/vsts-agent/_work/1/s
2016-11-25T22:52:48.6134190Z ##[debug]Absolute path for pathSegments: /Users/vso112885/vsts-agent/_work/1/s = /Users/vso112885/vsts-agent/_work/1/s
2016-11-25T22:52:48.6165370Z ##[debug]build.sourcesDirectory=/Users/vso112885/vsts-agent/_work/1/s
2016-11-25T22:52:48.6267500Z ##[debug]Absolute path for pathSegments: /Users/vso112885/vsts-agent/_work/1/s = /Users/vso112885/vsts-agent/_work/1/s
2016-11-25T22:52:48.6293900Z ##[debug]provProfilepath supplied :false
2016-11-25T22:52:48.6318320Z ##[debug]teamId=null
2016-11-25T22:52:48.6343390Z ##[debug]exec tool: /usr/bin/xcodebuild
2016-11-25T22:52:48.6378940Z ##[debug]Arguments:
2016-11-25T22:52:48.6413140Z ##[debug]   -sdk
2016-11-25T22:52:48.6441970Z ##[debug]   iphoneos
2016-11-25T22:52:48.6468330Z ##[debug]   -configuration
2016-11-25T22:52:48.6494220Z ##[debug]   Debug
2016-11-25T22:52:48.6519470Z ##[debug]   -scheme
2016-11-25T22:52:48.6546840Z ##[debug]   Project
2016-11-25T22:52:48.6572330Z ##[debug]   build
2016-11-25T22:52:48.6598130Z ##[debug]   clean
2016-11-25T22:52:48.6624990Z ##[debug]   DSTROOT=/Users/vso112885/vsts-agent/_work/1/s/ProjectApp/platforms/ios/output/iphoneos/Debug/build.dst
2016-11-25T22:52:48.6655930Z ##[debug]   OBJROOT=/Users/vso112885/vsts-agent/_work/1/s/ProjectApp/platforms/ios/output/iphoneos/Debug/build.obj
2016-11-25T22:52:48.6685300Z ##[debug]   SYMROOT=/Users/vso112885/vsts-agent/_work/1/s/ProjectApp/platforms/ios/output/iphoneos/Debug/build.sym
2016-11-25T22:52:48.6715060Z ##[debug]   SHARED_PRECOMPS_DIR=/Users/vso112885/vsts-agent/_work/1/s/ProjectApp/platforms/ios/output/iphoneos/Debug/build.pch
2016-11-25T22:52:48.6743250Z ##[debug]   -project
2016-11-25T22:52:48.6771040Z ##[debug]   /Users/vso112885/vsts-agent/_work/1/s/ProjectApp/platforms/ios/Project.xcodeproj
2016-11-25T22:52:48.6815890Z [command]/usr/bin/xcodebuild -sdk iphoneos -configuration Debug -scheme Project build clean DSTROOT=/Users/vso112885/vsts-agent/_work/1/s/ProjectApp/platforms/ios/output/iphoneos/Debug/build.dst OBJROOT=/Users/vso112885/vsts-agent/_work/1/s/ProjectApp/platforms/ios/output/iphoneos/Debug/build.obj SYMROOT=/Users/vso112885/vsts-agent/_work/1/s/ProjectApp/platforms/ios/output/iphoneos/Debug/build.sym SHARED_PRECOMPS_DIR=/Users/vso112885/vsts-agent/_work/1/s/ProjectApp/platforms/ios/output/iphoneos/Debug/build.pch -project /Users/vso112885/vsts-agent/_work/1/s/ProjectApp/platforms/ios/Project.xcodeproj
2016-11-25T22:52:49.0919290Z Build settings from command line:
2016-11-25T22:52:49.0976050Z     DSTROOT = /Users/vso112885/vsts-agent/_work/1/s/ProjectApp/platforms/ios/output/iphoneos/Debug/build.dst
2016-11-25T22:52:49.1034270Z     OBJROOT = /Users/vso112885/vsts-agent/_work/1/s/ProjectApp/platforms/ios/output/iphoneos/Debug/build.obj
2016-11-25T22:52:49.1069390Z     SDKROOT = iphoneos9.3
2016-11-25T22:52:49.1150150Z     SHARED_PRECOMPS_DIR = /Users/vso112885/vsts-agent/_work/1/s/ProjectApp/platforms/ios/output/iphoneos/Debug/build.pch
```
Here's the line where it gets stuck.
**`2016-11-25T22:52:49.1228780Z     SYMROOT = /Users/vso112885/vsts-agent/_work/1/s/ProjectApp/platforms/ios/output/iphoneos/Debug/build.sym
2016-11-25T22:52:49.1288550Z`** 
```diff
2016-11-25T22:56:25.9213590Z ##[error]The operation was canceled.
2016-11-25T22:56:25.9351490Z ##[debug]System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.VisualStudio.Services.Agent.ProcessInvoker.<ExecuteAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.NodeHandler.<RunAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.<RunAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.<RunAsync>d__0.MoveNext()
2016-11-25T22:56:25.9406960Z ##[section]Finishing: Xcode build clean
```

**Comment by madhurig** [comment]
@alexszilagyi: Can you verify if the scheme you are passing in is "shared" in your xcode project? Verify it is shared and committed to the repo.

**Comment by alexszilagyi** [comment]
@madhurig: How I'm able to check the scheme if the iOS project is generated runtime based on an ionic app? [or how I should generate the iOS project from the ionic one with shared enabled?](http://stackoverflow.com/q/40977851/850491)

Locally if I'm running the following command: `xcodebuild -list` then I get:

```
Information about project "PROJECT":
    Targets:
        PROJECT

    Build Configurations:
        Debug
        Release

    If no build configuration is specified and -scheme is not passed then "Release" is used.

    Schemes:
        PROJECT
        CordovaLib
```

**Comment by madhurig** [comment]
@alexszilagyi: That seems to be an issue with ionic not creating the projects to be compatible with CI systems. I found this article providing solutions for similar issue: http://moduscreate.com/cordova_xcodebuild_hangs_freezes_during_build/  

You could also trying using the Cordova task instead of Xcode task: https://www.visualstudio.com/en-us/docs/build/apps/mobile/cordova-build#osx

**Comment by alexszilagyi** [comment]
@madhurig : thanks for [pointing out](https://github.com/Microsoft/vsts-tasks/issues/3156#issuecomment-263617634), the issue was that the project was not shared. I had to use the shared_scheme (ruby script available for cordova).
