### ISSUE TITLE
FTP Upload randomly fails to Azure Web Site

### ISSUE THREAD

**Issue by sandersaares** [Microsoft/vsts-tasks#3160]
Sometimes the FTP Upload task fails with an "Access denied" error when uploading the contents of an Azure Web Site. This always happens after the "clean" step. Some conflict with the re-creation of wwwroot? Just guessing.

```
2016-11-28T10:05:14.7661916Z ##[section]Starting: FTP Upload: $(System.ArtifactsDirectory)/build/Site
 
2016-11-28T10:05:14.7991932Z ==============================================================================
 
2016-11-28T10:05:14.7991932Z Task         : FTP Upload
 
2016-11-28T10:05:14.7991932Z Description  : FTP Upload
 
2016-11-28T10:05:14.7991932Z Version      : 1.0.4
 
2016-11-28T10:05:14.7991932Z Author       : Microsoft Corporation
 
2016-11-28T10:05:14.7991932Z Help         : Upload files to a remote machine using the File Transfer Protocol (FTP), or securely with FTPS.  [More Information](http://go.microsoft.com/fwlink/?LinkId=809084).
 
2016-11-28T10:05:14.7991932Z ==============================================================================
 
2016-11-28T10:05:15.2182140Z 79eff99b-814c-4f67-a712-234f6985f84a exists true
 
2016-11-28T10:05:15.2182140Z connecting to: waws-prod-am2-053.ftp.azurewebsites.windows.net:21
 
2016-11-28T10:05:15.2372152Z connected: Microsoft FTP Service
 
2016-11-28T10:05:17.7140050Z cleaning remote directory: /site/wwwroot
 
2016-11-28T10:05:18.8319483Z uploading files to remote directory: /site/wwwroot
 
2016-11-28T10:05:18.8721919Z FTP upload failed: Unable to create remote directory: /site/wwwroot due to error: Error: Access is denied.
 
2016-11-28T10:05:18.8721919Z host: waws-prod-am2-053.ftp.azurewebsites.windows.net
 
2016-11-28T10:05:18.8721919Z path: /site/wwwroot
 
2016-11-28T10:05:18.8721919Z files uploaded: 0
 
2016-11-28T10:05:18.8721919Z files skipped: 0
 
2016-11-28T10:05:18.8721919Z directories processed: 0
 
2016-11-28T10:05:18.8761915Z unprocessed files & directories: 68
 
2016-11-28T10:05:18.8841903Z ##[error]Unable to create remote directory: /site/wwwroot due to error: Error: Access is denied.
 
2016-11-28T10:05:18.8921898Z disconnecting from:  waws-prod-am2-053.ftp.azurewebsites.windows.net
 
2016-11-28T10:05:18.8941890Z disconnected
 
2016-11-28T10:05:18.8971886Z ##[section]Finishing: FTP Upload: $(System.ArtifactsDirectory)/build/Site
```

**Comment by sandersaares** [comment]
The files I am uploading are a DocFX-generated documentation website consisting of purely static files. Task settings screenshot attached: 
![image](https://cloud.githubusercontent.com/assets/9914262/20823703/4893bae6-b85f-11e6-9c9a-718312e5906e.png)

**Comment by sandersaares** [comment]
I found these entries in the event log of the web site, corresponding to the timestamps of two of the failures.

```
<Event>
<System>
<Provider Name="ASP.NET 4.0.30319.0"/>
<EventID>1309</EventID>
<Level>2</Level>
<Task>0</Task>
<Keywords>Keywords</Keywords>
<TimeCreated SystemTime="2016-12-12T13:40:53Z"/>
<EventRecordID>2126110203</EventRecordID>
<Channel>Application</Channel>
<Computer>RD000D3A23090F</Computer>
<Security/>
</System>
<EventData>
<Data>3005</Data>
<Data>An unhandled exception has occurred.</Data>
<Data>12/12/2016 1:40:53 PM</Data>
<Data>12/12/2016 1:40:53 PM</Data>
<Data>bf1345d200884bb7b71cd2d8b4bec577</Data>
<Data>5</Data>
<Data>1</Data>
<Data>0</Data>
<Data>/LM/W3SVC/1351246350/ROOT-1-131260235388048128</Data>
<Data>Full</Data>
<Data>/</Data>
<Data>D:\home\site\wwwroot\</Data>
<Data>RD000D3A23090F</Data>
<Data/>
<Data>7240</Data>
<Data>w3wp.exe</Data>
<Data>IIS APPPOOL\xxxxxxxx</Data>
<Data>HttpException</Data>
<Data>
Failed to start monitoring changes to 'D:\home\site\wwwroot' because access is denied. at System.Web.DirMonCompletion..ctor(DirectoryMonitor dirMon, String dir, Boolean watchSubtree, UInt32 notifyFilter) at System.Web.DirectoryMonitor.StartMonitoring() at System.Web.DirectoryMonitor.StartMonitoringFileWithAssert(String file, FileChangeEventHandler callback, String alias) at System.Web.FileChangesMonitor.StartMonitoringPath(String alias, FileChangeEventHandler callback, FileAttributesData& fad) at System.Web.Caching.CacheDependency.Init(Boolean isPublic, String[] filenamesArg, String[] cachekeysArg, CacheDependency dependency, DateTime utcStart) at System.Web.Caching.CacheDependency..ctor(String filename, DateTime start) at System.Web.WebPages.Deployment.PreApplicationStartCode.RegisterForChangeNotifications() at System.Web.WebPages.Deployment.PreApplicationStartCode.OnChanged(String key, Object value, CacheItemRemovedReason reason) at System.Web.Caching.CacheEntry.CallCacheItemRemovedCallback(CacheItemRemovedCallback callback, CacheItemRemovedReason reason)
</Data>
<Data/>
<Data/>
<Data/>
<Data/>
<Data>False</Data>
<Data/>
<Data>IIS APPPOOL\xxxxxxxx</Data>
<Data>7</Data>
<Data>IIS APPPOOL\xxxxxxxx</Data>
<Data>False</Data>
<Data>
at System.Web.DirMonCompletion..ctor(DirectoryMonitor dirMon, String dir, Boolean watchSubtree, UInt32 notifyFilter) at System.Web.DirectoryMonitor.StartMonitoring() at System.Web.DirectoryMonitor.StartMonitoringFileWithAssert(String file, FileChangeEventHandler callback, String alias) at System.Web.FileChangesMonitor.StartMonitoringPath(String alias, FileChangeEventHandler callback, FileAttributesData& fad) at System.Web.Caching.CacheDependency.Init(Boolean isPublic, String[] filenamesArg, String[] cachekeysArg, CacheDependency dependency, DateTime utcStart) at System.Web.Caching.CacheDependency..ctor(String filename, DateTime start) at System.Web.WebPages.Deployment.PreApplicationStartCode.RegisterForChangeNotifications() at System.Web.WebPages.Deployment.PreApplicationStartCode.OnChanged(String key, Object value, CacheItemRemovedReason reason) at System.Web.Caching.CacheEntry.CallCacheItemRemovedCallback(CacheItemRemovedCallback callback, CacheItemRemovedReason reason)
</Data>
</EventData>
</Event>

<Event>
<System>
<Provider Name="ASP.NET 4.0.30319.0"/>
<EventID>1309</EventID>
<Level>2</Level>
<Task>0</Task>
<Keywords>Keywords</Keywords>
<TimeCreated SystemTime="2016-12-14T09:53:31Z"/>
<EventRecordID>-2009705031</EventRecordID>
<Channel>Application</Channel>
<Computer>RD000D3A23090F</Computer>
<Security/>
</System>
<EventData>
<Data>3005</Data>
<Data>An unhandled exception has occurred.</Data>
<Data>12/14/2016 9:53:30 AM</Data>
<Data>12/14/2016 9:53:30 AM</Data>
<Data>5fd0f8109d4f4affa2e0102308ca2086</Data>
<Data>5</Data>
<Data>1</Data>
<Data>0</Data>
<Data>/LM/W3SVC/1351246350/ROOT-2-131261001596485518</Data>
<Data>Full</Data>
<Data>/</Data>
<Data>D:\home\site\wwwroot\</Data>
<Data>RD000D3A23090F</Data>
<Data/>
<Data>7240</Data>
<Data>w3wp.exe</Data>
<Data>IIS APPPOOL\xxxxxxxx</Data>
<Data>DirectoryNotFoundException</Data>
<Data>
Could not find a part of the path 'D:\home\site\wwwroot'. at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) at System.IO.FileSystemEnumerableIterator`1.CommonInit() at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost) at System.IO.Directory.EnumerateFiles(String path) at System.Web.WebPages.Deployment.WebPagesDeployment.AppRootContainsWebPagesFile(String path) at System.Web.WebPages.Deployment.PreApplicationStartCode.OnChanged(String key, Object value, CacheItemRemovedReason reason) at System.Web.Caching.CacheEntry.CallCacheItemRemovedCallback(CacheItemRemovedCallback callback, CacheItemRemovedReason reason)
</Data>
<Data/>
<Data/>
<Data/>
<Data/>
<Data>False</Data>
<Data/>
<Data>IIS APPPOOL\xxxxxxxx</Data>
<Data>15</Data>
<Data>IIS APPPOOL\xxxxxxxx</Data>
<Data>False</Data>
<Data>
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) at System.IO.FileSystemEnumerableIterator`1.CommonInit() at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost) at System.IO.Directory.EnumerateFiles(String path) at System.Web.WebPages.Deployment.WebPagesDeployment.AppRootContainsWebPagesFile(String path) at System.Web.WebPages.Deployment.PreApplicationStartCode.OnChanged(String key, Object value, CacheItemRemovedReason reason) at System.Web.Caching.CacheEntry.CallCacheItemRemovedCallback(CacheItemRemovedCallback callback, CacheItemRemovedReason reason)
</Data>
</EventData>
</Event>
```

**Comment by DavidStaheli** [comment]
Update: we've reported this and related issues to the Azure Web App team to be fixed.  I'm closing this issue, but will update it with progress as received.

**Comment by DavidStaheli** [comment]
@sandersaares not that I'm aware of.  @bryanmacfarlane and @ericsciple, after our teams changed last year, I seem to remember your team investigating this further and perhaps finding a solution?  Not sure if you recall.
