### ISSUE TITLE
Azure Dacpac deployments failing often

### ISSUE THREAD

**Issue by janecos** [Microsoft/vsts-tasks#3165]
I am deploying into Azure using the hosted agent and deployments of dacpacs are often failing. Usually retrying works, sometimes I have to retry multiple times. The error seems to be when it is trying to add firewall rules, with the result being a 404 error. This is the same issue as in #3051, but that has been closed so opening a new issue.
The firewall code seems to be prone to issues. Issue #2116 was a previous issue I raised which retrying didn't fix.

My databases are open to Azure services to access, so I'm quite sure I don't need firewall rules to be added at all for the hosted agents to get to them. Please allow the firewall rule adding to be disabled. While these issues are happening I would be happier opening up my database manually to all IP addresses so at least the deployments would keep running.

Here is some detail from the log that shows the error:

2016-11-28T23:09:43.7935405Z ##[debug]Querying VSTS uri 'https://datacastle.vsdtl.visualstudio.com/' to get external ip address
2016-11-28T23:09:43.7965407Z ##[debug]Getting external ip address by making call to dtl service
2016-11-28T23:09:43.8255405Z ##[debug]GET https://datacastle.vsdtl.visualstudio.com//_apis/vslabs/ipaddress with 0-byte payload
2016-11-28T23:09:44.4783426Z ##[debug]No Firewall Rule was added
2016-11-28T23:09:44.4913441Z ##[debug]Caught exception from task script.
2016-11-28T23:09:44.4963417Z ##[debug]Error record:
2016-11-28T23:09:44.5823436Z ##[debug]C:\a\_tasks\SqlAzureDacpacDeployment_ce85a08b-a538-4d2b-8589-1d37a9ab970f\1.1.2\DeploySqlAzure.ps1 : 
2016-11-28T23:09:44.5838209Z ##[debug]
2016-11-28T23:09:44.5848305Z ##[debug]Status         : ProtocolError
2016-11-28T23:09:44.5868288Z ##[debug]Response       : System.Net.HttpWebResponse
2016-11-28T23:09:44.5888308Z ##[debug]Message        : The remote server returned an error: (404) Not Found.

**Comment by jpisano** [comment]
I was experiencing the same issue. IDK if your config is the same but I didn't have the port specified in the "Azure SQL Server Name" setting of the task. Once I added it, the 404's went away.

**Comment by nkpatterson** [comment]
Huh, I can confirm that appending the port number to the end of the "Azure SQL Server Name" field fixed the same problem for me. For example: myawesomedb.database.windows.net,1433. This was previously working without the port number and seems to have recently started failing. Not sure what changed...

**Comment by rajatagrawal-dev** [comment]
Hi @janecos 

Can you send the complete debug logs to RM_Customer_Queries at Microsoft dot com or post them here itself?

**Comment by janecos** [comment]
It worked today, so no error logs to show. I can get the logs from 2 weeks ago when I raised the issue if you still want to look at them.

**Comment by janecos** [comment]
This is now failing again, reliably this time, so I have emailed the full log from that task.

**Comment by vincentdass** [comment]
@kerslake, we are working on this issue.
Can you share your VSTS link ?

**Comment by kerslake** [comment]
Hi @vincentdass, can I share privately with you (e.g. email)? Thanks!

**Comment by vincentdass** [comment]
@kerslake, Please share the details with this github issue link to  **RM_Customer_Queries@microsoft.com**.

**Comment by vincentdass** [comment]
@kerslake  , Can u also share the screenshot  of `https://<vsaccount>.visualstudio.com/<project>/_machines` .
You can navigate to this URL by going to the `<project> -> Test -> Machines`.
![image](https://cloud.githubusercontent.com/assets/20121508/21764017/f43c557a-d686-11e6-8277-4628c6a50558.png)

**Comment by kerslake** [comment]
Hi @vincentdass, I've sent an email with the VSTS link failing with a 404, and the requested screenshot
Thanks!

**Comment by elferone** [comment]
We are getting the same problem as you guys. Tried to add the port number to the 
Azure SQL Server Name, but it did not work for me. Here is my log:

`2017-01-16T15:21:00.8163706Z ==============================================================================
 
2017-01-16T15:21:00.8163706Z Task         : Azure SQL Database Deployment
 
2017-01-16T15:21:00.8163706Z Description  : Deploy Azure SQL DB using DACPAC or run scripts using SQLCMD
 
2017-01-16T15:21:00.8163706Z Version      : 1.1.2
 
2017-01-16T15:21:00.8163706Z Author       : Microsoft Corporation
 
2017-01-16T15:21:00.8163706Z Help         : [More Information](https://aka.ms/sqlazuredeployreadme)
 
2017-01-16T15:21:00.8163706Z ==============================================================================
 
2017-01-16T15:21:02.9673685Z packageFile= C:\a\r1\a\eClient\DB\EClient.DB.dacpac
 
2017-01-16T15:21:03.5103936Z ##[error]
 
 
Status         : ProtocolError
 
Response       : System.Net.HttpWebResponse
 
Message        : The remote server returned an error: (404) Not Found.
 
Data           : {}
 
InnerException : 
 
TargetSite     : System.Net.WebResponse GetResponse(System.Net.WebRequest)
 
StackTrace     :    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
 
                    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
 
HelpLink       : 
 
Source         : Microsoft.PowerShell.Commands.Utility
 
HResult        : -2146233079
 
 `

Does anyone have found a solution for this? Sometime we get the error, sometime it works..

**Comment by KrishnaAdityaB** [comment]
We observed that some accounts have been redirected to wrong application tier instances because of which they may get 404 error while hitting https://<accountname>.vsdtl.visualstudio.com/_apis/vslabs/ipaddress. 
We are working on figuring out the impacted customers and fixing the issue proactively. 
If you face this issue meanwhile, please mail the debug logs and visual studio account name to RM_Customer_Queries@microsoft.com.

**Comment by mvvsubbu** [comment]
Feel free to reopen if anyone facing this issue.

**Comment by alcoforado** [comment]
jpisano solution worked for me as well

**I was experiencing the same issue. IDK if your config is the same but I didn't have the port specified in the "Azure SQL Server Name" setting of the task. Once I added it, the 404's went away.**

**Comment by Jsmiiii** [comment]
Adding the port number of Azure SQL DB to the end of the server name (,1433) within the VSTS build definition also worked for us. This was based on deployment of a DACPAC into Azure SQL DB, using a hosted build agent. Also ensure that your Azure SQL DB firewall rules allow traffic from the VSTS build agent.
