### ISSUE TITLE
Azure AppServices / WebApp Stop doesn't work with RM connection

### ISSUE THREAD

**Issue by phatcher** [Microsoft/vsts-tasks#3229]
Works fine with a classic connection but I get the following error if configured to use the Resource Manager

```
2016-12-10T13:46:39.2987139Z ##[section]Starting: Azure AppServices Stop
2016-12-10T13:46:39.3057142Z ==============================================================================
2016-12-10T13:46:39.3057142Z Task         : Azure AppServices / WebApp Stop
2016-12-10T13:46:39.3057142Z Description  : Task for stopping an Azure App Service as a part of a VSTS build
2016-12-10T13:46:39.3057142Z Version      : 0.3.0
2016-12-10T13:46:39.3057142Z Author       : rbengtsson
2016-12-10T13:46:39.3057142Z Help         : 
2016-12-10T13:46:39.3057142Z ==============================================================================
2016-12-10T13:46:39.3087147Z Preparing task execution handler.
2016-12-10T13:46:39.8267139Z Executing the powershell script: C:\a\_tasks\Stop_9a610776-bf44-420c-8c39-6c3eaa907b19\0.3.0\Stop.ps1
2016-12-10T13:46:40.2497143Z Looking for Azure PowerShell module at C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ServiceManagement\Azure\Azure.psd1
2016-12-10T13:46:40.2497143Z 
2016-12-10T13:46:40.2497143Z 
2016-12-10T13:46:44.2784381Z AzurePSCmdletsVersion= 2.0.1
2016-12-10T13:46:44.2794366Z 
2016-12-10T13:46:44.2794366Z 
2016-12-10T13:46:44.5234565Z 
2016-12-10T13:46:44.5234565Z 
2016-12-10T13:46:44.5294565Z Get-ServiceEndpoint -Name ******** -Context Microsoft.TeamFoundation.DistributedTask.Handlers.LegacyVSTSPowerShellHost.PSHostTaskContext
2016-12-10T13:46:44.5294565Z 
2016-12-10T13:46:44.5294565Z 
2016-12-10T13:46:44.5774633Z tenantId= ********
2016-12-10T13:46:44.5774633Z 
2016-12-10T13:46:44.5774633Z 
2016-12-10T13:46:44.5774633Z azureSubscriptionId= ********
2016-12-10T13:46:44.5774633Z 
2016-12-10T13:46:44.5774633Z 
2016-12-10T13:46:44.5784567Z azureSubscriptionName= FOO-TEST
2016-12-10T13:46:44.5784567Z 
2016-12-10T13:46:44.5784567Z 
2016-12-10T13:46:45.3364630Z Add-AzureRMAccount -ServicePrincipal -Tenant ******** -Credential System.Management.Automation.PSCredential
2016-12-10T13:46:45.3364630Z 
2016-12-10T13:46:45.3364630Z 
2016-12-10T13:46:46.1575824Z Select-AzureRMSubscription -SubscriptionId ******** -tenantId ********
2016-12-10T13:46:46.1575824Z 
2016-12-10T13:46:46.1575824Z 
2016-12-10T13:46:46.2622340Z Init Stop task
2016-12-10T13:46:46.2632331Z 
2016-12-10T13:46:46.2632331Z 
2016-12-10T13:46:46.2632331Z ConnectedServiceNameSelector = ConnectedServiceNameARM
2016-12-10T13:46:46.2632331Z 
2016-12-10T13:46:46.2632331Z 
2016-12-10T13:46:46.2632331Z ConnectedServiceName = 
2016-12-10T13:46:46.2632331Z 
2016-12-10T13:46:46.2632331Z 
2016-12-10T13:46:46.2632331Z ConnectedServiceNameARM = ********
2016-12-10T13:46:46.2632331Z 
2016-12-10T13:46:46.2632331Z 
2016-12-10T13:46:46.2642342Z WebAppName = foo-test
2016-12-10T13:46:46.2642342Z 
2016-12-10T13:46:46.2642342Z 
2016-12-10T13:46:46.2682340Z Slot = Production
2016-12-10T13:46:46.2682340Z 
2016-12-10T13:46:46.2682340Z 
2016-12-10T13:46:46.2712341Z ##[command]Get-AzureWebsite -Name foo-test -Slot Production
2016-12-10T13:46:46.2712341Z 
2016-12-10T13:46:46.2712341Z 
2016-12-10T13:46:46.4641991Z ##[error]System.ApplicationException: No default subscription has been designated. Use Select-AzureSubscription -Default <subscriptionName> to set the default subscription.
2016-12-10T13:46:46.4641991Z    at Microsoft.Azure.Commands.Common.Authentication.Factories.ClientFactory.CreateClient[TClient](AzureSMProfile profile, AzureSubscription subscription, Endpoint endpoint)
2016-12-10T13:46:46.4641991Z    at Microsoft.WindowsAzure.Commands.Utilities.CloudService.CloudServiceClient..ctor(AzureSMProfile profile, AzureSubscription subscription, String currentLocation, Action`1 debugStream, Action`1 verboseStream, Action`1 warningStream)
2016-12-10T13:46:46.4641991Z    at Microsoft.WindowsAzure.Commands.Utilities.Websites.WebsitesClient..ctor(AzureSMProfile profile, AzureSubscription subscription, Action`1 logger)
2016-12-10T13:46:46.4641991Z    at Microsoft.WindowsAzure.Commands.Utilities.Websites.Common.WebsiteBaseCmdlet.get_WebsitesClient()
2016-12-10T13:46:46.4641991Z    at Microsoft.WindowsAzure.Commands.Websites.GetAzureWebsiteCommand.<GetByName>b__0()
2016-12-10T13:46:46.4641991Z    at Microsoft.WindowsAzure.Commands.Websites.GetAzureWebsiteCommand.Do(Action call)
2016-12-10T13:46:46.4641991Z    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
2016-12-10T13:46:46.4641991Z ##[command]Stop-AzureWebsite -Name gul-test -Slot Production
2016-12-10T13:46:46.4641991Z 
2016-12-10T13:46:46.4641991Z 
2016-12-10T13:46:46.4641991Z ##[error]System.ApplicationException: No default subscription has been designated. Use Select-AzureSubscription -Default <subscriptionName> to set the default subscription.
2016-12-10T13:46:46.4651990Z    at Microsoft.Azure.Commands.Common.Authentication.Factories.ClientFactory.CreateClient[TClient](AzureSMProfile profile, AzureSubscription subscription, Endpoint endpoint)
2016-12-10T13:46:46.4651990Z    at Microsoft.WindowsAzure.Commands.Utilities.CloudService.CloudServiceClient..ctor(AzureSMProfile profile, AzureSubscription subscription, String currentLocation, Action`1 debugStream, Action`1 verboseStream, Action`1 warningStream)
2016-12-10T13:46:46.4651990Z    at Microsoft.WindowsAzure.Commands.Utilities.Websites.WebsitesClient..ctor(AzureSMProfile profile, AzureSubscription subscription, Action`1 logger)
2016-12-10T13:46:46.4651990Z    at Microsoft.WindowsAzure.Commands.Utilities.Websites.Common.WebsiteBaseCmdlet.get_WebsitesClient()
2016-12-10T13:46:46.4651990Z    at Microsoft.WindowsAzure.Commands.Websites.StopAzureWebsiteCommand.ExecuteCmdlet()
2016-12-10T13:46:46.4651990Z    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
2016-12-10T13:46:46.4651990Z Ending Stop task
2016-12-10T13:46:46.4651990Z 
2016-12-10T13:46:46.4651990Z 
2016-12-10T13:46:46.4821967Z ##[error]PowerShell script completed with 2 errors.
2016-12-10T13:46:46.4831972Z ##[section]Finishing: Azure AppServices Stop
```

**Comment by kmkumaran** [comment]
The command that is failing is Azure Service management command and not Azure Resource manager command. I believe you are using the task published by an extension which is not owned by Microsoft. Can you report your issue in https://marketplace.visualstudio.com/items?itemName=rbengtsson.appservices-start-stop or reachout to its publisher to follow-up.

**Comment by chshrikh** [comment]
closing the issue as task is not own by Microsoft
