### ISSUE TITLE
Cannot publishing a NuGet to TFS 2017

### ISSUE THREAD

**Issue by magol** [Microsoft/vsts-tasks#3287]
When I try to publish a NuGet to my TFS 2017 on-premises using a build step, I get following error messages:

```
2016-12-21T09:33:58.3510841Z [command]C:\Windows\system32\chcp.com 65001
2016-12-21T09:33:58.3667084Z Active code page: 65001
2016-12-21T09:34:00.7730379Z Detected NuGet version 3.3.0.212 / 3.3.0
2016-12-21T09:34:00.7730379Z SYSTEMVSSCONNECTION exists true
2016-12-21T09:34:00.7886681Z [command]C:\Agent\_work\_tasks\NuGetPublisher_333b11bd-d341-40d9-afcf-b32d5ce6f25b\0.2.21\node_modules\nuget-task-common\NuGet\3.3.0\NuGet.exe push -NonInteractive C:\Agent\_work\1\s\Foo.1.4.3-build-20161221-1.nupkg -Source http://myServer:8080/tfs/My%20Team%20Projects/_packaging/our-nuget/nuget/v3/index.json -ApiKey VSTS -Verbosity Detailed
2016-12-21T09:34:01.4761938Z Please provide credentials for: http://myserver:8080/tfs/My%20Team%20Projects/_packaging/our-nuget/nuget/v3/index.json
2016-12-21T09:34:01.4761938Z UserName: System.InvalidOperationException: Cannot prompt for input in non-interactive mode.
2016-12-21T09:34:01.5074440Z ##[error]Error: C:\Agent\_work\_tasks\NuGetPublisher_333b11bd-d341-40d9-afcf-b32d5ce6f25b\0.2.21\node_modules\nuget-task-common\NuGet\3.3.0\NuGet.exe failed with return code: 1
2016-12-21T09:34:01.5074440Z ##[error]Packages failed to publish
I have also try to run the NuGet.exe push ... command from a PowerShell script as a build step, and that also failed.
```

When I run it manually in a ordinary PowerShell console, it works without problems.

What is the runtime difference between running it from console compared to running it in a build step? How do I make it works?

**Comment by zjrunner** [comment]
Looks like you are using nuget 3.3 from those logs.  You need to use nuget 3.5 or higher to use the TFS Packaging feature due to some auth fixes that went into 3.5.  You'll find the version toggle inside the Nuget task options in your build definition.  We weren't able to just make it the default for everyone because of some breaking changes between 3.3 and 3.5 that would have impacted everyone using nuget tasks but not yet using TFS packaging (and no ability to set a good default only for new build definitions).  Please verify.

**Comment by magol** [comment]
But i have try to change to 3.5, and I still have problems 😯
Way can i do the published manual from a powershell console,  but not from a build steg?

**Comment by magol** [comment]
@zjrunner I have changed to 3.5, and got following error output:

```
##[section]Starting: NuGet Publisher 
##[debug]agent.workFolder=C:\Agent\_work
##[debug]loading inputs and endpoints
##[debug]loading ENDPOINT_AUTH_$/
##[debug]loading ENDPOINT_AUTH_PARAMETER_$/_ACCESSTOKEN
##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
##[debug]loading ENDPOINT_AUTH_SCHEME_$/
##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
##[debug]loading INPUT_FEEDNAME
##[debug]loading INPUT_NUGETFEEDTYPE
##[debug]loading INPUT_NUGETVERSION
##[debug]loading INPUT_SEARCHPATTERN
##[debug]loading INPUT_VERBOSITY
##[debug]loaded 11
##[debug]check path : C:\Agent\_work\_tasks\NuGetPublisher_333b11bd-d341-40d9-afcf-b32d5ce6f25b\0.2.21\task.json
##[debug]set resource file to: C:\Agent\_work\_tasks\NuGetPublisher_333b11bd-d341-40d9-afcf-b32d5ce6f25b\0.2.21\task.json
##[debug]system.culture=en-US
##[debug]check path : C:\Windows\system32\chcp.com
##[debug]C:\Windows\system32\chcp.com=C:\Windows\system32\chcp.com
##[debug]C:\Windows\system32\chcp.com arg: ["65001"]
##[debug]exec tool: C:\Windows\system32\chcp.com
##[debug]Arguments:
##[debug]   65001
[command]C:\Windows\system32\chcp.com 65001
Active code page: 65001
##[debug]searchPattern=C:\Agent\_work\1\s\**\*.nupkg;-:**\packages\**\*.nupkg;-:**\*.symbols.nupkg
##[debug]System.DefaultWorkingDirectory=C:\Agent\_work\1\s
##[debug]pattern: C:\Agent\_work\1\s\**\*.nupkg, isNegative: false
##[debug]Matching glob pattern: C:\Agent\_work\1\s\**\*.nupkg
##[debug]Index of first wildcard: 19
##[debug]find root dir: C:\Agent\_work\1
##[debug]find C:\Agent\_work\1
##[debug]4472 matches.
##[debug]pattern: C:\Agent\_work\1\s\**\packages\**\*.nupkg, isNegative: true
##[debug]Matching glob pattern: C:\Agent\_work\1\s\**\packages\**\*.nupkg
##[debug]Index of first wildcard: 19
##[debug]find root dir: C:\Agent\_work\1
##[debug]find C:\Agent\_work\1
##[debug]4472 matches.
##[debug]pattern: C:\Agent\_work\1\s\**\*.symbols.nupkg, isNegative: true
##[debug]Matching glob pattern: C:\Agent\_work\1\s\**\*.symbols.nupkg
##[debug]Index of first wildcard: 19
##[debug]find root dir: C:\Agent\_work\1
##[debug]find C:\Agent\_work\1
##[debug]4472 matches.
##[debug]connectedServiceName=null
##[debug]feedName=http://sag-s02:8080/tfs/SAG%20Team%20Projects/_packaging/sag-nuget/nuget/v3/index.json
##[debug]nuGetAdditionalArgs=null
##[debug]verbosity=Detailed
##[debug]nuGetFeedType=internal
##[debug]nuGetPath=null
##[debug]nuGetversion=3.5.0.1829
##[debug]Agent.HomeDirectory=C:\Agent
##[debug]looking for tool NuGet
##[debug]looking for tool variant NuGet.exe
##[debug]checking C:\Agent\_work\_tasks\NuGetPublisher_333b11bd-d341-40d9-afcf-b32d5ce6f25b\0.2.21\node_modules\nuget-task-common\NuGet\3.5.0\NuGet.exe
##[debug]SYSTEMVSSCONNECTION=http://sag-s02:8080/tfs/SAG Team Projects/
Detected NuGet version 3.5.0.1938 / 3.5.0
##[debug]Quirks for 3.5.0.1938:
##[debug]    NoTfsOnPremAuthConfig
##[debug]NuGet.ForceEnableCredentialProvider=undefined
##[debug]NuGetTasks.IsHostedTestEnvironment=undefined
##[debug]System.TeamFoundationCollectionUri=http://sag-s02:8080/tfs/SAG%20Team%20Projects/
##[debug]Credential provider is enabled.
##[debug]NuGet.ForceEnableCredentialConfig=undefined
##[debug]NuGetTasks.IsHostedTestEnvironment=undefined
##[debug]System.TeamFoundationCollectionUri=http://sag-s02:8080/tfs/SAG%20Team%20Projects/
##[debug]Credential config is disabled due to on-prem quirks.
##[debug]Getting credentials for local feeds
SYSTEMVSSCONNECTION exists true
##[debug]SYSTEMVSSCONNECTION exists true
##[debug]Got auth token
##[debug]discovered URL prefixes: http://sag-s02:8080/tfs/SAG Team Projects/
##[debug]NuGetTasks.ExtraUrlPrefixesForTesting=undefined
##[debug]C:\Agent\_work\_tasks\NuGetPublisher_333b11bd-d341-40d9-afcf-b32d5ce6f25b\0.2.21\node_modules\nuget-task-common\NuGet\3.5.0\NuGet.exe arg: push
##[debug]C:\Agent\_work\_tasks\NuGetPublisher_333b11bd-d341-40d9-afcf-b32d5ce6f25b\0.2.21\node_modules\nuget-task-common\NuGet\3.5.0\NuGet.exe arg: -NonInteractive
##[debug]C:\Agent\_work\_tasks\NuGetPublisher_333b11bd-d341-40d9-afcf-b32d5ce6f25b\0.2.21\node_modules\nuget-task-common\NuGet\3.5.0\NuGet.exe pathArg: C:\Agent\_work\1\s\Foo.1.4.3-build-20161221-3.nupkg
##[debug]C:\Agent\_work\_tasks\NuGetPublisher_333b11bd-d341-40d9-afcf-b32d5ce6f25b\0.2.21\node_modules\nuget-task-common\NuGet\3.5.0\NuGet.exe arg: C:\Agent\_work\1\s\Foo.1.4.3-build-20161221-3.nupkg
##[debug]C:\Agent\_work\_tasks\NuGetPublisher_333b11bd-d341-40d9-afcf-b32d5ce6f25b\0.2.21\node_modules\nuget-task-common\NuGet\3.5.0\NuGet.exe arg: ["-Source","http://sag-s02:8080/tfs/SAG%20Team%20Projects/_packaging/sag-nuget/nuget/v3/index.json"]
##[debug]C:\Agent\_work\_tasks\NuGetPublisher_333b11bd-d341-40d9-afcf-b32d5ce6f25b\0.2.21\node_modules\nuget-task-common\NuGet\3.5.0\NuGet.exe arg: ["-ApiKey","VSTS"]
##[debug]C:\Agent\_work\_tasks\NuGetPublisher_333b11bd-d341-40d9-afcf-b32d5ce6f25b\0.2.21\node_modules\nuget-task-common\NuGet\3.5.0\NuGet.exe arg: -Verbosity
##[debug]C:\Agent\_work\_tasks\NuGetPublisher_333b11bd-d341-40d9-afcf-b32d5ce6f25b\0.2.21\node_modules\nuget-task-common\NuGet\3.5.0\NuGet.exe arg: Detailed
##[debug]credProviderPath = C:\Agent\_work\_tasks\NuGetPublisher_333b11bd-d341-40d9-afcf-b32d5ce6f25b\0.2.21\node_modules\nuget-task-common\NuGet
##[debug]exec tool: C:\Agent\_work\_tasks\NuGetPublisher_333b11bd-d341-40d9-afcf-b32d5ce6f25b\0.2.21\node_modules\nuget-task-common\NuGet\3.5.0\NuGet.exe
##[debug]Arguments:
##[debug]   push
##[debug]   -NonInteractive
##[debug]   C:\Agent\_work\1\s\Foo.1.4.3-build-20161221-3.nupkg
##[debug]   -Source
##[debug]   http://sag-s02:8080/tfs/SAG%20Team%20Projects/_packaging/sag-nuget/nuget/v3/index.json
##[debug]   -ApiKey
##[debug]   VSTS
##[debug]   -Verbosity
##[debug]   Detailed
[command]C:\Agent\_work\_tasks\NuGetPublisher_333b11bd-d341-40d9-afcf-b32d5ce6f25b\0.2.21\node_modules\nuget-task-common\NuGet\3.5.0\NuGet.exe push -NonInteractive C:\Agent\_work\1\s\Foo.1.4.3-build-20161221-3.nupkg -Source http://sag-s02:8080/tfs/SAG%20Team%20Projects/_packaging/sag-nuget/nuget/v3/index.json -ApiKey VSTS -Verbosity Detailed
NuGet Version: 3.5.0.1938
System.AggregateException: One or more errors occurred. ---> NuGet.Protocol.Core.Types.FatalProtocolException: Unable to load the service index for source http://sag-s02:8080/tfs/SAG%20Team%20Projects/_packaging/sag-nuget/nuget/v3/index.json. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at NuGet.Protocol.HttpSource.<>c__DisplayClass12_0.<<GetAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Common.ConcurrencyUtilities.<ExecuteWithFileLockedAsync>d__2`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.HttpSource.<GetAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.Protocol.ServiceIndexResourceV3Provider.<GetServiceIndexResourceV3>d__9.MoveNext()
   --- End of inner exception stack trace ---
   at NuGet.Protocol.ServiceIndexResourceV3Provider.<GetServiceIndexResourceV3>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.ServiceIndexResourceV3Provider.<TryCreate>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.SourceRepository.<GetResourceAsync>d__16`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.PackageUpdateResourceV3Provider.<TryCreate>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.SourceRepository.<GetResourceAsync>d__16`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.SourceRepository.<GetResourceAsync>d__15`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.CommandRunnerUtility.<GetPackageUpdateResource>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.PushRunner.<Run>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.PushCommand.<ExecuteCommandAsync>d__28.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
---> (Inner Exception #0) NuGet.Protocol.Core.Types.FatalProtocolException: Unable to load the service index for source http://sag-s02:8080/tfs/SAG%20Team%20Projects/_packaging/sag-nuget/nuget/v3/index.json. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at NuGet.Protocol.HttpSource.<>c__DisplayClass12_0.<<GetAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Common.ConcurrencyUtilities.<ExecuteWithFileLockedAsync>d__2`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.HttpSource.<GetAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.Protocol.ServiceIndexResourceV3Provider.<GetServiceIndexResourceV3>d__9.MoveNext()
   --- End of inner exception stack trace ---
   at NuGet.Protocol.ServiceIndexResourceV3Provider.<GetServiceIndexResourceV3>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.ServiceIndexResourceV3Provider.<TryCreate>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.SourceRepository.<GetResourceAsync>d__16`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.PackageUpdateResourceV3Provider.<TryCreate>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.SourceRepository.<GetResourceAsync>d__16`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.SourceRepository.<GetResourceAsync>d__15`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.CommandRunnerUtility.<GetPackageUpdateResource>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.PushRunner.<Run>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.PushCommand.<ExecuteCommandAsync>d__28.MoveNext()<---

##[debug]rc:1
##[debug]success:false
##[error]Error: C:\Agent\_work\_tasks\NuGetPublisher_333b11bd-d341-40d9-afcf-b32d5ce6f25b\0.2.21\node_modules\nuget-task-common\NuGet\3.5.0\NuGet.exe failed with return code: 1
##[debug]Processed: ##vso[task.issue type=error;]Error: C:\Agent\_work\_tasks\NuGetPublisher_333b11bd-d341-40d9-afcf-b32d5ce6f25b\0.2.21\node_modules\nuget-task-common\NuGet\3.5.0\NuGet.exe failed with return code: 1
##[debug]task result: Failed
##[error]Packages failed to publish
##[debug]Processed: ##vso[task.issue type=error;]Packages failed to publish
##[debug]Processed: ##vso[task.complete result=Failed;]Packages failed to publish
##[section]Finishing: NuGet Publisher 

```

**Comment by zjrunner** [comment]
holiday delays, sorry -- You are past the auth issues on the client now, where nuget couldn't even find the creds to send to the server.  Now you are sending them to the server properly but it looks like an authn/authz issue since you're getting a 401.

Head to one of your projects and click the 'Packaging' link in the Build & Release header item to get over to your feeds.  Right click & Edit (or use the pencil icon) for your feed and go to the permissions.  Ensure you have at least read permissions (you'll need Contribute if you're doing a push here) for "Project Collection Build Service (YourProject)".  This is generally the issue -- setting it up from another project or removing permissions when narrowing down contributors.

**Comment by magol** [comment]
I have contribution rights for "Project Collection Build Service (TEAM FOUNDATION)". I cannot found any "Project Collection Build Service (YourProject)".

See image how the permissions look like: ![permissions](https://cloud.githubusercontent.com/assets/493140/21448176/dc3dfbb8-c8df-11e6-9a21-e1474922fb74.png)

**Comment by jmyersmsft** [comment]
Let's double-check you have the right Project Collection Build Service identity: 

1. Open the build definition
2. Go to the Options page and make sure "Allow Scripts to Access OAuth Token" is checked.
3. Go back to the Build page and add a new PowerShell Script task and move it to the top of the list.
4. Change the Type field in the script task to "Inline Script"
5. Paste the following code into the "Inline Script" field:
```
$headers = @{Authorization="Bearer ${env:SYSTEM_ACCESSTOKEN}"}
$response = Invoke-RestMethod "${env:SYSTEM_TEAMFOUNDATIONCOLLECTIONURI}/_apis/connectionData" -Headers $headers 
$response.authenticatedUser | Format-List id, customDisplayName | Out-Host
```
6. Save the build definition and run a build.
7. The output of the script task will show the actual identity that the build is running as. Copy the GUID listed as "id"
8. Open the permissions for the feed
9. Delete Project Collection Build Service (TEAM FOUNDATION)
10. Paste the "id" GUID from step 7.
11. Click "Search", then click on the single result
12. Click Save
13. Run another build to see if it works.
14. When done, delete the PowerShell Script task from step 3 and uncheck the checkbox from step 2 if it wasn't checked to start with.

**Comment by zjrunner** [comment]
@magol -- any luck with these steps and your auth issues?

**Comment by Lyra1337** [comment]
Hey, i'm running into a similar problem. I tried your steps, but can't find any account by pasting the Guid. I added then the "Project Collection Build Service"-Account by the name - but the problem is still here. 

Any help is appreciated!

**Comment by Lyra1337** [comment]
I'm able to run this powershell script:
`C:\BuildAgent2017.1\_work\_tasks\NuGetPublisher_333b11bd-d341-40d9-afcf-b32d5ce6f25b\0.2.30\node_modules\nuget-task-common\NuGet\3.5.0\NuGet.exe push C:\BuildAgent2017.1\_work\1\s\MyPackage.2.0.0.0.nupkg -Source <feed-url> -ApiKey VSTS -Verbosity Detailed`
and that works...

**Comment by bbraun-edf** [comment]
We just upgraded from TFS 2015 Up2 to TFS 2017 Up1 and we are having a similar issue on our build server.  The path to our local nuget server seems to be losing a slash.  Ctrl-F on \\nuget and you'll see the original debug states two slashes, but the actual command and error only have one ???


2017-03-21T21:50:56.0222350Z ##[debug]C:\VSTS_Service_Agent\tasks\NuGetInstaller\0.2.29\node_modules\nuget-task-common\NuGet\3.5.0\NuGet.exe arg: restore
2017-03-21T21:50:56.0222350Z ##[debug]C:\VSTS_Service_Agent\tasks\NuGetInstaller\0.2.29\node_modules\nuget-task-common\NuGet\3.5.0\NuGet.exe arg: -NonInteractive
2017-03-21T21:50:56.0222350Z ##[debug]C:\VSTS_Service_Agent\tasks\NuGetInstaller\0.2.29\node_modules\nuget-task-common\NuGet\3.5.0\NuGet.exe arg: C:\VSTS_Service_Agent\_work\3\s\PowerOps.sln
2017-03-21T21:50:56.0222350Z ##[debug]C:\VSTS_Service_Agent\tasks\NuGetInstaller\0.2.29\node_modules\nuget-task-common\NuGet\3.5.0\NuGet.exe arg: -source "https://api.nuget.org/v3/index.json;**\\nuget.**myCompanyName.com\Packages"
2017-03-21T21:50:56.0222350Z ##[debug]credProviderPath = C:\VSTS_Service_Agent\tasks\NuGetInstaller\0.2.29\node_modules\nuget-task-common\NuGet
2017-03-21T21:50:56.0222350Z ##[debug]exec tool: C:\VSTS_Service_Agent\tasks\NuGetInstaller\0.2.29\node_modules\nuget-task-common\NuGet\3.5.0\NuGet.exe
2017-03-21T21:50:56.0222350Z ##[debug]Arguments:
2017-03-21T21:50:56.0222350Z ##[debug]   restore
2017-03-21T21:50:56.0378576Z ##[debug]   -NonInteractive
2017-03-21T21:50:56.0378576Z ##[debug]   C:\VSTS_Service_Agent\_work\3\s\PowerOps.sln
2017-03-21T21:50:56.0378576Z ##[debug]   -source
2017-03-21T21:50:56.0378576Z ##[debug]   https://api.nuget.org/v3/index.json;\nuget.myCompanyName.com\Packages
2017-03-21T21:50:56.0378576Z [command]C:\VSTS_Service_Agent\tasks\NuGetInstaller\0.2.29\node_modules\nuget-task-common\NuGet\3.5.0\NuGet.exe restore -NonInteractive C:\VSTS_Service_Agent\_work\3\s\PowerOps.sln -source https://api.nuget.org/v3/index.json;**\nuget.**myCompanyName.com\Packages
2017-03-21T21:50:56.0378576Z MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'.
2017-03-21T21:50:56.0378576Z The specified source '**\nuget.**myCompanyName.com\Packages' is invalid. Please provide a valid source.
2017-03-21T21:50:56.0378576Z ##[debug]rc:1
2017-03-21T21:50:56.0378576Z ##[debug]success:false
2017-03-21T21:50:56.0378576Z ##[error]Error: C:\VSTS_Service_Agent\tasks\NuGetInstaller\0.2.29\node_modules\nuget-task-common\NuGet\3.5.0\NuGet.exe failed with return code: 1
2017-03-21T21:50:56.0378576Z ##[debug]task result: Failed
2017-03-21T21:50:56.0378576Z ##[error]Packages failed to install

**Comment by bbraun-edf** [comment]
Just to follow up, our build definition was pointing to a network file path, not a URL.  We have a temporary fix to remove this location from the build and put the nupkg files on the build service accounts repository on the build server.  We are investigating alternatives, like getting our local Nuget server to properly publish our packages over http or to switch to the TFS Nuget server.

**Comment by SiCro** [comment]
So friggen frustrating, had this issue as well with on-prem TFS 2017, had to add the build service account to the VS Enterprise Access Levels to get past the 401 Unauthorised error
![image](https://cloud.githubusercontent.com/assets/16787178/25828448/50129550-34a4-11e7-840a-1da23664ecf1.png)

**Comment by alexmullans** [comment]
This is fixed - [see here for the resolution](https://developercommunity.visualstudio.com/content/problem/34317/nuget-restore-no-longer-works-for-file-paths-remov.html).
