### ISSUE TITLE
Publish Code Coverage Results not working on Linux with latest VSTS Agent

### ISSUE THREAD

**Issue by nbashkankov** [Microsoft/vsts-tasks#3307]
VSTS Agent version: 2.110.0
NodeJS: 6.9.1
OS: Linux 3.16.0-4-amd64 x86_64
Task version: 1.0.3

2016-12-26T10:42:23.9631610Z ##[section]Starting: Publish Code Coverage Results coverage/cobertura-coverage.xml
2016-12-26T10:42:23.9825870Z ==============================================================================
2016-12-26T10:42:23.9831940Z Task         : Publish Code Coverage Results
2016-12-26T10:42:23.9838210Z Description  : Publish code coverage results to VSO/TFS
2016-12-26T10:42:23.9850080Z Author       : Microsoft Corporation
2016-12-26T10:42:23.9856070Z Help         : [More Information](http://go.microsoft.com/fwlink/?LinkID=626485)
2016-12-26T10:42:23.9862210Z ==============================================================================
2016-12-26T10:42:24.0450120Z ##[error]Supported task execution handler not found. Supported handlers: Node
2016-12-26T10:42:24.0498680Z ##[debug]**System.Exception: Supported task execution handler not found. Supported handlers: Node**
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.<RunAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.<RunAsync>d__0.MoveNext()
2016-12-26T10:42:24.0514460Z ##[section]Finishing: Publish Code Coverage Results coverage/cobertura-coverage.xml

**Comment by ericsciple** [comment]
it sounds like you are on an TFS 2015. which update?

**Comment by nbashkankov** [comment]
Microsoft Visual Studio Team Foundation Server
Version 14.102.25423.0

**Comment by ericsciple** [comment]
it looks like the version of the task that shipped with TFS 2015 U3 only contained an implementation for Windows.

looking at the most recent stable version, the agent version demand is showing as 1.90 - which is a milestone that predates 2015 U3. so it would probably ok to build the latest stable version and upload it to your collection. i.e.:
1. clone the repo
2. checkout releases/m109
3. `npm install`
4. `node make.js build --task PublishCodeCoverageResults`
5. use the [build tasks upload](https://github.com/Microsoft/tfs-cli/blob/master/docs/buildtasks.md#upload) command from the [tfx cli](https://github.com/Microsoft/tfs-cli/blob/master/README.md) to upload the _build/PublishCodeCoverageResults folder to your collection. make sure you upload to the collection - e.g. http\://myserver:8080/tfs/***DefaultCollection***

**Comment by ericsciple** [comment]
@nigurr any known issues with recent PublishCodeCoverageResults against a TFS 2015 U3 server?

**Comment by nigurr** [comment]
There's not any change from U3 to current master. it should be fine.

**Comment by nbashkankov** [comment]
Hello, @ericsciple 
Thank you, problem solved.
