### ISSUE TITLE
Remove Resource Group fails if deletion takes more than 5 minutes

### ISSUE THREAD

**Issue by ericmaino** [Microsoft/vsts-tasks#3543]
It appears that if a resource group remove takes more than 5 minutes the task will fail with a task cancellation exception:

This reproduces 100% of the time.

2017-02-06T20:11:48.7048933Z [Azure Resource Manager]Deleting resource group 'ericmai-EthereumEx-ci-2017-0206-1'
2017-02-06T20:11:49.0338123Z ##[debug]Performing the operation "Removing resource group ..." on target "ericmai-EthereumEx-ci-2017-0206-1".
2017-02-06T20:16:54.7377103Z ##[error]The operation was canceled.
2017-02-06T20:16:54.7377103Z ##[debug]System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.VisualStudio.Services.Agent.ProcessInvoker.<ExecuteAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.PowerShell3Handler.<RunAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.<RunAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.<RunAsync>d__0.MoveNext()
2017-02-06T20:16:54.7377103Z ##[section]Finishing: Delete ericmai-EthereumEx-ci-$(Build.BuildNumber)

**Comment by desattir** [comment]
@ericmaino Is this happening when you're using 1.* version of the task or 2.*?

**Comment by desattir** [comment]
@ericmaino Will look into that failure and fix it ASAP. Thank you for reporting :)

**Comment by desattir** [comment]
@ericmaino also can you verify, that you haven't set the task time out to be 5 min. You can find this in the Control Options of a task.

**Comment by ericmaino** [comment]
It appears the task timeout is not honored by the task. It was set to 0. I also set a big number 45 minutes and it still timed out in 5 minutes. The overall build timeout was set to 90 minutes.

**Comment by ds-249** [comment]
@ericmaino try updating to the 2.x version of the task, and let me know if you're still facing this issue. I apologize for the delay in response.

**Comment by ericmaino** [comment]
Thanks I'll give that a try and provide feedback if I see issues.

**Comment by ds-ms** [comment]
I'm closing this issue, assuming it didn't recur
