### ISSUE TITLE
Azure File Copy - Index operation failed; the array index evaluated to null.

### ISSUE THREAD

**Issue by jaquelinecramos** [Microsoft/vsts-tasks#3554]
2017-02-06T19:30:44.0777609Z ##[debug]Trying to get FQDN for the azureRM VM resources from resource Group RESOURCEGROUP
 
2017-02-06T19:30:44.1558736Z ##[debug]System.Management.Automation.RuntimeException: Index operation failed; the array index evaluated to null.
 
2017-02-06T19:30:44.1558736Z    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
 
2017-02-06T19:30:44.1558736Z    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
 
2017-02-06T19:30:44.1558736Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
 
2017-02-06T19:30:44.1558736Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
 
2017-02-06T19:30:44.2027576Z ##[debug][Azure Call]Deleting container: fd4b892e-3b92-4a3d-a0ee-272a23fc35eb in storage account: devopsdefaultstorageacc
 
2017-02-06T19:30:44.6393736Z ##[debug][Azure Call]Deleted container: fd4b892e-3b92-4a3d-a0ee-272a23fc35eb in storage account: devopsdefaultstorageacc
 
2017-02-06T19:30:44.6553342Z ##[debug]Completed Azure File Copy Task for Azure VMs Destination
 
2017-02-06T19:30:44.6553342Z ##[error]Index operation failed; the array index evaluated to null.

**This virtual machine has ip public, correctly**

**Comment by jaquelinecramos** [comment]
We use TFS2015 Update 2.1 on-premiss.

Is there a need to update the Task?

**Comment by arjgupta** [comment]
Hi @jaquelinecramos , Thanks for reporting this issue. Can you tell whether you are facing this issue intermittently or continuously. Also, Can you please send the full debug logs at RM_Customer_Queries@microsoft.com

**Comment by jaquelinecramos** [comment]
Hi, Arjun!


Yes, this issue is continuously.


Follows log files.


Thanks!


Jaqueline Ramos

+55 11 94139-5980

Skype: jaqueline.cramos1

Blog: jaquelinecramos.com


________________________________
De: Arjun Gupta <notifications@github.com>
Enviado: sexta-feira, 17 de fevereiro de 2017 08:38
Para: Microsoft/vsts-tasks
Cc: jaquelinecramos; Mention
Assunto: Re: [Microsoft/vsts-tasks] Azure File Copy - Index operation failed; the array index evaluated to null. (#3554)


Hi @jaquelinecramos<https://github.com/jaquelinecramos> , Thanks for reporting this issue. Can you tell whether you are facing this issue intermittently or continuously. Also, Can you please send the full debug logs at RM_Customer_Queries@microsoft.com<mailto:RM_Customer_Queries@microsoft.com>

**Comment by jaquelinecramos** [comment]
Updates?

**Comment by arjgupta** [comment]
Hi @jaquelinecramos , We are closing this issue as it is resolved. Feel free to open it up again, if this problem still happens for you
