### ISSUE TITLE
SonarQube task (new one)

### ISSUE THREAD

**Issue by vferras** [Microsoft/vsts-tasks#3571]
Hello,

I updated the task of Sonar analysis to the new version (2), and using the "native" connector instead of the generic one using tokens. But I'm not able to make it work, I'm always facing an 401 error:

2017-02-09T08:55:09.6988691Z 08:55:09.194  Fetching analysis configuration settings...
2017-02-09T08:55:10.1017876Z ##[error]
2017-02-09T08:55:10.3023047Z ##[error]Unhandled Exception: System.Net.WebException: The remote server returned an error: (401) Unauthorized.
2017-02-09T08:55:10.3023047Z ##[error]at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
2017-02-09T08:55:10.3023047Z ##[error]at System.Net.WebClient.DownloadString(Uri address)
2017-02-09T08:55:10.3023047Z ##[error]at System.Net.WebClient.DownloadString(String address)
2017-02-09T08:55:10.3023047Z ##[error]at SonarQube.TeamBuild.PreProcessor.WebClientDownloader.Download(String url)
2017-02-09T08:55:10.3023047Z ##[error]at SonarQube.TeamBuild.PreProcessor.SonarWebService.GetProperties(String projectKey, String projectBranch)...

I've installed Fiddler in the VM where I have installed Sonar, and I've seen the incoming request, and the Authorization header contains the token base 64 encoded, and I decoded id and I saw that is ending with a ":" (e.g. 3f19275b4d790b03d62d611cd4288baac7092ebe:). And I guess this is the reason why I receive the 401.
Maybe it's an issue linked to the basic authentication?

Thanks in advance!

Víctor

**Comment by ericsciple** [comment]
That task does not live in this repo anymore. See this issue for where to get help for that task: https://github.com/Microsoft/vsts-tasks/issues/3517
