### ISSUE TITLE
NPM authentication with On-Premise TFS2017Update1 Pakage feed

### ISSUE THREAD

**Issue by henning-krause** [Microsoft/vsts-tasks#3805]
We created an NPM feed on our on-premise TFS 2017 Update 1 server. 

Added the required .npmrc file to our project and the build process runs just fine on our developer machines using the Access token in our profile folder .npmrc.

But the Build on the server failed.

We enabled the OAuth-Token in the Build definition (Options -> Allow Scripts to Access OAuth Token).

Here is the log from the build:

```
2017-03-17T10:01:34.5183227Z ##[section]Starting: npm install Common
2017-03-17T10:01:34.5651478Z ==============================================================================
2017-03-17T10:01:34.5651478Z Task         : npm
2017-03-17T10:01:34.5651478Z Description  : Run an npm command
2017-03-17T10:01:34.5651478Z Version      : 0.2.21
2017-03-17T10:01:34.5651478Z Author       : Microsoft Corporation
2017-03-17T10:01:34.5651478Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613746)
2017-03-17T10:01:34.5651478Z ==============================================================================
2017-03-17T10:01:35.7099170Z SYSTEMVSSCONNECTION exists true
2017-03-17T10:01:35.7099170Z [command]C:\BuildAgent1\_work\_tasks\Npm_fe47e961-9fa8-4106-8639-368c022d43ad\0.2.21\Npm\vsts-npm-auth\bin\vsts-npm-auth.exe -NonInteractive -Verbosity Normal -Config C:\BuildAgent1\_work\2\s\Common\Client\Project\.npmrc -TargetConfig C:\BuildAgent1\_work\2\npm\auth.3659.npmrc
2017-03-17T10:01:36.0379920Z 
2017-03-17T10:01:36.0379920Z vsts-npm-auth v0.23.0.0 
2017-03-17T10:01:36.0379920Z -----------------------
2017-03-17T10:01:36.0848387Z Creating npmrcFile. Path: C:\BuildAgent1\_work\2\npm\auth.3659.npmrc
2017-03-17T10:01:36.5535926Z ##[warning]Failed to get the required authentication tokens for npm. Error: C:\BuildAgent1\_work\_tasks\Npm_fe47e961-9fa8-4106-8639-368c022d43ad\0.2.21\Npm\vsts-npm-auth\bin\vsts-npm-auth.exe failed with return code: 1
2017-03-17T10:01:36.5535926Z [command]C:\Program Files\nodejs\npm.cmd config list
2017-03-17T10:01:38.2411318Z ; cli configs
2017-03-17T10:01:38.2411318Z metrics-registry = "https://[tfsserver]/tfs/DefaultCollection/_packaging/default/npm/registry"
2017-03-17T10:01:38.2411318Z scope = ""
2017-03-17T10:01:38.2411318Z user-agent = "npm/4.4.1 node/v7.7.3 win32 x64"
2017-03-17T10:01:38.2411318Z 
2017-03-17T10:01:38.2411318Z ; environment configs
2017-03-17T10:01:38.2411318Z userconfig = "C:\\BuildAgent1\\_work\\2\\npm\\auth.3659.npmrc"
2017-03-17T10:01:38.2411318Z 
2017-03-17T10:01:38.2411318Z ; project config C:\BuildAgent1\_work\2\s\Common\Client\Project\.npmrc
2017-03-17T10:01:38.2411318Z always-auth = true
2017-03-17T10:01:38.2411318Z registry = "https://[tfsserver]/tfs/DefaultCollection/_packaging/default/npm/registry"
2017-03-17T10:01:38.2411318Z 
2017-03-17T10:01:38.2411318Z ; builtin config undefined
2017-03-17T10:01:38.2411318Z prefix = "C:\\Users\\[serviceaccount]\\AppData\\Roaming\\npm"
2017-03-17T10:01:38.2411318Z 
2017-03-17T10:01:38.2411318Z ; node bin location = C:\Program Files\nodejs\node.exe
2017-03-17T10:01:38.2411318Z ; cwd = C:\BuildAgent1\_work\2\s\Common\Client\Project
2017-03-17T10:01:38.2411318Z ; HOME = C:\Users\[serviceaccount]
2017-03-17T10:01:38.2411318Z ; "npm config ls -l" to show all defaults.
```

What do we need to get this working?

**Comment by keithrob** [comment]
Thanks for reaching out.  Couple of questions for you...

1. Is your build agent connected to the account identified by [tfsserver].  IOW, if you have multiple accounts you need to ensure that this build agent is connected to the same account identified by "registry =".  
2. Is the build agent running on win or *nix?

Keith

**Comment by henning-krause** [comment]
Hi Keith,

1. agent under a domain account.... I'm not sure what you mean exactly. Find our .npmrc file below.
2. Windows

Contents of the .npmrc file in the project:
```
registry=https://[tfsserver]/tfs/DefaultCollection/_packaging/default/npm/registry
always-auth=true
```

**Comment by keithrob** [comment]
At this point, I think we should probably take this off line and triage together.  Would you mind reaching out to me at kerobert AT microsoft.com?  I will work with you to resolve the issue.
Thanks,
Keith

**Comment by SayusiAndo** [comment]
Hey Guys, Sorry for polluting this thread, but I don't know where can I ask my questions regarding vsts-npm-auth. Is this place what I'm looking for? Thanks!

**Comment by keithrob** [comment]
@SayusiAndo, ask your question and we can decide if it is related to this thread or not.

**Comment by SayusiAndo** [comment]
Ok, thanks.

It seems my issue is similar what @henning-krause has. 
I have a build where I need packages from Telerik private, @progress, repository. I have the following build steps setup in our VSTS build (it is company VSO account).

**Info**:

- our account is companyiname.visualstudio.com
- build agents: managed by vso infrastructure pooling system (I don't know the proper word for it, sorry)
- build agent OS: windows (I can't find further info about the machine I get from the pool)

**Build steps:**

1. npm install -g vsts-npm-auth
2. npm install vsts-npm-auth
3. npm run telerikAuth, it runs the script : ```vsts-npm-auth.exe -C .npmrc_credentials -T .npmrc -V detailed``` and fails. You can find the error message from VSTS build below.

**Content of .npmrc**

```
@progress:registry=https://registry.npm.telerik.com/
always-auth=true
```

**Content of .npmrc_credentials**

```
@progress:registry=https://registry.npm.telerik.com/
always-auth=true
Password=verysecretpassword
Username=my.account
Email=my.email.address@mycompany.com
```

The build step fails with the message below:

```
2017-03-24T06:39:30.3553874Z ##[section]Starting: npm run
2017-03-24T06:39:30.3553874Z ==============================================================================
2017-03-24T06:39:30.3553874Z Task         : npm
2017-03-24T06:39:30.3553874Z Description  : Run an npm command
2017-03-24T06:39:30.3553874Z Version      : 0.2.21
2017-03-24T06:39:30.3553874Z Author       : Microsoft Corporation
2017-03-24T06:39:30.3553874Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613746)
2017-03-24T06:39:30.3553874Z ==============================================================================
2017-03-24T06:39:30.5741510Z SYSTEMVSSCONNECTION exists true
2017-03-24T06:39:30.5741510Z [command]e:\v\a1\_tasks\Npm_fe47e961-9fa8-4106-8639-368c022d43ad\0.2.21\Npm\vsts-npm-auth\bin\vsts-npm-auth.exe -NonInteractive -Verbosity Normal -Config e:\v\a1\26\s\src\Host\DeliveryDashboard.Host.Ui.Spa\.npmrc -TargetConfig e:\v\a1\26\npm\auth.396109.npmrc
2017-03-24T06:39:30.7460602Z 
2017-03-24T06:39:30.7460602Z vsts-npm-auth v0.23.0.0 
2017-03-24T06:39:30.7460602Z -----------------------
2017-03-24T06:39:30.7616592Z Creating npmrcFile. Path: e:\v\a1\26\npm\auth.396109.npmrc
2017-03-24T06:39:30.9960474Z ##[warning]Failed to get the required authentication tokens for npm. Error: e:\v\a1\_tasks\Npm_fe47e961-9fa8-4106-8639-368c022d43ad\0.2.21\Npm\vsts-npm-auth\bin\vsts-npm-auth.exe failed with return code: 1
2017-03-24T06:39:30.9960474Z [command]C:\Program Files\nodejs\npm.cmd config list
2017-03-24T06:39:32.1836305Z ; cli configs
2017-03-24T06:39:32.1836305Z user-agent = "npm/3.10.3 node/v6.5.0 win32 x64"
2017-03-24T06:39:32.1836305Z 
2017-03-24T06:39:32.1836305Z ; environment configs
2017-03-24T06:39:32.1836305Z userconfig = "e:\\v\\a1\\26\\npm\\auth.396109.npmrc"
2017-03-24T06:39:32.1836305Z 
2017-03-24T06:39:32.1836305Z ; project config e:\v\a1\26\s\src\Host\DeliveryDashboard.Host.Ui.Spa\.npmrc
2017-03-24T06:39:32.1836305Z @progress:registry = "https://registry.npm.telerik.com/"
2017-03-24T06:39:32.1836305Z always-auth = true
2017-03-24T06:39:32.1836305Z 
2017-03-24T06:39:32.1836305Z ; builtin config undefined
2017-03-24T06:39:32.1836305Z prefix = "C:\\Users\\VSOBuilds\\AppData\\Roaming\\npm"
2017-03-24T06:39:32.1836305Z 
2017-03-24T06:39:32.1836305Z ; node bin location = C:\Program Files\nodejs\node.exe
2017-03-24T06:39:32.1836305Z ; cwd = e:\v\a1\26\s\src\Host\DeliveryDashboard.Host.Ui.Spa
2017-03-24T06:39:32.1836305Z ; HOME = C:\Users\VSOBuilds
2017-03-24T06:39:32.1836305Z ; "npm config ls -l" to show all defaults.
2017-03-24T06:39:32.1836305Z 
2017-03-24T06:39:32.1992483Z [command]C:\Program Files\nodejs\npm.cmd run telerikAuth
2017-03-24T06:39:33.3868071Z 
2017-03-24T06:39:33.3868071Z > delivery-dashboard.host.ui.spa@0.0.0 telerikAuth e:\v\a1\26\s\src\Host\DeliveryDashboard.Host.Ui.Spa
2017-03-24T06:39:33.3868071Z > vsts-npm-auth -C .npmrc_credentials -T .npmrc -V detailed
2017-03-24T06:39:33.5743050Z 
2017-03-24T06:39:33.5743050Z 
2017-03-24T06:39:33.5743050Z vsts-npm-auth v0.21.0.0 
2017-03-24T06:39:33.5743050Z -----------------------
2017-03-24T06:39:33.5743050Z Parameters:
2017-03-24T06:39:33.5743050Z   AuthenticationProviders=wia,federated
2017-03-24T06:39:33.5743050Z   Config=.npmrc_credentials
2017-03-24T06:39:33.5743050Z   Help=False
2017-03-24T06:39:33.5743050Z   NonInteractive=False
2017-03-24T06:39:33.5743050Z   TargetConfig=.npmrc
2017-03-24T06:39:33.5743050Z   Verbosity=Detailed
2017-03-24T06:39:33.5899297Z INI (resolved): @progress:registry=https://registry.npm.telerik.com/
2017-03-24T06:39:33.5899297Z INI (resolved): always-auth=true
2017-03-24T06:39:33.5899297Z INI (resolved): @progress:registry=https://registry.npm.telerik.com/
2017-03-24T06:39:33.5899297Z INI (resolved): always-auth=true
2017-03-24T06:39:33.5899297Z INI (resolved): Password=verysecretpassword
2017-03-24T06:39:33.5899297Z INI (resolved): Username=my.account
2017-03-24T06:39:33.5899297Z INI (resolved): Email=my.email.address@mycompany.com
2017-03-24T06:39:33.6055553Z System.ArgumentNullException: Value cannot be null.
2017-03-24T06:39:33.6055553Z Parameter name: uriString
2017-03-24T06:39:33.6055553Z    at System.Uri..ctor(String uriString)
2017-03-24T06:39:33.6055553Z    at VSTS.Npm.Auth.NerfDart..ctor(String uri)
2017-03-24T06:39:33.6055553Z    at VSTS.Npm.Auth.NpmConfig.GetNpmrcKeyNameForRegistryAuthToken(String registry)
2017-03-24T06:39:33.6055553Z    at VSTS.Npm.Auth.NpmConfig.<GetPackageSources>d__9.MoveNext()
2017-03-24T06:39:33.6055553Z    at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
2017-03-24T06:39:33.6055553Z    at System.Linq.Enumerable.<DistinctIterator>d__63`1.MoveNext()
2017-03-24T06:39:33.6055553Z    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
2017-03-24T06:39:33.6055553Z    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
2017-03-24T06:39:33.6055553Z    at VSTS.Npm.Auth.NpmAuthHelper.GetPackageSources()
2017-03-24T06:39:33.6055553Z    at VSTS.Npm.Auth.NpmAuthHelper.UpdateCredentialsForSource()
2017-03-24T06:39:33.6055553Z    at VSTS.Npm.Auth.Program.Main(String[] args)
2017-03-24T06:39:33.6211807Z 
2017-03-24T06:39:33.6211807Z npm ERR! Windows_NT 6.3.9600
2017-03-24T06:39:33.6211807Z npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "telerikAuth"
2017-03-24T06:39:33.6211807Z npm ERR! node v6.5.0
2017-03-24T06:39:33.6211807Z npm ERR! npm  v3.10.3
2017-03-24T06:39:33.6211807Z npm ERR! code ELIFECYCLE
2017-03-24T06:39:33.6211807Z npm ERR! delivery-dashboard.host.ui.spa@0.0.0 telerikAuth: `vsts-npm-auth -C .npmrc_credentials -T .npmrc -V detailed`
2017-03-24T06:39:33.6211807Z npm ERR! Exit status 1
2017-03-24T06:39:33.6211807Z npm ERR! 
2017-03-24T06:39:33.6211807Z npm ERR! Failed at the delivery-dashboard.host.ui.spa@0.0.0 telerikAuth script 'vsts-npm-auth -C .npmrc_credentials-T .npmrc -V detailed'.
2017-03-24T06:39:33.6211807Z npm ERR! Make sure you have the latest version of node.js and npm installed.
2017-03-24T06:39:33.6211807Z npm ERR! If you do, this is most likely a problem with the delivery-dashboard.host.ui.spa package,
2017-03-24T06:39:33.6211807Z npm ERR! not with npm itself.
2017-03-24T06:39:33.6211807Z npm ERR! Tell the author that this fails on your system:
2017-03-24T06:39:33.6211807Z npm ERR!     vsts-npm-auth -C .npmrc_credentials -T .npmrc -V detailed
2017-03-24T06:39:33.6211807Z npm ERR! You can get information on how to open an issue for this project with:
2017-03-24T06:39:33.6211807Z npm ERR!     npm bugs delivery-dashboard.host.ui.spa
2017-03-24T06:39:33.6211807Z npm ERR! Or if that isn't available, you can get their info via:
2017-03-24T06:39:33.6211807Z npm ERR!     npm owner ls delivery-dashboard.host.ui.spa
2017-03-24T06:39:33.6211807Z npm ERR! There is likely additional logging output above.
2017-03-24T06:39:33.6211807Z 
2017-03-24T06:39:33.6211807Z npm ERR! Please include the following file with any support request:
2017-03-24T06:39:33.6211807Z npm ERR!     e:\v\a1\26\s\src\Host\DeliveryDashboard.Host.Ui.Spa\npm-debug.log
2017-03-24T06:39:33.6368065Z ##[error]npm failed with error: C:\Program Files\nodejs\npm.cmd failed with return code: 1
2017-03-24T06:39:33.6368065Z ##[section]Finishing: npm run
```

**What I tried so far**:
1. It is not clear for me how the .npmrc file should like. Telerik mentions this version:
```
@progress:registry=https://registry.npm.telerik.com/
always-auth=true
```

NPM sites and MS mention this one:
```
registry=https://registry.npm.telerik.com/
always-auth=true
```

In the first case the error is what I posted above, the long error message. In the second case it gets more stranger.

1. `npm install -g vsts-npm-auth` runs successfully
2. `npm install vsts-npm-auth` fails the error below:

```
2017-03-24T07:07:44.8645522Z ##[section]Starting: npm install
2017-03-24T07:07:44.8645522Z ==============================================================================
2017-03-24T07:07:44.8645522Z Task         : npm
2017-03-24T07:07:44.8645522Z Description  : Run an npm command
2017-03-24T07:07:44.8645522Z Version      : 0.2.21
2017-03-24T07:07:44.8645522Z Author       : Microsoft Corporation
2017-03-24T07:07:44.8645522Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613746)
2017-03-24T07:07:44.8645522Z ==============================================================================
2017-03-24T07:07:45.0677108Z SYSTEMVSSCONNECTION exists true
2017-03-24T07:07:45.0677108Z [command]e:\v\a1\_tasks\Npm_fe47e961-9fa8-4106-8639-368c022d43ad\0.2.21\Npm\vsts-npm-auth\bin\vsts-npm-auth.exe -NonInteractive -Verbosity Normal -Config e:\v\a1\26\s\src\Host\DeliveryDashboard.Host.Ui.Spa\.npmrc -TargetConfig e:\v\a1\26\npm\auth.396111.npmrc
2017-03-24T07:07:45.2239684Z 
2017-03-24T07:07:45.2239684Z vsts-npm-auth v0.23.0.0 
2017-03-24T07:07:45.2239684Z -----------------------
2017-03-24T07:07:45.2552220Z Creating npmrcFile. Path: e:\v\a1\26\npm\auth.396111.npmrc
2017-03-24T07:07:45.4739583Z ##[warning]Failed to get the required authentication tokens for npm. Error: e:\v\a1\_tasks\Npm_fe47e961-9fa8-4106-8639-368c022d43ad\0.2.21\Npm\vsts-npm-auth\bin\vsts-npm-auth.exe failed with return code: 1
2017-03-24T07:07:45.4739583Z [command]C:\Program Files\nodejs\npm.cmd config list
2017-03-24T07:07:46.6615189Z ; cli configs
2017-03-24T07:07:46.6615189Z user-agent = "npm/3.10.3 node/v6.5.0 win32 x64"
2017-03-24T07:07:46.6615189Z 
2017-03-24T07:07:46.6615189Z ; environment configs
2017-03-24T07:07:46.6615189Z userconfig = "e:\\v\\a1\\26\\npm\\auth.396111.npmrc"
2017-03-24T07:07:46.6615189Z 
2017-03-24T07:07:46.6615189Z ; project config e:\v\a1\26\s\src\Host\DeliveryDashboard.Host.Ui.Spa\.npmrc
2017-03-24T07:07:46.6615189Z always-auth = true
2017-03-24T07:07:46.6615189Z registry = "https://registry.npm.telerik.com/"
2017-03-24T07:07:46.6615189Z 
2017-03-24T07:07:46.6615189Z ; builtin config undefined
2017-03-24T07:07:46.6615189Z prefix = "C:\\Users\\VSOBuilds\\AppData\\Roaming\\npm"
2017-03-24T07:07:46.6615189Z 
2017-03-24T07:07:46.6615189Z ; node bin location = C:\Program Files\nodejs\node.exe
2017-03-24T07:07:46.6615189Z ; cwd = e:\v\a1\26\s\src\Host\DeliveryDashboard.Host.Ui.Spa
2017-03-24T07:07:46.6615189Z ; HOME = C:\Users\VSOBuilds
2017-03-24T07:07:46.6615189Z ; "npm config ls -l" to show all defaults.
2017-03-24T07:07:46.6615189Z 
2017-03-24T07:07:46.6771566Z [command]C:\Program Files\nodejs\npm.cmd install vsts-npm-auth
2017-03-24T07:08:58.0807563Z npm ERR! Windows_NT 6.3.9600
2017-03-24T07:08:58.0807563Z npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "vsts-npm-auth"
2017-03-24T07:08:58.0807563Z npm ERR! node v6.5.0
2017-03-24T07:08:58.0807563Z npm ERR! npm  v3.10.3
2017-03-24T07:08:58.0807563Z 
2017-03-24T07:08:58.0807563Z npm ERR! This request requires auth credentials. Run `npm login` and repeat the request.
2017-03-24T07:08:58.0807563Z npm ERR! 
2017-03-24T07:08:58.0807563Z npm ERR! If you need help, you may report this error at:
2017-03-24T07:08:58.0807563Z npm ERR!     <https://github.com/npm/npm/issues>
2017-03-24T07:08:58.0963747Z 
2017-03-24T07:08:58.0963747Z npm ERR! Please include the following file with any support request:
2017-03-24T07:08:58.0963747Z npm ERR!     e:\v\a1\26\s\src\Host\DeliveryDashboard.Host.Ui.Spa\npm-debug.log
2017-03-24T07:08:58.0963747Z ##[error]npm failed with error: C:\Program Files\nodejs\npm.cmd failed with return code: 1
2017-03-24T07:08:58.1119781Z ##[section]Finishing: npm install
```

**What I figured out so far**:

1. in the npm install section two versions of vsts-npm-auth mentioned, v0.23.0.0 and v0.22 is installed

```
2017-03-24T06:39:26.5602740Z ##[section]Starting: npm install
2017-03-24T06:39:26.5602740Z ==============================================================================
2017-03-24T06:39:26.5602740Z Task         : npm
2017-03-24T06:39:26.5602740Z Description  : Run an npm command
2017-03-24T06:39:26.5602740Z Version      : 0.2.21
2017-03-24T06:39:26.5602740Z Author       : Microsoft Corporation
2017-03-24T06:39:26.5602740Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613746)
2017-03-24T06:39:26.5602740Z ==============================================================================
2017-03-24T06:39:26.7790359Z SYSTEMVSSCONNECTION exists true
2017-03-24T06:39:26.7790359Z [command]e:\v\a1\_tasks\Npm_fe47e961-9fa8-4106-8639-368c022d43ad\0.2.21\Npm\vsts-npm-auth\bin\vsts-npm-auth.exe -NonInteractive -Verbosity Normal -Config e:\v\a1\26\s\src\Host\DeliveryDashboard.Host.Ui.Spa\.npmrc -TargetConfig e:\v\a1\26\npm\auth.396109.npmrc
2017-03-24T06:39:26.9196680Z 
2017-03-24T06:39:26.9196680Z vsts-npm-auth v0.23.0.0 
2017-03-24T06:39:26.9196680Z -----------------------
2017-03-24T06:39:26.9509197Z Creating npmrcFile. Path: e:\v\a1\26\npm\auth.396109.npmrc
2017-03-24T06:39:27.1540555Z ##[warning]Failed to get the required authentication tokens for npm. Error: e:\v\a1\_tasks\Npm_fe47e961-9fa8-4106-8639-368c022d43ad\0.2.21\Npm\vsts-npm-auth\bin\vsts-npm-auth.exe failed with return code: 1
2017-03-24T06:39:27.1540555Z [command]C:\Program Files\nodejs\npm.cmd config list
2017-03-24T06:39:28.2791152Z ; cli configs
2017-03-24T06:39:28.2791152Z user-agent = "npm/3.10.3 node/v6.5.0 win32 x64"
2017-03-24T06:39:28.2791152Z 
2017-03-24T06:39:28.2791152Z ; environment configs
2017-03-24T06:39:28.2791152Z userconfig = "e:\\v\\a1\\26\\npm\\auth.396109.npmrc"
2017-03-24T06:39:28.2791152Z 
2017-03-24T06:39:28.2791152Z ; project config e:\v\a1\26\s\src\Host\DeliveryDashboard.Host.Ui.Spa\.npmrc
2017-03-24T06:39:28.2791152Z @progress:registry = "https://registry.npm.telerik.com/"
2017-03-24T06:39:28.2791152Z always-auth = true
2017-03-24T06:39:28.2791152Z 
2017-03-24T06:39:28.2791152Z ; builtin config undefined
2017-03-24T06:39:28.2791152Z prefix = "C:\\Users\\VSOBuilds\\AppData\\Roaming\\npm"
2017-03-24T06:39:28.2791152Z 
2017-03-24T06:39:28.2791152Z ; node bin location = C:\Program Files\nodejs\node.exe
2017-03-24T06:39:28.2791152Z ; cwd = e:\v\a1\26\s\src\Host\DeliveryDashboard.Host.Ui.Spa
2017-03-24T06:39:28.2791152Z ; HOME = C:\Users\VSOBuilds
2017-03-24T06:39:28.2791152Z ; "npm config ls -l" to show all defaults.
2017-03-24T06:39:28.2791152Z 
2017-03-24T06:39:28.2947395Z [command]C:\Program Files\nodejs\npm.cmd install vsts-npm-auth
2017-03-24T06:39:30.3397625Z delivery-dashboard.host.ui.spa@0.0.0 e:\v\a1\26\s\src\Host\DeliveryDashboard.Host.Ui.Spa
2017-03-24T06:39:30.3397625Z `-- vsts-npm-auth@0.22.0 
2017-03-24T06:39:30.3397625Z 
2017-03-24T06:39:30.3553874Z ##[section]Finishing: npm install
```

npm info says:
```
$ npm info vsts-npm-auth

{ name: 'vsts-npm-auth',
  description: 'Auth Helper for npm in Visual Studio Team Services',
  'dist-tags': { latest: '0.22.0' },
  versions: [ '0.21.0', '0.22.0' ],
  maintainers: [ 'vsonline <bigbldt@microsoft.com>' ],
  time:
   { modified: '2017-01-05T21:02:46.545Z',
     created: '2016-11-01T17:45:52.689Z',
     '0.21.0': '2016-11-01T17:45:52.689Z',
     '0.22.0': '2016-11-01T23:24:28.673Z' },
  keywords: [ 'vsts' ],
  author: 'vsonline',
  license: 'SEE LICENSE IN EULA_MICROSOFT VISUAL STUDIO TEAM SERVICES AUTHHELPER FOR NPM.DOCX',
  readmeFilename: 'README.md',
  users: { drewigg: true },
  bin: { 'vsts-npm-auth': 'bin/vsts-npm-auth.exe' },
  scripts: { test: 'echo "Error: no test specified" && exit 1' },
  version: '0.22.0',
  main: 'index.js',
  dist:
   { shasum: '5b65e7ed97c875a41c165fff2cec80fe3dfecf37',
     tarball: 'https://registry.npmjs.org/vsts-npm-auth/-/vsts-npm-auth-0.22.0.tgz' },
  directories: {} }
```

2. the missing uriString in the error message is not mentioned in the documentation
```
$ node_modules/vsts-npm-auth/bin/vsts-npm-auth.exe
The argument 'Config' is required
Usage - vsts-npm-auth -options

GlobalOption          Description
Help (-?)             Shows this help
NonInteractive (-N)   Don't allow interactively prompting for credentials to
                      obtain a token
Config* (-C)          Comma-separated list of paths to npm configuration
                      file containing package sources to acquire
                      authentication tokens for
TargetConfig (-T)     npm configuration file to write the generated tokens
                      to. Usually user tokens are written to
                      %USERPROFILE%/.npmrc, ~/.npmrc or $HOME/.npmrc
Verbosity (-V)        Display this amount of detail in the output: silent,
                      quiet, normal, detailed.
                      Silent
                      Quiet
                      Normal
                      Detailed
```
3. There is a huge chance I do something wrong because the internet doesn't know this issue. Or people don't install npm packages from private repos in their builds. I believe it is unlikely.

Thanks for your help!

**Comment by henning-krause** [comment]
Thanks to @keithrob, we can wrap this up quickly: The vsts-npm-auth does not yet support on-premise installations. 

To work around this, we just followed the instructions in https://www.visualstudio.com/en-us/docs/package/npm/npmrc and put the .npmrc file containing the auth token in the home directory of the user running our build agent...

**Comment by keithrob** [comment]
@SayusiAndo,
Your problem is indeed different than Henning's and we should start a new thread.  However, I will say that it looks like you are using a private scoped registry with the default npm task.  The 'vsts-npm-auth' clearly isn't handling this external private registry very well (*.npm.telerik.com) and we will fix that.

In the meantime, I would suggest you use a powershell script to do an 'npm install'.  Also, I'm curious why you're using a private registry from *.npm.telerik.com when you can create a feed in your VSO account to host all of your private npm packages.  Instructions for that are [here](https://www.visualstudio.com/en-us/docs/package/npm/npmrc).

**Comment by keithrob** [comment]
Thanks @henning-krause for allowing us to triage with you today. 

For everyone else that reads this thread, vsts-npm-auth is unable to get credentials from an on-premise TFS server.  We will be fixing this; however, the near term solution is to generate a token and place it into the home directory of your build agent as Henning suggested.  The npm client will discover the token there and  successfully authenticate with your on-premise server.

**Comment by SayusiAndo** [comment]
@keithrob 
Thanks for your feedback and I apologize to get back that late. Do you need anything from my side? New ticket, a detailed user scenario?

**Comment by keithrob** [comment]
This issue is closed.  I would as that you open a new issue and tag me.

**Comment by ba55ie** [comment]
Our working fix is:

1. Put a `.npmrc` file with the authentication token in the same folder as your `package.json`.
1. Include this file in your repository (we use a read-only user token).
1. In your build definitions NPM install task:
    - Set the `working folder` to the folder containing the `.npmrc` and `package.json` files.
    - Add the argument `--userconfig=./.npmrc`.
1. Success!

You can ignore the `vsts-npm-auth ##[warning]Failed to get the required authentication tokens for npm` error.

![npmrc-tfs](https://user-images.githubusercontent.com/1845545/29915308-bd117a72-8e3b-11e7-8682-d5a3d2a49443.png)

We are using the following versions on the server:
- TFS 15.117.26714.0
- NPM task 0.2.22
- NodeJS 8.3.0
- NPM 5.3.0

**Comment by japj** [comment]
@keithrob is vsts-npm-auth (v0.37.0.0) supporting TFS on-premise officially yet?
I can't seem to get it working for TFS2018U3/AzureDevOpsServer2019.

**Comment by schmidtaa** [comment]
Same problem here - vsts not able to authorize for On-prem TFS.
