### ISSUE TITLE
Intermittent issue with async calls from PS task

### ISSUE THREAD

**Issue by mmajcica** [Microsoft/vsts-tasks#3858]
Dear,

I started experiencing an intermittent issue with my build/release task.

At the certain point I do the following:

```
$response = $httpClient.PostAsync("$EndpointUrl/package/upload/$fileName", $content).GetAwaiter().GetResult()
```

This succeeds or fails with no apparent reason. Sometimes the build or a deployment in the release goes well and this succeeds, other times I do get the following exception:

```
2017-03-24T13:35:48.5310353Z ##[debug]System.Management.Automation.MethodInvocationException: Exception calling "GetResult" with "0" argument(s): "The stream does not support concurrent IO read or write operations." ---> System.NotSupportedException: The stream does not support concurrent IO read or write operations.
 
2017-03-24T13:35:48.5310353Z ##[debug]   at System.Net.ConnectStream.InternalWrite(Boolean async, Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
 
2017-03-24T13:35:48.5310353Z ##[debug]   at System.Net.ConnectStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
 
2017-03-24T13:35:48.5310353Z ##[debug]   at System.Net.Http.StreamToStreamCopy.TryStartWriteSync(Int32 bytesRead)
 
2017-03-24T13:35:48.5310353Z ##[debug]   at System.Net.Http.StreamToStreamCopy.BufferReadCallback(IAsyncResult ar)
 
2017-03-24T13:35:48.5310353Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
 
2017-03-24T13:35:48.5310353Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 
2017-03-24T13:35:48.5310353Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 
2017-03-24T13:35:48.5310353Z ##[debug]   at CallSite.Target(Closure , CallSite , Object )
 
2017-03-24T13:35:48.5310353Z ##[debug]   --- End of inner exception stack trace ---
 
2017-03-24T13:35:48.5310353Z ##[debug]   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
 
2017-03-24T13:35:48.5465886Z ##[debug]   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
 
2017-03-24T13:35:48.5465886Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
 
2017-03-24T13:35:48.5465886Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
 
2017-03-24T13:35:48.5622313Z ##[error]Exception calling "GetResult" with "0" argument(s): "The stream does not support concurrent IO read or write operations."
```

I can't reproduce this locally (by running the script used by the build task from the build server) and it happens only once the agent runs this code, so I am doubting that this is an issue that may be due to the way agent is executing the tasks.
Any suggestion or tip will be appreciated as I really do not know on how to continue.

Thanks

**Comment by ericsciple** [comment]
is this from an ad-hoc powershell script, or a custom task? if custom task, which execution handler?

**Comment by mmajcica** [comment]
It is a custom task with PowerShell3 execution handler.

**Comment by ericsciple** [comment]
That handler launches powershell with `-STA -NonInteractive` and also the entry script is wrapped in a try/catch. Those two things might influence something differently than when you run it locally.

**Comment by ericsciple** [comment]
Have you considered using the request cmdlets that powershell exposes? or is there a synchronous function you can call?

**Comment by ericsciple** [comment]
what http client class are you using?

**Comment by mmajcica** [comment]
The problem is that Invoke-WebRequest or other similar Cmdlets can't do the type of call I'm using. I need a Multipart/form-data request and I'm using a technique I described here http://blog.majcica.com/2016/01/13/powershell-tips-and-tricks-multipartform-data-requests/.
For a year I had no issues with this code and a couple of weeks ago I started facing the above.
If I used this in, at example, the release deployment, it will fail once or twice with the above exception, then suddenly succeed.
I will now create a System.NET Trace as the last thing I can do in order to try to understand what is happening. And it is the same also with the hosted agent.

**Comment by mmajcica** [comment]
I made some progress here. If I do wrap my, incriminated, cmdlet into a Start-Job and wait for it to finish, the error doesn't occur anymore.
So it has to do something with the way the agent is executing this code...
Unfortunately I can't still tell what, however I will continue digging. If you have any suggestions they will be more than welcome.

**Comment by ericsciple** [comment]
closing this is also tracked here https://github.com/Microsoft/vsts-agent/issues/881
