### ISSUE TITLE
MSTestV2 Test upload fails when using paramerterized tests

### ISSUE THREAD

**Issue by henning-krause** [Microsoft/vsts-tasks#3887]
Environment: TFS 2017 with SP1
Task: Visual Studio Test Task
Version: 2.x
Run in parallel: Yes
Run only impacted tests: Yes
VSTest Version: 2017

Normal unittests run just fine.

Now I added a like this one:

```cs
[TestMethod]
[DataRow(0, 0)]
[DataRow(3, 4)]
public void Test(int value, int expected)
{
	Assert.AreEqual(expected, value);
}
```

This tests works as expected on my dev machine.

On the build server however, the mstests tasks runs the test and than fails afterwards with this exception:

```
2017-03-28T08:19:31.0319813Z Total tests: 1877. Passed: 1857. Failed: 0. Skipped: 20.
2017-03-28T08:19:31.0319813Z Test Run Successful.
2017-03-28T08:19:31.0319813Z Test execution time: 2,5945 Minutes
2017-03-28T08:19:32.2976123Z Results File: C:\BuildAgent1\_work\1\s\TestResults\tfssrv_tfssrv 2017-03-28 10_17_08.trx
2017-03-28T08:19:39.5875885Z [command]C:\BuildAgent1\_work\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.0.11\TestSelector\TestSelector.exe UpdateTestResults
2017-03-28T08:19:41.6623674Z PERF: GetTestCaseResults: took 1651.5843 ms
2017-03-28T08:19:41.9577751Z PERF: ReadResultsFromFile: took 293.5493 ms
2017-03-28T08:19:44.8855179Z PERF: UpdateResultsAndSignatures: took 2921.8993 ms
2017-03-28T08:19:44.9167705Z 
2017-03-28T08:19:44.9167705Z Exception : Index was out of range. Must be non-negative and less than the size of the collection.
2017-03-28T08:19:44.9167705Z Parameter name: index
2017-03-28T08:19:44.9167705Z 
2017-03-28T08:19:44.9167705Z  Stack :    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
2017-03-28T08:19:44.9167705Z    at System.Collections.Generic.List`1.get_Item(Int32 index)
2017-03-28T08:19:44.9167705Z    at Microsoft.TeamFoundation.DistributedTask.Task.TestResults.TestRunPublisher.UpdateResults(TestCaseResultData[] testResults, List`1 tcmTestCaseResults, TestHttpClientBase testImpactClient, Int32 runId, Int32 definitionRunId, DefinitionType definitionType) in D:\v2.0\A2\_work\3\s\DistributedTask\Agent\Task.TestResults\TestRunPublisher.cs:line 152
2017-03-28T08:19:44.9167705Z    at Microsoft.TestFoundation.TestImpact.TestSelector.CommandUpdateTestResults.Run() in D:\v2.0\A2\_work\3\s\Ta\Tasks\TestImpact\TestSelector\Commands\Command\CommandUpdateTestResults.cs:line 133
2017-03-28T08:19:44.9167705Z    at Microsoft.TestFoundation.TestImpact.TestSelector.Program.RunCommand(String commandName, String[] args) in D:\v2.0\A2\_work\3\s\Ta\Tasks\TestImpact\TestSelector\Program.cs:line 41
2017-03-28T08:19:44.9636452Z ##[error]Vstest exited with return code: 1.
2017-03-28T08:19:44.9792701Z ##[section]Finishing: Run Unittests
```

**Comment by acesiddhu** [comment]
@henning-krause let me try to repro this. Will get back on this

**Comment by acesiddhu** [comment]
We got a repro. Looks like Run only impacted tests doesn't work with data driven test cases. I will discuss this internally, what it takes to implement Run only impacted tests with data driven tests. In the mean time if you are blocked you can either

1) divide your vstest task into two vstest tasks in your build definition. One which runs only data driven tests and other that runs non data driven tests. you can enable Run only impacted tests in non data driven tests

2) Or disable Run only impacted tests in the current vstest task in your build definition.

**Comment by henning-krause** [comment]
@RanjanarMS, has this been fixed?
