### ISSUE TITLE
VSTest Fails After Installing Visual Studio 2017 on build machine

### ISSUE THREAD

**Issue by rufio620** [Microsoft/vsts-tasks#3942]
I recently installed Visual Studio 2017 Community on my build machine. Now all testing tasks fail with the error below.

2017-04-05T05:28:57.9166057Z ##[section]Starting: Test Assemblies **\debug\*test*.dll;-:**\obj\**
2017-04-05T05:28:57.9387394Z ==============================================================================
2017-04-05T05:28:57.9387394Z Task         : Visual Studio Test
2017-04-05T05:28:57.9387394Z Description  : Run tests with Visual Studio test runner
2017-04-05T05:28:57.9387394Z Version      : 1.0.84
2017-04-05T05:28:57.9387394Z Author       : Microsoft Corporation
2017-04-05T05:28:57.9387394Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=624539)
2017-04-05T05:28:57.9387394Z ==============================================================================
2017-04-05T05:28:57.9543757Z Preparing task execution handler.
2017-04-05T05:29:16.3842853Z Executing the powershell script: C:\agent\_work\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\1.0.84\VSTest.ps1
2017-04-05T05:29:18.2796408Z 
2017-04-05T05:29:18.2796408Z 
2017-04-05T05:29:18.2841539Z 
2017-04-05T05:29:18.2841539Z 
2017-04-05T05:29:18.2841539Z ##[warning]No results found to publish.
2017-04-05T05:29:18.5233762Z ##[error]System.Management.Automation.CmdletInvocationException: Unable to determine the location of vstest.console.exe ---> System.IO.FileNotFoundException: Unable to determine the location of vstest.console.exe
2017-04-05T05:29:18.5233762Z    at Microsoft.TeamFoundation.DistributedTask.Task.Internal.InvokeVSTestCmdlet.GetVsTestLocation()
2017-04-05T05:29:18.5233762Z    at Microsoft.TeamFoundation.DistributedTask.Task.Internal.InvokeVSTestCmdlet.ProcessRecord()
2017-04-05T05:29:18.5233762Z    at System.Management.Automation.CommandProcessor.ProcessRecord()
2017-04-05T05:29:18.5233762Z    --- End of inner exception stack trace ---
2017-04-05T05:29:18.5233762Z    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
2017-04-05T05:29:18.5233762Z    at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
2017-04-05T05:29:18.5233762Z    at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
2017-04-05T05:29:18.5233762Z    at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2017-04-05T05:29:18.5233762Z    at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2017-04-05T05:29:18.5233762Z    at Microsoft.TeamFoundation.DistributedTask.Handlers.LegacyVSTSPowerShellHost.VSTSPowerShellHost.Main(String[] args)
2017-04-05T05:29:18.5389278Z ##[error]LegacyVSTSPowerShellHost.exe completed with return code: -1.
2017-04-05T05:29:18.5389278Z ##[section]Finishing: Test Assemblies **\debug\*test*.dll;-:**\obj\**

**Comment by rufio620** [comment]
Never mind just realized there was a new version of the task with Visual Studio 2017 support.
