### ISSUE TITLE
Receiving 504 Gateway Timeout error with SQL Database Deployment Task

### ISSUE THREAD

**Issue by gtewksbury** [Microsoft/vsts-tasks#4011]
I'm receiving the following error from the SQL Database Deployment Task.  Interestingly, this task works on my initial Release Management environment, however, it consistently fails on the second environment, which is a clone of the first.

2017-04-13T02:28:21.8778544Z ##[debug]Evaluating condition for step: 'Execute Azure SQL : DacpacTask'
2017-04-13T02:28:21.8778544Z ##[debug]Evaluating: succeeded()
2017-04-13T02:28:21.8778544Z ##[debug]Evaluating succeeded:
2017-04-13T02:28:21.8778544Z ##[debug]=> (Boolean) True
2017-04-13T02:28:21.8778544Z ##[debug]Expanded: True
2017-04-13T02:28:21.8778544Z ##[debug]Result: True
2017-04-13T02:28:21.8778544Z ##[section]Starting: Execute Azure SQL : DacpacTask
2017-04-13T02:28:21.8778544Z ==============================================================================
2017-04-13T02:28:21.8778544Z Task         : Azure SQL Database Deployment
2017-04-13T02:28:21.8778544Z Description  : Deploy Azure SQL DB using DACPAC or run scripts using SQLCMD
2017-04-13T02:28:21.8778544Z Version      : 1.1.9
2017-04-13T02:28:21.8788563Z Author       : Microsoft Corporation
2017-04-13T02:28:21.8788563Z Help         : [More Information](https://aka.ms/sqlazuredeployreadme)
2017-04-13T02:28:21.8788563Z ==============================================================================
2017-04-13T02:28:23.9900279Z ##[debug]VstsTaskSdk 0.7.1 commit f990f8d8df6197b1cfcec01031ba014ad4905681
2017-04-13T02:28:24.1860391Z ##[debug]Entering D:\a\_tasks\SqlAzureDacpacDeployment_ce85a08b-a538-4d2b-8589-1d37a9ab970f\1.1.9\DeploySqlAzure.ps1.
2017-04-13T02:28:24.2520283Z ##[debug]INPUT_CONNECTEDSERVICENAMESELECTOR: 'ConnectedServiceNameARM'
2017-04-13T02:28:24.2520283Z ##[debug]INPUT_TASKNAMESELECTOR: 'DacpacTask'
2017-04-13T02:28:24.2520283Z ##[debug]INPUT_DACPACFILE: 'd:\a\r1\a\CD Build\drop\Demo.DB\bin\Release\Demo.DB.dacpac'
2017-04-13T02:28:24.2520283Z ##[debug]INPUT_SQLFILE: 'd:\a\r1\a'
2017-04-13T02:28:24.2520283Z ##[debug]INPUT_SQLINLINE (empty)
2017-04-13T02:28:24.2520283Z ##[debug]INPUT_SERVERNAME: 'gtewksbootcampdbserver.database.windows.net'
2017-04-13T02:28:24.2520283Z ##[debug]INPUT_DATABASENAME: 'gtewksbootcamp'
2017-04-13T02:28:24.2660405Z ##[debug]INPUT_CONNECTEDSERVICENAME (empty)
2017-04-13T02:28:24.2660405Z ##[debug]INPUT_CONNECTEDSERVICENAMEARM: '231e9482-ee55-49ea-b03e-d858b65ff1d4'
2017-04-13T02:28:24.2670673Z ##[debug]INPUT_SQLUSERNAME: 'gtewksbury'
2017-04-13T02:28:24.2670673Z ##[debug]INPUT_SQLPASSWORD (empty)
2017-04-13T02:28:24.2670673Z ##[debug]INPUT_PUBLISHPROFILE: 'd:\a\r1\a'
2017-04-13T02:28:24.2690284Z ##[debug]INPUT_ADDITIONALARGUMENTS (empty)
2017-04-13T02:28:24.3100273Z ##[debug]INPUT_SQLADDITIONALARGUMENTS (empty)
2017-04-13T02:28:24.4170287Z ##[debug]INPUT_INLINEADDITIONALARGUMENTS (empty)
2017-04-13T02:28:24.6470263Z ##[debug]INPUT_IPDETECTIONMETHOD: 'AutoDetect'
2017-04-13T02:28:24.6470263Z ##[debug]INPUT_STARTIPADDRESS (empty)
2017-04-13T02:28:24.6470263Z ##[debug]INPUT_ENDIPADDRESS (empty)
2017-04-13T02:28:24.6470263Z ##[debug]INPUT_DELETEFIREWALLRULE: 'true'
2017-04-13T02:28:24.6480278Z ##[debug] Converted to bool: True
2017-04-13T02:28:24.6480278Z ##[debug]Loading module from path 'D:\a\_tasks\SqlAzureDacpacDeployment_ce85a08b-a538-4d2b-8589-1d37a9ab970f\1.1.9\ps_modules\VstsAzureRestHelpers_\VstsAzureRestHelpers_.psm1'.
2017-04-13T02:28:24.6480278Z ##[debug]$OVERRIDING $global:DebugPreference from 'Continue' to 'SilentlyContinue'.
2017-04-13T02:28:24.6480278Z ##[debug]Loading resource strings from: D:\a\_tasks\SqlAzureDacpacDeployment_ce85a08b-a538-4d2b-8589-1d37a9ab970f\1.1.9\ps_modules\VstsAzureRestHelpers_/module.json
2017-04-13T02:28:24.6480278Z ##[debug]Loaded 4 strings.
2017-04-13T02:28:24.6480278Z ##[debug]SYSTEM_CULTURE: 'en-US'
2017-04-13T02:28:24.6480278Z ##[debug]Loading resource strings from: D:\a\_tasks\SqlAzureDacpacDeployment_ce85a08b-a538-4d2b-8589-1d37a9ab970f\1.1.9\ps_modules\VstsAzureRestHelpers_\Strings\resources.resjson\en-US\resources.resjson
2017-04-13T02:28:24.6480278Z ##[debug]Loaded 4 strings.
2017-04-13T02:28:24.6480278Z ##[debug]Exporting function 'Add-AzureSqlDatabaseServerFirewallRule'.
2017-04-13T02:28:24.6480278Z ##[debug]Exporting function 'Remove-AzureSqlDatabaseServerFirewallRule'.
2017-04-13T02:28:24.6480278Z ##[debug]Exporting function 'Get-AzStorageKeys'.
2017-04-13T02:28:24.6480278Z ##[debug]Exporting function 'Get-AzRMStorageKeys'.
2017-04-13T02:28:24.6490281Z ##[debug]Exporting function 'Get-AzRmVmCustomScriptExtension'.
2017-04-13T02:28:24.6490281Z ##[debug]Exporting function 'Remove-AzRmVmCustomScriptExtension'.
2017-04-13T02:28:24.6490281Z ##[debug]Exporting function 'Get-AzStorageAccount'.
2017-04-13T02:28:24.6490281Z ##[debug]Exporting function 'Get-AzRmStorageAccount'.
2017-04-13T02:28:24.6490281Z ##[debug]Exporting function 'Get-AzRmResourceGroup'.
2017-04-13T02:28:24.6490281Z ##[debug]Importing function 'Add-AzureSqlDatabaseServerFirewallRule'.
2017-04-13T02:28:24.6490281Z ##[debug]Importing function 'Get-AzRmResourceGroup'.
2017-04-13T02:28:24.6490281Z ##[debug]Importing function 'Get-AzRmStorageAccount'.
2017-04-13T02:28:24.6490281Z ##[debug]Importing function 'Get-AzRMStorageKeys'.
2017-04-13T02:28:24.6490281Z ##[debug]Importing function 'Get-AzRmVmCustomScriptExtension'.
2017-04-13T02:28:24.6490281Z ##[debug]Importing function 'Get-AzStorageAccount'.
2017-04-13T02:28:24.6490281Z ##[debug]Importing function 'Get-AzStorageKeys'.
2017-04-13T02:28:24.6490281Z ##[debug]Importing function 'Remove-AzRmVmCustomScriptExtension'.
2017-04-13T02:28:24.6490281Z ##[debug]Importing function 'Remove-AzureSqlDatabaseServerFirewallRule'.
2017-04-13T02:28:24.6490281Z ##[debug]Loading resource strings from: D:\a\_tasks\SqlAzureDacpacDeployment_ce85a08b-a538-4d2b-8589-1d37a9ab970f\1.1.9/Task.json
2017-04-13T02:28:24.6490281Z ##[debug]Loaded 11 strings.
2017-04-13T02:28:24.6490281Z ##[debug]SYSTEM_CULTURE: 'en-US'
2017-04-13T02:28:24.6490281Z ##[debug]Loading resource strings from: D:\a\_tasks\SqlAzureDacpacDeployment_ce85a08b-a538-4d2b-8589-1d37a9ab970f\1.1.9\Strings\resources.resjson\en-US\resources.resjson
2017-04-13T02:28:24.6500273Z ##[debug]Loaded 11 strings.
2017-04-13T02:28:24.6500273Z ##[debug]FilePath= Find-VstsFiles LegacyPattern d:\a\r1\a\CD Build\drop\Demo.DB\bin\Release\Demo.DB.dacpac
2017-04-13T02:28:24.6500273Z ##[debug]Entering Find-VstsFiles.
2017-04-13T02:28:24.6500273Z ##[debug] LiteralDirectory: 'LegacyPattern'
2017-04-13T02:28:24.6500273Z ##[debug] LegacyPattern: 'd:\a\r1\a\CD Build\drop\Demo.DB\bin\Release\Demo.DB.dacpac'
2017-04-13T02:28:24.6980284Z ##[debug]Entering Get-MatchingItems.
2017-04-13T02:28:24.7790291Z ##[debug] IncludePatterns: 'd:\a\r1\a\CD Build\drop\Demo.DB\bin\Release\Demo.DB.dacpac'
2017-04-13T02:28:24.8020264Z ##[debug] ExcludePatterns: ''
2017-04-13T02:28:24.8040271Z ##[debug] IncludeFiles: 'True'
2017-04-13T02:28:24.8040271Z ##[debug] IncludeDirectories: 'False'
2017-04-13T02:28:24.8040271Z ##[debug] Force: 'False'
2017-04-13T02:28:24.9600271Z ##[debug]Path: d:\a\r1\a\CD Build\drop\Demo.DB\bin\Release\Demo.DB.dacpac
2017-04-13T02:28:24.9670280Z ##[debug]Leaving Get-MatchingItems.
2017-04-13T02:28:24.9690270Z ##[debug]Total found: 1
2017-04-13T02:28:24.9700267Z ##[debug]Leaving Find-VstsFiles.
2017-04-13T02:28:24.9790265Z packageFile= d:\a\r1\a\CD Build\drop\Demo.DB\bin\Release\Demo.DB.dacpac
2017-04-13T02:28:25.0010321Z ##[debug]Server friendly name is gtewksbootcampdbserver
2017-04-13T02:28:25.0050278Z ##[debug]ENDPOINT_URL_231e9482-ee55-49ea-b03e-d858b65ff1d4: 'https://management.azure.com/'
2017-04-13T02:28:25.0080269Z ##[debug]ENDPOINT_AUTH_231e9482-ee55-49ea-b03e-d858b65ff1d4: '********'
2017-04-13T02:28:25.0120270Z ##[debug]ENDPOINT_DATA_231e9482-ee55-49ea-b03e-d858b65ff1d4: '{"subscriptionId":"98e9f13f-64ab-4cbf-af82-f4e4e0e44607","subscriptionName":"Windows Azure  MSDN - Visual Studio Premium","azureSpnRoleAssignmentId":"d2a82218-5cbf-4a0a-9af8-3f3a57f8c003","spnObjectId":"f8eb8c26-1c13-4744-a4ee-952b52de325c","appObjectId":"c4b1a32a-30cb-4c36-b9b8-a535e1e3c028","creationMode":"Automatic","environment":"AzureCloud","environmentUrl":"https://management.azure.com/","galleryUrl":"https://gallery.azure.com/","serviceManagementUrl":"https://management.core.windows.net/","resourceManagerUrl":"https://management.azure.com/","activeDirectoryAuthority":"https://login.microsoftonline.com/","environmentAuthorityUrl":"https://login.windows.net/","graphUrl":"https://graph.windows.net/","managementPortalUrl":"https://manage.windowsazure.com/","armManagementPortalUrl":"https://portal.azure.com/","activeDirectoryServiceEndpointResourceId":"https://management.core.windows.net/","sqlDatabaseDnsSuffix":".database.windows.net"}'
2017-04-13T02:28:25.0180283Z ##[debug]Reching SqlServer to check connection by running sqlcmd.exe -S gtewksbootcampdbserver.database.windows.net -U gtewksbury -P  -Q "select getdate()"
2017-04-13T02:28:25.1460292Z ##[debug]Sqlcmd: '-P': Missing argument. Enter '-?' for help.
2017-04-13T02:28:25.1580291Z ##[debug]IP Range Prefix 
2017-04-13T02:28:25.2030379Z ##[debug]
2017-04-13T02:28:25.2980269Z ##[debug]
2017-04-13T02:28:25.2980269Z ##[debug]Name  : StartIPAddress
2017-04-13T02:28:25.2980269Z ##[debug]Value : 0
2017-04-13T02:28:25.2980269Z ##[debug]
2017-04-13T02:28:25.2980269Z ##[debug]Name  : EndIPAddress
2017-04-13T02:28:25.2980269Z ##[debug]Value : 255
2017-04-13T02:28:25.2990284Z ##[debug]
2017-04-13T02:28:25.2990284Z ##[debug]
2017-04-13T02:28:25.2990284Z ##[debug]
2017-04-13T02:28:25.2990284Z ##[debug]
2017-04-13T02:28:25.2990284Z ##[debug]Entering Add-AzureSqlDatabaseServerFirewallRule.
2017-04-13T02:28:25.2990284Z ##[debug] endpoint: '@{Url=https://management.azure.com/; Data=; Auth=}'
2017-04-13T02:28:25.2990284Z ##[debug] startIPAddress: '0'
2017-04-13T02:28:25.2990284Z ##[debug] endIPAddress: '255'
2017-04-13T02:28:25.2990284Z ##[debug] serverName: 'gtewksbootcampdbserver'
2017-04-13T02:28:25.2990284Z ##[debug] firewallRuleName: '15f1a856-cca4-4e4c-a020-4cd75dd771b5'
2017-04-13T02:28:25.2990284Z ##[debug]Creating firewall rule 15f1a856-cca4-4e4c-a020-4cd75dd771b5
2017-04-13T02:28:25.2990284Z ##[debug]Connection type used is ServicePrincipal
2017-04-13T02:28:25.2990284Z ##[debug]Connection type used is ServicePrincipal
2017-04-13T02:28:25.2990284Z ##[debug]Connection type used is ServicePrincipal
2017-04-13T02:28:25.2990284Z ##[debug]Fetching Access Token
2017-04-13T02:28:25.2990284Z ##[debug]Reading proxy from the AGENT_PROXYURL environment variable. Proxy url specified=
2017-04-13T02:28:25.3160289Z ##[debug]Reading proxy from IE. Proxy url specified=https://login.windows.net/********/oauth2/token
2017-04-13T02:28:25.3330273Z ##[debug]No proxy settings
2017-04-13T02:28:25.4650272Z ##[debug]POST https://login.windows.net/********/oauth2/token with -1-byte payload
2017-04-13T02:28:25.5870280Z ##[debug]received 1293-byte response of content type application/json; charset=utf-8
2017-04-13T02:28:25.5990289Z ##[debug][Azure Rest Call] Get Resource Groups
2017-04-13T02:28:25.6070292Z ##[debug]Fetching Resources from https://management.azure.com//subscriptions/98e9f13f-64ab-4cbf-af82-f4e4e0e44607/resources?api-version=2014-04-01
2017-04-13T02:28:25.6080289Z ##[debug]GET https://management.azure.com//subscriptions/98e9f13f-64ab-4cbf-af82-f4e4e0e44607/resources?api-version=2014-04-01 with 0-byte payload
2017-04-13T02:28:25.6820269Z ##[debug]received 6340-byte response of content type application/json; charset=utf-8
2017-04-13T02:28:25.6820269Z ##[debug]PUT https://management.azure.com///subscriptions/98e9f13f-64ab-4cbf-af82-f4e4e0e44607/resourceGroups/AzureBootcamp/providers/Microsoft.Sql/servers/gtewksbootcampdbserver/firewallRules/15f1a856-cca4-4e4c-a020-4cd75dd771b5/?api-version=2014-04-01 with -1-byte payload
2017-04-13T02:29:26.0917997Z ##[debug]Exception message - System.Net.WebException: The remote server returned an error: (504) Gateway Timeout.
2017-04-13T02:29:26.0937999Z ##[debug]   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
2017-04-13T02:29:26.1387997Z ##[debug]   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
2017-04-13T02:29:26.1387997Z ##[debug]Exception message extracted from response {"error":{"code":"GatewayTimeout","message":"The gateway did not receive a response from 'Microsoft.Sql' within the specified time period."}}
2017-04-13T02:29:26.1387997Z ##[debug]No Firewall Rule was added
2017-04-13T02:29:26.1447998Z ##[debug]Caught exception from task script.
2017-04-13T02:29:26.1667997Z ##[debug]Error record:
2017-04-13T02:29:26.3167996Z ##[debug]D:\a\_tasks\SqlAzureDacpacDeployment_ce85a08b-a538-4d2b-8589-1d37a9ab970f\1.1.9\DeploySqlAzure.ps1 :  Please verify request URL : https://management.azure.com///subscriptions/98e9f13f-64ab-4cbf-af82-f4e4e0e44607/resourceGroups/AzureBootcamp/providers/Microsoft.Sql/servers/gtewksbootcampdbserver/firewallRules/15f1a856-cca4-4e4c-a020-4cd75dd771b5/?api-version=2014-04-01
2017-04-13T02:29:26.3177997Z ##[debug]At line:1 char:1
2017-04-13T02:29:26.3177997Z ##[debug]+ . 'd:\a\_tasks\SqlAzureDacpacDeployment_ce85a08b-a538-4d2b-8589-1d37a ...
2017-04-13T02:29:26.3177997Z ##[debug]+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2017-04-13T02:29:26.3177997Z ##[debug]    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
2017-04-13T02:29:26.3177997Z ##[debug]    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,DeploySqlAzure.ps1
2017-04-13T02:29:26.3177997Z ##[debug] 
2017-04-13T02:29:26.3177997Z ##[debug]Script stack trace:
2017-04-13T02:29:26.3177997Z ##[debug]at <ScriptBlock>, D:\a\_tasks\SqlAzureDacpacDeployment_ce85a08b-a538-4d2b-8589-1d37a9ab970f\1.1.9\DeploySqlAzure.ps1: line 229
2017-04-13T02:29:26.3177997Z ##[debug]at <ScriptBlock>, <No file>: line 1
2017-04-13T02:29:26.3177997Z ##[debug]at <ScriptBlock>, <No file>: line 22
2017-04-13T02:29:26.3177997Z ##[debug]at <ScriptBlock>, <No file>: line 18
2017-04-13T02:29:26.3177997Z ##[debug]at <ScriptBlock>, <No file>: line 1
2017-04-13T02:29:26.3177997Z ##[debug]Exception:
2017-04-13T02:29:26.3177997Z ##[debug]Microsoft.PowerShell.Commands.WriteErrorException:  Please verify request URL : https://management.azure.com///subscriptions/98e9f13f-64ab-4cbf-af82-f4e4e0e44607/resourceGroups/AzureBootcamp/providers/Microsoft.Sql/servers/gtewksbootcampdbserver/firewallRules/15f1a856-cca4-4e4c-a020-4cd75dd771b5/?api-version=2014-04-01
2017-04-13T02:29:26.3237996Z ##[error] Please verify request URL : https://management.azure.com///subscriptions/98e9f13f-64ab-4cbf-af82-f4e4e0e44607/resourceGroups/AzureBootcamp/providers/Microsoft.Sql/servers/gtewksbootcampdbserver/firewallRules/15f1a856-cca4-4e4c-a020-4cd75dd771b5/?api-version=2014-04-01
2017-04-13T02:29:26.3237996Z ##[debug]Processed: ##vso[task.logissue type=error] Please verify request URL : https://management.azure.com///subscriptions/98e9f13f-64ab-4cbf-af82-f4e4e0e44607/resourceGroups/AzureBootcamp/providers/Microsoft.Sql/servers/gtewksbootcampdbserver/firewallRules/15f1a856-cca4-4e4c-a020-4cd75dd771b5/?api-version=2014-04-01
2017-04-13T02:29:26.3237996Z ##[debug]Processed: ##vso[task.complete result=Failed]
2017-04-13T02:29:26.3527996Z ##[section]Finishing: Execute Azure SQL : DacpacTask

**Comment by mvvsubbu** [comment]
Thanks for reporting the issue, from your task log I could see, you are passing password as empty string.
If you can provide the password for sqlazure server (you can mark it secure, so that it won't show up in logs), it should unblock you. Is this working for you earlier and started failing now?

2017-04-13T02:28:24.2670673Z ##[debug]INPUT_SQLPASSWORD (empty)
2017-04-13T02:28:25.0180283Z ##[debug]Reching SqlServer to check connection by running sqlcmd.exe -S gtewksbootcampdbserver.database.windows.net -U gtewksbury -P -Q "select getdate()"
2017-04-13T02:28:25.1460292Z ##[debug]Sqlcmd: '-P': Missing argument. Enter '-?' for help
Few follow up questions to help us understand issue better:

**Comment by mvvsubbu** [comment]
Can you respond to my question ?

**Comment by mvvsubbu** [comment]
I am assuming you are unblocked after providing password and going ahead closing the issue. Please do let me know if that is not the case.

**Comment by gtewksbury** [comment]
I'm sorry @mvvsubbu , I've been away.  Yes, this resolved my issue.  Thanks for your help!
