### ISSUE TITLE
Run tests tasks failing after Deploy Agent task

### ISSUE THREAD

**Issue by AlexARoche** [Microsoft/vsts-tasks#4167]
Hi,
During the build the Run tests tasks started to fail after we updated Deploy test Agent task on TFS2015 (on-premise) with the following error:

2017-04-27T15:21:33.5622981Z ##[warning]For troubleshooting, refer http://aka.ms/remotevstest.
55 
2017-04-27T15:21:33.5779232Z ##[error]System.InvalidOperationException: The "Deploy Test Agent" task should be added before running the "Run Functional Test" task.
56 
2017-04-27T15:21:33.5779232Z ##[error]   at Microsoft.TeamFoundation.DistributedTask.Task.DistributedTestAutomation.RunTests.GetEnvironmentUri(Uri& machineEnvUri, Uri& autMachineEnvUri, Environment& dtlEnvironment, Environment& autEnvironment)
57 
2017-04-27T15:21:33.5779232Z ##[error]   at Microsoft.TeamFoundation.DistributedTask.Task.DistributedTestAutomation.RunTests.Run()
58 
2017-04-27T15:21:33.5779232Z ##[error]   at Microsoft.TeamFoundation.DistributedTask.Task.DistributedTestAutomation.TaskRunner.Run(Dictionary`2 arguments, VssConnection connection, TaskType taskType)
59 
2017-04-27T15:21:33.5779232Z ##[error]   at Microsoft.TeamFoundation.DistributedTask.Task.DistributedTestAutomation.RundistributedTestsCmdLet.ProcessRecord()

Before the error we have the following versions running:
- Deploy Test Agent task: 1.0.25
- Run task: 1.0.28

Now:
- Deploy Test Agent task: 2.0.8
- Run task: 1.0.28

The test agent installed is 2015 version, it has been validated in the VM that we are using and the agent seems to be running properly (at least I'm able to see the service).
WinRM is configured properly (certificate + firewall rule with the port 5986). The user that we are using for the build is the same for the deploy agent task and for the run tests task, it has permissions on TFS as well.

Do you know what can it be?

**Comment by prawalagarwal** [comment]
Hi @AlexARoche,

This error shows up when the Run Tests Task and the Deploy Test Agent task machine names do not match up. Can you please ensure that the machine names are exactly same in both the tasks (Copy paste from deploy task to run task)? 
If this does not help can you send screen shots of your Deploy Task and Run Tasks? Thanks.

**Comment by AlexARoche** [comment]
Hi Prawalagarwal,
First of all, thanks for your answer. 
Yes, both tasks have the same value. We are using the same environment variable for both tasks.
Here, the screenshots for deploy and run tasks:

![image](https://cloud.githubusercontent.com/assets/28107621/25685403/6fcf3470-3067-11e7-8d05-904380b1b22e.png)

and

![image](https://cloud.githubusercontent.com/assets/28107621/25685425/9e50d3f8-3067-11e7-9f1c-8eb6fc8bc748.png)

Thanks for your support

**Comment by prawalagarwal** [comment]
Hi @AlexARoche, I missed that you are on TFS 2015 in the last comment. For TFS 2015, you should not patch the task from master. The current version (v2) which you are using is supported with TFS 2017 onwards. Thanks

**Comment by AlexARoche** [comment]
Thanks for your support Prawalagarwal!
We alredy rollback the tasks to the previous version and now it's working fine again.

Regards
