### ISSUE TITLE
VSTS release failed in Run sql script on azure steps

### ISSUE THREAD

**Issue by dixhap** [Microsoft/vsts-tasks#4289]
Error : Cannot bind argument to parameter 'Path' because it is null
##[error]System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'Path' because it is null.
2017-05-10T08:50:56.7307474Z    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
2017-05-10T08:50:56.7307474Z    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
2017-05-10T08:50:56.7307474Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2017-05-10T08:50:56.7307474Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2017-05-10T08:50:56.7517467Z ##[error]PowerShell script completed with 1 errors.

**Comment by bryanmacfarlane** [comment]
There is not enough info here.

Which task is failing?  Is that a custom powershell script or a task?

**Comment by chrisrpatterson** [comment]
Are you sure that is a task that is shipped from the repo or that we ship?

**Comment by dixhap** [comment]
am attached the screen shot so that you can get clear view of  step of release which is failed.

![issue2](https://cloud.githubusercontent.com/assets/17857098/26092786/80960c2a-3a30-11e7-97e4-ec5d273dd86c.jpg)

**Comment by bryanmacfarlane** [comment]
That's not a task we ship.  It looks like it comes from the market place.  

https://marketplace.visualstudio.com/items?itemName=andrewlackenby.sql-toolkit-azure

If I follow the link on that, it's here:

https://github.com/crimdon/SQLToolkitAzure
