### ISSUE TITLE
Unable to deploy Test Agent on Azure VM - WinRM issue

### ISSUE THREAD

**Issue by Konnor5092** [Microsoft/vsts-tasks#4293]
Hi there,

For some reason I am unable to deploy the Test Agent on a VM with the following error...

`2017-05-11T03:03:32.4966120Z ##[warning]Task 'VerifyTestAgentInstalled' for machine DockerVM:5986's Error : System.Management.Automation.Remoting.PSRemotingTransportException: Connecting to remote server DockerVM failed with the following error message : The WinRM client cannot process the request because the server name cannot be resolved. For more information, see the about_Remote_Troubleshooting Help topic`

Here is the full log from the failed task

`2017-05-11T02:56:53.4998520Z ##[section]Starting: Deploy TestAgent on DockerVM
2017-05-11T02:56:53.4998520Z ==============================================================================
2017-05-11T02:56:53.4998520Z Task         : Visual Studio Test Agent Deployment
2017-05-11T02:56:53.4998520Z Description  : Deploy and configure Test Agent to run tests on a set of machines
2017-05-11T02:56:53.4998520Z Version      : 1.0.42
2017-05-11T02:56:53.4998520Z Author       : Microsoft Corporation
2017-05-11T02:56:53.4998520Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=625976)
2017-05-11T02:56:53.5008520Z ==============================================================================
2017-05-11T02:56:53.5118513Z Preparing task execution handler.
2017-05-11T02:56:56.7768212Z Executing the powershell script: d:\a\_tasks\DeployVisualStudioTestAgent_52a38a6a-1517-41d7-96cc-73ee0c60d2b6\1.0.42\DeployTestAgent.ps1
2017-05-11T02:56:59.8286653Z DistributedTests: Starting to deploy and configure test agent on test machines.
2017-05-11T02:56:59.8366656Z DistributedTests: Inputs provided are:
2017-05-11T02:56:59.8366656Z DistributedTests: Username: matty
2017-05-11T02:56:59.8366656Z DistributedTests: Use HTTP Port: False
2017-05-11T02:56:59.8366656Z DistributedTests: Run as process: True
2017-05-11T02:56:59.8366656Z DistributedTests: Login Automatically: True
2017-05-11T02:56:59.8366656Z DistributedTests: Disable Screen saver: True
2017-05-11T02:56:59.8366656Z DistributedTests: Agent would be downloaded from https://go.microsoft.com/fwlink/?LinkId=615472
2017-05-11T02:56:59.8366656Z DistributedTests: Update test agent: True
2017-05-11T02:56:59.8366656Z DistributedTests: Run test agent as DataCollection only : False
2017-05-11T02:56:59.8366656Z DistributedTests: Path to script that installs test agent on remote machine: D:\a\_tasks\DeployVisualStudioTestAgent_52a38a6a-1517-41d7-96cc-73ee0c60d2b6\1.0.42\TestAgentInstall.ps1
2017-05-11T02:56:59.8366656Z DistributedTests: Path to script that configures test agent on remote machine: D:\a\_tasks\DeployVisualStudioTestAgent_52a38a6a-1517-41d7-96cc-73ee0c60d2b6\1.0.42\TestAgentConfiguration.ps1
2017-05-11T02:56:59.8376657Z DistributedTests: Path to script that downloads test agent on Azure remote machines : D:\a\_tasks\DeployVisualStudioTestAgent_52a38a6a-1517-41d7-96cc-73ee0c60d2b6\1.0.42\DownloadTestAgent.ps1
2017-05-11T02:56:59.8376657Z DistributedTests: Path to script that checks if test agent is installed on remote machine: D:\a\_tasks\DeployVisualStudioTestAgent_52a38a6a-1517-41d7-96cc-73ee0c60d2b6\1.0.42\CheckTestAgentInstallation.ps1
2017-05-11T02:56:59.8376657Z DistributedTests: Path to script that checks if test agent is already running on remote machine: D:\a\_tasks\DeployVisualStudioTestAgent_52a38a6a-1517-41d7-96cc-73ee0c60d2b6\1.0.42\VerifyTestMachinesAreInUse.ps1
2017-05-11T02:56:59.8376657Z DistributedTests: Path to script that helps to download and configure test agent : 
2017-05-11T02:56:59.9366651Z DistributedTests: Task 'PopulatingMachinesPresentState' on machine 'DockerVM:5986' is being run
2017-05-11T02:57:02.5782449Z DistributedTests: Task 'PopulatingMachinesPresentState' on machine 'DockerVM:5986' completed.
2017-05-11T02:57:02.5802449Z ##[warning]DistributedTests: Task 'PopulatingMachinesPresentState' for machine DockerVM:5986's Error : System.Management.Automation.Remoting.PSRemotingTransportException: Connecting to remote server DockerVM failed with the following error message : The WinRM client cannot process the request because the server name cannot be resolved. For more information, see the about_Remote_Troubleshooting Help topic.
2017-05-11T02:57:02.5802449Z    at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
2017-05-11T02:57:02.5802449Z    at System.Management.Automation.Runspaces.Internal.RunspacePoolInternal.EndOpen(IAsyncResult asyncResult)
2017-05-11T02:57:02.5802449Z    at System.Management.Automation.RemoteRunspace.Open()
2017-05-11T02:57:02.5802449Z    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.Deployment.PowershellExecutor.GetOpenedRunspace()
2017-05-11T02:57:02.5802449Z    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.Deployment.PowershellExecutor.EstablishRemoteSession()
2017-05-11T02:57:02.5802449Z    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.RetryExecutor.Execute(Action action)
2017-05-11T02:57:02.5802449Z    at System.Threading.Tasks.Task.Execute()
2017-05-11T02:57:02.5802449Z --- End of stack trace from previous location where exception was thrown ---
2017-05-11T02:57:02.5802449Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-05-11T02:57:02.5812545Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-05-11T02:57:02.5812545Z    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.Deployment.PowershellExecutor.<Initialize>d__29.MoveNext()
2017-05-11T02:57:02.5812545Z --- End of stack trace from previous location where exception was thrown ---
2017-05-11T02:57:02.5812545Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-05-11T02:57:02.5812545Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-05-11T02:57:02.5812545Z    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.Deployment.PowershellExecutor.<Initialize>d__23.MoveNext()
2017-05-11T02:57:02.5812545Z --- End of stack trace from previous location where exception was thrown ---
2017-05-11T02:57:02.5812545Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-05-11T02:57:02.5812545Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-05-11T02:57:02.5812545Z    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.Deployment.RemoteDeploymentHelper.<Initialize>d__0.MoveNext()
2017-05-11T02:57:02.5812545Z --- End of stack trace from previous location where exception was thrown ---
2017-05-11T02:57:02.5812545Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-05-11T02:57:02.5812545Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-05-11T02:57:02.5812545Z    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.Deployment.DeploymentClient.<RunAsync>d__24.MoveNext()
2017-05-11T02:57:02.5812545Z ##[warning]DistributedTests: Task 'PopulatingMachinesPresentState' for machine DockerVM:5986's Log : Permission denied while trying to connect to the target machine DockerVM on the port:5986 via power shell remoting. Please check the following link for instructions: https://go.microsoft.com/fwlink/?LinkID=390236System.Management.Automation.Remoting.PSRemotingTransportException: Connecting to remote server DockerVM failed with the following error message : The WinRM client cannot process the request because the server name cannot be resolved. For more information, see the about_Remote_Troubleshooting Help topic.
2017-05-11T02:57:02.5812545Z    at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
2017-05-11T02:57:02.5812545Z    at System.Management.Automation.Runspaces.Internal.RunspacePoolInternal.EndOpen(IAsyncResult asyncResult)
2017-05-11T02:57:02.5822451Z    at System.Management.Automation.RemoteRunspace.Open()
2017-05-11T02:57:02.5822451Z    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.Deployment.PowershellExecutor.GetOpenedRunspace()
2017-05-11T02:57:02.5822451Z    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.Deployment.PowershellExecutor.EstablishRemoteSession()
2017-05-11T02:57:02.5822451Z    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.RetryExecutor.Execute(Action action)
2017-05-11T02:57:02.5822451Z    at System.Threading.Tasks.Task.Execute()
2017-05-11T02:57:02.5822451Z --- End of stack trace from previous location where exception was thrown ---
2017-05-11T02:57:02.5822451Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-05-11T02:57:02.5822451Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-05-11T02:57:02.5822451Z    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.Deployment.PowershellExecutor.<Initialize>d__29.MoveNext()
2017-05-11T02:57:02.5822451Z --- End of stack trace from previous location where exception was thrown ---
2017-05-11T02:57:02.5822451Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-05-11T02:57:02.5822451Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-05-11T02:57:02.5822451Z    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.Deployment.PowershellExecutor.<Initialize>d__23.MoveNext()
2017-05-11T02:57:02.5822451Z --- End of stack trace from previous location where exception was thrown ---
2017-05-11T02:57:02.5822451Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-05-11T02:57:02.5822451Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-05-11T02:57:02.5822451Z    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.Deployment.RemoteDeploymentHelper.<Initialize>d__0.MoveNext()
2017-05-11T02:57:02.5822451Z --- End of stack trace from previous location where exception was thrown ---
2017-05-11T02:57:02.5822451Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-05-11T02:57:02.5822451Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-05-11T02:57:02.5822451Z    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.Deployment.DeploymentClient.<RunAsync>d__24.MoveNext()
2017-05-11T02:57:02.5832443Z ##[error]Error occured on 'DockerVM:5986'. Details : 'Connecting to remote server DockerVM failed with the following error message : The WinRM client cannot process the request because the server name cannot be resolved. For more information, see the about_Remote_Troubleshooting Help topic.'. For troubleshooting, refer https://aka.ms/remotevstest.
2017-05-11T02:57:02.5862447Z ##[error]System.Exception: Error occured on 'DockerVM:5986'. Details : 'Connecting to remote server DockerVM failed with the following error message : The WinRM client cannot process the request because the server name cannot be resolved. For more information, see the about_Remote_Troubleshooting Help topic.'. For troubleshooting, refer https://aka.ms/remotevstest.
2017-05-11T02:57:02.5902446Z DistributedTests: Downloading test agent from https://go.microsoft.com/fwlink/?LinkId=615472;https://go.microsoft.com/fwlink/?LinkID=623891;https://go.microsoft.com/fwlink/?LinkID=623892 to $env:SystemDrive\TestAgent\vstf_testagent.exe;$env:SystemDrive\TestAgent\cab1.cab;$env:SystemDrive\TestAgent\vstf_testExecCore.msi location on the test machines
2017-05-11T02:57:02.5922450Z ##[warning]For troubleshooting, refer https://aka.ms/remotevstest.
2017-05-11T02:57:02.5932445Z ##[error]System.InvalidOperationException: Deploy Test Agent task has failed on all machines. Check the logs for more details.
2017-05-11T02:57:02.5932445Z    at Microsoft.TeamFoundation.DistributedTask.Task.DistributedTestAutomation.DtlMachineDeploymentHelper.ThrowIfNumberOfTargetMachinesAreZero(String exceptionMessage)
2017-05-11T02:57:02.5932445Z    at Microsoft.TeamFoundation.DistributedTask.Task.DistributedTestAutomation.DtlMachineDeploymentHelper.DownloadTestAgentToTestMachines(String sourcePath, String destinationPath, String downloadTestAgentScriptLocation, Boolean fallBackRun)
2017-05-11T02:57:02.5932445Z    at Microsoft.TeamFoundation.DistributedTask.Task.DistributedTestAutomation.DeployTestAgent.TryDownloadTestAgentToTestMachinesDirectly(Boolean fallBackRun)
2017-05-11T02:57:02.5932445Z    at Microsoft.TeamFoundation.DistributedTask.Task.DistributedTestAutomation.DeployTestAgent.TryTestAgentCopyOrDownload(TestAgentToTestMachineDelegate[] testAgentDel)
2017-05-11T02:57:02.5932445Z    at Microsoft.TeamFoundation.DistributedTask.Task.DistributedTestAutomation.DeployTestAgent.CopyAgentToTestMachines()
2017-05-11T02:57:02.5932445Z    at Microsoft.TeamFoundation.DistributedTask.Task.DistributedTestAutomation.DeployTestAgent.Run()
2017-05-11T02:57:02.5932445Z    at Microsoft.TeamFoundation.DistributedTask.Task.DistributedTestAutomation.TaskRunner.Run(Dictionary`2 arguments, VssConnection connection, TaskType taskType)
2017-05-11T02:57:02.5932445Z    at Microsoft.TeamFoundation.DistributedTask.Task.DistributedTestAutomation.InvokeDeployTestAgentCmdlet.ProcessRecord()
2017-05-11T02:57:02.6112443Z ##[error]PowerShell script completed with 2 errors.
2017-05-11T02:57:02.6122449Z ##[section]Finishing: Deploy TestAgent on DockerVM
`
This is despite having a preceding 'Azure Resource Group Deployment' task which has the action set to 'Select resource group' and 'Enable prerequisites' set to 'Configure with WinRM'. After this task but preceding the Test Agent deploy task I also have an azure file copy where I have ticked 'Enable Copy Prerequisites'.  

If I run `winrm e winrm/config/listener` on the VM I get the following response

Listener
    Address = *
    Transport = HTTP
    Port = 5985
    Hostname
    Enabled = true
    URLPrefix = wsman
    CertificateThumbprint
    ListeningOn = 10.0.0.4, 127.0.0.1, 192.168.1
:19df:ca65:6b09%7, fe80::ec39:1c4c:d598:e14c%9

Listener
    Address = *
    Transport = HTTPS
    Port = 5986
    Hostname = 51.141.29.252
    Enabled = true
    URLPrefix = wsman
    CertificateThumbprint = 842CE2C543615F333AC2
    ListeningOn = 10.0.0.4, 127.0.0.1, 192.168.1
:19df:ca65:6b09%7, fe80::ec39:1c4c:d598:e14c%9

Does anyone know what could be going on here?

Other info
- I'm using VSTS with a hosted build agent
- I'm using Visual Studio 2017 to edit my solution
- I've tried both HTTP and HTTPS protocols in the Deploy Test Agent task
- I've tried both version 1 and 2 of the task 

Many thanks,

**Comment by nigurr** [comment]
@Konnor5092 You can't use Hosted Build agent for Deploy Test Agent/Run Functional test task. Will add this to documentation.
You need to use "Private build agents"

**Comment by dcolliervb23** [comment]
I'm having the same problem. Where did you document this?  I am using [this ](https://github.com/Microsoft/vsts-tasks/issues/4293)documentation and it has no mention of this limitation. Is this for real? This seems like a really really bad limitation. Running tests, including integration tests, are an important part of builds and if hosted builds cannot run that task, it seems to be that they are a waste of time or distraction to even offer as an option. Is there any timeline to fix this issue?  Thanks!

**Comment by bl4cky** [comment]
Sorry @nigurr but could it be, that you missunderstood the topic? 
It is correct that you cant run "Deploy Test Agent/Run Functional test task" on Hosted Agents. 
But here the topic is: Why isnt it possible to run "Deploy Test Agent/Run Functional test task" on Azure VMs which are in this context "Private Build Agents". 

So if i am right, please reopen that topic. 

Thanks in advance!
