### ISSUE TITLE
Failed to deploy App Service (ERROR_FILE_IN_USE)

### ISSUE THREAD

**Issue by davenewza** [Microsoft/vsts-tasks#4365]
Occasionally we get the following exception thrown from the Azure App Service Deploy task (version 2.*)

```
Failed to deploy App Service.
Error Code: ERROR_FILE_IN_USE
Error: C:\Program Files (x86)\IIS\Microsoft Web Deploy V3\msdeploy.exe failed with return code: 4294967295
System.Management.Automation.CmdletInvocationException: Could not find a part of the path 'C:\agent\_work\2\s\test\Postman\Collections\results'. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\agent\_work\2\s\test\Postman\Collections\results'.
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.FileSystemEnumerableIterator`1.CommonInit()
at System.IO.Directory.EnumerateFiles(String path, String searchPattern, SearchOption searchOption)
at Microsoft.TeamFoundation.DistributedTask.Task.Common.Core.FindFiles.<GetPathIterator>d__4.MoveNext()
at Microsoft.TeamFoundation.DistributedTask.Task.Common.Core.FindFiles.GetMatchingItems(List`1 includePatterns, List`1 excludePatterns, Boolean includeFiles, Boolean includeFolders)
at Microsoft.TeamFoundation.DistributedTask.Task.Common.Core.FindFiles.FindMatchingFiles(String rootFolder, String matchPattern, Boolean includeFiles, Boolean includeFolders)
at Microsoft.TeamFoundation.DistributedTask.Task.Common.PowerShell.FindFilesCmdlet.ProcessRecord()
at System.Management.Automation.CommandProcessor.ProcessRecord()
--- End of inner exception stack trace ---
at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
at Microsoft.TeamFoundation.DistributedTask.Handlers.PowerShellHandler.Execute(ITaskContext context, CancellationToken cancellationToken, Int32 timeoutInMinutes)
at Microsoft.TeamFoundation.DistributedTask.Worker.JobRunner.RunTask(ITaskContext context, TaskWrapper task, CancellationTokenSource tokenSource)
```

Configuration:

![image](https://cloud.githubusercontent.com/assets/6212830/26254535/336975ac-3cb7-11e7-8a0d-1f1268ab3b26.png)

**Comment by mvvsubbu** [comment]
This is an issue with asp.net apps on azure app service, to avoid this our/asp.net recommended approach to update App is 

Approach 1:
1.  Stop staging slot deployment
2.  Deploy to staging slot
3.  Start the staging deployment
4.  Swap the slot

You can achieve using App Service Manage and App Service Deployment tasks together. This is correct way to deploy and it ensures file in use doesn't occur.

Approach 2:
1. Use App Offline check box of App Service Deployment task. But with this approach as well, we have seen some times file in use occurs. So we recommend Approach 1 to deploy your Apps.

For more updates on this issue you can follow here(https://github.com/aspnet/Home/issues/694)

**Comment by mvvsubbu** [comment]
Any update?

**Comment by mvvsubbu** [comment]
@davenewza 

Can you update if you are able to get unblocked with the given suggestion?

**Comment by mvvsubbu** [comment]
Closing the issue as nothing is actionable, please feel free to reach us if you still need assistance

**Comment by davenewza** [comment]
Apologies for not getting back to you. This didn't occur again.

**Comment by rmarinho** [comment]
I still have this issue even wit the new flag to rename locked files.. 

I don't like the approach for the workarounds.

**Comment by vincentdass** [comment]
@rmarinho , Is App Offline flag enabled in Release definition?
Can you please add `-retryInterval:6000  -retryAttempts:10` in Additional arguments of Web Deploy option?
We have another [thread ](https://github.com/Microsoft/vsts-tasks/issues/1607)to monitor the same issue.

Is there any webjobs or Application Insights extensions running in your App Service?

**Comment by henkmollema** [comment]
@vincentdass it seems that the Application Insights snapshot collector extension causes the locked files lately:

```
2017-10-09T07:01:44.9131651Z ##[error]Failed to deploy web package to App Service.
2017-10-09T07:01:44.9131651Z ##[warning]Try to deploy app service again with Rename locked files option selected.
2017-10-09T07:01:44.9131651Z ##[error]Error Code: ERROR_FILE_IN_USE
More Information: Web Deploy cannot modify the file 'Microsoft.ApplicationInsights.SnapshotCollector.dll' on the destination because it is locked by an external process.  In order to allow the publish operation to succeed, you may need to either restart your application to release the lock, or use the AppOffline rule handler for .Net applications on your next publish attempt.  Learn more at: http://go.microsoft.com/fwlink/?LinkId=221672#ERROR_FILE_IN_USE.
Error count: 1.
```

**Comment by harishgatla** [comment]
Checking Take App Offline, Publish using WebDeploy and Rename locked files check boxes fixed  my issue.
However the deployment was successful for two concurrent releases. Will update you once my nightly scheduled builds get succeeded.
![image](https://user-images.githubusercontent.com/29980295/34154043-2764d7a8-e4da-11e7-9408-c038aaff75da.png)

**Comment by sweetest** [comment]
I am trying to deploy Function App and having similar problem. 

```
2018-08-31T00:34:27.6473817Z Error: C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe failed with return code: 4294967295
2018-08-31T00:34:27.6474620Z     at ChildProcess.<anonymous> (D:\a\_tasks\AzureRmWebAppDeployment_497d490f-eea7-4f2b-ab94-48d9c1acdcb1\3.4.6\node_modules\vsts-task-lib\toolrunner.js:568:30)
2018-08-31T00:34:27.6476083Z     at emitTwo (events.js:106:13)
2018-08-31T00:34:27.6476443Z     at ChildProcess.emit (events.js:191:7)
2018-08-31T00:34:27.6484249Z     at maybeClose (internal/child_process.js:886:16)
2018-08-31T00:34:27.6484635Z     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```
