### ISSUE TITLE
[DeployVisualStudioTestAgent] Problem with username having more than 8 characters

### ISSUE THREAD

**Issue by 50802353** [Microsoft/vsts-tasks#4415]
Hello,

I've tried to deploy the test agent with Machine's admin username: trinh.pham and got the error as below
```
2017-05-22T05:17:40.6870427Z RemoteDeployerSource Verbose: 1221675 : [RemoteDeployer][22:May:17:12:17:38:8037; 6772, 5](LGVN14143-W10:5985-9005d6f4-9e7f-441d-81be-38f36e1922be)Finished retrying 1 out of 3 times for exception: System.Management.Automation.CmdletProviderInvocationException: An object at the specified path C:\Users\TRINH~1.PHA does not exist. ---> System.Management.Automation.PSArgumentException: An object at the specified path C:\Users\TRINH~1.PHA does not exist.
2017-05-22T05:17:40.6870427Z    at Microsoft.PowerShell.Commands.FileSystemProvider.NormalizeThePath(String basepath, Stack`1 tokenizedPathStack)
2017-05-22T05:17:40.6870427Z    at Microsoft.PowerShell.Commands.FileSystemProvider.NormalizeRelativePathHelper(String path, String basePath)
2017-05-22T05:17:40.6870427Z    --- End of inner exception stack trace ---
2017-05-22T05:17:40.6880438Z    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
2017-05-22T05:17:40.6880438Z    at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
2017-05-22T05:17:40.6880438Z    at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
2017-05-22T05:17:40.6890444Z    at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2017-05-22T05:17:40.6890444Z    at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2017-05-22T05:17:40.6900446Z    at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
2017-05-22T05:17:40.6900446Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Deployment.PowershellExecutor.<>c__DisplayClass28_0.<Invoke>b__0()
2017-05-22T05:17:40.6900446Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Utilities.RetryExecutor.<>c__DisplayClass19_0`1.<Execute>b__0()
2017-05-22T05:17:40.6910458Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Utilities.RetryExecutor.Execute(Action action)
2017-05-22T05:17:40.6910458Z RemoteDeployerSource Error: 1221741 : [RemoteDeployer][22:May:17:12:17:38:8057; 6772, 5](LGVN14143-W10:5985-9005d6f4-9e7f-441d-81be-38f36e1922be)System.AggregateException: Failed to execute the powershell script. Consult the logs below for details of the error.
2017-05-22T05:17:40.6910458Z An object at the specified path C:\Users\TRINH~1.PHA does not exist. ---> System.Management.Automation.CmdletProviderInvocationException: An object at the specified path C:\Users\TRINH~1.PHA does not exist. ---> System.Management.Automation.PSArgumentException: An object at the specified path C:\Users\TRINH~1.PHA does not exist.
2017-05-22T05:17:40.6920460Z    at Microsoft.PowerShell.Commands.FileSystemProvider.NormalizeThePath(String basepath, Stack`1 tokenizedPathStack)
2017-05-22T05:17:40.6920460Z    at Microsoft.PowerShell.Commands.FileSystemProvider.NormalizeRelativePathHelper(String path, String basePath)
2017-05-22T05:17:40.6920460Z    --- End of inner exception stack trace ---
2017-05-22T05:17:40.6920460Z    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
2017-05-22T05:17:40.6920460Z    at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
2017-05-22T05:17:40.6930474Z    at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
2017-05-22T05:17:40.6930474Z    at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2017-05-22T05:17:40.6930474Z    at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2017-05-22T05:17:40.6940483Z    at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
2017-05-22T05:17:40.6940483Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Deployment.PowershellExecutor.<>c__DisplayClass28_0.<Invoke>b__0()
2017-05-22T05:17:40.6940483Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Utilities.RetryExecutor.<>c__DisplayClass19_0`1.<Execute>b__0()
2017-05-22T05:17:40.6940483Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Utilities.RetryExecutor.Execute(Action action)
2017-05-22T05:17:40.6940483Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Utilities.RetryExecutor.Execute[T](Func`1 action)
2017-05-22T05:17:40.6950488Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Deployment.PowershellExecutor.Invoke(String errorContextMessage, Boolean writeResultToLog, Boolean isCancellable, ActionPreference errorActionPreference)
2017-05-22T05:17:40.6950488Z    --- End of inner exception stack trace ---
2017-05-22T05:17:40.6950488Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Deployment.PowershellExecutor.Invoke(String errorContextMessage, Boolean writeResultToLog, Boolean isCancellable, ActionPreference errorActionPreference)
2017-05-22T05:17:40.7090581Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Deployment.ScriptExecutor.ExecuteScript(IPowerShell powerShell, String script, String arguments, Boolean isScriptDotSourced, Boolean useHttp)
2017-05-22T05:17:40.7100584Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Deployment.DeploymentService.RunPowerShellScripts(DeploymentMachineSpecification deploymentMachine, ScriptSpecification scriptSpecification, ScriptSpecification initializationScriptSpecification, String applicationPath, IPowerShell powerShellSession)
2017-05-22T05:17:40.7100584Z ---> (Inner Exception #0) System.Management.Automation.CmdletProviderInvocationException: An object at the specified path C:\Users\TRINH~1.PHA does not exist. ---> System.Management.Automation.PSArgumentException: An object at the specified path C:\Users\TRINH~1.PHA does not exist.
2017-05-22T05:17:40.7110589Z    at Microsoft.PowerShell.Commands.FileSystemProvider.NormalizeThePath(String basepath, Stack`1 tokenizedPathStack)
2017-05-22T05:17:40.7110589Z    at Microsoft.PowerShell.Commands.FileSystemProvider.NormalizeRelativePathHelper(String path, String basePath)
2017-05-22T05:17:40.7110589Z    --- End of inner exception stack trace ---
2017-05-22T05:17:40.7120607Z    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
2017-05-22T05:17:40.7120607Z    at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
2017-05-22T05:17:40.7130606Z    at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
2017-05-22T05:17:40.7130606Z    at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2017-05-22T05:17:40.7130606Z    at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2017-05-22T05:17:40.7140611Z    at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
2017-05-22T05:17:40.7140611Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Deployment.PowershellExecutor.<>c__DisplayClass28_0.<Invoke>b__0()
2017-05-22T05:17:40.7140611Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Utilities.RetryExecutor.<>c__DisplayClass19_0`1.<Execute>b__0()
2017-05-22T05:17:40.7150617Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Utilities.RetryExecutor.Execute(Action action)
2017-05-22T05:17:40.7150617Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Utilities.RetryExecutor.Execute[T](Func`1 action)
2017-05-22T05:17:40.7150617Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Deployment.PowershellExecutor.Invoke(String errorContextMessage, Boolean writeResultToLog, Boolean isCancellable, ActionPreference errorActionPreference)<---
```
Trying with a shorter username (less than 8 characters) worked as expected.
Please help review and fix it ASAP.

**Environments**
- Windows 10 x64
- TFS 2017 on-premises, update 1
- VSTS Build Agent: vsts-agent-win7-x64-2.116.0
- VSTS Task: \DeployVisualStudioTestAgent\1.0.42
- My username [trinh.pham] is administrator and is configured for running as build agent service and test agent

**Comment by RanjanarMS** [comment]
Hi,
The issue is not because of the length. It is becuase of "." in the user name? Will it be possible for to remove the "." in the user name? 
PS: I am even able to create a remote powershell session with username containing dot in it

**Comment by 50802353** [comment]
I don't think so.
Currently, the accounts I'm using are: [duy.dao] and [cuong.do].
Both of them have dot in the username but the task can work as expected.

**Comment by RanjanarMS** [comment]
Hi.. This seems to be a powershell issue.. Please refer to this thread where similar issue is discussed https://stackoverflow.com/questions/41572933/an-object-at-the-specified-path-c-users-user1-name-does-not-exist
