### ISSUE TITLE
NuGet Publisher - 405 Method Not Allowed

### ISSUE THREAD

**Issue by mateuszmcz** [Microsoft/vsts-tasks#4493]
Hi, I'm trying to configure VSTS build that will publish NuGet package to internal feed. Puckage is being created successfully but have issue with NuGet Publisher. When NuGet publisher is trying to publish package then I got error The remote server returned an error: 

`(405) Method Not Allowed.. ---> System.Net.WebException: The remote server returned an error: (405) Method Not Allowed. `

I've already checked permissions to feed and Project Collection Build Service is added as a contributor. I've also tried to play with NuGet versions but it didn't help. If I download NuGet + VSTS Credential Provider then I can publish package manually with success.

Please find logs below:

```
Starting: NuGet Publisher
******************************************************************************
==============================================================================
Task : NuGet Publisher
Description : Uploads nupkg files to a NuGet server
Version : 0.2.34
Author : Lawrence Gripper
Help : [More Information](https://go.microsoft.com/fwlink/?LinkID=627417)
==============================================================================
C:\Windows\system32\chcp.com 65001
Active code page: 65001
Detected NuGet version 3.3.0.212 / 3.3.0
SYSTEMVSSCONNECTION exists true
save nuget.config to temp config file
Preparing to set credentials in NuGet.config
d:\a\_tasks\NuGetPublisher_333b11bd-d341-40d9-afcf-b32d5ce6f25b\0.2.34\node_modules\nuget-task-common\NuGet\3.3.0\NuGet.exe sources Remove -NonInteractive -Name internalFeed -ConfigFile d:\a\1\Nuget\tempNuGet_34.config
Unable to find any package source(s) matching name: internalFeed.
Setting credentials in NuGet.config
d:\a\_tasks\NuGetPublisher_333b11bd-d341-40d9-afcf-b32d5ce6f25b\0.2.34\node_modules\nuget-task-common\NuGet\3.3.0\NuGet.exe sources Add -NonInteractive -Name internalFeed -Source https://myvstsname.pkgs.visualstudio.com/_packaging/my.project@Release/nuget/v3/index.json -ConfigFile d:\a\1\Nuget\tempNuGet_34.config -Username VssSessionToken -Password ********
Package Source with Name: internalFeed added successfully.
d:\a\_tasks\NuGetPublisher_333b11bd-d341-40d9-afcf-b32d5ce6f25b\0.2.34\node_modules\nuget-task-common\NuGet\3.3.0\NuGet.exe push -NonInteractive d:\a\1\s\my.project.1.0.0-ci-20170608-115715.nupkg -Source https://myvstsname.pkgs.visualstudio.com/_packaging/my.project@Release/nuget/v3/index.json -ApiKey VSTS -ConfigFile d:\a\1\Nuget\tempNuGet_34.config -Verbosity Detailed
Using credentials from config. UserName: VssSessionToken
Pushing my.project 1.0.0-ci-20170608-115715 to 'https://myvstsname.pkgs.visualstudio.com/_packaging/b5ae5df2-b73e-4af2-90b6-273f9bd62f56@c23daa56-66df-4340-8e68-9d4be0071ba8/nuget/v2/'...
PUT https://myvstsname.pkgs.visualstudio.com/_packaging/b5ae5df2-b73e-4af2-90b6-273f9bd62f56@c23daa56-66df-4340-8e68-9d4be0071ba8/nuget/v2/
System.InvalidOperationException: Failed to process request. 'Method Not Allowed'. 
The remote server returned an error: (405) Method Not Allowed.. ---> System.Net.WebException: The remote server returned an error: (405) Method Not Allowed.
at System.Net.HttpWebRequest.GetResponse()
at NuGet.RequestHelper.GetResponse()
at NuGet.HttpClient.GetResponse()
at NuGet.PackageServer.EnsureSuccessfulResponse(HttpClient client, Nullable`1 expectedStatusCode)
--- End of inner exception stack trace ---
at NuGet.PackageServer.EnsureSuccessfulResponse(HttpClient client, Nullable`1 expectedStatusCode)
at NuGet.PackageServer.PushPackageToServer(String apiKey, Func`1 packageStreamFactory, Int64 packageSize, Int32 timeout, Boolean disableBuffering)
at NuGet.PackageServer.PushPackage(String apiKey, IPackage package, Int64 packageSize, Int32 timeout, Boolean disableBuffering)
at NuGet.CommandLine.PushCommand.PushPackageCore(String source, String apiKey, PackageServer packageServer, String packageToPush, TimeSpan timeout)
at NuGet.CommandLine.PushCommand.PushPackage(String packagePath, String source, String apiKey, TimeSpan timeout)
at NuGet.CommandLine.PushCommand.<ExecuteCommandAsync>d__16.MoveNext()
Error: d:\a\_tasks\NuGetPublisher_333b11bd-d341-40d9-afcf-b32d5ce6f25b\0.2.34\node_modules\nuget-task-common\NuGet\3.3.0\NuGet.exe failed with return code: 1
Packages failed to publish
******************************************************************************
Finishing: NuGet Publisher
```

**Comment by satbai** [comment]
Based on the logs it looks like you're trying to push to a release view. We don't support pushing packages directly to views today. You have to push the package to a feed first and then promote to the view after the package is in the feed. So to sum up, replacing your feedId@viewId with a feedId should solve the problem.

**Comment by div78641** [comment]
@satbai I ran into this issue today and after implementing your suggestion, my build finished successfully and published to my feed.

Thank you.

**Comment by alexmullans** [comment]
Closing this since it appears to be resolved.
