### ISSUE TITLE
Service Fabric Deploy Task: ArgumentException from Get-ServiceFabricComposeApplicationStatusPaged

### ISSUE THREAD

**Issue by tomasherceg** [Microsoft/vsts-tasks#4569]
I have created a simple ASP.NET Core app, added Docker Support and created the CI/CD build definitions using the Continuous Delivery Tools extension. 
I haven't changed anything in the Release definition except of adding the "system.debug=true" variable (without which I would only got the "One or more errors occured.").

Here is the full log:

```
2017-06-17T09:44:33.4721265Z ##[debug]Evaluating condition for step: 'Deploy docker-compose application to a Service Fabric cluster'
2017-06-17T09:44:33.4721265Z ##[debug]Evaluating: succeeded()
2017-06-17T09:44:33.4721265Z ##[debug]Evaluating succeeded:
2017-06-17T09:44:33.4721265Z ##[debug]=> (Boolean) True
2017-06-17T09:44:33.4731268Z ##[debug]Expanded: True
2017-06-17T09:44:33.4731268Z ##[debug]Result: True
2017-06-17T09:44:33.4731268Z ##[section]Starting: Deploy docker-compose application to a Service Fabric cluster
2017-06-17T09:44:33.4881262Z ==============================================================================
2017-06-17T09:44:33.4891260Z Task         : Service Fabric Compose Deploy (Preview)
2017-06-17T09:44:33.4891260Z Description  : Deploy a docker-compose application to a Service Fabric cluster.
2017-06-17T09:44:33.4891260Z Version      : 0.0.38
2017-06-17T09:44:33.4891260Z Author       : Microsoft Corporation
2017-06-17T09:44:33.4891260Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=847030)
2017-06-17T09:44:33.4891260Z ==============================================================================
2017-06-17T09:44:35.9733371Z ##[debug]VstsTaskSdk 0.7.1 commit f990f8d8df6197b1cfcec01031ba014ad4905681
2017-06-17T09:44:36.3363402Z ##[debug]Entering D:\a\_tasks\ServiceFabricComposeDeploy_19c02b15-d377-40e0-9efa-3168506e0933\0.0.38\ServiceFabricComposeDeploy.ps1.
2017-06-17T09:44:36.3503365Z ##[debug]Loading resource strings from: D:\a\_tasks\ServiceFabricComposeDeploy_19c02b15-d377-40e0-9efa-3168506e0933\0.0.38\task.json
2017-06-17T09:44:36.4193366Z ##[debug]Loaded 15 strings.
2017-06-17T09:44:36.4723368Z ##[debug]SYSTEM_CULTURE: 'en-US'
2017-06-17T09:44:36.4743371Z ##[debug]Loading resource strings from: D:\a\_tasks\ServiceFabricComposeDeploy_19c02b15-d377-40e0-9efa-3168506e0933\0.0.38\Strings\resources.resjson\en-US\resources.resjson
2017-06-17T09:44:36.4883369Z ##[debug]Loaded 15 strings.
2017-06-17T09:44:37.4553362Z ##[debug]Loading module from path 'D:\a\_tasks\ServiceFabricComposeDeploy_19c02b15-d377-40e0-9efa-3168506e0933\0.0.38\ps_modules\ServiceFabricHelpers\ServiceFabricHelpers.psm1'.
2017-06-17T09:44:37.5253369Z ##[debug]Loading resource strings from: D:\a\_tasks\ServiceFabricComposeDeploy_19c02b15-d377-40e0-9efa-3168506e0933\0.0.38\ps_modules\ServiceFabricHelpers\module.json
2017-06-17T09:44:37.5253369Z ##[debug]Loaded 9 strings.
2017-06-17T09:44:37.5253369Z ##[debug]SYSTEM_CULTURE: 'en-US'
2017-06-17T09:44:37.5253369Z ##[debug]Loading resource strings from: D:\a\_tasks\ServiceFabricComposeDeploy_19c02b15-d377-40e0-9efa-3168506e0933\0.0.38\ps_modules\ServiceFabricHelpers\Strings\resources.resjson\en-US\resources.resjson
2017-06-17T09:44:37.5253369Z ##[debug]Loaded 9 strings.
2017-06-17T09:44:37.5253369Z ##[debug]Entering Find-VstsFiles.
2017-06-17T09:44:37.5263369Z ##[debug] LiteralDirectory: 'D:\a\_tasks\ServiceFabricComposeDeploy_19c02b15-d377-40e0-9efa-3168506e0933\0.0.38\ps_modules\ServiceFabricHelpers'
2017-06-17T09:44:37.5263369Z ##[debug] LegacyPattern: '*.ps1'
2017-06-17T09:44:37.5263369Z ##[debug]Entering Get-MatchingItems.
2017-06-17T09:44:37.5263369Z ##[debug] IncludePatterns: 'D:\a\_tasks\ServiceFabricComposeDeploy_19c02b15-d377-40e0-9efa-3168506e0933\0.0.38\ps_modules\ServiceFabricHelpers\*.ps1'
2017-06-17T09:44:37.5263369Z ##[debug] ExcludePatterns: ''
2017-06-17T09:44:37.5263369Z ##[debug] IncludeFiles: 'True'
2017-06-17T09:44:37.5289990Z ##[debug] IncludeDirectories: 'False'
2017-06-17T09:44:37.5289990Z ##[debug] Force: 'False'
2017-06-17T09:44:37.5293382Z ##[debug]Path: D:\a\_tasks\ServiceFabricComposeDeploy_19c02b15-d377-40e0-9efa-3168506e0933\0.0.38\ps_modules\ServiceFabricHelpers\Connect-ServiceFabricClusterFromServiceEndpoint.ps1
2017-06-17T09:44:37.5293382Z ##[debug]Leaving Get-MatchingItems.
2017-06-17T09:44:37.5293382Z ##[debug]Total found: 1
2017-06-17T09:44:37.5293382Z ##[debug]Leaving Find-VstsFiles.
2017-06-17T09:44:37.5293382Z ##[debug]Exporting function 'Connect-ServiceFabricClusterFromServiceEndpoint'.
2017-06-17T09:44:37.5303377Z ##[debug]Importing function 'Connect-ServiceFabricClusterFromServiceEndpoint'.
2017-06-17T09:44:37.5303377Z ##[debug]INPUT_SERVICECONNECTIONNAME: '189036dd-7ca4-46b3-96e6-fba01e7a405c'
2017-06-17T09:44:37.5303377Z ##[debug]ENDPOINT_URL_189036dd-7ca4-46b3-96e6-fba01e7a405c: 'tcp://altairisnemesisevents2.westeurope.cloudapp.azure.com:19000/'
2017-06-17T09:44:37.5303377Z ##[debug]ENDPOINT_AUTH_189036dd-7ca4-46b3-96e6-fba01e7a405c: '********'
2017-06-17T09:44:37.5313382Z ##[debug]ENDPOINT_DATA_189036dd-7ca4-46b3-96e6-fba01e7a405c: '{}'
2017-06-17T09:44:37.5313382Z ##[debug]INPUT_COMPOSEFILEPATH: 'd:\a\r1\a\**\docker-compose.yml'
2017-06-17T09:44:37.5340061Z Searching for path: d:\a\r1\a\**\docker-compose.yml
2017-06-17T09:44:37.5340061Z ##[debug]Entering Find-VstsFiles.
2017-06-17T09:44:37.5343361Z ##[debug] LegacyPattern: 'd:\a\r1\a\**\docker-compose.yml'
2017-06-17T09:44:37.5343361Z ##[debug]Entering Get-MatchingItems.
2017-06-17T09:44:37.5353371Z ##[debug] IncludePatterns: 'd:\a\r1\a\**\docker-compose.yml'
2017-06-17T09:44:37.5353371Z ##[debug] ExcludePatterns: ''
2017-06-17T09:44:37.5353371Z ##[debug] IncludeFiles: 'True'
2017-06-17T09:44:37.5353371Z ##[debug] IncludeDirectories: 'False'
2017-06-17T09:44:37.5353371Z ##[debug] Force: 'False'
2017-06-17T09:44:37.5353371Z ##[debug]Path: d:\a\r1\a\Drop\docker-compose\docker-compose.yml
2017-06-17T09:44:37.5363365Z ##[debug]Leaving Get-MatchingItems.
2017-06-17T09:44:37.5363365Z ##[debug]Total found: 1
2017-06-17T09:44:37.5363365Z ##[debug]Leaving Find-VstsFiles.
2017-06-17T09:44:37.5363365Z ##[debug]Asserting leaf path exists: 'd:\a\r1\a\Drop\docker-compose\docker-compose.yml'
2017-06-17T09:44:37.5363365Z Found path: d:\a\r1\a\Drop\docker-compose\docker-compose.yml
2017-06-17T09:44:37.5363365Z ##[debug]INPUT_APPLICATIONNAME: 'fabric:/nemesiseventsdemo'
2017-06-17T09:44:37.5373360Z ##[debug]INPUT_DEPLOYTIMEOUTSEC (empty)
2017-06-17T09:44:37.5373360Z ##[debug]INPUT_REMOVETIMEOUTSEC (empty)
2017-06-17T09:44:37.5373360Z ##[debug]INPUT_GETSTATUSTIMEOUTSEC (empty)
2017-06-17T09:44:37.5373360Z Checking compose file
2017-06-17T09:44:39.3951837Z ##[debug]Join-Path "C:\Program Files\Microsoft Service Fabric\bin\fabric\fabric.code" "ServiceFabricServiceModel.xsd"
2017-06-17T09:44:39.4061824Z ##[debug]C:\Program Files\Microsoft Service Fabric\bin\fabric\fabric.code\ServiceFabricServiceModel.xsd
2017-06-17T09:44:39.4081818Z ##[debug]Length: 94
2017-06-17T09:44:39.4091835Z ##[debug]
2017-06-17T09:44:39.4131840Z ##[debug]Test-Path "C:\Program Files\Microsoft Service Fabric\bin\fabric\fabric.code\ServiceFabricServiceModel.xsd"
2017-06-17T09:44:39.4181834Z ##[debug]True
2017-06-17T09:44:39.4201847Z ##[debug]
2017-06-17T09:44:39.7583929Z ##[warning]The Docker compose file contains the following 'keys' which are not supported. They will be ignored. 
'networks' 'build' 
2017-06-17T09:44:39.7593929Z ##[debug]Processed: ##vso[task.logissue type=warning]The Docker compose file contains the following 'keys' which are not supported. They will be ignored. %0D%0A'networks' 'build' 
2017-06-17T09:44:39.7653933Z ##[debug]Entering Connect-ServiceFabricClusterFromServiceEndpoint.
2017-06-17T09:44:39.7783923Z ##[debug] ClusterConnectionParameters: 'System.Collections.Hashtable'
2017-06-17T09:44:39.7843936Z ##[debug] ConnectedServiceEndpoint: '@{Url=tcp://altairisnemesisevents2.westeurope.cloudapp.azure.com:19000/; Data=; Auth=}'
2017-06-17T09:44:39.9883940Z Imported cluster client certificate with thumbprint '********'.
2017-06-17T09:44:40.0063930Z 
2017-06-17T09:44:40.0063930Z Thumbprint                                Subject                                                                      
2017-06-17T09:44:40.0073964Z ----------                                -------                                                                      
2017-06-17T09:44:40.0073964Z ********  CN=www.altairisnemesisevents.westeurope.cloudapp.azure.com                   
2017-06-17T09:44:40.6888568Z Successfully connected to cluster.
2017-06-17T09:44:40.6948569Z ##[debug]Leaving Connect-ServiceFabricClusterFromServiceEndpoint.
2017-06-17T09:44:40.6988560Z ##[debug]INPUT_REGISTRYCREDENTIALS: 'AzureResourceManagerEndpoint'
2017-06-17T09:44:40.7038568Z ##[debug]INPUT_AZURESUBSCRIPTIONENDPOINT: '55aea2e5-660f-4f6b-a173-cb2136046e95'
2017-06-17T09:44:40.7078555Z ##[debug]ENDPOINT_URL_55aea2e5-660f-4f6b-a173-cb2136046e95: 'https://management.azure.com/'
2017-06-17T09:44:40.7108565Z ##[debug]ENDPOINT_AUTH_55aea2e5-660f-4f6b-a173-cb2136046e95: '********'
2017-06-17T09:44:40.7148563Z ##[debug]ENDPOINT_DATA_55aea2e5-660f-4f6b-a173-cb2136046e95: '{"subscriptionId":"789d076c-9b40-444c-aa42-fc911d827b0f","subscriptionName":"Subscription 1","creationMode":"Automatic","environment":"AzureCloud","azureSpnRoleAssignmentId":"f4ef3db7-7ef8-4b5e-8a51-fde09a0a281b","appObjectId":"c0919c78-9624-43ab-9b3c-31ce8c34a8cf","spnObjectId":"ec76ce60-d8e4-4e5e-a843-ec10853a9dff","environmentUrl":"https://management.azure.com/","galleryUrl":"https://gallery.azure.com/","serviceManagementUrl":"https://management.core.windows.net/","resourceManagerUrl":"https://management.azure.com/","activeDirectoryAuthority":"https://login.microsoftonline.com/","environmentAuthorityUrl":"https://login.windows.net/","graphUrl":"https://graph.windows.net/","managementPortalUrl":"https://manage.windowsazure.com/","armManagementPortalUrl":"https://portal.azure.com/","activeDirectoryServiceEndpointResourceId":"https://management.core.windows.net/","sqlDatabaseDnsSuffix":".database.windows.net","AzureKeyVaultDnsSuffix":"vault.azure.net","AzureKeyVaultServiceEndpointResourceId":"https://vault.azure.net"}'
2017-06-17T09:44:40.8678611Z Encrypting the password with the Server Certificate.
2017-06-17T09:44:40.9518651Z ##[debug]System.AggregateException: One or more errors occurred. ---> System.ArgumentException: Value does not fall within the expected range.
2017-06-17T09:44:40.9528683Z ##[debug]   at System.Fabric.Interop.NativeClient.IInternalFabricApplicationManagementClient.EndGetComposeApplicationStatusList(IFabricAsyncOperationContext context)
2017-06-17T09:44:40.9548671Z ##[debug]   at System.Fabric.FabricClient.QueryClient.GetComposeApplicationStatusListAsyncEndWrapper(IFabricAsyncOperationContext context)
2017-06-17T09:44:40.9558688Z ##[debug]   at System.Fabric.Interop.AsyncCallOutAdapter2`1.Finish(IFabricAsyncOperationContext context, Boolean expectedCompletedSynchronously)
2017-06-17T09:44:40.9568656Z ##[debug]   --- End of inner exception stack trace ---
2017-06-17T09:44:40.9588644Z ##[debug]   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
2017-06-17T09:44:40.9598678Z ##[debug]   at Microsoft.ServiceFabric.Preview.Client.Extensions.<>c__DisplayClass5_0.<GetComposeApplicationStatusPagedListAsync>b__0()
2017-06-17T09:44:40.9618702Z ##[debug]   at System.Threading.Tasks.Task`1.InnerInvoke()
2017-06-17T09:44:40.9628649Z ##[debug]   at System.Threading.Tasks.Task.Execute()
2017-06-17T09:44:40.9648663Z ##[debug]---> (Inner Exception #0) System.ArgumentException: Value does not fall within the expected range.
2017-06-17T09:44:40.9658652Z ##[debug]   at System.Fabric.Interop.NativeClient.IInternalFabricApplicationManagementClient.EndGetComposeApplicationStatusList(IFabricAsyncOperationContext context)
2017-06-17T09:44:40.9678640Z ##[debug]   at System.Fabric.FabricClient.QueryClient.GetComposeApplicationStatusListAsyncEndWrapper(IFabricAsyncOperationContext context)
2017-06-17T09:44:40.9688650Z ##[debug]   at System.Fabric.Interop.AsyncCallOutAdapter2`1.Finish(IFabricAsyncOperationContext context, Boolean expectedCompletedSynchronously)<---
2017-06-17T09:44:40.9708643Z ##[debug]
2017-06-17T09:44:40.9948309Z ##[debug]Leaving D:\a\_tasks\ServiceFabricComposeDeploy_19c02b15-d377-40e0-9efa-3168506e0933\0.0.38\ServiceFabricComposeDeploy.ps1.
2017-06-17T09:44:41.0237144Z ##[debug]Caught exception from task script.
2017-06-17T09:44:41.0277118Z ##[debug]Error record:
2017-06-17T09:44:41.1127096Z ##[debug]Get-ServiceFabricComposeApplicationStatusPaged : One or more errors occurred.
2017-06-17T09:44:41.1511576Z ##[debug]At D:\a\_tasks\ServiceFabricComposeDeploy_19c02b15-d377-40e0-9efa-3168506e0933\0.0.38\ServiceFabricComposeDeploy.ps1:109 char:28
2017-06-17T09:44:41.1617094Z ##[debug]+ ... plication = Get-ServiceFabricComposeApplicationStatusPaged @getStatus ...
2017-06-17T09:44:41.1617094Z ##[debug]+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2017-06-17T09:44:41.1617094Z ##[debug]    + CategoryInfo          : NotSpecified: (Microsoft.Servi...usterConnection:ClusterConnection) [Get-ServiceFabr...t    ionStatusPaged], AggregateException
2017-06-17T09:44:41.1617094Z ##[debug]    + FullyQualifiedErrorId : GetComposeApplicationStatusErrorId,Microsoft.ServiceFabric.Powershell.ComposeApplication    StatusPaged
2017-06-17T09:44:41.1678062Z ##[debug] 
2017-06-17T09:44:41.1753692Z ##[debug]Script stack trace:
2017-06-17T09:44:41.1810742Z ##[debug]at <ScriptBlock>, D:\a\_tasks\ServiceFabricComposeDeploy_19c02b15-d377-40e0-9efa-3168506e0933\0.0.38\ServiceFabricComposeDeploy.ps1: line 109
2017-06-17T09:44:41.1830815Z ##[debug]at <ScriptBlock>, <No file>: line 1
2017-06-17T09:44:41.1840819Z ##[debug]at <ScriptBlock>, <No file>: line 22
2017-06-17T09:44:41.1860826Z ##[debug]at <ScriptBlock>, <No file>: line 18
2017-06-17T09:44:41.1870880Z ##[debug]at <ScriptBlock>, <No file>: line 1
2017-06-17T09:44:41.1900881Z ##[debug]Exception:
2017-06-17T09:44:41.1970808Z ##[debug]System.AggregateException: One or more errors occurred. ---> System.ArgumentException: Value does not fall within the expected range.
2017-06-17T09:44:41.1990811Z ##[debug]   at System.Fabric.Interop.NativeClient.IInternalFabricApplicationManagementClient.EndGetComposeApplicationStatusList(IFabricAsyncOperationContext context)
2017-06-17T09:44:41.2000814Z ##[debug]   at System.Fabric.FabricClient.QueryClient.GetComposeApplicationStatusListAsyncEndWrapper(IFabricAsyncOperationContext context)
2017-06-17T09:44:41.2020811Z ##[debug]   at System.Fabric.Interop.AsyncCallOutAdapter2`1.Finish(IFabricAsyncOperationContext context, Boolean expectedCompletedSynchronously)
2017-06-17T09:44:41.2030817Z ##[debug]   --- End of inner exception stack trace ---
2017-06-17T09:44:41.2050813Z ##[debug]   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
2017-06-17T09:44:41.2060817Z ##[debug]   at Microsoft.ServiceFabric.Preview.Client.Extensions.<>c__DisplayClass5_0.<GetComposeApplicationStatusPagedListAsync>b__0()
2017-06-17T09:44:41.2082991Z ##[debug]   at System.Threading.Tasks.Task`1.InnerInvoke()
2017-06-17T09:44:41.2090815Z ##[debug]   at System.Threading.Tasks.Task.Execute()
2017-06-17T09:44:41.2110795Z ##[debug]---> (Inner Exception #0) System.ArgumentException: Value does not fall within the expected range.
2017-06-17T09:44:41.2120818Z ##[debug]   at System.Fabric.Interop.NativeClient.IInternalFabricApplicationManagementClient.EndGetComposeApplicationStatusList(IFabricAsyncOperationContext context)
2017-06-17T09:44:41.2140844Z ##[debug]   at System.Fabric.FabricClient.QueryClient.GetComposeApplicationStatusListAsyncEndWrapper(IFabricAsyncOperationContext context)
2017-06-17T09:44:41.2150825Z ##[debug]   at System.Fabric.Interop.AsyncCallOutAdapter2`1.Finish(IFabricAsyncOperationContext context, Boolean expectedCompletedSynchronously)<---
2017-06-17T09:44:41.2170809Z ##[debug]
2017-06-17T09:44:41.2260818Z ##[error]One or more errors occurred.
2017-06-17T09:44:41.2260818Z ##[debug]Processed: ##vso[task.logissue type=error]One or more errors occurred.
2017-06-17T09:44:41.2300815Z ##[debug]Processed: ##vso[task.complete result=Failed]
2017-06-17T09:44:41.2730825Z ##[section]Finishing: Deploy docker-compose application to a Service Fabric cluster
```

I have looked in the PowerShell script and the parameter passed to the Get-ServiceFabricComposeApplicationStatusPaged contains only the ApplicationName entry. 

The Service Fabric cluster in Azure is new and does not contain any applications yet.

**Comment by FelschR** [comment]
I also used the Continuous Delivery Tools extension. The build doesn't even run successfully for me.

I only got it working by replacing the NuGet Restore and Visual Studio Build tasks with a Docker Compose task that runs the docker-compose.ci.build.yml. I also had to switch to a Linux host agent to get this working.

Building and creating released in VSTS works now but after it was deployed I get some errors in my Service Fabric:
```
Error event: SourceId='System.Hosting', Property='Download:1.0:1.0'.
There was an error during download.Failed to download container image 
```

This is on my Azure Service Fabric running the Linux preview.
When I try to release it on a Windows Service Fabric (with Containers) cluster I already get errors in the VSTS release:
```
2017-06-22T12:01:57.2571095Z Successfully connected to cluster.
2017-06-22T12:01:57.4971529Z Encrypting the password with the Server Certificate.
2017-06-22T12:01:57.8894982Z ##[error]One or more errors occurred.
2017-06-22T12:01:57.9654966Z ##[section]Finishing: Deploy docker-compose application to a Service Fabric cluster
```

**Comment by bishal-pdMSFT** [comment]
@tomasherceg are you using hosted agent pool for release?

**Comment by tomasherceg** [comment]
Yes.

**Comment by bishal-pdMSFT** [comment]
Sorry I was not precise enough. Are you using hosted pool or hostedvs2017 pool? Also, I am assuming your cluster has preview version of service fabric which supports compose applications.

**Comment by tomasherceg** [comment]
I have tried both actually, and got the same error message. 
I have created the Azure Service Fabric in the portal the same day I have hit into this issue.

**Comment by bishal-pdMSFT** [comment]
When creating cluster in azure portal, did you choose preview version for cluster fabric?
![image](https://user-images.githubusercontent.com/7830141/27510289-0e296a3c-592b-11e7-8ffb-38d49069921a.png)

**Comment by tomasherceg** [comment]
Oh, that's the issue. I have picked "Automatic", so I guess it was not the preview version.

**Comment by bishal-pdMSFT** [comment]
yes, you need to choose last one in the list

**Comment by tomasherceg** [comment]
OK, many thanks for the help.

I think that the VSTS task should provide some clear error message about this (maybe a link to the documentation of the task which would also specify the required version of Service Fabric).
