### ISSUE TITLE
ArchiveFiles: "Unexpected token ILLEGAL"

### ISSUE THREAD

**Issue by JohannesDrexler** [Microsoft/vsts-tasks#4579]
We are suddenly facing problems with the task "Archive Files" version "1.118.0".
The task worked in "1.117.0" and its configuration was not changed.
The task is configured to create a zip-archive from a directory inside the solution, variables are used in the path of the file to create), Error output:
`2017-06-19T06:25:12.4104811Z                                                               
2017-06-19T06:25:12.4104811Z 
2017-06-19T06:25:12.4104811Z SyntaxError: Unexpected token ILLEGAL
2017-06-19T06:25:12.4104811Z     at exports.runInThisContext (vm.js:53:16)
2017-06-19T06:25:12.4104811Z     at Module._compile (module.js:387:25)
2017-06-19T06:25:12.4104811Z     at Object.Module._extensions..js (module.js:422:10)
2017-06-19T06:25:12.4104811Z     at Module.load (module.js:357:32)
2017-06-19T06:25:12.4104811Z     at Function.Module._load (module.js:314:12)
2017-06-19T06:25:12.4104811Z     at Module.require (module.js:367:17)
2017-06-19T06:25:12.4104811Z     at require (internal/module.js:16:19)
2017-06-19T06:25:12.4104811Z     at Object.<anonymous> ([AGENTDIRECTORY]\_work\_tasks\ArchiveFiles_d8b84976-e99a-4b86-b885-4849694435b0\1.118.0\node_modules\shelljs\src\ls.js:4:11)
2017-06-19T06:25:12.4104811Z     at Module._compile (module.js:413:34)
2017-06-19T06:25:12.4104811Z     at Object.Module._extensions..js (module.js:422:10)
2017-06-19T06:25:13.1993941Z ##[error]Exit code 1 returned from process: file name '[AGENTDIRECTORY]\externals\node\bin\node.exe', arguments '"[AGENTDIRECTORY]\_work\_tasks\ArchiveFiles_d8b84976-e99a-4b86-b885-4849694435b0\1.118.0\archivefiles.js"'.`

**Comment by DavidStaheli** [comment]
Hi @JohannesDrexler, apologies for the trouble.  We want to help troubleshoot this ASAP.  Can you please go the **Variables** tab of your build definition and set a variable named **System.Debug** to **true**?  Then after reproducing the failed build, can you please email to me the full logs (dastahel at microsoft dot com)?

**Comment by JohannesDrexler** [comment]
When i change "System.Debug" to "true" the task is working again.

**Comment by DavidStaheli** [comment]
Wild!  That variable shouldn't affect execution.  Does it stop working again when you change it back to false?  Thanks.

**Comment by JohannesDrexler** [comment]
I Had to disable the unit-tests from the solution because they failed when changing the variable. When i changed System.Debug back to false but let the unit-tests disabled the build works again.
Now i'm investigating the unit-tests since they seem to cause the problem

**Comment by JohannesDrexler** [comment]
This issue can be closed.

**Comment by DavidStaheli** [comment]
@JohannesDrexler I'm glad the problem is identified.  Thank again for the report.  It was definitely worth investigating.
