### ISSUE TITLE
Build is partially sucessfull. It fails at run test step

### ISSUE THREAD

**Issue by vinayapc** [Microsoft/vsts-tasks#4707]
My run tests is failing with the below error

2017-07-03T07:47:21.5815431Z RemoteDeployerSource Verbose: 8 : [RemoteDeployer][03:Jul:17:7:47:18:6761; 1188, 6](10.228.48.226:5985-8f33e0fc-0a1d-405c-a348-5d1c68dc9d0c)Completed specificed action. Result: Passed
2017-07-03T07:47:21.5835433Z ##[warning]For troubleshooting, refer https://aka.ms/remotevstest.
2017-07-03T07:47:21.5875433Z ##[error]System.IO.IOException: The user name or password is incorrect.
2017-07-03T07:47:21.5875433Z ##[error]   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
2017-07-03T07:47:21.5885436Z ##[error]   at System.IO.File.GetAttributes(String path)
2017-07-03T07:47:21.5885436Z ##[error]   at Microsoft.TeamFoundation.DistributedTask.Task.DistributedTestAutomation.RunTests.QueueAndWaitForRunToComplete()
2017-07-03T07:47:21.5895429Z ##[error]   at Microsoft.TeamFoundation.DistributedTask.Task.DistributedTestAutomation.RunTests.Run()
2017-07-03T07:47:21.5895429Z ##[error]   at Microsoft.TeamFoundation.DistributedTask.Task.DistributedTestAutomation.TaskRunner.Run(Dictionary`2 arguments, VssConnection connection, TaskType taskType)
2017-07-03T07:47:21.5895429Z ##[error]   at Microsoft.TeamFoundation.DistributedTask.Task.DistributedTestAutomation.RundistributedTestsCmdLet.ProcessRecord()
2017-07-03T07:47:21.5905427Z DistributedTests: ##vso[task.logissue type=error;TaskName=DTA;code=The user name or password is incorrect.
2017-07-03T07:47:21.5905427Z ]
Not much help availableonline related to this issue.

I am using onprem TFS installed in the VM on Azure and test VMs are created using the azure scaleset. They used to work few weeks back all of a sudden they stopped working

**Comment by dpksinghal** [comment]
Is the RunSettings file locally available or is it a network path? Can you please check if the run settings file is accessible by the build/release agent user?

**Comment by vinayapc** [comment]
Yes that was the issue. But the log file was not at all clear in providing the information required for debugging. So if you could add a feature where in log says which user it was trying to login and to which server or service would have helped a lot. In general exception logging in the TFS tasks is not that useful especially in the failure scenarios.

**Comment by dpksinghal** [comment]
Sure. I'll file it as a feedback item.
