### ISSUE TITLE
Timeout during QuickPerfTest

### ISSUE THREAD

**Issue by danielepo** [Microsoft/vsts-tasks#4723]
I started tp have troubles this afternoon with the QuickPerfTest task. the issue occurs only while runing the task during build/release
If I run cloud pref tests manually in vsts they run just fine, so it shouldn't be some limitations on the build/cloud test quotas,,
 
the log during the tast execution is 

`2017-07-05T15:04:53.9459038Z ##[section]Starting: Quick Web Performance Test ReadMessages
2017-07-05T15:04:53.9589042Z ==============================================================================
2017-07-05T15:04:53.9589042Z Task         : Cloud-based Web Performance Test
2017-07-05T15:04:53.9589042Z Description  : Runs a quick web performance test in the cloud with Visual Studio Team Services
2017-07-05T15:04:53.9589042Z Version      : 1.0.22
2017-07-05T15:04:53.9589042Z Author       : Microsoft Corporation
2017-07-05T15:04:53.9589042Z Help         : Triggers a cloud-based load test using Visual Studio Team Services. [Learn more](https://go.microsoft.com/fwlink/?linkid=613203)
2017-07-05T15:04:53.9589042Z ==============================================================================
2017-07-05T15:04:53.9869026Z Preparing task execution handler.
2017-07-05T15:04:59.4638417Z Executing the powershell script: d:\a\_tasks\QuickPerfTest_9648625c-1523-4eb5-b015-dfe7c685840c\1.0.22\Invoke-QuickPerfTest.ps1
2017-07-05T15:04:59.7717986Z Starting Quick Perf Test Script
2017-07-05T15:04:59.9457953Z Test name = ReadMessages.loadtest
2017-07-05T15:04:59.9457953Z Run duration = 60
2017-07-05T15:04:59.9457953Z Website Url = http://xchangeconf.azurewebsites.net
2017-07-05T15:04:59.9457953Z Virtual user load = 25
2017-07-05T15:04:59.9467740Z Load location = West Europe
2017-07-05T15:04:59.9467740Z Load generator machine type = 0
2017-07-05T15:04:59.9487951Z Run source identifier = build//229
2017-07-05T15:04:59.9717859Z Initializing threshold rule for avg. response time with value(ms) : 0 
2017-07-05T15:05:00.0117732Z VSO Account URL is : https://dnlpozzobon.visualstudio.com/
2017-07-05T15:05:00.0817737Z Getting Clt Endpoint:
2017-07-05T15:05:00.0817737Z 
2017-07-05T15:05:00.0817737Z 
2017-07-05T15:05:00.0837744Z Fetching the Clt endpoint for https://dnlpozzobon.visualstudio.com
2017-07-05T15:05:00.0837744Z 
2017-07-05T15:05:00.0837744Z 
2017-07-05T15:05:00.0847744Z Fetching the SPS endpoint for https://dnlpozzobon.visualstudio.com
2017-07-05T15:05:00.0847744Z 
2017-07-05T15:05:00.0847744Z 
2017-07-05T15:05:00.4603824Z Fetching the CLT endpoint for https://dnlpozzobon.visualstudio.com
2017-07-05T15:05:00.4603824Z 
2017-07-05T15:05:00.4603824Z 
2017-07-05T15:05:00.7747959Z VSO account Url = https://dnlpozzobon.visualstudio.com
2017-07-05T15:05:00.7767944Z CLT account Url = https://dnlpozzobon.vsclt.visualstudio.com/
2017-07-05T15:06:01.5952638Z ##[error]System.Net.WebException: The operation has timed out
2017-07-05T15:06:01.5952638Z    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
2017-07-05T15:06:01.5952638Z    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
2017-07-05T15:06:01.9077950Z ##[error]System.Net.WebException: The remote server returned an error: (405) Method Not Allowed.
2017-07-05T15:06:01.9077950Z    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
2017-07-05T15:06:01.9077950Z    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
2017-07-05T15:06:02.1274661Z Load test 'System.Object[]' is in state 'System.Object[]|System.Object[]'.
2017-07-05T15:06:17.3277431Z ##[error]System.Net.WebException: The remote server returned an error: (404) Not Found.
2017-07-05T15:06:17.3277431Z    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
2017-07-05T15:06:17.3277431Z    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
2017-07-05T15:06:17.3297419Z Load test '' is in state '|'.
2017-07-05T15:06:17.4845762Z ##[error]System.Net.WebException: The remote server returned an error: (404) Not Found.
2017-07-05T15:06:17.4845762Z    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
2017-07-05T15:06:17.4845762Z    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
2017-07-05T15:06:17.4845762Z ------------------------------------
2017-07-05T15:07:17.4870290Z ##[error]System.Net.WebException: The operation has timed out.
2017-07-05T15:07:17.4870290Z    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
2017-07-05T15:07:17.4870290Z    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
2017-07-05T15:07:17.4940286Z ------------------------------------
2017-07-05T15:07:17.6819543Z ##[error]System.Net.WebException: The remote server returned an error: (404) Not Found.
2017-07-05T15:07:17.6829534Z    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
2017-07-05T15:07:17.6829534Z    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
2017-07-05T15:07:17.6919537Z Run-id for this load test is System.Object[] and its name is 'System.Object[]'.
2017-07-05T15:07:17.6919537Z To view run details navigate to 
2017-07-05T15:07:17.6919537Z To view detailed results navigate to Load Test | Load Test Manager in Visual Studio IDE, and open this run.
2017-07-05T15:07:17.7303666Z ##[error]System.IO.FileNotFoundException: Unable to find the specified file.
2017-07-05T15:07:17.7303666Z    at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
2017-07-05T15:07:17.7333638Z Quick Perf Test Script execution completed
2017-07-05T15:07:17.7563637Z ##[error]PowerShell script completed with 7 errors.
2017-07-05T15:07:17.7583626Z ##[section]Finishing: Quick Web Performance Test ReadMessages
`

**Comment by dpksinghal** [comment]
I am checking on this but so far I don't see any obvious reason for this failure.

Some questions:
1. Are you seeing it consistently?
2. Did you also observe such failures earlier than yesterday?
3. Does any of the load test run (queued through the build) show up in the load test runs when you open the VSTS?

**Comment by danielepo** [comment]
1. Yes, I also tryed creating a new release definition to run only the load tests but it still times-out
2. No it began today. 
3. That's actually the strangest part, after the QuickPerfTest  task starts I can see the results of the successful run in the "load test" tab even if the task exists with failure 

I tried also creating another vsts account and the same configuration of the task runs without issues

**Comment by dpksinghal** [comment]
Are you having your own build agent? If it is happening consistently can you please get fiddler traces from the machine? Also if it is a private agent would it be possible for you to use the VSTS portal from there and check if there is any perceived slowness?

**Comment by dpksinghal** [comment]
Hi

Are you still seeing the issue? If not, can we close this thread?

Regards,
Deepak.

**Comment by danielepo** [comment]
No, I'm not having any more the issue, apparently it was related to the quotas because now it works just fine. thanks for your help
