### ISSUE TITLE
Maven task fails with goal deploy

### ISSUE THREAD

**Issue by tarunaroraonline** [Microsoft/vsts-tasks#4813]
The maven task fails when the goal is set to deploy, the task passes if the goal is set to package. The failure is as follows... 

What could be causing this failure? 

``` cmd
[WARNING] Could not transfer metadata centrica-vault:centrica-vault-models-common:0.0.1-SNAPSHOT/maven-metadata.xml from/to mseng-visualstudio.com-zcalvinmaven (https://mseng.pkgs.visualstudio.com/_packaging/zCalvinMaven2/maven/v1): Not authorized , ReasonPhrase:Unauthorized.
2017-07-18T07:49:54.5329170Z org.eclipse.aether.transfer.MetadataTransferException: Could not transfer metadata centrica-vault:centrica-vault-models-common:0.0.1-SNAPSHOT/maven-metadata.xml from/to mseng-visualstudio.com-zcalvinmaven (https://mseng.pkgs.visualstudio.com/_packaging/zCalvinMaven2/maven/v1): Not authorized , ReasonPhrase:Unauthorized.
2017-07-18T07:49:54.5329170Z 	at org.eclipse.aether.connector.wagon.WagonRepositoryConnector$5.wrap(WagonRepositoryConnector.java:995)
2017-07-18T07:49:54.5329170Z 	at org.eclipse.aether.connector.wagon.WagonRepositoryConnector$5.wrap(WagonRepositoryConnector.java:983)
2017-07-18T07:49:54.5329170Z 	at org.eclipse.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:725)
2017-07-18T07:49:54.5329170Z 	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
2017-07-18T07:49:54.5329170Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2017-07-18T07:49:54.5329170Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2017-07-18T07:49:54.5329170Z 	at java.lang.Thread.run(Thread.java:745)
2017-07-18T07:49:54.5329170Z Caused by: org.apache.maven.wagon.authorization.AuthorizationException: Not authorized , ReasonPhrase:Unauthorized.
2017-07-18T07:49:54.5329170Z 	at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:876)
2017-07-18T07:49:54.5329170Z 	at org.apache.maven.wagon.StreamWagon.getInputStream(StreamWagon.java:116)
2017-07-18T07:49:54.5329170Z 	at org.apache.maven.wagon.StreamWagon.getIfNewer(StreamWagon.java:88)
2017-07-18T07:49:54.5329170Z 	at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:61)
2017-07-18T07:49:54.5329170Z 	at org.eclipse.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:660)
2017-07-18T07:49:54.5329170Z 	... 4 more
2017-07-18T07:49:54.5329170Z [INFO] ------------------------------------------------------------------------
2017-07-18T07:49:54.5329170Z [INFO] BUILD FAILURE
2017-07-18T07:49:54.5329170Z [INFO] ------------------------------------------------------------------------
2017-07-18T07:49:54.5329170Z [INFO] Total time: 10.092 s
2017-07-18T07:49:54.5329170Z [INFO] Finished at: 2017-07-18T07:49:54+00:00
2017-07-18T07:49:54.6359155Z [INFO] Final Memory: 16M/152M
2017-07-18T07:49:54.6369165Z [INFO] ------------------------------------------------------------------------
2017-07-18T07:49:54.6449176Z [ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project centrica-vault-models-common: Failed to retrieve remote metadata centrica-vault:centrica-vault-models-common:0.0.1-SNAPSHOT/maven-metadata.xml: Could not transfer metadata centrica-vault:centrica-vault-models-common:0.0.1-SNAPSHOT/maven-metadata.xml from/to mseng-visualstudio.com-zcalvinmaven (https://mseng.pkgs.visualstudio.com/_packaging/zCalvinMaven2/maven/v1): Not authorized , ReasonPhrase:Unauthorized. -> [Help 1]
2017-07-18T07:49:54.6449176Z org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project centrica-vault-models-common: Failed to retrieve remote metadata centrica-vault:centrica-vault-models-common:0.0.1-SNAPSHOT/maven-metadata.xml: Could not transfer metadata centrica-vault:centrica-vault-models-common:0.0.1-SNAPSHOT/maven-metadata.xml from/to mseng-visualstudio.com-zcalvinmaven (https://mseng.pkgs.visualstudio.com/_packaging/zCalvinMaven2/maven/v1): Not authorized , ReasonPhrase:Unauthorized.
2017-07-18T07:49:54.6449176Z 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
2017-07-18T07:49:54.6449176Z 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
2017-07-18T07:49:54.6449176Z 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
2017-07-18T07:49:54.6449176Z 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
2017-07-18T07:49:54.6449176Z 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
2017-07-18T07:49:54.6449176Z 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
2017-07-18T07:49:54.6469181Z 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
2017-07-18T07:49:54.6469181Z 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
2017-07-18T07:49:54.6469181Z 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
2017-07-18T07:49:54.6469181Z 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
2017-07-18T07:49:54.6469181Z 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
2017-07-18T07:49:54.6469181Z 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
2017-07-18T07:49:54.6469181Z 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2017-07-18T07:49:54.6469181Z 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2017-07-18T07:49:54.6469181Z 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2017-07-18T07:49:54.6469181Z 	at java.lang.reflect.Method.invoke(Method.java:498)
2017-07-18T07:49:54.6469181Z 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
2017-07-18T07:49:54.6469181Z 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
2017-07-18T07:49:54.6469181Z 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
2017-07-18T07:49:54.6469181Z 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
2017-07-18T07:49:54.6479170Z Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to retrieve remote metadata centrica-vault:centrica-vault-models-common:0.0.1-SNAPSHOT/maven-metadata.xml: Could not transfer metadata centrica-vault:centrica-vault-models-common:0.0.1-SNAPSHOT/maven-metadata.xml from/to mseng-visualstudio.com-zcalvinmaven (https://mseng.pkgs.visualstudio.com/_packaging/zCalvinMaven2/maven/v1): Not authorized , ReasonPhrase:Unauthorized.
2017-07-18T07:49:54.6479170Z 	at org.apache.maven.plugin.deploy.DeployMojo.execute(DeployMojo.java:193)
2017-07-18T07:49:54.6489268Z 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
2017-07-18T07:49:54.6489268Z 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
2017-07-18T07:49:54.6489268Z 	... 19 more
2017-07-18T07:49:54.6489268Z Caused by: org.apache.maven.artifact.deployer.ArtifactDeploymentException: Failed to retrieve remote metadata centrica-vault:centrica-vault-models-common:0.0.1-SNAPSHOT/maven-metadata.xml: Could not transfer metadata centrica-vault:centrica-vault-models-common:0.0.1-SNAPSHOT/maven-metadata.xml from/to mseng-visualstudio.com-zcalvinmaven (https://mseng.pkgs.visualstudio.com/_packaging/zCalvinMaven2/maven/v1): Not authorized , ReasonPhrase:Unauthorized.
2017-07-18T07:49:54.6489268Z 	at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:143)
2017-07-18T07:49:54.6489268Z 	at org.apache.maven.plugin.deploy.AbstractDeployMojo.deploy(AbstractDeployMojo.java:167)
2017-07-18T07:49:54.6489268Z 	at org.apache.maven.plugin.deploy.DeployMojo.execute(DeployMojo.java:157)
2017-07-18T07:49:54.6489268Z 	... 21 more
2017-07-18T07:49:54.6489268Z Caused by: org.eclipse.aether.deployment.DeploymentException: Failed to retrieve remote metadata centrica-vault:centrica-vault-models-common:0.0.1-SNAPSHOT/maven-metadata.xml: Could not transfer metadata centrica-vault:centrica-vault-models-common:0.0.1-SNAPSHOT/maven-metadata.xml from/to mseng-visualstudio.com-zcalvinmaven (https://mseng.pkgs.visualstudio.com/_packaging/zCalvinMaven2/maven/v1): Not authorized , ReasonPhrase:Unauthorized.
2017-07-18T07:49:54.6489268Z 	at org.eclipse.aether.internal.impl.DefaultDeployer.upload(DefaultDeployer.java:463)
2017-07-18T07:49:54.6489268Z 	at org.eclipse.aether.internal.impl.DefaultDeployer.deploy(DefaultDeployer.java:313)
2017-07-18T07:49:54.6489268Z 	at org.eclipse.aether.internal.impl.DefaultDeployer.deploy(DefaultDeployer.java:268)
2017-07-18T07:49:54.6489268Z 	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.deploy(DefaultRepositorySystem.java:413)
2017-07-18T07:49:54.6489268Z 	at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:139)
2017-07-18T07:49:54.6489268Z 	... 23 more
2017-07-18T07:49:54.6489268Z Caused by: org.eclipse.aether.transfer.MetadataTransferException: Could not transfer metadata centrica-vault:centrica-vault-models-common:0.0.1-SNAPSHOT/maven-metadata.xml from/to mseng-visualstudio.com-zcalvinmaven (https://mseng.pkgs.visualstudio.com/_packaging/zCalvinMaven2/maven/v1): Not authorized , ReasonPhrase:Unauthorized.
2017-07-18T07:49:54.6489268Z 	at org.eclipse.aether.connector.wagon.WagonRepositoryConnector$5.wrap(WagonRepositoryConnector.java:995)
2017-07-18T07:49:54.6489268Z 	at org.eclipse.aether.connector.wagon.WagonRepositoryConnector$5.wrap(WagonRepositoryConnector.java:983)
2017-07-18T07:49:54.6489268Z 	at org.eclipse.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:725)
2017-07-18T07:49:54.6489268Z 	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
2017-07-18T07:49:54.6489268Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2017-07-18T07:49:54.6489268Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2017-07-18T07:49:54.6489268Z 	at java.lang.Thread.run(Thread.java:745)
2017-07-18T07:49:54.6489268Z Caused by: org.apache.maven.wagon.authorization.AuthorizationException: Not authorized , ReasonPhrase:Unauthorized.
2017-07-18T07:49:54.6489268Z 	at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:876)
2017-07-18T07:49:54.6489268Z 	at org.apache.maven.wagon.StreamWagon.getInputStream(StreamWagon.java:116)
2017-07-18T07:49:54.6489268Z 	at org.apache.maven.wagon.StreamWagon.getIfNewer(StreamWagon.java:88)
2017-07-18T07:49:54.6489268Z 	at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:61)
2017-07-18T07:49:54.6489268Z 	at org.eclipse.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:660)
2017-07-18T07:49:54.6499181Z 	... 4 more
2017-07-18T07:49:54.6499181Z [ERROR] 
2017-07-18T07:49:54.6499181Z [ERROR] 
2017-07-18T07:49:54.6499181Z [ERROR] For more information about the errors and possible solutions, please read the following articles:
2017-07-18T07:49:54.6499181Z [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by lkillgore** [comment]
Hi @tarunaroraonline, it looks like this is the reason: 
```
Could not transfer metadata centrica-vault:centrica-vault-models-common:0.0.1-SNAPSHOT/maven-metadata.xml from/to mseng-visualstudio.com-zcalvinmaven (https://mseng.pkgs.visualstudio.com/_packaging/zCalvinMaven2/maven/v1): Not authorized , ReasonPhrase:Unauthorized.
--

```
Specifically: **ReasonPhrase:Unauthorized.**

We automatically try to add credentials for authorization for self hosted packages (e.g. mseng builds should support mseng maven feeds).  The version of the Maven task with this support should be 1.120.0.

Could you verify two things for me?
1) Which account is building this? mseng?
2) Which version of the Maven task is used? 1.120.0 or another version

If you need another account other than _mseng_ to have access, you'll need to create a Personal Access Token and add the credentials to your settings.xml.  (See the help section of the Package Management Extension for snippets that you can use for your feed.  Also: https://maven.apache.org/settings.html)

**Comment by tarunaroraonline** [comment]
Thank you @lkillgore. I had incorrect VSTS instance in the settings file because of the example file i copied from ms documentation. I have since changed mseng to my vsts account and added the PAT and that has resolved the issue. Many thanks for your help. 

Tarun
