### ISSUE TITLE
DTAAgentExecutionService: Test Agent deployment failed with error code -1.

### ISSUE THREAD

**Issue by SanthoshYalamuri** [Microsoft/vsts-tasks#4886]
TestAgent deployment is unsuccessful with exit code 1. Following are the excerpts from the logs:

2017-07-27T00:02:14.8126748Z  V, 2017/07/27, 01:28:49.953, ACL Configuration:
2017-07-27T00:02:14.8126748Z 
2017-07-27T00:02:14.8126748Z  V, 2017/07/27, 01:28:49.953, AddAccessToDirectory: started: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE, rights: Write, Read
2017-07-27T00:02:14.8126748Z 
2017-07-27T00:02:14.8126748Z  V, 2017/07/27, 01:28:50.656, AddAccessToDirectory: completed
2017-07-27T00:02:14.8126748Z 
2017-07-27T00:02:14.8126748Z  I, 2017/07/27, 01:28:50.656, Granting permission on file C:\Windows\VSTFS\testagent.config to account Domain\Username
2017-07-27T00:02:14.8126748Z 
2017-07-27T00:02:14.8126748Z  E, 2017/07/27, 01:28:50.671, System.InvalidOperationException: Method failed with unexpected error code 3.
2017-07-27T00:02:14.8126748Z 
2017-07-27T00:02:14.8126748Z     at System.Security.AccessControl.NativeObjectSecurity.CreateInternal(ResourceType resourceType, Boolean isContainer, String name, SafeHandle handle, AccessControlSections includeSections, Boolean createByName, ExceptionFromErrorCode exceptionFromErrorCode, Object exceptionContext)
2017-07-27T00:02:14.8126748Z 
2017-07-27T00:02:14.8126748Z     at System.Security.AccessControl.FileSystemSecurity..ctor(Boolean isContainer, String name, AccessControlSections includeSections, Boolean isDirectory)
2017-07-27T00:02:14.8126748Z 
2017-07-27T00:02:14.8126748Z     at System.Security.AccessControl.FileSecurity..ctor(String fileName, AccessControlSections includeSections)
2017-07-27T00:02:14.8126748Z 
2017-07-27T00:02:14.8126748Z     at Microsoft.VisualStudio.TestTools.ConfigCore.ACLHandler.AddAccessToFile(String fileName, String account, FileSystemRights rights)
2017-07-27T00:02:14.8126748Z 
2017-07-27T00:02:14.8126748Z  E, 2017/07/27, 01:28:50.671, System.InvalidOperationException: Method failed with unexpected error code 3.

2017-07-27T00:02:14.8439269Z   2017/07/27, 02:01:43.167, UnInstallService: Service DTAAgentExecutionService uninstall failed. Error: 0
2017-07-27T00:02:14.8439269Z 
2017-07-27T00:02:14.8439269Z   2017/07/27, 02:01:43.167, Microsoft.VisualStudio.TestTools.ConfigCore.ConfigToolException: Failed to delete windows service DTAAgentExecutionService. (Error Code: 0)
2017-07-27T00:02:14.8439269Z 
2017-07-27T00:02:14.8439269Z     at Microsoft.VisualStudio.TestTools.ConfigCore.Services.UnInstallService(String serviceName)
2017-07-27T00:02:14.8439269Z 
2017-07-27T00:02:14.8439269Z     at Microsoft.VisualStudio.TestTools.ConfigCore.BaseConfiguration.RemoveService(String serviceName, DelegateStatusUpdate statusListener)
2017-07-27T00:02:14.8439269Z 
2017-07-27T00:02:14.8439269Z     at Microsoft.VisualStudio.TestTools.ConfigCore.DTAAgentConfiguration.SetupDTAAgentExecutionService(AgentConfigurationUpdatePack updatePack, DelegateStatusUpdate statusListener)
2017-07-27T00:02:14.8439269Z 
2017-07-27T00:02:14.8439269Z     at Microsoft.VisualStudio.TestTools.ConfigCore.DTAAgentConfiguration.Configure(AgentConfigurationUpdatePack updatePack, DelegateStatusUpdate statusListener)
2017-07-27T00:02:14.8439269Z 
2017-07-27T00:02:14.8439269Z     at Microsoft.VisualStudio.TestTools.AgentConfigCLI.ConfigurationCommon.Run(AgentConfigurationUpdatePack updatePack, DelegateStatusUpdate commandStatusListener)
2017-07-27T00:02:14.8439269Z 
2017-07-27T00:02:14.8439269Z     at Microsoft.VisualStudio.TestTools.AgentConfigCLI.CommandConfigureAsProcess.Run()
2017-07-27T00:02:14.8439269Z 
2017-07-27T00:02:14.8439269Z     at Microsoft.VisualStudio.TestTools.AgentConfigCLI.AppEntry.RunCommand(String commandName, String[] args)
2017-07-27T00:02:14.8439269Z 
2017-07-27T00:02:14.8439269Z   2017/07/27, 02:01:43.167, 
2017-07-27T00:02:14.8439269Z 
2017-07-27T00:02:14.8439269Z  Exception : Failed to delete windows service DTAAgentExecutionService. (Error Code: 0)
2017-07-27T00:02:14.8439269Z Return code received : -1

Unable to find the solution in order to resolve the issue which contains multiple error codes.
[logs.txt](https://github.com/Microsoft/vsts-tasks/files/1180078/logs.txt)

**Comment by vimegh** [comment]
@Santhosh It seems that Test Agent configuration is failing as admin credentials that you are using is not able to delete existing DTAAgentExecutionService in your test machine. Can you check on your test machine that presently who is the owner of service "DTAAgentExecutionService". Also can you try deleting it manually ( you can use:  sc delete DTAAgentExecutionService) and then try again.

**Comment by SanthoshYalamuri** [comment]
@vimegh Thank you, the issue was resolved in the next deployment. This might be an intermittent issue as the deployment user has administrator access on the test machine.

**Comment by vimegh** [comment]
Thanks for confirming Santhosh.  I am closing the issue for now. In case you face the issue again, please feel free to reach us.
