### ISSUE TITLE
Run Functional Tests using NUnit

### ISSUE THREAD

**Issue by ygeelen-tb** [Microsoft/vsts-tasks#4902]
The Deploy TestAgent task succeeds but when running the RFT task, all tests remain Pending. I see a lot of IEDriver and Internet Explorer processes being spawned at the Server but no tests seem to actually run? See the RFT task configuration in attached screenshot.

2017-07-28T10:17:19.2036651Z ==============================================================================
2017-07-28T10:17:19.2036651Z Task         : Run Functional Tests
2017-07-28T10:17:19.2036651Z Description  : Run Coded UI/Selenium/Functional tests on a set of machines (using Test Agent)
2017-07-28T10:17:19.2036651Z Version      : 1.0.52
2017-07-28T10:17:19.2036651Z Author       : Microsoft Corporation
2017-07-28T10:17:19.2036651Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=624389)
2017-07-28T10:17:19.2036651Z ==============================================================================
2017-07-28T10:17:19.2036651Z Preparing task execution handler.
2017-07-28T10:17:19.5630415Z Executing the powershell script: F:\agent01\_work\_tasks\RunVisualStudioTestsusingTestAgent_d353d6a2-e361-4a8f-8d8c-123bebb71028\1.0.52\RunDistributedTests.ps1
2017-07-28T10:17:20.7036636Z DistributedTests: Environment WinRm Protocol HTTP.
2017-07-28T10:17:20.7192886Z DistributedTests: Creating run for selected test assemblies with following parameters
2017-07-28T10:17:20.7192886Z DistributedTests: SourceFilter: CustomerTestAutomation.dll TestCaseFilter: 
2017-07-28T10:17:20.7192886Z DistributedTests: Run title: TestRun_Customer-CI_Release-137
2017-07-28T10:17:20.7192886Z DistributedTests: is automated: True
2017-07-28T10:17:20.7192886Z DistributedTests: build location: F:\Test\customer
2017-07-28T10:17:20.7192886Z DistributedTests: build id: 5477
2017-07-28T10:17:20.7192886Z DistributedTests: test configuration mapping: 
2017-07-28T10:17:22.1411706Z DistributedTests: Test Run with Id 364 Queued
2017-07-28T10:23:56.9235570Z DistributedTests: Test run '364' is in 'InProgress' state.
2017-07-28T10:23:56.9235570Z DistributedTests: Total Tests : 36, Passed Tests : 0
2017-07-28T10:18:02.8287490Z DistributedTests: Test run '364' is in 'InProgress' state.
2017-07-28T10:18:02.8287490Z DistributedTests: Total Tests : 36, Passed Tests : 0
2017-07-28T10:18:12.9068955Z DistributedTests: Test run '364' is in 'InProgress' state.
2017-07-28T10:18:12.9068955Z DistributedTests: Total Tests : 36, Passed Tests : 0
2017-07-28T10:18:23.0618427Z DistributedTests: Test run '364' is in 'InProgress' state.
2017-07-28T10:18:23.0618427Z DistributedTests: Total Tests : 36, Passed Tests : 0
2017-07-28T10:18:33.2024870Z DistributedTests: Test run '364' is in 'InProgress' state.
2017-07-28T10:18:33.2024870Z DistributedTests: Total Tests : 36, Passed Tests : 0
2017-07-28T10:18:43.4056431Z DistributedTests: Test run '364' is in 'InProgress' state.
2017-07-28T10:18:43.4056431Z DistributedTests: Total Tests : 36, Passed Tests : 0
2017-07-28T10:18:53.5462858Z DistributedTests: Test run '364' is in 'InProgress' state.
2017-07-28T10:18:53.5462858Z DistributedTests: Total Tests : 36, Passed Tests : 0
2017-07-28T10:19:03.6400600Z DistributedTests: Test run '364' is in 'InProgress' state.
2017-07-28T10:19:03.6400600Z DistributedTests: Total Tests : 36, Passed Tests : 0
2017-07-28T10:19:13.7494393Z DistributedTests: Test run '364' is in 'InProgress' state.
2017-07-28T10:19:13.7494393Z DistributedTests: Total Tests : 36, Passed Tests : 0
2017-07-28T10:19:23.8432336Z DistributedTests: Test run '364' is in 'InProgress' state.
2017-07-28T10:19:23.8432336Z DistributedTests: Total Tests : 36, Passed Tests : 0
2017-07-28T10:19:33.9369803Z DistributedTests: Test run '364' is in 'InProgress' state.
2017-07-28T10:19:33.9369803Z DistributedTests: Total Tests : 36, Passed Tests : 0
2017-07-28T10:19:44.0151279Z DistributedTests: Test run '364' is in 'InProgress' state.
2017-07-28T10:19:44.0151279Z DistributedTests: Total Tests : 36, Passed Tests : 0
2017-07-28T10:19:54.1088965Z DistributedTests: Test run '364' is in 'InProgress' state.
2017-07-28T10:19:54.1088965Z DistributedTests: Total Tests : 36, Passed Tests : 0
2017-07-28T10:20:04.2026653Z DistributedTests: Test run '364' is in 'InProgress' state.
2017-07-28T10:20:14.2964406Z DistributedTests: Total Tests : 36, Passed Tests : 0
2017-07-28T10:20:14.2964406Z DistributedTests: Test run '364' is in 'InProgress' state.
2017-07-28T10:20:14.2964406Z DistributedTests: Total Tests : 36, Passed Tests : 0
2017-07-28T10:20:24.3902078Z DistributedTests: Test run '364' is in 'InProgress' state.
2017-07-28T10:20:24.3902078Z DistributedTests: Total Tests : 36, Passed Tests : 0
2017-07-28T10:20:34.4839754Z DistributedTests: Test run '364' is in 'InProgress' state.
2017-07-28T10:20:34.4839754Z DistributedTests: Total Tests : 36, Passed Tests : 0
2017-07-28T10:20:44.8746320Z DistributedTests: Test run '364' is in 'InProgress' state.
2017-07-28T10:20:44.8746320Z DistributedTests: Total Tests : 36, Passed Tests : 0
2017-07-28T10:20:54.9527647Z DistributedTests: Test run '364' is in 'InProgress' state.
2017-07-28T10:20:54.9527647Z DistributedTests: Total Tests : 36, Passed Tests : 0
2017-07-28T10:21:05.0934102Z DistributedTests: Test run '364' is in 'InProgress' state.
2017-07-28T10:21:05.0934102Z DistributedTests: Total Tests : 36, Passed Tests : 0
2017-07-28T10:21:15.1888829Z DistributedTests: Test run '364' is in 'InProgress' state.
2017-07-28T10:21:15.1888829Z DistributedTests: Total Tests : 36, Passed Tests : 0
2017-07-28T10:21:25.2826357Z DistributedTests: Test run '364' is in 'InProgress' state.
2017-07-28T10:21:25.2826357Z DistributedTests: Total Tests : 36, Passed Tests : 0
2017-07-28T10:21:35.3607896Z DistributedTests: Test run '364' is in 'InProgress' state.
2017-07-28T10:21:35.3607896Z DistributedTests: Total Tests : 36, Passed Tests : 0
2017-07-28T10:21:45.6420502Z DistributedTests: Test run '364' is in 'InProgress' state.
2017-07-28T10:21:45.6420502Z DistributedTests: Total Tests : 36, Passed Tests : 0
2017-07-28T10:21:55.5327094Z DistributedTests: Test run '364' is in 'InProgress' state.
2017-07-28T10:21:55.5327094Z DistributedTests: Total Tests : 36, Passed Tests : 0
2017-07-28T10:22:05.6264709Z DistributedTests: Test run '364' is in 'InProgress' state.
2017-07-28T10:22:15.7202588Z DistributedTests: Total Tests : 36, Passed Tests : 0
2017-07-28T10:22:15.7202588Z DistributedTests: Test run '364' is in 'InProgress' state.
2017-07-28T10:22:15.7202588Z DistributedTests: Total Tests : 36, Passed Tests : 0
2017-07-28T10:22:25.8296340Z DistributedTests: Test run '364' is in 'InProgress' state.
2017-07-28T10:22:25.8296340Z DistributedTests: Total Tests : 36, Passed Tests : 0
2017-07-28T10:22:35.9546474Z DistributedTests: Test run '364' is in 'InProgress' state.
2017-07-28T10:22:35.9546474Z DistributedTests: Total Tests : 36, Passed Tests : 0
2017-07-28T10:22:46.0327934Z DistributedTests: Test run '364' is in 'InProgress' state.
2017-07-28T10:22:46.0327934Z DistributedTests: Total Tests : 36, Passed Tests : 0
2017-07-28T10:22:56.1109389Z DistributedTests: Test run '364' is in 'InProgress' state.
2017-07-28T10:22:56.1109389Z DistributedTests: Total Tests : 36, Passed Tests : 0
2017-07-28T10:23:06.2203316Z DistributedTests: Test run '364' is in 'InProgress' state.
2017-07-28T10:23:06.2203316Z DistributedTests: Total Tests : 36, Passed Tests : 0
2017-07-28T10:23:16.3922359Z DistributedTests: Test run '364' is in 'InProgress' state.
2017-07-28T10:23:16.3922359Z DistributedTests: Total Tests : 36, Passed Tests : 0
2017-07-28T10:23:26.5172468Z DistributedTests: Test run '364' is in 'InProgress' state.
2017-07-28T10:23:26.5172468Z DistributedTests: Total Tests : 36, Passed Tests : 0
2017-07-28T10:23:36.6578869Z DistributedTests: Test run '364' is in 'InProgress' state.
2017-07-28T10:23:36.6578869Z DistributedTests: Total Tests : 36, Passed Tests : 0
2017-07-28T10:23:46.7516616Z DistributedTests: Test run '364' is in 'InProgress' state.
2017-07-28T10:23:46.7516616Z DistributedTests: Total Tests : 36, Passed Tests : 0
2017-07-28T10:23:56.9235570Z DistributedTests: Test run '364' is in 'InProgress' state.
2017-07-28T10:23:56.9235570Z DistributedTests: Total Tests : 36, Passed Tests : 0

![rft](https://user-images.githubusercontent.com/12393883/28713924-6f66b6e4-7391-11e7-8821-330c3899d321.png)

**Comment by ygeelen-tb** [comment]
@nigurr @kaadhina
Here are the corresponding DTA logs (with sensitive information obscured):
[DTAExecutionHost.exe.log.txt](https://github.com/Microsoft/vsts-tasks/files/1182972/DTAExecutionHost.exe.log.txt)

**Comment by nigurr** [comment]
@ygeelen-tb Can you attache the build log? Is the task failed with some error? I do see that tests are getting executed and few of the tests failed and updated the test run with the same information.

**Comment by ygeelen-tb** [comment]
In fact I had to cancel the Release because it seemed to be hanging..
And after the cancellation I had to kill all those IEDriver and Internet Explorer processes.

[RFTlog.txt](https://github.com/Microsoft/vsts-tasks/files/1183074/RFTlog.txt)

**Comment by nigurr** [comment]
@ygeelen-tb From the logs, everything seems to be working fine.

From Test Agent machine:
DTAExecutionHost.exe Information: 0 : Publish.Run : Publishing to tcm finished
    DateTime=2017-07-28T10:27:46.9672582Z

From Release log:
2017-07-28T10:24:07.2360815Z ##[error]The operation was canceled.

You seems to cancelled the operation before even tests are completed.

**Comment by ygeelen-tb** [comment]
@nigurr I don't think it's normal that the RFT task runs for almost 7 minutes without finishing any test? They all stayed in Pending status, that's why it was cancelled.

**Comment by nigurr** [comment]
@ygeelen-tb Currently it's limitation that it will report at the end of the test run. We have improved to live reporting using VsTest v2 - https://blogs.msdn.microsoft.com/devops/2017/03/26/vstest-task-dons-a-new-avatar-testing-with-unified-agents-and-phases/

**Comment by ygeelen-tb** [comment]
@nigurr Does the VsTest v2 task replace the Run Functional Tests task? Does it support Selenium browser tests as well?

When waiting for 25+ minutes I managed to see the results (it's the same for all tests):

OpenQA.Selenium.WebDriverException : Unexpected error launching Internet Explorer. IELaunchURL() returned HRESULT 80070012 ('There are no more files.') for URL 'http://localhost:23946/'
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.

at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
at OpenQA.Selenium.IE.InternetExplorerDriver..ctor(InternetExplorerDriverService service, InternetExplorerOptions options)
at MyCustomerTestAutomation.AuthenticationSteps.GivenIAmOnTheAuthenticationpage() in C:\agent\_work\120\s\MyCustomerTestAutomation\Steps\AuthenticationSteps.cs:line 34
at lambda_method(Closure , IContextManager )
at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments)
at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStep(IContextManager contextManager, StepInstance stepInstance)
at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
at TechTalk.SpecFlow.TestRunner.CollectScenarioErrors()
at MyCustomerTestAutomation.Features.AuthenticationFeature.ScenarioCleanup()
at MyCustomerTestAutomation.Features.AuthenticationFeature.AuthenticationFailed(String username, String password, String[] exampleTags) in C:\agent\_work\120\s\MyCustomerTestAutomation\Features\Authentication.feature:line 23
--TearDown
at MyCustomerTestAutomation.AuthenticationSteps.DisposeWebDriver() in C:\agent\_work\120\s\MyCustomerTestAutomation\Steps\AuthenticationSteps.cs:line 108
at lambda_method(Closure , IContextManager )
at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.InvokeHook(IBindingInvoker invoker, IHookBinding hookBinding, HookType hookType)
at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.FireEvents(HookType hookType)
at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.FireScenarioEvents(HookType bindingEvent)
at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnScenarioEnd()
at TechTalk.SpecFlow.TestRunner.OnScenarioEnd()
at MyCustomerTestAutomation.Features.AuthenticationFeature.ScenarioTearDown()

**Comment by nigurr** [comment]
@ygeelen-tb Yes. It will be used for running running unit tests as well as functional tests. The error seems to be very specific to Selenium/Driver implementation
https://github.com/SeleniumHQ/selenium/issues/4135
