### ISSUE TITLE
VSTS tasks failing with insufficient system resources

### ISSUE THREAD

**Issue by aaron-bozit** [Microsoft/vsts-tasks#5140]
Hi,

We have TFS2017 Update 2 installed on-premises and we are trying to perform a build, this issue is stopping us so far from effectively using the new build agents (both 2.117.2 and 2.120.2 agent versions)

Even publishing Artifacts fails.

> 2017-08-31T00:20:03.6736841Z ##[section]Starting: Publish Artifact: 2887
> 2017-08-31T00:20:03.6746845Z ==============================================================================
> 2017-08-31T00:20:03.6746845Z Task         : Publish Build Artifacts
> 2017-08-31T00:20:03.6746845Z Description  : Publish Build artifacts to the server or a file share
> 2017-08-31T00:20:03.6746845Z Version      : 1.0.42
> 2017-08-31T00:20:03.6746845Z Author       : Microsoft Corporation
> 2017-08-31T00:20:03.6746845Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=708390)
> 2017-08-31T00:20:03.6746845Z ==============================================================================
> 2017-08-31T00:20:04.2857130Z ##[error]Insufficient system resources exist to complete the requested service
> 2017-08-31T00:20:04.2877127Z ##[section]Finishing: Publish Artifact: 2887

As part of the build we are doing an Archive.

> Starting: Archive files
> 
> 
> Task         : Archive Files
> Description  : Archive files using compression formats such as .7z, .rar, .tar.gz, and .zip.
> Version      : 1.117.0
> Author       : Microsoft Corporation
> Help         : [More Information](http://go.microsoft.com/fwlink/?LinkId=809083)
> 
> Insufficient system resources exist to complete the requested service

As part of the build, we are also doing a NuGet Restore.

During this we receive the following error from the task;

> 2017-08-28T23:32:06.1801215Z ##[section]Starting: Build
> 2017-08-28T23:32:06.1831215Z Current agent version: '2.117.2'
> 2017-08-28T23:32:16.0272739Z ##[section]Starting: NuGet restore fish.sln
> 2017-08-28T23:32:16.0372748Z ==============================================================================
> 2017-08-28T23:32:16.0372748Z Task         : NuGet Restore
> 2017-08-28T23:32:16.0372748Z Description  : Restores NuGet packages in preparation for a Visual Studio Build step.
> 2017-08-28T23:32:16.0372748Z Version      : 1.0.1
> 2017-08-28T23:32:16.0372748Z Author       : Microsoft Corporation
> 2017-08-28T23:32:16.0372748Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613747)
> 2017-08-28T23:32:16.0372748Z ==============================================================================
> 2017-08-28T23:32:16.6352728Z ##[error]Insufficient system resources exist to complete the requested service
> System.ComponentModel.Win32Exception: Insufficient system resources exist to complete the requested service
> 2017-08-28T23:32:16.6412729Z ##[section]Finishing: NuGet restore fish.sln

The build server we have has the agent '2.117.2', the server has 4Gb RAM and 21Gb of SSD disk space free.

Worker Log File;

> [2017-08-28 23:54:29Z INFO ProcessInvoker] Starting process:
> [2017-08-28 23:54:29Z INFO ProcessInvoker]   File name: 'C:\vstsAgent\externals\node\bin\node.exe'
> [2017-08-28 23:54:29Z INFO ProcessInvoker]   Arguments: '"C:\vstsAgent\_work\_tasks\NuGetRestore_333b11bd-d341-40d9-afcf-b32d5ce6f23b\1.0.1\nugetinstaller.js"'
> [2017-08-28 23:54:29Z INFO ProcessInvoker]   Working directory: 'C:\vstsAgent\_work\6\s'
> [2017-08-28 23:54:29Z INFO ProcessInvoker]   Require exit code zero: 'True'
> [2017-08-28 23:54:29Z INFO ProcessInvoker]   Encoding web name: utf-8 ; code page: '65001'
> [2017-08-28 23:54:29Z INFO ProcessInvoker]   Force kill process on cancellation: 'False'
> [2017-08-28 23:54:29Z INFO JobServerQueue] Try to upload 1 log files or attachments, success rate: 1/1.
> [2017-08-28 23:54:29Z INFO JobServerQueue] Try to append 1 batches web console lines, success rate: 1/1.
> [2017-08-28 23:54:29Z ERR  StepsRunner] Caught exception from step: System.ComponentModel.Win32Exception: Insufficient system resources exist to complete the requested service
>    at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
>    at Microsoft.VisualStudio.Services.Agent.ProcessInvoker.<ExecuteAsync>d__19.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.NodeHandler.<RunAsync>d__6.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.<RunAsync>d__24.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.<RunStepAsync>d__1.MoveNext()
> [2017-08-28 23:54:29Z INFO StepsRunner] Step result: Failed
> [2017-08-28 23:54:29Z INFO StepsRunner] Update job result with current step result 'Failed'.
> [2017-08-28 23:54:29Z INFO StepsRunner] Current state: job state = 'Failed'
> [2017-08-28 23:54:29Z INFO StepsRunner] Processing step: DisplayName='Build solution fish.sln', ContinueOnError=False, Enabled=True

Could you please help to point me in the direction to rectify this?

Thanks.

**Comment by aaron-bozit** [comment]
Closing issue as it appears that this was related to a Group Policy that was being applied to the server (not sure which), it would be good if the error message was a bit more clear.
