### ISSUE TITLE
Service Fabric: Could not find Local.xml in build error after upgrading Solution to Latest SF version

### ISSUE THREAD

**Issue by naresh1990** [Microsoft/vsts-tasks#5232]
We were upgrading Service Fabric package version for our application from 5.4 to 5.7. with this change, Local.xml in publish profiles got changed to Local.1Node.xml and Local.5Node.xml and there is no Local.xml anymore.

I was able to build the solution and deploy my local cluster as SF SDK 5.7 is installed in my machine.

But when it comes to VSTS CI, Build is failing with the below error.

```
2017-09-05T09:03:10.7060823Z ##[error]DeploymentLibrary\ServiceFabric\ServiceFabricMsBuild\Microsoft.VisualStudio.Azure.Fabric.ApplicationPackage.targets(52,5): Error MSB4018: The "GetApplicationParametersFiles" task failed unexpectedly.
System.IO.FileNotFoundException: Could not find file 'd:\a\1\s\<SF Application Type>\PublishProfiles\Local.xml'.
File name: 'd:\a\1\s\<SF Application Type>\PublishProfiles\Local.xml'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Microsoft.VisualStudio.Azure.Fabric.FileSystem.FileOpenRead(String path)
   at Microsoft.VisualStudio.Azure.Fabric.BuildTasks.GetApplicationParametersFiles.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

My question at first was, why the build server (Hosted Agent) was looking for Local.xml where there is no reference to it in the proj files.

after some initial search, i could find that as per this, Hosted agent has SF version 5.4 installed. may be this could be the reason it was looking for Local.xml instead of Local.5Node.xml

Is my analysis correct or there could be any other issue? Or How do we make it work with Hosted Agents instead of Custom agents with SF 5.7 installed?

Any help would be appreciated.

**Comment by bishal-pdMSFT** [comment]
@naresh1990 you are right that Hosted agent has SF 5.4. You can use HostedVS2017 pool which has 5.6 preview version of SF. it is going to be updated to 5.7 soon.

**Comment by bishal-pdMSFT** [comment]
@naresh1990 SF SDK has been upgraded to 2.8 in HostedVS2017 pool. Please retry and if you still see the bug, reactivate this issue.
