### ISSUE TITLE
Error during first build - cannot download sources

### ISSUE THREAD

**Issue by manisko** [Microsoft/vsts-tasks#5286]
Error: Exit code 255 returned from process: file name 'tf', arguments 'vc workspaces /format:xml /collection:https://dgsit.visualstudio.com/ /loginType:OAuth /login:.,******** /noprompt'.

Build Server contains BizTalk 2016 Feature Pack 1, VS 2015, SQL Server 2016

Fresh agent: 2.120.2

Logs from task Get Sources:

Evaluating condition for step: 'Get Sources'
Evaluating: succeeded()
Evaluating succeeded:
=> (Boolean) True
Expanded: True
Result: True
******************************************************************************
Starting: Get Sources
******************************************************************************
Sync source for endpoint: BizTalk Integration
Prepending Path environment variable with directory containing 'tf.exe'.
Path: 'D:\VstsBuildAgents\KBNDVTBS59-Agent1\externals\vstsom;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;%USERPROFILE%\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Microsoft BizTalk Server 2016\;C:\Program Files (x86)\Microsoft BizTalk Server 2016\Bins32;C:\Program Files (x86)\Microsoft BizTalk Server 2016\Bins64;C:\Program Files\Microsoft\Web Platform Installer\;C:\U...
Setting environment variable TFVC_BUILDAGENT_POLICYPATH
Querying workspace information.
tf vc workspaces /format:xml /collection:https://xxx.visualstudio.com/ /loginType:OAuth /login:.,******** /noprompt
Unhandled Exception: System.MissingMethodException: Method not found: 'System.Collections.Generic.IEnumerable`1<System.String> Microsoft.VisualStudio.Services.Common.VssEnvironment.EnumerateVssPaths()'.
at Microsoft.TeamFoundation.Common.VssAssemblyResolver.ResolveAssembly(String name)
at Microsoft.TeamFoundation.VersionControl.CommandLine.RegistryDetour.LoadDependecies()
at Microsoft.TeamFoundation.VersionControl.CommandLine.RegistryDetour..ctor()
at Microsoft.TeamFoundation.VersionControl.CommandLine.TFCommandLine.Main(String[] args)
Unhandled Exception: System.MissingMethodException: Method not found: 'System.Collections.Generic.IEnumerable`1<System.String> Microsoft.VisualStudio.Services.Common.VssEnvironment.EnumerateVssPaths()'.
   at Microsoft.TeamFoundation.Common.VssAssemblyResolver.ResolveAssembly(String name)
   at Microsoft.TeamFoundation.VersionControl.CommandLine.RegistryDetour.LoadDependecies()
   at Microsoft.TeamFoundation.VersionControl.CommandLine.RegistryDetour..ctor()
   at Microsoft.TeamFoundation.VersionControl.CommandLine.TFCommandLine.Main(String[] args)
Exit code 255 returned from process: file name 'tf', arguments 'vc workspaces /format:xml /collection:https://xxx.visualstudio.com/ /loginType:OAuth /login:.,******** /noprompt'.
Microsoft.VisualStudio.Services.Agent.ProcessExitCodeException: Exit code 255 returned from process: file name 'tf', arguments 'vc workspaces /format:xml /collection:https://xxx.visualstudio.com/ /loginType:OAuth /login:.,******** /noprompt'.
******************************************************************************
Finishing: Get Sources
******************************************************************************
Evaluating condition for step: 'Post Job Cleanup'
Always run post-job step: 'Post Job Cleanup'
******************************************************************************
Starting: Post Job Cleanup
******************************************************************************
******************************************************************************
Finishing: Post Job Cleanup
******************************************************************************
Cleaning agent temp folder: D:\B\_temp
******************************************************************************
Finishing: Build
******************************************************************************

**Comment by manisko** [comment]
After installation CU1/CU2 (BTS2016-KB4014788-ENU.exe) it works.
