### ISSUE TITLE
Azure Resource Group Deployment: Unable to edit or replace deployment

### ISSUE THREAD

**Issue by jukai16** [Microsoft/vsts-tasks#5320]
Hi,

I have multiple apps using the same ARM template during deployment. I am using multiple on-prem agents and understandably apps can be deployed simultaneously.

In some instances the _Azure Resource Group Deployment_ is kicked off at the same time. The challenge I have is, because the task creates a deployment with the following name: _[template name]-yyyymmdd-hhmm_ (for example: azuredeploy-20170913-055) I get the following error: 
> ##[error]Unable to edit or replace deployment **_'azuredeploy-20170913-0155'_**: previous deployment from '9/13/2017 1:55:45 AM' is still active (expiration time is '9/20/2017 1:55:44 AM')

Below are the logs from two different agents:
![image](https://user-images.githubusercontent.com/23535456/30405713-944ebe68-9941-11e7-8337-aa6b5603a64c.png)

**Comment by sachinma** [comment]
Thanks for reporting this. As you  pointed out, there can be a conflict with the deployment name format that we have chosen. We will work on fixing this.

**Comment by pratap284** [comment]
We are facing the same issue when running the same task for deploying Topics and subscriptions on our releases. 

2018-07-02T12:08:43.1073766Z ##[command]& 'H:\vsts6\_work\r19\a\design.main\drop\CreateESBSubscriptions.ps1' -scriptPath H:\vsts6\_work\r19\a\design.main\drop -serviceBusResourceGroup MT1-QA-184-SEA-RG-ESB -serviceBusNamespace MT1-QA-184-SEA-Servicebus -resourceLocation "Southeast Asia"
2018-07-02T12:08:46.0923632Z VERBOSE: Error record:
2018-07-02T12:08:46.1613496Z VERBOSE: New-AzureRmResourceGroupDeployment : Unable to edit or replace deployment 'ESPTopicsDeployment': previous 
2018-07-02T12:08:46.1615077Z deployment 
2018-07-02T12:08:46.1630681Z VERBOSE: from '7/2/2018 12:08:13 PM' is still active (expiration time is '7/9/2018 12:08:11 PM'). Please see 
2018-07-02T12:08:46.1638056Z VERBOSE: https://aka.ms/arm-deploy for usage details.
2018-07-02T12:08:46.1645606Z VERBOSE: At H:\vsts6\_work\r19\a\design.main\drop\CreateESBSubscriptions.ps1:149 char:1
2018-07-02T12:08:46.1654771Z VERBOSE: + New-AzureRmResourceGroupDeployment -Name ESPTopicsDeployment -Resourc ...
2018-07-02T12:08:46.1660758Z VERBOSE: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2018-07-02T12:08:46.1670673Z VERBOSE:     + CategoryInfo          : CloseError: (:) [New-AzureRmResourceGroupDeployment], CloudException
2018-07-02T12:08:46.1676958Z VERBOSE:     + FullyQualifiedErrorId : 
2018-07-02T12:08:46.1678212Z Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDep 
2018-07-02T12:08:46.1683847Z VERBOSE:    loymentCmdlet
2018-07-02T12:08:46.1689174Z VERBOSE:  
2018-07-02T12:08:46.1702547Z VERBOSE: Script stack trace:
2018-07-02T12:08:46.1739960Z VERBOSE: at <ScriptBlock>, H:\vsts6\_work\r19\a\design.main\drop\CreateESBSubscriptions.ps1: line 149
2018-07-02T12:08:46.1752194Z VERBOSE: at <ScriptBlock>, <No file>: line 1
2018-07-02T12:08:46.1759908Z VERBOSE: at <ScriptBlock>, 
2018-07-02T12:08:46.1767128Z VERBOSE: H:\vsts6\_work\_tasks\AzurePowerShell_72a1931b-effb-4d2e-8fd8-f8472a07cb62\1.113.5\AzurePowerShell.ps1: line 
2018-07-02T12:08:46.1767905Z 73
2018-07-02T12:08:46.1776465Z VERBOSE: at <ScriptBlock>, 
2018-07-02T12:08:46.1783472Z VERBOSE: H:\vsts6\_work\_tasks\AzurePowerShell_72a1931b-effb-4d2e-8fd8-f8472a07cb62\1.113.5\AzurePowerShell.ps1: line 
2018-07-02T12:08:46.1785065Z 69
2018-07-02T12:08:46.1796476Z VERBOSE: at <ScriptBlock>, <No file>: line 1
2018-07-02T12:08:46.1806238Z VERBOSE: at <ScriptBlock>, <No file>: line 22
2018-07-02T12:08:46.1815692Z VERBOSE: at <ScriptBlock>, <No file>: line 18
2018-07-02T12:08:46.1825952Z VERBOSE: at <ScriptBlock>, <No file>: line 1
2018-07-02T12:08:46.1838021Z VERBOSE: Exception:
2018-07-02T12:08:46.2091501Z VERBOSE: Microsoft.Rest.Azure.CloudException: Unable to edit or replace deployment 'ESPTopicsDeployment': previous 
2018-07-02T12:08:46.2092503Z deployment 
2018-07-02T12:08:46.2111319Z VERBOSE: from '7/2/2018 12:08:13 PM' is still active (expiration time is '7/9/2018 12:08:11 PM'). Please see 
2018-07-02T12:08:46.2121290Z VERBOSE: https://aka.ms/arm-deploy for usage details.
2018-07-02T12:08:46.2126865Z VERBOSE:    at 
2018-07-02T12:08:46.2128497Z Microsoft.Azure.Management.ResourceManager.DeploymentsOperations.<ValidateWithHttpMessagesAsync>d__10.MoveNext()
2018-07-02T12:08:46.2144727Z VERBOSE: --- End of stack trace from previous location where exception was thrown ---
2018-07-02T12:08:46.2152423Z VERBOSE:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-07-02T12:08:46.2160094Z VERBOSE:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-07-02T12:08:46.2165942Z VERBOSE:    at 
2018-07-02T12:08:46.2166938Z Microsoft.Azure.Management.ResourceManager.DeploymentsOperationsExtensions.<ValidateAsync>d__11.MoveNext()
2018-07-02T12:08:46.2183727Z VERBOSE: --- End of stack trace from previous location where exception was thrown ---
2018-07-02T12:08:46.2190106Z VERBOSE:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-07-02T12:08:46.2197896Z VERBOSE:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-07-02T12:08:46.2203151Z VERBOSE:    at 
2018-07-02T12:08:46.2205300Z Microsoft.Azure.Management.ResourceManager.DeploymentsOperationsExtensions.Validate(IDeploymentsOperations 
2018-07-02T12:08:46.2214761Z VERBOSE: operations, String resourceGroupName, String deploymentName, Deployment parameters)
2018-07-02T12:08:46.2222428Z VERBOSE:    at 
2018-07-02T12:08:46.2227277Z VERBOSE: 
2018-07-02T12:08:46.2229275Z Microsoft.Azure.Commands.ResourceManager.Cmdlets.SdkClient.ResourceManagerSdkClient.CheckBasicDeploymentErrors(String 
2018-07-02T12:08:46.2239506Z VERBOSE: resourceGroup, String deploymentName, Deployment deployment)
2018-07-02T12:08:46.2245276Z VERBOSE:    at 
2018-07-02T12:08:46.2246537Z Microsoft.Azure.Commands.ResourceManager.Cmdlets.SdkClient.ResourceManagerSdkClient.ExecuteDeployment(PSCreateRes
2018-07-02T12:08:46.2253705Z VERBOSE: ourceGroupDeploymentParameters parameters)
2018-07-02T12:08:46.2260304Z VERBOSE:    at 
2018-07-02T12:08:46.2262070Z Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDeploymentCmdlet.<ExecuteCmd
2018-07-02T12:08:46.2268779Z VERBOSE: let>b__25_0()
2018-07-02T12:08:46.2277760Z VERBOSE:    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ConfirmAction(Boolean force, String 
2018-07-02T12:08:46.2291321Z VERBOSE: continueMessage, String processMessage, String target, Action action, Func`1 useShouldContinue)
2018-07-02T12:08:46.2297889Z VERBOSE:    at 
2018-07-02T12:08:46.2302853Z VERBOSE: 
2018-07-02T12:08:46.2303358Z Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDeploymentCmdlet.ExecuteCmdlet()
2018-07-02T12:08:46.2311162Z VERBOSE:    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
2018-07-02T12:08:46.2496539Z ##[error]Unable to edit or replace deployment 'ESPTopicsDeployment': previous deployment from '7/2/2018 12:08:13 PM' is still active (expiration time is '7/9/2018 12:08:11 PM'). Please see https://aka.ms/arm-deploy for usage details.
2018-07-02T12:08:46.2497482Z ##[debug]Processed: ##vso[task.logissue type=error]Unable to edit or replace deployment 'ESPTopicsDeployment': previous deployment from '7/2/2018 12:08:13 PM' is still active (expiration time is '7/9/2018 12:08:11 PM'). Please see https://aka.ms/arm-deploy for usage details.
2018-07-02T12:08:46.2513992Z ##[debug]Processed: ##vso[task.complete result=Failed]

Do you have an update on when the fix will be available?

**Comment by ds-ms** [comment]
The issue doesn't seem to be with the name of the deployment, I suppose you're trying to run 2 deployments on the same resource group in parallel. Since the previous deployment is still in progress, ARM has blocked your new deployment request. You can verify your deployment logs in Azure and validate my theory. Also, if it's consistently happening, you can check the statuses of deployments on that resource group. Stop some deployments manually if you don't want them to work.

**Comment by pratap284** [comment]
Hi Deepak,

Makes sense and agree on this however the way we have setup our products they will be fired all at once and use ESB as a shared resource. Rather than using ARM template we will try with Set-AzureRM task for creating subscriptions. My guess is that this might allow parallel command executions instead of the ARM template.

Please let me know if you have any concerns or suggestion on above approach.

Thanks

Pratap Penmetsa
Release Engineer
m +1 (480) 878 8413

**Comment by hjungG** [comment]
I had same issue with New-AzResourceGroupDeployment but it seems working fine if I provide different deployment name with an argument (-n)
