### ISSUE TITLE
Override Template Parameters not working for securestring on V2

### ISSUE THREAD

**Issue by elferone** [Microsoft/vsts-tasks#5372]
When trying to override 2 parameters, which the 2 of them are securestring, only the first one works. the second parameter doesn't get replaced and I get this error message when releasing: 

Deployment template validation failed: 'The value for the template parameter 'appOnlyAuthClientSecret' at line '1' and column '772' is not provided. Please see https://aka.ms/arm-deploy/#parameter-file for usage details.'.

When switching back to to V1, it works.

Also, when selecting V2 and clicking "...", i get this error message: "
Error:Cannot read property 'artifacts' of undefined"

Don't know if it is related.

**Comment by ds-ms** [comment]
@elferone could you attach some debug logs and the way you've overrode those parameters for some investigation. Also, the template you've used.

**Comment by ds-ms** [comment]
Closing this; assuming you found a fix.

**Comment by devedse** [comment]
Hi, can we reopen this as this issue is still occurring. I can provide some logs on what's going wrong.

We are currently doing a 2 step deployment with ARM templates.

The first step is to copy the deployable content to an Azure Blob. The second step is to kick off the ARM template to do the actual deployment.

![image](https://user-images.githubusercontent.com/2350015/42232957-56f6e91a-7ef0-11e8-89ce-6a468bfb51f6.png)

As can be seen in the image above there's 2 output variables being written in the  copy to blob storage task.

In the step where we kick off the actual ARM deploy we use this string to override the release parameters:
`-_artifactsLocation $(artifactsLocation) -_artifactsLocationSasToken (ConvertTo-SecureString '$(artifactsLocationSasToken)' -AsPlainText -Force)`

![image](https://user-images.githubusercontent.com/2350015/42233031-91291248-7ef0-11e8-9068-ac5c50e119c3.png)


This will then be picked up in the ARM template itself with the following MSDeploy step:

```
      "resources": [
        {
          "type": "Extensions",
          "name": "MSDeploy",
          "apiVersion": "2016-08-01",
          "properties": {
            "packageUri": "[concat(parameters('_artifactsLocation'), '/', parameters('PackageFileName'), parameters('_artifactsLocationSasToken'))]",
            "dbType": "None",
            "connectionString": "",
            "setParameters": {
              "IIS Web Application Name": "[variables('siteName')]"
            }
          },
          "dependsOn": [
            "[concat('Microsoft.Web/Sites/', variables('siteName'))]"
          ]
        }
```
Assuming:
_artifactsLocation: 'arm'
PackageFileName: 'Bot.zip'
_artifactsLocationSasToken: 'Token123'

As can be seen in the code above the expected outcome should be:
`arm/Bot.zipToken123`

The error message that's being given by azure in this case is:
```
{
  "status": "failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'failed'.",
    "details": [
      {
        "code": "Failed",
        "message": "Failed to download package.\r\nAppGallery Deploy Failed: 'System.AggregateException: One or more errors occurred. ---&amp;amp;amp;gt; System.Net.WebException: The remote server returned an error: (403) Forbidden.\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)\r\n   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)\r\n   --- End of inner exception stack trace ---\r\n   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\r\n   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)\r\n   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)\r\n   at Microsoft.Web.Deployment.WebApi.AppGalleryPackage.&amp;amp;amp;lt;Download&amp;amp;amp;gt;d__a.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Deployment.WebApi.AppGalleryPackage.&amp;amp;amp;lt;Download&amp;amp;amp;gt;d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Deployment.WebApi.DeploymentController.&amp;amp;amp;lt;DownloadPackageAndSettings&amp;amp;amp;gt;d__26.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Deployment.WebApi.DeploymentController.&amp;amp;amp;lt;DownloadAndDeployPackage&amp;amp;amp;gt;d__17.MoveNext()\r\n---&amp;amp;amp;gt; (Inner Exception #0) System.Net.WebException: The remote server returned an error: (403) Forbidden.\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)\r\n   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)&amp;amp;amp;lt;---\r\n'\r\nFailed to download package.\r\nAppGallery Deploy Failed: 'System.AggregateException: One or more errors occurred. ---&amp;amp;gt; System.Net.WebException: The remote server returned an error: (403) Forbidden.\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)\r\n   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)\r\n   --- End of inner exception stack trace ---\r\n   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\r\n   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)\r\n   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)\r\n   at Microsoft.Web.Deployment.WebApi.AppGalleryPackage.&amp;amp;lt;Download&amp;amp;gt;d__a.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Deployment.WebApi.AppGalleryPackage.&amp;amp;lt;Download&amp;amp;gt;d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Deployment.WebApi.DeploymentController.&amp;amp;lt;DownloadPackageAndSettings&amp;amp;gt;d__26.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Deployment.WebApi.DeploymentController.&amp;amp;lt;DownloadAndDeployPackage&amp;amp;gt;d__17.MoveNext()\r\n---&amp;amp;gt; (Inner Exception #0) System.Net.WebException: The remote server returned an error: (403) Forbidden.\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)\r\n   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)&amp;amp;lt;---\r\n'\r\nFailed to download package.\r\nAppGallery Deploy Failed: 'System.AggregateException: One or more errors occurred. ---&amp;gt; System.Net.WebException: The remote server returned an error: (403) Forbidden.\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)\r\n   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)\r\n   --- End of inner exception stack trace ---\r\n   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\r\n   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)\r\n   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)\r\n   at Microsoft.Web.Deployment.WebApi.AppGalleryPackage.&amp;lt;Download&amp;gt;d__a.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Deployment.WebApi.AppGalleryPackage.&amp;lt;Download&amp;gt;d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Deployment.WebApi.DeploymentController.&amp;lt;DownloadPackageAndSettings&amp;gt;d__26.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Deployment.WebApi.DeploymentController.&amp;lt;DownloadAndDeployPackage&amp;gt;d__17.MoveNext()\r\n---&amp;gt; (Inner Exception #0) System.Net.WebException: The remote server returned an error: (403) Forbidden.\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)\r\n   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)&amp;lt;---\r\n'\r\nFailed to download package.\r\nAppGallery Deploy Failed: 'System.AggregateException: One or more errors occurred. ---&gt; System.Net.WebException: The remote server returned an error: (403) Forbidden.\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)\r\n   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)\r\n   --- End of inner exception stack trace ---\r\n   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\r\n   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)\r\n   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)\r\n   at Microsoft.Web.Deployment.WebApi.AppGalleryPackage.&lt;Download&gt;d__a.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Deployment.WebApi.AppGalleryPackage.&lt;Download&gt;d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Deployment.WebApi.DeploymentController.&lt;DownloadPackageAndSettings&gt;d__26.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Deployment.WebApi.DeploymentController.&lt;DownloadAndDeployPackage&gt;d__17.MoveNext()\r\n---&gt; (Inner Exception #0) System.Net.WebException: The remote server returned an error: (403) Forbidden.\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)\r\n   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)&lt;---\r\n'"
      }
    ]
  }
}
```

This error message however does not give any insight into the actual problem that's happening. If you login to SCM and then browse to the MSDeploy logs (appManagerLog.xml) you'll find the actual cause of this issue:

```
  <entry time="2018-07-03T16:31:24.7146831Z" type="Message">
    <message>Downloading package path 'ds-avabot-arm-staging-production/DS_AvaBot.Functions.NetF.zip(ConvertTo-SecureString '' from blob 'https://dsavabotarmstaging.blob.core.windows.net'</message>
  </entry>
  <entry time="2018-07-03T16:31:24.7771931Z" type="Error">
    <message>Failed to download package.</message>
  </entry>
  <entry time="2018-07-03T16:31:24.7928015Z" type="Error">
    <message>AppGallery Deploy Failed: 'System.AggregateException: One or more errors occurred. ---&gt; System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
   at Microsoft.Web.Deployment.WebApi.AppGalleryPackage.&lt;Download&gt;d__a.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.Deployment.WebApi.AppGalleryPackage.&lt;Download&gt;d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.Deployment.WebApi.DeploymentController.&lt;DownloadPackageAndSettings&gt;d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.Deployment.WebApi.DeploymentController.&lt;DownloadAndDeployPackage&gt;d__17.MoveNext()
---&gt; (Inner Exception #0) System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)&lt;---
'</message>
  </entry>
</entries>
```

**Comment by devedse** [comment]
Solution was posted here:
#7622
