### ISSUE TITLE
dotnet restore fails on Linux Agent with System.ArgumentNullException

### ISSUE THREAD

**Issue by henning-krause** [Microsoft/vsts-tasks#5382]
I've successfully connected a Linux Build Agent to my On-Premise TFS (2017.2). Now, running a build with a "dotnet restore" command yields this error:

```
2017-09-20T16:23:07.0962570Z ##[section]Starting: dotnet restore
2017-09-20T16:23:07.1349260Z ==============================================================================
2017-09-20T16:23:07.1376520Z Task         : .NET Core
2017-09-20T16:23:07.1406070Z Description  : Build, test and publish using dotnet core command-line.
2017-09-20T16:23:07.1435880Z Version      : 1.0.1
2017-09-20T16:23:07.1462760Z Author       : Microsoft Corporation
2017-09-20T16:23:07.1489990Z Help         : [More Information](https://go.microsoft.com/fwlink/?linkid=832194)
2017-09-20T16:23:07.1517360Z ==============================================================================
2017-09-20T16:23:08.3899740Z [command]/usr/bin/dotnet restore /BuildAgent-Linux-1/_work/1/s/src/myProject/myProject.sln -v normal
2017-09-20T16:23:08.3933640Z System.ArgumentNullException: Value cannot be null.
2017-09-20T16:23:08.3961410Z Parameter name: path1
2017-09-20T16:23:08.3988800Z    at System.IO.Path.Combine(String path1, String path2)
2017-09-20T16:23:08.4018170Z    at Microsoft.DotNet.Configurer.CliFallbackFolderPathCalculator.get_DotnetUserProfileFolderPath()
2017-09-20T16:23:08.4047080Z    at Microsoft.DotNet.Configurer.FirstTimeUseNoticeSentinel..ctor(CliFallbackFolderPathCalculator cliFallbackFolderPathCalculator)
2017-09-20T16:23:08.4075690Z    at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
2017-09-20T16:23:08.4103580Z    at Microsoft.DotNet.Cli.Program.Main(String[] args)
2017-09-20T16:23:08.4347570Z ##[error]Error: /usr/bin/dotnet failed with return code: 1
2017-09-20T16:23:08.4447060Z ##[error]Dotnet command failed with non-zero exit code on the following projects : /BuildAgent-Linux-1/_work/1/s/src/myProject/myProject.sln
2017-09-20T16:23:08.4588000Z ##[section]Finishing: dotnet restore
```

I've installed the .net Core 2.0 SDK on the Build Agent. Using CentOS as OS on the machine.

I found this issue on the .net CLI project, which might be related: https://github.com/dotnet/cli/issues/2385.

Any ideas on how to fix this?

**Comment by henning-krause** [comment]
Okay, figured it out. I executed the `./svc.sh` as root. That user didn't have a HOME directory. 

I've now created a new user and installed the service using that account. The agent is now working.
