### ISSUE TITLE
Visual Studio Test task fails build/release if MSTest test is inconclusive

### ISSUE THREAD

**Issue by abatishchev** [Microsoft/vsts-tasks#5385]
I'm using the latest [MSTest.TestFramework from NuGet](https://www.nuget.org/packages/MSTest.TestFramework/) and inconclusive tests used to work differently: build/release would continue but have orange/warning status. Now it fails:

```
2017-09-15T18:59:24.5870660Z Failed   GetProgramDefinitionInfo_Should_Return_StatusCode_Ok_When_ProgramDefinition_Was_Found
2017-09-15T18:59:24.5870660Z Error Message:
2017-09-15T18:59:24.5870660Z    Assert.Inconclusive failed. Storage contains no program definitions
2017-09-15T18:59:24.5870660Z Stack Trace:
2017-09-15T18:59:24.5870660Z    at Microsoft.UPP.Calc.Rules.Api.FunctionalTests.Controllers.ProgramDefinitionInfoControllerTest.<GetProgramCode>d__3.MoveNext() in E:\agent_work\439\s\Api.FunctionalTests\Controllers\ProgramDefinitionInfoControllerTest.cs:line 59
2017-09-15T18:59:24.5870660Z --- End of stack trace from previous location where exception was thrown ---
2017-09-15T18:59:24.5870660Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-09-15T18:59:24.5870660Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-09-15T18:59:24.5870660Z    at Microsoft.UPP.Calc.Rules.Api.FunctionalTests.Controllers.ProgramDefinitionInfoControllerTest.<GetProgramDefinitionInfo_Should_Return_StatusCode_Ok_When_ProgramDefinition_Was_Found>d__1.MoveNext() in E:\agent_work\439\s\Api.FunctionalTests\Controllers\ProgramDefinitionInfoControllerTest.cs:line 28
2017-09-15T18:59:24.5870660Z --- End of stack trace from previous location where exception was thrown ---
2017-09-15T18:59:24.5870660Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-09-15T18:59:24.5870660Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-09-15T18:59:24.5870660Z    at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.ThreadOperations.ExecuteWithAbortSafety(Action action)

2017-09-15T18:59:26.7120723Z ##[warning]Vstest failed with error. Check logs for failures. There might be failed tests.
2017-09-15T18:59:26.7120723Z ##[error]Error: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe failed with return code: 1
2017-09-15T18:59:27.8058364Z ##[error]Vstest exited with return code: 2.
```

See [these logs](https://microsoft.visualstudio.com/defaultcollection/Universal%20Store/Universal%20Store%20Team/_apps/hub/ms.vss-releaseManagement-web.hub-explorer?definitionId=3456&releaseId=240002&_a=release-logs).

Was it a change in the MSTest framework or in the VSTS task?

**Comment by ShreyasRmsft** [comment]
Can you please point me to the latest build/release where the the build/release continued despite having inconclusive tests? This is so that i can get an estimate of the time frame where the behavior appeared to have changed and also have a look at the task version and mstest version used.

**Comment by abatishchev** [comment]
hi @ShreyasRmsft,
All releases to Prod failed here because inconclusive test fails the task thus the whole build/release: https://microsoft.visualstudio.com/defaultcollection/Universal%20Store/Universal%20Store%20Team/_apps/hub/ms.vss-releaseManagement-web.hub-explorer?definitionId=3456&_a=releases. This happens at least since 8/24 for me.
Or I can follow-up to devops_tools@microsoft.com.

**Comment by ShreyasRmsft** [comment]
@abatishchev What I meant was can you provide me the link to a release where the release did not fail due to inconclusive tests? ie. where the release was marked orange. 

Also can you run the tests manually (using Visual Studio) using the same version of   MSTest.TestFramework and share the .trx file with me?

Because I had a look at the .trx attached along with the failed releases and the 4 tests that failed have been marked as failed in the .trx file and the VsTest Task simply reports whatever the .trx file has.

Running it locally with the versions of MsTest you are currently using (latest) and the one used in the earlier releases that you said were marked orange and examining the .trx files should let you know that it was indeed a change in the MsTest framework.

**Comment by abatishchev** [comment]
I figured this out! This is a bug in MSTest, apparently already being filed here, see https://github.com/Microsoft/testfx/issues/249

Thanks for your help!

**Comment by abatishchev** [comment]
I figured this out! This is a bug in MSTest, apparently already being filed here: https://github.com/Microsoft/testfx/issues/249

Thanks for your help!
