### ISSUE TITLE
Task "Visual Studio Test Agent Deployment" failes

### ISSUE THREAD

**Issue by DeV1L** [Microsoft/vsts-tasks#5411]
Hi team,

I've started have an errors during release at the task "Deploy TestAgent on localhost".

```
Agent.OSVersion | 10.0.14393
Agent.Version | 2.123.0
```
<a href="https://ibb.co/dmSb8k"><img src="https://preview.ibb.co/kaPdM5/Capture_55.jpg" alt="Capture_55" border="0"></a>
The error is:

```
2017-09-22T08:29:10.7581040Z ****************************************************************
2017-09-22T08:29:10.7737296Z ##[debug]Leaving C:\vstsagent\pool\_work\_tasks\DeployVisualStudioTestAgent_52a38a6a-1517-41d7-96cc-73ee0c60d2b6\2.1.24\DeployTestAgent.ps1.
2017-09-22T08:29:10.7737296Z ##[debug]Error record:
2017-09-22T08:29:10.8049817Z ##[debug]Invoke-VstsTaskScript : Unable to find type [VstsTaskSdk.TerminationException].
2017-09-22T08:29:10.8049817Z ##[debug]At line:1 char:746
2017-09-22T08:29:10.8049817Z ##[debug]+ ... Continue' ; Invoke-VstsTaskScript -ScriptBlock ([scriptblock]::Create ...
2017-09-22T08:29:10.8049817Z ##[debug]+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2017-09-22T08:29:10.8049817Z ##[debug]    + CategoryInfo          : InvalidOperation: (VstsTaskSdk.TerminationException:TypeName) [Invoke-VstsTaskScript], R    untimeException
2017-09-22T08:29:10.8049817Z ##[debug]    + FullyQualifiedErrorId : TypeNotFound,Invoke-VstsTaskScript
2017-09-22T08:29:10.8049817Z ##[debug] 
2017-09-22T08:29:10.8049817Z ##[debug]Script stack trace:
2017-09-22T08:29:10.8049817Z ##[debug]at <ScriptBlock>, <No file>: line 18
2017-09-22T08:29:10.8049817Z ##[debug]at <ScriptBlock>, <No file>: line 1
2017-09-22T08:29:10.8206104Z ##[debug]Exception:
2017-09-22T08:29:10.8206104Z ##[debug]System.Management.Automation.RuntimeException: Unable to find type [VstsTaskSdk.TerminationException].
2017-09-22T08:29:10.8206104Z ##[debug]   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
2017-09-22T08:29:10.8206104Z ##[debug]   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
2017-09-22T08:29:10.8206104Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2017-09-22T08:29:10.8362341Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2017-09-22T08:29:10.8362341Z ##[debug]   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
2017-09-22T08:29:10.8362341Z ##[debug]   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
2017-09-22T08:29:10.8362341Z ##[debug]   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
2017-09-22T08:29:10.8362341Z ##[debug]   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
2017-09-22T08:29:10.8518604Z ##[debug]   at System.Management.Automation.CommandProcessorBase.Complete()
2017-09-22T08:29:10.8674872Z ##[error]Unable to find type [VstsTaskSdk.TerminationException].
2017-09-22T08:29:10.8674872Z ##[debug]Processed: ##vso[task.logissue type=error]Unable to find type [VstsTaskSdk.TerminationException].
2017-09-22T08:29:10.9299899Z ##[error]Exit code 1 returned from process: file name 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe', arguments '-NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". ([scriptblock]::Create('if (!$PSHOME) { $null = Get-Item -LiteralPath ''variable:PSHOME'' } else { Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Management\Microsoft.PowerShell.Management.psd1'')) ; Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Utility\Microsoft.PowerShell.Utility.psd1'')) }')) 2>&1 | ForEach-Object { Write-Verbose $_.Exception.Message -Verbose } ; Import-Module -Name 'C:\vstsagent\pool\_work\_tasks\DeployVisualStudioTestAgent_52a38a6a-1517-41d7-96cc-73ee0c60d2b6\2.1.24\ps_modules\VstsTaskSdk\VstsTaskSdk.psd1' -ArgumentList @{ NonInteractive = $true } -ErrorAction Stop ; $VerbosePreference = 'Continue' ; $DebugPreference = 'Continue' ; Invoke-VstsTaskScript -ScriptBlock ([scriptblock]::Create('. ''C:\vstsagent\pool\_work\_tasks\DeployVisualStudioTestAgent_52a38a6a-1517-41d7-96cc-73ee0c60d2b6\2.1.24\DeployTestAgent.ps1'''))"'.
2017-09-22T08:29:10.9299899Z ##[debug]Microsoft.VisualStudio.Services.Agent.ProcessExitCodeException: Exit code 1 returned from process: file name 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe', arguments '-NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". ([scriptblock]::Create('if (!$PSHOME) { $null = Get-Item -LiteralPath ''variable:PSHOME'' } else { Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Management\Microsoft.PowerShell.Management.psd1'')) ; Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Utility\Microsoft.PowerShell.Utility.psd1'')) }')) 2>&1 | ForEach-Object { Write-Verbose $_.Exception.Message -Verbose } ; Import-Module -Name 'C:\vstsagent\pool\_work\_tasks\DeployVisualStudioTestAgent_52a38a6a-1517-41d7-96cc-73ee0c60d2b6\2.1.24\ps_modules\VstsTaskSdk\VstsTaskSdk.psd1' -ArgumentList @{ NonInteractive = $true } -ErrorAction Stop ; $VerbosePreference = 'Continue' ; $DebugPreference = 'Continue' ; Invoke-VstsTaskScript -ScriptBlock ([scriptblock]::Create('. ''C:\vstsagent\pool\_work\_tasks\DeployVisualStudioTestAgent_52a38a6a-1517-41d7-96cc-73ee0c60d2b6\2.1.24\DeployTestAgent.ps1'''))"'.
   at Microsoft.VisualStudio.Services.Agent.ProcessInvoker.<ExecuteAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.PowerShell3Handler.<RunAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.<RunAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.<RunStepAsync>d__1.MoveNext()
2017-09-22T08:29:10.9299899Z ##[section]Finishing: Deploy TestAgent on localhost
```

**Comment by kaadhina** [comment]
1. Can you please share the full debug logs?
2. Is this a consistent repro?
3. Can you try on a different agent/hosted agent ?

**Comment by DeV1L** [comment]
I've resetup vsts agent already. Issue can be closed.

**Comment by Jorje65** [comment]
Hi @DeV1L ....I'm experiencing similar issues when the 'Run on agent' task fails while deploying on the VSTS release pipeline. It throws similar errors as the ones in your error logs in the screenshot above. How were you able to resolve this?
