### ISSUE TITLE
VSTS keep task failing to authorize

### ISSUE THREAD

**Issue by jesomm** [Microsoft/vsts-tasks#5608]
## Environment

- VSTS
   - account name: [outlookweb](https://outlookweb.visualstudio.com/)
   - project name:  [outlook web](https://outlookweb.visualstudio.com/Outlook%20Web/)
   - build:
      - [here is a draft that fails](https://outlookweb.visualstudio.com/Outlook%20Web/_build/index?context=allDefinitions&path=%5CPeople&definitionId=264&_a=completed)
      - [here is an example failing build with debug params on](https://outlookweb.visualstudio.com/DefaultCollection/Outlook%20Web/_build/index?buildId=28855&_a=summary)

- Agent - Private: 
   - OS: Windows Server 2012 R2
   - agent version:  2.117.1
   - also if matters vsts keep task: 1.4.2

## Issue Description

VSTS Keep task is failing with unauthorized error.

### Error logs

```
2017-10-10T22:36:06.3946644Z ##[error]System.Net.WebException: The remote server returned an error: (401) Unauthorized.
2017-10-10T22:36:06.3946644Z ##[debug]Processed: ##vso[task.logissue type=error;]System.Net.WebException: The remote server returned an error: (401) Unauthorized.
2017-10-10T22:36:06.3946644Z    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
2017-10-10T22:36:06.3946644Z    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
2017-10-10T22:36:06.3946644Z RESULT: 
2017-10-10T22:36:06.3946644Z ##[error]PowerShell script completed with 1 errors.
```

calling params:
```
2017-10-10T23:14:01.8070851Z ##[debug]PowerShellHandler.Execute - Add inputParameters
2017-10-10T23:14:01.8070851Z ##[debug]PowerShellHandler.Execute - AddParameter(targetbranch=master)
2017-10-10T23:14:01.8070851Z ##[debug]PowerShellHandler.Execute - AddParameter(debugonly=false)
```

**Comment by jesomm** [comment]
On further investigation, we found the issue was inconsistent options across build definitions. Some of them had the use of OAuth token enabled, and some did not. The ones that did not were the ones vsts-keep was failing to authorize against..

I wonder if it might be worth VSTS tasks adding some special handling for this error to add a recommendation to check this OAuth setting?
