### ISSUE TITLE
Service Fabric Application Deployment Task fails because of missing default value 

### ISSUE THREAD

**Issue by burndeal** [Microsoft/vsts-tasks#5633]
## Environment
- Server - VSTS    
- Agent - VS2017 Hosted

## Issue Description
Service Fabric Application Deployment v.1.4.1 fails with this error (the full error is below):

`##[error]Exception calling "Parse" with "1" argument(s): "String was not recognized as a valid Boolean."`

Further analysis in debug mode points to line 36 in deploy.ps1:
`$configureDockerSettings = [System.Boolean]::Parse((Get-VstsInput -Name configureDockerSettings))`

It seems that the default value isn't set in my build definition, which I created yesterday with version 1.3.11.  A workaround is to make a change to the Build Definition and save it, which adds these params to the build definition:

`"configureDockerSettings": "false",`
`"registryCredentials": "AzureResourceManagerEndpoint",`
`"dockerRegistryEndpoint": "",`
`"azureSubscriptionEndpoint": "",`
`"registryUserName": "",`
`"registryPassword": "",`
`"passwordEncrypted": "true"`

### Error logs

2017-10-12T19:49:28.9401893Z ##[debug]Leaving D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.4.1\deploy.ps1.
2017-10-12T19:49:28.9842309Z ##[debug]Caught exception from task script.
2017-10-12T19:49:28.9872083Z ##[debug]Error record:
2017-10-12T19:49:29.0392219Z ##[debug]D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.4.1\deploy.ps1 : Exception calling "Parse" with "1" argument(s): "String was not recognized as a valid Boolean."
2017-10-12T19:49:29.0402233Z ##[debug]At line:1 char:1
2017-10-12T19:49:29.0412228Z ##[debug]+ . 'd:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c ...
2017-10-12T19:49:29.0422233Z ##[debug]+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2017-10-12T19:49:29.0432231Z ##[debug]    + CategoryInfo          : NotSpecified: (:) [deploy.ps1], MethodInvocationException
2017-10-12T19:49:29.0442235Z ##[debug]    + FullyQualifiedErrorId : FormatException,deploy.ps1
2017-10-12T19:49:29.0462233Z ##[debug] 
2017-10-12T19:49:29.0902339Z ##[debug]Script stack trace:
2017-10-12T19:49:29.0942351Z ##[debug]at <ScriptBlock>, D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.4.1\deploy.ps1: line 36
2017-10-12T19:49:29.0942351Z ##[debug]at <ScriptBlock>, <No file>: line 1
2017-10-12T19:49:29.0962367Z ##[debug]at <ScriptBlock>, <No file>: line 22
2017-10-12T19:49:29.0972368Z ##[debug]at <ScriptBlock>, <No file>: line 18
2017-10-12T19:49:29.0982378Z ##[debug]at <ScriptBlock>, <No file>: line 1
2017-10-12T19:49:29.0992386Z ##[debug]Exception:
2017-10-12T19:49:29.1032431Z ##[debug]System.Management.Automation.MethodInvocationException: Exception calling "Parse" with "1" argument(s): "String was not recognized as a valid Boolean." ---> System.FormatException: String was not recognized as a valid Boolean.
2017-10-12T19:49:29.1042402Z ##[debug]   at System.Boolean.Parse(String value)
2017-10-12T19:49:29.1052400Z ##[debug]   at CallSite.Target(Closure , CallSite , Type , Object )
2017-10-12T19:49:29.1062404Z ##[debug]   --- End of inner exception stack trace ---
2017-10-12T19:49:29.1072413Z ##[debug]   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
2017-10-12T19:49:29.1082409Z ##[debug]   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
2017-10-12T19:49:29.1092412Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2017-10-12T19:49:29.1102416Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2017-10-12T19:49:29.1112425Z ##[debug]   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
2017-10-12T19:49:29.1122421Z ##[debug]   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
2017-10-12T19:49:29.1132428Z ##[debug]   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
2017-10-12T19:49:29.1142426Z ##[debug]   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
2017-10-12T19:49:29.1152438Z ##[debug]   at System.Management.Automation.CommandProcessorBase.Complete()
2017-10-12T19:49:29.1372485Z ##[error]Exception calling "Parse" with "1" argument(s): "String was not recognized as a valid Boolean."

**Comment by Kwal** [comment]
Can confirm seeing the same issue

**Comment by iamkoch** [comment]
We are seeing the same issue as well.

**Comment by bishal-pdMSFT** [comment]
Thanks for reporting it. We are trying to hot-fix it.

**Comment by KasperNagel** [comment]
Thanks - Same issue for all services here ..

**Comment by PrasadSudama** [comment]
has the issue been fixed? still not working for us

**Comment by bishal-pdMSFT** [comment]
No it has not been fixed yet. While we are in the progress, you can unblock yourself by using the workaround in the original post - Check and uncheck "Configure docker settings" check box under "Docker settings" group in release/build definition

**Comment by Retro-Scrat** [comment]
Can confirm seeing the same issue

**Comment by karthik-2884** [comment]
Unfortunately the UI does not allow you to save if you simply check and uncheck and you cant save with checked option without providing docker details. However simply making any edit to your release definition and saving it seems to do the trick.

If you have multiple release definitions, you can use [VSTS Release Definition APIs](https://www.visualstudio.com/en-us/docs/integrate/api/rm/definitions) to set the configureDockerSettings to false for the corresponding task inputs. You can find this under environment->deployPhases->workflowTasks->inputs

**Comment by bishal-pdMSFT** [comment]
The fix has been rolled out

**Comment by iamkoch** [comment]
Could you link to the specific commit?

**Comment by bishal-pdMSFT** [comment]
Here is the [commit](https://github.com/Microsoft/vsts-tasks/commit/f3094cd48e5fb584bf03e3e5af385622ad779fe3)
