### ISSUE TITLE
isolation and/or non-parallel mode does not appear to be working properly

### ISSUE THREAD

**Issue by santoorman** [Microsoft/vsts-tasks#5684]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - VSTS or TFS on-premises?
    TFS on premises
    - If using TFS on-premises, provide the version: 
     15.117.26714.0

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 
Windows server 2012 R2

## Issue Description

[Include task name(s), screenshots and any other relevant details]
we run functional tests at night and we have some static methods that are conflicting.  we use SQL CE and we create a temp database file and then execute sql scripts.

The tests run at the same time and some of the static objects are crossing over.

Unit Test 1 - creates a temp folder and temp db w/ unique GUID (cc4b3035-c4d0-48c4-92f6-15ccf3307cd7 in the log file below)
- it does a bunch of stuff
- at the end it cleans up by deleting the database

Unit Test 2 - creates its own temp folder & db w/ unique GUID (22842bcb-621a-46f5-84c4-df82b22a7dca in the log file below)
- it is doing it's stuff, but then a db query uses the db path from Unit Test 1 and throws exception cos Unit Test 1 must have completed and deleted it's db:

System.Data.SqlServerCe.SqlCeException: The path is not valid. Check the directory for the database. [ Path = D:\agent1\_work\_temp\**cc4b3035-c4d0-48c4-92f6-15ccf3307cd7**\DB.sdf ]

set to run in isolation on server and no parallel:
https://imgur.com/0QXdSG8
also did this in RunSettings but don't think that does much:
	    <MaxCpuCount>0</MaxCpuCount>

### Error logs
log file is 186 MB will not attach here.  here is relevant info: (if you really want it let me know can zip it up etc.)

Unit Test #1 (this time it failed for an unrelated reason)
2017-10-20T10:08:11.6808584Z Failed   ImportDefaultMixedAnimalHPTest
2017-10-20T10:08:11.6808584Z Error Message:
2017-10-20T10:08:11.6808584Z    Test method Cuattro.Tests.Misc.DatabaseFunctionalTests.CreateDatabaseTests.ImportDefaultMixedAnimalHPTest threw exception: 
2017-10-20T10:08:11.6808584Z System.Exception: ImportWarningAttentionRequest WarningImportingHangingProtocolItem
2017-10-20T10:08:11.6808584Z Stack Trace:
2017-10-20T10:08:11.6808584Z     at Cuattro.Tests.Misc.DatabaseFunctionalTests.CreateDatabaseTests.ImportDefaultHPCore(HangingProtocolImportFile hangingProtocolImportFile) in D:\agent1\_work\2\s\Dev\20170305_MD_4.4\Tests\Misc\DatabaseFunctionalTests\CreateDatabaseTests.cs:line 123
2017-10-20T10:08:11.6808584Z    at Cuattro.Tests.Misc.DatabaseFunctionalTests.CreateDatabaseTests.ImportDefaultMixedAnimalHPTest() in D:\agent1\_work\2\s\Dev\20170305_MD_4.4\Tests\Misc\DatabaseFunctionalTests\CreateDatabaseTests.cs:line 57

2017-10-20T10:08:13.9621426Z Debug Trace:
2017-10-20T10:08:13.9621426Z Cuattro.Tests.Misc.DatabaseFunctionalTests.CreateDatabaseTests: 2017-10-20 05:02:42,347 DEBUG (11)- ServiceLocatorHelper.CreateAndInitContainer()
2017-10-20T10:08:13.9621426Z    Cuattro.Common.IOHelper: 2017-10-20 05:02:53,629 DEBUG (11)- GetTempFolder: D:\agent1\_work\_temp\**cc4b3035-c4d0-48c4-92f6-15ccf3307cd7**
2017-10-20T10:08:13.9621426Z    Created temp folder: D:\agent1\_work\_temp\**cc4b3035-c4d0-48c4-92f6-15ccf3307cd7**, dir exists: True

...
2017-10-20T10:08:45.5563686Z    Cuattro.Misc.SqlCe.SqlCeDatabaseAdmin: 2017-10-20 05:08:04,305 DEBUG (11)- Shutdown
2017-10-20T10:08:45.5563686Z    Cuattro.Misc.SqlCe.ExtendedSqlCeDatabase: 2017-10-20 05:08:04,305 DEBUG (11)- CloseSharedConnection
2017-10-20T10:08:45.5563686Z    Cuattro.Tests.Misc.DatabaseFunctionalTests.ServiceLocatorHelper: 2017-10-20 05:08:04,368 DEBUG (11)- Deleting temp folder from appContext: D:\agent1\_work\_temp\**cc4b3035-c4d0-48c4-92f6-15ccf3307cd7**

Unit Test #2 that fails because of missing file:

2017-10-20T10:08:45.5563686Z Failed   ImportDefaultHumanHPTest
2017-10-20T10:08:45.5563686Z Error Message:
2017-10-20T10:08:45.5563686Z    Test method Cuattro.Tests.Misc.DatabaseFunctionalTests.CreateDatabaseTests.ImportDefaultHumanHPTest threw exception: 
2017-10-20T10:08:45.5563686Z System.Data.SqlServerCe.SqlCeException: The path is not valid. Check the directory for the database. [ Path = D:\agent1\_work\_temp\**cc4b3035-c4d0-48c4-92f6-15ccf3307cd7**\DB.sdf ]

2017-10-20T10:08:45.5563686Z Debug Trace:
2017-10-20T10:08:45.5563686Z Cuattro.Tests.Misc.DatabaseFunctionalTests.CreateDatabaseTests: 2017-10-20 05:08:11,665 DEBUG (11)- ServiceLocatorHelper.CreateAndInitContainer()
2017-10-20T10:08:45.5563686Z    Cuattro.Common.IOHelper: 2017-10-20 05:08:11,665 DEBUG (11)- GetTempFolder: D:\agent1\_work\_temp\**22842bcb-621a-46f5-84c4-df82b22a7dca**
2017-10-20T10:08:45.5563686Z    Created temp folder: D:\agent1\_work\_temp\**22842bcb-621a-46f5-84c4-df82b22a7dca**, dir exists: True

**Comment by nigurr** [comment]
Hi,

Can  you please describe which task is being used to run the test and issue details?

**Comment by santoorman** [comment]
dont quite understand the question.. using Test Assemblies v2.x .... ?

**Comment by nigurr** [comment]
@santoorman Can you please try running these tests using "vstest.console.exe /isolation" and check if they are passing. You can report test platform related issues in http://github.com/microsoft/vstest

**Comment by prawalagarwal** [comment]
@santoorman Just to be clear, /isolation does not run individual tests in isolation. It just starts the test process as a different process (outside vstest.console). If your tests are accessing each others data, then you can still encounter this issue.

**Comment by prawalagarwal** [comment]
Closing this. Please feel free to reopen if you have further questions or your issue is not resolved.

**Comment by santoorman** [comment]
OK but why isn't the non-parallel working properly?

**Comment by prawalagarwal** [comment]
Please reach out at devops_tools[at]microsoft[dot]com with logs of your run. Thanks.
