### ISSUE TITLE
Git fetch failed with exit code: 128

### ISSUE THREAD

**Issue by vinaysandela** [Microsoft/vsts-tasks#5698]
Getting Error due to Unable o access the Repository. Can someone help in fixing the issue. 

Thanks

Error Logs: 
2017-10-24T17:47:05.6498588Z ##[section]Starting: Get Sources
2017-10-24T17:47:05.6654588Z ##[debug]Primary repository: Physician Insight. repository type: TfsGit
2017-10-24T17:47:05.6654588Z ##[debug]Preparing build directory.
2017-10-24T17:47:05.7278588Z ##[debug]Delete existing artifacts directory: 'E:\nadcwpapptfs02-agentV2-04\_work\14\a'
2017-10-24T17:47:05.7278588Z ##[debug]Deleting artifacts directory: 'E:\nadcwpapptfs02-agentV2-04\_work\14\a'
2017-10-24T17:47:06.0398588Z ##[debug]Creating artifacts directory: 'E:\nadcwpapptfs02-agentV2-04\_work\14\a'
2017-10-24T17:47:06.0398588Z ##[debug]Delete existing test results directory: 'E:\nadcwpapptfs02-agentV2-04\_work\14\TestResults'
2017-10-24T17:47:06.0398588Z ##[debug]Deleting test results directory: 'E:\nadcwpapptfs02-agentV2-04\_work\14\TestResults'
2017-10-24T17:47:06.0398588Z ##[debug]Creating test results directory: 'E:\nadcwpapptfs02-agentV2-04\_work\14\TestResults'
2017-10-24T17:47:06.0398588Z ##[debug]Set build variables.
2017-10-24T17:47:06.0398588Z ##[debug]Sync source for endpoint: Physician Insight
2017-10-24T17:47:06.0866588Z Syncing repository: Physician Insight (TfsGit)
2017-10-24T17:47:06.0866588Z Prepending Path environment variable with directory containing 'git.exe'.
2017-10-24T17:47:06.0866588Z ##[debug]Path: 'E:\nadcwpapptfs02-agentV2-04\externals\git\cmd;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\HP\NCU;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\VSShell\Common7\IDE\;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;%USERPROFILE%\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;e:\docker;C:\Program Files\Universal\USap\bin\;C:\PROGRA~1\IBM\IBMDAT~1\BIN;C:\Windows\System32\WindowsPowerShell\v1.0\;c:\Users\ParaSvcDevOpsCet\AppData\Roaming\npm;E:\nadcwpapptfs02-agentV2-04\bin;E:\nadcwpapptfs02-agentV2-04\bin'
2017-10-24T17:47:06.1022588Z ##[debug]Get git version.
2017-10-24T17:47:06.1022588Z ##[command]git version
2017-10-24T17:47:06.2582588Z ##[debug]git version output: git version 2.10.0.windows.1
2017-10-24T17:47:06.2738588Z ##[debug]Detect git version: 2.10.0.
2017-10-24T17:47:06.2738588Z ##[debug]Set git useragent to: git/2.10.0 (vsts-agent-git/2.112.0).
2017-10-24T17:47:06.2738588Z ##[debug]Checking if the repo on E:\nadcwpapptfs02-agentV2-04\_work\14\s matches the expected repository origin URL. expected Url: http://devconnecttfs.hca.corpad.net:8080/tfs/BPG%20Enterprise%20Collection/_git/Physician%20Insight
2017-10-24T17:47:06.2738588Z ##[debug]Inspect remote.origin.url for repository under E:\nadcwpapptfs02-agentV2-04\_work\14\s
2017-10-24T17:47:06.2738588Z ##[command]git config --get remote.origin.url
2017-10-24T17:47:06.3206588Z ##[debug]Get remote origin fetch url from git config: http://devconnecttfs.hca.corpad.net:8080/tfs/BPG%20Enterprise%20Collection/_git/Physician%20Insight
2017-10-24T17:47:06.3206588Z ##[debug]Repository remote origin fetch url is http://devconnecttfs.hca.corpad.net:8080/tfs/BPG Enterprise Collection/_git/Physician Insight
2017-10-24T17:47:06.3362588Z ##[debug]URLs match.
2017-10-24T17:47:06.3362588Z ##[debug]Delete untracked files/folders for repository at E:\nadcwpapptfs02-agentV2-04\_work\14\s.
2017-10-24T17:47:06.3362588Z ##[command]git clean -fdx
2017-10-24T17:47:16.8194588Z ##[debug]Undo any changes to tracked files in the working tree for repository at E:\nadcwpapptfs02-agentV2-04\_work\14\s.
2017-10-24T17:47:16.8194588Z ##[command]git reset --hard HEAD
2017-10-24T17:47:19.5338588Z HEAD is now at eeb1405 Revert "Remove local build files from Git repository and add them to git ignore"
2017-10-24T17:47:19.5338588Z ##[debug]Disable git auto garbage collection.
2017-10-24T17:47:19.5338588Z ##[command]git config gc.auto 0
2017-10-24T17:47:19.5962588Z ##[debug]Checking git config http.http://devconnecttfs.hca.corpad.net:8080/tfs/BPG%20Enterprise%20Collection/_git/Physician%20Insight.extraheader exist or not
2017-10-24T17:47:19.5962588Z ##[command]git config --get-all http.http://devconnecttfs.hca.corpad.net:8080/tfs/BPG%20Enterprise%20Collection/_git/Physician%20Insight.extraheader
2017-10-24T17:47:19.6430588Z ##[debug]Checking git config http.proxy exist or not
2017-10-24T17:47:19.6430588Z ##[command]git config --get-all http.proxy
2017-10-24T17:47:19.6898588Z ##[debug]Remove any proxy setting from git config.
2017-10-24T17:47:19.6898588Z ##[debug]Unset git config --unset-all http.proxy
2017-10-24T17:47:19.6898588Z ##[command]git config --unset-all http.proxy
**2017-10-24T17:47:19.7366588Z ##[warning]Unable to remove "http.proxy" from the git config. To remove the credential, execute "git config --unset-all http.proxy" from the repository root "http.proxy".
2017-10-24T17:47:19.7522588Z ##[debug]Fetch git repository at: E:\nadcwpapptfs02-agentV2-04\_work\14\s remote: origin.**
2017-10-24T17:47:19.7522588Z ##[command]git -c http.extraheader="AUTHORIZATION: bearer ********" fetch --tags --prune --progress origin
2017-10-24T17:47:19.9082588Z fatal: unable to access 'http://devconnecttfs.hca.corpad.net:8080/tfs/BPG%20Enterprise%20Collection/_git/Physician%20Insight/': The requested URL returned error: 407
**2017-10-24T17:47:19.9082588Z ##[error]Git fetch failed with exit code: 128**
2017-10-24T17:47:19.9082588Z ##[debug]System.InvalidOperationException: Git fetch failed with exit code: 128
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.GitSourceProvider.<GetSourceAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.BuildJobExtension.<PrepareAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.JobExtensionRunner.<RunAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.<RunAsync>d__0.MoveNext()
2017-10-24T17:47:19.9238588Z ##[section]Finishing: Get Sources

**Comment by scottboehmer** [comment]
The http 407 error in that log indicates a proxy authentication issue between your agent and TFS. This page should be able to help with configuring your agent to use the proxy server: https://docs.microsoft.com/en-us/vsts/build-release/actions/agents/_shared/v2/qa-proxy-unix

**Comment by vinaysandela** [comment]
This is indeed a access issue and resolved it by adding permissions to the service account that I am using. 
Thanks
