### ISSUE TITLE
jenkins endpoint verification gives false positive on untrusted SSL cert

### ISSUE THREAD

**Issue by morgwai** [Microsoft/vsts-tasks#5806]
vsts fails to download artifacts from jenkins

## Environment
Server: VSTS
account name: morgwai@2clicksolutions.onmicrosoft.com
team project name: 2CS.Goce
release definition name: jenkins-release
release id: Release-5

## Issue Description

I've successfully created jenkins service endpoint definition (morgwai@devmaster.saigon) and verified that the connection works:
![tfs-endpoint](https://user-images.githubusercontent.com/1413602/32578059-709eda40-c50e-11e7-9f99-2bb36befa2b8.png)

Then I've successfully created a release definition and while defining its tasks I was able to browse the artificats downloaded from jenkins successfully:
![tfs-browse](https://user-images.githubusercontent.com/1413602/32577592-055194ae-c50d-11e7-8a57-4d9c852af410.png)

yet when I attempted to make a release the download of the artifacts failed with error message "A security error occurred" (log attached).

### Error logs

> 2017-11-08T21:55:43.2927277Z ##[section]Starting: Download Artifacts
2017-11-08T21:55:44.6547547Z Downloading artifact
2017-11-08T21:55:44.6617545Z Creating artifacts directory: d:\a\r1\a
2017-11-08T21:55:44.6637544Z Created artifacts directory: d:\a\r1\a
2017-11-08T21:55:44.6647549Z Starting artifacts download...
2017-11-08T21:55:44.6707496Z Downloading linked artifact goce@jenkins@devmaster of type Jenkins...
2017-11-08T21:55:44.6767489Z Ensuring artifact folder d:\a\r1\a\goce@jenkins@devmaster exists and is clean.
2017-11-08T21:55:44.6807490Z Received Jenkins Artifact Details
2017-11-08T21:55:44.6807490Z Job Name: GOCE
2017-11-08T21:55:44.6807490Z BuildId: 58
2017-11-08T21:55:47.3983843Z An error occurred during download: System.AggregateException: One or more errors occurred. (An error occurred while sending the request.) ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: A security error occurred
   at System.Net.Http.WinHttpRequestCallback.OnRequestSendingRequest(WinHttpRequestState state)
   at System.Net.Http.WinHttpRequestCallback.RequestCallback(IntPtr handle, WinHttpRequestState state, UInt32 internetStatus, IntPtr statusInformation, UInt32 statusInformationLength)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Release.Artifacts.GenericHttpClient.<GetAsync>d__0.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.VisualStudio.Services.Agent.Worker.Release.Artifacts.JenkinsArtifact.IsValidBuild(IGenericHttpClient client, JenkinsArtifactDetails jenkinsDetails)
   at Microsoft.VisualStudio.Services.Agent.Worker.Release.Artifacts.JenkinsArtifact.<DownloadAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Release.ReleaseJobExtension.<>c__DisplayClass34_2.<<DownloadArtifacts>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Release.RetryExecutor.<ExecuteAsync>d__20.MoveNext()
---> (Inner Exception #0) System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: A security error occurred
   at System.Net.Http.WinHttpRequestCallback.OnRequestSendingRequest(WinHttpRequestState state)
   at System.Net.Http.WinHttpRequestCallback.RequestCallback(IntPtr handle, WinHttpRequestState state, UInt32 internetStatus, IntPtr statusInformation, UInt32 statusInformationLength)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Release.Artifacts.GenericHttpClient.<GetAsync>d__0.MoveNext()<---

**Comment by morgwai** [comment]
checking "accept untrusted SSL certificates" solved the issue. This means that the endpoint verification gave a false positive: I've updated the title.
Also, it means that lets-encrypt CA certs should be installed on vsts.

**Comment by morgwai** [comment]
hmm, it puzzles me that I was still able to browse the jenkins artifacts when creating tasks while the option "accept untrusted SSL certificates" was unchecked... it seems that some parts vsts DO recognize letsencrypt certs while others don't...

**Comment by kasubram** [comment]
I couldn't reproduce this, I configured a Jenkins server with self signed certifacte.

When untrusted SSL certificate option is unchecked it failed with an error saying could not make trust relationship to the server.
![image](https://user-images.githubusercontent.com/17177298/34377495-4164c2b0-eb17-11e7-93b4-b4ae2aa96f31.png)

It passed after enabling the option,
![image](https://user-images.githubusercontent.com/17177298/34377518-67d3ba78-eb17-11e7-8e40-476e4d3fa3e8.png)

However, there is a possibility that underlying ServicePointManager caches the WebRequest's connection. Only for SSL connection caching happens though. Did you first enable the checkbox and validate and disabled again? 

Could you give it another try? uncheck the option and validate again and see if it fails now. If its not failing please add port to your url explicitly like https://servername:**443**/jenkins/ so that url looks different than the previous url.

**Comment by GitHubSriramB** [comment]
@morgwai - if you are able to repro this issue & the above workaround suggested doesn't help, pl. reactivate the issue.
