### ISSUE TITLE
jenkins service hook "pull request merge attempted" should not trigger on completed pull requests

### ISSUE THREAD

**Issue by morgwai** [Microsoft/vsts-tasks#5813]
## Environment
Server: VSTS
account name: morgwai@2clicksolutions.onmicrosoft.com
team project name: 2CS.Goce

## Issue Description

At the moment, when "merge result" is set to "successful" this service hook is triggering a build under 3 conditions:
- pull request created (good)
- pull request updated with new commits pushed to the source branch (good)
- pull request completed and merge commit pushed to the target branch (bad)

This last one is basically redundant to "code pushed" hook and additionally confuses jenkins tfs plugin as it tries to update build status of a completed pull request (see below).

Additionally the name of this hook is quite misleading: it should be something like "pull request modified"

### Error logs

ERROR: Error while trying to update pending status in TFS/Team Services
java.io.IOException: HTTP 403 (Forbidden): {"$id":"1","innerException":null,"message":"The requested pull request status cannot be updated as it requires an active pull request.","typeName":"Microsoft.TeamFoundation.Git.Server.GitPullRequestStatusNotEditableException, Microsoft.TeamFoundation.Git.Server","typeKey":"GitPullRequestStatusNotEditableException","errorCode":0,"eventId":3000}
	at hudson.plugins.tfs.util.TeamRestClient.innerRequest(TeamRestClient.java:164)
	at hudson.plugins.tfs.util.TeamRestClient.request(TeamRestClient.java:123)
	at hudson.plugins.tfs.util.TeamRestClient.request(TeamRestClient.java:84)
	at hudson.plugins.tfs.util.TeamRestClient.addPullRequestStatus(TeamRestClient.java:292)
	at hudson.plugins.tfs.util.TeamStatus.createFromRun(TeamStatus.java:69)
	at hudson.plugins.tfs.TeamPendingStatusBuildStep.perform(TeamPendingStatusBuildStep.java:44)
	at hudson.plugins.tfs.TeamPendingStatusBuildStep.perform(TeamPendingStatusBuildStep.java:38)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)

**Comment by jpricketMSFT** [comment]
This bug isn't related to the jenkins tasks so this isn't a great spot for it. But we did see it. I will file this bug internally so that we can track it and try to update this issue with the progress.

**Comment by joshmgross** [comment]
Closing this issue to clean up the backlog. Reopen this if the issue presents itself again.
