### ISSUE TITLE
CI using TFS vNext from GIT Repo. Getting Error

### ISSUE THREAD

**Issue by vinaysandela** [Microsoft/vsts-tasks#5905]
HI, I am configuring CI Build on TFS using vNext. I am using GIT Repositoy. 
It is the first time I am Building with the GIT Repo, so far using TFS. 

I Created Build Definition, but its failing at the first step in **Getting Sources**. Getting the following Error- 

**Error Log:**
2017-11-20T19:32:37.6525390Z ##[section]Starting: Get Sources
2017-11-20T19:32:37.6681390Z ##[debug]Primary repository: TestKITT. repository type: TfsGit
2017-11-20T19:32:37.6681390Z ##[debug]Preparing build directory.
2017-11-20T19:32:37.7305390Z ##[debug]Delete existing artifacts directory: 'C:\Installs\New folder\vsts-agent-win7-x64-2.112.0 (6)\_work\3\a'
2017-11-20T19:32:37.7305390Z ##[debug]Deleting artifacts directory: 'C:\Installs\New folder\vsts-agent-win7-x64-2.112.0 (6)\_work\3\a'
2017-11-20T19:32:37.8085390Z ##[debug]Creating artifacts directory: 'C:\Installs\New folder\vsts-agent-win7-x64-2.112.0 (6)\_work\3\a'
2017-11-20T19:32:37.8085390Z ##[debug]Delete existing test results directory: 'C:\Installs\New folder\vsts-agent-win7-x64-2.112.0 (6)\_work\3\TestResults'
2017-11-20T19:32:37.8085390Z ##[debug]Deleting test results directory: 'C:\Installs\New folder\vsts-agent-win7-x64-2.112.0 (6)\_work\3\TestResults'
2017-11-20T19:32:37.8085390Z ##[debug]Creating test results directory: 'C:\Installs\New folder\vsts-agent-win7-x64-2.112.0 (6)\_work\3\TestResults'
2017-11-20T19:32:37.8085390Z ##[debug]Set build variables.
2017-11-20T19:32:37.8085390Z ##[debug]Sync source for endpoint: TestKITT
2017-11-20T19:32:37.8553390Z Syncing repository: TestKITT (TfsGit)
2017-11-20T19:32:37.8553390Z Prepending Path environment variable with directory containing 'git.exe'.
2017-11-20T19:32:37.8553390Z ##[debug]Path: 'C:\Installs\New folder\vsts-agent-win7-x64-2.112.0 (6)\externals\git\cmd;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\HP\NCU;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\VSShell\Common7\IDE\;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;%USERPROFILE%\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;e:\docker;C:\Program Files\Universal\USap\bin\;C:\PROGRA~1\IBM\IBMDAT~1\BIN;C:\Windows\System32\WindowsPowerShell\v1.0\;c:\Users\ParaSvcDevOpsCet\AppData\Roaming\npm;C:\Installs\New folder\vsts-agent-win7-x64-2.112.0 (6)\bin;C:\Installs\New folder\vsts-agent-win7-x64-2.112.0 (6)\bin'
2017-11-20T19:32:37.8553390Z ##[debug]Get git version.
2017-11-20T19:32:37.8709390Z ##[command]git version
2017-11-20T19:32:38.5105390Z ##[debug]git version output: git version 2.10.0.windows.1
2017-11-20T19:32:38.5105390Z ##[debug]Detect git version: 2.10.0.
2017-11-20T19:32:38.5105390Z ##[debug]Set git useragent to: git/2.10.0 (vsts-agent-git/2.112.0).
2017-11-20T19:32:38.5105390Z ##[debug]Checking if the repo on C:\Installs\New folder\vsts-agent-win7-x64-2.112.0 (6)\_work\3\s matches the expected repository origin URL. expected Url: http://devconnecttfs.hca.corpad.net:8080/tfs/BPG%20Project%20Services%20Collection/_git/TestKITT
2017-11-20T19:32:38.5261390Z ##[debug]Inspect remote.origin.url for repository under C:\Installs\New folder\vsts-agent-win7-x64-2.112.0 (6)\_work\3\s
2017-11-20T19:32:38.5261390Z ##[command]git config --get remote.origin.url
2017-11-20T19:32:38.5885390Z ##[debug]Get remote origin fetch url from git config: http://devconnecttfs.hca.corpad.net:8080/tfs/BPG%20Project%20Services%20Collection/_git/TestKITT
2017-11-20T19:32:38.5885390Z ##[debug]Repository remote origin fetch url is http://devconnecttfs.hca.corpad.net:8080/tfs/BPG Project Services Collection/_git/TestKITT
2017-11-20T19:32:38.5885390Z ##[debug]URLs match.
2017-11-20T19:32:38.5885390Z ##[debug]Delete untracked files/folders for repository at C:\Installs\New folder\vsts-agent-win7-x64-2.112.0 (6)\_work\3\s.
2017-11-20T19:32:38.5885390Z ##[command]git clean -fdx
2017-11-20T19:32:38.6353390Z ##[debug]Undo any changes to tracked files in the working tree for repository at C:\Installs\New folder\vsts-agent-win7-x64-2.112.0 (6)\_work\3\s.
2017-11-20T19:32:38.6353390Z ##[command]git reset --hard HEAD
2017-11-20T19:32:38.7133390Z fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
2017-11-20T19:32:38.7133390Z Use '--' to separate paths from revisions, like this:
2017-11-20T19:32:38.7133390Z 'git <command> [<revision>...] -- [<file>...]'
2017-11-20T19:32:38.7133390Z ##[debug]'git reset --hard HEAD' failed with exit code 128
For futher investigation, manually run 'git reset --hard HEAD' on repo root: C:\Installs\New folder\vsts-agent-win7-x64-2.112.0 (6)\_work\3\s after each build.
2017-11-20T19:32:38.7133390Z ##[warning]Unable to run "git clean -fdx" and "git reset --hard HEAD" successfully, delete source folder instead.
2017-11-20T19:32:38.7289390Z ##[debug]Init git repository at: C:\Installs\New folder\vsts-agent-win7-x64-2.112.0 (6)\_work\3\s.
2017-11-20T19:32:38.7289390Z ##[command]git init "C:\Installs\New folder\vsts-agent-win7-x64-2.112.0 (6)\_work\3\s"
2017-11-20T19:32:38.8225390Z Initialized empty Git repository in C:/Installs/New folder/vsts-agent-win7-x64-2.112.0 (6)/_work/3/s/.git/
2017-11-20T19:32:38.8225390Z ##[debug]Add git remote: origin to url: http://devconnecttfs.hca.corpad.net:8080/tfs/BPG%20Project%20Services%20Collection/_git/TestKITT for repository under: C:\Installs\New folder\vsts-agent-win7-x64-2.112.0 (6)\_work\3\s.
2017-11-20T19:32:38.8225390Z ##[command]git remote add origin http://devconnecttfs.hca.corpad.net:8080/tfs/BPG%20Project%20Services%20Collection/_git/TestKITT
2017-11-20T19:32:38.9005390Z ##[debug]Disable git auto garbage collection.
2017-11-20T19:32:38.9005390Z ##[command]git config gc.auto 0
2017-11-20T19:32:38.9473390Z ##[debug]Checking git config http.http://devconnecttfs.hca.corpad.net:8080/tfs/BPG%20Project%20Services%20Collection/_git/TestKITT.extraheader exist or not
2017-11-20T19:32:38.9473390Z ##[command]git config --get-all http.http://devconnecttfs.hca.corpad.net:8080/tfs/BPG%20Project%20Services%20Collection/_git/TestKITT.extraheader
2017-11-20T19:32:39.0253390Z ##[debug]Checking git config http.proxy exist or not
2017-11-20T19:32:39.0253390Z ##[command]git config --get-all http.proxy
2017-11-20T19:32:39.0877390Z ##[debug]Remove any proxy setting from git config.
2017-11-20T19:32:39.0877390Z ##[debug]Unset git config --unset-all http.proxy
2017-11-20T19:32:39.0877390Z ##[command]git config --unset-all http.proxy
2017-11-20T19:32:39.1345390Z ##[warning]Unable to remove "http.proxy" from the git config. To remove the credential, execute "git config --unset-all http.proxy" from the repository root "http.proxy".
2017-11-20T19:32:39.1501390Z ##[debug]Fetch git repository at: C:\Installs\New folder\vsts-agent-win7-x64-2.112.0 (6)\_work\3\s remote: origin.
2017-11-20T19:32:39.1501390Z ##[command]git -c http.extraheader="AUTHORIZATION: bearer ********" fetch --tags --prune --progress origin
**2017-11-20T19:32:39.2905390Z fatal: unable to access 'http://devconnecttfs.hca.corpad.net:8080/tfs/BPG%20Project%20Services%20Collection/_git/TestKITT/': The requested URL returned error: 407
2017-11-20T19:32:39.2905390Z ##[error]Git fetch failed with exit code: 128
2017-11-20T19:32:39.2905390Z ##[debug]System.InvalidOperationException: Git fetch failed with exit code: 128**
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.GitSourceProvider.<GetSourceAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.BuildJobExtension.<PrepareAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.JobExtensionRunner.<RunAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.<RunAsync>d__0.MoveNext()
2017-11-20T19:32:39.3061390Z ##[section]Finishing: Get Sources

**Comment by bryanmacfarlane** [comment]
407 Proxy Authentication Required (RFC 7235)
The client must first authenticate itself with the proxy

**Comment by bryanmacfarlane** [comment]
See agent docs on configuring for proxy.

**Comment by vinaysandela** [comment]
Adding to this
I am getting the same Proxy error while Cloning from VS2017. Attached

I am able to Clone from VS2015. Can someone help to fix this Proxy error. Thanks
![cloneproxyerror_commandline](https://user-images.githubusercontent.com/22040836/33842534-6933adba-de60-11e7-9635-33760abd23b9.JPG)
