### ISSUE TITLE
System.InvalidOperationException: The "Deploy Test Agent" task should be added before running the "Run Functional Test" task.

### ISSUE THREAD

**Issue by vinayapc** [Microsoft/vsts-tasks#5922]
I get this error all of a sudden. This used to work earlier. 
Getting the connection object
Invoke - Get-VssConnection cmdlet
Get - SecretService and EndpointService from TaskContext
Fetched Endpoint:SystemVssConnection
AuthorizationType : OAuth
VssConnection created
UnregisterTestAgent script Path =
Calling Invoke-RunDistributedTests
Invoking Run Distributed Tests with Register Environment support
For troubleshooting, refer https://aka.ms/remotevstest.
Processed: ##vso[task.logissue type=warning]For troubleshooting, refer https://aka.ms/remotevstest.
System.InvalidOperationException: The "Deploy Test Agent" task should be added before running the "Run Functional Test" task.
Processed: ##vso[task.logissue type=error;]System.InvalidOperationException: The "Deploy Test Agent" task should be added before running the "Run Functional Test" task.
   at Microsoft.TeamFoundation.DistributedTask.Task.DistributedTestAutomation.RunTests.GetEnvironmentUri(Uri& machineEnvUri, Uri& autMachineEnvUri, Environment& dtlEnvironment, Environment& autEnvironment)
   at Microsoft.TeamFoundation.DistributedTask.Task.DistributedTestAutomation.RunTests.Run()
   at Microsoft.TeamFoundation.DistributedTask.Task.DistributedTestAutomation.TaskRunner.Run(Dictionary`2 arguments, VssConnection connection, TaskType taskType)
   at Microsoft.TeamFoundation.DistributedTask.Task.DistributedTestAutomation.InvokeRundistributedTestsCmdLet.ProcessRecord()
PowerShell script completed with 1 errors.

I have TFS 2017

**My Deploy Task version**
2017-11-25T03:55:41.9952859Z ==============================================================================
2017-11-25T03:55:41.9952859Z Task         : Visual Studio Test Agent Deployment
2017-11-25T03:55:41.9952859Z Description  : Deploy and configure Test Agent to run tests on a set of machines
2017-11-25T03:55:41.9952859Z Version      : 1.0.42
2017-11-25T03:55:41.9952859Z Author       : Microsoft Corporation
2017-11-25T03:55:41.9952859Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=625976)

**My Run Task Version is** 
2017-11-25T04:08:48.4674955Z ==============================================================================
2017-11-25T04:08:48.4674955Z Task         : Run Functional Tests
2017-11-25T04:08:48.4674955Z Description  : Run Coded UI/Selenium/Functional tests on a set of machines (using Test Agent)
2017-11-25T04:08:48.4674955Z Version      : 1.0.52
2017-11-25T04:08:48.4674955Z Author       : Microsoft Corporation
2017-11-25T04:08:48.4674955Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=624389)
2017-11-25T04:08:48.4674955Z ==============================================================================

**Comment by nigurr** [comment]
@vinayapc Please let us know if you are still having this issue. Closing this issue as there's no response.
