### ISSUE TITLE
TFS 2017 - Deploy Test Agent fails (TestAgentConfiguration) : The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop

### ISSUE THREAD

**Issue by haddedayyadi** [Microsoft/vsts-tasks#5934]
## Environment 
- TFS on-premises
- Version : TFS 2017 UPDATE 3

## Agent
- Private
- OS : Windows 2016 Virtual Machine
- Agent version :  2.122.1

I use TFS with https access and certificate created by own certification authority.

## Issue Description

when running the test agent deployment task, the build fails and return an error : Error : System.Exception: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Exception calling ".ctor" with "2" argument(s): "One or more errors occurred."

Looking in the powershell scripts for the task, I found that it fails at the level of the TestAgentConfiguration.ps1 file and exactly the line :

$DtaAgentClient = New-Object MS.VS.TestService.Client.Utility.TestExecutionServiceRestApiHelper -ArgumentList $TfsCollection, $PersonalAccessToken
 
### Error logs
2017-11-28T13:55:03.9318732Z ##[section]Starting: Deploy TestAgent
2017-11-28T13:55:03.9631318Z ==============================================================================
2017-11-28T13:55:03.9631318Z Task         : Visual Studio Test Agent Deployment
2017-11-28T13:55:03.9631318Z Description  : Deploy and configure Test Agent to run tests on a set of machines
2017-11-28T13:55:03.9631318Z Version      : 2.1.8
2017-11-28T13:55:03.9631318Z Author       : Microsoft Corporation
2017-11-28T13:55:03.9631318Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=838890)
2017-11-28T13:55:03.9631318Z ==============================================================================
2017-11-28T13:55:05.2756903Z ****************************************************************
2017-11-28T13:55:05.2756903Z                     Task Input Information                      
2017-11-28T13:55:05.2756903Z ----------------------------------------------------------------
2017-11-28T13:55:05.2756903Z testMachineInput         = xx
2017-11-28T13:55:05.2756903Z adminUserName            = xx
2017-11-28T13:55:05.2756903Z winRmProtocal            = Http
2017-11-28T13:55:05.2756903Z testCertificate          = true
2017-11-28T13:55:05.2756903Z machineUserName          = xx
2017-11-28T13:55:05.2756903Z runAsProcess             = false
2017-11-28T13:55:05.2756903Z logonAutomatically       = false
2017-11-28T13:55:05.2756903Z disableScreenSaver       = false
2017-11-28T13:55:05.2756903Z isDataCollectionOnly     = false
2017-11-28T13:55:05.2756903Z testPlatform             = 15.0
2017-11-28T13:55:05.2756903Z agentLocation            = D:\TestAgent\TestAgent.zip
2017-11-28T13:55:05.2756903Z updateTestAgent          = true
2017-11-28T13:55:05.2756903Z ****************************************************************
2017-11-28T13:55:05.6975846Z Starting to deploy and configure test agent on test machines.
2017-11-28T13:55:05.6975846Z Inputs provided are:
2017-11-28T13:55:05.6975846Z Use HTTP Port: True
2017-11-28T13:55:05.6975846Z Username: cib\adco9proctfsinstall
2017-11-28T13:55:05.6975846Z Disable Screen saver: False
2017-11-28T13:55:05.6975846Z Login Automatically: False
2017-11-28T13:55:05.6975846Z Run as process: False
2017-11-28T13:55:05.6975846Z Agent location: D:\TestAgent\TestAgent.zip
2017-11-28T13:55:05.6975846Z Update test agent: True
2017-11-28T13:55:05.6975846Z Run test agent as DataCollection only : False
2017-11-28T13:55:05.8069631Z Task 'VerifyTestAgentInstalled' on machine 'xxx:5985' is being run
2017-11-28T13:55:09.5900038Z 	 Deployment started on target machine...
2017-11-28T13:55:09.5900038Z 
2017-11-28T13:55:09.5900038Z Query for Testplatfrom version: 15.0
2017-11-28T13:55:09.5900038Z 
2017-11-28T13:55:09.5900038Z Testing container: 'REGISTRY::HKEY_CLASSES_ROOT\CLSID\{177F0C4A-1CD3-4DE7-A32C-71DBBB9FA36D}'
2017-11-28T13:55:09.5900038Z 
2017-11-28T13:55:09.5900038Z Exists.
2017-11-28T13:55:09.5900038Z 
2017-11-28T13:55:09.5900038Z Getting Visual Studio setup instances.
2017-11-28T13:55:09.5900038Z 
2017-11-28T13:55:09.5900038Z Found 1 instances.
2017-11-28T13:55:09.5900038Z 
2017-11-28T13:55:09.5900038Z 
2017-11-28T13:55:09.5900038Z 
2017-11-28T13:55:09.5900038Z Description   : Supports running automated tests and load tests remotely
2017-11-28T13:55:09.5900038Z DisplayName   : Visual Studio Test Agent 2017
2017-11-28T13:55:09.5900038Z Id            : 83c3e9db
2017-11-28T13:55:09.5900038Z InstallDate   : System.Runtime.InteropServices.ComTypes.FILETIME
2017-11-28T13:55:09.5900038Z Name          : VisualStudio/15.4.5+27004.2010
2017-11-28T13:55:09.5900038Z Path          : C:\TestAgent2017
2017-11-28T13:55:09.5900038Z Version       : 15.4.27004.2010
2017-11-28T13:55:09.5900038Z VersionString : 15.4.27004.2010
2017-11-28T13:55:09.5900038Z 
2017-11-28T13:55:09.5900038Z 
2017-11-28T13:55:09.5900038Z 
2017-11-28T13:55:09.5900038Z 
2017-11-28T13:55:09.5900038Z 
2017-11-28T13:55:09.5900038Z Test Agent already exists
2017-11-28T13:55:09.6055697Z 
2017-11-28T13:55:09.6055697Z Version: 15.4.27004.2010
2017-11-28T13:55:09.6055697Z 
2017-11-28T13:55:09.6055697Z DTAAgentExecutionService is not present on the machine
2017-11-28T13:55:09.6055697Z 
2017-11-28T13:55:09.6055697Z DTAExecutionHost is not running
2017-11-28T13:55:09.6055697Z 
2017-11-28T13:55:09.6055697Z 
2017-11-28T13:55:09.6055697Z RemoteDeployerSource Verbose: 2 : [RemoteDeployer][28:Nov:17:14:55:7:1744; 964, 4](xxx)Created public key for communication
2017-11-28T13:55:09.6055697Z RemoteDeployerSource Information: 12 : [RemoteDeployer][28:Nov:17:14:55:7:1744; 964, 4](xxx)Deployment service - VisualStudioRemoteDeployer2815d668-4033-4f0b-aa26-59151fbc505a is running...
2017-11-28T13:55:09.6055697Z RemoteDeployerSource Verbose: 4 : [RemoteDeployer][28:Nov:17:14:55:8:2011; 964, 6](xxx)Input file found
2017-11-28T13:55:09.6055697Z RemoteDeployerSource Verbose: 5 : [RemoteDeployer][28:Nov:17:14:55:8:2011; 964, 6](xxx)Reading input parameters
2017-11-28T13:55:09.6055697Z RemoteDeployerSource Verbose: 6 : [RemoteDeployer][28:Nov:17:14:55:8:2011; 964, 6](xxx)Finished reading input parameters
2017-11-28T13:55:09.6055697Z 
2017-11-28T13:55:09.6055697Z Task 'VerifyTestAgentInstalled' on machine 'xxx:5985' completed.
2017-11-28T13:55:09.9024594Z Task 'CopyFilesToTestAgent' on machine 'xxx:5985' is being run
2017-11-28T13:55:10.5154283Z 
2017-11-28T13:55:10.5154283Z \\xxx was deleted successfully.
2017-11-28T13:55:10.5154283Z 
2017-11-28T13:55:10.5154283Z Copying recursively from D:\Agents\vsts-agent-01\_work\_tasks\DeployVisualStudioTestAgent_52a38a6a-1517-41d7-96cc-73ee0c60d2b6\2.1.8\TestExecution.zip to C:\TestAgent on machine xxx succeeded.
2017-11-28T13:55:10.5154283Z 
2017-11-28T13:55:10.5154283Z \\xxx was deleted successfully.
2017-11-28T13:55:10.5154283Z 
2017-11-28T13:55:10.5154283Z 
2017-11-28T13:55:10.5154283Z Task 'CopyFilesToTestAgent' on machine 'xxx:5985' completed.
2017-11-28T13:55:10.5310533Z Task 'TestAgentConfiguration' on machine 'xxx:5985' is being run
2017-11-28T13:55:59.3518517Z RemoteDeployerSource Verbose: 2 : [RemoteDeployer][28:Nov:17:14:55:11:6907; 11268, 4](xxx)Created public key for communication
2017-11-28T13:55:59.3518517Z RemoteDeployerSource Information: 12 : [RemoteDeployer][28:Nov:17:14:55:11:6907; 11268, 4](xxx)Deployment service - VisualStudioRemoteDeployer4cdafa2f-6c28-4285-94bc-006a14131630 is running...
2017-11-28T13:55:59.3518517Z RemoteDeployerSource Verbose: 4 : [RemoteDeployer][28:Nov:17:14:55:12:7145; 11268, 6](xxx)Input file found
2017-11-28T13:55:59.3518517Z RemoteDeployerSource Verbose: 5 : [RemoteDeployer][28:Nov:17:14:55:12:7145; 11268, 6](xxx)Reading input parameters
2017-11-28T13:55:59.3518517Z RemoteDeployerSource Verbose: 6 : [RemoteDeployer][28:Nov:17:14:55:12:7145; 11268, 6](xxx)Finished reading input parameters
2017-11-28T13:55:59.3518517Z 
2017-11-28T13:55:59.3518517Z Task 'TestAgentConfiguration' on machine 'xxx:5985' completed.
2017-11-28T13:55:59.3518517Z ##[warning]Task 'TestAgentConfiguration' for machine xxx:5985's Error : System.Exception: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Exception calling ".ctor" with "2" argument(s): "One or more errors occurred."
2017-11-28T13:55:59.3518517Z ##[warning]Task 'TestAgentConfiguration' for machine xxx:5985's Log : 
2017-11-28T13:55:59.3518517Z 	 Deployment started on target machine...
2017-11-28T13:55:59.3518517Z 
2017-11-28T13:55:59.3518517Z System.AggregateException: Failed to execute the powershell script. Consult the logs below for details of the error.
2017-11-28T13:55:59.3518517Z The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Exception calling ".ctor" with "2" argument(s): "One or more errors occurred." ---> System.Management.Automation.ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Exception calling ".ctor" with "2" argument(s): "One or more errors occurred."
2017-11-28T13:55:59.3518517Z    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
2017-11-28T13:55:59.3518517Z    at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
2017-11-28T13:55:59.3518517Z    at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
2017-11-28T13:55:59.3518517Z    at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2017-11-28T13:55:59.3518517Z    at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2017-11-28T13:55:59.3518517Z    at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
2017-11-28T13:55:59.3518517Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Deployment.PowershellExecutor.<>c__DisplayClass28_0.<Invoke>b__0()
2017-11-28T13:55:59.3518517Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Utilities.RetryExecutor.<>c__DisplayClass19_0`1.<Execute>b__0()
2017-11-28T13:55:59.3518517Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Utilities.RetryExecutor.Execute(Action action)
2017-11-28T13:55:59.3518517Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Utilities.RetryExecutor.Execute[T](Func`1 action)
2017-11-28T13:55:59.3518517Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Deployment.PowershellExecutor.Invoke(String errorContextMessage, Boolean writeResultToLog, Boolean isCancellable, ActionPreference errorActionPreference)
2017-11-28T13:55:59.3518517Z    --- End of inner exception stack trace ---
2017-11-28T13:55:59.3518517Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Deployment.PowershellExecutor.Invoke(String errorContextMessage, Boolean writeResultToLog, Boolean isCancellable, ActionPreference errorActionPreference)
2017-11-28T13:55:59.3518517Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Deployment.ScriptExecutor.ExecuteScript(IPowerShell powerShell, String script, String arguments, Boolean isScriptDotSourced, Boolean useHttp)
2017-11-28T13:55:59.3518517Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Deployment.DeploymentService.RunPowerShellScripts(DeploymentMachineSpecification deploymentMachine, ScriptSpecification scriptSpecification, ScriptSpecification initializationScriptSpecification, String applicationPath, IPowerShell powerShellSession)
2017-11-28T13:55:59.3518517Z ---> (Inner Exception #0) System.Management.Automation.ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Exception calling ".ctor" with "2" argument(s): "One or more errors occurred."
2017-11-28T13:55:59.3518517Z    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
2017-11-28T13:55:59.3518517Z    at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
2017-11-28T13:55:59.3518517Z    at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
2017-11-28T13:55:59.3518517Z    at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2017-11-28T13:55:59.3518517Z    at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2017-11-28T13:55:59.3518517Z    at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
2017-11-28T13:55:59.3518517Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Deployment.PowershellExecutor.<>c__DisplayClass28_0.<Invoke>b__0()
2017-11-28T13:55:59.3518517Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Utilities.RetryExecutor.<>c__DisplayClass19_0`1.<Execute>b__0()
2017-11-28T13:55:59.3518517Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Utilities.RetryExecutor.Execute(Action action)
2017-11-28T13:55:59.3518517Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Utilities.RetryExecutor.Execute[T](Func`1 action)
2017-11-28T13:55:59.3518517Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Deployment.PowershellExecutor.Invoke(String errorContextMessage, Boolean writeResultToLog, Boolean isCancellable, ActionPreference errorActionPreference)<---
2017-11-28T13:55:59.3518517Z Testing container: 'REGISTRY::HKEY_CLASSES_ROOT\CLSID\{177F0C4A-1CD3-4DE7-A32C-71DBBB9FA36D}'
2017-11-28T13:55:59.3518517Z 
2017-11-28T13:55:59.3518517Z Exists.
2017-11-28T13:55:59.3518517Z 
2017-11-28T13:55:59.3518517Z Getting Visual Studio setup instances.
2017-11-28T13:55:59.3518517Z 
2017-11-28T13:55:59.3518517Z Found 1 instances.
2017-11-28T13:55:59.3518517Z 
2017-11-28T13:55:59.3518517Z 
2017-11-28T13:55:59.3518517Z 
2017-11-28T13:55:59.3518517Z Description   : Supports running automated tests and load tests remotely
2017-11-28T13:55:59.3518517Z DisplayName   : Visual Studio Test Agent 2017
2017-11-28T13:55:59.3518517Z Id            : 83c3e9db
2017-11-28T13:55:59.3518517Z InstallDate   : System.Runtime.InteropServices.ComTypes.FILETIME
2017-11-28T13:55:59.3518517Z Name          : VisualStudio/15.4.5+27004.2010
2017-11-28T13:55:59.3518517Z Path          : C:\TestAgent2017
2017-11-28T13:55:59.3518517Z Version       : 15.4.27004.2010
2017-11-28T13:55:59.3518517Z VersionString : 15.4.27004.2010
2017-11-28T13:55:59.3518517Z 
2017-11-28T13:55:59.3518517Z 
2017-11-28T13:55:59.3518517Z 
2017-11-28T13:55:59.3518517Z 
2017-11-28T13:55:59.3518517Z 
2017-11-28T13:55:59.3518517Z VS path C:\TestAgent2017\Common7\IDE; Test window path C:\TestAgent2017\Common7\IDE\CommonExtensions\Microsoft\TestWindow
2017-11-28T13:55:59.3518517Z 
2017-11-28T13:55:59.3518517Z Path: C:\TestAgent\TfsAssemblies\Newtonsoft.Json.dll
2017-11-28T13:55:59.3518517Z 
2017-11-28T13:55:59.3518517Z Loading module from path 'C:\TestAgent\TfsAssemblies\Newtonsoft.Json.dll'.
2017-11-28T13:55:59.3518517Z 
2017-11-28T13:55:59.3518517Z Loading module from path 'C:\TestAgent\TfsAssemblies\System.Net.Http.Formatting.dll'.
2017-11-28T13:55:59.3518517Z 
2017-11-28T13:55:59.3518517Z Loading module from path 'C:\TestAgent\TfsAssemblies\Microsoft.TeamFoundation.DistributedTask.Task.TestExecution.dll'.
2017-11-28T13:55:59.3518517Z 
2017-11-28T13:55:59.3518517Z Loading module from path 'C:\TestAgent\TfsAssemblies\Microsoft.TeamFoundation.Common.dll'.
2017-11-28T13:55:59.3518517Z 
2017-11-28T13:55:59.3518517Z Loading module from path 'C:\TestAgent\TfsAssemblies\Microsoft.TeamFoundation.Test.WebApi.dll'.
2017-11-28T13:55:59.3518517Z 
2017-11-28T13:55:59.3518517Z Loading module from path 'C:\TestAgent\TfsAssemblies\Microsoft.VisualStudio.Services.Common.dll'.
2017-11-28T13:55:59.3518517Z 
2017-11-28T13:55:59.3518517Z Loading module from path 'C:\TestAgent\TfsAssemblies\Microsoft.VisualStudio.Services.WebApi.dll'.
2017-11-28T13:55:59.3518517Z 
2017-11-28T13:55:59.3518517Z Loading module from path 'C:\TestAgent\PrivateAssemblies\MS.VS.TestService.Client.Utility.dll'.
2017-11-28T13:55:59.3518517Z 
2017-11-28T13:55:59.3518517Z ****************************************************************
2017-11-28T13:55:59.3518517Z 
2017-11-28T13:55:59.3518517Z                     Configure Test Agent                      
2017-11-28T13:55:59.3518517Z 
2017-11-28T13:55:59.3518517Z ----------------------------------------------------------------
2017-11-28T13:55:59.3518517Z 
2017-11-28T13:55:59.3518517Z SetupPath                       : (C:\TestAgent)
2017-11-28T13:55:59.3518517Z 
2017-11-28T13:55:59.3518517Z TestUserName                    : (xxx)
2017-11-28T13:55:59.3518517Z 
2017-11-28T13:55:59.3518517Z TfsCollection                   : (xxx)
2017-11-28T13:55:59.3518517Z 
2017-11-28T13:55:59.3518517Z AsServiceOrProcess              : (Service)
2017-11-28T13:55:59.3518517Z 
2017-11-28T13:55:59.3518517Z EnvironmentUrl                  : (xxx)
2017-11-28T13:55:59.3518517Z 
2017-11-28T13:55:59.3518517Z MachineName                     : (xxx)
2017-11-28T13:55:59.3518517Z 
2017-11-28T13:55:59.3518517Z Capabilities                    : ()
2017-11-28T13:55:59.3518517Z 
2017-11-28T13:55:59.3518517Z TestAgentVersion                : (15.0)
2017-11-28T13:55:59.3518517Z 
2017-11-28T13:55:59.3518517Z ****************************************************************
2017-11-28T13:55:59.3518517Z 
2017-11-28T13:55:59.3518517Z 
2017-11-28T13:55:59.3518517Z Exception calling ".ctor" with "2" argument(s): "One or more errors occurred."
2017-11-28T13:55:59.3518517Z 
2017-11-28T13:55:59.3518517Z 
2017-11-28T13:55:59.3674758Z ##[error]Error occured on 'xxx:5985'. Details : 'The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Exception calling ".ctor" with "2" argument(s): "One or more errors occurred."'. For troubleshooting, refer https://aka.ms/remotevstest.
2017-11-28T13:55:59.3987260Z ##[section]Finishing: Deploy TestAgent

**Comment by haddedayyadi** [comment]
I solved this Issue ;)

I recommends enabling and using the TLS 1.2 protocol on your server.  TLS 1.2 has improvements over previous versions of the TLS and SSL protocol which will improve your level of security.  By default, Windows Server does not have this feature enabled.  This KB article will describe the process to enable this.
Start the registry editor by clicking on Start and Run. Type in "regedit" into the Run field (without quotations).

Highlight Computer at the top of the registry tree.  Backup the registry first by clicking on File and then on Export.  Select a file location to save the registry file.

Note: You will be editing the registry.  This could have detrimental effects on your computer if done incorrectly, so it is strongly advised to make a backup.

Browse to the following registry key:
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols

Right click on the Protocols folder and select New and then Key from the drop-down menu. This will create new folder.  Rename this folder to TLS 1.2.

Right click on the TLS 1.2 key and add two new keys underneath it.

Rename the two new keys as:
Client
Server

Right click on the Client key and select New and then DWORD (32-bit) Value from the drop-down list.

Rename the DWORD to DisabledByDefault.

Right-click the name DisabledByDefault and select Modify... from the drop-down menu.

Ensure that the Value data field is set to 0 and the Base is Hexadecimal.  Click on OK.

Create another DWORD for the Client key as you did in Step 7.

Rename this second DWORD to Enabled.

Right-click the name Enabled and select Modify... from the drop-down menu.

Ensure that the Value data field is set to 1 and the Base is Hexadecimal. Click on OK.

Repeat steps 7 to 14 for the Server key (by creating two DWORDs, DisabledByDefault and Enabled, and their values underneath the Server key).

Reboot the server.

**Comment by prawalagarwal** [comment]
Thanks for reporting. Please get back to us at devops_tools@microsoft.com if you face any more issues.
