### ISSUE TITLE
Send email task failed when using Hosted Linux Preview

### ISSUE THREAD

**Issue by doggy8088** [Microsoft/vsts-tasks#5990]
## Environment
- Server - VSTS or TFS on-premises?
    - If using TFS on-premises, provide the version: 

      N/A    

    - If using VSTS, provide the account name, team project name, build definition name/build number: 

      Account Name: `miniasp`
      Team Project Name: `TraPac_STARS`
      Release Definition Name: `TraPac_STARS CD (Docker)`
      Release Number: `Release-6`

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

      `Hosted Linux Preview`

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

      N/A

## Issue Description

The "Send email" task looks like not supported in **Hosted Linux Preview** queue.

### Error logs

```
2017-12-08T02:15:19.3250130Z ##[debug]Evaluating condition for step: 'Send an email to all stakeholders'
2017-12-08T02:15:19.3269610Z ##[debug]Evaluating: succeeded()
2017-12-08T02:15:19.3286740Z ##[debug]Evaluating succeeded:
2017-12-08T02:15:19.3311650Z ##[debug]=> (Boolean) True
2017-12-08T02:15:19.3328540Z ##[debug]Expanded: True
2017-12-08T02:15:19.3345970Z ##[debug]Result: True
2017-12-08T02:15:19.3363220Z ##[section]Starting: Send an email to all stakeholders
2017-12-08T02:15:19.3403400Z ==============================================================================
2017-12-08T02:15:19.3416720Z Task         : Send email
2017-12-08T02:15:19.3428660Z Description  : Send an email to 1 or more addresses via the SMTP server you provide
2017-12-08T02:15:19.3440400Z Version      : 1.1.1029
2017-12-08T02:15:19.3451900Z Author       : R. van Osnabrugge
2017-12-08T02:15:19.3463560Z Help         : Version: 1.1.1029. [More information](http://gitub.com/rvanosnabrugge)
2017-12-08T02:15:19.3475050Z ==============================================================================
2017-12-08T02:15:19.6327200Z ##[error]A supported task execution handler was not found. This error usually means the task does not carry an implementation that is compatible with your current operating system. Contact the task author for more details.
2017-12-08T02:15:19.6403220Z ##[debug]System.Exception: A supported task execution handler was not found. This error usually means the task does not carry an implementation that is compatible with your current operating system. Contact the task author for more details.
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.<RunAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.<RunStepAsync>d__1.MoveNext()
2017-12-08T02:15:19.6433500Z ##[section]Finishing: Send an email to all stakeholders
```

**Comment by bryanmacfarlane** [comment]
send email task is not a task in this repo

**Comment by doggy8088** [comment]
@bryanmacfarlane Do you have any "Send email" related task?
