### ISSUE TITLE
Created basic CI CD setup and getting strange error

### ISSUE THREAD

**Issue by punkouter** [Microsoft/vsts-tasks#5997]
It builds and runs fine.

C:\Program Files\dotnet\sdk\2.0.2\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets (323, 5) 
C:\Program Files\dotnet\sdk\2.0.2\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(323,5): Error : Assets file 'd:\a\1\s\QuickApp\DAL\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.

C:\Program Files\dotnet\sdk\2.0.2\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets (165, 5) 
C:\Program Files\dotnet\sdk\2.0.2\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(165,5): Error : Assets file 'd:\a\1\s\QuickApp\DAL\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.

Process 'msbuild.exe' exited with code '1'.

**Comment by JohannesDrexler** [comment]
missing a "dotnet restore" before the build ?

**Comment by punkouter** [comment]
I ran that on the DAL still same error. Oh well. Ill have to revisit this maybe some other day.. I was hoping it would just 'work'

**Comment by brcrista** [comment]
What does your build definition look like?

If you can enable the YAML builds preview feature for your account, you can export your build definition as a YAML file and attach it to this thread.  https://docs.microsoft.com/en-us/vsts/collaborate/preview-features

**Comment by bryanmacfarlane** [comment]
This doesn't look like a CI or task issue - it looks like your build and nuget is outputting an error and the task is correctly reporting it.  There's an ask for more details above.  Need more info to repro.

**Comment by alexmullans** [comment]
For future readers: this definitely looks like you need a dotnet restore step before your build. If you use the ASP.NET Core build template, you should have such a step already. If not, add the '.NET Core' build task from the catalog and select the "restore" command from the dropdown.

I'm going to close this for now since it's been 8 days since the filer commented. Please feel free to comment and tag me if you're able to continue troubleshooting and the advice above doesn't solve your issue.

**Comment by yzorg** [comment]
@alexmullans FYI, just for long-tail (one data point, not actionable)

I hit this same symptom today, missing `{project}\obj\project.assets.json`, where project was my DAL library, which is netstandard 2.0 project, the rest of my projects are 4.x.

But `project.assets.json` was missing b/c of what looked like an MSBuild race condition, or if it wasn't a race the error message didn't make sense to me.

```
2017-12-22T20:43:44.8908707Z [command]d:\a\_tool\NuGet\4.3.0\x64\nuget.exe restore d:\a\1\s\MyApp.sln -Verbosity Detailed -NonInteractive -ConfigFile d:\a\1\Nuget\tempNuGet_1738.config
2017-12-22T20:46:56.4035420Z NuGet Version: 4.3.0.4406
2017-12-22T20:46:56.4041837Z MSBuild auto-detection: using msbuild version '15.4.8.50001' from 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\bin'. Use option -MSBuildVersion to force nuget to use a specific version of MSBuild.
2017-12-22T20:46:56.4048682Z MSBuild P2P timeout [ms]: 120000
2017-12-22T20:46:56.4056237Z C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\bin\msbuild.exe "d:\a\_temp\NuGetScratch\re1o55sm.wwh.nugetinputs.targets" /t:GenerateRestoreGraphFile /nologo /nr:false /v:q /p:NuGetRestoreTargets="d:\a\_temp\NuGetScratch\sahnchut.eth.nugetrestore.targets" /p:RestoreTaskAssemblyFile="d:\a\_tool\NuGet\4.3.0\x64\nuget.exe" /p:RestoreSolutionDirectory="d:\a\1\s" /p:RestoreConfigFile="d:\a\1\Nuget\tempNuGet_1738.config"
2017-12-22T20:46:56.4083540Z NuGet.CommandLine.CommandLineException: MsBuild timeout out while trying to get project to project references.
2017-12-22T20:46:56.4090852Z    at NuGet.CommandLine.MsBuildUtility.<GetProjectReferencesAsync>d__6.MoveNext()
2017-12-22T20:46:56.4091311Z --- End of stack trace from previous location where exception was thrown ---
2017-12-22T20:46:56.4091591Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-12-22T20:46:56.4091835Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-12-22T20:46:56.4092073Z    at NuGet.CommandLine.RestoreCommand.<GetDependencyGraphSpecAsync>d__48.MoveNext()
2017-12-22T20:46:56.4092336Z --- End of stack trace from previous location where exception was thrown ---
2017-12-22T20:46:56.4092562Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-12-22T20:46:56.4092792Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-12-22T20:46:56.4105295Z    at NuGet.CommandLine.RestoreCommand.<DetermineInputsFromMSBuildAsync>d__43.MoveNext()
2017-12-22T20:46:56.4105762Z WARNING: Error reading msbuild project information, ensure that your input solution or project file is valid. NETCore and UAP projects will be skipped, only packages.config files will be restored.
2017-12-22T20:46:56.4106078Z Restoring NuGet package Antlr.3.5.0.2.
2017-12-22T20:46:56.4106288Z Restoring NuGet package Autofac.4.6.0.
```

**Comment by alexmullans** [comment]
@yzorg thanks; I'll forward this to the dotnet team to take a look.
