### ISSUE TITLE
Error: Cannot find module in VSTS

### ISSUE THREAD

**Issue by marceloavf** [Microsoft/vsts-tasks#6258]
## Environment
- VSTS
precisaosistemas/InovaFarmaAPI/InovaFarama API

- Agent Private: 
**Windows Server 2016 Standard**
**Agent version** 2.124.0

## Issue Description

I'm trying to use some node_modules inside my js task with gulp, but I don't know how to import it and use it. Do I need to install it global in agent to provide it or someway import it inside the project?

Link to the extension: https://github.com/marceloavf/github-tools-vsts

### Error logs

```
2018-01-20T13:39:12.6756810Z ==============================================================================
2018-01-20T13:39:12.6756810Z Task         : Create GitHub Release
2018-01-20T13:39:12.6766811Z Description  : Create and publish GitHub Release and upload assets, accepting manifest content
2018-01-20T13:39:12.6766811Z Version      : 0.1.7
2018-01-20T13:39:12.6766811Z Author       : Marcelo Formentão
2018-01-20T13:39:12.6766811Z Help         : [More Information](https://github.com/marceloavf/github-tools-vsts)
2018-01-20T13:39:12.6766811Z ==============================================================================
2018-01-20T13:39:12.9527031Z module.js:471
2018-01-20T13:39:12.9527031Z     throw err;
2018-01-20T13:39:12.9527031Z     ^
2018-01-20T13:39:12.9527031Z 
2018-01-20T13:39:12.9527031Z Error: Cannot find module 'gulp-github-release'
2018-01-20T13:39:12.9527031Z     at Function.Module._resolveFilename (module.js:469:15)
2018-01-20T13:39:12.9527031Z     at Function.Module._load (module.js:417:25)
2018-01-20T13:39:12.9527031Z     at Module.require (module.js:497:17)
2018-01-20T13:39:12.9527031Z     at require (internal/module.js:20:19)
2018-01-20T13:39:12.9527031Z     at Object.<anonymous> (C:\agent\_work\_tasks\github-tools_0e54b1de-2c34-4acd-b93d-0fa1b9730bbe\0.1.7\github-release-publish.js:1:79)
2018-01-20T13:39:12.9537027Z     at Module._compile (module.js:570:32)
2018-01-20T13:39:12.9537027Z     at Object.Module._extensions..js (module.js:579:10)
2018-01-20T13:39:12.9537027Z     at Module.load (module.js:487:32)
2018-01-20T13:39:12.9537027Z     at tryModuleLoad (module.js:446:12)
2018-01-20T13:39:12.9537027Z     at Function.Module._load (module.js:438:3)
2018-01-20T13:39:13.0537072Z ##[error]Exit code 1 returned from process: file name 'C:\agent\externals\node\bin\node.exe', arguments '"C:\agent\_work\_tasks\github-tools_0e54b1de-2c34-4acd-b93d-0fa1b9730bbe\0.1.7\github-release-publish.js"'.
2018-01-20T13:39:13.0617025Z ##[debug]Microsoft.VisualStudio.Services.Agent.ProcessExitCodeException: Exit code 1 returned from process: file name 'C:\agent\externals\node\bin\node.exe', arguments '"C:\agent\_work\_tasks\github-tools_0e54b1de-2c34-4acd-b93d-0fa1b9730bbe\0.1.7\github-release-publish.js"'.
   at Microsoft.VisualStudio.Services.Agent.ProcessInvoker.<ExecuteAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.NodeHandler.<RunAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.<RunAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.<RunStepAsync>d__1.MoveNext()
2018-01-20T13:39:13.0617025Z ##[section]Finishing: Create a GitHub Release
```

**Comment by marceloavf** [comment]
Just need to bundle up.
