### ISSUE TITLE
Coded UI test execution fails using a Test Run

### ISSUE THREAD

**Issue by rudidlo** [Microsoft/vsts-tasks#6264]
## Environment
- Server - VSTS or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 2018
    
- Agent - Hosted or Private: 
    
    - If using private agent, provide the OS of the machine running the agent and the agent version: Windows Server 2016, Agent version 2.122.1

## Issue Description

We started using Coded UI tests. Our tests are working correctly if we execute them using "Run functional tests" step during build. If we disable this execution and create release according to page Run automated tests from the test hub (we have associated Test case with Coded UI test), when we execute a test run, we receive following error when test run is being executed.

it is also strange, that we are getting warning 
##[warning]Other console options is not supported when using the multi-agent phase setting. This option will be ignored.

But if I check parallelism settings in Release definition, I have set it to None, but I still see in the log, that execution type is set to multi configuration.

[SYSTEM_PARALLELEXECUTIONTYPE] --> [MultiConfiguration]

### Error logs
[ReleaseLogs_842.zip](https://github.com/Microsoft/vsts-tasks/files/1651878/ReleaseLogs_842.zip)
![paralelism](https://user-images.githubusercontent.com/15245022/35220343-e5268770-ff6d-11e7-83e1-015762cd71a3.PNG)

2018-01-19T16:27:04.5241154Z ##[error]ExecutionTaskStateModel.ExecuteTask: Recived error while executing task: System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: No test assemblies found on the test machine matching th
2018-01-19T16:27:04.5241154Z e source filter criteria or no tests discovered matching test filter criteria. Verify that test assemblies are present on the machine and test filter criteria is correct.
2018-01-19T16:27:04.5241154Z at Microsoft.VisualStudio.TestService.VstestAdapter.Execution.Run(CancellationTok
2018-01-19T16:27:04.5241154Z en cancellationToken) in E:\v2.0\A6_work\1\s\Ta\Agent\VS.TestService.VstestAdapter\Phases\Execution.cs:line 60
2018-01-19T16:27:04.5241154Z at Microsoft.VisualStudio.TestService.VstestAdapter.ExecutionAndPublish.Run(CancellationToken cancellationToken) in E:\v2.0\A6_work\1\s\Ta\
2018-01-19T16:27:04.5241154Z Agent\VS.TestService.VstestAdapter\Phases\ExecuteAndPublish.cs:line 51
2018-01-19T16:27:04.5241154Z at Microsoft.VisualStudio.TestService.VstestAdapter.VstestAdapter.<>c_DisplayClass2_0.<ExecuteAsync>b0() in E:\v2.0\A6_work\1\s\Ta\Agent\VS.TestService.VstestAdapter\VstestAdapt
2018-01-19T16:27:04.5241154Z er.cs:line 61
2018-01-19T16:27:04.5241154Z at System.Threading.Tasks.Task`1.InnerInvoke()
2018-01-19T16:27:04.5241154Z at System.Threading.Tasks.Task.Execute()
2018-01-19T16:27:04.5241154Z --- End of inner exception stack trace ---
2018-01-19T16:27:04.5241154Z ---> (Inner Exception #0) System.InvalidOperationException: No test assemblies found on the test m
2018-01-19T16:27:04.5241154Z achine matching the source filter criteria or no tests discovered matching test filter criteria. Verify that test assemblies are present on the machine and test filter criteria is correct.
2018-01-19T16:27:04.5241154Z at Microsoft.VisualStudio.TestService.VstestAdapter.Execution.R
2018-01-19T16:27:04.5241154Z un(CancellationToken cancellationToken) in E:\v2.0\A6_work\1\s\Ta\Agent\VS.TestService.VstestAdapter\Phases\Execution.cs:line 60
2018-01-19T16:27:04.5241154Z at Microsoft.VisualStudio.TestService.VstestAdapter.ExecutionAndPublish.Run(CancellationToken cancellationToken) in E:\v2.
2018-01-19T16:27:04.5241154Z 0\A6_work\1\s\Ta\Agent\VS.TestService.VstestAdapter\Phases\ExecuteAndPublish.cs:line 51
2018-01-19T16:27:04.5241154Z at Microsoft.VisualStudio.TestService.VstestAdapter.VstestAdapter.<>cDisplayClass2_0.<ExecuteAsync>b_0() in E:\v2.0\A6_work\1\s\Ta\Agent\VS.TestService.VstestA
2018-01-19T16:27:04.5241154Z dapter\VstestAdapter.cs:line 61
2018-01-19T16:27:04.5241154Z at System.Threading.Tasks.Task`1.InnerInvoke()
2018-01-19T16:27:04.5241154Z at System.Threading.Tasks.Task.Execute()<---
2018-01-19T16:27:04.5241154Z 
2018-01-19T16:27:04.5241154Z ##[error]ExecutionTaskStateModel.AbortSlice : System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: No test assemblies found on the test machine matching the source filter criteria or no tests
2018-01-19T16:27:04.5241154Z discovered matching test filter criteria. Verify that test assemblies are present on the machine and test filter criteria is correct.
2018-01-19T16:27:04.5241154Z at Microsoft.VisualStudio.TestService.VstestAdapter.Execution.Run(CancellationToken cancellationToken) in E:\v2.0\A6\
2018-01-19T16:27:04.5241154Z work\1\s\Ta\Agent\VS.TestService.VstestAdapter\Phases\Execution.cs:line 60
2018-01-19T16:27:04.5241154Z at Microsoft.VisualStudio.TestService.VstestAdapter.ExecutionAndPublish.Run(CancellationToken cancellationToken) in E:\v2.0\A6_work\1\s\Ta\Agent\VS.TestService.VstestAdapter\P
2018-01-19T16:27:04.5241154Z hases\ExecuteAndPublish.cs:line 51
2018-01-19T16:27:04.5241154Z at Microsoft.VisualStudio.TestService.VstestAdapter.VstestAdapter.<>cDisplayClass2_0.<ExecuteAsync>b0() in E:\v2.0\A6_work\1\s\Ta\Agent\VS.TestService.VstestAdapter\VstestAdapter.cs:line 61
2018-01-19T16:27:04.5241154Z at System.Threadin
2018-01-19T16:27:04.5241154Z g.Tasks.Task`1.InnerInvoke()
2018-01-19T16:27:04.5241154Z at System.Threading.Tasks.Task.Execute()
2018-01-19T16:27:04.5241154Z --- End of inner exception stack trace ---
2018-01-19T16:27:04.5241154Z ---> (Inner Exception #0) System.InvalidOperationException: No test assemblies found on the test machine matching the source filter cr
2018-01-19T16:27:04.5241154Z iteria or no tests discovered matching test filter criteria. Verify that test assemblies are present on the machine and test filter criteria is correct.
2018-01-19T16:27:04.5241154Z at Microsoft.VisualStudio.TestService.VstestAdapter.Execution.Run(CancellationToken cancellationTok
2018-01-19T16:27:04.5241154Z en) in E:\v2.0\A6_work\1\s\Ta\Agent\VS.TestService.VstestAdapter\Phases\Execution.cs:line 60
2018-01-19T16:27:04.5241154Z at Microsoft.VisualStudio.TestService.VstestAdapter.ExecutionAndPublish.Run(CancellationToken cancellationToken) in E:\v2.0\A6_work\1\s\Ta\Agent\VS.TestServi
2018-01-19T16:27:04.5241154Z ce.VstestAdapter\Phases\ExecuteAndPublish.cs:line 51
2018-01-19T16:27:04.5241154Z at Microsoft.VisualStudio.TestService.VstestAdapter.VstestAdapter.<>cDisplayClass2_0.<ExecuteAsync>b_0() in E:\v2.0\A6_work\1\s\Ta\Agent\VS.TestService.VstestAdapter\VstestAdapter.cs:line 61
2018-01-19T16:27:04.5241154Z 
2018-01-19T16:27:04.5241154Z at System.Threading.Tasks.Task`1.InnerInvoke()
2018-01-19T16:27:04.5241154Z at System.Threading.Tasks.Task.Execute()<---

**Comment by acesiddhu** [comment]
@rudidlo Sorry for the late reply. Are you still blocked on this? The error message suggest that agent doesn't have test assemblies specified in the search location. Can you cross check that

"No test assemblies found on the test machine matching the source filter cr 2018-01-19T16:27:04.5241154Z iteria or no tests discovered matching test filter criteria. Verify that test assemblies are present on the machine and test filter criteria is correct"

**Comment by rudidlo** [comment]
Test assemblies were successfully copied to folder where expected. Problem was with Visual Studio  2017 installation at test machine. Repair did not helped, but I had to uninstall and install Visual Studio again.
