### ISSUE TITLE
Azure Web App deploy fails, Error Code: ERROR_INSUFFICIENT_ACCESS_TO_SITE_FOLDER

### ISSUE THREAD

**Issue by elmalakai** [Microsoft/vsts-tasks#6344]
## Environment: VSTS 
- Account: digitalsolutionsllc
- Project: Quanta
- Build Def: QuantaWebAPI_Dev_BuildDefinition
- Build Number: 877

- Agent - Hosted VS2017

## Issue Description
Receiving intermediate deployment failures from Azure App Service Deploy, revolving around deleting a file "**dotnete-aspnet-codegeneratore-design.exe**".

I'm using  version 3.*, and I have enabled the following:
 -"Take app Offline" 
 - Publihs using Web Deploy
 - Remove additional files at destination
 - Exclude files from App_Data folder
 - Rename locked files

"Remove additional files at destination" was enabled because of migrating from .Net Core 1.0 to 2.0 resulted in a process failure without first cleaning the directory.

Shutting down the Web App allows the tasks to complete.

I also have the "MSDEPLOY_RENAME_LOCKED_FILES = 1" app setting configured on this Azure Web app.

### Error logs
```
2018-02-01T20:27:12.4010464Z ##[section]Starting: Azure App Service Deploy: QuantaWebAPI
2018-02-01T20:27:12.4024281Z ==============================================================================
2018-02-01T20:27:12.4024820Z Task         : Azure App Service Deploy
2018-02-01T20:27:12.4025425Z Description  : Update Azure WebApp Services On Windows, Web App On Linux with built-in images or docker containers, ASP.NET, .NET Core, PHP, Python or Node based Web applications, Function Apps, Mobile Apps, Api applications, Web Jobs using Web Deploy / Kudu REST APIs
2018-02-01T20:27:12.4026011Z Version      : 3.3.32
2018-02-01T20:27:12.4026348Z Author       : Microsoft Corporation
2018-02-01T20:27:12.4026736Z Help         : [More Information](https://aka.ms/azurermwebdeployreadme)
2018-02-01T20:27:12.4027149Z ==============================================================================
2018-02-01T20:27:15.0309618Z Got connection details for Azure App Service:'QuantaWebAPI'
2018-02-01T20:27:15.4392326Z [command]"C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" -verb:sync -source:package='d:\a\1\a\Quanta.API.zip' -dest:auto,ComputerName='https://******.scm.azurewebsites.net:443/msdeploy.axd?site=QuantaWebAPI',UserName='********',Password='********',AuthType='Basic' -setParam:name='IIS Web Application Name',value='QuantaWebAPI' -enableRule:AppOffline -skip:Directory=App_Data -userAgent:VSTS_b78395c7-912b-46e3-88c3-d6d71fc3cbe4_build_12_875
2018-02-01T20:27:16.3598343Z Info: Using ID '1a29e029-b84c-463f-95a5-6c33bb4060a4' for connections to the remote server.
2018-02-01T20:27:18.5279202Z Info: Object dirPath (QuantaWebAPI\App_Data) skipped due to skip directive 'CommandLineSkipDirective 1'.
2018-02-01T20:27:18.5280470Z Info: Deleting file (QuantaWebAPI\Quanta.ReportingAPI\dotnet-aspnet-codegenerator-design.exe).
2018-02-01T20:27:18.6031615Z ##[error]Failed to deploy web package to App Service.
2018-02-01T20:27:18.6035151Z ##[warning]Try to deploy app service again with Take application offline option selected.
2018-02-01T20:27:18.6041846Z ##[error]Error Code: ERROR_INSUFFICIENT_ACCESS_TO_SITE_FOLDER
More Information: Unable to perform the operation ("Delete File")  for the specified directory ("D:\home\site\wwwroot\Quanta.ReportingAPI\dotnet-aspnet-codegenerator-design.exe"). This can occur if the server administrator has not authorized this operation for the user credentials you are using.  Learn more at: http://go.microsoft.com/fwlink/?LinkId=221672#ERROR_INSUFFICIENT_ACCESS_TO_SITE_FOLDER.
Error: The error code was 0x80070005.
Error: Access to the path 'D:\home\site\wwwroot\Quanta.ReportingAPI\dotnet-aspnet-codegenerator-design.exe' is denied.
   at Microsoft.Web.Deployment.NativeMethods.RaiseIOExceptionFromErrorCode(Win32ErrorCode errorCode, String maybeFullPath)
   at Microsoft.Web.Deployment.FileEx.Delete(String path)
   at Microsoft.Web.Deployment.FilePathProviderBase.Delete(Boolean whatIf)
Error count: 1.

2018-02-01T20:27:18.6046312Z ##[error]Error: C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe failed with return code: 4294967295
2018-02-01T20:27:19.2184426Z Adding release annotation for the Application Insights resource 'Quanta.Api.Insight.Dev'
2018-02-01T20:27:20.5718309Z Successfully added release annotation to the Application Insight : Quanta.Api.Insight.Dev
2018-02-01T20:27:21.9273552Z Successfully updated deployment History at https://quantawebapi-dev.scm.azurewebsites.net/api/deployments/8751517516840572
2018-02-01T20:27:21.9383299Z ##[section]Finishing: Azure App Service Deploy: QuantaWebAPI

``

Thanks

**Comment by vincentdass** [comment]
@elmalakai , Can you please try the steps provided [here](https://github.com/projectkudu/kudu/wiki/Dealing-with-locked-files-during-deployment) to find out the reason behind locked file?

**Comment by vincentdass** [comment]
@elmalakai , closing the issue. Feel free to re-open the thread or create a new one, if the link provided above doesn't solve the issue.
