### ISSUE TITLE
PowerShell on Target Machines - Deployments using 'test hub: machine groups' is no longer supported

### ISSUE THREAD

**Issue by thomasmktong** [Microsoft/vsts-tasks#6363]
## Environment
- Server - VSTS
- Agent - Private

## Issue Description

We use "Powershell on Target Machines" task for deployment and it is suddenly not working today. Error shown below.

### Error logs

```
2018-02-05T16:54:39.2854265Z ==============================================================================
2018-02-05T16:54:39.2854404Z Task         : PowerShell on Target Machines
2018-02-05T16:54:39.2854533Z Description  : Execute PowerShell scripts on remote machine(s)
2018-02-05T16:54:39.2854645Z Version      : 1.0.47
2018-02-05T16:54:39.2854751Z Author       : Microsoft Corporation
2018-02-05T16:54:39.2854880Z Help         : [More Information](https://go.microsoft.com/fwlink/?linkid=627414)
2018-02-05T16:54:39.2855139Z ==============================================================================
```

```
2018-02-05T16:54:42.9114310Z ##[debug]Unable to create a environment object for given json - Unexpected character encountered while parsing value: Q. Path '', line 0, position 0.
2018-02-05T16:54:45.9214309Z ##[error].};]
2018-02-05T16:54:45.9214614Z ##[debug]Processed: ##vso[task.logissue type=error;code={"Task_Internal_Error":Deployments using 'test hub: machine groups' is no longer supported. Refer to https://go.microsoft.com/fwlink/?LinkID=799742&clcid=0x409 for more information or get help from Developer Community [https://developercommunity.visualstudio.com/spaces/21/index.html].};]
2018-02-05T16:54:45.9214885Z 
2018-02-05T16:54:45.9214951Z 
2018-02-05T16:54:45.9255351Z ##[error]System.Management.Automation.ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Deployments using 'test hub: machine groups' is no longer supported. Refer to https://go.microsoft.com/fwlink/?LinkID=799742&clcid=0x409 for more information or get help from Developer Community [https://developercommunity.visualstudio.com/spaces/21/index.html].
2018-02-05T16:54:45.9255814Z ##[debug]Processed: ##vso[task.logissue type=error;]System.Management.Automation.ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Deployments using 'test hub: machine groups' is no longer supported. Refer to https://go.microsoft.com/fwlink/?LinkID=799742&clcid=0x409 for more information or get help from Developer Community [https://developercommunity.visualstudio.com/spaces/21/index.html].
2018-02-05T16:54:45.9256304Z    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
2018-02-05T16:54:45.9256553Z    at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
2018-02-05T16:54:45.9256738Z    at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
2018-02-05T16:54:45.9256907Z    at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2018-02-05T16:54:45.9257228Z    at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2018-02-05T16:54:45.9257539Z    at Microsoft.TeamFoundation.DistributedTask.Handlers.LegacyVSTSPowerShellHost.VSTSPowerShellHost.Main(String[] args)
2018-02-05T16:54:45.9380823Z ##[error]LegacyVSTSPowerShellHost.exe completed with return code: -1.
```

**Comment by kmkumaran** [comment]
@thomasmktong - As you can see from the error message, the usage of "machine groups" from "test hub" has been decommissioned. More details at https://go.microsoft.com/fwlink/?LinkID=799742&clcid=0x409. Please look for the guidance in the same page on how to move away from the "test hub: machine groups" usage.

If you are not using "test hub: machine groups" but still seeing this issue, then please mail your account name to RM_Customer_Queries@microsoft.com

**Comment by thomasmktong** [comment]
Thanks, just sent the email. We are not using "test hub: machine groups". Actually if that feature has retired since Jan 31st 2018 our jobs would have been failed for few days, but it only happened since yesterday.

**Comment by chshrikh** [comment]
@thomasmktong to unblock yourself, could you please change the task version to 2.x. We are looking to address the issue you reported in older version. Moving to 2.0 can unblock you faster.

**Comment by TheSquiffy** [comment]
Hi, it's happening here too, switching to 2.0 didn't solved. I'm still getting the same error.

**Comment by Shriram-A-R** [comment]
Same here...getting this same error on two of our release definitions even though we are using our own machines

**Comment by TheSquiffy** [comment]
Forgive me, I had to re-release process. Switching to 2.0 solved the problem.

**Comment by chshrikh** [comment]
@Shriram-A-R could you please try to switch to 2.x version of task and check if it works for you

**Comment by Shriram-A-R** [comment]
@chshrikh Thanks for the recommendation. Yes, switching to 2.* version worked for me as well.

**Comment by ljacobsenpc** [comment]
We also started to have this error in "Windows Machine File Copy" and "PowerShell on Target Machines" yesterday. We are not using "test hub: machine groups". Switching to version 2.* of both task types resolved the problem.

**Comment by chshrikh** [comment]
this has been fixed now
