### ISSUE TITLE
Current npm version (v3.10.8) does not handle optional dependencies when using shrinkwrap

### ISSUE THREAD

**Issue by ggirard07** [Microsoft/vsts-tasks#6395]
## Issue Description

1. Create a new build definition
2. Add a single NPM step
3. Configure NPM step as Custom with command as "install -g polymer-cli"
4. Save and run the definition on a VSTS Hosted Agent

## Expected result
Command should execute without any issue.

## Actual result
Command fails due to an optional package related to macOS platform being installed despite it is not necessary.

### Error logs
```
2018-02-09T15:14:08.5769237Z ==============================================================================
2018-02-09T15:14:08.5769398Z Task         : npm
2018-02-09T15:14:08.5769561Z Description  : Install and publish npm packages, or run an npm command. Supports npmjs.com and authenticated registries like Package Management.
2018-02-09T15:14:08.5769738Z Version      : 1.0.10
2018-02-09T15:14:08.5769850Z Author       : Microsoft Corporation
2018-02-09T15:14:08.5769977Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613746)
2018-02-09T15:14:08.5770246Z ==============================================================================
2018-02-09T15:14:09.4902747Z [command]C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files\nodejs\npm.cmd" --version"
2018-02-09T15:14:13.6905874Z 3.10.8
2018-02-09T15:14:16.9887815Z [command]C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files\nodejs\npm.cmd" config list"
2018-02-09T15:14:18.4614831Z ; cli configs
2018-02-09T15:14:18.4615481Z user-agent = "npm/3.10.8 node/v6.9.1 win32 x64"
2018-02-09T15:14:18.4615824Z 
2018-02-09T15:14:18.4615998Z ; environment configs
2018-02-09T15:14:18.4616254Z cache = "C:\\NPM\\Cache"
2018-02-09T15:14:18.4616446Z prefix = "C:\\NPM\\Modules"
2018-02-09T15:14:18.4616740Z userconfig = "D:\\a\\1\\npm\\33823.npmrc"
2018-02-09T15:14:18.4616880Z 
2018-02-09T15:14:18.4617419Z ; globalconfig C:\NPM\Modules\etc\npmrc
2018-02-09T15:14:18.4617642Z registry = "http://registry.npmjs.org/"
2018-02-09T15:14:18.4617782Z 
2018-02-09T15:14:18.4617957Z ; builtin config undefined
2018-02-09T15:14:18.4618109Z 
2018-02-09T15:14:18.4618297Z ; node bin location = C:\Program Files\nodejs\node.exe
2018-02-09T15:14:18.4618482Z ; cwd = D:\a\1\s
2018-02-09T15:14:18.4618661Z ; HOME = C:\Users\buildguest
2018-02-09T15:14:18.4618869Z ; "npm config ls -l" to show all defaults.
2018-02-09T15:14:18.4619008Z 
2018-02-09T15:14:18.4621692Z [command]C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files\nodejs\npm.cmd" install -g polymer-cli"
2018-02-09T15:15:20.3975302Z npm ERR! Windows_NT 6.3.9600
2018-02-09T15:15:20.3975860Z C:\NPM\Modules
2018-02-09T15:15:20.3979392Z npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "polymer-cli"
2018-02-09T15:15:20.3979695Z `-- (empty)
2018-02-09T15:15:20.3981781Z npm ERR! node v6.9.1
2018-02-09T15:15:20.3981882Z 
2018-02-09T15:15:20.4128290Z npm ERR! npm  v3.10.8
2018-02-09T15:15:20.4130039Z npm ERR! code EBADPLATFORM
2018-02-09T15:15:20.4130416Z 
2018-02-09T15:15:20.4130791Z npm ERR! notsup Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
2018-02-09T15:15:20.4131404Z npm ERR! notsup Valid OS:    darwin
2018-02-09T15:15:20.4131825Z npm ERR! notsup Valid Arch:  any
2018-02-09T15:15:20.4132147Z npm ERR! notsup Actual OS:   win32
2018-02-09T15:15:20.4132521Z npm ERR! notsup Actual Arch: x64
2018-02-09T15:15:20.4132828Z 
2018-02-09T15:15:20.4133307Z npm ERR! Please include the following file with any support request:
2018-02-09T15:15:20.4133681Z npm ERR!     D:\a\1\s\npm-debug.log
2018-02-09T15:15:20.4134059Z npm ERR! code 1
```
...
```
2018-02-09T15:15:20.7725926Z 113214 verbose stack Error: Unsupported platform for fsevents@1.1.3: wanted {"name":"fsevents","version":"1.1.3","description":"Native Access to Mac OS-X FSEvents","main":"fsevents.js","dependencies":{"nan":"^2.3.0","node-pre-gyp":"^0.6.39"},"os":["darwin"],"engines":{"node":">=0.8.0"},"scripts":{"install":"node install","prepublish":"if [ $(npm -v | head -c 1) -lt 3 ]; then exit 1; fi && npm dedupe","test":"tap ./test","node-pre-gyp":"node-pre-gyp"},"binary":{"module_name":"fse","module_path":"./lib/binding/{configuration}/{node_abi}-{platform}-{arch}/","remote_path":"./v{version}/","package_name":"{module_name}-v{version}-{node_abi}-{platform}-{arch}.tar.gz","host":"https://fsevents-binaries.s3-us-west-2.amazonaws.com"},"repository":{"type":"git","url":"git+https://github.com/strongloop/fsevents.git"},"keywords":["fsevents","mac"],"author":{"name":"Philipp Dunkel","email":"pip@pipobscure.com"},"license":"MIT","bugs":{"url":"https://github.com/strongloop/fsevents/issues"},"homepage":"https://github.com/strongloop/fsevents","devDependencies":{"tap":"~0.4.8"},"readme":"# fsevents [![NPM](https://nodei.co/npm/fsevents.png)](https://nodei.co/npm/fsevents/)\n\nNative access to OS X FSEvents in [Node.js](http://nodejs.org/)\n\nThe FSEvents API in OS X allows applications to register for notifications of\nchanges to a given directory tree. It is a very fast and lightweight alternative\nto kqueue.\n\nThis is a low-level library. For a cross-compatible file watching module that\nuses fsevents, check out [Chokidar](https://www.npmjs.com/package/chokidar).\n\n* [Module Site & GitHub](https://github.com/strongloop/fsevents)\n* [NPM Page](https://npmjs.org/package/fsevents)\n\n## Installation\n\n\t$ npm install fsevents\n\n## Usage\n\n```js\nvar fsevents = require('fsevents');\nvar watcher = fsevents(__dirname);\nwatcher.on('fsevent', function(path, flags, id) { }); // RAW Event as emitted by OS-X\nwatcher.on('change', function(path, info) { }); // Common Event for all changes\nwatcher.start() // To start observation\nwatcher.stop()  // To end observation\n```\n\n### Events\n\n * *fsevent* - RAW Event as emitted by OS-X\n * *change* - Common Event for all changes\n * *created* - A File-System-Item has been created\n * *deleted* - A File-System-Item has been deleted\n * *modified* - A File-System-Item has been modified\n * *moved-out* - A File-System-Item has been moved away from this location\n * *moved-in* - A File-System-Item has been moved into this location\n\nAll events except *fsevent* take an *info* object as the second parameter of the callback. The structure of this object is:\n\n```js\n{\n  \"event\": \"<event-type>\",\n  \"id\": <eventi-id>,\n  \"path\": \"<path-that-this-is-about>\",\n  \"type\": \"<file|directory|symlink>\",\n  \"changes\": {\n    \"inode\": true, // Has the iNode Meta-Information changed\n    \"finder\": false, // Has the Finder Meta-Data changed\n    \"access\": false, // Have the access permissions changed\n    \"xattrs\": false // Have the xAttributes changed\n  },\n  \"flags\": <raw-flags>\n}\n```\n\n## MIT License\n\nCopyright (C) 2010-2014 Philipp Dunkel\n\nPermission is hereby granted, free of charge, to any person obtaining a copy\nof this software and associated documentation files (the \"Software\"), to deal\nin the Software without restriction, including without limitation the rights\nto use, copy, modify, merge, publish, distribute, sublicense, and/or sell\ncopies of the Software, and to permit persons to whom the Software is\nfurnished to do so, subject to the following conditions:\n\nThe above copyright notice and this permission notice shall be included in\nall copies or substantial portions of the Software.\n\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\nFITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\nAUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\nLIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\nOUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN\nTHE SOFTWARE.\n","readmeFilename":"Readme.md","bundleDependencies":["node-pre-gyp"],"_id":"fsevents@1.1.3","_shasum":"11f82318f5fe7bb2cd22965a108e9306208216d8","_resolved":"https://registry.npmjs.org/fsevents/-/fsevents-1.1.3.tgz","_from":"fsevents@https://registry.npmjs.org/fsevents/-/fsevents-1.1.3.tgz","_inCache":true,"_requested":{"raw":"fsevents@https://registry.npmjs.org/fsevents/-/fsevents-1.1.3.tgz","scope":null,"escapedName":"fsevents","name":"fsevents","rawSpec":"https://registry.npmjs.org/fsevents/-/fsevents-1.1.3.tgz","spec":"https://registry.npmjs.org/fsevents/-/fsevents-1.1.3.tgz","type":"remote"},"_spec":"fsevents@https://registry.npmjs.org/fsevents/-/fsevents-1.1.3.tgz","_where":"C:\\NPM\\Modules\\node_modules\\polymer-cli","_args":[[{"raw":"fsevents@https://registry.npmjs.org/fsevents/-/fsevents-1.1.3.tgz","scope":null,"escapedName":"fsevents","name":"fsevents","rawSpec":"https://registry.npmjs.org/fsevents/-/fsevents-1.1.3.tgz","spec":"https://registry.npmjs.org/fsevents/-/fsevents-1.1.3.tgz","type":"remote"},"C:\\NPM\\Modules\\node_modules\\polymer-cli"]],"_shrinkwrap":null,"optionalDependencies":{}} (current: {"os":"win32","cpu":"x64"})
2018-02-09T15:15:20.7737947Z 113214 verbose stack     at checkPlatform (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-install-checks\index.js:45:14)
2018-02-09T15:15:20.7738253Z 113214 verbose stack     at thenWarnEngineIssues (C:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:41:5)
2018-02-09T15:15:20.7738430Z 113214 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\iferr\index.js:13:50
2018-02-09T15:15:20.7738593Z 113214 verbose stack     at checkEngine (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-install-checks\index.js:24:10)
2018-02-09T15:15:20.7738763Z 113214 verbose stack     at module.exports.isInstallable (C:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:38:3)
2018-02-09T15:15:20.7738939Z 113214 verbose stack     at actions.(anonymous function) (C:\Program Files\nodejs\node_modules\npm\lib\install\actions.js:52:14)
2018-02-09T15:15:20.7739094Z 113214 verbose stack     at execAction (C:\Program Files\nodejs\node_modules\npm\lib\install\actions.js:114:7)
2018-02-09T15:15:20.7739248Z 113214 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
2018-02-09T15:15:20.7739406Z 113214 verbose stack     at Array.forEach (native)
2018-02-09T15:15:20.7739542Z 113214 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
2018-02-09T15:15:20.7739670Z 113215 verbose pkgid fsevents@1.1.3
2018-02-09T15:15:20.7739786Z 113216 verbose cwd D:\a\1\s
2018-02-09T15:15:20.7739892Z 113217 error Windows_NT 6.3.9600
2018-02-09T15:15:20.7740044Z 113218 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "polymer-cli"
2018-02-09T15:15:20.7740196Z 113219 error node v6.9.1
2018-02-09T15:15:20.7740298Z 113220 error npm  v3.10.8
2018-02-09T15:15:20.7740401Z 113221 error code EBADPLATFORM
2018-02-09T15:15:20.7740554Z 113222 error notsup Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
2018-02-09T15:15:20.7740690Z 113223 error notsup Valid OS:    darwin
2018-02-09T15:15:20.7740863Z 113223 error notsup Valid Arch:  any
2018-02-09T15:15:20.7740973Z 113223 error notsup Actual OS:   win32
2018-02-09T15:15:20.7741094Z 113223 error notsup Actual Arch: x64
2018-02-09T15:15:20.7741199Z 113224 verbose exit [ 1, true ]
2018-02-09T15:15:20.7741266Z 
2018-02-09T15:15:20.7795203Z ##[error]Error: Npm failed with return code: 1
```

### Remarks
The dependency generating the error (`fsevents`) comes from the following dependency graph
```
C:\Users\me>npm-remote-ls polymer-cli
└─ polymer-cli@1.6.0
   ├─ ...
   ├─ chokidar@1.7.0
   │  ├─ ...
   │  ├─ fsevents@1.1.3
   │  │  ├─ ...
```
The dependecy from `chokidar` to `fsevents` is well defined as optional [here](https://github.com/paulmillr/chokidar/blob/master/package.json#L44).

When running the same command locally on a Windows 10 box (`npm/3.10.10 node/v7.3.0 win32 x64`), package installation is executed property (`fsevents` is reported as an optional package and is skipped):
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\polymer-cli\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
```

After narrowing down the issue, I noticed polymer-cli [is using a npm shrinkwrap to manage dependencies](https://github.com/Polymer/polymer-cli/blob/master/npm-shrinkwrap.json).
There is also [a known issue](https://github.com/npm/npm/issues/14042) about npm which does not handle well optional dependencies with shrinkwrap in v3.10.8.

Issue seems to be fixed by npm [v3.10.10](https://github.com/npm/npm/releases/tag/v3.10.10). Is it possible to include that update on the VSTS hosted agent?

**Comment by ggirard07** [comment]
Looks like only solution is to wait on https://github.com/Microsoft/vsts-image-generation/issues/13 to complete its deployment

**Comment by bryanmacfarlane** [comment]
You can use the node installer task in the box.  Pick the node 6.x (npm 3.x latest) or node 8.x (npm 5.x latest) to pull JIT.

No need to wait.

**Comment by bryanmacfarlane** [comment]
I would also recommend moving to npm 5.x (node 8.x) and use package lock files.  shrinkwrap is being deprecated

**Comment by ggirard07** [comment]
I update my build definition default queue to use a Hosted Agent VS2017 as this one is sourced with npm 5.x (node 8.x).
Shrinkwrap is used by a dependency we need to build our project and can't get ride of it.

**Comment by alexmullans** [comment]
Great. I'm going to close this since you're unblocked. As Bryan mentioned, you can also use the Node Tool Installer task to control the exact versions of Node and npm used in a particular build, regardless of what's on the agent.
