### ISSUE TITLE
ServiceFabricDeploy task is failing after updating the visual studio to 15.5.6 and service fabric v6.1

### ISSUE THREAD

**Issue by wahabakhtar** [Microsoft/vsts-tasks#6457]
## Environment
- Server - VSTS or TFS on-premises?
    - VSTS

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: Hosted Agent

## Issue Description
Service Fabric Deployment Task started failing after updating the Visual Studio 2017 to 15.5.6 release and building the solution. This update made changes to the Service Fabric project and when we checked-in the code, the deploy task start failing. The difference I have noticed is, the build output now has _manifests folder under ApplicationPackage\Code and I have no idea what this new folder does.

### Error logs

```
2018-02-16T01:25:32.8872095Z ##[debug]INPUT_OVERRIDEPUBLISHPROFILESETTINGS: 'false'
2018-02-16T01:25:32.9655173Z ##[debug]INPUT_USEDIFFPACKAGE: 'false'
2018-02-16T01:25:32.9741696Z ##[debug]INPUT_OVERWRITEBEHAVIOR: 'SameAppTypeAndVersion'
2018-02-16T01:25:33.4027863Z ##[debug]Join-Path "C:\Program Files\Microsoft Service Fabric\bin\fabric\fabric.code" "ServiceFabricServiceModel.xsd"
2018-02-16T01:25:33.4082854Z ##[debug]C:\Program Files\Microsoft Service Fabric\bin\fabric\fabric.code\ServiceFabricServiceModel.xsd
2018-02-16T01:25:33.4095672Z ##[debug]Length: 94
2018-02-16T01:25:33.4105628Z ##[debug]
2018-02-16T01:25:33.4128187Z ##[debug]Test-Path "C:\Program Files\Microsoft Service Fabric\bin\fabric\fabric.code\ServiceFabricServiceModel.xsd"
2018-02-16T01:25:33.4158892Z ##[debug]True
2018-02-16T01:25:33.4174165Z ##[debug]
2018-02-16T01:25:33.8303557Z ##[debug]System.Fabric.Management.ImageBuilder.FabricImageBuilderValidationException: Exception while parsing XML file: C:\Users\buildguest\AppData\Local\Temp\TestApplicationPackage_4082260934\1bnmsoge.nt1\applicationpackage\ApplicationManifest.xml
2018-02-16T01:25:33.8315037Z ##[debug]FileName: C:\Users\buildguest\AppData\Local\Temp\TestApplicationPackage_4082260934\1bnmsoge.nt1\applicationpackage\ApplicationManifest.xml ---> System.InvalidOperationException: There is an error in XML document (2, 272). ---> System.Xml.Schema.XmlSchemaValidationException: The 'ManifestId' attribute is not declared.
2018-02-16T01:25:33.8327126Z ##[debug]   at System.Xml.Schema.XmlSchemaValidator.SendValidationEvent(XmlSchemaValidationException e, XmlSeverityType severity)
2018-02-16T01:25:33.8337915Z ##[debug]   at System.Xml.Schema.XmlSchemaValidator.SendValidationEvent(String code, String arg)
2018-02-16T01:25:33.8350159Z ##[debug]   at System.Xml.Schema.XmlSchemaValidator.ValidateAttribute(String lName, String ns, XmlValueGetter attributeValueGetter, String attributeStringValue, XmlSchemaInfo schemaInfo)
2018-02-16T01:25:33.8362080Z ##[debug]   at System.Xml.Schema.XmlSchemaValidator.ValidateAttribute(String localName, String namespaceUri, XmlValueGetter attributeValue, XmlSchemaInfo schemaInfo)
2018-02-16T01:25:33.8372481Z ##[debug]   at System.Xml.XsdValidatingReader.ValidateAttributes()
2018-02-16T01:25:33.8384306Z ##[debug]   at System.Xml.XsdValidatingReader.ProcessElementEvent()
2018-02-16T01:25:33.8396321Z ##[debug]   at System.Xml.XsdValidatingReader.Read()
2018-02-16T01:25:33.8406772Z ##[debug]   at System.Xml.XmlReader.MoveToContent()
2018-02-16T01:25:33.8418667Z ##[debug]   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read395_ApplicationManifest()
2018-02-16T01:25:33.8430428Z ##[debug]   --- End of inner exception stack trace ---
2018-02-16T01:25:33.8441057Z ##[debug]   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
2018-02-16T01:25:34.4720539Z ##[debug]   at System.Fabric.Management.ImageBuilder.ImageBuilderUtility.ReadXml[T](String fileName, XmlReader reader)
2018-02-16T01:25:34.4722506Z ##[debug]   --- End of inner exception stack trace ---
2018-02-16T01:25:34.4723288Z ##[debug]   at System.Fabric.Management.ImageBuilder.ImageBuilderUtility.TraceAndThrowValidationErrorWithFileName(Exception innerException, String type, String fileName, String format, Object[] args)
2018-02-16T01:25:34.4724551Z ##[debug]   at System.Fabric.Management.ImageBuilder.ImageBuilderUtility.ReadXml[T](String fileName, XmlReader reader)
2018-02-16T01:25:34.4725077Z ##[debug]   at System.Fabric.Management.ImageBuilder.ImageBuilderUtility.ReadXml[T](String fileName, XmlReaderSettings validatingXmlReaderSettings)
2018-02-16T01:25:34.4725691Z ##[debug]   at System.Fabric.Management.ImageBuilder.ApplicationProvisionOperation.<ParseApplicationPackageAsync>d__8.MoveNext()
2018-02-16T01:25:34.4726148Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
2018-02-16T01:25:34.4726558Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2018-02-16T01:25:34.4726997Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-02-16T01:25:34.4727436Z ##[debug]   at System.Fabric.Management.ImageBuilder.ApplicationProvisionOperation.<ProvisionApplicationAsync>d__0.MoveNext()
2018-02-16T01:25:34.4727890Z ##[debug]Leaving D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.6.0\deploy.ps1.
2018-02-16T01:25:34.4728285Z ##[debug]Caught exception from task script.
2018-02-16T01:25:34.4728629Z ##[debug]Error record:
2018-02-16T01:25:34.4729213Z ##[debug]Test-ServiceFabricApplicationPackage : Exception while parsing XML file: C:\Users\buildguest\AppData\Local\Temp\TestApplicationPackage_4082260934\1bnmsoge.nt1\applicationpackage\ApplicationManifest.xml
2018-02-16T01:25:34.4730448Z ##[debug]FileName: C:\Users\buildguest\AppData\Local\Temp\TestApplicationPackage_4082260934\1bnmsoge.nt1\applicationpackage\ApplicationManifest.xml
2018-02-16T01:25:34.4731069Z ##[debug]At D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.6.0\ServiceFabricSDK\Publish-NewServiceFabricApplication.ps1:138 char:38
2018-02-16T01:25:34.4731600Z ##[debug]+ ... tionSuccess = (Test-ServiceFabricApplicationPackage $AppPkgPathToUse)
2018-02-16T01:25:34.4732055Z ##[debug]+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2018-02-16T01:25:34.4732568Z ##[debug]    + CategoryInfo          : InvalidOperation: (:) [Test-ServiceFabricApplicationPackage], FabricImageBuilderValidati    onException
2018-02-16T01:25:34.4733225Z ##[debug]    + FullyQualifiedErrorId : TestApplicationPackageErrorId,Microsoft.ServiceFabric.Powershell.TestApplicationPackage
2018-02-16T01:25:34.4733670Z ##[debug] 
2018-02-16T01:25:34.4734012Z ##[debug]Script stack trace:
2018-02-16T01:25:34.4734512Z ##[debug]at Publish-NewServiceFabricApplication, D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.6.0\ServiceFabricSDK\Publish-NewServiceFabricApplication.ps1: line 138
2018-02-16T01:25:34.4735322Z ##[debug]at <ScriptBlock>, D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.6.0\deploy.ps1: line 165
2018-02-16T01:25:34.4735797Z ##[debug]at <ScriptBlock>, <No file>: line 1
2018-02-16T01:25:34.4736185Z ##[debug]at <ScriptBlock>, <No file>: line 22
2018-02-16T01:25:34.4736711Z ##[debug]at <ScriptBlock>, <No file>: line 18
2018-02-16T01:25:34.4737182Z ##[debug]at <ScriptBlock>, <No file>: line 1
2018-02-16T01:25:34.4737552Z ##[debug]Exception:
2018-02-16T01:25:34.4738225Z ##[debug]System.Fabric.Management.ImageBuilder.FabricImageBuilderValidationException: Exception while parsing XML file: C:\Users\buildguest\AppData\Local\Temp\TestApplicationPackage_4082260934\1bnmsoge.nt1\applicationpackage\ApplicationManifest.xml
2018-02-16T01:25:34.4739098Z ##[debug]FileName: C:\Users\buildguest\AppData\Local\Temp\TestApplicationPackage_4082260934\1bnmsoge.nt1\applicationpackage\ApplicationManifest.xml ---> System.InvalidOperationException: There is an error in XML document (2, 272). ---> System.Xml.Schema.XmlSchemaValidationException: The 'ManifestId' attribute is not declared.
2018-02-16T01:25:34.4740209Z ##[debug]   at System.Xml.Schema.XmlSchemaValidator.SendValidationEvent(XmlSchemaValidationException e, XmlSeverityType severity)
2018-02-16T01:25:34.4740736Z ##[debug]   at System.Xml.Schema.XmlSchemaValidator.SendValidationEvent(String code, String arg)
2018-02-16T01:25:34.4741269Z ##[debug]   at System.Xml.Schema.XmlSchemaValidator.ValidateAttribute(String lName, String ns, XmlValueGetter attributeValueGetter, String attributeStringValue, XmlSchemaInfo schemaInfo)
2018-02-16T01:25:34.4741977Z ##[debug]   at System.Xml.Schema.XmlSchemaValidator.ValidateAttribute(String localName, String namespaceUri, XmlValueGetter attributeValue, XmlSchemaInfo schemaInfo)
2018-02-16T01:25:34.4752887Z ##[debug]   at System.Xml.XsdValidatingReader.ValidateAttributes()
2018-02-16T01:25:34.4757534Z ##[debug]   at System.Xml.XsdValidatingReader.ProcessElementEvent()
2018-02-16T01:25:34.4768679Z ##[debug]   at System.Xml.XsdValidatingReader.Read()
2018-02-16T01:25:34.4779445Z ##[debug]   at System.Xml.XmlReader.MoveToContent()
2018-02-16T01:25:34.4790294Z ##[debug]   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read395_ApplicationManifest()
2018-02-16T01:25:34.4800287Z ##[debug]   --- End of inner exception stack trace ---
2018-02-16T01:25:34.4813351Z ##[debug]   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
2018-02-16T01:25:34.4822184Z ##[debug]   at System.Fabric.Management.ImageBuilder.ImageBuilderUtility.ReadXml[T](String fileName, XmlReader reader)
2018-02-16T01:25:34.4831864Z ##[debug]   --- End of inner exception stack trace ---
2018-02-16T01:25:34.4842456Z ##[debug]   at System.Fabric.Management.ImageBuilder.ImageBuilderUtility.TraceAndThrowValidationErrorWithFileName(Exception innerException, String type, String fileName, String format, Object[] args)
2018-02-16T01:25:34.4853348Z ##[debug]   at System.Fabric.Management.ImageBuilder.ImageBuilderUtility.ReadXml[T](String fileName, XmlReader reader)
2018-02-16T01:25:34.4863970Z ##[debug]   at System.Fabric.Management.ImageBuilder.ImageBuilderUtility.ReadXml[T](String fileName, XmlReaderSettings validatingXmlReaderSettings)
2018-02-16T01:25:34.4874197Z ##[debug]   at System.Fabric.Management.ImageBuilder.ApplicationProvisionOperation.<ParseApplicationPackageAsync>d__8.MoveNext()
2018-02-16T01:25:34.4884077Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
2018-02-16T01:25:34.4895713Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2018-02-16T01:25:34.4906000Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-02-16T01:25:34.4916364Z ##[debug]   at System.Fabric.Management.ImageBuilder.ApplicationProvisionOperation.<ProvisionApplicationAsync>d__0.MoveNext()
2018-02-16T01:25:34.5121360Z ##[error]Exception while parsing XML file: C:\Users\buildguest\AppData\Local\Temp\TestApplicationPackage_4082260934\1bnmsoge.nt1\applicationpackage\ApplicationManifest.xml
FileName: C:\Users\buildguest\AppData\Local\Temp\TestApplicationPackage_4082260934\1bnmsoge.nt1\applicationpackage\ApplicationManifest.xml
2018-02-16T01:25:34.5122362Z ##[debug]Processed: ##vso[task.logissue type=error]Exception while parsing XML file: C:\Users\buildguest\AppData\Local\Temp\TestApplicationPackage_4082260934\1bnmsoge.nt1\applicationpackage\ApplicationManifest.xml%0D%0AFileName: C:\Users\buildguest\AppData\Local\Temp\TestApplicationPackage_4082260934\1bnmsoge.nt1\applicationpackage\ApplicationManifest.xml
2018-02-16T01:25:34.5123954Z ##[debug]Processed: ##vso[task.complete result=Failed]
2018-02-16T01:25:34.5581147Z ##[section]Finishing: Deploy Service Fabric Application]
```

**Comment by bishal-pdMSFT** [comment]
@NCarlsonMSFT , has there been a recent change in VS tooling to cause this behavior? Hosted agent is currently having SF SDK 3.0.456.9494

**Comment by ericsciple** [comment]
@wahabakhtar note, the `Hosted` queue has VS 2015, and the `Hosted VS2017` queue has VS 2017. I may be off here, but if you are using VS 2017 locally, you might want to give the `Hosted VS2017` queue a try.

**Comment by wahabakhtar** [comment]
@ericsciple it does seem to throw a different error on `Hosted2017`, i.e Application with the same name and version number exist on the cluster, You must first remove the existing application before a new application can be deployed or provide a new name for the application. Is there a configuration on the task that can force the existing build to be pushed to the cluster?

**Comment by bishal-pdMSFT** [comment]
@wahabakhtar the task is rightly failing as you would already have deployed application with same app type and version earlier. If you want to task to uninstall old application first, you should set "Overwrite behavior" input(in 'Advanced settings' of task) to either Always or SameAppTypeAndVersion

**Comment by wahabakhtar** [comment]
@bishal-pdMSFT after making your recommended changes and using `Hosted VS2017` queue, it does seems to solve the problem. So, is it primarily due the SDK difference on each queue?

**Comment by bishal-pdMSFT** [comment]
Yes, Hosted pool has VS2015 with corresponding SF tools and it is not actively updated anymore. HostedVS2017 has VS2017 and corresponding SF tools and is updated regularly.
