### ISSUE TITLE
`PowerShell on Target Machines` does not process scripts using non-interactive account correctly

### ISSUE THREAD

**Issue by bergmeister** [Microsoft/vsts-tasks#6469]
## Environment
    
VSTS

Agent: Private
    
Agent.OS | Windows_NT
Agent.OSVersion | 10.0.14393
Agent.Version | 2.126.0

## Issue Description

I am using the `PowerShell on Target Machines` task (v1 and v2) with a non-interactive user account. This works generally fine , but calling `Invoke-Pester` fails (using Pester v 41.1. and 4.2.0) with this error message:

 > A command that prompts the user failed because the host program or the command type does not support user interaction. Try a host program that supports user interaction, such as the Windows PowerShell Console or Windows PowerShell ISE, and remove prompt-related commands from command types that do not support user interaction, such as Windows 

This does not happen when executing the `Invoke-Pester` command myself via `Invoke-Command -ScriptBlock -Credential`, therefore the VSTS task is to blame.

### Error logs

````
2018-02-19T13:19:27.3864541Z 	 Deployment started on target machine...
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z System.AggregateException: Failed to execute the powershell script. Consult the logs below for details of the error.
2018-02-19T13:19:27.3864541Z A command that prompts the user failed because the host program or the command type does not support user interaction. Try a host program that supports user interaction, such as the Windows PowerShell Console or Windows PowerShell ISE, and remove prompt-related commands from command types that do not support user interaction, such as Windows PowerShell workflows. ---> System.Management.Automation.CmdletInvocationException: A command that prompts the user failed because the host program or the command type does not support user interaction. Try a host program that supports user interaction, such as the Windows PowerShell Console or Windows PowerShell ISE, and remove prompt-related commands from command types that do not support user interaction, such as Windows PowerShell workflows. ---> System.Management.Automation.Host.HostException: A command that prompts the user failed because the host program or the command type does not support user interaction. Try a host program that supports user interaction, such as the Windows PowerShell Console or Windows PowerShell ISE, and remove prompt-related commands from command types that do not support user interaction, such as Windows PowerShell workflows.
2018-02-19T13:19:27.3864541Z    at System.Management.Automation.Internal.Host.InternalHostRawUserInterface.ThrowNotInteractive()
2018-02-19T13:19:27.3864541Z    at System.Management.Automation.Internal.Host.InternalHostRawUserInterface.get_BackgroundColor()
2018-02-19T13:19:27.3864541Z    at Microsoft.PowerShell.Commands.ConsoleColorCmdlet.get_BackgroundColor()
2018-02-19T13:19:27.3864541Z    at Microsoft.PowerShell.Commands.WriteHostCommand.ProcessRecord()
2018-02-19T13:19:27.3864541Z    at System.Management.Automation.CommandProcessor.ProcessRecord()
2018-02-19T13:19:27.3864541Z    --- End of inner exception stack trace ---
2018-02-19T13:19:27.3864541Z    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
2018-02-19T13:19:27.3864541Z    at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
2018-02-19T13:19:27.3864541Z    at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
2018-02-19T13:19:27.3864541Z    at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2018-02-19T13:19:27.3864541Z    at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2018-02-19T13:19:27.3864541Z    at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
2018-02-19T13:19:27.3864541Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Deployment.PowershellExecutor.<>c__DisplayClass28_0.<Invoke>b__0()
2018-02-19T13:19:27.3864541Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Utilities.RetryExecutor.<>c__DisplayClass19_0`1.<Execute>b__0()
2018-02-19T13:19:27.3864541Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Utilities.RetryExecutor.Execute(Action action)
2018-02-19T13:19:27.3864541Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Utilities.RetryExecutor.Execute[T](Func`1 action)
2018-02-19T13:19:27.3864541Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Deployment.PowershellExecutor.Invoke(String errorContextMessage, Boolean writeResultToLog, Boolean isCancellable, ActionPreference errorActionPreference)
2018-02-19T13:19:27.3864541Z    --- End of inner exception stack trace ---
2018-02-19T13:19:27.3864541Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Deployment.PowershellExecutor.Invoke(String errorContextMessage, Boolean writeResultToLog, Boolean isCancellable, ActionPreference errorActionPreference)
2018-02-19T13:19:27.3864541Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Deployment.ScriptExecutor.ExecuteScript(IPowerShell powerShell, String script, String arguments, Boolean isScriptDotSourced, Boolean useHttp)
2018-02-19T13:19:27.3864541Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Deployment.DeploymentService.RunPowerShellScripts(DeploymentMachineSpecification deploymentMachine, ScriptSpecification scriptSpecification, ScriptSpecification initializationScriptSpecification, String applicationPath, IPowerShell powerShellSession)
2018-02-19T13:19:27.3864541Z ---> (Inner Exception #0) System.Management.Automation.CmdletInvocationException: A command that prompts the user failed because the host program or the command type does not support user interaction. Try a host program that supports user interaction, such as the Windows PowerShell Console or Windows PowerShell ISE, and remove prompt-related commands from command types that do not support user interaction, such as Windows PowerShell workflows. ---> System.Management.Automation.Host.HostException: A command that prompts the user failed because the host program or the command type does not support user interaction. Try a host program that supports user interaction, such as the Windows PowerShell Console or Windows PowerShell ISE, and remove prompt-related commands from command types that do not support user interaction, such as Windows PowerShell workflows.
2018-02-19T13:19:27.3864541Z    at System.Management.Automation.Internal.Host.InternalHostRawUserInterface.ThrowNotInteractive()
2018-02-19T13:19:27.3864541Z    at System.Management.Automation.Internal.Host.InternalHostRawUserInterface.get_BackgroundColor()
2018-02-19T13:19:27.3864541Z    at Microsoft.PowerShell.Commands.ConsoleColorCmdlet.get_BackgroundColor()
2018-02-19T13:19:27.3864541Z    at Microsoft.PowerShell.Commands.WriteHostCommand.ProcessRecord()
2018-02-19T13:19:27.3864541Z    at System.Management.Automation.CommandProcessor.ProcessRecord()
2018-02-19T13:19:27.3864541Z    --- End of inner exception stack trace ---
2018-02-19T13:19:27.3864541Z    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
2018-02-19T13:19:27.3864541Z    at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
2018-02-19T13:19:27.3864541Z    at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
2018-02-19T13:19:27.3864541Z    at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2018-02-19T13:19:27.3864541Z    at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2018-02-19T13:19:27.3864541Z    at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
2018-02-19T13:19:27.3864541Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Deployment.PowershellExecutor.<>c__DisplayClass28_0.<Invoke>b__0()
2018-02-19T13:19:27.3864541Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Utilities.RetryExecutor.<>c__DisplayClass19_0`1.<Execute>b__0()
2018-02-19T13:19:27.3864541Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Utilities.RetryExecutor.Execute(Action action)
2018-02-19T13:19:27.3864541Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Utilities.RetryExecutor.Execute[T](Func`1 action)
2018-02-19T13:19:27.3864541Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Deployment.PowershellExecutor.Invoke(String errorContextMessage, Boolean writeResultToLog, Boolean isCancellable, ActionPreference errorActionPreference)<---
2018-02-19T13:19:27.3864541Z Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\Pester\lib\legacy\Gherkin.dll'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\Pester\Dependencies\Axiom\Axiom.psm1'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Exporting function 'Verify-Equal'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Exporting function 'Verify-True'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Exporting function 'Verify-False'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Exporting function 'Verify-Null'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Exporting function 'Verify-NotNull'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Exporting function 'Verify-Same'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Exporting function 'Verify-NotSame'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Exporting function 'Verify-Throw'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Exporting function 'Verify-Type'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Exporting function 'Verify-AssertionFailed'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z The 'Verify-AssertionFailed' command in the Axiom' module was imported, but because its name does not include an approved verb, it might be difficult to find. The suggested alternative verbs are "Test".
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Importing function 'Verify-AssertionFailed'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z The 'Verify-Equal' command in the Axiom' module was imported, but because its name does not include an approved verb, it might be difficult to find. The suggested alternative verbs are "Test".
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Importing function 'Verify-Equal'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z The 'Verify-False' command in the Axiom' module was imported, but because its name does not include an approved verb, it might be difficult to find. The suggested alternative verbs are "Test".
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Importing function 'Verify-False'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z The 'Verify-NotNull' command in the Axiom' module was imported, but because its name does not include an approved verb, it might be difficult to find. The suggested alternative verbs are "Test".
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Importing function 'Verify-NotNull'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z The 'Verify-NotSame' command in the Axiom' module was imported, but because its name does not include an approved verb, it might be difficult to find. The suggested alternative verbs are "Test".
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Importing function 'Verify-NotSame'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z The 'Verify-Null' command in the Axiom' module was imported, but because its name does not include an approved verb, it might be difficult to find. The suggested alternative verbs are "Test".
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Importing function 'Verify-Null'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z The 'Verify-Same' command in the Axiom' module was imported, but because its name does not include an approved verb, it might be difficult to find. The suggested alternative verbs are "Test".
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Importing function 'Verify-Same'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z The 'Verify-Throw' command in the Axiom' module was imported, but because its name does not include an approved verb, it might be difficult to find. The suggested alternative verbs are "Test".
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Importing function 'Verify-Throw'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z The 'Verify-True' command in the Axiom' module was imported, but because its name does not include an approved verb, it might be difficult to find. The suggested alternative verbs are "Test".
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Importing function 'Verify-True'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z The 'Verify-Type' command in the Axiom' module was imported, but because its name does not include an approved verb, it might be difficult to find. The suggested alternative verbs are "Test".
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Importing function 'Verify-Type'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Exporting function 'Context'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Exporting function 'Describe'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Exporting function 'In'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Exporting function 'It'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Exporting function 'Mock'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Exporting function 'Assert-VerifiableMock'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Exporting function 'Assert-MockCalled'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Exporting function 'Set-TestInconclusive'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Exporting function 'Assert-VerifiableMocks'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Exporting function 'InModuleScope'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Exporting function 'Invoke-Mock'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Exporting function 'New-Fixture'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Exporting function 'Get-TestDriveItem'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Exporting function 'Setup'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Exporting function 'Should'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Exporting function 'Invoke-Pester'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Exporting function 'BeforeEach'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Exporting function 'AfterEach'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Exporting function 'BeforeAll'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Exporting function 'AfterAll'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Exporting function 'Set-DynamicParameterVariable'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Exporting function 'Get-MockDynamicParameter'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Exporting function 'New-PesterOption'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Exporting function 'SafeGetCommand'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Exporting function 'Invoke-Gherkin'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Exporting function 'Find-GherkinStep'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Exporting function 'BeforeEachFeature'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Exporting function 'AfterEachFeature'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Exporting function 'BeforeEachScenario'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Exporting function 'AfterEachScenario'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Exporting function 'GherkinStep'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Exporting alias 'Given'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Exporting alias 'When'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Exporting alias 'Then'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Exporting alias 'And'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Exporting alias 'But'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Exporting function 'Add-AssertionOperator'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Exporting function 'New-MockObject'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Exporting function 'EnterTestGroup'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Exporting function 'LeaveTestGroup'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Exporting function 'AddTestResult'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Exporting function 'AddSetupOrTeardownBlock'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Exporting function 'GetTestCaseSetupBlocks'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Exporting function 'GetTestCaseTeardownBlocks'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Exporting function 'GetCurrentTestGroupSetupBlocks'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Exporting function 'GetCurrentTestGroupTeardownBlocks'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Exporting function 'EnterTest'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Exporting function 'LeaveTest'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Exporting variable 'Strict'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Exporting variable 'Show'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.3864541Z Exporting variable 'TagFilter'.
2018-02-19T13:19:27.3864541Z 
2018-02-19T13:19:27.4027575Z Exporting variable 'ExcludeTagFilter'.
2018-02-19T13:19:27.4027575Z 
2018-02-19T13:19:27.4027575Z Exporting variable 'TestNameFilter'.
2018-02-19T13:19:27.4027575Z 
2018-02-19T13:19:27.4027575Z Exporting variable 'SessionState'.
2018-02-19T13:19:27.4027575Z 
2018-02-19T13:19:27.4027575Z Exporting variable 'CommandCoverage'.
2018-02-19T13:19:27.4027575Z 
2018-02-19T13:19:27.4027575Z Exporting variable 'InTest'.
2018-02-19T13:19:27.4027575Z 
2018-02-19T13:19:27.4027575Z Exporting variable 'TestResult'.
2018-02-19T13:19:27.4027575Z 
2018-02-19T13:19:27.4027575Z Exporting variable 'TotalCount'.
2018-02-19T13:19:27.4027575Z 
2018-02-19T13:19:27.4027575Z Exporting variable 'Time'.
2018-02-19T13:19:27.4027575Z 
2018-02-19T13:19:27.4027575Z Exporting variable 'PassedCount'.
2018-02-19T13:19:27.4027575Z 
2018-02-19T13:19:27.4027575Z Exporting variable 'FailedCount'.
2018-02-19T13:19:27.4027575Z 
2018-02-19T13:19:27.4027575Z Exporting variable 'SkippedCount'.
2018-02-19T13:19:27.4027575Z 
2018-02-19T13:19:27.4027575Z Exporting variable 'PendingCount'.
2018-02-19T13:19:27.4027575Z 
2018-02-19T13:19:27.4027575Z Exporting variable 'InconclusiveCount'.
2018-02-19T13:19:27.4027575Z 
2018-02-19T13:19:27.4027575Z Exporting variable 'IncludeVSCodeMarker'.
2018-02-19T13:19:27.4027575Z 
2018-02-19T13:19:27.4027575Z Exporting variable 'TestSuiteName'.
2018-02-19T13:19:27.4027575Z 
2018-02-19T13:19:27.4027575Z Exporting variable 'TestActions'.
2018-02-19T13:19:27.4027575Z 
2018-02-19T13:19:27.4027575Z Exporting variable 'TestGroupStack'.
2018-02-19T13:19:27.4027575Z 
2018-02-19T13:19:27.4027575Z 
2018-02-19T13:19:27.4027575Z 
2018-02-19T13:19:27.4027575Z Deployment status for machine '**************.com:5985' : 'Failed'
2018-02-19T13:19:27.8083540Z ##[error]A command that prompts the user failed because the host program or the command type does not support user interaction. Try a host program that supports user interaction, such as the Windows PowerShell Console or Windows PowerShell ISE, and remove prompt-related commands from command types that do not support user interaction, such as Windows PowerShell workflows.
````

**Comment by chshrikh** [comment]
@bergmeister the task does not support the interactive commands execution. Could you please try to consider the option of invoking the pester with PassThru argument. Here you can find the details 

https://github.com/pester/Pester/wiki/Invoke-Pester#example-5

**Comment by chshrikh** [comment]
@bergmeister are you got unblocked here

**Comment by bergmeister** [comment]
I am doing the remoting using Invoke-Command myself now as a workaround and there is no interactive command execution.

**Comment by chshrikh** [comment]
closing this as @bergmeister is not blocked on this. We will update this once new version of task is available
