### ISSUE TITLE
[ServiceFabricDeploy] Unable to upgrade to same version

### ISSUE THREAD

**Issue by atifield** [Microsoft/vsts-tasks#6481]
## Environment
VSTS, Microsoft account, ICE org, releaseId 541
Universal Store Agent Pool

## Issue Description

[ServiceFabricDeploy] version 1.6.1 unable to upgrade same version of application even though script source says it could. Error is Unregister-ServiceFabricApplicationType : Application type and version is still in use

Please note in the error log "Unregister-ServiceFabricApplicationType" is exceptioned out on line 222 even though v1.6.1 already did checks to skip unregistering app type and not calling unregister on line 222.

### Error logs

2018-02-21T07:28:44.7249939Z ==============================================================================
2018-02-21T07:28:44.7250317Z Task         : Service Fabric Application Deployment
2018-02-21T07:28:44.7250938Z Description  : Deploy a Service Fabric application to a cluster.
2018-02-21T07:28:44.7251573Z Version      : 1.6.1
2018-02-21T07:28:44.7251866Z Author       : Microsoft Corporation
2018-02-21T07:28:44.7252195Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=820528)
2018-02-21T07:28:44.7252543Z ==============================================================================

....

2018-02-21T07:28:51.5766205Z Application type 'ICE.Service.Gateway' and version '1.0.0.20180213.1_master' was already registered with the cluster, unregistering it...
2018-02-21T07:28:51.6238220Z ##[debug]System.Fabric.FabricException: Application type and version is still in use ---> System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x80071BDB
2018-02-21T07:28:51.6257759Z ##[debug]   at System.Fabric.Interop.NativeClient.IFabricApplicationManagementClient10.EndUnprovisionApplicationType(IFabricAsyncOperationContext context)
2018-02-21T07:28:51.6277062Z ##[debug]   at System.Fabric.Interop.Utility.<>c__DisplayClass22_0.<WrapNativeAsyncInvoke>b__0(IFabricAsyncOperationContext context)
2018-02-21T07:28:51.6296135Z ##[debug]   at System.Fabric.Interop.AsyncCallOutAdapter2`1.Finish(IFabricAsyncOperationContext context, Boolean expectedCompletedSynchronously)
2018-02-21T07:28:51.6315911Z ##[debug]   --- End of inner exception stack trace ---
2018-02-21T07:28:51.6667127Z ##[debug]Leaving E:\agent_work\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.6.1\deploy.ps1.
2018-02-21T07:28:51.6985299Z ##[debug]Caught exception from task script.
2018-02-21T07:28:51.7021433Z ##[debug]Error record:
2018-02-21T07:28:51.8058408Z ##[debug]Unregister-ServiceFabricApplicationType : Application type and version is still in use
2018-02-21T07:28:51.8074137Z ##[debug]At E:\agent_work\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.6.1\ServiceFabricSDK\Publish-UpgradedServiceFabricApplication.ps1:222 char:20
2018-02-21T07:28:51.8089933Z ##[debug]+             $reg | Unregister-ServiceFabricApplicationType -Force
2018-02-21T07:28:51.8106760Z ##[debug]+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2018-02-21T07:28:51.8126347Z ##[debug]    + CategoryInfo          : InvalidOperation: (Microsoft.Servi...usterConnection:ClusterConnection) [Unregister-Serv    iceFabricApplicationType], FabricException
2018-02-21T07:28:51.8141710Z ##[debug]    + FullyQualifiedErrorId : UnregisterApplicationTypeErrorId,Microsoft.ServiceFabric.Powershell.UnregisterApplicatio    nType
2018-02-21T07:28:51.8158921Z ##[debug]

**Comment by bishal-pdMSFT** [comment]
@atifield could you please provide more details on why you think this is an issue. Is the application type not already in use? Could you please point me to failing release?

**Comment by atifield** [comment]
Hi my MSFT alias is erhuan. Ping me directly if you need any more details:

Here is release that shows the issue:

https://microsoft.visualstudio.com/ICE/_release?releaseId=540&_a=release-logs

I am trying to upgrade to the same manifest version that is on cluster already BUT the application parameter has changed. According to the script it should already worked by skipping unregister application type but it didn't work and always try to unregister application first.

You can see the exception message does not correspond to the commit that is related to the version of the task. I have since taken the release task and convert into just powershell scripts and it worked fine.


Eric
________________________________

**Comment by bishal-pdMSFT** [comment]
@atifield i do not have access to above project
It seems the release is quite old. have you re-tried same scenario recently? The task code you are seeing is latest, but the task version you used(as per the logs above) is old. We did some changes to handle already in-use app types in the meawhile. 
Please let me know if you still see this issue.

**Comment by bishal-pdMSFT** [comment]
@atifield is there an update?

**Comment by atifield** [comment]
Hi, sorry this had fallen off the radar. I will test this again today. I did notice the task version has been updated so it might just work.
________________________________

**Comment by atifield** [comment]
Hi, I have tested this again and the original issue is no longer reproducible. The task version has been updated and I noticed the new script path is used so it will now attempt to upgrade even if the manifest version is the same. Now it will fail because application parameter has not been changed but that is a valid fail case. You can close the issue now. Thank you!
________________________________
