### ISSUE TITLE
Unable to run cloud based load test in VSO build definition.

### ISSUE THREAD

**Issue by abdulrahaman7** [Microsoft/vsts-tasks#6530]
Unable to run cloud based load test in VSO build definition, getting exception
System.Management.Automation.MethodInvocationException: Exception calling "FindServicePoint" with "1" argument(s): "This operation is not supported for a relative URI." ---> System.InvalidOperationException: This operation is not supported for a relative URI.

I created a generic service endpoint for this task with server url as: https://microsoftit.visualstudio.com/ with my login credentials.

Complete log of cloud based load test task:
2018-02-26T09:43:14.7644640Z ##[section]Starting: Microsoft.Offerings.QueryAllItems
2018-02-26T09:43:14.7648756Z ==============================================================================
2018-02-26T09:43:14.7649045Z Task         : Cloud-based Load Test
2018-02-26T09:43:14.7649320Z Description  : Runs the load test in the cloud with Visual Studio Team Services
2018-02-26T09:43:14.7649597Z Version      : 1.0.25
2018-02-26T09:43:14.7649830Z Author       : Microsoft Corporation
2018-02-26T09:43:14.7650178Z Help         : This task triggers a cloud-based load test using Visual Studio Team Services. [Learn more](https://go.microsoft.com/fwlink/?linkid=546976)
2018-02-26T09:43:14.7650564Z ==============================================================================
2018-02-26T09:43:14.7732042Z Preparing task execution handler.
2018-02-26T09:43:20.3146301Z Executing the powershell script: D:\a\_tasks\CloudLoadTest_9e9db38a-b40b-4c13-b7f0-31031c894c22\1.0.25\Start-CloudLoadTest.ps1
2018-02-26T09:43:20.6421428Z Starting Load Test Script
2018-02-26T09:43:20.8181115Z Test settings = Source/Microsoft.Offerings/phoenix-dev.testsettings
2018-02-26T09:43:20.8182673Z Test drop = Source/Microsoft.Offerings/App/Microsoft.Offerings.App.LoadTests
2018-02-26T09:43:20.8184026Z Load test = Microsoft.Offerings.QueryAllItems.loadtest
2018-02-26T09:43:20.8185636Z Load generator machine type = 0
2018-02-26T09:43:20.8187591Z Run source identifier = build/10782/979771
2018-02-26T09:43:20.8321093Z Updated test drop location is D:\a\1\s\Source/Microsoft.Offerings/App/Microsoft.Offerings.App.LoadTests
2018-02-26T09:43:20.8352657Z Updated test settings file is D:\a\1\s\Source/Microsoft.Offerings/phoenix-dev.testsettings
2018-02-26T09:43:20.8868165Z Selected load test file is 'D:\a\1\s\Source\Microsoft.Offerings\App\Microsoft.Offerings.App.LoadTests\Microsoft.Offerings.QueryAllItems.loadtest' under 'D:\a\1\s\Source\Microsoft.Offerings\App\Microsoft.Offerings.App.LoadTests'
2018-02-26T09:43:20.8870310Z Test Drop location used for the run is D:\a\1\s\Source\Microsoft.Offerings\App\Microsoft.Offerings.App.LoadTests. Please ensure all required files (test dlls, plugin dlls, dependent files) are part of this output folder
2018-02-26T09:43:20.9240327Z VSO Account URL is : https://microsoftit.visualstudio.com/
2018-02-26T09:43:20.9941246Z Getting Clt Endpoint:
2018-02-26T09:43:20.9955265Z Fetching the Clt endpoint for https://microsoftit.visualstudio.com
2018-02-26T09:43:20.9968942Z Fetching the SPS endpoint for https://microsoftit.visualstudio.com
2018-02-26T09:43:21.1843971Z ##[error]System.Net.WebException: The remote server returned an error: (401) Unauthorized.
2018-02-26T09:43:21.1867450Z    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
2018-02-26T09:43:21.1867920Z    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
2018-02-26T09:43:21.2000362Z Fetching the CLT endpoint for https://microsoftit.visualstudio.com
2018-02-26T09:43:21.2106574Z ##[error]System.Management.Automation.MethodInvocationException: Exception calling "FindServicePoint" with "1" argument(s): "This operation is not supported for a relative URI." ---> System.InvalidOperationException: This operation is not supported for a relative URI.
2018-02-26T09:43:21.2107600Z    at System.Uri.get_IsDefaultPort()
2018-02-26T09:43:21.2108043Z    at System.Net.ServicePointManager.MakeQueryString(Uri address)
2018-02-26T09:43:21.2108567Z    at System.Net.ServicePointManager.FindServicePointHelper(Uri address, Boolean isProxyServicePoint)
2018-02-26T09:43:21.2109243Z    at System.Net.ServicePointManager.FindServicePoint(Uri address, IWebProxy proxy, ProxyChain& chain, HttpAbortDelegate& abortDelegate, Int32& abortState)
2018-02-26T09:43:21.2109708Z    at CallSite.Target(Closure , CallSite , Type , Object )
2018-02-26T09:43:21.2110176Z    --- End of inner exception stack trace ---
2018-02-26T09:43:21.2110674Z    at System.Management.Automation.ExceptionHandlingOps.ConvertToMethodInvocationException(Exception exception, Type typeToThrow, String methodName, Int32 numArgs, MemberInfo memberInfo)
2018-02-26T09:43:21.2112083Z    at CallSite.Target(Closure , CallSite , Type , Object )
2018-02-26T09:43:21.2112485Z    at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
2018-02-26T09:43:21.2112933Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2018-02-26T09:43:21.2192411Z ##[error]System.UriFormatException: Invalid URI: The hostname could not be parsed.
2018-02-26T09:43:21.2209329Z    at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
2018-02-26T09:43:21.2210002Z    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.CheckProtocol(Uri uri)
2018-02-26T09:43:21.2210562Z    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetRequest(Uri uri)
2018-02-26T09:43:21.2211036Z    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
2018-02-26T09:43:21.2211505Z    at System.Management.Automation.CommandProcessor.ProcessRecord()
2018-02-26T09:43:21.2212703Z ##[error]System.Management.Automation.RuntimeException: You cannot call a method on a null-valued expression.
2018-02-26T09:43:21.2213581Z    at CallSite.Target(Closure , CallSite , Object , String )
2018-02-26T09:43:21.2214068Z    at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
2018-02-26T09:43:21.2215648Z    at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
2018-02-26T09:43:21.2216301Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2018-02-26T09:43:21.2216801Z TFS account Url = https://microsoftit.visualstudio.com
2018-02-26T09:43:21.2217201Z CLT account Url = 
2018-02-26T09:43:21.2251250Z ##[error]System.Management.Automation.MethodInvocationException: Exception calling "FindServicePoint" with "1" argument(s): "This operation is not supported for a relative URI." ---> System.InvalidOperationException: This operation is not supported for a relative URI.
2018-02-26T09:43:21.2252317Z    at System.Uri.get_IsDefaultPort()
2018-02-26T09:43:21.2254010Z    at System.Net.ServicePointManager.MakeQueryString(Uri address)
2018-02-26T09:43:21.2268383Z    at System.Net.ServicePointManager.FindServicePointHelper(Uri address, Boolean isProxyServicePoint)
2018-02-26T09:43:21.2269087Z    at System.Net.ServicePointManager.FindServicePoint(Uri address, IWebProxy proxy, ProxyChain& chain, HttpAbortDelegate& abortDelegate, Int32& abortState)
2018-02-26T09:43:21.2269686Z    at CallSite.Target(Closure , CallSite , Type , Object )
2018-02-26T09:43:21.2270165Z    --- End of inner exception stack trace ---
2018-02-26T09:43:21.2270774Z    at System.Management.Automation.ExceptionHandlingOps.ConvertToMethodInvocationException(Exception exception, Type typeToThrow, String methodName, Int32 numArgs, MemberInfo memberInfo)
2018-02-26T09:43:21.2271372Z    at CallSite.Target(Closure , CallSite , Type , Object )
2018-02-26T09:43:21.2271889Z    at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
2018-02-26T09:43:21.2272425Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2018-02-26T09:43:21.2273489Z ##[error]System.UriFormatException: Invalid URI: The hostname could not be parsed.
2018-02-26T09:43:21.2274592Z    at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
2018-02-26T09:43:21.2275150Z    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.CheckProtocol(Uri uri)
2018-02-26T09:43:21.2275796Z    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetRequest(Uri uri)
2018-02-26T09:43:21.2276272Z    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
2018-02-26T09:43:21.2276755Z    at System.Management.Automation.CommandProcessor.ProcessRecord()
2018-02-26T09:43:21.2277767Z ##[error]System.Management.Automation.RuntimeException: You cannot call a method on a null-valued expression.
2018-02-26T09:43:21.2279074Z    at CallSite.Target(Closure , CallSite , Object , String )
2018-02-26T09:43:21.2279589Z    at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
2018-02-26T09:43:21.2280282Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2018-02-26T09:43:21.2311514Z ##[error]Microsoft.PowerShell.Commands.WriteErrorException: Connection 'f8ff44ee-c192-4fa2-b265-407299c89041' failed for service 'https://microsoftit.visualstudio.com/'
2018-02-26T09:43:21.2314906Z Load Test Script execution completed
2018-02-26T09:43:21.2489230Z ##[error]PowerShell script completed with 8 errors.
2018-02-26T09:43:21.2496563Z ##[section]Finishing: Microsoft.Offerings.QueryAllItems

**Comment by cltshivash** [comment]
@abdulrahaman7 You should be use a PAT token in the credentials of the generic service endpoint and not the actual user credentials. Please reopen if you still face issues.
