### ISSUE TITLE
Running a VSTest task on a Test plan fails with no tests found

### ISSUE THREAD

**Issue by GrimSmiler** [Microsoft/vsts-tasks#6589]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - VSTS or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 16.122.27102.1

- Agent - Hosted or Private: 
    
    - If using private agent, provide the OS of the machine running the agent and the agent version: 
        - windows 10
        - 2.122.1

## Issue Description

Create a test case
Associate a test method (XUnit Fact) through an API [howto](https://stackoverflow.com/questions/48825094/how-to-associate-a-xunit-fact-to-a-test-case-in-tfs)
Associate a test plan with a build and a release env
In the release enc, download the binaries with tests and run the tests using the following vstest(v15) vNext step settings 

[Include task name(s), screenshots and any other relevant details]
![image](https://user-images.githubusercontent.com/5007741/36891420-dfa12640-1e01-11e8-856e-b9cb83538a00.png)

Here is the iamge of the Associated Automated Test

![image](https://user-images.githubusercontent.com/5007741/36892330-ada8ab1a-1e04-11e8-9593-b17ff2593e66.png)

### Error logs

```
2018-03-02T09:21:22.0092431Z ##[section]Starting: Release
2018-03-02T09:21:22.0112428Z Current agent version: '2.122.1'
2018-03-02T09:21:22.3132449Z ##[section]Starting: Initialize Job
2018-03-02T09:21:22.3152417Z Prepare release directory.
2018-03-02T09:21:22.3162420Z ReleaseId=424, TeamProjectId=e1712684-97e7-45d5-8417-348c419464d2, ReleaseDefinitionName=Runt Test Plan
2018-03-02T09:21:22.3212418Z Release folder: C:\agent\_work\r11\a
2018-03-02T09:21:22.3322455Z Environment variables available are below.  Note that these environment variables can be referred to in the task (in the ReleaseDefinition) by replacing "_" with "." e.g. AGENT_NAME environment variable can be referenced using Agent.Name in the ReleaseDefinition: 
				[AGENT_HOMEDIRECTORY] --> [C:\agent]
				[AGENT_ID] --> [30]
				[AGENT_JOBNAME] --> [Release]
				[AGENT_MACHINENAME] --> [SOLEYPC-1]
				[AGENT_NAME] --> [CI-Agent-1-Berta-2.117.2]
				[AGENT_OS] --> [Windows_NT]
				[AGENT_RELEASEDIRECTORY] --> [C:\agent\_work\r11\a]
				[AGENT_ROOTDIRECTORY] --> [C:\agent\_work]
				[AGENT_SERVEROMDIRECTORY] --> [C:\agent\externals\vstsom]
				[AGENT_TEMPDIRECTORY] --> [C:\agent\_work\_temp]
				[AGENT_TOOLSDIRECTORY] --> [C:\agent\_work\_tool]
				[AGENT_VERSION] --> [2.122.1]
				[AGENT_WORKFOLDER] --> [C:\agent\_work]
				[AZURE_HTTP_USER_AGENT] --> [TFS_307dbc96-bd47-4e92-b586-ec0b055df476_release_13_424_424_1]
				[BUILD_BUILDID] --> [11219]
				[BUILD_BUILDNUMBER] --> [11219]
				[BUILD_BUILDURI] --> [vstfs:///Build/Build/11219]
				[BUILD_DEFINITIONID] --> [84]
				[BUILD_DEFINITIONNAME] --> [Run Scenario Tests]
				[BUILD_PROJECTID] --> [e1712684-97e7-45d5-8417-348c419464d2]
				[BUILD_PROJECTNAME] --> [SoleyServer]
				[BUILD_REPOSITORY_ID] --> [d48e8832-33ec-4a18-82d3-9d6e865b6624]
				[BUILD_REPOSITORY_NAME] --> [SoleyServer]
				[BUILD_REPOSITORY_PROVIDER] --> [TfsGit]
				[BUILD_REQUESTEDFOR] --> [Ilya Migal]
				[BUILD_REQUESTEDFORID] --> [4866c9e3-6340-4010-9068-5ad6d23176c7]
				[BUILD_SOURCEBRANCH] --> [refs/heads/master]
				[BUILD_SOURCEBRANCHNAME] --> [master]
				[BUILD_SOURCEVERSION] --> [5505e6a337969e364894ed49a4767df71439f288]
				[BUILD_TYPE] --> [Build]
				[MSDEPLOY_HTTP_USER_AGENT] --> [TFS_307dbc96-bd47-4e92-b586-ec0b055df476_release_13_424_424_1]
				[RELEASE_ARTIFACTS_RUN_SCENARIO_TESTS_BUILDID] --> [11219]
				[RELEASE_ARTIFACTS_RUN_SCENARIO_TESTS_BUILDNUMBER] --> [11219]
				[RELEASE_ARTIFACTS_RUN_SCENARIO_TESTS_BUILDURI] --> [vstfs:///Build/Build/11219]
				[RELEASE_ARTIFACTS_RUN_SCENARIO_TESTS_DEFINITIONID] --> [84]
				[RELEASE_ARTIFACTS_RUN_SCENARIO_TESTS_DEFINITIONNAME] --> [Run Scenario Tests]
				[RELEASE_ARTIFACTS_RUN_SCENARIO_TESTS_PROJECTID] --> [e1712684-97e7-45d5-8417-348c419464d2]
				[RELEASE_ARTIFACTS_RUN_SCENARIO_TESTS_PROJECTNAME] --> [SoleyServer]
				[RELEASE_ARTIFACTS_RUN_SCENARIO_TESTS_REPOSITORY_ID] --> [d48e8832-33ec-4a18-82d3-9d6e865b6624]
				[RELEASE_ARTIFACTS_RUN_SCENARIO_TESTS_REPOSITORY_NAME] --> [SoleyServer]
				[RELEASE_ARTIFACTS_RUN_SCENARIO_TESTS_REPOSITORY_PROVIDER] --> [TfsGit]
				[RELEASE_ARTIFACTS_RUN_SCENARIO_TESTS_REQUESTEDFOR] --> [Ilya Migal]
				[RELEASE_ARTIFACTS_RUN_SCENARIO_TESTS_REQUESTEDFORID] --> [4866c9e3-6340-4010-9068-5ad6d23176c7]
				[RELEASE_ARTIFACTS_RUN_SCENARIO_TESTS_SOURCEBRANCH] --> [refs/heads/master]
				[RELEASE_ARTIFACTS_RUN_SCENARIO_TESTS_SOURCEBRANCHNAME] --> [master]
				[RELEASE_ARTIFACTS_RUN_SCENARIO_TESTS_SOURCEVERSION] --> [5505e6a337969e364894ed49a4767df71439f288]
				[RELEASE_ARTIFACTS_RUN_SCENARIO_TESTS_TYPE] --> [Build]
				[RELEASE_ATTEMPTNUMBER] --> [1]
				[RELEASE_DEFINITIONENVIRONMENTID] --> [14]
				[RELEASE_DEFINITIONID] --> [13]
				[RELEASE_DEFINITIONNAME] --> [Runt Test Plan]
				[RELEASE_DEPLOYMENT_REQUESTEDFOR] --> [Ilya Migal]
				[RELEASE_DEPLOYMENT_REQUESTEDFOREMAIL] --> [migal@soley.io]
				[RELEASE_DEPLOYMENT_REQUESTEDFORID] --> [4866c9e3-6340-4010-9068-5ad6d23176c7]
				[RELEASE_DEPLOYMENTID] --> [667]
				[RELEASE_DEPLOYPHASEID] --> [1284]
				[RELEASE_ENVIRONMENTID] --> [424]
				[RELEASE_ENVIRONMENTNAME] --> [Environment 1]
				[RELEASE_ENVIRONMENTS_ENVIRONMENT_1_STATUS] --> [InProgress]
				[RELEASE_ENVIRONMENTURI] --> [vstfs:///ReleaseManagement/Environment/424]
				[RELEASE_RELEASEDESCRIPTION] --> []
				[RELEASE_RELEASEID] --> [424]
				[RELEASE_RELEASENAME] --> [Release-10]
				[RELEASE_RELEASEURI] --> [vstfs:///ReleaseManagement/Release/424]
				[RELEASE_RELEASEWEBURL] --> [https://tfs.soley.io:8686/tfs/soleyCollection/e1712684-97e7-45d5-8417-348c419464d2/_release?releaseId=424&_a=release-summary]
				[RELEASE_REQUESTEDFOR] --> [Ilya Migal]
				[RELEASE_REQUESTEDFOREMAIL] --> [migal@soley.io]
				[RELEASE_REQUESTEDFORID] --> [4866c9e3-6340-4010-9068-5ad6d23176c7]
				[RELEASE_SKIPARTIFACTSDOWNLOAD] --> [False]
				[REQUESTEDFORID] --> [4866c9e3-6340-4010-9068-5ad6d23176c7]
				[SYSTEM] --> [release]
				[SYSTEM_ARTIFACTSDIRECTORY] --> [C:\agent\_work\r11\a]
				[SYSTEM_COLLECTIONID] --> [307dbc96-bd47-4e92-b586-ec0b055df476]
				[SYSTEM_CULTURE] --> [en-US]
				[SYSTEM_DEFAULTWORKINGDIRECTORY] --> [C:\agent\_work\r11\a]
				[SYSTEM_ENABLEACCESSTOKEN] --> [False]
				[SYSTEM_HOSTTYPE] --> [release]
				[SYSTEM_JOBID] --> [19983752-6fc3-4941-96e8-8d2a3ca216d0]
				[SYSTEM_JOBPOSITIONINPHASE] --> [1]
				[SYSTEM_PARALLELEXECUTIONTYPE] --> [None]
				[SYSTEM_PLANID] --> [600ac4c0-ce4a-4e51-bf3b-76668779407e]
				[SYSTEM_TASKDEFINITIONSURI] --> [https://tfs.soley.io:8686/tfs/soleyCollection/]
				[SYSTEM_TEAMFOUNDATIONCOLLECTIONURI] --> [https://tfs.soley.io:8686/tfs/soleyCollection/]
				[SYSTEM_TEAMFOUNDATIONSERVERURI] --> [https://tfs.soley.io:8686/tfs/soleyCollection/]
				[SYSTEM_TEAMPROJECT] --> [SoleyServer]
				[SYSTEM_TEAMPROJECTID] --> [e1712684-97e7-45d5-8417-348c419464d2]
				[SYSTEM_TIMELINEID] --> [600ac4c0-ce4a-4e51-bf3b-76668779407e]
				[SYSTEM_TOTALJOBSINPHASE] --> [1]
				[SYSTEM_WORKFOLDER] --> [C:\agent\_work]
2018-03-02T09:21:22.3352417Z Download all required tasks.
2018-03-02T09:21:22.3752420Z ##[section]Finishing: Initialize Job
2018-03-02T09:21:22.4072428Z ##[section]Starting: Download Artifacts
2018-03-02T09:21:22.4772746Z Downloading artifact
2018-03-02T09:21:22.4822605Z Creating artifacts directory: C:\agent\_work\r11\a
2018-03-02T09:21:22.6852848Z Created artifacts directory: C:\agent\_work\r11\a
2018-03-02T09:21:22.6872833Z Starting artifacts download...
2018-03-02T09:21:22.6892843Z Downloading linked artifact Run Scenario Tests of type Build...
2018-03-02T09:21:22.6922849Z Ensuring artifact folder C:\agent\_work\r11\a\Run Scenario Tests exists and is clean.
2018-03-02T09:21:22.6982850Z Preparing to get the list of available artifacts from build
2018-03-02T09:21:22.8462433Z Preparing to download artifact: ScenarioTests
2018-03-02T09:21:22.8522431Z Artifact Type: ServerDrop
.......
2018-03-02T09:21:28.2502437Z Download complete.
2018-03-02T09:21:28.2512440Z 402 placed file(s): 402 downloaded, 0 empty
2018-03-02T09:21:28.2512440Z 49 MB downloaded at 9507 KB/sec. Download time: 00:00:05.1931725.
2018-03-02T09:21:28.2512440Z Downloaded linked artifact Run Scenario Tests
2018-03-02T09:21:28.2512440Z Finished artifacts download
2018-03-02T09:21:28.2512440Z Downloading commits
2018-03-02T09:21:28.2542438Z ##[section]Finishing: Download Artifacts
2018-03-02T09:21:28.2622702Z ##[section]Starting: VsTest - testPlan
2018-03-02T09:21:28.2802874Z ==============================================================================
2018-03-02T09:21:28.2802874Z Task         : Visual Studio Test
2018-03-02T09:21:28.2802874Z Description  : Run tests with Visual Studio test runner
2018-03-02T09:21:28.2802874Z Version      : 2.1.9
2018-03-02T09:21:28.2802874Z Author       : Microsoft Corporation
2018-03-02T09:21:28.2802874Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=835764)
2018-03-02T09:21:28.2802874Z ==============================================================================
2018-03-02T09:21:29.1332443Z In distributed testing flow
2018-03-02T09:21:29.1332443Z ======================================================
2018-03-02T09:21:29.1332443Z Test selector : Test plan
2018-03-02T09:21:29.1332443Z Test plan Id : 9191
2018-03-02T09:21:29.1332443Z Test plan configuration Id : 15
2018-03-02T09:21:29.1332443Z Test suite Id selected: 9193
2018-03-02T09:21:29.1332443Z Search folder : C:\agent\_work\r11\a\Run Scenario Tests\ScenarioTests\ScenarioTests
2018-03-02T09:21:29.1332443Z Run settings file : C:\agent\_work\r11\a
2018-03-02T09:21:29.1332443Z Run in parallel : false
2018-03-02T09:21:29.1332443Z Run in isolation : false
2018-03-02T09:21:29.1332443Z Path to custom adapters : null
2018-03-02T09:21:29.1332443Z Other console options : /Logger:trx
2018-03-02T09:21:29.1332443Z Code coverage enabled : true
2018-03-02T09:21:29.1332443Z vstest.console.exe, specified location : C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow
2018-03-02T09:21:29.1332443Z [command]C:\WINDOWS\System32\Wbem\WMIC.exe datafile where "name='C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\Common7\\IDE\\CommonExtensions\\Microsoft\\TestWindow\\vstest.console.exe'" get Version /Value
2018-03-02T09:21:29.1352456Z 
2018-03-02T09:21:29.1352456Z 
2018-03-02T09:21:29.1352456Z 
2018-03-02T09:21:29.1352456Z 
2018-03-02T09:21:29.1352456Z Version=15.0.27130.2020
2018-03-02T09:21:29.1352456Z 
2018-03-02T09:21:29.1352456Z 
2018-03-02T09:21:29.1352456Z 
2018-03-02T09:21:29.1352456Z 
2018-03-02T09:21:29.1352456Z 
2018-03-02T09:21:29.1352456Z 
2018-03-02T09:21:29.1352456Z 
2018-03-02T09:21:29.1922425Z ##[warning]Other console options is not supported when using the multi-agent phase setting. This option will be ignored.
2018-03-02T09:21:29.1922425Z Distributed test execution, number of agents in phase : 1
2018-03-02T09:21:29.1922425Z SystemVssConnection exists true
2018-03-02T09:21:29.1942470Z ======================================================
2018-03-02T09:21:29.8852445Z [command]d:\agent\_work\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.1.9\modules\TestExecutionHost.exe
2018-03-02T09:21:29.9162444Z ##########################################################################
2018-03-02T09:21:29.9282748Z ===========================================
2018-03-02T09:21:29.9282748Z AgentName: SOLEYPC-1-CI-Agent-1-Berta-2.117.2-30
2018-03-02T09:21:29.9282748Z AgentId: 83
2018-03-02T09:21:29.9282748Z ServiceUrl: https://tfs.soley.io:8686/tfs/soleyCollection/
2018-03-02T09:21:29.9282748Z TestPlatformVersion: 
2018-03-02T09:21:29.9282748Z EnvironmentUri: dta://env/SoleyServer/_apis/release/424/1284/1
2018-03-02T09:21:29.9282748Z QueryForTaskIntervalInMilliseconds: 3000
2018-03-02T09:21:29.9282748Z MaxQueryForTaskIntervalInMilliseconds: 10000
2018-03-02T09:21:29.9282748Z QueueNotFoundDelayTimeInMilliseconds: 3000
2018-03-02T09:21:29.9282748Z MaxQueueNotFoundDelayTimeInMilliseconds: 50000
2018-03-02T09:21:29.9282748Z RetryCountWhileConnectingToTfs: 3
2018-03-02T09:21:29.9282748Z UseVsTestConsole: False
2018-03-02T09:21:29.9282748Z ===========================================
2018-03-02T09:21:29.9362441Z Initializing the Test Execution Engine
2018-03-02T09:21:30.2312878Z Acquired the Test Agent details from TFS
2018-03-02T09:21:30.4213055Z Creating run for selected test plan with following parameters
2018-03-02T09:21:30.4213055Z Test plan ID: 9191
2018-03-02T09:21:30.4213055Z Test suite ID: 9193
2018-03-02T09:21:30.4213055Z Test configuration ID: 15
2018-03-02T09:21:30.5082457Z test configuration mapping: 
2018-03-02T09:21:30.5092434Z Run title: TestRun_Runt Test Plan_Release-10
2018-03-02T09:21:30.5092434Z test settings id : 2626
2018-03-02T09:21:30.5102437Z Build location: C:\agent\_work\r11\a\Run Scenario Tests\ScenarioTests\ScenarioTests
2018-03-02T09:21:30.5102437Z Build Id: 11219
2018-03-02T09:21:30.6012433Z Test run with Id 10694 associated
2018-03-02T09:21:30.6632433Z Please use this link to analyze the test run : https://tfs.soley.io:8686/tfs/soleyCollection/SoleyServer/_TestManagement/Runs#_a=resultQuery&runId=10694&queryPath=Recent+Run%2FRun+10694
2018-03-02T09:21:30.6632433Z Test run '10694' is in 'InProgress' state.
2018-03-02T09:21:30.6632433Z Total Tests : 1, Passed Tests : 0
2018-03-02T09:21:33.5752725Z Count of test sources found: 1
2018-03-02T09:21:33.6272493Z Custom adapters: C:\agent\_work\r11\a\Run Scenario Tests\ScenarioTests\ScenarioTests
2018-03-02T09:21:40.7112473Z Test run '10694' is in 'InProgress' state.
2018-03-02T09:21:40.7112473Z Total Tests : 1, Passed Tests : 0
2018-03-02T09:21:48.4102878Z ##[error]ExecutionTaskStateModel.ExecuteTask: Recived error while executing task: System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: No test assemblies found on the test machine matching the source filter criteria or no tests discovered matching test filter criteria. Verify that test assemblies are present on the machine and test filter criteria is correct.
2018-03-02T09:21:48.4102878Z    at Microsoft.VisualStudio.TestService.VstestAdapter.Execution.Run(CancellationToken cancellationToken) in E:\v2.0\A6\_work\1\s\Ta\Agent\VS.TestService.VstestAdapter\Phases\Execution.cs:line 60
2018-03-02T09:21:48.4102878Z    at Microsoft.VisualStudio.TestService.VstestAdapter.ExecutionAndPublish.Run(CancellationToken cancellationToken) in E:\v2.0\A6\_work\1\s\Ta\Agent\VS.TestService.VstestAdapter\Phases\ExecuteAndPublish.cs:line 51
2018-03-02T09:21:48.4102878Z    at Microsoft.VisualStudio.TestService.VstestAdapter.VstestAdapter.<>c__DisplayClass2_0.<ExecuteAsync>b__0() in E:\v2.0\A6\_work\1\s\Ta\Agent\VS.TestService.VstestAdapter\VstestAdapter.cs:line 61
2018-03-02T09:21:48.4102878Z    at System.Threading.Tasks.Task`1.InnerInvoke()
2018-03-02T09:21:48.4102878Z    at System.Threading.Tasks.Task.Execute()
2018-03-02T09:21:48.4102878Z    --- End of inner exception stack trace ---
2018-03-02T09:21:48.4102878Z ---> (Inner Exception #0) System.InvalidOperationException: No test assemblies found on the test machine matching the source filter criteria or no tests discovered matching test filter criteria. Verify that test assemblies are present on the machine and test filter criteria is correct.
2018-03-02T09:21:48.4102878Z    at Microsoft.VisualStudio.TestService.VstestAdapter.Execution.Run(CancellationToken cancellationToken) in E:\v2.0\A6\_work\1\s\Ta\Agent\VS.TestService.VstestAdapter\Phases\Execution.cs:line 60
2018-03-02T09:21:48.4102878Z    at Microsoft.VisualStudio.TestService.VstestAdapter.ExecutionAndPublish.Run(CancellationToken cancellationToken) in E:\v2.0\A6\_work\1\s\Ta\Agent\VS.TestService.VstestAdapter\Phases\ExecuteAndPublish.cs:line 51
2018-03-02T09:21:48.4102878Z    at Microsoft.VisualStudio.TestService.VstestAdapter.VstestAdapter.<>c__DisplayClass2_0.<ExecuteAsync>b__0() in E:\v2.0\A6\_work\1\s\Ta\Agent\VS.TestService.VstestAdapter\VstestAdapter.cs:line 61
2018-03-02T09:21:48.4102878Z    at System.Threading.Tasks.Task`1.InnerInvoke()
2018-03-02T09:21:48.4102878Z    at System.Threading.Tasks.Task.Execute()<---
2018-03-02T09:21:48.4102878Z  
2018-03-02T09:21:48.4112970Z ##[error]ExecutionTaskStateModel.AbortSlice : System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: No test assemblies found on the test machine matching the source filter criteria or no tests discovered matching test filter criteria. Verify that test assemblies are present on the machine and test filter criteria is correct.
2018-03-02T09:21:48.4112970Z    at Microsoft.VisualStudio.TestService.VstestAdapter.Execution.Run(CancellationToken cancellationToken) in E:\v2.0\A6\_work\1\s\Ta\Agent\VS.TestService.VstestAdapter\Phases\Execution.cs:line 60
2018-03-02T09:21:48.4112970Z    at Microsoft.VisualStudio.TestService.VstestAdapter.ExecutionAndPublish.Run(CancellationToken cancellationToken) in E:\v2.0\A6\_work\1\s\Ta\Agent\VS.TestService.VstestAdapter\Phases\ExecuteAndPublish.cs:line 51
2018-03-02T09:21:48.4112970Z    at Microsoft.VisualStudio.TestService.VstestAdapter.VstestAdapter.<>c__DisplayClass2_0.<ExecuteAsync>b__0() in E:\v2.0\A6\_work\1\s\Ta\Agent\VS.TestService.VstestAdapter\VstestAdapter.cs:line 61
2018-03-02T09:21:48.4112970Z    at System.Threading.Tasks.Task`1.InnerInvoke()
2018-03-02T09:21:48.4112970Z    at System.Threading.Tasks.Task.Execute()
2018-03-02T09:21:48.4112970Z    --- End of inner exception stack trace ---
2018-03-02T09:21:48.4112970Z ---> (Inner Exception #0) System.InvalidOperationException: No test assemblies found on the test machine matching the source filter criteria or no tests discovered matching test filter criteria. Verify that test assemblies are present on the machine and test filter criteria is correct.
2018-03-02T09:21:48.4112970Z    at Microsoft.VisualStudio.TestService.VstestAdapter.Execution.Run(CancellationToken cancellationToken) in E:\v2.0\A6\_work\1\s\Ta\Agent\VS.TestService.VstestAdapter\Phases\Execution.cs:line 60
2018-03-02T09:21:48.4112970Z    at Microsoft.VisualStudio.TestService.VstestAdapter.ExecutionAndPublish.Run(CancellationToken cancellationToken) in E:\v2.0\A6\_work\1\s\Ta\Agent\VS.TestService.VstestAdapter\Phases\ExecuteAndPublish.cs:line 51
2018-03-02T09:21:48.4112970Z    at Microsoft.VisualStudio.TestService.VstestAdapter.VstestAdapter.<>c__DisplayClass2_0.<ExecuteAsync>b__0() in E:\v2.0\A6\_work\1\s\Ta\Agent\VS.TestService.VstestAdapter\VstestAdapter.cs:line 61
2018-03-02T09:21:48.4112970Z    at System.Threading.Tasks.Task`1.InnerInvoke()
2018-03-02T09:21:48.4112970Z    at System.Threading.Tasks.Task.Execute()<---
2018-03-02T09:21:48.4112970Z 
2018-03-02T09:21:50.7582968Z Test run '10694' is in 'Aborted' state.
2018-03-02T09:21:50.7582968Z Total Tests : 1, Passed Tests : 0
2018-03-02T09:21:51.3212966Z ##########################################################################
2018-03-02T09:22:00.7582773Z ##[warning]Test run is aborted. Logging details of the run logs.
2018-03-02T09:22:00.7733003Z ##[warning]New test run created.
2018-03-02T09:22:00.7733003Z Test Run queued for Project Collection Build Service (soleyCollection).
2018-03-02T09:22:00.7733003Z 
2018-03-02T09:22:00.7733003Z ##[warning]Test execution started. Test run id : 10694
2018-03-02T09:22:00.7733003Z ##[warning]UnExpected error occurred during test execution. Try again.
2018-03-02T09:22:00.7733003Z ##[warning]Error : One or more errors occurred.--->No test assemblies found on the test machine matching the source filter criteria or no tests discovered matching test filter criteria. Verify that test assemblies are present on the machine and test filter criteria is correct.
2018-03-02T09:22:00.7733003Z 
2018-03-02T09:22:00.7733003Z ##[warning]Test run aborted. Test run id: 10694
2018-03-02T09:22:00.7742488Z ##[error]System.Exception: The test run was aborted, failing the task.
2018-03-02T09:22:00.8112482Z ##[section]Async Command Start: Telemetry
2018-03-02T09:22:00.8112482Z ##[section]Async Command End: Telemetry
2018-03-02T09:22:00.8112482Z ##[section]Async Command Start: Telemetry
2018-03-02T09:22:00.8112482Z ##[section]Async Command End: Telemetry
2018-03-02T09:22:00.8112482Z ##[section]Async Command Start: Telemetry
2018-03-02T09:22:00.8112482Z ##[section]Async Command End: Telemetry
2018-03-02T09:22:00.8112482Z ##[section]Async Command Start: Telemetry
2018-03-02T09:22:00.8112482Z ##[section]Async Command End: Telemetry
2018-03-02T09:22:00.8112482Z ##[section]Async Command Start: Telemetry
2018-03-02T09:22:00.8112482Z ##[section]Async Command End: Telemetry
2018-03-02T09:22:00.8112482Z ##[section]Async Command Start: Telemetry
2018-03-02T09:22:00.8112482Z ##[section]Async Command End: Telemetry
2018-03-02T09:22:00.8112482Z ##[section]Async Command Start: Telemetry
2018-03-02T09:22:00.8112482Z ##[section]Async Command End: Telemetry
2018-03-02T09:22:00.8112482Z ##[section]Async Command Start: Telemetry
2018-03-02T09:22:00.8112482Z ##[section]Async Command End: Telemetry
2018-03-02T09:22:00.8112482Z ##[section]Async Command Start: Telemetry
2018-03-02T09:22:00.8112482Z ##[section]Async Command End: Telemetry
2018-03-02T09:22:00.8112482Z ##[section]Async Command Start: Telemetry
2018-03-02T09:22:00.8112482Z ##[section]Async Command End: Telemetry
2018-03-02T09:22:00.8112482Z ##[section]Finishing: VsTest - testPlan
2018-03-02T09:22:00.8242904Z ##[section]Finishing: Release
```

**Comment by GrimSmiler** [comment]
Just an explanation of what i am trying to do:
1) Create a XUnit Fact
2) Associate with a test
3) Run the XUnit tests in the build/release
4) Automatically update the states of the associated test cases in the test plan

**Comment by nigurr** [comment]
@GrimSmiler, This is currently not supported scenario.
Test plan/Test suite and automated test cases association is available only for MsTest based tests.

Please use uservoice to request for new features/feedback. Thank you
https://visualstudio.uservoice.com/forums/330519-visual-studio-team-services

**Comment by GrimSmiler** [comment]
@nigurr is there a possibility to personally extend this step?
Where would I find documentation regarding implementing a possible enhancement to this code?

**Comment by prawalagarwal** [comment]
@GrimSmiler I am afraid it is not possible to contribute to this project today. Association through VS and the corresponding APIs are not open source today. Please ask for this feature as @nigurr suggested through the feedback channel.

**Comment by GrimSmiler** [comment]
@prawalagarwal understood, thanks.
