### ISSUE TITLE
The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot add a member with the name "TelemetryError" because a member with that name already exists. 

### ISSUE THREAD

**Issue by mars3333** [Microsoft/vsts-tasks#6769]
## Troubleshooting
// Here is the log

2018-03-20T12:45:02.5117835Z 
2018-03-20T12:45:02.5274024Z Copying recursively from C:\Agent2.0\_work\r2\a\eRegistration Kelly Build\eReg Build\Staging\Deployment Scripts to F:\Apps\Middleware\Ops on machine amtrowobwebd01.amer.prd.kellyservices.com succeeded
2018-03-20T12:45:02.5742802Z ##[section]Finishing: Copy Deployment Powershell Files
2018-03-20T12:45:02.5742802Z ##[section]Starting: Turn off IIS Sites
2018-03-20T12:45:02.5742802Z ==============================================================================
2018-03-20T12:45:02.5742802Z Task         : PowerShell on Target Machines
2018-03-20T12:45:02.5742802Z Description  : Execute PowerShell scripts on remote machine(s)
2018-03-20T12:45:02.5742802Z Version      : 1.0.49
2018-03-20T12:45:02.5742802Z Author       : Microsoft Corporation
2018-03-20T12:45:02.5742802Z Help         : [More Information](https://go.microsoft.com/fwlink/?linkid=627414)
2018-03-20T12:45:02.5742802Z ==============================================================================
2018-03-20T12:45:02.5742802Z Preparing task execution handler.
2018-03-20T12:45:03.3086771Z Executing the powershell script: C:\Agent2.0\_work\_tasks\PowerShellOnTargetMachines_3b5693d4-5777-4fee-862a-bd2b7a374c68\1.0.49\PowerShellOnTargetMachines.ps1
2018-03-20T12:45:05.3557475Z Deployment started for machine: 'amtrowobwebd01.amer.prd.kellyservices.com:5985'
2018-03-20T12:45:22.0122824Z ##[error]System.Management.Automation.ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot add a member with the name "TelemetryError" because a member with that name already exists. To overwrite the member anyway, add the Force parameter to your command.
2018-03-20T12:45:22.0122824Z    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
2018-03-20T12:45:22.0122824Z    at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
2018-03-20T12:45:22.0122824Z    at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
2018-03-20T12:45:22.0122824Z    at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2018-03-20T12:45:22.0122824Z    at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2018-03-20T12:45:22.0122824Z    at Microsoft.TeamFoundation.DistributedTask.Handlers.LegacyVSTSPowerShellHost.VSTSPowerShellHost.Main(String[] args)
2018-03-20T12:45:22.0435256Z ##[error]LegacyVSTSPowerShellHost.exe completed with return code: -1.
2018-03-20T12:45:22.0435256Z ##[section]Finishing: Turn off IIS Sites
2018-03-20T12:45:22.0590782Z ##[section]Finishing: Release

## Environment
- Server - VSTS or TFS on-premises? **VSTS**
    
    - If using TFS on-premises, provide the version: 
    
    - If using VSTS, provide the account name, team project name, build definition name/build number: 
      eRegistration, Viper, build 42, release 270

- Agent - Hosted or Private: 

Not sure

## Issue Description

Turn off IIS Sites

The powershell script has only 1 line and is as follows:

& {iisreset /STOP}

However, the script doesn't seem to be the issue, because 2 week ago it worked. Now it fails on every task on the server.

**Comment by bigmck1** [comment]
Hi

I am also getting this issue on https://tgpsystemdevelopment.visualstudio.com

thanks

**Comment by rokmicrosoft** [comment]
We had already identified this issue. For some of the rings it had already deployed  and tomorrow we are planning for rest of the rings.

**Comment by rokmicrosoft** [comment]
@bigmck1  @mars3333  Can you please try it once and let us know if you still face this issue ?

**Comment by bigmck1** [comment]
Hi

I tried on Friday and it was working again.

Thanks

**Comment by rokmicrosoft** [comment]
Thanks @bigmck1  Now I am closing this issue .

**Comment by mars3333** [comment]
Yes, it is working for me now.

Thanks!
