### ISSUE TITLE
Windows Machine File Copy fails with unknown option if password begins with a slash

### ISSUE THREAD

**Issue by ascire** [Microsoft/vsts-tasks#6803]
## Environment
TFS on-premise, v 15.117.26714.0

Hosted Agent

* Agent.OS | Windows_NT
* Agent.OSVersion | 10.0.14393
* Agent.Version | 2.117.2

## Issue Description

When running Windows Machine File Copy with a password that begins with a forward slash, the task fails with "The option /password is unknown."

When attempting to escape the password by surrounding it with single quotes, the process fails with an invalid password.

### Error logs

Without escaping:
```
2018-03-26T14:20:27.8651458Z ##[section]Starting: Copy files from $(System.DefaultWorkingDirectory)/CI/drop
2018-03-26T14:20:27.8651458Z ==============================================================================
2018-03-26T14:20:27.8651458Z Task         : Windows Machine File Copy
2018-03-26T14:20:27.8651458Z Description  : Copy files to remote machine(s)
2018-03-26T14:20:27.8651458Z Version      : 1.0.41
2018-03-26T14:20:27.8651458Z Author       : Microsoft Corporation
2018-03-26T14:20:27.8651458Z Help         : [More Information](https://go.microsoft.com/fwlink/?linkid=627415)
2018-03-26T14:20:27.8651458Z ==============================================================================
2018-03-26T14:20:27.8807700Z Preparing task execution handler.
2018-03-26T14:20:28.1932803Z Executing the powershell script: C:\tfs2017buildagent\_work\_tasks\WindowsMachineFileCopy_731004d4-1d66-4f70-8c05-638018b22210\1.0.41\WindowsMachineFileCopy.ps1
2018-03-26T14:20:29.0058048Z Copy started for - 'mydevserver'
2018-03-26T14:20:29.1308024Z ##[error]System.Management.Automation.RuntimeException: Copying failed for resource : mydevserver
2018-03-26T14:20:29.1308024Z 
2018-03-26T14:20:29.1308024Z       Failed to connect to the path \\mydevserver with the user mydomain\myuser for copying.
2018-03-26T14:20:29.1308024Z     The option /mypassword is unknown. 
2018-03-26T14:20:29.1308024Z  The syntax of this command is:
2018-03-26T14:20:29.1308024Z  
2018-03-26T14:20:29.1308024Z  NET USE
2018-03-26T14:20:29.1308024Z [devicename | *] [\\computername\sharename[\volume] [password | *]]
2018-03-26T14:20:29.1308024Z         [/USER:[domainname\]username]
2018-03-26T14:20:29.1308024Z         [/USER:[dotted domain name\]username]
2018-03-26T14:20:29.1308024Z         [/USER:[username@dotted domain name]
2018-03-26T14:20:29.1308024Z         [/SMARTCARD]
2018-03-26T14:20:29.1308024Z         [/SAVECRED]
2018-03-26T14:20:29.1308024Z         [[/DELETE] | [/PERSISTENT:{YES | NO}]]
2018-03-26T14:20:29.1308024Z 
2018-03-26T14:20:29.1308024Z NET USE {devicename | *} [password | *] /HOME
2018-03-26T14:20:29.1308024Z 
2018-03-26T14:20:29.1308024Z NET USE [/PERSISTENT:{YES | NO}]
2018-03-26T14:20:29.1308024Z 
2018-03-26T14:20:29.1308024Z  More help is available by typing NET HELPMSG 3506.
2018-03-26T14:20:29.1308024Z 
2018-03-26T14:20:29.1308024Z  ---> System.Management.Automation.RuntimeException: Copying failed for resource : mydevserver
2018-03-26T14:20:29.1308024Z 
2018-03-26T14:20:29.1308024Z       Failed to connect to the path \\mydevserver with the user mydomain\myuser for copying.
2018-03-26T14:20:29.1308024Z     The option /mypassword is unknown. 
2018-03-26T14:20:29.1308024Z  The syntax of this command is:
2018-03-26T14:20:29.1308024Z  
2018-03-26T14:20:29.1308024Z  NET USE
2018-03-26T14:20:29.1308024Z [devicename | *] [\\computername\sharename[\volume] [password | *]]
2018-03-26T14:20:29.1308024Z         [/USER:[domainname\]username]
2018-03-26T14:20:29.1308024Z         [/USER:[dotted domain name\]username]
2018-03-26T14:20:29.1308024Z         [/USER:[username@dotted domain name]
2018-03-26T14:20:29.1308024Z         [/SMARTCARD]
2018-03-26T14:20:29.1308024Z         [/SAVECRED]
2018-03-26T14:20:29.1308024Z         [[/DELETE] | [/PERSISTENT:{YES | NO}]]
2018-03-26T14:20:29.1308024Z 
2018-03-26T14:20:29.1308024Z NET USE {devicename | *} [password | *] /HOME
2018-03-26T14:20:29.1308024Z 
2018-03-26T14:20:29.1308024Z NET USE [/PERSISTENT:{YES | NO}]
2018-03-26T14:20:29.1308024Z 
2018-03-26T14:20:29.1308024Z  More help is available by typing NET HELPMSG 3506.
2018-03-26T14:20:29.1308024Z 
2018-03-26T14:20:29.1308024Z 
2018-03-26T14:20:29.1308024Z    --- End of inner exception stack trace ---
2018-03-26T14:20:29.1308024Z    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
2018-03-26T14:20:29.1308024Z    at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
2018-03-26T14:20:29.1308024Z    at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
2018-03-26T14:20:29.1308024Z    at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2018-03-26T14:20:29.1308024Z    at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2018-03-26T14:20:29.1308024Z    at Microsoft.TeamFoundation.DistributedTask.Handlers.LegacyVSTSPowerShellHost.VSTSPowerShellHost.Main(String[] args)
2018-03-26T14:20:29.1464279Z ##[error]LegacyVSTSPowerShellHost.exe completed with return code: -1.
2018-03-26T14:20:29.1464279Z ##[section]Finishing: Copy files from $(System.DefaultWorkingDirectory)/CI/drop
```

With escaping:
```
2018-03-26T14:20:10.2430800Z ##[section]Starting: Copy files from $(System.DefaultWorkingDirectory)/CI/drop
2018-03-26T14:20:10.2430800Z ==============================================================================
2018-03-26T14:20:10.2430800Z Task         : Windows Machine File Copy
2018-03-26T14:20:10.2430800Z Description  : Copy files to remote machine(s)
2018-03-26T14:20:10.2430800Z Version      : 1.0.41
2018-03-26T14:20:10.2430800Z Author       : Microsoft Corporation
2018-03-26T14:20:10.2430800Z Help         : [More Information](https://go.microsoft.com/fwlink/?linkid=627415)
2018-03-26T14:20:10.2430800Z ==============================================================================
2018-03-26T14:20:10.2430800Z Preparing task execution handler.
2018-03-26T14:20:10.5712059Z Executing the powershell script: C:\tfs2017buildagent\_work\_tasks\WindowsMachineFileCopy_731004d4-1d66-4f70-8c05-638018b22210\1.0.41\WindowsMachineFileCopy.ps1
2018-03-26T14:20:11.3680992Z Copy started for - 'mydevserver'
2018-03-26T14:20:11.6026557Z ##[error]System.Management.Automation.RuntimeException: Copying failed for resource : mydevserver
2018-03-26T14:20:11.6026557Z 
2018-03-26T14:20:11.6026557Z       Failed to connect to the path \\mydevserver with the user mydomain\myuser for copying.
2018-03-26T14:20:11.6026557Z     System error 1326 has occurred. 
2018-03-26T14:20:11.6026557Z The user name or password is incorrect.
2018-03-26T14:20:11.6026557Z 
2018-03-26T14:20:11.6026557Z  ---> System.Management.Automation.RuntimeException: Copying failed for resource : mydevserver
2018-03-26T14:20:11.6026557Z 
2018-03-26T14:20:11.6026557Z       Failed to connect to the path \\mydevserver with the user mydomain\myuser for copying.
2018-03-26T14:20:11.6026557Z     System error 1326 has occurred. 
2018-03-26T14:20:11.6026557Z The user name or password is incorrect.
2018-03-26T14:20:11.6026557Z 
2018-03-26T14:20:11.6026557Z 
2018-03-26T14:20:11.6026557Z    --- End of inner exception stack trace ---
2018-03-26T14:20:11.6026557Z    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
2018-03-26T14:20:11.6026557Z    at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
2018-03-26T14:20:11.6026557Z    at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
2018-03-26T14:20:11.6026557Z    at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2018-03-26T14:20:11.6026557Z    at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2018-03-26T14:20:11.6026557Z    at Microsoft.TeamFoundation.DistributedTask.Handlers.LegacyVSTSPowerShellHost.VSTSPowerShellHost.Main(String[] args)
2018-03-26T14:20:11.6181064Z ##[error]LegacyVSTSPowerShellHost.exe completed with return code: -1.
2018-03-26T14:20:11.6181064Z ##[section]Finishing: Copy files from $(System.DefaultWorkingDirectory)/CI/drop
```

**Comment by rokmicrosoft** [comment]
@ascire 
We use "net use \\server\share /user:<domain\username> <password>" to connect another system in same network. Forward slash (/) is normally used to mark switches (options). Using forward slash in options argument can lead to various obscure behaviors, and is best avoided. This is the reason neither ^ or \ escape characters works in our case [Link](http://www.robvanderwoude.com/escapechars.php).

**Comment by rokmicrosoft** [comment]
@ascire 
Can you please change the password to unblock yourself. In next release we are replacing net use with New-PSDrive. Then it will work fine even it contain Forward slash (/) .

**Comment by ascire** [comment]
@rokmicrosoft 
Sounds good.  I am already working around the issue by using a different password.

**Comment by rokmicrosoft** [comment]
@ascire  Thanks for update ..I am closing this thread. Please feel free to contact us If you still face any issue.
