### ISSUE TITLE
$distributedTaskContext is null in custom task after importing DitributedTask.Common and .Internal

### ISSUE THREAD

**Issue by lettucemode** [Microsoft/vsts-tasks#6867]
## Environment
- Server - VSTS or TFS on-premises?
    
    - If using TFS on-premises, provide the version:  **TFS 2017 Version 15.117.26714.0** 

- Agent - Hosted or Private: 
    
    - If using private agent, provide the OS of the machine running the agent and the agent version: 
```**
[2018-03-31 04:04:04Z INFO AgentProcess] Agent is built for Windows - win7-x64.
[2018-03-31 04:04:04Z INFO AgentProcess] RuntimeInformation: Microsoft Windows 10.0.14393 .
[2018-03-31 04:04:04Z INFO AgentProcess] Version: 2.117.2
[2018-03-31 04:04:04Z INFO AgentProcess] Commit: 38c028a22fde25ec5deff999b2518392ba750446
[2018-03-31 04:04:04Z INFO AgentProcess] Culture: en-US
[2018-03-31 04:04:04Z INFO AgentProcess] UI Culture: en-US**
```

## Issue Description

Hello, first off thanks so much for maintaining this project.

I am trying to write a custom build task that associates artifacts to the build and copies the build artifacts out to a file share. The script is in PowerShell. I went back in the PublishBuildArtifacts task history (since it is in Typescript now) and am using the code from there. However I am having trouble calling the method Copy-BuildArtifact because it says the $distributedTaskContext variable is null. Here's the particular call that is having trouble:

```	# gather files into artifact staging folder
	Write-Host (Get-LocalizedString -Key "Preparing artifact content in staging folder {0}..." -ArgumentList $stagingFolder) 
	$artifactStagingFolder = Copy-BuildArtifact $distributedTaskContext $stagingFolder $stagingFolder $ArtifactName $Contents 
```

The version of Microsoft.TeamFoundation.DistributedTask.Task.LegacySDK.dll is 15.108.25929.0. All other relevant examples I can find seem to indicate that the $distributedTaskContext variable should not be null after importing the Internal and Common modules, but that's what is happening for me.

I am pulling the modules from C:\agent\externals\vstshost on the build server, which is not the path I saw in a few other examples. Maybe grabbing the wrong version of the .dll?

I also noticed that the Common and Internal .psd1s and .psm1s do not export any variables, only cmdlets. Do I need to modify one of those?

Thanks in advance!

### Error logs

```
2018-04-03T21:48:02.8764069Z Preparing artifact content in staging folder C:\agent\_work\5\a...
2018-04-03T21:48:02.8834047Z ##[debug]Leaving C:\agent\_work\_tasks\WebBuild_8d0d3400-0435-11e7-9dc6-bb0dbd6a1e16\1.0.17\WebBuild.ps1.
2018-04-03T21:48:02.8884267Z ##[debug]Caught exception from task script.
2018-04-03T21:48:02.8914066Z ##[debug]Error record:
2018-04-03T21:48:02.9534120Z ##[debug]C:\agent\_work\_tasks\WebBuild_8d0d3400-0435-11e7-9dc6-bb0dbd6a1e16\1.0.17\WebBuild.ps1 : Cannot bind argument to parameter 'Context' because it is null.
2018-04-03T21:48:02.9544104Z ##[debug]At line:1 char:1
2018-04-03T21:48:02.9624144Z ##[debug]+ . 'C:\agent\_work\_tasks\WebBuild_8d0d3400-0435-11e7-9dc6-bb0dbd6a ...
2018-04-03T21:48:02.9634178Z ##[debug]+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2018-04-03T21:48:02.9644142Z ##[debug]    + CategoryInfo          : InvalidData: (:) [WebBuild.ps1], ParameterBindingValidationException
2018-04-03T21:48:02.9654183Z ##[debug]    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,WebBuild.ps1
2018-04-03T21:48:02.9664161Z ##[debug] 
2018-04-03T21:48:02.9684142Z ##[debug]Script stack trace:
2018-04-03T21:48:02.9724162Z ##[debug]at <ScriptBlock>, C:\agent\_work\_tasks\WebBuild_8d0d3400-0435-11e7-9dc6-bb0dbd6a1e16\1.0.17\WebBuild.ps1: line 271
2018-04-03T21:48:02.9734184Z ##[debug]at <ScriptBlock>, <No file>: line 1
2018-04-03T21:48:02.9744176Z ##[debug]at <ScriptBlock>, <No file>: line 22
2018-04-03T21:48:02.9754149Z ##[debug]at <ScriptBlock>, <No file>: line 18
2018-04-03T21:48:02.9764149Z ##[debug]at <ScriptBlock>, <No file>: line 1
2018-04-03T21:48:02.9784169Z ##[debug]Exception:
2018-04-03T21:48:02.9834142Z ##[debug]System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'Context' because it is null.
2018-04-03T21:48:02.9844156Z ##[debug]   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
2018-04-03T21:48:02.9854160Z ##[debug]   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
2018-04-03T21:48:02.9864194Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2018-04-03T21:48:02.9874177Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2018-04-03T21:48:02.9884157Z ##[debug]   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
2018-04-03T21:48:02.9904188Z ##[debug]   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
2018-04-03T21:48:02.9914142Z ##[debug]   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
2018-04-03T21:48:02.9924183Z ##[debug]   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
2018-04-03T21:48:02.9934165Z ##[debug]   at System.Management.Automation.CommandProcessorBase.Complete()
2018-04-03T21:48:03.0064168Z ##[error]Cannot bind argument to parameter 'Context' because it is null.
2018-04-03T21:48:03.0064168Z ##[debug]Processed: ##vso[task.logissue type=error]Cannot bind argument to parameter 'Context' because it is null.
2018-04-03T21:48:03.0084187Z ##[debug]Processed: ##vso[task.complete result=Failed]
```

**Comment by bryanmacfarlane** [comment]
Make sure you're using the ps3 handler (and not the deprecated powershell handler) in the task.json exec section.

you may want to log an issue in the vsts-task-lib repo since that's where task authoring stuff is (this repo is for tracking issues with the tasks in this repo).

**Comment by lettucemode** [comment]
I think I'm good there, here's what I have:

```
"execution": {
		"PowerShell3": {
			"target": "PPGWebBuild.ps1"
		}
	},
```

Thanks for the suggestion, I'll follow up with that repo.

**Comment by lettucemode** [comment]
Resolved here: https://github.com/Microsoft/vsts-task-lib/issues/337
