### ISSUE TITLE
Service Fabric Application Deployment task fails if optional RegisterPackageTimeoutSec parameter isn't declared

### ISSUE THREAD

**Issue by remullig** [Microsoft/vsts-tasks#7007]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
VSTS
Account Name: dynamicscrm
Project Name: OneCRM
Release Definition: ManagementServices.Arca.OfficialRelease
Release Numbers: Release 318-321

Agent: Hosted
Agent Queue: Hosted VS2017

## Issue Description

Service Fabric Application Deployment task fails if RegisterPackageTimeoutSec (which is supposed to be optional) isn't declared. This is due to a change made in commit 9fdf39d89d318c5f53b5dbab8e5a668b26cebf90, which was checked into master on March 28. In this commit, the -TimeoutSec $RegisterPackageTimeoutSec parameters were added to line 247, which doesn't check if the timeout is declared in the first place. This change is causing all of our deployments to fail unless this parameter is declared in the task.

### Error logs

2018-04-16T22:04:36.4920720Z ##[debug]Evaluating condition for step: 'Deploy Geneva monitoring agent application'
2018-04-16T22:04:36.4922225Z ##[debug]Evaluating: succeeded()
2018-04-16T22:04:36.4923051Z ##[debug]Evaluating succeeded:
2018-04-16T22:04:36.4924353Z ##[debug]=> (Boolean) True
2018-04-16T22:04:36.4925240Z ##[debug]Expanded: True
2018-04-16T22:04:36.4926053Z ##[debug]Result: True
2018-04-16T22:04:36.4926970Z ##[section]Starting: Deploy Geneva monitoring agent application
2018-04-16T22:04:36.4935808Z ==============================================================================
2018-04-16T22:04:36.4936554Z Task         : Service Fabric Application Deployment
2018-04-16T22:04:36.4937241Z Description  : Deploy a Service Fabric application to a cluster.
2018-04-16T22:04:36.4938149Z Version      : 1.7.5
2018-04-16T22:04:36.4938710Z Author       : Microsoft Corporation
2018-04-16T22:04:36.4939413Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=820528)
2018-04-16T22:04:36.4940162Z ==============================================================================
2018-04-16T22:04:37.7296071Z ##[debug]VstsTaskSdk 0.8.2 commit 
2018-04-16T22:04:38.4719886Z ##[debug]Entering D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.5\deploy.ps1.
2018-04-16T22:04:38.4722321Z ##[debug]Loading resource strings from: D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.5\task.json
2018-04-16T22:04:38.4724075Z ##[debug]Loaded 56 strings.
2018-04-16T22:04:38.4725600Z ##[debug]SYSTEM_CULTURE: 'en-US'
2018-04-16T22:04:38.4726710Z ##[debug]Loading resource strings from: D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.5\Strings\resources.resjson\en-US\resources.resjson
2018-04-16T22:04:38.6500739Z ##[debug]Loaded 56 strings.
2018-04-16T22:04:38.6560799Z ##[debug]Loading module from path 'D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.5\ps_modules\ServiceFabricHelpers\ServiceFabricHelpers.psm1'.
2018-04-16T22:04:38.6654368Z ##[debug]Loading resource strings from: D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.5\ps_modules\ServiceFabricHelpers\module.json
2018-04-16T22:04:38.6886788Z ##[debug]Loaded 11 strings.
2018-04-16T22:04:38.6916249Z ##[debug]SYSTEM_CULTURE: 'en-US'
2018-04-16T22:04:38.6939741Z ##[debug]Loading resource strings from: D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.5\ps_modules\ServiceFabricHelpers\Strings\resources.resjson\en-US\resources.resjson
2018-04-16T22:04:38.7219069Z ##[debug]Loaded 11 strings.
2018-04-16T22:04:38.7442394Z ##[debug]Entering Find-VstsFiles.
2018-04-16T22:04:38.7567448Z ##[debug] LiteralDirectory: 'D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.5\ps_modules\ServiceFabricHelpers'
2018-04-16T22:04:38.7585354Z ##[debug] LegacyPattern: '*.ps1'
2018-04-16T22:04:38.8424860Z ##[debug]Entering Get-MatchingItems.
2018-04-16T22:04:38.8456003Z ##[debug] IncludePatterns: 'D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.5\ps_modules\ServiceFabricHelpers\*.ps1'
2018-04-16T22:04:38.8516909Z ##[debug] ExcludePatterns: ''
2018-04-16T22:04:38.8566052Z ##[debug] IncludeFiles: 'True'
2018-04-16T22:04:38.8585824Z ##[debug] IncludeDirectories: 'False'
2018-04-16T22:04:38.8607776Z ##[debug] Force: 'False'
2018-04-16T22:04:39.2787544Z ##[debug]Paths: D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.5\ps_modules\ServiceFabricHelpers\
2018-04-16T22:04:39.5803674Z ##[debug] Connect-ServiceFabricClusterFromServiceEndpoint.ps1
2018-04-16T22:04:39.5805666Z ##[debug] Get-ServiceFabricEncryptedText.ps1
2018-04-16T22:04:39.5808074Z ##[debug]Leaving Get-MatchingItems.
2018-04-16T22:04:39.5809508Z ##[debug]Total found: 2
2018-04-16T22:04:39.5810609Z ##[debug]Leaving Find-VstsFiles.
2018-04-16T22:04:39.5811767Z ##[debug]Exporting function 'Connect-ServiceFabricClusterFromServiceEndpoint'.
2018-04-16T22:04:39.5812941Z ##[debug]Exporting function 'Get-ServiceFabricEncryptedText'.
2018-04-16T22:04:39.5816031Z ##[debug]Importing function 'Connect-ServiceFabricClusterFromServiceEndpoint'.
2018-04-16T22:04:39.5817275Z ##[debug]Importing function 'Get-ServiceFabricEncryptedText'.
2018-04-16T22:04:39.5818889Z ##[debug]Loading module from path 'D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.5\ps_modules\PowershellHelpers\PowershellHelpers.psm1'.
2018-04-16T22:04:39.5820557Z ##[debug]Loading resource strings from: D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.5\ps_modules\PowershellHelpers\module.json
2018-04-16T22:04:39.5821856Z ##[debug]Loaded 2 strings.
2018-04-16T22:04:39.5822880Z ##[debug]SYSTEM_CULTURE: 'en-US'
2018-04-16T22:04:39.5824249Z ##[debug]Loading resource strings from: D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.5\ps_modules\PowershellHelpers\Strings\resources.resjson\en-US\resources.resjson
2018-04-16T22:04:39.5825749Z ##[debug]Loaded 2 strings.
2018-04-16T22:04:39.5826895Z ##[debug]Exporting function 'Invoke-ActionWithRetries'.
2018-04-16T22:04:39.5828369Z ##[debug]Exporting function 'Get-TempDirectoryPath'.
2018-04-16T22:04:39.5829554Z ##[debug]Importing function 'Get-TempDirectoryPath'.
2018-04-16T22:04:39.5833339Z ##[debug]Importing function 'Invoke-ActionWithRetries'.
2018-04-16T22:04:39.5834690Z ##[debug]INPUT_PUBLISHPROFILEPATH: 'D:\a\r1\a\**\drop\projectartifacts\src\GenevaMonitoringApplication\EnvironmentConfig\TIE\PublishProfiles\ds-tie-bn3-001.xml'
2018-04-16T22:04:39.5835947Z Searching for path: D:\a\r1\a\**\drop\projectartifacts\src\GenevaMonitoringApplication\EnvironmentConfig\TIE\PublishProfiles\ds-tie-bn3-001.xml
2018-04-16T22:04:39.5837205Z ##[debug]Entering Find-VstsFiles.
2018-04-16T22:04:39.5838666Z ##[debug] LegacyPattern: 'D:\a\r1\a\**\drop\projectartifacts\src\GenevaMonitoringApplication\EnvironmentConfig\TIE\PublishProfiles\ds-tie-bn3-001.xml'
2018-04-16T22:04:39.5840012Z ##[debug]Entering Get-MatchingItems.
2018-04-16T22:04:39.5841758Z ##[debug] IncludePatterns: 'D:\a\r1\a\**\drop\projectartifacts\src\GenevaMonitoringApplication\EnvironmentConfig\TIE\PublishProfiles\ds-tie-bn3-001.xml'
2018-04-16T22:04:39.5843888Z ##[debug] ExcludePatterns: ''
2018-04-16T22:04:39.5845477Z ##[debug] IncludeFiles: 'True'
2018-04-16T22:04:39.5847166Z ##[debug] IncludeDirectories: 'False'
2018-04-16T22:04:39.5849049Z ##[debug] Force: 'False'
2018-04-16T22:04:39.8291338Z ##[debug]Path: D:\a\r1\a\arca-tfs publish\drop\projectartifacts\src\GenevaMonitoringApplication\EnvironmentConfig\TIE\PublishProfiles\ds-tie-bn3-001.xml
2018-04-16T22:04:39.8571423Z ##[debug]Leaving Get-MatchingItems.
2018-04-16T22:04:39.8598211Z ##[debug]Total found: 1
2018-04-16T22:04:39.8600007Z ##[debug]Leaving Find-VstsFiles.
2018-04-16T22:04:39.8601979Z ##[debug]Asserting leaf path exists: 'D:\a\r1\a\arca-tfs publish\drop\projectartifacts\src\GenevaMonitoringApplication\EnvironmentConfig\TIE\PublishProfiles\ds-tie-bn3-001.xml'
2018-04-16T22:04:39.8603377Z Found path: D:\a\r1\a\arca-tfs publish\drop\projectartifacts\src\GenevaMonitoringApplication\EnvironmentConfig\TIE\PublishProfiles\ds-tie-bn3-001.xml
2018-04-16T22:04:40.0607196Z ##[debug]INPUT_APPLICATIONPACKAGEPATH: 'D:\a\r1\a\arca-tfs publish\drop\monitoringagent\MonitoringServiceWithMA'
2018-04-16T22:04:40.0618131Z Searching for path: D:\a\r1\a\arca-tfs publish\drop\monitoringagent\MonitoringServiceWithMA
2018-04-16T22:04:40.0640830Z ##[debug]Entering Find-VstsFiles.
2018-04-16T22:04:40.0660591Z ##[debug] LegacyPattern: 'D:\a\r1\a\arca-tfs publish\drop\monitoringagent\MonitoringServiceWithMA'
2018-04-16T22:04:40.0678785Z ##[debug] IncludeDirectories: 'True'
2018-04-16T22:04:40.0708343Z ##[debug]Entering Get-MatchingItems.
2018-04-16T22:04:40.0727295Z ##[debug] IncludePatterns: 'D:\a\r1\a\arca-tfs publish\drop\monitoringagent\MonitoringServiceWithMA'
2018-04-16T22:04:40.0746266Z ##[debug] ExcludePatterns: ''
2018-04-16T22:04:40.0765146Z ##[debug] IncludeFiles: 'False'
2018-04-16T22:04:40.0792347Z ##[debug] IncludeDirectories: 'True'
2018-04-16T22:04:40.0810812Z ##[debug] Force: 'False'
2018-04-16T22:04:40.1195666Z ##[debug]Path: D:\a\r1\a\arca-tfs publish\drop\monitoringagent\MonitoringServiceWithMA
2018-04-16T22:04:40.1216390Z ##[debug]Leaving Get-MatchingItems.
2018-04-16T22:04:40.1234545Z ##[debug]Total found: 1
2018-04-16T22:04:40.1254845Z ##[debug]Leaving Find-VstsFiles.
2018-04-16T22:04:40.1280419Z ##[debug]Asserting container path exists: 'D:\a\r1\a\arca-tfs publish\drop\monitoringagent\MonitoringServiceWithMA'
2018-04-16T22:04:40.1291090Z Found path: D:\a\r1\a\arca-tfs publish\drop\monitoringagent\MonitoringServiceWithMA
2018-04-16T22:04:40.1316480Z ##[debug]INPUT_SERVICECONNECTIONNAME: 'da933a42-81f3-45c7-816e-da31bc0d83f9'
2018-04-16T22:04:40.1453769Z ##[debug]ENDPOINT_URL_da933a42-81f3-45c7-816e-da31bc0d83f9: 'https://ds-tie-bn3-sf1-sf.northcentralus.cloudapp.azure.com:19000/'
2018-04-16T22:04:40.1481095Z ##[debug]ENDPOINT_AUTH_da933a42-81f3-45c7-816e-da31bc0d83f9: '********'
2018-04-16T22:04:40.1510356Z ##[debug]ENDPOINT_DATA_da933a42-81f3-45c7-816e-da31bc0d83f9: '{}'
2018-04-16T22:04:40.1542680Z ##[debug]INPUT_COPYPACKAGETIMEOUTSEC (empty)
2018-04-16T22:04:40.1589561Z ##[debug]INPUT_REGISTERPACKAGETIMEOUTSEC (empty)
2018-04-16T22:04:40.1615365Z ##[debug]INPUT_COMPRESSPACKAGE: 'false'
2018-04-16T22:04:40.1659077Z ##[debug]INPUT_SKIPUPGRADESAMETYPEANDVERSION: 'false'
2018-04-16T22:04:40.1684359Z ##[debug]INPUT_SKIPPACKAGEVALIDATION: 'true'
2018-04-16T22:04:40.1707189Z ##[debug]INPUT_UNREGISTERUNUSEDVERSIONS: 'true'
2018-04-16T22:04:40.2284666Z ##[debug]INPUT_CONFIGUREDOCKERSETTINGS: 'false'
2018-04-16T22:04:40.2577597Z ##[debug]Entering Connect-ServiceFabricClusterFromServiceEndpoint.
2018-04-16T22:04:40.2614512Z ##[debug] ClusterConnectionParameters: 'System.Collections.Hashtable'
2018-04-16T22:04:40.2647031Z ##[debug] ConnectedServiceEndpoint: '@{Url=https://ds-tie-bn3-sf1-sf.northcentralus.cloudapp.azure.com:19000/; Data=; Auth=}'
2018-04-16T22:04:40.3627546Z Imported cluster client certificate with thumbprint '********'.
2018-04-16T22:04:40.3743318Z 
2018-04-16T22:04:40.3748714Z Thumbprint                                Subject                                                                      
2018-04-16T22:04:40.3750172Z ----------                                -------                                                                      
2018-04-16T22:04:40.3751066Z ********  CN=CrmClusterManagement.tie.windows-int.net                                  
2018-04-16T22:04:44.4783306Z Successfully connected to cluster.
2018-04-16T22:04:44.4858066Z ##[debug]Leaving Connect-ServiceFabricClusterFromServiceEndpoint.
2018-04-16T22:04:44.5176954Z ##[debug]INPUT_APPLICATIONPARAMETERPATH: 'D:\a\r1\a'
2018-04-16T22:04:44.5188020Z Searching for path: D:\a\r1\a
2018-04-16T22:04:44.5221956Z ##[debug]Entering Find-VstsFiles.
2018-04-16T22:04:44.5237913Z ##[debug] LegacyPattern: 'D:\a\r1\a'
2018-04-16T22:04:44.5268028Z ##[debug]Entering Get-MatchingItems.
2018-04-16T22:04:44.5294467Z ##[debug] IncludePatterns: 'D:\a\r1\a'
2018-04-16T22:04:44.5313246Z ##[debug] ExcludePatterns: ''
2018-04-16T22:04:44.5332719Z ##[debug] IncludeFiles: 'True'
2018-04-16T22:04:44.5351091Z ##[debug] IncludeDirectories: 'False'
2018-04-16T22:04:44.5368994Z ##[debug] Force: 'False'
2018-04-16T22:04:44.7738845Z ##[debug]No paths.
2018-04-16T22:04:44.7759662Z ##[debug]Leaving Get-MatchingItems.
2018-04-16T22:04:44.7783592Z ##[debug]Total found: 0
2018-04-16T22:04:44.7800864Z ##[debug]Leaving Find-VstsFiles.
2018-04-16T22:04:44.7825742Z No items were found with search pattern D:\a\r1\a.
2018-04-16T22:04:44.7881998Z ##[debug]Asserting leaf path exists: 'D:\a\r1\a\arca-tfs publish\drop\projectartifacts\src\GenevaMonitoringApplication\EnvironmentConfig\TIE\PublishProfiles\..\ApplicationParameters\ds-tie-bn3-001.xml'
2018-04-16T22:04:44.7908170Z ##[debug]INPUT_OVERRIDEPUBLISHPROFILESETTINGS: 'false'
2018-04-16T22:04:45.0113254Z ##[debug]INPUT_USEDIFFPACKAGE: 'true'
2018-04-16T22:04:45.0134165Z ##[debug]Loading module from path 'D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.5\Create-DiffPackage.psm1'.
2018-04-16T22:04:45.0189117Z ##[debug]Exporting function 'Create-DiffPackage'.
2018-04-16T22:04:45.0206215Z ##[debug]Exporting function 'Copy-DiffPackage'.
2018-04-16T22:04:45.0222253Z ##[debug]Importing function 'Copy-DiffPackage'.
2018-04-16T22:04:45.0515300Z ##[warning]The names of some imported commands from the module 'Create-DiffPackage' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
2018-04-16T22:04:45.0531514Z ##[debug]Processed: ##vso[task.logissue type=warning]The names of some imported commands from the module 'Create-DiffPackage' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
2018-04-16T22:04:45.0533542Z ##[debug]The 'Create-DiffPackage' command in the Create-DiffPackage' module was imported, but because its name does not include an approved verb, it might be difficult to find. The suggested alternative verbs are "New".
2018-04-16T22:04:45.0534520Z ##[debug]Importing function 'Create-DiffPackage'.
2018-04-16T22:04:45.0735476Z ##[debug]Entering Create-DiffPackage.
2018-04-16T22:04:45.0751085Z ##[debug] ApplicationName: 'fabric:/ArcaFabricMonitoringService'
2018-04-16T22:04:45.0766096Z ##[debug] ApplicationPackagePath: 'D:\a\r1\a\arca-tfs publish\drop\monitoringagent\MonitoringServiceWithMA'
2018-04-16T22:04:45.0790128Z ##[debug] ConnectedServiceEndpoint: '@{Url=https://ds-tie-bn3-sf1-sf.northcentralus.cloudapp.azure.com:19000/; Data=; Auth=}'
2018-04-16T22:04:45.0805824Z ##[debug] ClusterConnectionParameters: 'System.Collections.Hashtable'
2018-04-16T22:04:45.0813339Z Trying to create diff package...
2018-04-16T22:04:45.0836184Z ##[debug]Importing function 'Connect-ServiceFabricClusterFromServiceEndpoint'.
2018-04-16T22:04:45.0851692Z ##[debug]Importing function 'Get-ServiceFabricEncryptedText'.
2018-04-16T22:04:45.0871537Z ##[debug]Importing function 'Get-TempDirectoryPath'.
2018-04-16T22:04:45.0886117Z ##[debug]Importing function 'Invoke-ActionWithRetries'.
2018-04-16T22:04:45.1186746Z The application fabric:/ArcaFabricMonitoringService to be upgraded by using diff package does not exist in the cluster https://ds-tie-bn3-sf1-sf.northcentralus.cloudapp.azure.com:19000/. Applying full application packge to do the deployment now...
2018-04-16T22:04:45.1203591Z ##[debug]Leaving Create-DiffPackage.
2018-04-16T22:04:45.1325810Z ##[debug]INPUT_OVERWRITEBEHAVIOR: 'Always'
2018-04-16T22:04:45.3377287Z Application type 'ArcaFabricMonitoringServiceApplication' and version '6.0.20' was already registered with the cluster, unregistering it...
2018-04-16T22:04:45.4476758Z ##[debug]Leaving D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.5\deploy.ps1.
2018-04-16T22:04:45.4569775Z ##[debug]Caught exception from task script.
2018-04-16T22:04:45.4600469Z ##[debug]Error record:
2018-04-16T22:04:45.5121702Z ##[debug]Unregister-ServiceFabricApplicationType : PowerShell timeout in seconds cannot be negative or zero
2018-04-16T22:04:45.5131672Z ##[debug]At D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.5\ServiceFabricSDK\Publish-NewServiceFabricApplication.ps1:247 char:24
2018-04-16T22:04:45.5142150Z ##[debug]+ ...      $reg | Unregister-ServiceFabricApplicationType -Force -TimeoutSe ...
2018-04-16T22:04:45.5152475Z ##[debug]+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2018-04-16T22:04:45.5163607Z ##[debug]    + CategoryInfo          : NotSpecified: (:) [Unregister-ServiceFabricApplicationType], ArgumentException
2018-04-16T22:04:45.5173530Z ##[debug]    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.ServiceFabric.Powershell.UnregisterApplicationType
2018-04-16T22:04:45.5183647Z ##[debug] 
2018-04-16T22:04:45.5200086Z ##[debug]Script stack trace:
2018-04-16T22:04:45.5232614Z ##[debug]at Publish-NewServiceFabricApplication, D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.5\ServiceFabricSDK\Publish-NewServiceFabricApplication.ps1: line 247
2018-04-16T22:04:45.5242770Z ##[debug]at <ScriptBlock>, D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.5\deploy.ps1: line 179
2018-04-16T22:04:45.5252850Z ##[debug]at <ScriptBlock>, <No file>: line 1
2018-04-16T22:04:45.5262243Z ##[debug]at <ScriptBlock>, <No file>: line 22
2018-04-16T22:04:45.5283492Z ##[debug]at <ScriptBlock>, <No file>: line 18
2018-04-16T22:04:45.5289101Z ##[debug]at <ScriptBlock>, <No file>: line 1
2018-04-16T22:04:45.5307034Z ##[debug]Exception:
2018-04-16T22:04:45.5347553Z ##[debug]System.ArgumentException: PowerShell timeout in seconds cannot be negative or zero
2018-04-16T22:04:45.5357421Z ##[debug]   at Microsoft.ServiceFabric.Powershell.CommonCmdletBase.GetTimeout()
2018-04-16T22:04:45.5368089Z ##[debug]   at Microsoft.ServiceFabric.Powershell.ApplicationCmdletBase.UnregisterApplicationType(UnprovisionApplicationTypeDescription description)
2018-04-16T22:04:45.5377931Z ##[debug]   at Microsoft.ServiceFabric.Powershell.UnregisterApplicationType.ProcessRecord()
2018-04-16T22:04:45.5388396Z ##[debug]   at System.Management.Automation.CommandProcessor.ProcessRecord()
2018-04-16T22:04:45.5439871Z ##[error]PowerShell timeout in seconds cannot be negative or zero
2018-04-16T22:04:45.5441092Z ##[debug]Processed: ##vso[task.logissue type=error]PowerShell timeout in seconds cannot be negative or zero
2018-04-16T22:04:45.5444788Z ##[debug]Processed: ##vso[task.complete result=Failed]
2018-04-16T22:04:45.6154858Z ##[section]Finishing: Deploy Geneva monitoring agent application

**Comment by wahabakhtar** [comment]
Having the same issue in our environment? Is there a work around for now?

**Comment by remullig** [comment]
I ended up having to declare a large timeout time in each of our deploy application tasks (the RegisterPackageTimeoutSec parameter) to mitigate.

**Comment by Falconwmua** [comment]
@remullig where are you setting the timeout time? "TimeoutSec"?

**Comment by remullig** [comment]
No, "RegisterPackageTimeoutSec" under advanced settings.

**Comment by sachinma** [comment]
Thanks for reporting this. We have identified the issue and are fixing it in #7033

**Comment by sachinma** [comment]
This has now been resolved.
