### ISSUE TITLE
Starting Http listener in VS Test fails with AccessDenied

### ISSUE THREAD

**Issue by vaishnavk** [Microsoft/vsts-tasks#7010]
We have a test which brings up a Owin Selfhost. The test fails with access denied when running it through the VS Test Task.

Error message
Initialization method VolumeResourceManager.Test.VolumeResourceManagerTest.TestSetup threw exception. System.Net.HttpListenerException: Access is denied.
Stack trace
at System.Net.HttpListener.AddAllPrefixes()

at System.Net.HttpListener.Start()

at Microsoft.Owin.Host.HttpListener.OwinHttpListener.Start(HttpListener listener, Func`2 appFunc, IList`1 addresses, IDictionary`2 capabilities, Func`2 loggerFactory)

at Microsoft.Owin.Host.HttpListener.OwinServerFactory.Create(Func`2 app, IDictionary`2 properties)

https://msazure.visualstudio.com/One/Service%20Fabric/_build/index?buildId=12478884&_a=summary&tab=ms.vss-test-web.test-result-details

I am guessing this is because the tests are run with lower privilege. I couldn't find an option in VS Test task to run it with higher privilege. Any idea on how to fix this?

**Comment by cltshivash** [comment]
@vaishnavk You will need to run the automation agent under the user credentials that can do the above operation. There's no option currently in the vstest framework/task to run as a specific user.
