### ISSUE TITLE
Azure CLI: [Errno 2] No such file or directory: 'gp2P(eXdo'

### ISSUE THREAD

**Issue by jordanchang** [Microsoft/vsts-tasks#7025]
VSTS, Hosted VS 2017

Unable to run Azure cli task, fails on logging in with service principal.
### Error logs

C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" login --service-principal -u ******** -p ******** --tenant ********"
ERROR: [Errno 2] No such file or directory: 'gp2P(eXdo'
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 100, in _expand_file_prefix
    return '='.join([arg_split[0], _maybe_load_file(arg_split[1])])
IndexError: list index out of range
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\knack\cli.py", line 194, in invoke
    cmd_result = self.invocation.execute(args)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 215, in execute
    args = _pre_command_table_create(self.cli_ctx, args)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 109, in _pre_command_table_create
    return _expand_file_prefixed_files(args)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 104, in _expand_file_prefixed_files
    return list([_expand_file_prefix(arg) for arg in args])
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 104, in <listcomp>
    return list([_expand_file_prefix(arg) for arg in args])
task result: Failed
Script failed with error: ERROR: [Errno 2] No such file or directory: 'gp2P(eXdo'

**Comment by hiyadav** [comment]
Closing issue, you can reopen if still facing this.
