### ISSUE TITLE
Improve error message when ArtifactName is not provided as input to DownloadBuildArtifacts task

### ISSUE THREAD

**Issue by GitHubSriramB** [Microsoft/vsts-tasks#7186]
We removed the default value for the artifact name as "drop" in 0.134.1 version of task.

With this YAML generated does not have any value for the artifact name resulting in the download failing with cryptic error. Need to improve the error message in the task.

Task logs:

2018-05-10T15:31:58.1201691Z ##[section]Starting: Download Build Artifacts
2018-05-10T15:31:58.1428383Z ==============================================================================
2018-05-10T15:31:58.1428647Z Task         : Download Build Artifacts
2018-05-10T15:31:58.1428767Z Description  : Download Build Artifacts
2018-05-10T15:31:58.1428876Z Version      : 0.134.1
2018-05-10T15:31:58.1429062Z Author       : Microsoft Corporation
2018-05-10T15:31:58.1429171Z Help         : 
2018-05-10T15:31:58.1429286Z ==============================================================================
2018-05-10T15:31:59.1524156Z Downloading artifacts for build: 906868
2018-05-10T15:31:59.1524404Z Successfully downloaded artifacts to M:\GeneralVS15-052\_work\27\a
2018-05-10T15:31:59.1542330Z M:\GeneralVS15-052\_work\_tasks\DownloadBuildArtifacts_a433f589-fce1-4460-9ee6-44a624aeb1fb\0.134.1\node_modules\artifact-engine\Engine\artifactEngine.js:145
2018-05-10T15:31:59.2063508Z     throw err;
2018-05-10T15:31:59.2063689Z     ^
2018-05-10T15:31:59.2063815Z 
2018-05-10T15:31:59.2063924Z TypeError: Cannot read property 'type' of undefined
2018-05-10T15:31:59.2064104Z     at M:\GeneralVS15-052\_work\_tasks\DownloadBuildArtifacts_a433f589-fce1-4460-9ee6-44a624aeb1fb\0.134.1\main.js:211:46
2018-05-10T15:31:59.2064245Z     at next (native)
2018-05-10T15:31:59.2064404Z     at M:\GeneralVS15-052\_work\_tasks\DownloadBuildArtifacts_a433f589-fce1-4460-9ee6-44a624aeb1fb\0.134.1\main.js:7:71
2018-05-10T15:31:59.2064645Z     at __awaiter (M:\GeneralVS15-052\_work\_tasks\DownloadBuildArtifacts_a433f589-fce1-4460-9ee6-44a624aeb1fb\0.134.1\main.js:3:12)
2018-05-10T15:31:59.2064829Z     at M:\GeneralVS15-052\_work\_tasks\DownloadBuildArtifacts_a433f589-fce1-4460-9ee6-44a624aeb1fb\0.134.1\main.js:204:28
2018-05-10T15:31:59.2064968Z     at Array.forEach (native)
2018-05-10T15:31:59.2065129Z     at M:\GeneralVS15-052\_work\_tasks\DownloadBuildArtifacts_a433f589-fce1-4460-9ee6-44a624aeb1fb\0.134.1\main.js:203:27
2018-05-10T15:31:59.2065288Z     at next (native)
2018-05-10T15:31:59.2065443Z     at fulfilled (M:\GeneralVS15-052\_work\_tasks\DownloadBuildArtifacts_a433f589-fce1-4460-9ee6-44a624aeb1fb\0.134.1\main.js:4:58)
2018-05-10T15:31:59.2065617Z     at process._tickCallback (internal/process/next_tick.js:109:7)
2018-05-10T15:31:59.2117863Z ##[error]artifact-engine: unhandled rejection TypeError: Cannot read property 'type' of undefined
2018-05-10T15:31:59.2128895Z ##[error]Unhandled: Cannot read property 'type' of undefined
2018-05-10T15:31:59.2129905Z ##[error]Unhandled: Cannot read property 'type' of undefined
2018-05-10T15:31:59.2585778Z ##[error]artifact-engine: unhandled exception TypeError: Cannot read property 'type' of undefined
2018-05-10T15:31:59.2818687Z ##[error]Exit code 7 returned from process: file name 'M:\GeneralVS15-052\externals\node\bin\node.exe', arguments '"M:\GeneralVS15-052\_work\_tasks\DownloadBuildArtifacts_a433f589-fce1-4460-9ee6-44a624aeb1fb\0.134.1\main.js"'.
2018-05-10T15:31:59.2842958Z ##[section]Finishing: Download Build Artifacts

**Comment by GitHubSriramB** [comment]
This is done with following commit:
https://github.com/Microsoft/vsts-tasks/commit/7ef5be6bc47b37eb74e1e57d2d63da856e03c6a6#diff-3838eb12f4eeaf3635c031b2de8ad1a6
