### ISSUE TITLE
Multi-Agent with Visual Studio Test task is not working

### ISSUE THREAD

**Issue by ggenetec** [Microsoft/vsts-tasks#7265]
We are using TFS 2017.2
![image](https://user-images.githubusercontent.com/39531977/40380298-af3879b8-5dc6-11e8-8c32-122ce9202dfb.png)

using Visual studio Test Version 2.*

when running tests on single agent, tests runs with pass or failed results.
when using Multi-Agent, we get System.IndexOutOfRangeException
![image](https://user-images.githubusercontent.com/39531977/40380343-d5804c22-5dc6-11e8-9cfa-3c04ef2f6332.png)

##[error]ExecutionTaskStateModel.ExecuteTask : An exception occured while executing the task. So the task is not executed. System.IndexOutOfRangeException: Index was outside the bounds of the array.
at Minimatch.Minimatcher.MatchOne(IList`1 file, IList`1 pattern, Boolean partial)
at Minimatch.Minimatcher.Match(String input, Boolean partial)
at Minimatch.Minimatcher.IsMatch(String input)
at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
at Microsoft.VisualStudio.TestService.VstestAdapter.MiniMatchSourceFilter.FilterSources() in E:\v2.0\A5\_work\1\s\Ta\Agent\VS.TestService.VstestAdapter\MiniMatchSourceFilter.cs:line 68
at Microsoft.VisualStudio.TestService.VstestAdapter.RunDetailsStore.NormalizeSettings() in E:\v2.0\A5\_work\1\s\Ta\Agent\VS.TestService.VstestAdapter\SliceDetailsStore.cs:line 154
at Microsoft.VisualStudio.TestService.VstestAdapter.RunDetailsStore.set_CurrentSliceDetails(TestAutomationRunSlice value) in E:\v2.0\A5\_work\1\s\Ta\Agent\VS.TestService.VstestAdapter\SliceDetailsStore.cs:line 57
at Microsoft.VisualStudio.TestService.VstestAdapter.VstestAdapter.ExecuteAsync(TestAutomationRunSlice sliceDetails, CancellationToken cancellationToken, IProgress`1 progress) in E:\v2.0\A5\_work\1\s\Ta\Agent\VS.TestService.VstestAdapter\VstestAdapter.cs:line 52
at Microsoft.VisualStudio.TestService.AgentExecutionHost.ExecutionTaskStateModel.GetExecutionTask(CancellationToken cancellationToken) in E:\v2.0\A5\_work\1\s\Ta\Agent\VS.TestService.AgentExecutionHost\ExecutionTaskStateModel.cs:line 351
at Microsoft.VisualStudio.TestService.AgentExecutionHost.ExecutionTaskStateModel.ExecuteTask(CancellationToken cancellationToken) in E:\v2.0\A5\_work\1\s\Ta\Agent\VS.TestService.AgentExecutionHost\ExecutionTaskStateModel.cs:line 189
##[error]ExecutionTaskStateModel.AbortSlice : System.IndexOutOfRangeException: Index was outside the bounds of the array.

**Comment by prawalagarwal** [comment]
@ggenetec  Thanks for reaching out. Two points:
1) Currently we do not support UNC paths for "Search Folder" input. The error you see comes up because the filter on task fails to process a UNC path correctly. Please use a File copy task before VsTest task to copy the files to a local agent location and then use that path in your task.

2) To utilize the multi-agent scenario in VsTest task, please update to Update 3 of TFS 2017. You will an Advanced Options in the task post that which lets you customize on how you wish to distribute your tests.

**Comment by prawalagarwal** [comment]
@ggenetec  Are you unblocked?

**Comment by ggenetec** [comment]
I changed the path a simple name of a dll in "test assemblies" but it is still not working :(
"folder' does not contain any assemblies that match the specified criteria: 'Genetec.Media.Tests.dll'.
I checked <folder> and the dll is there. I tried with 'Genetec.Media.Tests*.dll' still same error

**Comment by prawalagarwal** [comment]
Did you change your input to "Search Folder" field? As I mentioned earlier, UNC paths are not supported in that field.

**Comment by ggenetec** [comment]
changing to Agent.ROOTDIRECTORY solved the problem. Thanks

**Comment by prawalagarwal** [comment]
Thanks for reporting back.
