### ISSUE TITLE
ChefKnife task failing with ruby_env

### ISSUE THREAD

**Issue by arunprakashwa** [Microsoft/vsts-tasks#7267]
## Issue Description

Chef knife task is failing with below error, even before it is getting into executing the script that is passed for the task. Looks like this is being affected by the number of artifacts present on the release definition. 
### Error logs

2018-05-22T15:10:25.3234984Z ##[debug]Creating Chef Repo
2018-05-22T15:10:25.3470854Z ##[debug]userName = ***
2018-05-22T15:10:25.3532142Z ##[debug]organizationUrl = https://<myUrl>
2018-05-22T15:10:25.4253307Z ##[debug]Running knife command: knife configure --repository 'C:\Windows\TEMP\35067df2-f9f0-42b9-be4d-53e091ab6a8a' --server-url 'https://<myUrl>' --user '***' --validation-client-name '***'  --validation-key '***.pem' --config 'C:\Windows\TEMP\35067df2-f9f0-42b9-be4d-53e091ab6a8a\.chef\knife.rb' --yes
2018-05-22T15:10:37.3481288Z ##[debug]Deleting Chef Repo
2018-05-22T15:10:37.3533961Z ##[debug]Chef Repo Deleted
2018-05-22T15:10:37.4068058Z ##[error]System.Management.Automation.ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/ssl_env_hack.rb:30:in `[]=': Invalid argument - ruby_setenv(SSL_CERT_FILE) (Errno::EINVAL)
2018-05-22T15:10:37.4087644Z ##[debug]Processed: ##vso[task.logissue type=error;]System.Management.Automation.ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/ssl_env_hack.rb:30:in `[]=': Invalid argument - ruby_setenv(SSL_CERT_FILE) (Errno::EINVAL)
2018-05-22T15:10:37.4089092Z    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
2018-05-22T15:10:37.4089864Z    at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
2018-05-22T15:10:37.4090466Z    at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
2018-05-22T15:10:37.4090985Z    at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2018-05-22T15:10:37.4091809Z    at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2018-05-22T15:10:37.4092422Z    at Microsoft.TeamFoundation.DistributedTask.Handlers.LegacyVSTSPowerShellHost.VSTSPowerShellHost.Main(String[] args)
2018-05-22T15:10:37.4204854Z ##[error]LegacyVSTSPowerShellHost.exe completed with return code: -1.

**Comment by RoopeshNair** [comment]
@arunprakashwa - Chef Knife task is deprecated. The Chef and Chef Knife task will be removed. Our recommendation is to use the tasks from Chef extension available in VSTS marketplace
