### ISSUE TITLE
Vs test failed but all tests passed OK

### ISSUE THREAD

**Issue by yhan** [Microsoft/vsts-tasks#7358]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - VSTS or TFS on-premises?
 tfs 2018
    
    - If using TFS on-premises, provide the version:  2018
    
    - If using VSTS, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description
All my tests pass but I have:
2018-06-01T16:37:32.7021501Z Total tests: Unknown. Passed: 12. Failed: 0. Skipped: 0.
2018-06-01T16:37:32.7023340Z Test Run Aborted.
2018-06-01T16:37:32.7034948Z Test execution time: 6,1030 Seconds
2018-06-01T16:37:32.7367752Z Results File: E:\Builds\TheFuture01\_work\120\s\TestResults\compilhooker_01TFSBLDAM01_2018-06-01_18_37_31.trx
2018-06-01T16:37:32.7672139Z ##[warning]Vstest failed with error. Check logs for failures. There might be failed tests.
2018-06-01T16:37:32.8502876Z ##[error]Error: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe failed with return code: 1
2018-06-01T16:37:33.1862647Z ##[error]VsTest task failed.

my csproj

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Toolbox.WebApi.Health.SQL\Toolbox.WebApi.Health.SQL.csproj" />
    <ProjectReference Include="..\..\src\ToolBox.WebApi.Health\ToolBox.WebApi.Health.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.7.2" />
    <PackageReference Include="newtonsoft.json" Version="11.0.2" />
    <PackageReference Include="nfluent" Version="2.2.0" />
    <PackageReference Include="nunit" Version="3.10.1" />
    <PackageReference Include="nsubstitute" Version="3.1.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.10.0" />
  </ItemGroup>

</Project>

[Include task name(s), screenshots and any other relevant details]

### Error logs

[Insert error from the logs here]

If I run cmd or open E:\Builds\TheFuture01\_work\120\s\TestResults\compilhooker_01TFSBLDAM01_2018-06-01_18_37_31.trx, I have:

C:\Users\compilhooker>"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" "E:\Builds\TheFuture01\_work\120\s\tests\ToolBox.WebApi.Health.Tests\obj\Release\netcoreapp2.1\ToolBox.WebApi.Health.Tests.dll" /logger:trx
Microsoft (R) Test Execution Command Line Tool Version 15.6.1
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
System.IO.FileNotFoundException: No test is available in E:\Builds\TheFuture01\_work\120\s\tests\ToolBox.WebApi.Health.Tests\obj\Release\netcoreapp2.1\ToolBox.WebApi.Health.Tests.dll. Make sure test project has a nuget reference of package "Microsoft.NET.Test.Sdk" and framework version settings are appropriate and try again.
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.GetTestHostProcessStartInfo(IEnumerable`1 sources, IDictionary`2 environmentVariables, TestRunnerConnectionInfo connectionInfo)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyExecutionManager.StartTestRun(TestRunCriteria testRunCriteria, ITestRunEventsHandler eventHandler)

Test Run Aborted.

**Comment by prawalagarwal** [comment]
Hi @yhan 
netcoreapp tests are not supported via VsTest task. Please use the .Net task to run these.

**Comment by acesiddhu** [comment]
As @prawalagarwal suggested please use .net task to run netcore tests

**Comment by yhan** [comment]
I resolved by excluding NUnit3.TestAdapter.dll as part of Testing assembly ( before this resolution, wildcard *test* was used.

Now, the filter is 
```
**\*test*.dll
!**\*TestAdapter.dll
!**\obj\**
```

So I suppose that what is meant by 

> No test is available in E:\Builds\TheFuture01_work\120\s\tests\ToolBox.WebApi.Health.Tests\obj\Release\netcoreapp2.1\ToolBox.WebApi.Health.Tests.dll. 

is test runner found no test in NUnit3.TestAdapter.dll, which is normal. ;)

As task, I do use Visual Studio Test. That does not seem a problem.

**Comment by tanbchr** [comment]
@yhan solution worked for me.
