### ISSUE TITLE
Import-Module AzureRM fails with The TypeConverter was ignored because it already occurs

### ISSUE THREAD

**Issue by Naninani** [Microsoft/vsts-tasks#7443]
## Environment
VSTS

- Agent: Private

- Windows 10 Enterprise N

## Issue Description
Import-Module -Name C:\Program Files\WindowsPowerShell\Modules\AzureRM\5.6.0\AzureRM.psd1 -Global fails with:

Error in TypeData "Microsoft.Azure.Commands.Common.Authentication.Abstractions.IAzureContextContainer": The TypeConverter was ignored because it already occurs.

Details:

This occurs when the module is already imported and you try to import new version.

==============================================================================
Task         : Azure PowerShell
Description  : Run a PowerShell script within an Azure environment
Version      : 1.113.5
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613749)
==============================================================================

AzureRM version 5.2.0

Failed command: 
##[command]Import-Module -Name C:\Program Files\WindowsPowerShell\Modules\AzureRM\5.6.0\AzureRM.psd1 -Global

### Error logs

2018-06-12T20:58:33.0134658Z 'C:\Users\<user>\Documents\WindowsPowerShell\Modules\AzureRM.Profile\5.2.0\Microsoft.Azure.Commands.Profile.fo
2018-06-12T20:58:33.0135572Z rmat.ps1xml'.
2018-06-12T20:58:33.1440057Z ##[debug]Leaving Import-FromModulePath.
2018-06-12T20:58:33.1472811Z ##[debug]Leaving Import-AzureModule.
2018-06-12T20:58:33.1502244Z ##[debug]Leaving Initialize-Azure.
2018-06-12T20:58:33.1556380Z ##[debug]Caught exception from task script.
2018-06-12T20:58:33.1585446Z ##[debug]Error record:
2018-06-12T20:58:33.2573751Z ##[debug]The following error occurred while loading the extended type data file: Error in TypeData "Microsoft.Azure.Commands.Common.Authentication.Abstractions.IAzureContextContainer": The TypeConverter was ignored because it already occurs.
2018-06-12T20:58:33.2586179Z ##[debug]Error in TypeData "Microsoft.Azure.Commands.Common.Authentication.Abstractions.IAzureContextContainer": The member SerializationDepth is already present.
2018-06-12T20:58:33.2599107Z ##[debug]Error in TypeData "Microsoft.Azure.Commands.Common.Authentication.ProtectedFileTokenCache": The member PropertySerializationSet is already present.
2018-06-12T20:58:33.2611729Z ##[debug]Error in TypeData "Microsoft.Azure.Commands.Common.Authentication.ProtectedFileTokenCache": The member SerializationMethod is already present.
2018-06-12T20:58:33.2624896Z ##[debug]Error in TypeData "Microsoft.Azure.Commands.Common.Authentication.AuthenticationStoreTokenCache": The member PropertySerializationSet is already present.
2018-06-12T20:58:33.2637584Z ##[debug]Error in TypeData "Microsoft.Azure.Commands.Common.Authentication.AuthenticationStoreTokenCache": The member SerializationMethod is already present.
2018-06-12T20:58:33.2649929Z ##[debug]Error in TypeData "Microsoft.Azure.Commands.Profile.Models.PSAzureContext": The member SerializationDepth is already present.
2018-06-12T20:58:33.2663009Z ##[debug]Error in TypeData "Microsoft.Azure.Commands.Profile.Models.PSAzureProfile": The member SerializationDepth is already present.
2018-06-12T20:58:33.2675417Z ##[debug]
2018-06-12T20:58:33.2704356Z ##[debug]    + CategoryInfo          : NotSpecified: (:) [], RuntimeException
2018-06-12T20:58:33.2705600Z ##[debug]    + FullyQualifiedErrorId : ErrorsUpdatingTypes
2018-06-12T20:58:33.2714140Z ##[debug] 
2018-06-12T20:58:33.2734637Z ##[debug]Script stack trace:
2018-06-12T20:58:33.2780322Z ##[debug]
2018-06-12T20:58:33.2799488Z ##[debug]Exception:
2018-06-12T20:58:33.2845002Z ##[debug]System.Management.Automation.RuntimeException: The following error occurred while loading the extended type data file: Error in TypeData "Microsoft.Azure.Commands.Common.Authentication.Abstractions.IAzureContextContainer": The TypeConverter was ignored because it already occurs.
2018-06-12T20:58:33.2857347Z ##[debug]Error in TypeData "Microsoft.Azure.Commands.Common.Authentication.Abstractions.IAzureContextContainer": The member SerializationDepth is already present.
2018-06-12T20:58:33.2869995Z ##[debug]Error in TypeData "Microsoft.Azure.Commands.Common.Authentication.ProtectedFileTokenCache": The member PropertySerializationSet is already present.
2018-06-12T20:58:33.2883336Z ##[debug]Error in TypeData "Microsoft.Azure.Commands.Common.Authentication.ProtectedFileTokenCache": The member SerializationMethod is already present.
2018-06-12T20:58:33.2895795Z ##[debug]Error in TypeData "Microsoft.Azure.Commands.Common.Authentication.AuthenticationStoreTokenCache": The member PropertySerializationSet is already present.
2018-06-12T20:58:33.2908513Z ##[debug]Error in TypeData "Microsoft.Azure.Commands.Common.Authentication.AuthenticationStoreTokenCache": The member SerializationMethod is already present.
2018-06-12T20:58:33.2921035Z ##[debug]Error in TypeData "Microsoft.Azure.Commands.Profile.Models.PSAzureContext": The member SerializationDepth is already present.
2018-06-12T20:58:33.2934009Z ##[debug]Error in TypeData "Microsoft.Azure.Commands.Profile.Models.PSAzureProfile": The member SerializationDepth is already present.
2018-06-12T20:58:33.2946183Z ##[debug]
2018-06-12T20:58:33.2959209Z ##[debug]   at System.Management.Automation.Runspaces.InitialSessionState.ThrowTypeOrFormatErrors(String resourceString, String errorMsg, String errorId)
2018-06-12T20:58:33.2971212Z ##[debug]   at System.Management.Automation.Runspaces.InitialSessionState.UpdateTypes(ExecutionContext context, Boolean updateOnly)
2018-06-12T20:58:33.2983861Z ##[debug]   at System.Management.Automation.Runspaces.InitialSessionState.Bind_UpdateTypes(ExecutionContext context, Boolean updateOnly)
2018-06-12T20:58:33.2996133Z ##[debug]   at System.Management.Automation.Runspaces.InitialSessionState.Bind(ExecutionContext context, Boolean updateOnly, PSModuleInfo module, Boolean noClobber, Boolean local)
2018-06-12T20:58:33.3008684Z ##[debug]   at System.Management.Automation.Runspaces.InitialSessionState.Bind(ExecutionContext context, Boolean updateOnly)
2018-06-12T20:58:33.3021731Z ##[debug]   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleManifest(String moduleManifestPath, ExternalScriptInfo manifestScriptInfo, Hashtable data, Hashtable localizedData, ManifestProcessingFlags manifestProcessingFlags, Version minimumVersion, Version maximumVersion, Version requiredVersion, Nullable`1 requiredModuleGuid, ImportModuleOptions& options, Boolean& containedErrors)
2018-06-12T20:58:33.3326444Z ##[error]The following error occurred while loading the extended type data file: Error in TypeData "Microsoft.Azure.Commands.Common.Authentication.Abstractions.IAzureContextContainer": The TypeConverter was ignored because it already occurs.
Error in TypeData "Microsoft.Azure.Commands.Common.Authentication.Abstractions.IAzureContextContainer": The member SerializationDepth is already present.
Error in TypeData "Microsoft.Azure.Commands.Common.Authentication.ProtectedFileTokenCache": The member PropertySerializationSet is already present.
Error in TypeData "Microsoft.Azure.Commands.Common.Authentication.ProtectedFileTokenCache": The member SerializationMethod is already present.
Error in TypeData "Microsoft.Azure.Commands.Common.Authentication.AuthenticationStoreTokenCache": The member PropertySerializationSet is already present.
Error in TypeData "Microsoft.Azure.Commands.Common.Authentication.AuthenticationStoreTokenCache": The member SerializationMethod is already present.
Error in TypeData "Microsoft.Azure.Commands.Profile.Models.PSAzureContext": The member SerializationDepth is already present.
Error in TypeData "Microsoft.Azure.Commands.Profile.Models.PSAzureProfile": The member SerializationDepth is already present.

Related to [https://github.com/Azure/azure-powershell/issues/4835](url)

Fix: Running the Import-Module with -Force will fix this
i.e.
Import-Module -Name C:\Program Files\WindowsPowerShell\Modules\AzureRM\5.6.0\AzureRM.psd1 -Global -Force

**Comment by Naninani** [comment]
PR with the fix: [https://github.com/Microsoft/vsts-tasks/pull/7444](url)

**Comment by johnhydemtm365** [comment]
Hi there, I am also experiencing this issue. I have tried using Version 1 and Version 2 (Preview) of the task. I am running powershell 5.6.0, but the error also happens with 5.1.1.

I have rebooted the build machine a couple of times, but no joy.

The following error occurred while loading the extended type data file: Error in TypeData "Microsoft.Azure.Commands.Common.Authentication.Abstractions.IAzureContextContainer": The TypeConverter was ignored because it already occurs.

Full logs attached
Thanks
John

[Vsts_AzcopyTaskFailure1.txt](https://github.com/Microsoft/vsts-tasks/files/2370433/Vsts_AzcopyTaskFailure1.txt)

**Comment by dejangeci** [comment]
Had a similar issue - the problem was that both Azure and AzureRM modules were installed.
The solution was to uninstall everything, and then install only AzureRM.

```powershell
foreach ($module in (Get-Module -ListAvailable Az*).Name | Get-Unique) {
    Write-Host "Removing Module $module"
    Uninstall-module $module
}

Install-Module AzureRM
```
