### ISSUE TITLE
Unable to process command '##vso[telemetry.publish on downloading artifacts task in release

### ISSUE THREAD

**Issue by domisginger** [Microsoft/vsts-tasks#7547]
## Environment
VSTS
account PHNT
project SeeEHR
release API-Reactionem

Built with hosted 2017 but release is failing on Default hosted (windows), was working up to yesterday lunchtime (GMT) with no changes. Agent is online. Any help greatly appreciated.

### Error logs
```
Unable to process command '##vso[telemetry.publish area=artifact-engine;feature=performance]{"hostType":"release","definitionName":"[NonEmail:API-Reactionem]","processId":"1353","processUrl":"https://phnt.visualstudio.com/db0b9959-b2e3-4588-96c0-6cf88ff4ac9a/_release?releaseId=1353&_a=release-summary","taskDisplayName":"Download artifact - ReactionemApi","jobid":"dbc15921-2735-48b0-a7ca-ae20b92bdfe9","agentVersion":"2.123.0","agentOS":"Windows_NT","agentName":"PICTS346AzureAgent2","version":"0.1.23","location":"https://phnt.visualstudio.com//_apis/resources/Containers/2430203?itemPath=drop-train&isShallow=true&api-version=4.1-preview.4","total":67,"files":55,"processed":55,"skipped":0,"failed":0,"downloadTimeInSeconds":7.161,"downloadSizeInBytes":3088681,"fileSizeInBytes":9560721}' successfully. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)
An error occurred while sending the request.
```

**Comment by domisginger** [comment]
Better stacktrace

```
2018-06-22T09:51:57.0329552Z ##[error]Unable to process command '##vso[telemetry.publish area=artifact-engine;feature=performance]{"hostType":"release","definitionName":"[NonEmail:API-Reactionem]","processId":"1357","processUrl":"https://phnt.visualstudio.com/db0b9959-b2e3-4588-96c0-6cf88ff4ac9a/_release?releaseId=1357&_a=release-summary","taskDisplayName":"Download artifact - ReactionemApi","jobid":"48adbce0-145d-46be-ba94-36f9ebe7602d","agentVersion":"2.123.0","agentOS":"Windows_NT","agentName":"PICTS346AzureAgent3","version":"0.1.23","location":"https://phnt.visualstudio.com//_apis/resources/Containers/2432122?itemPath=drop-debug&isShallow=true&api-version=4.1-preview.4","total":67,"files":55,"processed":55,"skipped":0,"failed":0,"downloadTimeInSeconds":28.077,"downloadSizeInBytes":3088711,"fileSizeInBytes":9560782}' successfully. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)
2018-06-22T09:51:57.0339554Z ##[error]An error occurred while sending the request.
2018-06-22T09:51:57.0479582Z ##[debug]System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The operation timed out
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.<SendAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__46`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.<GetConnectionDataAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.<ConnectAsync>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.<EnsureConnectedAsync>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.<CheckForServerUpdatesAsync>d__38.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.<FindServiceDefinitionsAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.<GetResourceLocationsAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssConnection.<GetClientInstanceAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssConnection.<GetClientServiceImplAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssConnection.<GetClientAsync>d__12`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.TaskExtensions.SyncResult[T](Task`1 task)
   at Microsoft.VisualStudio.Services.WebApi.VssConnection.GetClient[T]()
   at Microsoft.VisualStudio.Services.Agent.Worker.Telemetry.CustomerIntelligenceServer.Initialize(VssConnection connection)
   at Microsoft.VisualStudio.Services.Agent.Worker.Telemetry.TelemetryCommandExtension.ProcessPublishTelemetryCommand(IExecutionContext context, Dictionary`2 eventProperties, String data)
   at Microsoft.VisualStudio.Services.Agent.Worker.WorkerCommandManager.TryProcessCommand(IExecutionContext context, String input)
```

**Comment by GitHubSriramB** [comment]
@domisginger - is this issue still happening?

**Comment by GitHubSriramB** [comment]
@domisginger - From latest release logs for API-Reactionem release definition, I see that this error is not happening. Could you pl. confirm?

However download of artifacts failing is intermittently failing due to ETIMEDOUT. This is because of a bug in retry logic we have. Essentially the query to get build failed with ETIMEDOUT and subsequent calls are failing with the same error:

2018-06-25T13:38:38.9377499Z ##[debug]buildId=4072
2018-06-25T13:38:59.1497993Z Error : in getBuild, so retrying => retries pending  : 4
2018-06-25T13:39:03.1834272Z Error : in getBuild, so retrying => retries pending  : 3
2018-06-25T13:39:07.1928071Z Error : in getBuild, so retrying => retries pending  : 2
2018-06-25T13:39:11.2021870Z Error : in getBuild, so retrying => retries pending  : 1
2018-06-25T13:39:15.2115669Z ##[error]Failed in getBuild with error: Error: connect ETIMEDOUT 13.107.6.175:443
...

We are in the process of hotfixing it.

**Comment by domisginger** [comment]
@GitHubSriramB  Thanks for your response. Yes our error did change as you described. Could you let me know when the hotfix goes out we've had to revert to manual release processes at the worst possible time?

**Comment by GitHubSriramB** [comment]
@domisginger - hotfix for the task is complete on your account

**Comment by domisginger** [comment]
@GitHubSriramB  Super, just checked and were up and running again. Thank you for your help.
