### ISSUE TITLE
password contains "(" and VSTS task "Power Shell on Target Machine" version 3.* is failing with error parsing '********' - Not enough )'s. 

### ISSUE THREAD

**Issue by vishwa90** [Microsoft/vsts-tasks#7552]
## Environment
- Server - VSTS on-premises   
    
    - If using VSTS, provide the account name, team project name, build definition name/build number: 

- Agent - Private: 
    

    - If using private agent, provide the OS of the machine running the agent and the agent version: Windows Server 2012

### Error logs

[Insert error from the logs here]

2018-06-22T20:59:01.2123397Z ##[debug]Evaluating condition for step: 'Enable Monitoring on QA1'
2018-06-22T20:59:01.2124548Z ##[debug]Evaluating: succeeded()
2018-06-22T20:59:01.2125022Z ##[debug]Evaluating succeeded:
2018-06-22T20:59:01.2125963Z ##[debug]=> (Boolean) True
2018-06-22T20:59:01.2126734Z ##[debug]Expanded: True
2018-06-22T20:59:01.2127426Z ##[debug]Result: True
2018-06-22T20:59:01.2128193Z ##[section]Starting: Enable Monitoring on QA1
2018-06-22T20:59:01.2137193Z ==============================================================================
2018-06-22T20:59:01.2137642Z Task         : PowerShell on Target Machines
2018-06-22T20:59:01.2138042Z Description  : Execute PowerShell scripts on remote machine(s) using Invoke-Command cmdlet
2018-06-22T20:59:01.2138422Z Version      : 3.0.0
2018-06-22T20:59:01.2138747Z Author       : Microsoft Corporation
2018-06-22T20:59:01.2139139Z Help         : [More Information](https://go.microsoft.com/fwlink/?linkid=873465)
2018-06-22T20:59:01.2139561Z ==============================================================================
2018-06-22T20:59:02.7578798Z ##[debug]VstsTaskSdk 0.10.0 commit 787a46ec0a2df5b4d12c2e801bd3f319975c054c
2018-06-22T20:59:03.0206730Z ##[debug]Entering E:\VSTS\_work\_tasks\PowerShellOnTargetMachines_3b5693d4-5777-4fee-862a-bd2b7a374c68\3.0.0\PowerShellOnTargetMachines.ps1.
2018-06-22T20:59:03.0367789Z VERBOSE: Loading resource strings from: 
2018-06-22T20:59:03.0372474Z VERBOSE: E:\VSTS\_work\_tasks\PowerShellOnTargetMachines_3b5693d4-5777-4fee-862a-bd2b7a374c68\3.0.0\task.json
2018-06-22T20:59:03.0555665Z VERBOSE: Loaded 6 strings.
2018-06-22T20:59:03.0600131Z VERBOSE: SYSTEM_CULTURE: 'en-US'
2018-06-22T20:59:03.0663110Z VERBOSE: Loading resource strings from: 
2018-06-22T20:59:03.0665056Z E:\VSTS\_work\_tasks\PowerShellOnTargetMachines_3b5693d4-5777-4fee-862a-bd2b7a374c68\3.0
2018-06-22T20:59:03.0671300Z VERBOSE: .0\Strings\resources.resjson\en-US\resources.resjson
2018-06-22T20:59:03.0888232Z VERBOSE: Loaded 6 strings.
2018-06-22T20:59:03.0953105Z VERBOSE: Loading module from path 
2018-06-22T20:59:03.0954191Z 'E:\VSTS\_work\_tasks\PowerShellOnTargetMachines_3b5693d4-5777-4fee-862a-bd2b7a374c68\3.0.0\ps
2018-06-22T20:59:03.0960820Z VERBOSE: _modules\RemoteDeployer\RemoteDeployer.psm1'.
2018-06-22T20:59:03.3144716Z VERBOSE: Loading resource strings from: 
2018-06-22T20:59:03.3145600Z E:\VSTS\_work\_tasks\PowerShellOnTargetMachines_3b5693d4-5777-4fee-862a-bd2b7a374c68\3.0
2018-06-22T20:59:03.3152071Z VERBOSE: .0\ps_modules\RemoteDeployer\module.json
2018-06-22T20:59:03.3396400Z VERBOSE: Loaded 10 strings.
2018-06-22T20:59:03.3423217Z VERBOSE: SYSTEM_CULTURE: 'en-US'
2018-06-22T20:59:03.3492849Z VERBOSE: Loading resource strings from: 
2018-06-22T20:59:03.3495286Z E:\VSTS\_work\_tasks\PowerShellOnTargetMachines_3b5693d4-5777-4fee-862a-bd2b7a374c68\3.0
2018-06-22T20:59:03.3500879Z VERBOSE: .0\ps_modules\RemoteDeployer\Strings\resources.resjson\en-US\resources.resjson
2018-06-22T20:59:03.3735334Z VERBOSE: Loaded 10 strings.
2018-06-22T20:59:03.3748417Z VERBOSE: Exporting function 'Invoke-RemoteScript'.
2018-06-22T20:59:03.3760030Z VERBOSE: Importing function 'Invoke-RemoteScript'.
2018-06-22T20:59:03.4492030Z VERBOSE: INPUT_MACHINES: 'FAAMESA001.ame.fantasia.qa:5985'
2018-06-22T20:59:03.4514367Z VERBOSE: INPUT_AUTHENTICATIONMECHANISM: 'Default'
2018-06-22T20:59:03.4564346Z VERBOSE: INPUT_USERNAME: '********'
2018-06-22T20:59:03.4607007Z VERBOSE: INPUT_USERPASSWORD: '********'
2018-06-22T20:59:03.4714475Z VERBOSE: Entering Get-TargetMachineCredential.
2018-06-22T20:59:03.4838539Z VERBOSE:  userName: '********'
2018-06-22T20:59:03.5087551Z ##[error]Unable to process command '##vso[task.setsecret]********' successfully. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)
2018-06-22T20:59:03.5119097Z ##[error]parsing '********' - Not enough )'s.
2018-06-22T20:59:03.5392184Z ##[debug]System.ArgumentException: parsing '********' - Not enough )'s.
   at System.Text.RegularExpressions.RegexParser.ScanRegex()
   at System.Text.RegularExpressions.RegexParser.Parse(String re, RegexOptions op)
   at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options, TimeSpan matchTimeout, Boolean useCache)
   at System.Text.RegularExpressions.Regex..ctor(String pattern)
   at Microsoft.VisualStudio.Services.Agent.SecretMasker.AddRegex(String expression)
   at Microsoft.VisualStudio.Services.Agent.Worker.WorkerCommandManager.TryProcessCommand(IExecutionContext context, String input)
2018-06-22T20:59:03.5397398Z ##[debug]Processed: ##vso[task.setsecret]********
2018-06-22T20:59:03.6524500Z VERBOSE: Leaving Get-TargetMachineCredential.
2018-06-22T20:59:03.6546792Z VERBOSE: INPUT_COMMUNICATIONPROTOCOL: 'Http'
2018-06-22T20:59:03.6573250Z VERBOSE: INPUT_NEWPSSESSIONOPTIONARGUMENTS: '-SkipCACheck -IdleTimeout 7200000 -OperationTimeout 0 -OutputBufferingMode
2018-06-22T20:59:03.6575365Z  Block'
2018-06-22T20:59:03.6597193Z VERBOSE: INPUT_RUNPOWERSHELLINPARALLEL: 'true'
2018-06-22T20:59:03.6619575Z VERBOSE:  Converted to bool: True
2018-06-22T20:59:03.6675630Z VERBOSE: Entering Parse-TargetMachineNames.
2018-06-22T20:59:03.6688233Z VERBOSE:  machineNames: 'FAAMESA001.ame.fantasia.qa:5985'
2018-06-22T20:59:03.6790663Z VERBOSE: TargetMachineName: 'faamesa001.ame.fantasia.qa:5985'
2018-06-22T20:59:03.6828932Z VERBOSE: Leaving Parse-TargetMachineNames.
2018-06-22T20:59:03.6860193Z VERBOSE: Entering Get-NewPSSessionOption.
2018-06-22T20:59:03.6877479Z VERBOSE:  arguments: '-SkipCACheck -IdleTimeout 7200000 -OperationTimeout 0 -OutputBufferingMode Block'
2018-06-22T20:59:03.6897831Z VERBOSE: New-PSSessionOption command: New-PSSessionOption -SkipCACheck -IdleTimeout 7200000 -OperationTimeout 0 
2018-06-22T20:59:03.6990476Z VERBOSE: -OutputBufferingMode Block
2018-06-22T20:59:03.7068496Z VERBOSE: Leaving Get-NewPSSessionOption.
2018-06-22T20:59:03.7095455Z VERBOSE: Entering Get-RemoteScriptJobArguments.
2018-06-22T20:59:03.7120796Z VERBOSE: INPUT_SCRIPTTYPE: 'Inline'
2018-06-22T20:59:03.7149452Z VERBOSE: INPUT_INLINESCRIPT: 'E:\IBM\EnableMonitoring.bat Clients CSFV1Application'
2018-06-22T20:59:03.7181106Z VERBOSE: INPUT_ERRORACTIONPREFERENCE: 'stop'
2018-06-22T20:59:03.7195204Z VERBOSE: INPUT_FAILONSTDERR: 'false'
2018-06-22T20:59:03.7220424Z VERBOSE:  Converted to bool: False
2018-06-22T20:59:03.7233405Z VERBOSE: INPUT_IGNORELASTEXITCODE: 'false'
2018-06-22T20:59:03.7259062Z VERBOSE:  Converted to bool: False
2018-06-22T20:59:03.7323196Z VERBOSE: INPUT_WORKINGDIRECTORY (empty)
2018-06-22T20:59:03.7473394Z VERBOSE: Leaving Get-RemoteScriptJobArguments.
2018-06-22T20:59:03.7953959Z VERBOSE: Entering Invoke-RemoteScript.
2018-06-22T20:59:03.8440180Z VERBOSE:  targetMachineNames: 'faamesa001.ame.fantasia.qa:5985'
2018-06-22T20:59:03.8446619Z VERBOSE: Entering Get-TargetMachines.
2018-06-22T20:59:03.8447390Z VERBOSE: Target Machines: faamesa001.ame.fantasia.qa:5985
2018-06-22T20:59:03.8726766Z VERBOSE: ComputerName = faamesa001.ame.fantasia.qa
2018-06-22T20:59:03.8733966Z VERBOSE: WSManPort = 5985
2018-06-22T20:59:03.8734556Z VERBOSE: Authentication = Default
2018-06-22T20:59:03.8735064Z VERBOSE: SessionConfigurationName = microsoft.powershell
2018-06-22T20:59:03.8735577Z VERBOSE: UseSSL = False
2018-06-22T20:59:03.8747598Z VERBOSE: Total target machines are: 1
2018-06-22T20:59:03.8761010Z VERBOSE: Leaving Get-TargetMachines.
2018-06-22T20:59:03.8999951Z VERBOSE: Entering Get-WinRmConnectionToTargetMachine.
2018-06-22T20:59:03.9010508Z VERBOSE:  computerName: 'faamesa001.ame.fantasia.qa'
2018-06-22T20:59:03.9022389Z VERBOSE:  port: '5985'
2018-06-22T20:59:03.9074484Z VERBOSE:  credential: 'System.Management.Automation.PSCredential'
2018-06-22T20:59:03.9086930Z VERBOSE:  authentication: 'Default'
2018-06-22T20:59:03.9096698Z VERBOSE:  sessionName: 'b021b0ce-6492-46e8-a78a-068ca562c360'
2018-06-22T20:59:03.9108690Z VERBOSE:  sessionConfigurationName: 'microsoft.powershell'
2018-06-22T20:59:03.9122627Z VERBOSE:  useSsl: 'False'
2018-06-22T20:59:03.9264923Z VERBOSE: Entering Get-NewPSSessionCommand.
2018-06-22T20:59:03.9276016Z VERBOSE:  computerName: 'faamesa001.ame.fantasia.qa'
2018-06-22T20:59:03.9287045Z VERBOSE:  port: '5985'
2018-06-22T20:59:03.9298816Z VERBOSE:  authentication: 'Default'
2018-06-22T20:59:03.9313532Z VERBOSE:  sessionName: 'b021b0ce-6492-46e8-a78a-068ca562c360'
2018-06-22T20:59:03.9358906Z VERBOSE:  useSsl: 'False'
2018-06-22T20:59:03.9485919Z VERBOSE:  sessionConfigurationName: 'microsoft.powershell'
2018-06-22T20:59:03.9578000Z VERBOSE:  NoCredential: 'False'
2018-06-22T20:59:03.9579310Z VERBOSE: New-PSSessionCommand: New-PSSession -ComputerName 'faamesa001.ame.fantasia.qa' -Port 5985 -Authentication 
2018-06-22T20:59:03.9579921Z Default 
2018-06-22T20:59:03.9580479Z VERBOSE: -Name 'b021b0ce-6492-46e8-a78a-068ca562c360' -Credential $credential -ErrorAction 'SilentlyContinue' 
2018-06-22T20:59:03.9581035Z -ErrorVariable 
2018-06-22T20:59:03.9581581Z VERBOSE: sessionErrors -ConfigurationName 'microsoft.powershell'
2018-06-22T20:59:03.9582106Z VERBOSE: Leaving Get-NewPSSessionCommand.
2018-06-22T20:59:03.9582661Z VERBOSE: Trying to establish connection: Attempt #1
2018-06-22T20:59:06.5705086Z VERBOSE: Connection established to computer:'faamesa001.ame.fantasia.qa' port:'5985'
2018-06-22T20:59:06.5715029Z PSSession created for Machines:'faamesa001.ame.fantasia.qa'
2018-06-22T20:59:06.5750150Z VERBOSE: Leaving Get-WinRmConnectionToTargetMachine.
2018-06-22T20:59:06.5856797Z VERBOSE: Entering Get-TemporaryLogsFolder.
2018-06-22T20:59:06.5917899Z VERBOSE: AGENT_TEMPDIRECTORY: 'E:\VSTS\_work\_temp'
2018-06-22T20:59:06.6025451Z VERBOSE: Created temporary logs folder: E:\VSTS\_work\_temp\e908da80-8a4f-4b83-a17b-af05959e53f7
2018-06-22T20:59:06.6039873Z VERBOSE: Leaving Get-TemporaryLogsFolder.
2018-06-22T20:59:06.6102634Z VERBOSE: Entering Run-RemoteScriptJobs.
2018-06-22T20:59:06.6144657Z VERBOSE: Entering Get-ScriptArguments.
2018-06-22T20:59:06.6580882Z VERBOSE: Leaving Get-ScriptArguments.
2018-06-22T20:59:06.6708567Z VERBOSE: SYSTEM_JOBID: 'b7947c0d-6d87-40f9-9906-a23d202d6fa8'
2018-06-22T20:59:06.7299982Z VERBOSE: Entering Get-JobResults.
2018-06-22T20:59:06.8928262Z VERBOSE: Exporting function 'New-PSWorkflowSession'.
2018-06-22T20:59:06.8935930Z VERBOSE: Exporting alias 'nwsn'.
2018-06-22T20:59:07.0278491Z VERBOSE: JobId: '2', JobState: 'running', ComputerName: 'faamesa001.ame.fantasia.qa'
2018-06-22T20:59:07.0286278Z ================================================ faamesa001.ame.fantasia.qa ================================================
2018-06-22T20:59:37.0619967Z VERBOSE: JobId: '2', JobState: 'completed', ComputerName: 'faamesa001.ame.fantasia.qa'
2018-06-22T20:59:37.0627608Z ================================================ faamesa001.ame.fantasia.qa ================================================
2018-06-22T20:59:37.0636955Z ##[command]& 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe' -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'C:\Users\dtt_sc_soaiibqa\AppData\Local\Temp\91ed9acf-1a8b-42b6-a82a-916e7e5a2c68.ps1'"
2018-06-22T20:59:37.0758028Z 
2018-06-22T20:59:37.0760434Z 
2018-06-22T20:59:37.0934604Z C:\Users\dtt_sc_soaiibqa\Documents>SET arg1=Clients 
2018-06-22T20:59:37.0936856Z 
2018-06-22T20:59:37.0970474Z 
2018-06-22T20:59:37.0973654Z 
2018-06-22T20:59:37.1007731Z C:\Users\dtt_sc_soaiibqa\Documents>SET arg2=CSFV1Application 
2018-06-22T20:59:37.1009003Z 
2018-06-22T20:59:37.1042910Z 
2018-06-22T20:59:37.1044173Z 
2018-06-22T20:59:37.1078387Z C:\Users\dtt_sc_soaiibqa\Documents>SET mqsi=E:\IBM\IIB\server 
2018-06-22T20:59:37.1080680Z 
2018-06-22T20:59:37.1112702Z 
2018-06-22T20:59:37.1114419Z 
2018-06-22T20:59:37.1146447Z C:\Users\dtt_sc_soaiibqa\Documents>call "E:\IBM\IIB\server\bin\mqsiprofile.cmd" 
2018-06-22T20:59:37.1148955Z 
2018-06-22T20:59:37.1179188Z *** Adding directory with log4j2.xml to Classpath ***
2018-06-22T20:59:37.1180639Z 
2018-06-22T20:59:37.1212886Z 
2018-06-22T20:59:37.1214748Z 
2018-06-22T20:59:37.1248020Z MQSI 10.0.0.11
2018-06-22T20:59:37.1249140Z 
2018-06-22T20:59:37.1278943Z E:\IBM\IIB\server
2018-06-22T20:59:37.1280101Z 
2018-06-22T20:59:37.1317696Z 
2018-06-22T20:59:37.1319114Z 
2018-06-22T20:59:37.1350626Z "Enabling Monitoring for EG : Clients And Application: CSFV1Application"
2018-06-22T20:59:37.1351587Z 
2018-06-22T20:59:37.1385626Z BIP8071I: Successful command completion. 
2018-06-22T20:59:37.1386798Z 
2018-06-22T20:59:37.1424379Z ##[debug][FAAMESA001]LASTEXITCODE is 0
2018-06-22T20:59:37.1425510Z 
2018-06-22T20:59:37.1628503Z VERBOSE: Leaving Get-JobResults.
2018-06-22T20:59:37.1665707Z VERBOSE: Leaving Run-RemoteScriptJobs.
2018-06-22T20:59:37.1769242Z VERBOSE: Entering Publish-Telemetry.
2018-06-22T20:59:37.1913992Z VERBOSE: SYSTEM_JOBID: 'b7947c0d-6d87-40f9-9906-a23d202d6fa8'
2018-06-22T20:59:37.2139884Z VERBOSE: Telemetry Data is: {    "TelemetryError":  "",    "JobId":  "b7947c0d-6d87-40f9-9906-a23d202d6fa8",    
2018-06-22T20:59:37.2141011Z "IsAzureVm":  
2018-06-22T20:59:37.2145161Z VERBOSE: false,    "VmUuidHash":  
2018-06-22T20:59:37.2146382Z "A29E71D140C2ECC3AA623C8D6D4BFB5C75094C89452B50D641956120EEC782B2770AAEEA24332390FFC37F439327B
2018-06-22T20:59:37.2152342Z VERBOSE: B94712F36DCE94F385B64AF7C47AE69E6F6"}
2018-06-22T20:59:41.3638203Z ##[debug]Processed: ##vso[telemetry.publish area=TaskHub;feature=PowerShellOnTargetMachines]{    "TelemetryError":  "",    "JobId":  "b7947c0d-6d87-40f9-9906-a23d202d6fa8",    "IsAzureVm":  false,    "VmUuidHash":  "A29E71D140C2ECC3AA623C8D6D4BFB5C75094C89452B50D641956120EEC782B2770AAEEA24332390FFC37F439327BB94712F36DCE94F385B64AF7C47AE69E6F6"}
2018-06-22T20:59:41.3639589Z VERBOSE: Leaving Publish-Telemetry.
2018-06-22T20:59:41.3639983Z VERBOSE: Entering Upload-TargetMachineLogs.
2018-06-22T20:59:41.3640377Z VERBOSE:  logsFolder: 'E:\VSTS\_work\_temp\e908da80-8a4f-4b83-a17b-af05959e53f7'
2018-06-22T20:59:41.3671965Z ##[debug]Processed: ##vso[task.uploadfile]E:\VSTS\_work\_temp\e908da80-8a4f-4b83-a17b-af05959e53f7\faamesa001.ame.fantasia.qa.log
2018-06-22T20:59:41.3672505Z VERBOSE: Leaving Upload-TargetMachineLogs.
2018-06-22T20:59:41.3672861Z VERBOSE: Entering Set-TaskResult.
2018-06-22T20:59:41.3673244Z VERBOSE: Remote script execution completed for machine: FAAMESA001
2018-06-22T20:59:41.3673628Z Script execution succeeded for ComputerName: 'FAAMESA001'
2018-06-22T20:59:41.3675242Z ##[debug]Processed: ##vso[task.complete result=Succeeded]
2018-06-22T20:59:41.3675641Z VERBOSE: Leaving Set-TaskResult.
2018-06-22T20:59:41.3675954Z VERBOSE: Job results are: 
2018-06-22T20:59:41.3676257Z VERBOSE: 
2018-06-22T20:59:41.3676666Z VERBOSE: Name                           Value                                                                          
2018-06-22T20:59:41.3677047Z          
2018-06-22T20:59:41.3677448Z VERBOSE: ----                           -----                                                                          
2018-06-22T20:59:41.3677863Z          
2018-06-22T20:59:41.3678251Z VERBOSE: Message                        PS_TM_ExitCode                                                                 
2018-06-22T20:59:41.3678658Z          
2018-06-22T20:59:41.3678978Z VERBOSE: MachineGuidHash                
2018-06-22T20:59:41.3679364Z A29E71D140C2ECC3AA623C8D6D4BFB5C75094C89452B50D641956120EEC782B2770AAEEA24332390FFC37...
2018-06-22T20:59:41.3679844Z VERBOSE: ComputerName                   FAAMESA001                                                                     
2018-06-22T20:59:41.3680237Z          
2018-06-22T20:59:41.3680622Z VERBOSE: ExitCode                       0                                                                              
2018-06-22T20:59:41.3681011Z          
2018-06-22T20:59:41.3681397Z VERBOSE: Status                         Passed                                                                         
2018-06-22T20:59:41.3681797Z          
2018-06-22T20:59:41.3682807Z VERBOSE: IsAzureVM                      False                                                                          
2018-06-22T20:59:41.3683196Z          
2018-06-22T20:59:41.3685095Z VERBOSE: TelemetryError                                                                                                
2018-06-22T20:59:41.3685572Z          
2018-06-22T20:59:41.3685838Z VERBOSE: 
2018-06-22T20:59:41.3686122Z VERBOSE: 
2018-06-22T20:59:41.3686404Z VERBOSE: 
2018-06-22T20:59:41.3686733Z VERBOSE: Entering Disconnect-WinRmConnectionToTargetMachines.
2018-06-22T20:59:41.3687109Z VERBOSE: Entering Get-RemoteConnection.
2018-06-22T20:59:41.3687444Z VERBOSE: Leaving Get-RemoteConnection.
2018-06-22T20:59:41.3687869Z VERBOSE: Trying to disconnect pssession with name: b021b0ce-6492-46e8-a78a-068ca562c360, computerName: 
2018-06-22T20:59:41.3688289Z VERBOSE: faamesa001.ame.fantasia.qa
2018-06-22T20:59:41.3688686Z VERBOSE: Successfully disconnected session: b021b0ce-6492-46e8-a78a-068ca562c360 on computer: 
2018-06-22T20:59:41.3689106Z faamesa001.ame.fantasia.qa
2018-06-22T20:59:41.3689473Z VERBOSE: Leaving Disconnect-WinRmConnectionToTargetMachines.
2018-06-22T20:59:41.3690102Z VERBOSE: Leaving Invoke-RemoteScript.
2018-06-22T20:59:41.3690783Z VERBOSE: Leaving 
2018-06-22T20:59:41.3691222Z E:\VSTS\_work\_tasks\PowerShellOnTargetMachines_3b5693d4-5777-4fee-862a-bd2b7a374c68\3.0.0\PowerShellOnTargetMa
2018-06-22T20:59:41.3691616Z VERBOSE: chines.ps1.
2018-06-22T20:59:41.3695230Z ##[section]Finishing: Enable Monitoring on QA1

**Comment by niadak** [comment]
@vishwa90 , Can you try version 2.* of the task and check if it is working fine?

**Comment by SumiranAgg** [comment]
@vishwa90 Are you still blocked? Did you try version 2.*?

**Comment by SumiranAgg** [comment]
@vishwa90 I hope you are unblocked for now. We will fix the issue in version 3.* in next deployment.

**Comment by vishwa90** [comment]
@arjgupta we are not using a hosted agent, We have our own agent running on a windows machine (os is windows server 2012 R2). Yes you are right, the scripts are executed even when we see this error. how can i find out the agent version?
Right now since V2 is working fine, we will proceed with it.

**Comment by arjgupta** [comment]
@vishwa90  navigate to the agent queues page. select the agent that you are running and look under the capabilities tab. There should be a key named 'Agent.Version'. The corresponding value is the agent version.

**Comment by SumiranAgg** [comment]
Closing since no further customer communication. Please feel to reopen if required.

**Comment by rhyswynn** [comment]
Am I able to reopen this issue?  I am experiencing the same thing and I cannot use V2 because V2 does not include the inline script option.

If V3 will be fixed, do you have an ETA when that will happen?  

Thank you!
