### ISSUE TITLE
Service Fabric Diff Package creation failing

### ISSUE THREAD

**Issue by Tadimsky** [Microsoft/vsts-tasks#7648]
I'm getting a failure in the `Service Fabric Application Deployment` task when trying to create a Diff package.
This is on VSTS:

```
2018-07-06T21:27:21.9771247Z ##[debug]Evaluating condition for step: 'Deploy Service Fabric Application'
2018-07-06T21:27:21.9772028Z ##[debug]Evaluating: succeeded()
2018-07-06T21:27:21.9772395Z ##[debug]Evaluating succeeded:
2018-07-06T21:27:21.9772841Z ##[debug]=> True
2018-07-06T21:27:21.9773926Z ##[debug]Result: True
2018-07-06T21:27:21.9774357Z ##[section]Starting: Deploy Service Fabric Application
2018-07-06T21:27:21.9780169Z ==============================================================================
2018-07-06T21:27:21.9780610Z Task         : Service Fabric Application Deployment
2018-07-06T21:27:21.9780855Z Description  : Deploy a Service Fabric application to a cluster.
2018-07-06T21:27:21.9781086Z Version      : 1.7.13
2018-07-06T21:27:21.9781282Z Author       : Microsoft Corporation
2018-07-06T21:27:21.9781541Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=820528)
2018-07-06T21:27:21.9781809Z ==============================================================================
2018-07-06T21:27:24.0841355Z ##[debug]VstsTaskSdk 0.8.2 commit 
2018-07-06T21:27:25.0174274Z ##[debug]Entering D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.13\deploy.ps1.
2018-07-06T21:27:25.2114227Z ##[debug]Loading resource strings from: D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.13\task.json
2018-07-06T21:27:25.3101874Z ##[debug]Loaded 57 strings.
2018-07-06T21:27:25.3168948Z ##[debug]SYSTEM_CULTURE: 'en-US'
2018-07-06T21:27:25.3178651Z ##[debug]Loading resource strings from: D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.13\Strings\resources.resjson\en-US\resources.resjson
2018-07-06T21:27:25.4459586Z ##[debug]Loaded 57 strings.
2018-07-06T21:27:25.4518550Z ##[debug]Loading module from path 'D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.13\ps_modules\ServiceFabricHelpers\ServiceFabricHelpers.psm1'.
2018-07-06T21:27:25.4570306Z ##[debug]Loading resource strings from: D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.13\ps_modules\ServiceFabricHelpers\module.json
2018-07-06T21:27:25.4840957Z ##[debug]Loaded 11 strings.
2018-07-06T21:27:25.4871373Z ##[debug]SYSTEM_CULTURE: 'en-US'
2018-07-06T21:27:25.4895429Z ##[debug]Loading resource strings from: D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.13\ps_modules\ServiceFabricHelpers\Strings\resources.resjson\en-US\resources.resjson
2018-07-06T21:27:25.5157511Z ##[debug]Loaded 11 strings.
2018-07-06T21:27:25.5376252Z ##[debug]Entering Find-VstsFiles.
2018-07-06T21:27:25.5476251Z ##[debug] LiteralDirectory: 'D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.13\ps_modules\ServiceFabricHelpers'
2018-07-06T21:27:25.5496334Z ##[debug] LegacyPattern: '*.ps1'
2018-07-06T21:27:25.6578559Z ##[debug]Entering Get-MatchingItems.
2018-07-06T21:27:25.6614209Z ##[debug] IncludePatterns: 'D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.13\ps_modules\ServiceFabricHelpers\*.ps1'
2018-07-06T21:27:25.6676911Z ##[debug] ExcludePatterns: ''
2018-07-06T21:27:25.6722423Z ##[debug] IncludeFiles: 'True'
2018-07-06T21:27:25.6742656Z ##[debug] IncludeDirectories: 'False'
2018-07-06T21:27:25.6762582Z ##[debug] Force: 'False'
2018-07-06T21:27:26.2131040Z ##[debug]Paths: D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.13\ps_modules\ServiceFabricHelpers\
2018-07-06T21:27:26.2205180Z ##[debug] Connect-ServiceFabricClusterFromServiceEndpoint.ps1
2018-07-06T21:27:26.2264851Z ##[debug] Get-ServiceFabricEncryptedText.ps1
2018-07-06T21:27:26.2265231Z ##[debug] SFOperations.ps1
2018-07-06T21:27:26.2265564Z ##[debug]Leaving Get-MatchingItems.
2018-07-06T21:27:26.2392073Z ##[debug]Total found: 3
2018-07-06T21:27:26.2417549Z ##[debug]Leaving Find-VstsFiles.
2018-07-06T21:27:26.2442370Z ##[debug]Exporting function 'Connect-ServiceFabricClusterFromServiceEndpoint'.
2018-07-06T21:27:26.2463970Z ##[debug]Exporting function 'Get-ServiceFabricEncryptedText'.
2018-07-06T21:27:26.3080286Z ##[debug]Exporting variable 'SF_Operations'.
2018-07-06T21:27:26.5976736Z ##[debug]Importing function 'Connect-ServiceFabricClusterFromServiceEndpoint'.
2018-07-06T21:27:26.6120323Z ##[debug]Importing function 'Get-ServiceFabricEncryptedText'.
2018-07-06T21:27:26.6121197Z ##[debug]Importing variable 'SF_Operations'.
2018-07-06T21:27:26.6121948Z ##[debug]Loading module from path 'D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.13\ps_modules\PowershellHelpers\PowershellHelpers.psm1'.
2018-07-06T21:27:26.6123377Z ##[debug]Loading resource strings from: D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.13\ps_modules\PowershellHelpers\module.json
2018-07-06T21:27:26.6146572Z ##[debug]Loaded 2 strings.
2018-07-06T21:27:26.6189534Z ##[debug]SYSTEM_CULTURE: 'en-US'
2018-07-06T21:27:26.6210602Z ##[debug]Loading resource strings from: D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.13\ps_modules\PowershellHelpers\Strings\resources.resjson\en-US\resources.resjson
2018-07-06T21:27:26.6322945Z ##[debug]Loaded 2 strings.
2018-07-06T21:27:26.6338428Z ##[debug]Exporting function 'Invoke-ActionWithRetries'.
2018-07-06T21:27:26.6355111Z ##[debug]Exporting function 'Get-TempDirectoryPath'.
2018-07-06T21:27:26.6369750Z ##[debug]Importing function 'Get-TempDirectoryPath'.
2018-07-06T21:27:26.6390946Z ##[debug]Importing function 'Invoke-ActionWithRetries'.
2018-07-06T21:27:26.6398438Z ##[debug]Loading module from path 'D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.13\ps_modules\TelemetryHelper\TelemetryHelper.psm1'.
2018-07-06T21:27:26.6441170Z ##[debug]Exporting function 'Write-Telemetry'.
2018-07-06T21:27:26.6461916Z ##[debug]Exporting function 'Get-ExceptionData'.
2018-07-06T21:27:26.6479443Z ##[debug]Exporting variable 'telemetryCodes'.
2018-07-06T21:27:26.6496503Z ##[debug]Importing function 'Get-ExceptionData'.
2018-07-06T21:27:26.6512520Z ##[debug]Importing function 'Write-Telemetry'.
2018-07-06T21:27:26.6528787Z ##[debug]Importing variable 'telemetryCodes'.
2018-07-06T21:27:26.6763908Z ##[debug]INPUT_PUBLISHPROFILEPATH: 'D:\a\r1\a\**\projectartifacts\**\PublishProfiles\Int.xml'
2018-07-06T21:27:26.6835346Z Searching for path: D:\a\r1\a\**\projectartifacts\**\PublishProfiles\Int.xml
2018-07-06T21:27:26.6856167Z ##[debug]Entering Find-VstsFiles.
2018-07-06T21:27:26.6873079Z ##[debug] LegacyPattern: 'D:\a\r1\a\**\projectartifacts\**\PublishProfiles\Int.xml'
2018-07-06T21:27:26.6900086Z ##[debug]Entering Get-MatchingItems.
2018-07-06T21:27:26.6920357Z ##[debug] IncludePatterns: 'D:\a\r1\a\**\projectartifacts\**\PublishProfiles\Int.xml'
2018-07-06T21:27:26.6949021Z ##[debug] ExcludePatterns: ''
2018-07-06T21:27:26.6975614Z ##[debug] IncludeFiles: 'True'
2018-07-06T21:27:26.6995490Z ##[debug] IncludeDirectories: 'False'
2018-07-06T21:27:26.7013938Z ##[debug] Force: 'False'
2018-07-06T21:27:27.1224336Z ##[debug]Path: D:\a\r1\a\intentional-services CI\projectartifacts\IntentionalServices\PublishProfiles\Int.xml
2018-07-06T21:27:27.1225728Z ##[debug]Leaving Get-MatchingItems.
2018-07-06T21:27:27.1226180Z ##[debug]Total found: 1
2018-07-06T21:27:27.1226750Z ##[debug]Leaving Find-VstsFiles.
2018-07-06T21:27:27.1626058Z ##[debug]Asserting leaf path exists: 'D:\a\r1\a\intentional-services CI\projectartifacts\IntentionalServices\PublishProfiles\Int.xml'
2018-07-06T21:27:27.2182620Z Found path: D:\a\r1\a\intentional-services CI\projectartifacts\IntentionalServices\PublishProfiles\Int.xml
2018-07-06T21:27:27.2749585Z ##[debug]INPUT_APPLICATIONPACKAGEPATH: 'D:\a\r1\a\**\applicationpackage\IntentionalServicesPkg'
2018-07-06T21:27:27.2750083Z Searching for path: D:\a\r1\a\**\applicationpackage\IntentionalServicesPkg
2018-07-06T21:27:27.2750438Z ##[debug]Entering Find-VstsFiles.
2018-07-06T21:27:27.2750971Z ##[debug] LegacyPattern: 'D:\a\r1\a\**\applicationpackage\IntentionalServicesPkg'
2018-07-06T21:27:27.2751403Z ##[debug] IncludeDirectories: 'True'
2018-07-06T21:27:27.2751813Z ##[debug]Entering Get-MatchingItems.
2018-07-06T21:27:27.2752828Z ##[debug] IncludePatterns: 'D:\a\r1\a\**\applicationpackage\IntentionalServicesPkg'
2018-07-06T21:27:27.2753715Z ##[debug] ExcludePatterns: ''
2018-07-06T21:27:27.2754067Z ##[debug] IncludeFiles: 'False'
2018-07-06T21:27:27.2754400Z ##[debug] IncludeDirectories: 'True'
2018-07-06T21:27:27.2754723Z ##[debug] Force: 'False'
2018-07-06T21:27:27.4306069Z ##[debug]Path: D:\a\r1\a\intentional-services CI\applicationpackage\IntentionalServicesPkg
2018-07-06T21:27:27.4325011Z ##[debug]Leaving Get-MatchingItems.
2018-07-06T21:27:27.4343761Z ##[debug]Total found: 1
2018-07-06T21:27:27.4390686Z ##[debug]Leaving Find-VstsFiles.
2018-07-06T21:27:27.4411286Z ##[debug]Asserting container path exists: 'D:\a\r1\a\intentional-services CI\applicationpackage\IntentionalServicesPkg'
2018-07-06T21:27:27.4421848Z Found path: D:\a\r1\a\intentional-services CI\applicationpackage\IntentionalServicesPkg
2018-07-06T21:27:27.4445225Z ##[debug]INPUT_SERVICECONNECTIONNAME: '66b6f74f-bc3a-4069-881c-1309361a6179'
2018-07-06T21:27:27.4567710Z ##[debug]ENDPOINT_URL_66b6f74f-bc3a-4069-881c-1309361a6179: 'tcp://intentional-services-int-lb.westus2.cloudapp.azure.com:19000/'
2018-07-06T21:27:27.4593240Z ##[debug]ENDPOINT_AUTH_66b6f74f-bc3a-4069-881c-1309361a6179: '********'
2018-07-06T21:27:27.4632915Z ##[debug]ENDPOINT_DATA_66b6f74f-bc3a-4069-881c-1309361a6179: '{}'
2018-07-06T21:27:27.4661705Z ##[debug]INPUT_COPYPACKAGETIMEOUTSEC (empty)
2018-07-06T21:27:27.4703148Z ##[debug]INPUT_REGISTERPACKAGETIMEOUTSEC (empty)
2018-07-06T21:27:27.4726592Z ##[debug]INPUT_COMPRESSPACKAGE: 'true'
2018-07-06T21:27:27.4764865Z ##[debug]INPUT_SKIPUPGRADESAMETYPEANDVERSION: 'true'
2018-07-06T21:27:27.4788982Z ##[debug]INPUT_SKIPPACKAGEVALIDATION: 'false'
2018-07-06T21:27:27.4811976Z ##[debug]INPUT_UNREGISTERUNUSEDVERSIONS: 'true'
2018-07-06T21:27:27.4835645Z ##[debug]INPUT_CONFIGUREDOCKERSETTINGS: 'false'
2018-07-06T21:27:27.4857680Z ##[debug]INPUT_OVERRIDEAPPLICATIONPARAMETER: 'false'
2018-07-06T21:27:27.5379773Z ##[debug]Entering Connect-ServiceFabricClusterFromServiceEndpoint.
2018-07-06T21:27:27.5411985Z ##[debug] ClusterConnectionParameters: 'System.Collections.Hashtable'
2018-07-06T21:27:27.5443836Z ##[debug] ConnectedServiceEndpoint: '@{Url=tcp://intentional-services-int-lb.westus2.cloudapp.azure.com:19000/; Data=; Auth=}'
2018-07-06T21:27:27.5466999Z ##[debug]Loading module from path 'D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.13\ps_modules\TlsHelper_\TlsHelper_.psm1'.
2018-07-06T21:27:27.5525423Z ##[debug]Loading resource strings from: D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.13\ps_modules\TlsHelper_/module.json
2018-07-06T21:27:27.5620967Z ##[debug]Loaded 3 strings.
2018-07-06T21:27:27.5650699Z ##[debug]SYSTEM_CULTURE: 'en-US'
2018-07-06T21:27:27.5673770Z ##[debug]Loading resource strings from: D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.13\ps_modules\TlsHelper_\Strings\resources.resjson\en-US\resources.resjson
2018-07-06T21:27:27.5764974Z ##[debug]Loaded 3 strings.
2018-07-06T21:27:27.5785372Z ##[debug]Exporting function 'Add-Tls12InSession'.
2018-07-06T21:27:27.5803092Z ##[debug]Exporting function 'Assert-TlsError'.
2018-07-06T21:27:27.5819578Z ##[debug]Importing function 'Add-Tls12InSession'.
2018-07-06T21:27:27.5840176Z ##[debug]Importing function 'Assert-TlsError'.
2018-07-06T21:27:27.6743972Z ##[debug]TLS 1.2 already present in session.
2018-07-06T21:27:37.1648501Z AAD Authority: https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47
2018-07-06T21:27:37.1660698Z Cluster Application ID: 6fa770fb-fdf9-4bf9-a298-ae3181ba914f
2018-07-06T21:27:37.1685835Z Client Application ID: d8f8adda-c944-4400-9f18-e4e65d089ef5
2018-07-06T21:27:40.7473953Z Successfully connected to cluster.
2018-07-06T21:27:40.7558898Z ##[debug]Leaving Connect-ServiceFabricClusterFromServiceEndpoint.
2018-07-06T21:27:40.8236103Z ##[debug]INPUT_APPLICATIONPARAMETERPATH: 'D:\a\r1\a'
2018-07-06T21:27:40.8255337Z Searching for path: D:\a\r1\a
2018-07-06T21:27:40.8278776Z ##[debug]Entering Find-VstsFiles.
2018-07-06T21:27:40.8308542Z ##[debug] LegacyPattern: 'D:\a\r1\a'
2018-07-06T21:27:40.8326813Z ##[debug]Entering Get-MatchingItems.
2018-07-06T21:27:40.8388446Z ##[debug] IncludePatterns: 'D:\a\r1\a'
2018-07-06T21:27:41.0579199Z ##[debug] ExcludePatterns: ''
2018-07-06T21:27:41.0580473Z ##[debug] IncludeFiles: 'True'
2018-07-06T21:27:41.0938591Z ##[debug] IncludeDirectories: 'False'
2018-07-06T21:27:41.1244765Z ##[debug] Force: 'False'
2018-07-06T21:27:41.1572030Z ##[debug]No paths.
2018-07-06T21:27:41.1594366Z ##[debug]Leaving Get-MatchingItems.
2018-07-06T21:27:41.1614554Z ##[debug]Total found: 0
2018-07-06T21:27:41.1635974Z ##[debug]Leaving Find-VstsFiles.
2018-07-06T21:27:41.1665050Z No items were found with search pattern D:\a\r1\a.
2018-07-06T21:27:41.1721825Z ##[debug]Asserting leaf path exists: 'D:\a\r1\a\intentional-services CI\projectartifacts\IntentionalServices\PublishProfiles\..\ApplicationParameters\Int.xml'
2018-07-06T21:27:41.1751520Z ##[debug]INPUT_OVERRIDEPUBLISHPROFILESETTINGS: 'false'
2018-07-06T21:27:41.6648127Z ##[debug]INPUT_USEDIFFPACKAGE: 'true'
2018-07-06T21:28:46.7477510Z ##[debug]Join-Path "C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code" "ServiceFabricServiceModel.xsd"
2018-07-06T21:28:46.7570394Z ##[debug]C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\ServiceFabricServiceModel.xsd
2018-07-06T21:28:46.7581580Z ##[debug]Length: 94
2018-07-06T21:28:46.7605330Z ##[debug]
2018-07-06T21:28:46.7633399Z ##[debug]Test-Path "C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\ServiceFabricServiceModel.xsd"
2018-07-06T21:28:46.7676228Z ##[debug]True
2018-07-06T21:28:46.7681709Z ##[debug]
2018-07-06T21:29:26.6375625Z ##[debug]Loading module from path 'D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.13\Create-DiffPackage.psm1'.
2018-07-06T21:29:26.6462496Z ##[debug]Exporting function 'New-DiffPackage'.
2018-07-06T21:29:26.6480013Z ##[debug]Exporting function 'Copy-DiffPackage'.
2018-07-06T21:29:26.6495926Z ##[debug]Importing function 'Copy-DiffPackage'.
2018-07-06T21:29:26.6513272Z ##[debug]Importing function 'New-DiffPackage'.
2018-07-06T21:29:26.6616053Z ##[debug]Entering New-DiffPackage.
2018-07-06T21:29:26.6685438Z ##[debug] ApplicationName: 'fabric:/IntentionalServices'
2018-07-06T21:29:26.6703422Z ##[debug] ApplicationPackagePath: 'D:\a\r1\a\intentional-services CI\applicationpackage\IntentionalServicesPkg'
2018-07-06T21:29:26.6721368Z ##[debug] ConnectedServiceEndpoint: '@{Url=tcp://intentional-services-int-lb.westus2.cloudapp.azure.com:19000/; Data=; Auth=}'
2018-07-06T21:29:26.6739278Z ##[debug] ClusterConnectionParameters: 'System.Collections.Hashtable'
2018-07-06T21:29:26.6768743Z Trying to create diff package...
2018-07-06T21:29:26.6814044Z ##[debug]Importing function 'Connect-ServiceFabricClusterFromServiceEndpoint'.
2018-07-06T21:29:26.6830749Z ##[debug]Importing function 'Get-ServiceFabricEncryptedText'.
2018-07-06T21:29:26.6951412Z ##[debug]Importing variable 'SF_Operations'.
2018-07-06T21:29:26.6951870Z ##[debug]Importing function 'Get-TempDirectoryPath'.
2018-07-06T21:29:26.7001247Z ##[debug]Importing function 'Invoke-ActionWithRetries'.
2018-07-06T21:29:26.7830972Z ##[debug]AGENT_TEMPDIRECTORY: 'D:\a\_temp'
2018-07-06T21:29:26.8835994Z Copying D:\a\r1\a\intentional-services CI\applicationpackage\IntentionalServicesPkg\ApplicationManifest.xml from full application package to D:\a\_temp\DiffPackage\ApplicationManifest.xml in diff package...
2018-07-06T21:29:27.2239698Z Creating diff package for service: WorkerQueueServicePkg, clusterServiceManifest.Version: 1.0.29763, localServiceManifest.Version: 1.0.29976
2018-07-06T21:29:27.2358442Z Copying D:\a\r1\a\intentional-services CI\applicationpackage\IntentionalServicesPkg\WorkerQueueServicePkg\Code from full application package to D:\a\_temp\DiffPackage\WorkerQueueServicePkg\Code in diff package...
2018-07-06T21:29:27.4276448Z Copying D:\a\r1\a\intentional-services CI\applicationpackage\IntentionalServicesPkg\WorkerQueueServicePkg\ServiceManifest.xml from full application package to D:\a\_temp\DiffPackage\WorkerQueueServicePkg\ServiceManifest.xml in diff package...
2018-07-06T21:29:27.4306111Z The service SubstrateTokenServicePkg of application fabric:/IntentionalServices to be upgraded by using diff package has the same version 1.0.26006 running in the cluster tcp://intentional-services-int-lb.westus2.cloudapp.azure.com:19000/. Skip upgrading it.
2018-07-06T21:29:27.4324669Z Creating diff package for service: MsaAuthServicePkg, clusterServiceManifest.Version: 1.0.26006, localServiceManifest.Version: 1.0.29896
2018-07-06T21:29:27.4352312Z The package D:\a\r1\a\intentional-services CI\applicationpackage\IntentionalServicesPkg\MsaAuthServicePkg\Code does not exist in the full application package. Skip copying it to diff package.
2018-07-06T21:29:27.4363819Z Copying D:\a\r1\a\intentional-services CI\applicationpackage\IntentionalServicesPkg\MsaAuthServicePkg\ServiceManifest.xml from full application package to D:\a\_temp\DiffPackage\MsaAuthServicePkg\ServiceManifest.xml in diff package...
2018-07-06T21:29:27.5516871Z ##[debug]Leaving New-DiffPackage.
2018-07-06T21:29:27.8451077Z ##[debug]Processed: ##vso[task.logissue type=error;code={"Task_Internal_Error":"CreateDiffPackage|System.IO.DirectoryNotFoundException;|D:\\a\\_tasks\\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\\1.7.13\\Create-DiffPackage.psm1|109"};]
2018-07-06T21:29:27.8451937Z ##[debug]Leaving D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.13\deploy.ps1.
2018-07-06T21:29:27.8486184Z ##[debug]Caught exception from task script.
2018-07-06T21:29:27.8517666Z ##[debug]Error record:
2018-07-06T21:29:27.9445976Z ##[debug]Copy-Item : Could not find a part of the path 'D:\a\_temp\DiffPackage\MsaAuthServicePkg\ServiceManifest.xml'.
2018-07-06T21:29:27.9458843Z ##[debug]At D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.13\Create-DiffPackage.psm1:109 char:13
2018-07-06T21:29:27.9470671Z ##[debug]+             Copy-Item -LiteralPath $localServiceManifestPath (Join-Pa ...
2018-07-06T21:29:27.9483283Z ##[debug]+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2018-07-06T21:29:27.9496224Z ##[debug]    + CategoryInfo          : NotSpecified: (:) [Copy-Item], DirectoryNotFoundException
2018-07-06T21:29:27.9508572Z ##[debug]    + FullyQualifiedErrorId : System.IO.DirectoryNotFoundException,Microsoft.PowerShell.Commands.CopyItemCommand
2018-07-06T21:29:27.9521608Z ##[debug] 
2018-07-06T21:29:27.9541059Z ##[debug]Script stack trace:
2018-07-06T21:29:27.9576415Z ##[debug]at New-DiffPackage, D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.13\Create-DiffPackage.psm1: line 109
2018-07-06T21:29:27.9588627Z ##[debug]at <ScriptBlock>, D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.13\deploy.ps1: line 122
2018-07-06T21:29:27.9601234Z ##[debug]at <ScriptBlock>, <No file>: line 1
2018-07-06T21:29:27.9614195Z ##[debug]at <ScriptBlock>, <No file>: line 22
2018-07-06T21:29:27.9629541Z ##[debug]at <ScriptBlock>, <No file>: line 18
2018-07-06T21:29:27.9642934Z ##[debug]at <ScriptBlock>, <No file>: line 1
2018-07-06T21:29:27.9662943Z ##[debug]Exception:
2018-07-06T21:29:27.9705636Z ##[debug]System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\a\_temp\DiffPackage\MsaAuthServicePkg\ServiceManifest.xml'.
2018-07-06T21:29:27.9718763Z ##[debug]   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
2018-07-06T21:29:27.9732439Z ##[debug]   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
2018-07-06T21:29:27.9744653Z ##[debug]   at System.IO.FileInfo.CopyTo(String destFileName, Boolean overwrite)
2018-07-06T21:29:27.9757268Z ##[debug]   at Microsoft.PowerShell.Commands.FileSystemProvider.CopyFileInfoItem(FileInfo file, String destinationPath, Boolean force, PowerShell ps)
2018-07-06T21:29:27.9771575Z ##[debug]   at Microsoft.PowerShell.Commands.FileSystemProvider.CopyItemLocalOrToSession(String path, String destinationPath, Boolean recurse, Boolean Force, PowerShell ps)
2018-07-06T21:29:27.9784674Z ##[debug]   at Microsoft.PowerShell.Commands.FileSystemProvider.CopyItem(String path, String destinationPath, Boolean recurse)
2018-07-06T21:29:27.9797050Z ##[debug]   at System.Management.Automation.SessionStateInternal.CopyItem(CmdletProvider providerInstance, String path, String copyPath, Boolean recurse, CmdletProviderContext context)
2018-07-06T21:29:28.0020977Z ##[error]Could not find a part of the path 'D:\a\_temp\DiffPackage\MsaAuthServicePkg\ServiceManifest.xml'.
2018-07-06T21:29:28.0021837Z ##[debug]Processed: ##vso[task.logissue type=error]Could not find a part of the path 'D:\a\_temp\DiffPackage\MsaAuthServicePkg\ServiceManifest.xml'.
2018-07-06T21:29:28.0027741Z ##[debug]Processed: ##vso[task.complete result=Failed]
2018-07-06T21:29:28.0422830Z ##[section]Finishing: Deploy Service Fabric Application
```

Any ideas what could cause this?

**Comment by bishal-pdMSFT** [comment]
Notice this error line number. This is not in correct. Have you modified the task yourself by any chance?

> 2018-07-06T21:29:27.9445976Z ##[debug]Copy-Item : Could not find a part of the path 'D:\a\_temp\DiffPackage\MsaAuthServicePkg\ServiceManifest.xml'.
2018-07-06T21:29:27.9458843Z ##[debug]At D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.13\Create-DiffPackage.psm1:109 char:13
2018-07-06T21:29:27.9470671Z ##[debug]+             **Copy-Item -LiteralPath $localServiceManifestPath (Join-Pa ...**
2018-07-06T21:29:27.9483283Z ##[debug]+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2018-07-06T21:29:27.9496224Z ##[debug]    + CategoryInfo          : NotSpecified: (:) [Copy-Item], DirectoryNotFoundException
2018-07-06T21:29:27.9508572Z ##[debug]    + FullyQualifiedErrorId : System.IO.DirectoryNotFoundException,Microsoft.PowerShell.Commands.CopyItemCommand

**Comment by Tadimsky** [comment]
Nope, no local modifications. Didn't even know you could do that 🙂

**Comment by bishal-pdMSFT** [comment]
My bad, I was looking at master branch history instead of release branch. This fix has actually not made it to   all scale units. It will take one more week to reach all.
Let me see if I can do a hotfix.

**Comment by Tadimsky** [comment]
Ah, cool cool! That makes sense!

**Comment by bishal-pdMSFT** [comment]
@Tadimsky is this fixed for you now?

**Comment by Tadimsky** [comment]
I haven't done an upgrade with just service manifest changes again. I'll make sure to see when I do it next time - thanks @bishal-pdMSFT

**Comment by bishal-pdMSFT** [comment]
@Tadimsky should we close the issue? You can re-open later if this is not fixed.

**Comment by Tadimsky** [comment]
@bishal-pdMSFT sounds good to me!
