### ISSUE TITLE
TokenCache.dat

### ISSUE THREAD

**Issue by elangelo** [Microsoft/vsts-tasks#7690]
We recently updated our Release Machines
1. We updated to AzureRM 6.4.0
2. We updated all agents to the last version (134)
3. All Release agents are running as a domain user (there are 10 agents on every machine) (before they were running as SYSTEM (the default))
4. We switched some releases to use the AzureRM Preview 3 task

Now we are noticing some releases failing with:
The process cannot access the file 'C:\Users\sa.vstsrma\AppData\Roaming\Windows Azure Powershell\TokenCache.dat' because it is being used by another process. | The process cannot access the file 'C:\Users\sa.vstsrma\AppData\Roaming\Windows Azure Powershell\TokenCache.dat' because it is being used by another process.

We are unsure which change could have caused this but 3 and 4 seem very likely

**Comment by elangelo** [comment]
Update
1. We stopped using the Preview 3: are still seeing the issue
2. Switched back to SYSTEM: still seeing the issue
3. Downgraded AzureRM to 5.7.0... still testing.

**Comment by elangelo** [comment]
The downgrade to 5.7.0 got us back in the problem where all are Azure Powershell tasks are being canceled.

**Comment by SumiranAgg** [comment]
After downgrading Azure PS version what is the error that you get on task failure?

**Comment by elangelo** [comment]
we get `a task was cancelled` on 20 to 50% of our Azure Powershell tasks that get executed.

**Comment by elangelo** [comment]
```
2018-07-13T03:31:02.7714945Z ##[section]Starting: Create Asset Storage
2018-07-13T03:31:02.7721653Z ==============================================================================
2018-07-13T03:31:02.7722313Z Task         : Azure PowerShell
2018-07-13T03:31:02.7723124Z Description  : Run a PowerShell script within an Azure environment
2018-07-13T03:31:02.7723569Z Version      : 2.0.11
2018-07-13T03:31:02.7723966Z Author       : Microsoft Corporation
2018-07-13T03:31:02.7724462Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613749)
2018-07-13T03:31:02.7725027Z ==============================================================================
2018-07-13T03:31:04.7862660Z Added TLS 1.2 in session.
2018-07-13T03:31:04.9964383Z ##[command]Import-Module -Name C:\Program Files\WindowsPowerShell\Modules\AzureRM\5.7.0\AzureRM.psd1 -Global
2018-07-13T03:31:33.0229576Z ##[command]Add-AzureRMAccount -ServicePrincipal -Tenant *** -Credential System.Management.Automation.PSCredential -Environment AzureCloud
2018-07-13T03:31:33.8067903Z ##[command] Select-AzureRMSubscription -SubscriptionId *** -TenantId ***
2018-07-13T03:31:34.3550899Z ##[command]& 'F:\agent02\_work\r4\a\***.ps1' -AssetStorageAccount *** -Customer g***
2018-07-13T03:33:14.6759475Z ##[error]A task was canceled.
```

**Comment by SumiranAgg** [comment]
last weak we were facing some issue in correcting to Azure Resource manager i.e. making calls to management.azure.com, which was resulting in error "task cancelled". This issue had been resolved, pleaase refer https://blogs.msdn.microsoft.com/vsoservice/?p=17125 for details.

**Comment by elangelo** [comment]
I'm aware of that but we still encounter the `task was cancelled` with AzureRM 5.7.0.
For now we have upgraded again to 6.4.0 and we are using a different account for every instance of the agent. It is mighty inconvenient but it seems to work for now. Feels very much like a workaround though.

**Comment by SumiranAgg** [comment]
@elangelo Can you share the script that is failing? It seems that we have a single file that holds the tokens for a single user on a machine. So, if you are trying to login through multiple jobs in parallel, the file is locked by one process and cannot be accessed by the other.

**Comment by elangelo** [comment]
It's not a single script that is failing. Pretty much any script can fail as long as it's running simultaneously with another script and it's a Azure Powershell task. Generally this happens in the login phase to Azure. It has happened a couple of times in steps that involve access to Azure Keyvaults
 (get-azurekeyvaultsecret and set-azurekeyvaultsecret)

(PS i'm on leave till the first of august so i might not be able to provide any further details till then)

**Comment by SumiranAgg** [comment]
As I understand you are running jobs in parallel and each job is trying to login to azure. There is only one file for a single user on a machine that stores tokens viz. TokenCache.dat.
When one job is tryng to login, it acquires lock on that file, as such another job running in parallel will not be able to access it.
If you’re not trying to use multiple Azure accounts and just want to remain logged in for every PowerShell session. Log in once, run Enable-ContextAutoSave, and then every new session (parallel or otherwise) will be logged in. So, no need to login for every parallel instance.
Doc for reference https://docs.microsoft.com/en-us/powershell/azure/context-persistence?view=azurermps-6.4.0&viewFallbackFrom=azurermps-6.0.0

**Comment by rajatagrawal-dev** [comment]
@elangelo Please try using Enable-ContextAutoSave as suggested by @SumiranAgg. According to the doc, your context info will be saved in a file in 'AppData' folder. Subsequently, each new PowerShell session targets the context used in your last session.

**Comment by rajatagrawal-dev** [comment]
@elangelo Did you get a chance to try "Enable-ContextAutoSave"? Let us know if that mitigated the issue for you.

**Comment by elangelo** [comment]
Not really, I'm still trying to think of a way on how to do this for my vstsagent.

**Comment by rajatagrawal-dev** [comment]
@elangelo Do you have multiple agents configured on a single machine? Or do you have multiple machines with single agent configured on each machine?

**Comment by elangelo** [comment]
I have multiple machines with multiple agents

**Comment by rajatagrawal-dev** [comment]
If you have multiple agents configured on any machine, then please also try deleting the TokenCache.dat file from your machines once. It might get you unblocked.

**Comment by elangelo** [comment]
The release definition seems to have done it's work, I haven't encountered the tokencache problem anymore so you can close this if you want.

**Comment by elangelo** [comment]
I will have to reopen the issue. The problem with the TokeCache.Dat file being locked every now and then is still occuring:
```
2018-08-09T11:08:37.9269086Z ==============================================================================
2018-08-09T11:08:37.9269808Z Task         : Azure PowerShell
2018-08-09T11:08:37.9270471Z Description  : Run a PowerShell script within an Azure environment
2018-08-09T11:08:37.9271238Z Version      : 3.0.5
2018-08-09T11:08:37.9271784Z Author       : Microsoft Corporation
2018-08-09T11:08:37.9272491Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613749)
2018-08-09T11:08:37.9273261Z ==============================================================================
2018-08-09T11:08:43.0772052Z Added TLS 1.2 in session.
2018-08-09T11:08:43.3386675Z ##[command]Import-Module -Name C:\Program Files\WindowsPowerShell\Modules\AzureRM\6.4.0\AzureRM.psd1 -Global
2018-08-09T11:09:10.9864040Z ##[command]Add-AzureRMAccount -ServicePrincipal -Tenant *** -Credential System.Management.Automation.PSCredential -Environment AzureCloud
2018-08-09T11:09:11.1909181Z ##[error]The process cannot access the file 'C:\Users\sa.vstsrma\AppData\Roaming\Windows Azure Powershell\TokenCache.dat' because it is being used by another process.
2018-08-09T11:09:11.3436477Z ##[error]There was an error with the service principal used for the deployment.
```

**Comment by jsheetzati** [comment]
We have ran into this issue as well and are running multiple agents on multiple machines. Each machine runs 3 agents.

**Comment by elangelo** [comment]
> @elangelo oudl you please confirm are you still using multiple agents on a single machine set-up or you are a single agent installed on a machine

Yes. We are running still multiple agents on a single machine but all of them are now using different users to make sure that none of them tries to write in the same tokencache.dat.

**Comment by SumiranAgg** [comment]
Can you confirm if no jobs are running in parallel. For instance are you running any releases stages in parallel?

**Comment by elangelo** [comment]
Of course i can't confirm that. I'm pretty sure jobs are running in parallel...
If I have to bring up a release server for every job that is running this quickly becomes totally unpayable...

**Comment by mstephens-adig** [comment]
We are still seeing this issue as well. We have multiple build agents per build machine. We have confirmed that it occurs even when only a single agent is currently running tasks on the build machine that errors.  This occurs on all 4 of our build machines.

**Comment by SumiranAgg** [comment]
@elangelo Running jobs in parallel is not an issue. The problem occurs when a user is trying to login with different accounts in parallel. Login required access to tokencache.dat file. If one job has lock over it and another tries to access, the operation fails.
If you are logging in with same account 
Enable-AzureRmContextAutosave -Scope CurrentUser
would solve the problem. As per your previous comment you have already added it.
We will investigate further on why has it stopped working and update the thread.

**Comment by elangelo** [comment]
As far as i know the account is always the same, what might change is the subscription name though. Though we did split up our non-production and production release servers as much as possible it could still happen that our non-production release servers are still trying to reach the production subscription for certain tasks.

**Comment by elangelo** [comment]
see opening post:
We updated to AzureRM 6.4.0

**Comment by Ajay-MS** [comment]
@elangelo 

Yes, have seen that. I was doubting if you have upgraded after that. 

Can you please try out with version 6.7 or later and share your observation.

**Comment by ohadschn** [comment]
For me, `Enable-AzureRmContextAutosave` only replaces this issue with this issue: https://github.com/Azure/azure-powershell/issues/9448

**Comment by michaelelleby** [comment]
We are seeing this issue as well, with Azure DevOps Server 2019 version `Dev17.M143.6`  and AzureRM version `6.10.0`

```
System.IO.IOException: The process cannot access the file 'C:\Users\releasesvc\AppData\Roaming\Windows Azure Powershell\TokenCache.dat' because it is 
	being used by another process.
	   at 
	Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.RunAsyncTask[T](Task`1 
	task)
	   at Microsoft.Azure.Commands.Common.Authentication.ServicePrincipalTokenProvider.GetAccessTok
	en(AdalConfiguration config, String promptBehavior, Action`1 promptAction, String userId, 
	SecureString password, String credentialType)
	   at Microsoft.Azure.Commands.Common.Authentication.Factories.AuthenticationFactory.Authentica
	te(IAzureAccount account, IAzureEnvironment environment, String tenant, SecureString password, 
	String promptBehavior, Action`1 promptAction, IAzureTokenCache tokenCache, String resourceId)
	   at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.AcquireAccessToken(IAzure
	Account account, IAzureEnvironment environment, String tenantId, SecureString password, String 
	promptBehavior, Action`1 promptAction)
	   at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.Login(IAzureAccount 
	account, IAzureEnvironment environment, String tenantId, String subscriptionId, String 
	subscriptionName, SecureString password, Boolean skipValidation, Action`1 promptAction, String 
	name, Boolean shouldPopulateContextList)
	   at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.<>c__DisplayClass87_0.<Exec
	uteCmdlet>b__0(AzureRmProfile localProfile, RMProfileClient profileClient, String name)
	   at 
	Microsoft.Azure.Commands.Profile.Common.AzureContextModificationCmdlet.ModifyContext(Action`2 
	contextAction)
	   at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.SetContextWithOverwriteProm
	pt(Action`3 setContextAction)
	   at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.ExecuteCmdlet()
	   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
```
