### ISSUE TITLE
UWP UnitTest App won't run using VsTest.Console

### ISSUE THREAD

**Issue by Daroosh** [Microsoft/vsts-tasks#7705]
## Troubleshooting
I have a UWP composed of 2 projects:
1) Universal App
2) Unit Test App

Tests are visible in Visual Studio Test Explorer and I am fully capable of running them.
As soon as I try to run the tests from VsTest.Console using the following command:

**_vstest.console WTSBridge.build.appxrecipe /framework:FrameworkUap10_**

I get the following error message:

```
Microsoft (R) Test Execution Command Line Tool Version 15.7.2
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Attempting to deploy to target 'Local Machine'.
Creating a new clean layout...

Copying files: Total 39 mb to layout...

Checking whether required frameworks are installed...

Registering the application to run from layout...

Deployment complete (0:00:02.088). Full package name: "68D6D712.Webroot.WebThreatShield.UWP.Edge_1.8.0.0_x86__3n9w82bea0x6e"

Deployment operation succeeded, package moniker: '68D6D712.Webroot.WebThreatShield.UWP.Edge_1.8.0.0_x86__3n9w82bea0x6e'.
Attempting to launch app with app user model Id '68D6D712.Webroot.WebThreatShield.UWP.Edge_3n9w82bea0x6e!App' and arguments '--port 49756 --endpoint 127.0.0.1:049756 --role client --parentprocessid 20064 --telemetryoptedin false'.
Successfully launched process Id '16092'.
Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Failed to initialize client proxy: could not connect to test process.
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyExecutionManager.StartTestRun(TestRunCriteria testRunCriteria, ITestRunEventsHandler eventHandler)
Closing app with package full name '68D6D712.Webroot.WebThreatShield.UWP.Edge_1.8.0.0_x86__3n9w82bea0x6e'.

Test Run Aborted.
```
The test application starts and for a second the window blinks open but, it shuts down right away and I get the above mentioned issue.

## Environment
- Visual Studio 17 (v.15.7.5)
- MSTest.TestAdapter v.1.2.1
- MSTest.TestFramework v.1.2.1

**Comment by mayankbansal018** [comment]
@Daroosh , can you try following:

- Can you please share what is the Max TargetSDK you are using for your UWP app, is it 14393?
-  from CLI can you also enable diagnostics log via passing --diag:<path_to_log.txt>, it should print path to two log files on console, please share both of them.
- Can you also try this for a blank UWP UT app. We want to make sure that there is no external factor which is blocking TCP/IP communication b/w vstest.console, & UWP test app.
- Please also verify that "**package.appxmanifest**" for your Test App contain "internetClientServer", & "privateNetworkClientServer" Capabilities.

**Comment by Daroosh** [comment]
@mayankbansal018 , Thanks a lot for your feedback.

- Yes, 14393 is the TargetSDK version
- I enabled the diagnostics logging and attached the output log file 
- I tried with a blank UWP and UnitTest project, same result
- Yes, both capabilities are enabled in both projects; UWP & UnitTest

Thanks a lot!
[log.txt](https://github.com/Microsoft/vsts-tasks/files/2240933/log.txt)

**Comment by mayankbansal018** [comment]
@Daroosh if the Max Target SDK is 14393, it means that for such UWP test projects we will use our older Testplatform. To run tests for such projects from CLI, You will have to use ".appx" as input, & make sure you set an env variable "PREFER_TP_LEGACY" to 1, & then run it via CLI . Please make sure you register the App before running it via ".appx"

However if you can move your Max target SDK to >14393, & make sure the version of "Microsoft.NETCore.UniversalWindowsPlatform" >5.2.2, you can then use our newer testplatform which takes ".appxrecipe" as input on CLI

I would suggest you try it with Blank UWP Test App, with target SDK > 14393, & then run tests from CLI via ".appxrecipe".

**Comment by Daroosh** [comment]
@mayankbansal018 I did the changes in the empty UWP project. However, I am getting the exact same error.

- Target version in both; UWP project and UnitTest project: 15063
- Microsoft.NETCore.UniversalWindowsPlatform: v6.1.5
- MSTest.TestAdapter: v1.2.1
- MSTest.TestFramework: v1.2.1
[log.txt](https://github.com/Microsoft/vsts-tasks/files/2241488/log.txt)



The following is Package.appxmanifest [UWP project]:
`<?xml version="1.0" encoding="utf-8"?>

<Package
  xmlns="http://schemas.microsoft.com/appx/manifest/foundation/windows10"
  xmlns:mp="http://schemas.microsoft.com/appx/2014/phone/manifest"
  xmlns:uap="http://schemas.microsoft.com/appx/manifest/uap/windows10"
  IgnorableNamespaces="uap mp">

  <Identity
    Name="628b5464-265b-492c-9ac0-c0dec37342b3"
    Publisher="CN=MELSAIE"
    Version="1.0.0.0" />

  <mp:PhoneIdentity PhoneProductId="628b5464-265b-492c-9ac0-c0dec37342b3" PhonePublisherId="00000000-0000-0000-0000-000000000000"/>

  <Properties>
    <DisplayName>EmptyUwp</DisplayName>
    <PublisherDisplayName>MELSAIE</PublisherDisplayName>
    <Logo>Assets\StoreLogo.png</Logo>
  </Properties>

  <Dependencies>
    <TargetDeviceFamily Name="Windows.Desktop" MinVersion="10.0.15063.0" MaxVersionTested="10.0.15063.0" />
  </Dependencies>

  <Resources>
    <Resource Language="x-generate"/>
  </Resources>

  <Applications>
    <Application Id="App"
      Executable="$targetnametoken$.exe"
      EntryPoint="EmptyUwp.App">
      <uap:VisualElements
        DisplayName="EmptyUwp"
        AppListEntry="none"
        Square150x150Logo="Assets\Square150x150Logo.png"
        Square44x44Logo="Assets\Square44x44Logo.png"
        Description="EmptyUwp"
        BackgroundColor="transparent">
        <uap:DefaultTile Wide310x150Logo="Assets\Wide310x150Logo.png"/>
        <uap:SplashScreen Image="Assets\SplashScreen.png" />
      </uap:VisualElements>
    </Application>
  </Applications>

  <Capabilities>
    <Capability Name="internetClientServer" />
    <Capability Name="privateNetworkClientServer" />
  </Capabilities>
</Package>`

The following is Package.appxmanifest [UnitTest project]:
`<?xml version="1.0" encoding="utf-8"?>
<Package
  xmlns="http://schemas.microsoft.com/appx/manifest/foundation/windows10"
  xmlns:mp="http://schemas.microsoft.com/appx/2014/phone/manifest"
  xmlns:uap="http://schemas.microsoft.com/appx/manifest/uap/windows10"
  IgnorableNamespaces="uap mp">

  <Identity Name="4106298d-5419-42c3-85ad-fcddccafd67d"
            Publisher="CN=MELSAIE"
            Version="1.0.0.0" />

  <mp:PhoneIdentity PhoneProductId="4106298d-5419-42c3-85ad-fcddccafd67d" PhonePublisherId="00000000-0000-0000-0000-000000000000"/>

  <Properties>
    <DisplayName>EmptyUnitTest</DisplayName>
    <PublisherDisplayName>MELSAIE</PublisherDisplayName>
    <Logo>Assets\StoreLogo.png</Logo>
  </Properties>

  <Dependencies>
    <TargetDeviceFamily Name="Windows.Universal" MinVersion="10.0.15063.0" MaxVersionTested="10.0.15063.0" />
  </Dependencies>

  <Resources>
    <Resource Language="x-generate" />
  </Resources>
  <Applications>
    <Application Id="vstest.executionengine.universal.App"
        Executable="$targetnametoken$.exe"
        EntryPoint="EmptyUnitTest.App">
      <uap:VisualElements
        DisplayName="EmptyUnitTest"
        Square150x150Logo="Assets\Square150x150Logo.png"
        Square44x44Logo="Assets\Square44x44Logo.png"
        Description="EmptyUnitTest"
        BackgroundColor="transparent">
        <uap:DefaultTile Wide310x150Logo="Assets\Wide310x150Logo.png"/>
        <uap:SplashScreen Image="Assets\SplashScreen.png" />
      </uap:VisualElements>
    </Application>
  </Applications>
  <Capabilities>
    <Capability Name="internetClientServer" />
    <Capability Name="privateNetworkClientServer" />
  </Capabilities>
</Package>`

**Comment by mayankbansal018** [comment]
@Daroosh , you mentioned that you are able to run test from IDE, are you able to do the same for Blank UWP Test project?
Can you verify what is the TestPlatfom.Universal version shown in IDE (refer attached image), it should be 15.5.0
![tp_version](https://user-images.githubusercontent.com/24792973/43403852-cfe38a9c-9433-11e8-9eb2-f7eddaea336f.PNG)

- When you run via CLI, do you your empty  UWP app launched or not?
- Also please share what is displayed on the console when you run via CLI.
- Can you zip you empty UWP project "the whole bin\x86\debug folder

**Comment by Daroosh** [comment]
@mayankbansal018 
**TestPlatform.Universal: v.15.0.0**

Cli output:
```
Microsoft (R) Test Execution Command Line Tool Version 15.7.2
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Logging Vstest Diagnostics in file: C:\Users\MELSAIE\Desktop\TOOLS\EDGE\BuildLogs\log.txt
Attempting to deploy to target 'Local Machine'.
Updating the layout...

Copying files: Total <1 mb to layout...

Checking whether required frameworks are installed...

Registering the application to run from layout...

Deployment complete (0:00:01.946). Full package name: "4106298d-5419-42c3-85ad-fcddccafd67d_1.0.0.0_x86__zn6f25kw3wxgr"

Deployment operation succeeded, package moniker: '4106298d-5419-42c3-85ad-fcddccafd67d_1.0.0.0_x86__zn6f25kw3wxgr'.
Attempting to launch app with app user model Id '4106298d-5419-42c3-85ad-fcddccafd67d_zn6f25kw3wxgr!vstest.executionengine.universal.App' and arguments '--port 49810 --endpoint 127.0.0.1:049810 --role client --parentprocessid 16416 --diag "C:\Users\MELSAIE\Desktop\TOOLS\EDGE\BuildLogs\log.host.18-07-30_16-19-32_11173_6.txt" --telemetryoptedin false'.
Successfully launched process Id '10904'.
Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Failed to initialize client proxy: could not connect to test process.
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyExecutionManager.StartTestRun(TestRunCriteria testRunCriteria, ITestRunEventsHandler eventHandler)
Closing app with package full name '4106298d-5419-42c3-85ad-fcddccafd67d_1.0.0.0_x86__zn6f25kw3wxgr'.

Test Run Aborted.
```
When run from cli, unitTest app flickers, a window is displayed and then disappears. Shortly after, the test fails and i get the error message mentioned above.

[Debugx86.zip](https://github.com/Microsoft/vsts-tasks/files/2241613/Debugx86.zip)

**Comment by mayankbansal018** [comment]
@Daroosh since the version is 15.0.0 which means your app is still targeting older testplatform, I don't know why it is doing so.
The reason you are getting the error is because the vstest.console that is getting invoked has a different communication model, as compared to that of old platform(your UWP app contains bits from Old platform because of 15.0.0) hence the error. 

It's possible that something is wrong with your VS installation, can you please try to repair your VS, or run this experiment on a separate VM with clean VS installation.?

**Comment by Daroosh** [comment]
@mayankbansal018 Thanks a lot for the info. I'll try on a fresh installed VS on one of my VM's and I'll keep you posted!

Thank you!

**Comment by mayankbansal018** [comment]
Also the reason things are working from VS IDE, is because based on Testplatform version (15.0 vs 15.5) IDE determines how to run the UWP Test app, where as CLI can't do so.

Another thing you can try is, modify you csproj file, & change the value of
**UnitTestPlatformVersion** from "$(VisualStudioVersion)" to 15.5, this should explicitly bring in dependencies of latest test platform, & then try to run the app via CLI.

If the above doesn't work(build fails), please see whether 15.5 SDK is present at location "C:\Program Files (x86)\Microsoft SDKs\Windows Kits\10\ExtensionSDKs\TestPlatform.Universal" or not, & what all assemblies it contains internally.

**Comment by mayankbansal018** [comment]
@Daroosh , any update on this?

**Comment by Daroosh** [comment]
@mayankbansal018 Thanks for the follow up. We are currently in the process of updating our components and will try within a freshly installed environment. I'll keep you updated very shortly as soon as we're done with the set up.

Thanks again!

**Comment by mayankbansal018** [comment]
@Daroosh good to know it got resolved for you. :)
