### ISSUE TITLE
Service Fabric Deployment fails with ApplicationTypeName parameter not found

### ISSUE THREAD

**Issue by edwardg-MSFT** [Microsoft/vsts-tasks#7801]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
devdiv.visualstudio.com
Failed release (current task version 1.7.17 - look at attempt #1): https://devdiv.visualstudio.com/XlabImageFactory/XlabImageFactory%20Team/_apps/hub/ms.vss-releaseManagement-web.hub-explorer?releaseId=24014&definitionId=19&_a=release-logs
Successful release of same package (task version 1.7.15): https://devdiv.visualstudio.com/XlabImageFactory/XlabImageFactory%20Team/_release?releaseId=23838&_a=release-logs

- Agent - Hosted or Private: 
Private - Server 2016 R2

## Issue Description

Our CI deployments stopped working between Tuesday 7/17 (using version 1.7.15 of the task) and 7/20 (version 1.7.17) with the below error, even when attempting to deploy the same package.

### Error logs
2018-07-20T21:54:20.2859077Z ##[debug]Asserting leaf path exists: 'C:\Agent\_work\r2\a\MediaDropApplication\drop\windowsprojectartifacts\MediaDropApplication\WindowsMediaDropApplication\PublishProfiles\..\ApplicationParameters\PPECloud.xml'
2018-07-20T21:54:20.2899093Z ##[debug]INPUT_OVERRIDEPUBLISHPROFILESETTINGS: 'false'
2018-07-20T21:54:20.4235435Z ##[debug]INPUT_USEDIFFPACKAGE: 'false'
2018-07-20T21:54:20.9701242Z ##[debug]Processed: ##vso[task.logissue type=error;code={"Task_Internal_Error":"GetApplication|System.Management.Automation.ParameterBindingException;|C:\\Agent\\_work\\_tasks\\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\\1.7.17\\deploy.ps1|187"};]
2018-07-20T21:54:21.5898702Z ##[debug]Leaving C:\Agent\_work\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.17\deploy.ps1.
2018-07-20T21:54:21.5958637Z ##[debug]Caught exception from task script.
2018-07-20T21:54:21.5988638Z ##[debug]Error record:
2018-07-20T21:54:21.6678714Z ##[debug]Publish-UpgradedServiceFabricApplication : A parameter cannot be found that matches parameter name 'ApplicationTypeName'.
2018-07-20T21:54:21.6698725Z ##[debug]At C:\Agent\_work\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.17\deploy.ps1:187 char:9
2018-07-20T21:54:21.6708723Z ##[debug]+         Publish-UpgradedServiceFabricApplication @publishParameters
2018-07-20T21:54:21.6728642Z ##[debug]+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2018-07-20T21:54:21.6748693Z ##[debug]    + CategoryInfo          : InvalidArgument: (:) [Publish-UpgradedServiceFabricApplication], ParameterBindingExcepti    on
2018-07-20T21:54:21.6768641Z ##[debug]    + FullyQualifiedErrorId : NamedParameterNotFound,Publish-UpgradedServiceFabricApplication
2018-07-20T21:54:21.6778788Z ##[debug] 
2018-07-20T21:54:21.6798651Z ##[debug]Script stack trace:
2018-07-20T21:54:21.6848761Z ##[debug]at Get-ServiceFabricApplicationAction, C:\Agent\_work\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.17\ServiceFabricSDK\Utilities.ps1: line 232
2018-07-20T21:54:21.6858789Z ##[debug]at Publish-UpgradedServiceFabricApplication, C:\Agent\_work\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.17\ServiceFabricSDK\Publish-UpgradedServiceFabricApplication.ps1: line 206
2018-07-20T21:54:21.6878632Z ##[debug]at <ScriptBlock>, C:\Agent\_work\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.17\deploy.ps1: line 187
2018-07-20T21:54:21.6898668Z ##[debug]at <ScriptBlock>, <No file>: line 1
2018-07-20T21:54:21.6908818Z ##[debug]at <ScriptBlock>, <No file>: line 22
2018-07-20T21:54:21.6928631Z ##[debug]at <ScriptBlock>, <No file>: line 18
2018-07-20T21:54:21.6939443Z ##[debug]at <ScriptBlock>, <No file>: line 1
2018-07-20T21:54:21.6958977Z ##[debug]Exception:
2018-07-20T21:54:21.6998654Z ##[debug]System.Management.Automation.ParameterBindingException: A parameter cannot be found that matches parameter name 'ApplicationTypeName'.
2018-07-20T21:54:21.7018738Z ##[debug]   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
2018-07-20T21:54:21.7028649Z ##[debug]   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
2018-07-20T21:54:21.7048665Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2018-07-20T21:54:21.7060585Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2018-07-20T21:54:21.7068652Z ##[debug]   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
2018-07-20T21:54:21.7088675Z ##[debug]   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
2018-07-20T21:54:21.7099270Z ##[debug]   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
2018-07-20T21:54:21.7108969Z ##[debug]   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
2018-07-20T21:54:21.7128644Z ##[debug]   at System.Management.Automation.CommandProcessorBase.Complete()
2018-07-20T21:54:21.7374514Z ##[error]A parameter cannot be found that matches parameter name 'ApplicationTypeName'.
2018-07-20T21:54:21.7374514Z ##[debug]Processed: ##vso[task.logissue type=error]A parameter cannot be found that matches parameter name 'ApplicationTypeName'.
2018-07-20T21:54:21.7384556Z ##[debug]Processed: ##vso[task.complete result=Failed]
2018-07-20T21:54:21.7874584Z ##[section]Finishing: Deploy Windows Service Fabric Application

**Comment by bishal-pdMSFT** [comment]
@edwardg-MSFT this can happen if the service fabric sdk which is installed on private agent is old. You can update the SDK + runtime and retry.

**Comment by bishal-pdMSFT** [comment]
@edwardg-MSFT we do have made some changes in the task in 1.7.17 version, however there is no change related to the error message you have reported. This error looks like agent is using old version of service fabric SDK. Have you changed agent queue for your release which resulted into older SDK ?

**Comment by rorymacleod** [comment]
I had a similar issue, except that the missing parameter was "ApplicationTypeVersion". My build agent was using version 2.6.220 of the Service Fabric SDK - upgrading to the latest 3.2.162 fixed it.

**Comment by edwardg-MSFT** [comment]
There was no change to the agent pool. However, updating to the latest version (3.2.162) has enabled the task to succeed.

**Comment by bishal-pdMSFT** [comment]
Just to update - fix for this has been rolled out. You won't need to use newer SDK.

**Comment by bishal-pdMSFT** [comment]
but, if you use newer SDK, you will get added reliability in task. So, better to use new SDK
