### ISSUE TITLE
VSTS Nuget Push Task

### ISSUE THREAD

**Issue by bgklein** [Microsoft/vsts-tasks#7877]
## Troubleshooting
We tried mitigating the tag issue by adding an additional X.Y.Z.Patch.Tag which did not work.

## Issue Description

When using to Nuget Push Task to push an internal package feed get the following version when adding a task with the version '1.3.0.8-0001'. We are able to upload packages fine with X.Y.Z.Patch fine so it has to do with the tag at the end. 

### Error logs

Microsoft.VisualStudio.Services.NuGet.WebApi.Exceptions.InvalidPackageException: The package is invalid: The package's version isn't formatted correctly.
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponse(HttpResponseMessage response)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VstsNuGetPush.PackageAdder.AddPackageToFeed(String feedName, BlobIdentifierWithBlocks blobId)
   at VstsNuGetPush.VstsNuGetPushOperation.AddPackageToFeed(BlobIdentifierWithBlocks blobId)
   at VstsNuGetPush.VstsNuGetPushCommand.MainCore(ILogger logger)
   at VstsNuGetPush.VstsNuGetPushCommand.Main())

**Comment by bgklein** [comment]
Closing
