### ISSUE TITLE
GetInput results in error "Cannot read property 'retrieveSecret' of undefined"

### ISSUE THREAD

**Issue by scott-lin** [Microsoft/vsts-tasks#7892]
## Environment
- VSTS
    - Account: pyewpyew
    - Project: VstsExtensionTesting
    - Build Definition: Build VstsExtensionTesting
    - BuildId: 181
- Agent: Hosted

## Issue Description

I'm developing a custom build task using `"vsts-task-lib": "^2.6.0"` dependency. The first action my task performs is to fetch inputs (see line 97 below). When doing so, it fails with error, "Cannot read property 'retrieveSecret' of undefined".

``
Line 97:     let openApiDocumentVersion = tl.getInput('openApiDocumentVersion', true);
``

It seems "_vault" is undefined when calling [getInput](https://github.com/Microsoft/vsts-task-lib/blob/3a7905b99d698a535d9f5a477efc124894b8d2ae/node/task.ts#L178). Full log and error stack trace below.

I'm happy to share the source or complete extension package upon request.

### Task Log with debug enabled
```
2018-07-31T21:50:18.6098542Z ##[debug]Evaluating condition for step: 'Build OpenAPI Document: Swagger Samples'
2018-07-31T21:50:18.6099261Z ##[debug]Evaluating: succeeded()
2018-07-31T21:50:18.6099439Z ##[debug]Evaluating succeeded:
2018-07-31T21:50:18.6099710Z ##[debug]=> True
2018-07-31T21:50:18.6099971Z ##[debug]Result: True
2018-07-31T21:50:18.6100237Z ##[section]Starting: Build OpenAPI Document: Swagger Samples
2018-07-31T21:50:18.6105682Z ==============================================================================
2018-07-31T21:50:18.6105898Z Task         : Build OpenAPI Document
2018-07-31T21:50:18.6106013Z Description  : Generates OpenAPI document(s) based on a build's output.
2018-07-31T21:50:18.6106121Z Version      : 0.0.10
2018-07-31T21:50:18.6106237Z Author       : Microsoft Corporation
2018-07-31T21:50:18.6106331Z Help         : 
2018-07-31T21:50:18.6106437Z ==============================================================================
2018-07-31T21:50:18.8304343Z ##[debug]agent.TempDirectory=D:\a\_temp
2018-07-31T21:50:18.8337511Z ##[debug]loading inputs and endpoints
2018-07-31T21:50:18.8343007Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
2018-07-31T21:50:18.8361369Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
2018-07-31T21:50:18.8365163Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
2018-07-31T21:50:18.8367737Z ##[debug]loading INPUT_ASSEMBLYFILENAMEPATTERNS
2018-07-31T21:50:18.8371268Z ##[debug]loading INPUT_ASSEMBLYFILESEARCHPATH
2018-07-31T21:50:18.8373424Z ##[debug]loading INPUT_CREATEOUTPUTDIRECTORYIFNOTEXISTS
2018-07-31T21:50:18.8376202Z ##[debug]loading INPUT_CSHARPANNOTATIONSDOCUMENTGENERATIONADVANCEDCONFIGURATIONFILESEARCHPATH
2018-07-31T21:50:18.8378373Z ##[debug]loading INPUT_FAILONMULTIPLEASSEMBLYFILEMATCHES
2018-07-31T21:50:18.8381946Z ##[debug]loading INPUT_FAILONMULTIPLECSHARPANNOTATIONSDOCUMENTGENERATIONADVANCEDCONFIGURATIONFILEMATCHES
2018-07-31T21:50:18.8384651Z ##[debug]loading INPUT_FAILONMULTIPLEVISUALSTUDIOXMLMATCHES
2018-07-31T21:50:18.8386666Z ##[debug]loading INPUT_FORMAT
2018-07-31T21:50:18.8389333Z ##[debug]loading INPUT_OPENAPIDOCUMENTVERSION
2018-07-31T21:50:18.8393859Z ##[debug]loading INPUT_OPENAPISPECIFICATIONVERSION
2018-07-31T21:50:18.8395509Z ##[debug]loading INPUT_OUTPUTDIRECTORYPATH
2018-07-31T21:50:18.8406517Z ##[debug]loading INPUT_RECURSIVECSHARPANNOTATIONSDOCUMENTGENERATIONADVANCEDCONFIGURATIONFILESEARCH
2018-07-31T21:50:18.8430168Z ##[debug]loading INPUT_SERVICENAME
2018-07-31T21:50:18.8430377Z ##[debug]loading INPUT_USECAMELCASEFORSCHEMAPROPERTIES_CSHARPANNOTATIONSDOCUMENTGENERATIONSETTING
2018-07-31T21:50:18.8430575Z ##[debug]loading INPUT_VISUALSTUDIOXMLDOCUMENTATIONFILENAMEPATTERNS
2018-07-31T21:50:18.8430738Z ##[debug]loading INPUT_VISUALSTUDIOXMLSEARCHPATH
2018-07-31T21:50:18.8430904Z ##[debug]loaded 19
2018-07-31T21:50:18.8436677Z ##[debug]Agent.ProxyUrl=undefined
2018-07-31T21:50:18.8438521Z ##[debug]Agent.CAInfo=undefined
2018-07-31T21:50:18.8439378Z ##[debug]Agent.ClientCert=undefined
2018-07-31T21:50:18.8440016Z ##[debug]Agent.SkipCertValidation=undefined
2018-07-31T21:50:18.8958477Z Failed to build OpenAPI document(s): {"stack":"TypeError: Cannot read property 'retrieveSecret' of undefined\n    at Object.getInput (D:\\a\\_tasks\\BuildOpenApiDocument_332865cc-aa31-450c-9888-2b2a51e1c5ac\\0.0.10\\node_modules\\vsts-task-lib\\task.js:156:26)\n    at readTaskConfiguration (D:\\a\\_tasks\\BuildOpenApiDocument_332865cc-aa31-450c-9888-2b2a51e1c5ac\\0.0.10\\Index.js:97:37)\n    at D:\\a\\_tasks\\BuildOpenApiDocument_332865cc-aa31-450c-9888-2b2a51e1c5ac\\0.0.10\\Index.js:161:33\n    at next (native)\n    at D:\\a\\_tasks\\BuildOpenApiDocument_332865cc-aa31-450c-9888-2b2a51e1c5ac\\0.0.10\\Index.js:12:71\n    at __awaiter (D:\\a\\_tasks\\BuildOpenApiDocument_332865cc-aa31-450c-9888-2b2a51e1c5ac\\0.0.10\\Index.js:8:12)\n    at run (D:\\a\\_tasks\\BuildOpenApiDocument_332865cc-aa31-450c-9888-2b2a51e1c5ac\\0.0.10\\Index.js:159:12)\n    at Object.<anonymous> (D:\\a\\_tasks\\BuildOpenApiDocument_332865cc-aa31-450c-9888-2b2a51e1c5ac\\0.0.10\\Index.js:218:1)\n    at Module._compile (module.js:570:32)\n    at Object.Module._extensions..js (module.js:579:10)","message":"Cannot read property 'retrieveSecret' of undefined"}
2018-07-31T21:50:18.8962054Z ##[debug]task result: Failed
2018-07-31T21:50:18.8964426Z ##[error]Cannot read property 'retrieveSecret' of undefined
2018-07-31T21:50:18.8964948Z ##[debug]Processed: ##vso[task.issue type=error;]Cannot read property 'retrieveSecret' of undefined
2018-07-31T21:50:18.8965716Z ##[debug]Processed: ##vso[task.complete result=Failed;]Cannot read property 'retrieveSecret' of undefined
2018-07-31T21:50:18.9015823Z ##[section]Finishing: Build OpenAPI Document: Swagger Samples
```

### Error from log above

```
{
  "stack": "TypeError: Cannot read property 'retrieveSecret' of undefined
    at Object.getInput (D:\\a\\_tasks\\BuildOpenApiDocument_332865cc-aa31-450c-9888-2b2a51e1c5ac\\0.0.8\\node_modules\\vsts-task-lib\\task.js:139:26)
    at readTaskConfiguration (D:\\a\\_tasks\\BuildOpenApiDocument_332865cc-aa31-450c-9888-2b2a51e1c5ac\\0.0.8\\Index.js:97:37)
    at D:\\a\\_tasks\\BuildOpenApiDocument_332865cc-aa31-450c-9888-2b2a51e1c5ac\\0.0.8\\Index.js:162:33
    at next (native)\n
    at D:\\a\\_tasks\\BuildOpenApiDocument_332865cc-aa31-450c-9888-2b2a51e1c5ac\\0.0.8\\Index.js:12:71
    at __awaiter (D:\\a\\_tasks\\BuildOpenApiDocument_332865cc-aa31-450c-9888-2b2a51e1c5ac\\0.0.8\\Index.js:8:12)
    at run (D:\\a\\_tasks\\BuildOpenApiDocument_332865cc-aa31-450c-9888-2b2a51e1c5ac\\0.0.8\\Index.js:159:12)
    at Object.<anonymous> (D:\\a\\_tasks\\BuildOpenApiDocument_332865cc-aa31-450c-9888-2b2a51e1c5ac\\0.0.8\\Index.js:220:1)
    at Module._compile (module.js:570:32)\n    at Object.Module._extensions..js (module.js:579:10)",
  "message": "Cannot read property 'retrieveSecret' of undefined"
}
```

**Comment by scott-lin** [comment]
Sorry, I realized I should have opened this in https://github.com/Microsoft/vsts-task-lib instead. Moving there.
