### ISSUE TITLE
[warning]Unable to get feature flag: TestExecution.EnableTranslationApi and  2018-08-15T09:12:25.3666141Z ##[warning]DiscoveryMessage : Exception occurred while instantiating discoverer : Exception has been thrown by the target of an invocation.

### ISSUE THREAD

**Issue by illumination7272** [Microsoft/vsts-tasks#8040]
until the 7 of august everything worked fine but after that this issue popped out #7970 after yesterdays i started getting these warnings:

 [warning]Unable to get feature flag: TestExecution.EnableTranslationApi and  2018-08-15T09:12:25.3666141Z 
[warning]DiscoveryMessage : Exception occurred while instantiating discoverer : Exception has been thrown by the target of an invocation. 

in vsts test run task.

Error log:
2018-08-15T09:12:27.0218950Z [RunStatistics]This execution slice with id '4534', received '145' testcases to execute out of which '0' is discovered.
2018-08-15T09:12:27.1105628Z ##[error]An exception occurred while executing the task. So the task is not executed. System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: No test assemblies found on the test machine matching the source filter criteria or no tests discovered matching test filter criteria. Verify that test assemblies are present on the machine and test filter criteria is correct.
2018-08-15T09:12:27.1107968Z    at Microsoft.VisualStudio.TestService.VstestAdapter.Execution.Run(ExecutionStateContext stateModdelContext, CancellationToken cancellationToken) in D:\V2.0\A1\_work\38\s\Ta\Agent\VS.TestService.VstestAdapter\Phases\Execution.cs:line 53
2018-08-15T09:12:27.1108815Z    at Microsoft.VisualStudio.TestService.VstestAdapter.ExecutionAndPublish.Run(ExecutionStateContext stateModelContext, CancellationToken cancellationToken) in D:\V2.0\A1\_work\38\s\Ta\Agent\VS.TestService.VstestAdapter\Phases\ExecuteAndPublish.cs:line 35
2018-08-15T09:12:27.1109348Z    at System.Threading.Tasks.Task`1.InnerInvoke()
2018-08-15T09:12:27.1109673Z    at System.Threading.Tasks.Task.Execute()
2018-08-15T09:12:27.1109969Z    --- End of inner exception stack trace ---
2018-08-15T09:12:27.1110527Z ---> (Inner Exception #0) System.InvalidOperationException: No test assemblies found on the test machine matching the source filter criteria or no tests discovered matching test filter criteria. Verify that test assemblies are present on the machine and test filter criteria is correct.
2018-08-15T09:12:27.1111271Z    at Microsoft.VisualStudio.TestService.VstestAdapter.Execution.Run(ExecutionStateContext stateModdelContext, CancellationToken cancellationToken) in D:\V2.0\A1\_work\38\s\Ta\Agent\VS.TestService.VstestAdapter\Phases\Execution.cs:line 53
2018-08-15T09:12:27.1112025Z    at Microsoft.VisualStudio.TestService.VstestAdapter.ExecutionAndPublish.Run(ExecutionStateContext stateModelContext, CancellationToken cancellationToken) in D:\V2.0\A1\_work\38\s\Ta\Agent\VS.TestService.VstestAdapter\Phases\ExecuteAndPublish.cs:line 35
2018-08-15T09:12:27.1114164Z    at System.Threading.Tasks.Task`1.InnerInvoke()
2018-08-15T09:12:27.1114494Z    at System.Threading.Tasks.Task.Execute()<---
2018-08-15T09:12:27.1114689Z 
2018-08-15T09:12:27.1118873Z ##[error]The slice of type 'Execution' is 'Aborted' because of the error : System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: No test assemblies found on the test machine matching the source filter criteria or no tests discovered matching test filter criteria. Verify that test assemblies are present on the machine and test filter criteria is correct.
2018-08-15T09:12:27.1120064Z    at Microsoft.VisualStudio.TestService.VstestAdapter.Execution.Run(ExecutionStateContext stateModdelContext, CancellationToken cancellationToken) in D:\V2.0\A1\_work\38\s\Ta\Agent\VS.TestService.VstestAdapter\Phases\Execution.cs:line 53
2018-08-15T09:12:27.1120536Z    at Microsoft.VisualStudio.TestService.VstestAdapter.ExecutionAndPublish.Run(ExecutionStateContext stateModelContext, CancellationToken cancellationToken) in D:\V2.0\A1\_work\38\s\Ta\Agent\VS.TestService.VstestAdapter\Phases\ExecuteAndPublish.cs:line 35
2018-08-15T09:12:27.1120854Z    at System.Threading.Tasks.Task`1.InnerInvoke()
2018-08-15T09:12:27.1121048Z    at System.Threading.Tasks.Task.Execute()
2018-08-15T09:12:27.1121220Z    --- End of inner exception stack trace ---
2018-08-15T09:12:27.1121540Z ---> (Inner Exception #0) System.InvalidOperationException: No test assemblies found on the test machine matching the source filter criteria or no tests discovered matching test filter criteria. Verify that test assemblies are present on the machine and test filter criteria is correct.
2018-08-15T09:12:27.1122406Z    at Microsoft.VisualStudio.TestService.VstestAdapter.Execution.Run(ExecutionStateContext stateModdelContext, CancellationToken cancellationToken) in D:\V2.0\A1\_work\38\s\Ta\Agent\VS.TestService.VstestAdapter\Phases\Execution.cs:line 53
2018-08-15T09:12:27.1122850Z    at Microsoft.VisualStudio.TestService.VstestAdapter.ExecutionAndPublish.Run(ExecutionStateContext stateModelContext, CancellationToken cancellationToken) in D:\V2.0\A1\_work\38\s\Ta\Agent\VS.TestService.VstestAdapter\Phases\ExecuteAndPublish.cs:line 35
2018-08-15T09:12:27.1123160Z    at System.Threading.Tasks.Task`1.InnerInvoke()
2018-08-15T09:12:27.1123339Z    at System.Threading.Tasks.Task.Execute()<---
2018-08-15T09:12:27.1123451Z 
2018-08-15T09:12:27.2523157Z ##[error]ExecutionStateResolver.SetNextPhase : Test Run Phase Results should not be null.
2018-08-15T09:12:37.4121638Z Test run '22279' is in 'Aborted' state with 'Total Tests' : 145 and 'Passed Tests' : 0.
2018-08-15T09:12:37.4122870Z ##[error]Test run is aborted. Logging details of the run logs.
2018-08-15T09:12:37.4809817Z ##[error]New test run created.
2018-08-15T09:12:37.4810726Z Test Run queued for Project Collection Build Service 
2018-08-15T09:12:37.4815960Z Test Run queued for Project Collection Build Service 
2018-08-15T09:12:37.4816406Z ##[error]Test execution started. Test run id : 22279
2018-08-15T09:12:37.4817343Z ##[error]One or more slices were aborted during execution. Try again by re-queuing the run.
2018-08-15T09:12:37.4818532Z ##[error]Error : One or more errors occurred.--->No test assemblies found on the test machine matching the source filter criteria or no tests discovered matching test filter criteria. Verify that test assemblies are present on the machine and test filter criteria is correct.
2018-08-15T09:12:37.4819643Z ##[error]Test run aborted. Test run id: 22279
2018-08-15T09:12:37.4820972Z ##[error]System.Exception: The test run was aborted, failing the task.

**Comment by acesiddhu** [comment]
@illumination7272 can u enable system.debug and share the build logs with us.

**Comment by prawalagarwal** [comment]
@illumination7272 please share your build logs with us at devops_tools@microsoft.com with system.debug set as true in build varialbles.

**Comment by prawalagarwal** [comment]
@illumination7272 are you still facing this issue? If yes, can you share the logs on the id mentioned in the last comment. Thanks!

**Comment by illumination7272** [comment]
Yeah i have contacted microsoft support team and they provided me with an answer
