### ISSUE TITLE
Publish Build Drop: Fails with 'No http handler was found for request type PUT'

### ISSUE THREAD

**Issue by JohannesDrexler** [Microsoft/vsts-tasks#8119]
## Environment
- Server - VSTS or TFS on-premises?
    vsts

- Agent - Hosted or Private: 
    private, win2012r2, agentversion 2.139.0

## Issue Description

Task fails when trying to upload a folder with binaries.

### Error logs (this is only the failing task, system.debug=true)

```
2018-08-23T06:53:22.3745748Z ##[debug]Evaluating condition for step: 'Publish Build Drop'
2018-08-23T06:53:22.3746690Z ##[debug]Evaluating: succeeded()
2018-08-23T06:53:22.3746973Z ##[debug]Evaluating succeeded:
2018-08-23T06:53:22.3747297Z ##[debug]=> True
2018-08-23T06:53:22.3747587Z ##[debug]Result: True
2018-08-23T06:53:22.3747881Z ##[section]Starting: Publish Build Drop
2018-08-23T06:53:22.3750917Z ==============================================================================
2018-08-23T06:53:22.3751058Z Task         : Publish Build Drop
2018-08-23T06:53:22.3751166Z Description  : Publish Build Drop
2018-08-23T06:53:22.3751314Z Version      : 0.138.0
2018-08-23T06:53:22.3751417Z Author       : Microsoft Corporation
2018-08-23T06:53:22.3751550Z Help         : Publish a local directory or file as a named drop artifact for the current build.
2018-08-23T06:53:22.3751690Z ==============================================================================
2018-08-23T06:53:22.7316403Z Uploading drop from E:\a\1\_w\179\b\binaries for build #15525
2018-08-23T06:53:24.2257983Z Information, 10 files to be processsed in 1 groups.
2018-08-23T06:53:24.6823533Z Information, 10 out of 10 files processed (Group: 1/1)
2018-08-23T06:53:24.6831899Z Information, Processed 10 files from E:\a\1\_w\179\b\binaries successfully.
2018-08-23T06:53:24.7370915Z Information, Uploading 10 files from directory E:\a\1\_w\179\b\binaries to Drop service.
2018-08-23T06:53:24.7420355Z Information, Uploaded 0 out of 115.781 bytes
2018-08-23T06:53:26.4979402Z ##[error]Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException: No http handler was found for request type 'PUT'
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupStoreHttpClient.PutDedupAsync(Guid locationId, DedupIdentifier dedupId, DedupCompressedBuffer chunkBuffer, KeepUntilBlobReference keepUntil, SummaryKeepUntilReceipt receipt, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupStoreHttpClient.PutNodeAndKeepUntilReferenceAsync(NodeDedupIdentifier dedupId, DedupCompressedBuffer chunkBuffer, KeepUntilBlobReference keepUntil, SummaryKeepUntilReceipt receipt, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupStoreClient.UploadSession.UploadNodeAsyncInternal(NodeDedupIdentifier nodeId, DedupNode node, FileStream file, String path, Nullable`1 offset, String indent, KeepUntilReceipt[] receipts, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupStoreClient.UploadSession.UploadNodeAsync(DedupNode node, String path, FileStream file, Nullable`1 offset, String indent, Boolean alreadyLocked, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.BlobStore.WebApi.BuildDropManager.PublishAsync(String sourceDirectory, BuildDropPublishOptions buildDropPublishOptions, String manifestFileOutputPath, CancellationToken cancellationToken)
   at Agent.Plugins.BuildDrop.BuildDropServer.UploadDropArtifactAsync(AgentTaskPluginExecutionContext context, Guid projectId, Int32 buildId, String name, String source, CancellationToken cancellationToken)
   at Agent.Plugins.BuildDrop.PublishBuildDropTask.ProcessCommandInternalAsync(AgentTaskPluginExecutionContext context, String targetPath, String artifactName, CancellationToken token)
   at Agent.Plugins.BuildDrop.BuildDropTaskPluginBase.RunAsync(AgentTaskPluginExecutionContext context, CancellationToken token)
   at Agent.PluginHost.Program.Main(String[] args)
2018-08-23T06:53:26.4981747Z ##[debug]Processed: ##vso[task.logissue type=error;]Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException: No http handler was found for request type 'PUT'%0D%0A   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)%0D%0A   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)%0D%0A   at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupStoreHttpClient.PutDedupAsync(Guid locationId, DedupIdentifier dedupId, DedupCompressedBuffer chunkBuffer, KeepUntilBlobReference keepUntil, SummaryKeepUntilReceipt receipt, CancellationToken cancellationToken)%0D%0A   at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupStoreHttpClient.PutNodeAndKeepUntilReferenceAsync(NodeDedupIdentifier dedupId, DedupCompressedBuffer chunkBuffer, KeepUntilBlobReference keepUntil, SummaryKeepUntilReceipt receipt, CancellationToken cancellationToken)%0D%0A   at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupStoreClient.UploadSession.UploadNodeAsyncInternal(NodeDedupIdentifier nodeId, DedupNode node, FileStream file, String path, Nullable`1 offset, String indent, KeepUntilReceipt[%5D receipts, CancellationToken cancellationToken)%0D%0A   at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupStoreClient.UploadSession.UploadNodeAsync(DedupNode node, String path, FileStream file, Nullable`1 offset, String indent, Boolean alreadyLocked, CancellationToken cancellationToken)%0D%0A   at Microsoft.VisualStudio.Services.BlobStore.WebApi.BuildDropManager.PublishAsync(String sourceDirectory, BuildDropPublishOptions buildDropPublishOptions, String manifestFileOutputPath, CancellationToken cancellationToken)%0D%0A   at Agent.Plugins.BuildDrop.BuildDropServer.UploadDropArtifactAsync(AgentTaskPluginExecutionContext context, Guid projectId, Int32 buildId, String name, String source, CancellationToken cancellationToken)%0D%0A   at Agent.Plugins.BuildDrop.PublishBuildDropTask.ProcessCommandInternalAsync(AgentTaskPluginExecutionContext context, String targetPath, String artifactName, CancellationToken token)%0D%0A   at Agent.Plugins.BuildDrop.BuildDropTaskPluginBase.RunAsync(AgentTaskPluginExecutionContext context, CancellationToken token)%0D%0A   at Agent.PluginHost.Program.Main(String[%5D args)
2018-08-23T06:53:26.4984395Z ##[debug]Processed: ##vso[task.complete result=Failed;]
2018-08-23T06:53:26.5054270Z ##[section]Finishing: Publish Build Drop

```

**Comment by praneetloke** [comment]
I have the same issue in a hosted agent as well. I don't have any binaries in the folder that is getting published to the drop site. It is just the distribution files for a SPA.

I see that this issue isn't assigned to anyone yet. Can someone please take a look at this?

**Comment by jachin84** [comment]
I have the same issue on a self-hosted agent.

**Comment by csinge** [comment]
Same, Ubuntu 1604 agent

**Comment by jerickmsft** [comment]
Looking into this ASAP.

**Comment by jerickmsft** [comment]
This should be resolved now.  The impact should have been limited to orgs hosted in Australia and my logs confirm this.  Do let me know if you have seen otherwise.  Apologies both for the disruption and the delayed response.

**Comment by praneetloke** [comment]
@jerickmsft I sent you an email shown on your GH profile.

**Comment by jachin84** [comment]
@jerickmsft Did you check the feature flags for the Release pipeline? I'm not able to consume any artifacts that are published via the new publish pipelines artifact. I'm an Australian customer.

**Comment by jachin84** [comment]
I'm seeing the following:
![image](https://user-images.githubusercontent.com/2740855/50270463-61d0ae80-047d-11e9-9961-a3d9673e27d1.png)

When running the realease pipeline nothing is downloaded to the agent either.

**Comment by mitchdenny** [comment]
Assumig you are using Pipeline Artifacts then this is expected right now. we are currently working on an enhancement to support better drill down into Pipeline Artifiact-type artifacts. Its on of the reasons it is still in preview. Should roll out in the next deployment.

**Comment by mitchdenny** [comment]
The fix for the pipeline artifacts not downloading is also being fixed in an upcoming deployment (in the new year at this stage). For now you can manually insert the Download Pipeline Artifact task. It automatically injects in some circumstances but we don't have it covered for all scenarios.

**Comment by jachin84** [comment]
Weird as this was working fine. I'll try adding a manual download step to see what happens. Even with this being preview it's way faster than the previous approach.

**Comment by mitchdenny** [comment]
Yep. Our main focus for the preview was landing some tech we’ve been using inside Microsoft for a while. Now it’s just a matter of filing off the rough edges ;)
