### ISSUE TITLE
VsTestV2 fails to upload test results: XmlException - Root element is missing

### ISSUE THREAD

**Issue by bergmeister** [Microsoft/vsts-tasks#8187]
## Environment

- Server : VSTS 
- Release log: https://rcss-02-willistowerswatson.visualstudio.com/Unify/_releaseProgress?releaseId=10400&environmentId=10798&_a=release-environment-logs
- Agent : Private (run in interactive mode)
- OS: Windows 10 - 1803
- Agent version 2.134.2

## Issue Description

[Include task name(s), screenshots and any other relevant details]

### Error logs

```
2018-08-28T17:55:50.2119762Z ##[section]Starting: VsTest - testAssemblies
2018-08-28T17:55:50.2130119Z ==============================================================================
2018-08-28T17:55:50.2130358Z Task         : Visual Studio Test
2018-08-28T17:55:50.2130754Z Description  : Run unit and functional tests (Selenium, Appium, Coded UI test, etc.) using the Visual Studio Test (VsTest) runner. Test frameworks that have a Visual Studio test adapter such as MsTest, xUnit, NUnit, Chutzpah (for JavaScript tests using QUnit, Mocha and Jasmine), etc. can be run. Tests can be distributed on multiple agents using this task (version 2).
2018-08-28T17:55:50.2131517Z Version      : 2.139.9
2018-08-28T17:55:50.2132659Z Author       : Microsoft Corporation
2018-08-28T17:55:50.2133281Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=835764)
2018-08-28T17:55:50.2133575Z ==============================================================================
2018-08-28T17:55:54.4544580Z SystemVssConnection exists true
2018-08-28T17:55:54.5876329Z SystemVssConnection exists true
2018-08-28T17:55:54.6454389Z Running tests using vstest.console.exe runner.
2018-08-28T17:55:54.6454651Z ======================================================
2018-08-28T17:55:54.6455021Z Test selector : Test assemblies
2018-08-28T17:55:54.6455361Z Test filter criteria : FullyQualifiedName~TestsRequiringBrowserAndDesigner
2018-08-28T17:55:54.6518624Z Search folder : \\E20-IX-UNWB007Q\Unify Ranorex for vNext\Ranorex Test Projects\TW.Gem.RanorexTests
2018-08-28T17:55:54.9268121Z Run settings file : undefined
2018-08-28T17:55:54.9268563Z Run in parallel : false
2018-08-28T17:55:54.9268805Z Run in isolation : false
2018-08-28T17:55:54.9269037Z Path to custom adapters : null
2018-08-28T17:55:54.9269615Z Other console options : null
2018-08-28T17:55:54.9270035Z Code coverage enabled : false
2018-08-28T17:55:54.9270223Z Diagnostics enabled : false
2018-08-28T17:55:54.9272421Z Rerun failed tests: true
2018-08-28T17:55:54.9273735Z Rerun maximum failed test case limit: 10
2018-08-28T17:55:54.9274263Z Rerun maximum attempts: 2
2018-08-28T17:55:54.9275080Z SystemVssConnection exists true
2018-08-28T17:55:54.9279286Z Run the tests locally using vstest.console.exe
2018-08-28T17:55:54.9279601Z ========================================================
2018-08-28T17:55:55.9382986Z Source filter: **\*RanorexTests.dll
2018-08-28T17:55:57.3708808Z SystemVssConnection exists true
2018-08-28T17:55:57.6754373Z [command]D:\_Builds\E20-IX-UNWB007Q.01\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.139.9\Modules\DTAExecutionHost.exe --inputFile D:\_Builds\E20-IX-UNWB007Q.01\_temp\input_9da45830-aaeb-11e8-9822-012fa4373d2e.json
2018-08-28T17:55:57.7449117Z ======================================================
2018-08-28T17:55:57.7597403Z (node:8408) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): ReferenceError: Q is not defined
2018-08-28T17:55:57.8867141Z ##########################################################################
2018-08-28T17:55:58.6253990Z Starting TestExecution Model...
2018-08-28T17:55:59.9633118Z Updated Run Settings:
2018-08-28T17:55:59.9633781Z <RunSettings>
2018-08-28T17:55:59.9642584Z   <RunConfiguration>
2018-08-28T17:55:59.9643281Z     <ResultsDirectory>D:\_Builds\E20-IX-UNWB007Q.01\_temp\TR_bdd91290-35a4-4d0c-bc3d-3ff8e18fa6f0</ResultsDirectory>
2018-08-28T17:55:59.9643939Z   </RunConfiguration>
2018-08-28T17:55:59.9644511Z </RunSettings>
2018-08-28T17:55:59.9792999Z **************** Starting test execution *********************
2018-08-28T17:56:00.0227131Z [command]D:\_Builds\E20-IX-UNWB007Q.01\_tool\VsTest\15.8.0\x64\tools\net451\Common7\IDE\Extensions\TestPlatform\vstest.console.exe "@C:\Users\sveAzRCSTST\AppData\Local\Temp\tmpC418.tmp"
2018-08-28T17:56:00.3288167Z Microsoft (R) Test Execution Command Line Tool Version 15.8.0
2018-08-28T17:56:00.3288962Z Copyright (c) Microsoft Corporation.  All rights reserved.
2018-08-28T17:56:00.3667236Z vstest.console.exe "\\E20-IX-UNWB007Q\Unify Ranorex for vNext\Ranorex Test Projects\TW.Gem.RanorexTests\TW.Gem.RanorexTests.dll"
2018-08-28T17:56:00.3668803Z /TestCaseFilter:"FullyQualifiedName~TestsRequiringBrowserAndDesigner"
2018-08-28T17:56:00.3669760Z /Settings:"C:\Users\sveAzRCSTST\AppData\Local\Temp\tmpC3E8.runsettings"
2018-08-28T17:56:00.3670186Z /Logger:"trx"
2018-08-28T17:56:00.3672144Z /TestAdapterPath:"\\E20-IX-UNWB007Q\Unify Ranorex for vNext\Ranorex Test Projects\TW.Gem.RanorexTests"
...

 ##[error]Error occurred while publishing test results : System.Xml.XmlException: Root element is missing.
2018-08-29T08:31:00.7086310Z    at System.Xml.XmlTextReaderImpl.Throw(Exception e)
2018-08-29T08:31:00.7087595Z    at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
2018-08-29T08:31:00.7087919Z    at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
2018-08-29T08:31:00.7089226Z    at System.Xml.XmlDocument.Load(XmlReader reader)
2018-08-29T08:31:00.7089566Z    at System.Xml.XmlDocument.LoadXml(String xml)
2018-08-29T08:31:00.7090012Z    at Microsoft.TeamFoundation.TestClient.PublishTestResults.TrxResultParser.CreateXmlDocumentFromResultFile(String filePath) in D:\V2.0\A2\_work\37\s\Ta\Tasks\PublishTestResults\Parser\TrxResultParser.cs:line 121
2018-08-29T08:31:00.7090638Z    at Microsoft.TeamFoundation.TestClient.PublishTestResults.TrxResultParser.ParseTestResultFile(TestRunContext runContext, String filePath) in D:\V2.0\A2\_work\37\s\Ta\Tasks\PublishTestResults\Parser\TrxResultParser.cs:line 65
2018-08-29T08:31:00.7091126Z    at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
2018-08-29T08:31:00.7091483Z    at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
2018-08-29T08:31:00.7091982Z    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
2018-08-29T08:31:00.7092462Z    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
2018-08-29T08:31:00.7092864Z    at Microsoft.TeamFoundation.TestClient.PublishTestResults.TrxResultParser.ParseTestResultFiles(TestRunContext runContext, IList`1 resultFilePaths) in D:\V2.0\A2\_work\37\s\Ta\Tasks\PublishTestResults\Parser\TrxResultParser.cs:line 48
2018-08-29T08:31:00.7093592Z    at Microsoft.VisualStudio.TestService.TcmTestResultPublisher.TrxTestResultPublisher.ParseTrx(TestRunContext testRunContext, IList`1 trxFilePaths) in D:\V2.0\A2\_work\37\s\Ta\Agent\VS.TestService.TcmTestResultPublisher\TrxTestRunPublisher.cs:line 154
2018-08-29T08:31:00.7094151Z    at Microsoft.VisualStudio.TestService.TcmTestResultPublisher.TrxTestResultPublisher.PublishTestRunResults(TestRunModel testRunModel) in D:\V2.0\A2\_work\37\s\Ta\Agent\VS.TestService.TcmTestResultPublisher\TrxTestRunPublisher.cs:line 31
2018-08-29T08:31:00.7094668Z    at MS.VS.TestService.VstestConsoleAdapter.PublishTestResult.CreateOrUpdateTestRun(TestRunModel testRunModel) in D:\V2.0\A2\_work\37\s\Ta\Agent\VS.TestService.VstestConsoleAdapter\PublishTestResult.cs:line 74
2018-08-29T08:31:00.7095166Z    at MS.VS.TestService.VstestConsoleAdapter.PublishTestResult.Publish(VstestConsoleRunContext testRunContext) in D:\V2.0\A2\_work\37\s\Ta\Agent\VS.TestService.VstestConsoleAdapter\PublishTestResult.cs:line 53
```

**Comment by prawalagarwal** [comment]
@bergmeister Can you provide the trx file which caused this? You can send it to devops_tools@microsoft.com

**Comment by bergmeister** [comment]
@prawalagarwal The file does not exist on the machine any more because another release (from a different release definition) ran on the same agent, which seems to have deleted the trx file that was supposed to be in ` D:\_Builds\E20-IX-UNWB007Q.01\_temp\TR_bdd91290-35a4-4d0c-bc3d-3ff8e18fa6f0\sveAzRCSTST_E20-IX-UNWB007Q_2018-08-28_19_01_23.trx`

**Comment by bergmeister** [comment]
@prawalagarwal Thanks for the info. Although it is a UNC path, it is just a local file share. I will try changing it to a local path similar to your example though and will see if it improves (note that the issue is sporadic and more likely to happen in long test runs over 10 hours)

**Comment by prawalagarwal** [comment]
@bergmeister Yes I noticed from the logs that your tests ran for a long time. Not sure if that is creating a buggy trx file or if it is some other issue. Will need to have a look at the file to determine the same. Please let us know whenever your have the trx. Thanks!

**Comment by ShreyasRmsft** [comment]
@bergmeister any updates here?

**Comment by bergmeister** [comment]
@ShreyasRmsft I set the `system.debug` variable to true and on the next run I had the same error but the error message also included a hint that the system is running out of space (the working directory of the agent is on a separate, relatively small drive of 16 GB size) but I am not sure if this is the same error or a new error as it might have been caused by the verbose log taking up more space. I doubled the disk space and will continue to monitor
```
2018-08-31T04:51:20.9012355Z ##[error]Test Run Failed.
2018-08-31T04:51:20.9093120Z ##[debug]Processed: ##vso[task.logissue type=error;]Test Run Failed.
2018-08-31T04:51:20.9094711Z ##[error]Unhandled Exception: System.IO.IOException: There is not enough space on the disk.
2018-08-31T04:51:20.9095708Z ##[debug]Processed: ##vso[task.logissue type=error;]Unhandled Exception: System.IO.IOException: There is not enough space on the disk.
2018-08-31T04:51:20.9096220Z ##[error]   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
2018-08-31T04:51:20.9096672Z ##[debug]Processed: ##vso[task.logissue type=error;]   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
2018-08-31T04:51:20.9097167Z ##[error]   at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
2018-08-31T04:51:20.9097644Z ##[debug]Processed: ##vso[task.logissue type=error;]   at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
2018-08-31T04:51:20.9098138Z ##[error]   at System.IO.FileStream.FlushWrite(Boolean calledFromFinalizer)
2018-08-31T04:51:20.9098582Z ##[debug]Processed: ##vso[task.logissue type=error;]   at System.IO.FileStream.FlushWrite(Boolean calledFromFinalizer)
2018-08-31T04:51:20.9099388Z ##[error]   at System.IO.FileStream.Dispose(Boolean disposing)
2018-08-31T04:51:20.9099840Z ##[debug]Processed: ##vso[task.logissue type=error;]   at System.IO.FileStream.Dispose(Boolean disposing)
2018-08-31T04:51:20.9100768Z ##[error]   at System.IO.FileStream.Finalize()
2018-08-31T04:51:20.9101566Z ##[debug]Processed: ##vso[task.logissue type=error;]   at System.IO.FileStream.Finalize()
2018-08-31T04:51:32.8589023Z ##[debug]Exited vstest.console.exe with code 1.
2018-08-31T04:51:32.8678091Z ##[debug]PERF: ExecuteVsTestPhase.InvokeVSTest: took 121698271.2294 ms
2018-08-31T04:51:32.8681856Z ##[debug]Exited vstest.console.exe with code 1
2018-08-31T04:51:32.8682363Z **************** Completed test execution *********************
2018-08-31T04:51:32.8683050Z ##[debug]Current Phase: MS.VS.TestService.VstestConsoleAdapter.ExecuteVsTestPhase Phase Result: MS.VS.TestService.VstestConsoleAdapter.ExecutionVsTestPhaseResults
2018-08-31T04:51:32.8683737Z ##[debug]PERF WARNING: Running the phase MS.VS.TestService.VstestConsoleAdapter.ExecuteVsTestPhase: took 121698281.2196 ms
2018-08-31T04:51:32.8685266Z ##[debug]Current phase: MS.VS.TestService.VstestConsoleAdapter.PublishTestResultPhase
2018-08-31T04:51:32.8686943Z ##[debug]Starting Publish Test Results: TIA: False
2018-08-31T04:51:32.8786171Z ##[debug]Starting PublishTestResult from Result Files
2018-08-31T04:51:33.1147505Z Test results files: D:\_Builds\E20-IX-UNWB007Q.01\_temp\TR_53269337-6fdc-44cb-8bba-d867eab180b2\sveAzRCSTST_E20-IX-UNWB007Q_2018-08-29_20_11_41.trx
2018-08-31T04:51:33.1526328Z ##[debug]Entering ParseTestResultFiles
2018-08-31T04:51:33.1526964Z ##[debug]runContext.Platform is null
2018-08-31T04:51:33.1527355Z ##[debug]runContext.Configuration is null
2018-08-31T04:51:33.1863897Z ##[debug]Reading test results from file 'D:\_Builds\E20-IX-UNWB007Q.01\_temp\TR_53269337-6fdc-44cb-8bba-d867eab180b2\sveAzRCSTST_E20-IX-UNWB007Q_2018-08-29_20_11_41.trx'.
2018-08-31T04:51:33.1910416Z ##[debug]Completed PublishTestResult
2018-08-31T04:51:33.2133525Z ##[debug]PERF: PublishTestResultPhase.Publish: took 322.5289 ms
2018-08-31T04:51:33.2133926Z ##[debug]Completed Publish Test Results.
2018-08-31T04:51:33.2134320Z ##[debug]Current Phase: MS.VS.TestService.VstestConsoleAdapter.PublishTestResultPhase Phase Result: MS.VS.TestService.VstestConsoleAdapter.PublishTestResultPhaseResults
2018-08-31T04:51:33.7530126Z ##[error]Error occurred while publishing test results : System.Xml.XmlException: Root element is missing.
2018-08-31T04:51:33.7531441Z ##[debug]Processed: ##vso[task.logissue type=error;]Error occurred while publishing test results : System.Xml.XmlException: Root element is missing.
2018-08-31T04:51:33.7532933Z    at System.Xml.XmlTextReaderImpl.Throw(Exception e)
2018-08-31T04:51:33.8156821Z    at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
2018-08-31T04:51:33.8165110Z    at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
2018-08-31T04:51:33.8168290Z    at System.Xml.XmlDocument.Load(XmlReader reader)
2018-08-31T04:51:33.8170417Z    at System.Xml.XmlDocument.LoadXml(String xml)
2018-08-31T04:51:33.8171144Z    at Microsoft.TeamFoundation.TestClient.PublishTestResults.TrxResultParser.CreateXmlDocumentFromResultFile(String filePath) in D:\V2.0\A2\_work\37\s\Ta\Tasks\PublishTestResults\Parser\TrxResultParser.cs:line 121
2018-08-31T04:51:33.8172268Z    at Microsoft.TeamFoundation.TestClient.PublishTestResults.TrxResultParser.ParseTestResultFile(TestRunContext runContext, String filePath) in D:\V2.0\A2\_work\37\s\Ta\Tasks\PublishTestResults\Parser\TrxResultParser.cs:line 65
2018-08-31T04:51:33.8172924Z    at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
2018-08-31T04:51:33.8173424Z    at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
2018-08-31T04:51:33.8173931Z    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
2018-08-31T04:51:33.8174401Z    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
2018-08-31T04:51:33.8175214Z    at Microsoft.TeamFoundation.TestClient.PublishTestResults.TrxResultParser.ParseTestResultFiles(TestRunContext runContext, IList`1 resultFilePaths) in D:\V2.0\A2\_work\37\s\Ta\Tasks\PublishTestResults\Parser\TrxResultParser.cs:line 48
2018-08-31T04:51:33.8176170Z    at Microsoft.VisualStudio.TestService.TcmTestResultPublisher.TrxTestResultPublisher.ParseTrx(TestRunContext testRunContext, IList`1 trxFilePaths) in D:\V2.0\A2\_work\37\s\Ta\Agent\VS.TestService.TcmTestResultPublisher\TrxTestRunPublisher.cs:line 154
2018-08-31T04:51:33.8176768Z    at Microsoft.VisualStudio.TestService.TcmTestResultPublisher.TrxTestResultPublisher.PublishTestRunResults(TestRunModel testRunModel) in D:\V2.0\A2\_work\37\s\Ta\Agent\VS.TestService.TcmTestResultPublisher\TrxTestRunPublisher.cs:line 31
2018-08-31T04:51:33.8177527Z    at MS.VS.TestService.VstestConsoleAdapter.PublishTestResult.CreateOrUpdateTestRun(TestRunModel testRunModel) in D:\V2.0\A2\_work\37\s\Ta\Agent\VS.TestService.VstestConsoleAdapter\PublishTestResult.cs:line 74
2018-08-31T04:51:33.8178849Z    at MS.VS.TestService.VstestConsoleAdapter.PublishTestResult.Publish(VstestConsoleRunContext testRunContext) in D:\V2.0\A2\_work\37\s\Ta\Agent\VS.TestService.VstestConsoleAdapter\PublishTestResult.cs:line 53
2018-08-31T04:51:33.8179893Z ##[debug]PERF: Running the phase MS.VS.TestService.VstestConsoleAdapter.PublishTestResultPhase: took 920.3159 ms
2018-08-31T04:51:33.8180584Z ##[debug]Current phase: MS.VS.TestService.VstestConsoleAdapter.CleanupPhase
2018-08-31T04:51:33.8181434Z ##[debug]Started CleanupPhase 0
2018-08-31T04:51:33.8244290Z ##[debug]Looking for diag files with pattern Attempt*cd867b0f-c555-4c90-a156-ad403b73478a*.diag
2018-08-31T04:51:33.8248301Z ##[debug]Processed: ##vso[task.uploadfile]D:\_Builds\E20-IX-UNWB007Q.01\_temp\Attempt-2_cd867b0f-c555-4c90-a156-ad403b73478a.diag
2018-08-31T04:51:33.8249056Z ##[error]Skipping marking test run as complete as test run id 0 is invalid.
2018-08-31T04:51:33.8249565Z ##[debug]Processed: ##vso[task.logissue type=error;]Skipping marking test run as complete as test run id 0 is invalid.
2018-08-31T04:51:34.5230847Z ##[debug]Current Phase: MS.VS.TestService.VstestConsoleAdapter.CleanupPhase Phase Result: MS.VS.TestService.VstestConsoleAdapter.CleanupPhaseResults
2018-08-31T04:51:34.5585400Z ##[debug]PERF: Running the phase MS.VS.TestService.VstestConsoleAdapter.CleanupPhase: took 568.448 ms
2018-08-31T04:51:34.5764835Z ##[debug]Completed the ExecutionStateModel
2018-08-31T04:51:34.5827106Z Completed TestExecution Model...
2018-08-31T04:51:34.5828183Z ##[debug]rc:1
2018-08-31T04:51:34.5828546Z ##[debug]success:false
2018-08-31T04:51:34.5829039Z ##[warning]Vstest failed with error. Check logs for failures. There might be failed tests.
```

**Comment by prawalagarwal** [comment]
@bergmeister for now we don't need the debug logs. Just the trx file will do. As I mentioned in a previous comment, you can execute this on any machine using the vstest console. You can even run fewer tests by using test categories and test filter with the command line.

**Comment by ShreyasRmsft** [comment]
@bergmeister can you please provide the trx file as prawal has requested?

**Comment by bergmeister** [comment]
@ShreyasRmsft As I said, I could not retrieve the trx file because the tasks saves the file to the agent's temp directory, which gets cleaned for every release. I will therefore have to wait for when it occurs next and stop any subsequent releases. I am on annual leave at the moment, therefore please bear with me for the moment.

**Comment by ShreyasRmsft** [comment]
@bergmeister you can provide a runsettings with a custom results directory folder and make it save the trx in a convenient location

**Comment by kaadhina** [comment]
@bergmeister are you unblocked on this? If not, can you please share the trx as mentioned above?
