### ISSUE TITLE
Error while packing VSTS Task

### ISSUE THREAD

**Issue by abbgrade** [Microsoft/vsts-tasks#8225]
## Environment
Development System, with Windows10 with the latest updates and Visual Studio 2017 and Visual Studio Code.

## Issue Description

When i want to create the package of vsts-tasks for a specific task the directory `vsts-tasks\_package\milestone-layout` is missing. I ran the build task before, that exited without a error.
Unfortunately the explanation in [the contributing doc](https://github.com/Microsoft/vsts-tasks/blob/master/docs/contribute.md#build-a-specific-task-recommended) did not help in this case.

### Error logs

```
> Executing task: node make.js package --task PowerShellV2 <


> prepending PATH C:\Users\s.kampmann\source\repos\vsts-tasks\node_modules\.bin

------------------------------------------------------------
Starting package process...
------------------------------------------------------------

> Creating NuGet package per task

> Creating task zips folder

> Creating artifacts folder

> Zipping task folders
fs.js:904
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir 'C:\Users\s.kampmann\source\repos\vsts-tasks\_package\milestone-layout'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.createNugetPackagePerTask (C:\Users\s.kampmann\source\repos\vsts-tasks\make-util.js:1277:8)
    at Function.target.package (C:\Users\s.kampmann\source\repos\vsts-tasks\make.js:492:10)
    at Object.global.target.(anonymous function) [as package] (C:\Users\s.kampmann\source\repos\vsts-tasks\node_modules\shelljs\make.js:28:26)
    at C:\Users\s.kampmann\source\repos\vsts-tasks\node_modules\shelljs\make.js:38:27
    at Array.forEach (<anonymous>)
    at Timeout._onTimeout (C:\Users\s.kampmann\source\repos\vsts-tasks\node_modules\shelljs\make.js:36:10)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
Der Terminalprozess wurde mit folgendem Exitcode beendet: 1
```

**Comment by bryanmacfarlane** [comment]
Can you outline why you're trying to create a package?  What's your end goal?

**Comment by bryanmacfarlane** [comment]
per the contribution guide: This is only used for TFS internal engineering

**Comment by bryanmacfarlane** [comment]
https://github.com/Microsoft/vsts-tasks/commit/ae6bc73951d80e338ba76101e26e9a6de23fcb2c

**Comment by abbgrade** [comment]
I would like to have a task to deploy PowerBI Reports.

**Comment by bryanmacfarlane** [comment]
vsts-task-lib repo covers how to create your own task.  it has a step by step guide.
