### ISSUE TITLE
Visual Studio Test task silently passes while exception was thrown during the test

### ISSUE THREAD

**Issue by hengjiaqi** [Microsoft/vsts-tasks#8363]
Hi folks,

Seems like the VS Test task is not able to report the exception. Not sure if there is anything missing from my side. Thanks in advance!

## Environment
- Server - VSTS
    - If using VSTS, provide the account name, team project name, build definition name/build number: 

account name: msasg
project name: Bing_and_IPG
build definition name: EKG Rolling Build
build number: 1.0.1809.19020

- Agent - Hosted: 
    - If using Hosted agent, provide agent queue name:
Hosted VS2017

## Issue Description

If you check the task named "Unit Integration Tests", exception was thrown, while the task was still marked as successful.

### Task logs

NUnit Adapter 3.10.0.21: Test execution started
2018-09-19T18:44:57.9516585Z Exception System.IO.FileNotFoundException, Exception thrown executing tests
2018-09-19T18:44:57.9517615Z Could not load file or assembly 'System.Xml.XPath.XmlDocument, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
2018-09-19T18:44:57.9519261Z    at NUnit.VisualStudio.TestAdapter.NUnit3TestExecutor.RunAssembly(String assemblyPath, TestFilter filter)
2018-09-19T18:44:57.9520853Z    at NUnit.VisualStudio.TestAdapter.NUnit3TestExecutor.RunTests(IEnumerable`1 sources, IRunContext runContext, IFrameworkHandle frameworkHandle) in D:\repos\nunit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnit3TestExecutor.cs:line 97

**Comment by ShreyasRmsft** [comment]
@hengjiaqi the issues template clearly asks for the entire logs zip with system.debug set to true in the build definition.

Please provide those. Also verify if when running locally with vstest.console.exe and the same error occurs whether the test run is marked as failed or not.

**Comment by hengjiaqi** [comment]
@ShreyasRmsft , thanks for the response, please refer to the log with system.debug set to true. I don't see the same error when running locally.

[log_15_3360757.zip](https://github.com/Microsoft/vsts-tasks/files/2403404/log_15_3360757.zip)

**Comment by ShreyasRmsft** [comment]
@hengjiaqi please provide the complete zip file you get when you click download all logs. There are additional files we upload apart from the task logs that help with diagnosing issues on the testplatform side and these are present in the complete zip.

**Comment by hengjiaqi** [comment]
[log_9_3367396.zip](https://github.com/Microsoft/vsts-tasks/files/2406564/log_9_3367396.zip)
@ShreyasRmsft  Please refer to the entire log of the build definition.

**Comment by hengjiaqi** [comment]
@ShreyasRmsft Any updates?
