### ISSUE TITLE
Service Fabric Application Deploy Error

### ISSUE THREAD

**Issue by washraf** [Microsoft/vsts-tasks#8409]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - Azure Pipelines or TFS on-premises?
    **Azure Pipeline**
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
**accountName: moveitgate
team project name: testicide 
Build: 20180925.1**

- Agent - Hosted or Private: 
   **Hosted**
    - If using Hosted agent, provide agent queue name:
    **Hosted VS2017**
    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description
**The Deployment Fails for no apparent reason (First deployment)**
[Include task name(s), screenshots and any other relevant details]

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

### Error logs

2018-09-25T13:58:35.1869996Z ##[section]Starting: Deploy Service Fabric Application
2018-09-25T13:58:35.1877857Z ==============================================================================
2018-09-25T13:58:35.1878140Z Task         : Service Fabric Application Deployment
2018-09-25T13:58:35.1878371Z Description  : Deploy a Service Fabric application to a cluster.
2018-09-25T13:58:35.1878586Z Version      : 1.7.21
2018-09-25T13:58:35.1878774Z Author       : Microsoft Corporation
2018-09-25T13:58:35.1879000Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=820528)
2018-09-25T13:58:35.1879280Z ==============================================================================
2018-09-25T13:58:38.9711846Z Searching for path: D:\a\r1\a\**\drop\projectartifacts\**\PublishProfiles\Cloud.xml
2018-09-25T13:58:39.4006269Z Found path: D:\a\r1\a\_Testicide-Azure Service Fabric application-CI\drop\projectartifacts\src\Testicide\PublishProfiles\Cloud.xml
2018-09-25T13:58:39.5203507Z Searching for path: D:\a\r1\a\**\drop\applicationpackage
2018-09-25T13:58:39.8763970Z Found path: D:\a\r1\a\_Testicide-Azure Service Fabric application-CI\drop\applicationpackage
2018-09-25T14:00:44.2088486Z Service fabric SDK version: 3.2.162.9494.
2018-09-25T14:00:44.9193482Z ##[error]One or more errors occurred.
2018-09-25T14:00:44.9679357Z ##[section]Finishing: Deploy Service Fabric Application

**Comment by bishal-pdMSFT** [comment]
@washraf can you please provide details about the error. You can enable debug logging by setting a release variable 'system.debug' set to 'true'.
Does it happen only for first deployment? Does next attempt succeed?

**Comment by washraf** [comment]
2018-09-26T17:05:47.6794824Z ##[debug]Evaluating condition for step: 'Deploy Service Fabric Application'
2018-09-26T17:05:47.6796045Z ##[debug]Evaluating: succeeded()
2018-09-26T17:05:47.6796397Z ##[debug]Evaluating succeeded:
2018-09-26T17:05:47.6796861Z ##[debug]=> True
2018-09-26T17:05:47.6797292Z ##[debug]Result: True
2018-09-26T17:05:47.6797734Z ##[section]Starting: Deploy Service Fabric Application
2018-09-26T17:05:47.6805177Z ==============================================================================
2018-09-26T17:05:47.6805408Z Task         : Service Fabric Application Deployment
2018-09-26T17:05:47.6805621Z Description  : Deploy a Service Fabric application to a cluster.
2018-09-26T17:05:47.6805794Z Version      : 1.7.21
2018-09-26T17:05:47.6805965Z Author       : Microsoft Corporation
2018-09-26T17:05:47.6806155Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=820528)
2018-09-26T17:05:47.6806367Z ==============================================================================
2018-09-26T17:05:49.2459610Z ##[debug]VstsTaskSdk 0.8.2 commit 
2018-09-26T17:05:50.0557328Z ##[debug]Entering D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.21\deploy.ps1.
2018-09-26T17:05:50.0982863Z ##[debug]Loading resource strings from: D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.21\task.json
2018-09-26T17:05:50.3303903Z ##[debug]Loaded 79 strings.
2018-09-26T17:05:50.3434824Z ##[debug]SYSTEM_CULTURE: 'en-US'
2018-09-26T17:05:50.3436474Z ##[debug]Loading resource strings from: D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.21\Strings\resources.resjson\en-US\resources.resjson
2018-09-26T17:05:50.5742630Z ##[debug]Loaded 79 strings.
2018-09-26T17:05:50.5808952Z ##[debug]Loading module from path 'D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.21\ps_modules\ServiceFabricHelpers\ServiceFabricHelpers.psm1'.
2018-09-26T17:05:50.5909730Z ##[debug]Loading resource strings from: D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.21\ps_modules\ServiceFabricHelpers\module.json
2018-09-26T17:05:50.6227585Z ##[debug]Loaded 15 strings.
2018-09-26T17:05:50.6258697Z ##[debug]SYSTEM_CULTURE: 'en-US'
2018-09-26T17:05:50.6285019Z ##[debug]Loading resource strings from: D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.21\ps_modules\ServiceFabricHelpers\Strings\resources.resjson\en-US\resources.resjson
2018-09-26T17:05:50.6652363Z ##[debug]Loaded 15 strings.
2018-09-26T17:05:50.6880420Z ##[debug]Entering Find-VstsFiles.
2018-09-26T17:05:50.7283379Z ##[debug] LiteralDirectory: 'D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.21\ps_modules\ServiceFabricHelpers'
2018-09-26T17:05:50.7303930Z ##[debug] LegacyPattern: '*.ps1'
2018-09-26T17:05:51.5974614Z ##[debug]Entering Get-MatchingItems.
2018-09-26T17:05:51.6022136Z ##[debug] IncludePatterns: 'D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.21\ps_modules\ServiceFabricHelpers\*.ps1'
2018-09-26T17:05:51.6086488Z ##[debug] ExcludePatterns: ''
2018-09-26T17:05:51.6137681Z ##[debug] IncludeFiles: 'True'
2018-09-26T17:05:51.6162763Z ##[debug] IncludeDirectories: 'False'
2018-09-26T17:05:51.6182347Z ##[debug] Force: 'False'
2018-09-26T17:05:52.2203148Z ##[debug]Paths: D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.21\ps_modules\ServiceFabricHelpers\
2018-09-26T17:05:52.2229431Z ##[debug] CommonHelpers.ps1
2018-09-26T17:05:52.2230491Z ##[debug] Connect-ServiceFabricClusterFromServiceEndpoint.ps1
2018-09-26T17:05:52.2230926Z ##[debug] Get-ServiceFabricEncryptedText.ps1
2018-09-26T17:05:52.2231433Z ##[debug] SFOperations.ps1
2018-09-26T17:05:52.2255948Z ##[debug]Leaving Get-MatchingItems.
2018-09-26T17:05:52.2437269Z ##[debug]Total found: 4
2018-09-26T17:05:52.2458829Z ##[debug]Leaving Find-VstsFiles.
2018-09-26T17:05:52.2478635Z ##[debug]Exporting function 'Connect-ServiceFabricClusterFromServiceEndpoint'.
2018-09-26T17:05:52.2498446Z ##[debug]Exporting function 'Remove-ClientCertificate'.
2018-09-26T17:05:52.4034566Z ##[debug]Exporting function 'Get-ServiceFabricEncryptedText'.
2018-09-26T17:05:52.4138596Z ##[debug]Exporting variable 'SF_Operations'.
2018-09-26T17:05:52.4154629Z ##[debug]Exporting function 'Publish-Telemetry'.
2018-09-26T17:05:52.4155784Z ##[debug]Exporting function 'Get-SfSdkVersion'.
2018-09-26T17:05:52.4156290Z ##[debug]Importing function 'Connect-ServiceFabricClusterFromServiceEndpoint'.
2018-09-26T17:05:52.4156865Z ##[debug]Importing function 'Get-ServiceFabricEncryptedText'.
2018-09-26T17:05:52.4166488Z ##[debug]Importing function 'Get-SfSdkVersion'.
2018-09-26T17:05:52.4184179Z ##[debug]Importing function 'Publish-Telemetry'.
2018-09-26T17:05:52.4203514Z ##[debug]Importing function 'Remove-ClientCertificate'.
2018-09-26T17:05:52.4219612Z ##[debug]Importing variable 'SF_Operations'.
2018-09-26T17:05:52.4244746Z ##[debug]Loading module from path 'D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.21\ps_modules\PowershellHelpers\PowershellHelpers.psm1'.
2018-09-26T17:05:52.4304119Z ##[debug]Loading resource strings from: D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.21\ps_modules\PowershellHelpers\module.json
2018-09-26T17:05:52.4409677Z ##[debug]Loaded 3 strings.
2018-09-26T17:05:52.4439525Z ##[debug]SYSTEM_CULTURE: 'en-US'
2018-09-26T17:05:52.4461004Z ##[debug]Loading resource strings from: D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.21\ps_modules\PowershellHelpers\Strings\resources.resjson\en-US\resources.resjson
2018-09-26T17:05:52.4567635Z ##[debug]Loaded 3 strings.
2018-09-26T17:05:52.4623084Z ##[debug]Exporting function 'Invoke-ActionWithRetries'.
2018-09-26T17:05:52.4674745Z ##[debug]Exporting function 'Get-TempDirectoryPath'.
2018-09-26T17:05:52.4683907Z ##[debug]Importing function 'Get-TempDirectoryPath'.
2018-09-26T17:05:52.4684469Z ##[debug]Importing function 'Invoke-ActionWithRetries'.
2018-09-26T17:05:52.5287163Z ##[debug]INPUT_PUBLISHPROFILEPATH: 'D:\a\r1\a\**\drop\projectartifacts\**\PublishProfiles\Cloud.xml'
2018-09-26T17:05:52.5371872Z Searching for path: D:\a\r1\a\**\drop\projectartifacts\**\PublishProfiles\Cloud.xml
2018-09-26T17:05:52.5395081Z ##[debug]Entering Find-VstsFiles.
2018-09-26T17:05:52.5414983Z ##[debug] LegacyPattern: 'D:\a\r1\a\**\drop\projectartifacts\**\PublishProfiles\Cloud.xml'
2018-09-26T17:05:52.5447009Z ##[debug]Entering Get-MatchingItems.
2018-09-26T17:05:52.5467028Z ##[debug] IncludePatterns: 'D:\a\r1\a\**\drop\projectartifacts\**\PublishProfiles\Cloud.xml'
2018-09-26T17:05:52.5487320Z ##[debug] ExcludePatterns: ''
2018-09-26T17:05:52.5506739Z ##[debug] IncludeFiles: 'True'
2018-09-26T17:05:52.5526892Z ##[debug] IncludeDirectories: 'False'
2018-09-26T17:05:52.5549267Z ##[debug] Force: 'False'
2018-09-26T17:05:53.0085268Z ##[debug]Path: D:\a\r1\a\_Testicide-Azure Service Fabric application-CI\drop\projectartifacts\src\Testicide\PublishProfiles\Cloud.xml
2018-09-26T17:05:53.0129759Z ##[debug]Leaving Get-MatchingItems.
2018-09-26T17:05:53.0149208Z ##[debug]Total found: 1
2018-09-26T17:05:53.0171566Z ##[debug]Leaving Find-VstsFiles.
2018-09-26T17:05:53.0373883Z ##[debug]Asserting leaf path exists: 'D:\a\r1\a\_Testicide-Azure Service Fabric application-CI\drop\projectartifacts\src\Testicide\PublishProfiles\Cloud.xml'
2018-09-26T17:05:53.0387843Z Found path: D:\a\r1\a\_Testicide-Azure Service Fabric application-CI\drop\projectartifacts\src\Testicide\PublishProfiles\Cloud.xml
2018-09-26T17:05:53.1691658Z ##[debug]INPUT_APPLICATIONPACKAGEPATH: 'D:\a\r1\a\**\drop\applicationpackage'
2018-09-26T17:05:53.1703868Z Searching for path: D:\a\r1\a\**\drop\applicationpackage
2018-09-26T17:05:53.1727145Z ##[debug]Entering Find-VstsFiles.
2018-09-26T17:05:53.1748056Z ##[debug] LegacyPattern: 'D:\a\r1\a\**\drop\applicationpackage'
2018-09-26T17:05:53.1768149Z ##[debug] IncludeDirectories: 'True'
2018-09-26T17:05:53.1799901Z ##[debug]Entering Get-MatchingItems.
2018-09-26T17:05:53.1820118Z ##[debug] IncludePatterns: 'D:\a\r1\a\**\drop\applicationpackage'
2018-09-26T17:05:53.1842078Z ##[debug] ExcludePatterns: ''
2018-09-26T17:05:53.1862203Z ##[debug] IncludeFiles: 'False'
2018-09-26T17:05:53.1882600Z ##[debug] IncludeDirectories: 'True'
2018-09-26T17:05:53.1902552Z ##[debug] Force: 'False'
2018-09-26T17:05:53.5403280Z ##[debug]Path: D:\a\r1\a\_Testicide-Azure Service Fabric application-CI\drop\applicationpackage
2018-09-26T17:05:53.5423159Z ##[debug]Leaving Get-MatchingItems.
2018-09-26T17:05:53.5443407Z ##[debug]Total found: 1
2018-09-26T17:05:53.5465524Z ##[debug]Leaving Find-VstsFiles.
2018-09-26T17:05:53.5486387Z ##[debug]Asserting container path exists: 'D:\a\r1\a\_Testicide-Azure Service Fabric application-CI\drop\applicationpackage'
2018-09-26T17:05:53.5498932Z Found path: D:\a\r1\a\_Testicide-Azure Service Fabric application-CI\drop\applicationpackage
2018-09-26T17:05:53.5531890Z ##[debug]INPUT_SERVICECONNECTIONNAME: '9c1d7c88-19c0-477d-8c21-0a8886294aff'
2018-09-26T17:05:53.5659661Z ##[debug]ENDPOINT_URL_9c1d7c88-19c0-477d-8c21-0a8886294aff: 'tcp://testicidecluster.westeurope.cloudapp.azure.com:19000/'
2018-09-26T17:05:53.5686937Z ##[debug]ENDPOINT_AUTH_9c1d7c88-19c0-477d-8c21-0a8886294aff: '********'
2018-09-26T17:05:53.5731137Z ##[debug]ENDPOINT_DATA_9c1d7c88-19c0-477d-8c21-0a8886294aff: '{}'
2018-09-26T17:05:53.5764399Z ##[debug]INPUT_COPYPACKAGETIMEOUTSEC (empty)
2018-09-26T17:05:53.5810631Z ##[debug]INPUT_REGISTERPACKAGETIMEOUTSEC (empty)
2018-09-26T17:05:53.5836937Z ##[debug]INPUT_COMPRESSPACKAGE: 'true'
2018-09-26T17:05:53.5878699Z ##[debug]INPUT_SKIPUPGRADESAMETYPEANDVERSION: 'true'
2018-09-26T17:05:53.5903045Z ##[debug]INPUT_SKIPPACKAGEVALIDATION: 'false'
2018-09-26T17:05:53.5928827Z ##[debug]INPUT_UNREGISTERUNUSEDVERSIONS: 'true'
2018-09-26T17:05:53.5952851Z ##[debug]INPUT_CONFIGUREDOCKERSETTINGS: 'false'
2018-09-26T17:05:53.5978713Z ##[debug]INPUT_OVERRIDEAPPLICATIONPARAMETER: 'false'
2018-09-26T17:05:53.6139439Z ##[debug]Entering Connect-ServiceFabricClusterFromServiceEndpoint.
2018-09-26T17:05:53.6176083Z ##[debug] ClusterConnectionParameters: 'System.Collections.Hashtable'
2018-09-26T17:05:53.6211979Z ##[debug] ConnectedServiceEndpoint: '@{Url=tcp://testicidecluster.westeurope.cloudapp.azure.com:19000/; Data=; Auth=}'
2018-09-26T17:05:53.6238043Z ##[debug]Loading module from path 'D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.21\ps_modules\TlsHelper_\TlsHelper_.psm1'.
2018-09-26T17:05:53.6307047Z ##[debug]Loading resource strings from: D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.21\ps_modules\TlsHelper_/module.json
2018-09-26T17:05:53.6408385Z ##[debug]Loaded 3 strings.
2018-09-26T17:05:53.6438790Z ##[debug]SYSTEM_CULTURE: 'en-US'
2018-09-26T17:05:53.6459864Z ##[debug]Loading resource strings from: D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.21\ps_modules\TlsHelper_\Strings\resources.resjson\en-US\resources.resjson
2018-09-26T17:05:53.6557942Z ##[debug]Loaded 3 strings.
2018-09-26T17:05:53.6577704Z ##[debug]Exporting function 'Add-Tls12InSession'.
2018-09-26T17:05:53.6594601Z ##[debug]Exporting function 'Assert-TlsError'.
2018-09-26T17:05:53.6615976Z ##[debug]Importing function 'Add-Tls12InSession'.
2018-09-26T17:05:53.6641023Z ##[debug]Importing function 'Assert-TlsError'.
2018-09-26T17:05:53.6666406Z ##[debug]Importing function 'Get-TempDirectoryPath'.
2018-09-26T17:05:53.6683275Z ##[debug]Importing function 'Invoke-ActionWithRetries'.
2018-09-26T17:05:54.1686649Z ##[debug]TLS 1.2 already present in session.
2018-09-26T17:06:58.1888812Z ##[debug]System.AggregateException: One or more errors occurred. ---> System.Fabric.FabricTransientException: Could not ping any of the provided Service Fabric gateway endpoints. ---> System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x80071C49
2018-09-26T17:06:58.1902063Z ##[debug]   at System.Fabric.Interop.NativeClient.IFabricPropertyManagementClient2.EndNameExists(IFabricAsyncOperationContext context)
2018-09-26T17:06:58.1915073Z ##[debug]   at System.Fabric.FabricClient.PropertyManagementClient.NameExistsEndWrapper(IFabricAsyncOperationContext context)
2018-09-26T17:06:58.1928288Z ##[debug]   at System.Fabric.Interop.AsyncCallOutAdapter2`1.Finish(IFabricAsyncOperationContext context, Boolean expectedCompletedSynchronously)
2018-09-26T17:06:58.1941168Z ##[debug]   --- End of inner exception stack trace ---
2018-09-26T17:06:58.1954610Z ##[debug]   --- End of inner exception stack trace ---
2018-09-26T17:06:58.1967246Z ##[debug]   at Microsoft.ServiceFabric.Powershell.ClusterConnection.InitializeClaimsMetadata(TimeSpan timeout)
2018-09-26T17:06:58.1980393Z ##[debug]   at Microsoft.ServiceFabric.Powershell.ConnectCluster.ProcessRecord()
2018-09-26T17:06:58.1995257Z ##[debug]---> (Inner Exception #0) System.Fabric.FabricTransientException: Could not ping any of the provided Service Fabric gateway endpoints. ---> System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x80071C49
2018-09-26T17:06:58.2007860Z ##[debug]   at System.Fabric.Interop.NativeClient.IFabricPropertyManagementClient2.EndNameExists(IFabricAsyncOperationContext context)
2018-09-26T17:06:58.2020715Z ##[debug]   at System.Fabric.FabricClient.PropertyManagementClient.NameExistsEndWrapper(IFabricAsyncOperationContext context)
2018-09-26T17:06:58.2034497Z ##[debug]   at System.Fabric.Interop.AsyncCallOutAdapter2`1.Finish(IFabricAsyncOperationContext context, Boolean expectedCompletedSynchronously)
2018-09-26T17:06:58.2047303Z ##[debug]   --- End of inner exception stack trace ---<---
2018-09-26T17:06:58.2060516Z ##[debug]
2018-09-26T17:06:58.2888840Z ##[debug]System.Management.Automation.PipelineStoppedException: The pipeline has been stopped.
2018-09-26T17:06:58.2900747Z ##[debug]   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
2018-09-26T17:06:58.2913896Z ##[debug]   at System.Management.Automation.Cmdlet.ThrowTerminatingError(ErrorRecord errorRecord)
2018-09-26T17:06:58.2926290Z ##[debug]   at Microsoft.ServiceFabric.Powershell.ConnectCluster.ProcessRecord()
2018-09-26T17:07:58.4559678Z ##[debug]System.AggregateException: One or more errors occurred. ---> System.Fabric.FabricTransientException: Could not ping any of the provided Service Fabric gateway endpoints. ---> System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x80071C49
2018-09-26T17:07:58.4581189Z ##[debug]   at System.Fabric.Interop.NativeClient.IFabricPropertyManagementClient2.EndNameExists(IFabricAsyncOperationContext context)
2018-09-26T17:07:58.4601101Z ##[debug]   at System.Fabric.FabricClient.PropertyManagementClient.NameExistsEndWrapper(IFabricAsyncOperationContext context)
2018-09-26T17:07:58.4617506Z ##[debug]   at System.Fabric.Interop.AsyncCallOutAdapter2`1.Finish(IFabricAsyncOperationContext context, Boolean expectedCompletedSynchronously)
2018-09-26T17:07:58.4631511Z ##[debug]   --- End of inner exception stack trace ---
2018-09-26T17:07:58.4651091Z ##[debug]   --- End of inner exception stack trace ---
2018-09-26T17:07:58.4664922Z ##[debug]   at Microsoft.ServiceFabric.Powershell.ClusterConnection.InitializeClaimsMetadata(TimeSpan timeout)
2018-09-26T17:07:58.4678975Z ##[debug]   at Microsoft.ServiceFabric.Powershell.ConnectCluster.ProcessRecord()
2018-09-26T17:07:58.4692566Z ##[debug]---> (Inner Exception #0) System.Fabric.FabricTransientException: Could not ping any of the provided Service Fabric gateway endpoints. ---> System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x80071C49
2018-09-26T17:07:58.4705652Z ##[debug]   at System.Fabric.Interop.NativeClient.IFabricPropertyManagementClient2.EndNameExists(IFabricAsyncOperationContext context)
2018-09-26T17:07:58.4726651Z ##[debug]   at System.Fabric.FabricClient.PropertyManagementClient.NameExistsEndWrapper(IFabricAsyncOperationContext context)
2018-09-26T17:07:58.4737310Z ##[debug]   at System.Fabric.Interop.AsyncCallOutAdapter2`1.Finish(IFabricAsyncOperationContext context, Boolean expectedCompletedSynchronously)
2018-09-26T17:07:58.4743310Z ##[debug]   --- End of inner exception stack trace ---<---
2018-09-26T17:07:58.4757820Z ##[debug]
2018-09-26T17:07:58.4781430Z ##[debug]System.Management.Automation.PipelineStoppedException: The pipeline has been stopped.
2018-09-26T17:07:58.4796505Z ##[debug]   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
2018-09-26T17:07:58.4809238Z ##[debug]   at System.Management.Automation.Cmdlet.ThrowTerminatingError(ErrorRecord errorRecord)
2018-09-26T17:07:58.4826465Z ##[debug]   at Microsoft.ServiceFabric.Powershell.ConnectCluster.ProcessRecord()
2018-09-26T17:07:58.5516731Z ##[debug]Leaving Connect-ServiceFabricClusterFromServiceEndpoint.
2018-09-26T17:07:58.5890666Z ##[debug]SYSTEM_JOBID: 'a5c17f25-04bd-46ec-8738-234c13bdc9cc'
2018-09-26T17:07:58.5981834Z Service fabric SDK version: 3.2.162.9494.
2018-09-26T17:07:58.9846421Z ##[debug]Processed: ##vso[telemetry.publish area=TaskHub;feature=ServiceFabricDeploy]{"OperationId":"ConnectClusterMetadata","ExceptionData":"System.Fabric.FabricTransientException;|D:\\a\\_tasks\\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\\1.7.21\\ps_modules\\ServiceFabricHelpers\\Connect-ServiceFabricClusterFromServiceEndpoint.ps1|251","JobId":"a5c17f25-04bd-46ec-8738-234c13bdc9cc","SDKVersion":"3.2.162.9494"}
2018-09-26T17:07:58.9847332Z ##[debug]Leaving D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.21\deploy.ps1.
2018-09-26T17:07:59.1009286Z ##[debug]Caught exception from task script.
2018-09-26T17:07:59.1043447Z ##[debug]Error record:
2018-09-26T17:07:59.1872690Z ##[debug]Connect-ServiceFabricCluster : One or more errors occurred.
2018-09-26T17:07:59.1884424Z ##[debug]At D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.21\ps_modules\ServiceFabricHelpers\Connect-ServiceFabricClusterFromServiceEndpoint.ps1:251 char:28
2018-09-26T17:07:59.1898115Z ##[debug]+ ... tAction = { Connect-ServiceFabricCluster @clusterConnectionParameters ...
2018-09-26T17:07:59.1910624Z ##[debug]+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2018-09-26T17:07:59.1927237Z ##[debug]    + CategoryInfo          : NotSpecified: (:) [Connect-ServiceFabricCluster], AggregateException
2018-09-26T17:07:59.1938642Z ##[debug]    + FullyQualifiedErrorId : CreateClusterConnectionErrorId,Microsoft.ServiceFabric.Powershell.ConnectCluster
2018-09-26T17:07:59.1952973Z ##[debug] 
2018-09-26T17:07:59.1975240Z ##[debug]Script stack trace:
2018-09-26T17:07:59.2039552Z ##[debug]at <ScriptBlock>, D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.21\ps_modules\ServiceFabricHelpers\Connect-ServiceFabricClusterFromServiceEndpoint.ps1: line 251
2018-09-26T17:07:59.2040508Z ##[debug]at Invoke-ActionWithRetries, D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.21\ps_modules\PowershellHelpers\Helpers.ps1: line 39
2018-09-26T17:07:59.2044214Z ##[debug]at Connect-ServiceFabricClusterAction, D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.21\ps_modules\ServiceFabricHelpers\Connect-ServiceFabricClusterFromServiceEndpoint.ps1: line 252
2018-09-26T17:07:59.2077371Z ##[debug]at Get-AadSecurityToken, D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.21\ps_modules\ServiceFabricHelpers\Connect-ServiceFabricClusterFromServiceEndpoint.ps1: line 30
2018-09-26T17:07:59.2078944Z ##[debug]at Connect-ServiceFabricClusterFromServiceEndpoint, D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.21\ps_modules\ServiceFabricHelpers\Connect-ServiceFabricClusterFromServiceEndpoint.ps1: line 181
2018-09-26T17:07:59.2093671Z ##[debug]at <ScriptBlock>, D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.21\deploy.ps1: line 59
2018-09-26T17:07:59.2282532Z ##[debug]at <ScriptBlock>, <No file>: line 1
2018-09-26T17:07:59.2295667Z ##[debug]at <ScriptBlock>, <No file>: line 22
2018-09-26T17:07:59.2309102Z ##[debug]at <ScriptBlock>, <No file>: line 18
2018-09-26T17:07:59.2321939Z ##[debug]at <ScriptBlock>, <No file>: line 1
2018-09-26T17:07:59.2345929Z ##[debug]Exception:
2018-09-26T17:07:59.2393268Z ##[debug]System.AggregateException: One or more errors occurred. ---> System.Fabric.FabricTransientException: Could not ping any of the provided Service Fabric gateway endpoints. ---> System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x80071C49
2018-09-26T17:07:59.2405182Z ##[debug]   at System.Fabric.Interop.NativeClient.IFabricPropertyManagementClient2.EndNameExists(IFabricAsyncOperationContext context)
2018-09-26T17:07:59.2418936Z ##[debug]   at System.Fabric.FabricClient.PropertyManagementClient.NameExistsEndWrapper(IFabricAsyncOperationContext context)
2018-09-26T17:07:59.2431540Z ##[debug]   at System.Fabric.Interop.AsyncCallOutAdapter2`1.Finish(IFabricAsyncOperationContext context, Boolean expectedCompletedSynchronously)
2018-09-26T17:07:59.2444439Z ##[debug]   --- End of inner exception stack trace ---
2018-09-26T17:07:59.2458152Z ##[debug]   --- End of inner exception stack trace ---
2018-09-26T17:07:59.2470212Z ##[debug]   at Microsoft.ServiceFabric.Powershell.ClusterConnection.InitializeClaimsMetadata(TimeSpan timeout)
2018-09-26T17:07:59.2483505Z ##[debug]   at Microsoft.ServiceFabric.Powershell.ConnectCluster.ProcessRecord()
2018-09-26T17:07:59.2496596Z ##[debug]---> (Inner Exception #0) System.Fabric.FabricTransientException: Could not ping any of the provided Service Fabric gateway endpoints. ---> System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x80071C49
2018-09-26T17:07:59.2509550Z ##[debug]   at System.Fabric.Interop.NativeClient.IFabricPropertyManagementClient2.EndNameExists(IFabricAsyncOperationContext context)
2018-09-26T17:07:59.2522626Z ##[debug]   at System.Fabric.FabricClient.PropertyManagementClient.NameExistsEndWrapper(IFabricAsyncOperationContext context)
2018-09-26T17:07:59.2534417Z ##[debug]   at System.Fabric.Interop.AsyncCallOutAdapter2`1.Finish(IFabricAsyncOperationContext context, Boolean expectedCompletedSynchronously)
2018-09-26T17:07:59.2547592Z ##[debug]   --- End of inner exception stack trace ---<---
2018-09-26T17:07:59.2559852Z ##[debug]
2018-09-26T17:07:59.2885225Z ##[error]One or more errors occurred.
2018-09-26T17:07:59.2896820Z ##[debug]Processed: ##vso[task.logissue type=error]One or more errors occurred.
2018-09-26T17:07:59.2898222Z ##[debug]Processed: ##vso[task.complete result=Failed]
2018-09-26T17:07:59.5557311Z ##[section]Finishing: Deploy Service Fabric Application

**Comment by washraf** [comment]
and till now i am unable to deploy.

**Comment by bishal-pdMSFT** [comment]
Looks like the task is not able to connect to cluster endpoint. Have you used correct cluster endpoint url in the VSTS service endpoint? You can run following powershell command to see if it connects(this will require you to install service fabric SDK on the machine where you are running the command):
`Connect-ServiceFabricCluster -ConnectionEndpoint <cluster-endpoint-url-without-tcp://> -GetMetadata`

**Comment by washraf** [comment]
I very sorry. the mistake was that i added the certificate 64 byte value incorrectly. Thanks very much
