### ISSUE TITLE
grunt build failing with invalid grunt: null

### ISSUE THREAD

**Issue by hspain** [Microsoft/vsts-tasks#906]
I have a build that was working great using the windows execution route in the tasks added as steps, but recently started trying to use the Node path for no apparent reason.  This is causing a ripple effect of errors.

Short question: is there a way to force the use of the PowerShell execution path for tasks?

**Comment by bryanmacfarlane** [comment]
Yes!  And we added it because teams need a way to ease the change through.

See the ant task as an example: https://github.com/Microsoft/vso-agent-tasks/blob/master/Tasks/ANT/task.json 

Look in the execution, powershell section and not how it's 'pinned' for windows.

But be aware, that's a temporary solution as the goal should be to have one implementation.  If it's a cross platform task (which if you have two implementations, I gather it is), then JS is the solution for xplat tasks.  The windows agent is now capable of running js implementations which was the shortcoming of why folks had to have two implementations.

What task do you have?  A customer one or some xplat tool?

**Comment by hspain** [comment]
This is happening specifically with the npm and grunt tasks.

**Comment by hspain** [comment]
Thanks, btw!

**Comment by bryanmacfarlane** [comment]
OK, I would be very interested in what the ripple effect of errors was - the intent was to push those specific tasks to one implementation.  Those aren't pinned to windows.

If you could elaborate on the issues, I'm very interested in addressed.

We know of one potential issue with grunt ...

**Comment by hspain** [comment]
Below is the log from the Grunt task.  When this was running with PowerShell, I had no issues with this task.

```
2015-11-30T21:28:21.5475706Z Set workingFolder to default: C:\agent-internal\tasks\Grunt\0.5.3
2015-11-30T21:28:21.5475706Z Prepare node module: vso-task-lib version: Latest Version for task script at workingFolder: C:\agent-internal\tasks\Grunt\0.5.3\node_modules\vso-task-lib.
2015-11-30T21:28:21.5475706Z Reuse junction point from C:\agent-internal\tasks\Grunt\0.5.3\node_modules\vso-task-lib to C:\agent-internal\modules\vso-task-lib\0.4.5.
2015-11-30T21:28:21.9069850Z ##[debug]check path : null
2015-11-30T21:28:21.9225700Z ##[error]invalid grunt: null
2015-11-30T21:28:21.9225700Z ##[debug]task result: Failed
2015-11-30T21:28:21.9383095Z ##[debug]grunt=null
2015-11-30T21:28:21.9383095Z ##[debug]targets=bower:install
2015-11-30T21:28:21.9383095Z ##[error]child_process.js:1136
2015-11-30T21:28:21.9383095Z ##[error]  var err = this._handle.spawn(options);
2015-11-30T21:28:21.9383095Z ##[error]                         ^
2015-11-30T21:28:21.9383095Z ##[error]TypeError: Bad argument
2015-11-30T21:28:21.9383095Z ##[error]    at TypeError (native)
2015-11-30T21:28:21.9383095Z ##[error]    at ChildProcess.spawn (child_process.js:1136:26)
2015-11-30T21:28:21.9383095Z ##[error]    at Object.exports.spawn (child_process.js:995:9)
2015-11-30T21:28:21.9383095Z ##[error]    at ToolRunner.exec (C:\agent-internal\modules\vso-task-lib\0.4.5\lib\toolrunner.js:91:24)
2015-11-30T21:28:21.9383095Z ##[error]    at Object.<anonymous> (C:\agent-internal\tasks\Grunt\0.5.3\grunttask.js:21:4)
2015-11-30T21:28:21.9383095Z ##[error]    at Module._compile (module.js:460:26)
2015-11-30T21:28:21.9383095Z ##[error]    at Object.Module._extensions..js (module.js:478:10)
2015-11-30T21:28:21.9383095Z ##[error]    at Module.load (module.js:355:32)
2015-11-30T21:28:21.9383095Z ##[error]    at Function.Module._load (module.js:310:12)
2015-11-30T21:28:21.9538174Z ##[error]    at Function.Module.runMain (module.js:501:10)
2015-11-30T21:28:21.9538174Z ##[debug]gruntFile=c:\Builds-Internal\5\s\Portal.Client\Gruntfile.js
2015-11-30T21:28:21.9538174Z ##[debug]arguments=--verbose
2015-11-30T21:28:21.9538174Z ##[debug]cwd=c:\Builds-Internal\5\s\Portal.Client
2015-11-30T21:28:21.9538174Z [command]null bower:install --gruntfile c:\Builds-Internal\5\s\Portal.Client\Gruntfile.js --verbose
```

**Comment by bryanmacfarlane** [comment]
OK - yes, that's the issue we know about.  Adding Ting to this thread

The issue is if you are running your own agent and grunt-cli -g install is not in the path of the account that is running your agent.  grunt-cli

2015-11-30T21:28:21.9069850Z ##[debug]check path : null
2015-11-30T21:28:21.9225700Z ##[error]invalid grunt: null

On the hosted pool, grunt should be in the path.  

Can you confirm it's your own agent and not grunt?

We are fixing it right now.

**Comment by hspain** [comment]
I am running an NPM install for grunt-cli in a prior task.  This succeeds, though it is also running through Node now instead of PowerShell.

```
2015-11-30T21:27:35.9857604Z Set workingFolder to default: C:\agent-internal\tasks\Npm\0.2.0
2015-11-30T21:27:35.9857604Z Prepare node module: vso-task-lib version: Latest Version for task script at workingFolder: C:\agent-internal\tasks\Npm\0.2.0\node_modules\vso-task-lib.
2015-11-30T21:27:35.9857604Z Reuse junction point from C:\agent-internal\tasks\Npm\0.2.0\node_modules\vso-task-lib to C:\agent-internal\modules\vso-task-lib\0.4.5.
2015-11-30T21:27:36.3917703Z ##[debug]check path : C:\Program Files\nodejs\npm.cmd
2015-11-30T21:27:36.3917703Z ##[debug]npm=C:\Program Files\nodejs\npm.cmd
2015-11-30T21:27:36.3917703Z ##[debug]command=install
2015-11-30T21:27:36.3917703Z ##[debug]arguments=-g grunt-cli
2015-11-30T21:27:36.3917703Z ##[debug]cwd=c:\Builds-Internal\5\s\Portal.Client
2015-11-30T21:27:36.3917703Z [command]C:\Program Files\nodejs\npm.cmd install -g grunt-cli
2015-11-30T21:27:39.6730883Z npm WARN deprecated lodash@2.4.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0.
2015-11-30T21:27:40.1105544Z C:\Users\tfsservice\AppData\Roaming\npm\grunt -> C:\Users\tfsservice\AppData\Roaming\npm\node_modules\grunt-cli\bin\grunt
2015-11-30T21:27:40.2667792Z C:\Users\tfsservice\AppData\Roaming\npm
2015-11-30T21:27:40.2667792Z ΓööΓöÇΓöÇ grunt-cli@0.1.13 
2015-11-30T21:27:40.2980493Z ##[debug]task result: Succeeded
```

**Comment by bryanmacfarlane** [comment]
OK - for npm, that's expected - we are collapsing node and other tasks to one implementation (js).

For grunt issue, can you confirm whether you have your own agent (VM) or whether you are using the hosted pool?  I would only expect it to fail on the former depending on path settings

**Comment by hspain** [comment]
I am using my own agent.  Do you know why it would change suddenly?

**Comment by bryanmacfarlane** [comment]
Yes, grunt -g installs globally on the machine.  When you install node & npm there's an option to add the path where it installs global tools to the path.  but, it alters the path of the installing user.  If you don't run the windows agent as that user (likely since default is network service), then it's not in your path.  On hosted pool images (and our test machines) it's in the path.  the node implementation does which (like where) on grunt and that's null.  The ps1 implementation did not do which but scanned.

**Comment by bryanmacfarlane** [comment]
one more thing on 'suddenly' - agents are automatically upgraded on restart, when tasks demand etc... So, that's the sudden part.

**Comment by hspain** [comment]
Thank you for all your help.  It builds now on my end.

**Comment by bryanmacfarlane** [comment]
Cool - just to confirm - did you end up altering the path?

I might leave the issue open for a few days to see if we get other hits due to the change

**Comment by hspain** [comment]
Yes, I added the service user's NPM folder to the path.

**Comment by bryanmacfarlane** [comment]
Thanks for confirming,
